### ISSUE TITLE
unable to connect to RDS (aws) in node.js 6.0

### ISSUE THREAD

**Issue by holmok** [brianc/node-postgres#1003]
When attempting to connect to an RDS instance in AWS I am getting failed to authenticate errors in node 6.0.  I reverted back to 5.11.0 and it resolved the issue. My guess is the SSL/TLS stuff.

**Comment by vitaly-t** [comment]
@holmok have you seen [this](https://github.com/brianc/node-postgres/issues/1000), and have you upgraded to 4.5.5 yet?

**Comment by holmok** [comment]
there you go.  thanks that resolves it.

**Comment by vitaly-t** [comment]
No problem. Please close the issue ;)
