### ISSUE TITLE
"alter role with password" - syntax error

### ISSUE THREAD

**Issue by cherryliu** [brianc/node-postgres#1004]
Hi,

I was using 

client.query("ALTER ROLE john WITH PASSWORD $1",[new_password], function(err, result) { ...});
where new_password was passed as a variable, e.g. var new_password='abc';

It returns a 'syntax error near $1' - anything to do with escaping the string? I tried not passing the new password as a variable, but inside the query text instead, and that works fine. But I'd like to have it input from the user. How should that be done?

**Comment by brianc** [comment]
`ALTER ROLE __ WITH PASSWORD` is not a query, its a special postgres
statement. Postgres doesn't support parameters in these statements, you
have to pass it as plain text in the query.
