### ISSUE TITLE
Best way to handle hitting the wrong kind of server?

### ISSUE THREAD

**Issue by dhalden** [brianc/node-postgres#1005]
I'm writing a program that needs to be able to access multiple different kinds of databases. Because of this I was testing under some interesting conditions, and I ended up trying to connect to a MySQL database with the postgres library. It errors, and not only errors, but also crashes the program I set up to listen for these calls.

``````
/Users/Shazam/node_modules/pg/lib/connection.js:109
      self.emit(msg.name, msg);
                   ^

TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (/Users/Shazam/node_modules/pg/lib/connection.js:109:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)```

Is there a way I can handle this that doesn't involve the module crashing my listener?
``````

**Comment by vitaly-t** [comment]
>Is there a way I can handle this that doesn't involve the module crashing my listener?

Yes, you can order your connection config so it doesn't try to use a PostgreSQL driver to connect to MySQL.

I wouldn't expect anyone changing the PostgreSQL driver following your application bugs.

It was designed to be functionally solid, but not fool-proof.

**Comment by langpavel** [comment]
@vitaly-t sure, but @dhalden not crashing entire application is reasonable request..

**Comment by brianc** [comment]
Oofff! hitting parsing errors like that is a hard one.  I can look into it
but thats a white-hot code path and i'd really hate to put a try/catch
around it. Not to mention this is the first bug report in the six years
since ive written this lib around that!

I can take a look and see if Im actually throwing the error - in that case
i can do something about it. I can check this out when i get some time but
its not high priority for me. Alternatively, If you want to submit a PR i
will happily review it! :)

**Comment by langpavel** [comment]
@brianc absolutely agree on hot paths and try/catch. But is there some higher function on stack where this can be done? Btw for v8 engine - there is performance impact only for inline code. You can prevent deoptimization by wrapping working stuff to separate function and try/catch on one level up..

**Comment by langpavel** [comment]
I know there is also lot of sync stuff. Can be solved by domains? I think you already using domains.

**Comment by langpavel** [comment]
Meaning async of course, smartphone is not smart enough ;-)

**Comment by SegFaultx64** [comment]
I don't think domains are the right choice here. I think the correct choice is just to attach a `process.on('uncaughtException')` handler and then exit on anything except the one you are trying to catch. 

This is definitely janky but I think it is better than screwing up hotspot optimization.

**Comment by langpavel** [comment]
@SegFaultx64 Hmm, `process.on('uncaughtException')` is one of most dangerous APIs in node, but I agree, if domains will be used, it is the same result. But I think domains are already introduced there, I'm wrong?

**Comment by brianc** [comment]
Connecting to a backend that isn't PostgreSQL isn't supported.
