### ISSUE TITLE
Number array parameter parsed as string array

### ISSUE THREAD

**Issue by camsteffen** [brianc/node-postgres#1008]
I am not able to use an array of numbers as a parameter

```javascript
var keep = [1, 2, 3]

// this does not work
client.query('delete from foo where key_one=$1 and key_two not in($2)', [id, keep], function(err, result) {
    // handle result
})
```

gives this error

`invalid input syntax for integer: "{"1","2","3"}"`

**Comment by brianc** [comment]
Your query is formed wrong - you have to build the inlint clause yourself. There are multiple other closed issues on this repo w/ the same issue.

**Comment by camsteffen** [comment]
@brianc Thanks for your response. I tired searching and couldn't find anything similar so maybe I wasn't searching for the right thing. If I can use an array of strings, why can't I also use an array of numbers? Wouldn't this be fairly simple to implement? It should at least work by specifying the parameter type as in `$2::int`.

**Comment by brianc** [comment]
A quick google produced this:

http://www.postgresql.org/message-id/1187290651.24679.10.camel@dogma.ljc.laika.com

**Comment by camsteffen** [comment]
That thread is about functions and not queries. I don't mean to be belligerent but do you have an answer to my question? Why is there support for a string array parameter but not a number array?

**Comment by camsteffen** [comment]
I figured it out. My query was formed wrong but it is actually possible to use a number array as a parameter.

var keep = [1, 2, 3]
client.query('delete from foo where key_one=$1 and not key_two = any($2)', [id, keep], function(err, result) {
    // handle result
})

**Comment by oncletom** [comment]
@camsteffen you mean is replacing `field IN (<array_of_int>)` by `field = ANY(<array_of_int>)` is what makes it work? Very subtle. Thank you :-)
