### ISSUE TITLE
Advanced properties in `Query`

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1009]
Which of the advanced `Query` properties are applicable to Prepared Statements, and which ones are applicable to Parameterized Queries?
- `binary`
- `portal`
- `rowMode`
- `rows`
- `stream`
- `types`

I want to wrap each Prepared Statement and Parameterized Query into two separate classes, and I want to support only the properties that are applicable within the right context.

Current documentation doesn't explain the meaning of these advanced properties to figure out which ones can be used where.

**Comment by pdiniz13** [comment]
Some documentation explaining what these properties are and how to use them would be very helpful. It would also help us to plan ahead in case you are looking to deprecate any of them moving forward.

**Comment by vitaly-t** [comment]
I will be writing here with updates, the results of my own investigation into this...

---

### binary
According to [this](https://github.com/brianc/node-postgres/blob/master/lib/defaults.js#L21), it is `binary result mode`. I have tried to set it and look for any changes, but none found yet.

### portal
No idea what it is and how it is supposed to work. However, looking [at the code](https://github.com/brianc/node-postgres/blob/master/lib/query.js#L21)  makes me think it doesn't work at all, because in the constructor it is set as `portal`, while everywhere later it is used as `portalName` - is this a bug?

### rowMode
Changes the way rows are delivered to the client. Setting to string `array` changes the result into array of arrays, as opposed to arrays of objects. Not sure if there is any other meaning or value for it.

### rows
According to [this](https://github.com/brianc/node-postgres/blob/master/lib/defaults.js#L19), `number of rows to return at a time from a prepared statement's portal. 0 will return all rows at once`.

Does this mean it is not used for Parameterized Queries?
