### ISSUE TITLE
Unref method so that Node process can terminate if there are no pending queries

### ISSUE THREAD

**Issue by olalonde** [brianc/node-postgres#1015]
It would be useful to have an unref method on Client instances so that Node can terminate if there are no pending queries.

**Comment by olalonde** [comment]
Just wrote this as a quick fix:

```javascript
const patchClient = (client) => {
  const connect = client.connect.bind(client)
  const query = client.query.bind(client)
  let refCount = 0

  const ref = () => {
    refCount++
    client.connection.stream.ref()
  }
  const unref = () => {
    refCount--
    if (!refCount) client.connection.stream.unref()
  }

  const wrap = (fn) => (...args) => {
    ref()
    const lastArg = args[args.length - 1]
    const lastArgIsCb = typeof lastArg === 'function'
    const outerCb = lastArgIsCb ? lastArg : noop
    if (lastArgIsCb) args.pop()
    const cb = (...cbArgs) => {
      unref()
      outerCb(...cbArgs)
    }
    args.push(cb)
    return fn(...args)
  }

  client.connect = wrap(connect)
  client.query = wrap(query)
  return client
}
```

seems to work... but needs more testing.

**Comment by vitaly-t** [comment]
Node can always terminate when there are no pending queries.

But if you are using the connection pool, then the pool is waiting (30 seconds by default) for the connection(s) to expire, and then exit. If you want to force it, call `pg.end()`.

**Comment by olalonde** [comment]
> Node can always terminate when there are no pending queries.

That doesn't seem to be the case, a connected client prevents Node from terminating even if it's not part of the connection pool. What I want is for Node to terminate even if there's a connected client as long as there are no "in flight" queries.

**Comment by vitaly-t** [comment]
Why not use `process.exit()` then?

**Comment by olalonde** [comment]
Because I'm writing a library and I don't want users to scratch their head wondering why their process doesn't exit.

**Comment by fantapop** [comment]
It would be nice to have this.  As a user of node-postgres, I was scratching my head for a bit until I decided to investigate.  node_redis providing this feature was how I thought to look for this functionality in node-postgres.

https://github.com/NodeRedis/node_redis/blob/79fc40036baee3ca87c877625145c810b865a553/lib/extendedApi.js#L74

**Comment by fantapop** [comment]
Running into this again in combination with this node bug:

https://github.com/nodejs/node/issues/6456

I'm trying to pull large json objects out of postgres and print them to stdout.   If I don't call process.exit() the script doesn't exit.  If i do, the output is truncated.  The suggested workaround in the node bug is working inconsistently.

**Comment by olalonde** [comment]
Have you tried my `patchClient` workaround? It's been working well for me.

**Comment by brianc** [comment]
If you want your process to terminate immediately you can 

1) close your client with `client.end` if you're using a single client
2) call `pool.end()` on the pool instance if you're using a pool

I think in 99% of the cases that's the right approach.  In your request you said you don't want users to scratch their heads wondering why their process isn't terminating? Not sure your exact requirements but if you're creating the client/pool in your library I'd wager your library is responsible for cleaning up when the user's done with it...which includes calling `.end` on things internally.  

Adding an `unref` to the client isn't something I'm really interested in doing...the client API already pretty large and there isn't a super intuitive way to add `unref` behavior to an entire pool.  If you absolutely need to unref the socket you can use that `patchClient` thing or manually call `client.connection.stream.unref()`.

**Comment by fantapop** [comment]
I ran into another case where node-postgres just wouldn't exit.  I was using only the client and calling client.end() when I was done.  I tried manually calling ```client.connection.stream.unref()``` after calling client.end() and it still wouldn't end.  @olalonde your ```patchClient``` function did the trick.

**Comment by fantapop** [comment]
Actually... having some issues with the ```wrap(query)```.  I'm using promises with node-pg and this wrapper is adding a callback to deal with the references which in turn is changing the behaviour.  I'm still trying to track down the actual problem.

**Comment by fantapop** [comment]
On further investigation.  My problem was unrelated to node-pg at all.  Sorry for the back and forth.  I'm going to delete these ramblings since I don't think they add to the issue in a meaningful way.
