### ISSUE TITLE
Error while trying to insert an json array

### ISSUE THREAD

**Issue by eriknyk** [brianc/node-postgres#1016]
Hi, this issue #442 should be reopened, since in postgres shell is possible to execute without problems:
```
INSERT INTO public.my_table (userId, personId, books) VALUES (1, 1, '[1,2,3]');
```
however when trying to insert the same array using pg module I'm getting the error:

```
"error": {
    "cause": {
      "message": "invalid input syntax for type json",
      "code": "22P02",
      "detail": "Expected \":\", but found \",\".",
      "length": 148,
      "severity": "ERROR",
      "where": "JSON data, line 1: {\"1\",...",
      "file": "json.c",
      "line": "1198",
      "routine": "report_parse_error"
    },
    "isOperational": true,
    "code": "22P02",
    "detail": "Expected \":\", but found \",\".",
    "length": 148,
    "severity": "ERROR",
    "where": "JSON data, line 1: {\"1\",...",
    "file": "json.c",
    "line": "1198",
    "routine": "report_parse_error"
  }
```

Best Regards

**Comment by joskuijpers** [comment]
Could you give your Table layout so we could try to reproduce this error?

**Comment by brianc** [comment]
This looks like a syntax error with your query & not a bug with node-postgres. Particularly in the case of a plain text query without parameters the query is passed 100% unaltered to the backend server.

**Comment by dcworldwide** [comment]
Just to confirm, is inserting an array into a JSON/B column supported?

I'm having an issue inserting an array into a JSON column with typeorm. It's a library that depends on this library for postgres integration. I want to know if it's a bug in that library, or a limitation of this library. Thanks 

https://github.com/typeorm/typeorm/issues/183

**Comment by charmander** [comment]
@dcworldwide See #1143.
