### ISSUE TITLE
pg connection issue after node upgarde (possibly openssl related)

### ISSUE THREAD

**Issue by eyalsach** [brianc/node-postgres#1019]
after upgrade to node v6.1.0, can't connect to postgres hosted on aws.

example code:
var pg = require('pg');
pg.connect(connectionString, function(err, client, done) {

where connectionString can be something like:
postgres://master:password@aws-postgres.XXX.us-west-2.rds.amazonaws.com:5432/db_demo?ssl=true

EDIT: the same happens even when omitting the ssl=true param.

I get: { error: password authentication failed for user "master"

(the password is the correct one, this error happens only on the latest node version)

is this a bug or a change that I need to handle differently?

it's likely related to https://github.com/nodejs/node/pull/6551

(original issue: https://github.com/nodejs/node/issues/6782)

**Comment by vitaly-t** [comment]
Duplicate of https://github.com/brianc/node-postgres/issues/1000?

**Comment by eyalsach** [comment]
Thanks, you're right. It's a dup. Solved after upgrading. Not sure how I missed this upgrade but thanks anyway
