### ISSUE TITLE
pg insert single quote value issue

### ISSUE THREAD

**Issue by alxpereira** [brianc/node-postgres#1020]
hi,
I have an issue when I use pg to insert value with single quote using the parameterized method.

`client.query('insert into mytable values ($1)', ["a value with sing''le quo''te"])`

as you see I use the double-quote escape to avoid any insertion error, which works, but the issue is that now in my DB the final value is `sing''le quo''te` and not `sing'le quo'te` as it should be.

when I try directly in the DB, everything is fine, using parameterized queries, it breaks.

any solution ?
thanks !

**Comment by xkjyeah** [comment]
```client.query('insert into mytable values ($1)', ["a value with sing'le quo'te"])```

**Comment by vitaly-t** [comment]
>as you see I use the double-quote escape to avoid any insertion error

You shouldn't be doing that ever! The library provides the correct escaping for strings as well as all the other JavaScript types.

**Comment by scarabdesign** [comment]
I'm trying to insert any arbitrary data (content of which I don't control) some of which have single quotes (as apostrophes, e.g., O'Brien). During the parsing of the input data, each string comes in as an argument. When I'm building my values array, I'm putting each into an array as follows:
`var values = [arg1, arg2, arg3]`
In doing so, the single quotes inside my strings are being escaped automatically by node with a slash. 
`['string1', 'string2\'s', 'string3']`
This, of course, does not work with node-postgres.
It's frustrating that the node engine defaults to single quotes; you can test this. In a node terminal type:
`["a", "b's", "c"]`
What you get back is:
`['a', 'b\'s', 'c']`
Do you have a suggestion on how I can resolve this?

**Comment by brianc** [comment]
If you pass parameters (as you are in your example) then postgres will escape them for you - no need to provide a `''` escape for the `'` character - its handled internally within postgres
