### ISSUE TITLE
True way for replset

### ISSUE THREAD

**Issue by escaton** [brianc/node-postgres#1021]
Hi!
I have to create pool with connections to 3 different hosts with same db (kind of replset). What can you suggest for this, using as much your functionality as possible?

**Comment by vitaly-t** [comment]
You use 3 separate connection configs when connecting, that's all.

**Comment by escaton** [comment]
if pg were providing class instead of singleton, yes, but how could i manage errors if they all are fired on one instance?

**Comment by vitaly-t** [comment]
Each query uses its own `Query` instance, and errors are quite easy to separate.

**Comment by brianc** [comment]
@escaton with the newest version of node-postgres (6.0.0+) the singleton is discouraged and it's encouraged and easy to create and manage a pool yourself in your app.  Hopefully this solves your problem!  i've updated the readme to be current with the new API (which is for the most part backwards compatible) so you should be good to go if you upgrade to `pg@6.x`. 👏 

I feel your pain on the singleton - it's been a long standing hold-over of bad API design I did +5 years ago...hopefully having an instantiatable pool helps pave the path forward for a cleaner architecture than a global singleton. 

If the new pool design doesn't solve your issue please feel free to open another one!
