### ISSUE TITLE
connection-parameters.js does not support currentSchema

### ISSUE THREAD

**Issue by plcstpierre** [brianc/node-postgres#1023]
http://stackoverflow.com/questions/4168689/is-it-possible-to-specify-schema-when-connecting-to-postgres-with-jdbc

neither does pg-connection-string

**Comment by vitaly-t** [comment]
The feature was introduced in PostgreSQL 9.4:
```
postgres://username:password@host:port/database?currentSchema=myschema
```

Both [pg-connection-string](https://github.com/iceddev/pg-connection-string) and this library would need to be updated.

**Comment by plcstpierre** [comment]
Do you have a link for the postgres protocol? I would like to give it a try.

**Comment by elmigranto** [comment]
> Do you have a link for the postgres protocol?

@plcstpierre Is this what you are asking about?
https://www.postgresql.org/docs/9.5/static/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by plcstpierre** [comment]
Nope. I mean the low level stuff. What the client is supposed to do when it receive a schema in the string?

**Comment by elmigranto** [comment]
It supposed to pass it down to server to figure out.

**Comment by charmander** [comment]
Duplicate of #1123
