### ISSUE TITLE
Unable to get some replication infos (select * from pg_stat_replication)

### ISSUE THREAD

**Issue by laurentdebricon** [brianc/node-postgres#1027]
Hello,
i have a replication server in hot-stanby .

I want to get from nodejs the delay between my master DB with my slave. With pg_admin the command is :
`select * from pg_stat_replication  (to run on the master)
`and also
`select now() - pg_last_xact_replay_timestamp() AS replication_delay;` (to run on the slave) wich gives me the delay. 

It's working fine with pg_admin, but with node-postgres, pg_last_xact_replay_timestamp() is null, also neary all of "select * from pg_stat_replication" are also null.

Help :)

**Comment by brianc** [comment]
I'd need to see the code in more detail. Historically if it works in `psql` but doesn't work with node-postgres it's almost always an error in the code...do you have code to reproduce this issue?

**Comment by laurentdebricon** [comment]
Hello, you were right, it was my fault in my code :s . Thank you.
