### ISSUE TITLE
Parameterized query containing the "IS NOT" operator with a boolean parameter produces a syntax error

### ISSUE THREAD

**Issue by manjabes** [brianc/node-postgres#1032]
For example, such a table:

```
CREATE TABLE test
(
  id serial NOT NULL,
  bla text,
  enabled boolean,
  CONSTRAINT test_pk PRIMARY KEY (id)
)

```
and such usage:
```
var pg = require('pg');
pg.connect('tcp://user:pass@localhost:5432/test', function(error, client, done){
  client.query('SELECT id, bla, enabled FROM test WHERE id = $1 AND enabled IS NOT $2', [1, false],  function(error, result) {
    if(error){
      console.error("ERR", error);
    }
    else {
      console.log('OK', result);
    }
  });
});

```

produces the following result:
```
ERR { [error: syntax error at or near "$2"]
  name: 'error',
  length: 84,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '68',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1052',
  routine: 'scanner_yyerror' }
```
whereas one would expect rows to be returned.
Tested with v.4.5.5

[Link to pg doc](https://www.postgresql.org/docs/9.1/static/functions-comparison.html)

**Comment by EliSnow** [comment]
The same result is happening with null parameters with the `IS` and `IS NOT` operators.

```
var pg = require('pg');
pg.connect('tcp://user:pass@localhost:5432/test', function(error, client, done){
  client.query('SELECT NULL IS $1', [null],  function(error, result) {
    if(error){
      console.error("ERR", error);
    }
    else {
      console.log('OK', result);
    }
  });
});
```

**Comment by EliSnow** [comment]
This happens in the latest 5.1.0 as well, FYI.

**Comment by brianc** [comment]
If postgres is saying that's a syntax error than its likely a syntax error.
Are you certain postgres supports parameterizing the `IS` statement? The
query is passed _unchanged_ to the server so I'm betting its not supported
by postgres.

**Comment by EliSnow** [comment]
I think you may be right @brianc. I just tried from within the database (pgAdmin):

```sql
DEALLOCATE foo;
PREPARE foo (text) AS
SELECT NULL IS $1;

EXECUTE foo(NULL);
```

and got the syntax error. Interestingly enough,

```sql
DEALLOCATE foo;
PREPARE foo (text) AS
SELECT NULL IS NOT DISTINCT FROM $1;

EXECUTE foo(NULL);
```

does work, as does the following from within pg.js:

```js
var pg = require('pg');
pg.connect('tcp://user:pass@localhost:5432/test', function(error, client, done){
  client.query('SELECT NULL IS NOT DISTINCT FROM $1', [null],  function(error, result) {
    if(error){
      console.error("ERR", error);
    }
    else {
      console.log('OK', result);
    }
  });
});
```

**Comment by manjabes** [comment]
I tried the same query with two Python bindings, pg8000 and psycopg2. With psycopg2 (which [uses libpq](https://wiki.postgresql.org/wiki/Python)) it worked:

```
>>> import psycopg2
>>> conn = psycopg2.connect(database='test', user='user', password='pass')
>>> cur = conn.cursor()
>>> cur.execute('SELECT id, bla, enabled FROM test WHERE id = %s AND enabled IS NOT %s', (1, False))
>>> cur.fetchall()
[(1, 'shsdfh', None)]

```
but with pg8000, which is a supposedly pure Python implementation, a similar parsing error occurred:

```
>>> import pg8000
>>> conn = pg8000.connect(database='test', user='user', password='pass')
>>> cur = conn.cursor()
>>> cur.execute('SELECT id, bla, enabled FROM test WHERE id = %s AND enabled IS NOT %s', (1, False))
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\pg8000\core.py", line 1891, in execute
    ps = cache['ps'][key]
KeyError: ('SELECT id, bla, enabled FROM test WHERE id = %s AND enabled IS NOT %s', ((705, 0, <function Connection.__init__.<locals>.unknown_out at 0x0000026FC7699510>), (16, 1, <function bool_send at 0x0000026FC765D2F0>)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    cur.execute('SELECT id, bla, enabled FROM test WHERE id = %s AND enabled IS NOT %s', (1, False))
  File "C:\Python35\lib\site-packages\pg8000\core.py", line 906, in execute
    self._c.execute(self, operation, args)
  File "C:\Python35\lib\site-packages\pg8000\core.py", line 1940, in execute
    self.handle_messages(cursor)
  File "C:\Python35\lib\site-packages\pg8000\core.py", line 2088, in handle_messages
    raise self.error
pg8000.core.ProgrammingError: ('ERROR', '42601', 'syntax error at or near "$2"', '68', 'scan.l', '1052', 'scanner_yyerror', '', '')
```

And, in case of psycopg2, the queries succeeded whether the second argument was True, False or None (which is cast to NULL for PostgreSQL according to [this](http://initd.org/psycopg/docs/usage.html#adaptation-of-python-values-to-sql-types)) and in case of pg8000 all the the queries failed.
The first mention of this feature in PostgreSQL docs is [version 7.2](https://www.postgresql.org/docs/7.2/static/functions-comparison.html) so it's not like it's some kind of brand new gimmick either. I might even be bold enough to claim that the fact, that this query works with psycopg2, would rule out PostgreSQL itself not supporting that.

**Comment by brianc** [comment]
psycopg2 doesn't use parameterized sql - it escapes parameters on the python side before passing to libpq.  Using a parameter in an `IS` statement is not supported by the postgres query dialect, and therefore isn't supported by node-postgres.  If you want to use a "parameter" there you'll have to manually escape it & string-concat it into your query. 

You could use this: https://www.npmjs.com/package/pg-escape
