### ISSUE TITLE
how to catch raise notice properly

### ISSUE THREAD

**Issue by prtome** [brianc/node-postgres#1034]
Hello
I obviously do not understand well the documentation. I am trying to debug an after insert trigger that works perfectly when doing the insert in the command line and not from my node server.
I have 2 raise notice that return the values ok from command line.
Now I have this in my code:
var db = new dbs();
var connString = db.pgConnect(req);
pg.connect(connString, function(err, client, done) {
var handleError = function(err) { // handle error};
client.on('notice', function(msg) {
console.log("notice: %j", msg);
});

I get something in console log: notice: {"name":"notice","length":724,"severity":"NOTICE","code":"00000","where":"SQL statement \"insert into ... and all my SQl statement
but not the values I asked (Raise notice 'ID IS %',theid; )
what is that I am doing wrong ? 
as an aside: 
The problem I have with the trigger is an "insert into ... select..." where the select goes into joins between multiple tables. It works on the command line not in the node server. (I have asked in stackoverflow http://stackoverflow.com/questions/37551129/nodenode-postgrespostgres-insert-into-from-select-not-working-in-trigger)
An "insert into.. select.. in only one table" works perfectly.
very strange

Thanks

**Comment by joskuijpers** [comment]
Could you apply code formatting to the code to make it more readable? Also, could you make a pg function for us to reproduce this problem?

**Comment by prtome** [comment]
sorry - I always have problems with the markdown ;)
I have now this very simple function, 

         create or replace function ctrl_func(theids integer[],thejsons text[])
         RETURNS integer AS \$$
         DECLARE
         i integer;
        BEGIN
           FOR i IN 1 .. array_upper(theids, 1)
           LOOP
               raise notice 'ids %',theids[i];
             raise notice 'the jsons %',thejsons[i];
             // here I must enter thejsons[i] in the database
          END LOOP;
         END;
         \$$ LANGUAGE plpgsql;

How do I see the raised notice in my server log ?
my code in node is

         var db = new dbs();
         var connString = db.pgConnect(req);
           pg.connect(connString, function(err, client, done) {
           var handleError = function(err) { // handle error};
             client.on('notice', function(msg) {
                    console.log("notice: %j", msg);
           });

I have a problem passing arrays of json correctly formatted so that the function correctly inserts them, which is why i need the notices to see what is going on. They work perfectly if I call the function from psql command line.
Thanks for your help

**Comment by sibedge** [comment]
@prtome it is not `notice`, it is `notification` ;)

**Comment by prtome** [comment]
@sibedge I am sorry I do not understand what you mean.
I must put notification in client.on instead of notice ?
and then I would get the notice from my function displayed ?

**Comment by joskuijpers** [comment]
Yes, that is what he means. Did you try it?

**Comment by prtome** [comment]
I finally found out what was not working, at least the way I thought. I needed again the notice and found out that if I write:

        console.log("notice", msg);

taking out the %j that is in the example (and in my question) I get the full notice as I would calling the function in psql. Which is what I need.
