### ISSUE TITLE
npm install pg error

### ISSUE THREAD

**Issue by Oulayatse** [brianc/node-postgres#1037]
hello 
a have a probleme with i
install modules pg any help please 
![koka](https://cloud.githubusercontent.com/assets/15874006/15741407/e0f1a41e-28b9-11e6-9782-2422cb8b6722.PNG)

**Comment by brianc** [comment]
That looks like an issue with mom, not this module

**Comment by Oulayatse** [comment]
i didn't understand can you explain please

**Comment by Oulayatse** [comment]
can any one help me please

**Comment by JCornat** [comment]
Running `npm install pg` will create a folder `node_modules` in your current directory, and you are doing this in`c:/Program FIles`. Only administrators can do this : you can run your command prompt as Administrator or execute this command in another folder which is not protected by admin rights.

**Comment by Oulayatse** [comment]
i run it as admin wits c:\users\xxxx and didnt work

**Comment by Oulayatse** [comment]
![kkk](https://cloud.githubusercontent.com/assets/15874006/15778014/cb6ba948-2993-11e6-9be3-777f12563b86.PNG)

**Comment by JCornat** [comment]
As written, `This is most likely not a problem with npm itself and is related to network connectivity` : you should Google the error, and close this one because it is not an issue linked to this module.

**Comment by Oulayatse** [comment]
i google it without result

**Comment by samholmes1337** [comment]
Really? I just did a google search for `npm ECONNRESET 407` and got several hundred results. Having said that though, this error is very likely totally unrelated to npm and more to do with the way your network is configured.

The error message reads:

```
In most cases you are behind a proxy or have bad network settings.
If you are behind a proxy, please make sure that the 'proxy' config is set properly.
```

I would check your network connectivity settings, make sure you're not running behind a proxy and, if you are? Use `npm help config` for more information on how to set up npm to work with your proxy.

**Comment by joskuijpers** [comment]
This is unrelated to pg itself.

@brianc I think this can be closed.

**Comment by brianc** [comment]
👍
