### ISSUE TITLE
Releasing from pool doesn't work?

### ISSUE THREAD

**Issue by markasoftware** [brianc/node-postgres#1039]
Releasing from the pool does not seem to work properly. When I run the callback to release a client from the pool, I can still run queries on that client and they return results.

**Comment by brianc** [comment]
yeah the client isn't disconnected, just returned to the pool.  It's a very bad idea to run queries on a client once you've released it.  Similarly you can exit a lock block in parallel code and still access & mutate shared state from other threads...but you shouldn't.  Best bet: once you release a client back to the pool __don't__ touch it again.  Just check another one out. :)
