### ISSUE TITLE
Vertica gives ECONNRESET on placeholder values

### ISSUE THREAD

**Issue by msiebuhr** [brianc/node-postgres#1042]
I'm using `pg` to talk to a hosted Vertica database, eg:

    client.query('SELECT 1::int AS number', [], function () {...});

works as expected, but

    client.query('SELECT $1::int AS number, ['1'], function () {...});

Just hangs. Or gets `ECONNRESET` on `read()` on lucky runs. The same invariably repeats with other queries.

From reading Vertica's docs ([Vertica Programmers Guide](https://my.vertica.com/docs/7.0.x/PDF/HP_Vertica_7.0.x_Programmers_Guide.pdf))) make no mention that I can find of using `$1` and friends as placeholders.

I unfortunately cannot provide access to the database in question to test things on, but I'll be happy to run ad-hoc things as time permits, if that turns out relevant.

**Comment by brianc** [comment]
Vertica might not support parameterized queries. I have no experience with
vertica. If that's the case you will have to avoid using parameterized
queries.  Just don't forget to escape any user supplied data before
concatenating it into your sql!  Without using parameters you'll have to do
this yourself!
