### ISSUE TITLE
large amount of idle connections

### ISSUE THREAD

**Issue by bbnnt** [brianc/node-postgres#1044]
I have the following piece of code to connect a simple node script to the database : 

https://gist.github.com/anonymous/bad7ae217037baba739ad5bae738ce66

Used to serve a website, I run some stress tests on it to see how much it can handle (using blitz, increasing up to 500 simultaneous connections). My problem is that after running a test, I can see a large  amount (20/30) of idle connections (all the same, `postgres: dbuser dbname ::1(53034) idle`)

I'm not experienced enough to understand the implications, if it is normal or if it has to be adressed. I've read there was a timeout on idle connections, but they remained here the whole day (the site is not in production)

This happen with the node script specifically; a rails service running on the same db and being hit with the same amount of requests, does not induce those idle connections. Thanks a lot if any experienced advices could answer those concerns

Best

**Comment by brianc** [comment]
Don't call `pg.end` at the end of your request - that is really only useful
if you're trying to fully shut your app down.  You also need to call `done`
inside the callback of your query finishing, not before you send it.  It
looks like there are some issues in your implementation.  There are unit
tests around the idle timeout behaving as expected & I've also witnessed it
countless times in my own apps so...its likely something w/ the way you're
using pg.
