### ISSUE TITLE
Parse error returned by client.query

### ISSUE THREAD

**Issue by deryl27** [brianc/node-postgres#1046]
The format of the error is as follows 
{ [error: must be superuser or have the same role to cancel queries running in other server processes] name: 'error', 
length: 14, 
severity: 'ERROR', 
code: '01',
 detail: undefined,
 routine: 'pg_cancel_backend' }

How do I get the error attribute to retrieve the actual message. ??  It is not a Json format and when I do Json.stringify(err), the error array is not present

**Comment by joskuijpers** [comment]
The message is what you see there. it is 'must be superuser .... processes'. I suspect this is just another `Error` object so you can use `err.message` to retrieve that message.

**Comment by brianc** [comment]
Yup @joskuijpers nailed it: `error.message` is what you're looking for
