### ISSUE TITLE
Missing fields from Results

### ISSUE THREAD

**Issue by thilorichter-optimizely** [brianc/node-postgres#1050]
I have an issue where the SQL is missing results for fields. I have a query which uses a left join to connect two tables.
If I run that query using PgAdmin, I get the expected result. Two tables joined on an ID. If I run that through node with PG, I have a lot of results where the ID is null (which should be impossible on a left join, since it includes all results of the left table (which all have an ID) and the matching results for the right table). 
I also checked individual results. The same row has an ID in pgAdmin where it is NULL when I use pg.

There seems to be a problem how pg parses the results. How can I debug this further?

Node version 6.2.1
PG version 5.1.0

**Comment by brianc** [comment]
Can you send a self-contained code sample that demonstrates the problem? I
can't really help unless I have a piece of code I can run which reproduces
the issue.

**Comment by thilorichter-optimizely** [comment]
Hey,

I found an inconsistency between how pgAdmin handles the query and pg. I did a select * and left join. The ID column was present in both tables. After the join, pg decided to use an ID column of the right table (which was NULL sometimes) while pgAdmin decided to use the ID field of the left table which resulted in the correct result.

Clearly specifying which fields I want from which table (which is good practice anyways) fixed the problem. Still there is an implementation difference on how results are interpreted.

So not a bug necessarily.

**Comment by inian** [comment]
This caught me up too. If the query is a left join and the column being joined on is ID, then I think the ID from the left table should be returned. Right now node-postgres returns the ID from the right table which can be null (which is the whole point of doing a left join). 

What do you think @brianc?

**Comment by charmander** [comment]
@inian I don’t think pg has any way of knowing which columns come from which side of a join, or that it should try to do anything with that information. You can:

- rename your columns in the query so there are no conflicts, e.g. `SELECT a.id AS a_id, b.id AS b_id FROM …`, or
- use the `rowMode: 'array'` query option to get back arrays instead of objects, and combine that with information from the result’s `fields` property if you want.

**Comment by inian** [comment]
Hey @charmander, I ended up explicitly renaming the columns which worked for me. However, I was seeing if there was a way for this module to match the behaviour when I run the query directly on the database (via CLI or a GUI program). Running the query directly on a SQL GUI program gives me a non-NULL ID and I would expect running the query via this module also to give similar results.
