### ISSUE TITLE
[improvement] removing the need to explicitly convert a parameter to string before every call

### ISSUE THREAD

**Issue by arkenidar** [brianc/node-postgres#1051]
UPDATE: now submitted a pull request
[pull request: handle 'stringable' objects in query() method, besides strings and query objects]
(https://github.com/brianc/node-postgres/pull/1052)

in _normalizeQueryConfig()_ of _pg/lib/utils.js_ 
```
  if( 0 !== config.toString().indexOf('[object ') ){
    // if toString is overridden then call it
    config = config.toString();
  }
```
So **this patch would allow to reduce replication** of "toString" code (when calling query method).

**Comment by joskuijpers** [comment]
@brianc PR is closed, so this one as well
