### ISSUE TITLE
Invalid disconnection error with Native Bindings

### ISSUE THREAD

**Issue by sibedge** [brianc/node-postgres#1053]
When we use `pg.on('error', handler)` to handle server disconnection:

```js
pg.on('error', function(err){
   if(/*using Native Bindings*/){
    var isErrorObject = err instanceof Error; // true
    var errMsg = err.message; // it is empty !!! ???
  }
});
```
...the server disconnects, and we are getting an `Error` object with property `message` not set to anything at all. 

At the same time, something spits into the console: `FATAL:  terminating connection due to administrator command`.

This doesn't happen with JavaScript Bindings, works as expected.

The way to reproduce it - by opening Services, and clicking Stop on the PostgreSQL service.

OS: Windows 10, 64-bit
Node.js: 6.2.1

**Comment by joskuijpers** [comment]
Errors are either created using `new Error("some text")` or forwarded from upstream. I can't seem to find any `new Error()` calls without a message, so it seems this comes from upstream.
Can you give a backtrace and find out where this exact error was thrown?

**Comment by sibedge** [comment]
I can no longer reproduce the problem, so closing for now.
