### ISSUE TITLE
Dropping support for node v0.10?

### ISSUE THREAD

**Issue by evansiroky** [brianc/node-postgres#1057]
I got a failed continuous integration build based on commit 2fd9c77085c1efd66306f4dfe40ae4f05b7dede7.  Does this mean that this pg package no longer supports node 0.10?

Here is the continuous integration build:  https://travis-ci.org/evansiroky/db-streamer/builds/139227721

**Comment by brianc** [comment]
It still supports node@0.10 - you'll need to polyfill the `Promise` API:

https://github.com/brianc/node-postgres/blob/master/test/test-helper.js#L5

That's how I did it here. note: my tests are still running green against node@0.10!  Sorry for the headache!

**Comment by MehranJanfeshan** [comment]
I had the same problem and  I got polyfill and added this code to fix everything: 

`if (typeof Promise == 'undefined') {
  global.Promise = require('promise-polyfill')
} `
