### ISSUE TITLE
Example at https://github.com/brianc/node-postgres/wiki/Example is missing pool.connect()

### ISSUE THREAD

**Issue by MatixYo** [brianc/node-postgres#1064]
Given example won't work. It probably requires pool.connect() in order for it to work.

**Comment by brianc** [comment]
Thanks for the heads up @MatixYo!  I updated the example & tested it locally - should work now with a copy/paste as long as you install node-postgres at version 6.x!

https://github.com/brianc/node-postgres/wiki/Example

**Comment by MatixYo** [comment]
It doesn't seem to work. It only creates table 'visit' but doesn't add any records to it.
I'm running 6.2.1.
