### ISSUE TITLE
Confusing Node.js version support

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1066]
The library itself is being tested against Node.js 0.10, till the latest, while everything has been moved to use the new `pg-pool`, which uses ES6 promises, and restricts you to Node.js 4.x and later.

This creates confusion among users, and presumably a mess during deployment when the target server suddenly has a pre-4.x version of Node.js.

Check out another recent question I answered: [error in pg-pool module when using postgres module with nodejs and heroku](http://stackoverflow.com/questions/38061325/error-in-pg-pool-module-when-using-postgres-module-with-nodejs-and-heroku/38069371#38069371).

---

I believe that for this library it is very important to continue supporting Node.js 0.10 fully, which is still used by many, and will be for some time.

As for the promises, if somebody really wants to use them properly - you can tell them to use `pg-promise`, which will work under any Node.js version. I honestly don't think that promises should be used on this level, which is essentially a kernel for other libraries, and should remain to be that way :wink:

**Comment by brianc** [comment]
Thanks! I will include instructions in the pg-pool library on how to
polyfill a promise implementation if they're on an older version of node
that doesn't have one.

node-postgres and therefore pg-pool both should support node back to
0.10.x. The tests still pass in Travis for nide-postgres, which uses
pg-pool in 0.10, I just had to polyfill a promise implementation.  I'll
make that more clear!

**Comment by brianc** [comment]
I've updated the [pg-pool readme](https://github.com/brianc/node-pg-pool#bring-your-own-promise) with better instructions on how to use it in versions of node which do not support Promises natively, and I've made the [tests pass in older versions of node](https://github.com/brianc/node-pg-pool/pull/17) by removing the es6 stuff in the tests!  Thanks. 😄

**Comment by vitaly-t** [comment]
Great job! :smile:
