### ISSUE TITLE
Unable to connect using custom SSL configuration

### ISSUE THREAD

**Issue by fredrikgrohn** [brianc/node-postgres#1069]
There is a recent change (https://github.com/brianc/node-postgres/commit/1596a933eb5e856b96193e5e25b908cdc25ceda6) that seem to make connecting to a database using a custom SSL configuration no longer possible.

This would be a code sample:

	var databaseConfig = {
		user: 'myuser',
		database: 'mydb',
		port: 5432,
		host: 'myhost',
		ssl: {
			ca: fs.readFileSync('root.crt'),
			rejectUnauthorized: true,
			key: fs.readFileSync('user.key'),
			cert: fs.readFileSync('user.crt')
		}
	};
	var client = new pg.Client(databaseConfig);

The offending line of code is in lib/connection-parameters.js, at line 50:

	this.ssl = typeof config.ssl === 'boolean' ? config.ssl : useSsl();

This should probably be changed to something like:

	this.ssl = typeof config.ssl === 'boolean' || typeof config.ssl === 'object' ? config.ssl : useSsl();

At least this appears to fix it for me.

**Comment by guoxiangyang** [comment]
I've push a PullRequest to fix this, only need one line change.

**Comment by brianc** [comment]
I merged the PR & fixed this! Thank you!!!
