### ISSUE TITLE
Query events with Pool

### ISSUE THREAD

**Issue by jtuu** [brianc/node-postgres#1070]
With a client we can use the "row" event of a query.
`client.query("select id from table").on("row", row => console.log(row))`

```
{ id: 1 }
{ id: 2 }
{ id: 3 }
{ id: 4 }
{ id: 5 }
```

But with a pool we can't do this.
`pool.query("select id from table").on("row", row => console.log(row))`
`TypeError: pool.query(...).on is not a function`

Is it possible to use the query events with pool?

**Comment by lebreRafael** [comment]
I`m facing the same problem here. I don`t want to refactor all code using loops instead of .on('row') to change pg.client to pg.pool

**Comment by RenanBardy** [comment]
I have the same error in my application. Is there any way to fix this?

**Comment by brianc** [comment]
The pool supports returning a client if you want to do something like that:

```js
pool.connect(function(err, client, done) {
  var query = client.query('whatever')
  query.on('row', //etc)
  //...etc
})
```

`pool.query` is a helper method for the most common operation which is "I want to run a query and get the rows back."  If you want to do something "fancier" with a client (transactions, row events, listen/notify, pg-query-stream, etc) then `pool.query` isn't for you.  I don't really want to extend the `pool.query` method with even more functionality...

Curious: why are you using `query.on('row')` in the first place?

**Comment by lebreRafael** [comment]
@brianc I'm using `query.on('row')` because I need to do something for each line returned and with the row event I don't need to write loops in my code.

**Comment by jtuu** [comment]
@brianc Thank you for the example, it helped me. I get that `pool.query` is supposed to be a helper method but perhaps it should use a different name to avoid confusion/inconsistency between `client.query` and `pool.query`. Btw I use `query.on('row')` to "stream" data through websocket in realtime.

**Comment by charmander** [comment]
Discouraged for `Client.prototype.query` as well in pg 7.

**Comment by jcuenod** [comment]
I know this is an old thread but I'm wanted to do something like what @jtuu is describing.

I want to use `pool` so I don't have to manage a warm pool of db connections (which is what I understand the point of pool to be). I want to stream results to clients though and the `row` event seems like a much better option that polling the cursor.

What is the best way of accomplishing this?

**Comment by charmander** [comment]
> I want to stream results to clients though and the `row` event seems like a much better option that polling the cursor.

@jcuenod That’s not what the `row` event did, but it’s an easy mistake to make (and why it’s not part of the public API now). You will probably want to use a cursor, but it [doesn’t have to be directly][1].

  [1]: https://github.com/brianc/node-pg-query-stream

**Comment by bluenote10** [comment]
> If you want to do something "fancier" with a client (transactions, row events, listen/notify, pg-query-stream, etc) then pool.query isn't for you. I don't really want to extend the pool.query method with even more functionality...

@brianc Thanks for the clarification, that really makes sense. A quick question about the exact semantics: When using `client.on('notification', callback)` on a client acquired from a pool, is it safe to release this client back to the pool and still get notify updates, or does this require holding on to the client indefinitely?
