### ISSUE TITLE
new keyword or not ?

### ISSUE THREAD

**Issue by Brakkar** [brianc/node-postgres#1077]
Hi,
should I use this:

```
let pg = require( 'pg' ).native

const dbPool = new pg.Pool( dbConfig) 

// or this (without new keyword) ?

const dbPool = pg.Pool( dbConfig) 
```

**Comment by vitaly-t** [comment]
`Pool` is a class, so using `new` is the right approach.

**Comment by vitaly-t** [comment]
[I have submitted a PR](https://github.com/brianc/node-pg-pool/pull/18) to make this irrelevant.

**Comment by brianc** [comment]
@vitaly-t nailed it!  Thanks y'all!
