### ISSUE TITLE
'password authentication failed for user' in Node v6

### ISSUE THREAD

**Issue by spamguy** [brianc/node-postgres#1080]
I'm running my app on Node v6.2.2, PostgreSQL 9.5, and Ubuntu 14. Knex, which uses pg, refuses to make any connections and throws this error instead:

```
dipl.io-0 (out): Knex:Error Pool2 - error: password authentication failed for user "XYZ"
dipl.io-0 (out): Knex:Error Pool2 - error: password authentication failed for user "XYZ"

dipl.io-0 (err):     at Promise._execute (/var/www/html/diplio/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:272:9)
dipl.io-0 (err):     at Promise._resolveFromExecutor (/var/www/html/diplio/node_modules/knex/node_modules/bluebird/js/release/promise.js:475:18)
dipl.io-0 (err):     at new Promise (/var/www/html/diplio/node_modules/knex/node_modules/bluebird/js/release/promise.js:77:14)
dipl.io-0 (err):     at /var/www/html/diplio/node_modules/knex/lib/runner.js:187:35
dipl.io-0 (err):     at tryCatcher (/var/www/html/diplio/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
dipl.io-0 (err):     at Function.Promise.attempt.Promise.try (/var/www/html/diplio/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
dipl.io-0 (err):     at Runner.ensureConnection (/var/www/html/diplio/node_modules/knex/lib/runner.js:186:39)
dipl.io-0 (err):     at Runner.run (/var/www/html/diplio/node_modules/knex/lib/runner.js:41:44)
dipl.io-0 (err):     at QueryBuilder.Target.then (/var/www/html/diplio/node_modules/knex/lib/interface.js:32:43)
dipl.io-0 (err):     at QueryBuilder.tryCatcher (/var/www/html/diplio/node_modules/bluebird/js/main/util.js:26:23)
dipl.io-0 (err):     at doThenable (/var/www/html/diplio/node_modules/bluebird/js/main/thenables.js:52:38)
dipl.io-0 (err):     at tryConvertToPromise (/var/www/html/diplio/node_modules/bluebird/js/main/thenables.js:30:20)
dipl.io-0 (err):     at Promise._resolveCallback (/var/www/html/diplio/node_modules/bluebird/js/main/promise.js:442:24)
dipl.io-0 (err):     at Promise._settlePromiseFromHandler (/var/www/html/diplio/node_modules/bluebird/js/main/promise.js:515:17)
dipl.io-0 (err):     at Promise._settlePromiseAt (/var/www/html/diplio/node_modules/bluebird/js/main/promise.js:581:18)
dipl.io-0 (err):     at Async._drainQueue (/var/www/html/diplio/node_modules/bluebird/js/main/async.js:128:12)
dipl.io-0 (err):     at Async._drainQueues (/var/www/html/diplio/node_modules/bluebird/js/main/async.js:133:10)
dipl.io-0 (err):     at Immediate.Async.drainQueues [as _onImmediate] (/var/www/html/diplio/node_modules/bluebird/js/main/async.js:15:14)
dipl.io-0 (err):     at tryOnImmediate (timers.js:543:15)
dipl.io-0 (err):     at processImmediate [as _immediateCallback] (timers.js:523:5)
```

I know there are many tickets like this in knex and pg, but none of them fully explain anything.
* I am running the latest version of pg, 6.0.2.
* I deleted the node_modules directory, cleared npm cache, and reran `npm install --production`.
* The user cited in the error (obscured as 'XYZ') is my Linux username, not the username set in my Node app.
* My dev environment is OSX, and I had no trouble at all. Deploying to Ubuntu triggered all this.

It was a tossup posting this on knex versus here, so let me know if this belongs somewhere better.

**Comment by spamguy** [comment]
Minor update: Bumped my node version to 6.3, nuked node_modules, reinstalled. No change.

**Comment by brianc** [comment]
When you install postgres on ubuntu it is more secure by default than it is
on os x, sometimes not having password authentication enabled at all by
default...unfortunately this is a configuration issue with your environment
and not actually a bug with node-postgres.  Make sure you can connect with
password auth via psql over localhost, not a unix domain socket.  Its
always a pain in the ass when i set up a new postgres box on linux because
the default config disallows password auth over the network, even
localhost.

**Comment by brianc** [comment]
One other tip: use environment vars to control connection params in your app

'PGUSER=foo PGDATABASE=bar PGPASSWORD=baz node my-app.js'

Helps to explicitly supply them

**Comment by spamguy** [comment]
Thanks, you were right about the details needed to make user/pass authentication work. By tweaking the pg_hba file *and* renaming my PSQL username to match Unix, it eventually cleared up. Your help is appreciated!

**Comment by Praveen-Invoscape** [comment]
I am also have this same issue plz give some more details to fix it spamguy........

**Comment by spamguy** [comment]
Sorry @Praveen-Invoscape, the specs of my project changed and I no longer have Postgres installed.

**Comment by sandhawke** [comment]
I don't really know what I'm doing, but here's how I got it to work, in case it's useful to someone.

`sudo emacs /etc/postgresql/9.6/main/pg_hba.conf`
add line: `host feedbot sandro 127.0.0.1/32 password`
(where feedbot is the table, sandro is my username)
`sudo /etc/init.d/postgresql restart`

`node -e "console.log(crypto.randomBytes(16).toString('hex'))"`
to generate a nice password, let's say 56c14c640ee1b59d163228
`sudo -u postgres psql`
`alter role sandro unencrypted password '56c14c640ee1b59d163228';`

` export PGPASSWORD=56c14c640ee1b59d163228`
`psql -h localhost -d feedbot`
works for me

**Comment by Globik** [comment]
@sandhawke  so feedbot is a database name or a name of database name's table?

**Comment by Globik** [comment]
@sandhawke  yes, it works. But I have no need edit pg_hba.conf. Enough  to establish the command alter role username unencrypted password 'yourpass'

**Comment by Crypto-Ash** [comment]
Hey,
Have You Got The Solution...
Because I Am Facing The Same Issue While Running Command
**yarn knex migrate:latest**
Please Reply Back
