### ISSUE TITLE
How to get Raw Date Strings from DB

### ISSUE THREAD

**Issue by nsisodiya** [brianc/node-postgres#1084]
![image](https://cloud.githubusercontent.com/assets/333455/16946572/e009bfd6-4dc7-11e6-810f-c82ce2dfa01d.png)

If you see my console, I made a query and I am getting staydate as `2016-08-01`  and `2016-08-02`.
But same query If I make in my application, 
I get Date object.

![image](https://cloud.githubusercontent.com/assets/333455/16946667/643998b2-4dc8-11e6-9e22-f0d90f604dac.png)

How I can disable this kind of behaviour ?
I want just plain string which I am getting in console !

**Comment by nsisodiya** [comment]
btw: I forget to tell, I am using https://github.com/vitaly-t/pg-promise/ library for getting data.
I am not using `node-postgres` library directly. But documentation of `pg-promise` says that it is using `node-postgres` ! So, I asked this question in this place !!

**Comment by vitaly-t** [comment]
What type is your `staydate` in the database? It is probably one of the data types, in which case the behavior is the expected one. If you want a string, then convert `Date` to a string.

**Comment by nsisodiya** [comment]
I got the answer !!

**Comment by nsisodiya** [comment]
Just to explain, how I got the my answer, here is the explanation !

My Query was like this !!

```js
let query = "select staydate, num_days, cost from rateTable";
```

I changed my query to like this

```js
let query = "select staydate::TEXT, num_days, cost from rateTable";
```

Now, I am getting dates in `YYYY-MM-DD` format, the way, I get it in console.

**Comment by brianc** [comment]
Thanks! Glad you got it figured out & appreciate you sharing your answer
here!
