### ISSUE TITLE
PG.connect never calls-back after (PG.defaults.poolSize) connections are used [6.0.3]

### ISSUE THREAD

**Issue by sparebytes** [brianc/node-postgres#1085]
I was using v4.4.2, but after upgrading to Node v6, I was no longer able to connect to my PSQL server with md5 authentication. I upgraded PG to v6.0.2 (and 6.0.3) which resolved that one issue but has caused another. After opening and closing connections 50 times, PG.connect quits invoking the callback. 

I set `PG.defaults.poolSize = 50;` Whatever value I set `poolSize` to be, that's how many connections before PG breaks. The problem goes away downgrading back to PG v4.4.2 and allowing password authentication on my PSQL server.

**Comment by brianc** [comment]
I'd need to see your code - I'm guessing you're not releasing connections back to the pool? If you don't release your connections then after you check out the number which the pool contains you'll never receive another one since they're all checked out.

**Comment by sparebytes** [comment]
```
'use strict';
const PG = require('pg');
PG.defaults.poolSize = 3;

function runTest() {
    const connectionString = require('../config/config').dbConnectionString;
    PG.connect(connectionString, function (err, connection) {
        if (!err) {
            console.log("Connected");
            connection.end();
            console.log("Closed");
            setTimeout(runTest, 100);
        }
        else {
            console.log("Error");
            setTimeout(runTest, 100);
        }
    });
}
runTest();
```

Output: It only iterates 3 times:
```
Connected
Closed
Connected
Closed
Connected
Closed
```

Am I missing something?

**Comment by brianc** [comment]
Yah; unfortunately, you're not using the pool correctly.  Why it ever worked on 4.x for you is a mystery.

Please read this: https://github.com/brianc/node-postgres#client-pooling

Notice in `PG.connect` the callback receives __three__ arguments in the example.  The 3rd being the `done` method you __must__ call when you're done w/ the connection.  What you're doing above is checking out a connection from the pool, using it, and then closing it yourself.  You're never returning the connection to the pool.  You shouldn't close a connection when its in the pool - the pool manages the connection lifecycle, you just get it when you need to run a query.

For further info read this entire readme, it should help explain things too:

https://github.com/brianc/node-pg-pool

Hope this helps 😄
