### ISSUE TITLE
pg.Pool - my new favorite helper function?

### ISSUE THREAD

**Issue by joefromct** [brianc/node-postgres#1089]
I am on node-postges version ` "pg": "^6.0.3"`.

I see that it uses `pg-pool` in the change notes. 

However, I can't figure out how to use "your new favorite helper method" from the [node-pg-pool readme](https://github.com/brianc/node-pg-pool): 

```javascript
var pool = new pg.Pool()
var time = await pool.query('SELECT NOW()')
var name = await pool.query('select $1::text as name', ['brianc'])
console.log(name.rows[0].name, 'says hello at', time.rows[0].name)
```
I get this when run through `babel-cli` 's `babel-node`: 
````
SyntaxError: C:/Users/some/dir/postres.js: Unexpected token (25:21)
  23 |
  24 | function summary_counts() {
> 25 |     var time = await pool.query('SELECT NOW()')
     |                      ^
````
I can however get the second example with a callback to work:
````javascript

    var pool = new pg.Pool()
    pool.query('SELECT $1::text as name', ['brianc'], function (err, res) {
        console.log(res.rows[0].name) // brianc
    })
````

What other dependencies do i have to get the `await` functionality to work in my helper function?  
I've tried:
1. Node.js 4.4.7, Node.js 6.x
2. installing [asyncawait ](https://github.com/yortus/asyncawait) since it appears to use that?
Nothing has yielded different results as of yet. 

Any tips appreciated thanks.

**Comment by brianc** [comment]
Howdy!

If you want to use async/await you'll need to use something like [babel](https://babeljs.io/docs/plugins/transform-async-to-generator/) to transpile for you.

If you want to use `yield` you can do that right now without transpiliting if you're using a recent version of node:  I use [co](https://github.com/tj/co) in basically everything I do with node now. No more callbacks, but you don't have to transpile with babel.

**Comment by brianc** [comment]
to do that w/ co you could do something like this:

```js
co(function * () {
  const res = yield pool.query('SELECT NOW()')
  const res2 = yeild pool.query('SELECT $1::text as name', ['brianc'])
  console.log(res.rows[0]) // the date
  console.log(res.rows[1].name) // brianc
}).then(() => { })
```

**Comment by brianc** [comment]
basically `pool.query` returns a promise. `yield` and `async/await` are higher level ways to deal with promise-based flow control.
