### ISSUE TITLE
Prepared statements maximum bindings

### ISSUE THREAD

**Issue by konhondros** [brianc/node-postgres#1091]
I am trying to do some big bulk inserts to Postgres via node-postgres When the bindings array exceeds 65536 values then passes to postgres the rest of values and when the query it runs I take the error

`[error: bind message supplies 4 parameters, but prepared statement "" requires 65540]
`

**Comment by vitaly-t** [comment]
@konhondros I believe you got your answer on StackOverflow: http://stackoverflow.com/questions/38540913/postgresql-node-js-prepared-statements-maximum-bindings/

**Comment by brianc** [comment]
@konhondros Postgres itself doesn't support more than [34464](http://stackoverflow.com/questions/6581573/what-are-the-max-number-of-allowable-parameters-per-database-provider-type) parameters for a bound statement.  You'll need to break up your bulk insert into multiple statements.

**Comment by hulbert** [comment]
@brianc this bit us pretty badly in production (via using knex, actually). Is there any way to have a more graceful error here? My team is happy to contribute it if you want to point us in a direction.

**Comment by charmander** [comment]
@hulbert You shouldn’t be binding an unbounded number of parameters. (If it’s through the intended use of a knex builtin, that’s a knex bug.) Use array parameters instead.

**Comment by hulbert** [comment]
@charmander do you mean something like this? Found here (https://github.com/brianc/node-postgres/wiki/Parameterized-queries-and-Prepared-Statements)

```js
client.query('SELECT * FROM table WHERE id = ANY($1::int[])', [[id1, id2, id3]])
```

**Comment by charmander** [comment]
@hulbert Yes.

**Comment by phiresky** [comment]
@brianc It would still be useful if this would somehow throw a different error. 

As it stands, for a parameterized query with X parameters you just get the error
_[bind message supplies `X modulo 65536` parameters, but prepared statement "" requires `X`]_
which is very unhelpful for diagnosing the cause for the problem.

Also the limit of 34464 parameters is wrong, at least for postgresql 9.6.3 I can do a single insert with 65535 parameters without problems.
