### ISSUE TITLE
prepared statement use

### ISSUE THREAD

**Issue by greaber** [brianc/node-postgres#1092]
Hi!  Database novice here.

On https://github.com/brianc/node-postgres/wiki/Prepared-Statements, I read,

> A prepared statement lets postgres plan the statement so that each execution takes advantage of the plan. 

But on https://www.postgresql.org/docs/current/static/sql-prepare.html, I read,

> PREPARE creates a prepared statement. A prepared statement is a server-side object that can be used to optimize performance. When the PREPARE statement is executed, the specified statement is parsed, analyzed, and rewritten. When an EXECUTE command is subsequently issued, the prepared statement is planned and executed. This division of labor avoids repetitive parse analysis work, while allowing the execution plan to depend on the specific parameter values supplied.

So is the `node-postgres` documentation misleading?

Also, I am currently using parameterized queries for everything and never using prepared statements.  But I wonder if I should always use prepared statements and never use parameterized queries, perhaps auto-generating the statement name based on the the query text.  Or if `node-postgres` should do that internally, at least as an option.  Is there a downside of prepared statements that I am missing?  (I guess they take up some space on the server, but wouldn't it usually be negligible?)

**Comment by brianc** [comment]
Really the only reason to use prepared statements is if the query clause is complex & the parse, analyze and rewrite phases take a while.  It's up to you to decide to use them.  My rule of thumb is two things. 1) premature optimization is the root of all evil. 2) I've only used them 2-3 times ever in 5 years of writing apps with node-postgres.  When the where & join clauses are sufficiently complex in a high throughput part of your app you'll see a minor difference.  For the most part you probably have bigger performance fish to fry.

**Comment by greaber** [comment]
OK, I didn't know that prepared statements were so unlikely to make a significant difference.  I won't give it a lot more thought for now.  Still it seems unfair to apply the rule "premature optimization is the root of all evil" unless there is some downside to using them, and the docs do seem to wrongly(?) suggest that using prepared statements affects whether Postgres replans each time the statement is used, no?

**Comment by abenhamdine** [comment]
@brianc, for FWIW, I add some lines in the wiki to precise the inpact of prepared statements on performance, see https://github.com/brianc/node-postgres/wiki/Prepared-Statements

**Comment by brianc** [comment]
awesome Arnaud! thanks!

On Sun, Jul 24, 2016 at 1:18 PM, Arnaud Benhamdine <notifications@github.com

**Comment by greaber** [comment]
I edited Arnaud's additions to improve the English and to add clarity about
whether prepared statements save on planning.

**Comment by abenhamdine** [comment]
ah thx you, indeed, your rewrite is more concise. I'd like my English to be better... :cry:
