### ISSUE TITLE
problems using pool syntax

### ISSUE THREAD

**Issue by tnsupport** [brianc/node-postgres#1097]
trying to use the new client pooling syntax - following the wiki page example but adding a 2nd query - docs are a bit confusing between readme and the wiki page 
- query 1 - drop table if exists
query 2 - create table 
error => syntax error around "if"

var pool = new pg.Pool(config);
createSignups = function() {
    console.log("create signups");
    pool.connect(function(err, client, done) {
      if(err) {
        return console.error('error fetching client from pool', err);
      }
      client.query('drop table signups if exists', function(err, result) {
        if(err){
          return console.error("query failed",err)
        } else {
          console.log("dropped table");
          client.query('create table signups (id serial primary key,' +
        'jsondata json)',function(err, result) {
            if (err) {
              return console.error("create table fail",err);
            } else {
              console.log("created table");
            }
          });
          done();
        }
      });
    });
  };

**Comment by brianc** [comment]
hey @tnsupport - I hate to be pedantic about this but I receive multiple issues & request for help on a nearly daily basis and having properly formatted code is something that _really_ makes triaging things easier - could you apply some [proper formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to your code? thanks!

**Comment by tnsupport** [comment]
understand - sorry github knocks out spacing  - see if this file is better.  pls feel free to use any corrections to this code in a recipe example in the wiki

[postgres-pool-chain.txt](https://github.com/brianc/node-postgres/files/391970/postgres-pool-chain.txt)

also I realize async / await will so simplify using postgres with node - we tried hard to use it with babel - but it was 3 days of total fail.

**Comment by manueltimita** [comment]
@tnsupport I think @brianc suggested formatting it using Markdown (use <> in the comment editor). 

The error you report is not a `node-postgres` issue. You got the SQL syntax wrong. Should be `drop table if exists signups`. I think the issue can be closed.

Just in case, here is the code, formatted: 

```javascript
var pool = new pg.Pool(config);

createSignups = function() {
  console.log("create signups");
  pool.connect(function(err, client, done) {
    if(err) {
      return console.error('error fetching client from pool', err);
    }
    client.query('drop table signups if exists', function(err, result) {
      if(err){
        return console.error("query failed",err)
      } else {
        console.log("dropped table");
        client.query('create table signups (id serial primary key,' +
          'jsondata json)',function(err, result) {
          if (err) {
            return console.error("create table fail",err);
          } else {
            console.log("created table");
          }
        });
        done();
      }
    });
  });
};
```

**Comment by brianc** [comment]
thanks for your help @manueltimita!
