### ISSUE TITLE
Cannot use question mark as prepared statement placeholder?

### ISSUE THREAD

**Issue by samphilipd** [brianc/node-postgres#1100]
I am converting an existing project from MySQL to Postgres. There are quite a few raw SQL literals in the code that use `?` as a placeholder, e.g. 

```sql
  SELECT
    id
  FROM
    users
  WHERE
    name = ?
```

But I get this error:

DB query error: error: operator does not exist: character varying = ?

I don't want to convert all my existing SQL from `?` to postgres-style operators like `$1`. Is there some way of having node-postgres accept the question marks instead, or a utility that can convert to postgres style params?

**Comment by brianc** [comment]
Unfortunately no. Postgres only accepts numbered parameters and not
question marks.  I'm not familiar with "ECPG" but it's not something
supported natively by the protocol or this driver. It looks specific to C.

**Comment by samphilipd** [comment]
ok thanks

**Comment by gajus** [comment]
> I don't want to convert all my existing SQL from ? to postgres-style operators like $1.

You can use https://www.npmjs.com/package/sqlstring module.

> Unfortunately no. Postgres only accepts numbered parameters and not question marks.

Whats the reason this library cannot convert `?` to `$1` before passing it to pq?

**Comment by charmander** [comment]
> You can use https://www.npmjs.com/package/sqlstring module.

That one is for MySQL.

> Whats the reason this library cannot convert ? to $1 before passing it to pq?

A placeholder inconsistent with Postgres would mean pg would have to parse the query, for practically no benefit.

**Comment by gajus** [comment]
> That one is for MySQL.

@charmander Whats the problem using it with pg? It will only touch the `?` placeholders.

**Comment by charmander** [comment]
@gajus MySQL’s string escaping is non-standard and won’t work with PostgreSQL:

```js
> console.log(SqlString.format("?", "shouldn't"));
'shouldn\'t'
```

The entire sqlstring approach is a bad one in the first place, though. Use real parameters, please.

**Comment by gajus** [comment]
```js
> console.log(SqlString.format("?", "shouldn't"));
'shouldn\'t'
```

Whats the expected output?

I am not too keen about using `$1` parameter placeholders. There is virtually no benefit to it apart from making me extra conscious of the position of the values. I will rather fork-`sqlstring` to make it work with PG.

**Comment by charmander** [comment]
> Whats the expected output?

`'shouldn''t'`, if you’re escaping, but again: don’t. It’s a terrible idea. Use parameters. You don’t have to write them manually: https://gist.github.com/charmander/8f7b05f8d2b2e4e3c190c7a9e1bec1f2

Aside: a properly fair comparison would be:

```js
query(`SELECT $1, $2, $3`, [1, 2, 3]);
```

> I can easily see the latter scenario happening as part of crappy refactoring of the codebase.

Solution: don’t do that.
