### ISSUE TITLE
Will the "end" handler be called after "error"?

### ISSUE THREAD

**Issue by mannyveloso** [brianc/node-postgres#1101]
Hi!

I'm just wondering if end is the equivalent of finally ie: will it always be called, even if there's an error?

Thanks!

**Comment by brianc** [comment]
It should be called as long as the backend sends another 'readyForQuery' message after the error. I'd recommend using a callback or promise to handle the completion (with or without error) of your query and not the `end` event, but it is there if you need it. 😄
