### ISSUE TITLE
The existence of documentation is not obvious

### ISSUE THREAD

**Issue by jameshfisher** [brianc/node-postgres#1109]
I can't see the documentation for this. There are quite a few other Postgres config options which I can't see any mention of.

**Comment by jameshfisher** [comment]
I eventually found it hidden under https://github.com/brianc/node-postgres/wiki

I'll change the task here to: making the existence of documentation more obvious

**Comment by jameshfisher** [comment]
Specifically the link is in https://github.com/brianc/node-postgres but just called "More documentation" in a random location

AFAIK it's not linked from https://www.npmjs.com/package/pg at all

**Comment by joskuijpers** [comment]
Well, it is linked in the package file, as it is just the README. Also, github wikis are for documentation, so it is quite logical.

What change would you suggest? Maybe have a PR?

**Comment by brianc** [comment]
I agree with @joskuijpers - if you think of a way to make documentation more obvious please open a PR to discuss!

**Comment by jameshfisher** [comment]
Currently the README is like

```
documentation...
documentation...
[hidden link to 99% of the documentation]
documentation...
documentation...
```

I'd suggest:

* moving all the documentation in the README to be in the wiki instead
* put the link right at the top of the readme, "Documentation" rather than "More documentation"
