### ISSUE TITLE
release() cancels further execution, thus unable to use a pool in a promise.

### ISSUE THREAD

**Issue by ghost** [brianc/node-postgres#1112]
Using the `PostgreSQL.pool(Configuration)` option and calling `connect(error, client, release)` and submitting the client and release into a promise chain causes problems when `release()` is called, because the promise cannot finish execution.

For example:

``` js
function insertX(...) {
    getConnection.then(function(client, release) {
        return new Promise(function(resolve, reject) {
            client.query('...', function(error) {
                if(error) { release(); return reject(error); }
                release();
                return resolve();
           });
       });
    });
```

The `reject/resolve` statement is never reached, as `release` terminates execution.

**Comment by brianc** [comment]
I appreciate you filing an issue here & would like to try and help; however, I receive multiple issues & request for help on a nearly daily basis and having properly formatted code is something that really makes triaging things easier - could you update your issue text by applying some [proper formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to your code? thanks!

**Comment by CTucker1327** [comment]
Done

**Comment by elmigranto** [comment]
I believe `Pool.connect` has `client.release` function, if you use promise api. And maybe same for callback one. Was changed at some point from what you wrote (client itself and release function).

**Comment by iamchenxin** [comment]
Is the `PostgreSQL.pool` means `pg.pool`(`node-pg-pool`)? 
Here is it's source code [pg/index.js#L54](https://github.com/brianc/node-pg-pool/blob/master/index.js#L54) . It only resolve a client,not a (client, release) tuple.
```
...
      if (cb) {
        cb(null, client, client.release)
      }

      return resolve(client)  // line 84
...
```
And You could add type defs to your ide or tools chain to avoid type wrong Args, TypeScript -> [TypeScript type def](https://github.com/types/npm-pg), Flow -> [Flow type def](https://github.com/brianc/node-pg-pool/pull/26/)

**Comment by charmander** [comment]
Seems like it was probably misuse of the API. The account’s been deleted, anyway.
