### ISSUE TITLE
Huge inserts fail

### ISSUE THREAD

**Issue by Rauno56** [brianc/node-postgres#1116]
I tried to paste together code from different sources and boil down the example as much as possible so I apologize for the messy code:
https://gist.github.com/Rauno56/c3369b58111ffbe17ff63d64289e4aa6
On my setup this fails with

```
bind message supplies 26784 parameters, but prepared statement "" requires 420000
```

even though parameter count and placeholder count match(see from the outputs).

If you were to change N smaller or chunk up the request it does fine. Seems like the input of parameters is cut short at some point.

**Comment by vitaly-t** [comment]
Looks like you misusing parameter formatting within Prepared Statements.

They are not meant to be used across multi-row inserts or multi-row updates.

As a result, you are hitting the limit on how many variables one can have within a Prepared Statement.

These might help:

* [multi-row inserts](http://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise)
* [multi-row updates](http://stackoverflow.com/questions/39119922/postgresql-multi-row-updates-in-node-js)

**Comment by Rauno56** [comment]
Thank you for the insightful comment.

I'm sure I'm misusing that, but as far as this module's configuration goes, it seems to be the go-to way to do it.
pg-promise has clear documentation about this - I will give that a try.

So what those examples basically do is pre-compile the query to a string outside of pg's parameterized query system, right?

**Comment by charmander** [comment]
Try arrays?

```javascript
const rows = [
    {column1: 1, column2: 2},
    …
];

const columns =
    ['column1', 'column2'].map(columnName =>
        rows.map(row => row[columnName])
    );

pool.query(`
    INSERT INTO test_table (test_column_1, test_column_2)
    SELECT * FROM UNNEST ($1, $2) AS t
`, columns)
```

**Comment by Rauno56** [comment]
Could not use UNNEST in my case as the db version was tiny bit short of supporting it. Precompiled using pg-promise's helpers. I think this limit of parameters should at least be documented and alternatives provided here, in pg module too.

Thank you very much @charmander @vitaly-t

**Comment by ugultopu** [comment]
Arrays worked like a charm, thanks @charmander ! Unrelated to this issue, I have one question that maybe you can help: I'm trying to implement an "optional upsert". That is:

- If the record does not exist, insert.
- If the record exists, for certain columns, check the parameters to understand if they should be updated. If yes, update them. Otherwise, leave them as-is.

Here's what I came up with so far:

```sql
INSERT INTO table_name (
  "col1",
  "col2",
  "col3",
  "col4",
  "col5",
  "col6",
  "col7"
)
SELECT DISTINCT
  a."col1",
  a."col2",
  a."col3",
  a."col4",
  a."col5",
  a."col6",
  a."col7"
FROM UNNEST (
  $1::uuid[],
  $2::uuid[],
  $3::numeric[],
  $4::numeric[],
  $5::boolean[],
  $6::boolean[],
  $7::timestamptz[],
  $8::boolean[],
  $9::boolean[],
  $10::boolean[]
) WITH ORDINALITY AS a(
  "col1",
  "col2",
  "col3",
  "col4",
  "col5",
  "col6",
  "col7",
  "shouldUpdateCol3",
  "shouldUpdateCol4",
  "shouldUpdateCol5",
  "ordinality"
)
ON CONFLICT
  ("col1", "col2")
DO UPDATE
SET
  "col3" = CASE WHEN EXCLUDED."shouldUpdateCol3" = TRUE THEN EXCLUDED."col3" ELSE table_name."col3" END,
  "col4" = CASE WHEN EXCLUDED."shouldUpdateCol4" = TRUE THEN EXCLUDED."col4" ELSE table_name."col4" END,
  "col5" = CASE WHEN EXCLUDED."shouldUpdateCol5" = TRUE THEN EXCLUDED."col5" ELSE table_name."col5" END,
  "col7" = EXCLUDED."col7";
```

The problem is, since `shouldUpdateCol3`, `shouldUpdateCol4` and `shouldUpdateCol5` are not selected in the `SELECT FROM UNNEST` above, this does not work.

However, if I add them to the `SELECT FROM UNNEST`, then I get `INSERT has more expressions than target columns` error.

Do you know how I can accomplish this?
