### ISSUE TITLE
Custom parser for JSON.parse

### ISSUE THREAD

**Issue by pankleks** [brianc/node-postgres#1122]
Hello,

Is there a way to provide custom parser for JSON.parse you use during deserializing JSONB columns?

**Comment by pankleks** [comment]
Any solution?

**Comment by brianc** [comment]
Take a look at [pg-types](https://github.com/brianc/node-pg-types) - should
have all the info you need.

**Comment by joskuijpers** [comment]
You can re-register (overwrite) the parsers used for json(b).
The numbers are here: https://github.com/brianc/node-pg-types/blob/master/lib/textParsers.js#L170
How to set your own parser is described in the readme: https://github.com/brianc/node-pg-types/blob/master/README.md
