### ISSUE TITLE
please, does it support the search of array?

### ISSUE THREAD

**Issue by senlin-wei** [brianc/node-postgres#1124]
such as search from this data, by the id(d908d364-fc63-4019-a712-da8d0eca5539) under the category:
{
        "id": "74caf3f3-87b2-4e85-8a71-f9036290463b",
        "markets": [
          {
            "code"    : "1",
            "id"      : "656b9e1e-79cd-bd8e-1474-a76321a0c732",
            "name"    : "CA - Los Angeles",
            "rank"    : 0
          }
        ],
        "category": [
          {
            "code": "FLO",
            "id": "d908d364-fc63-4019-a712-da8d0eca5539",
            "name": "Florists"
          },
          {
            "code": "FLO",
            "id": "d908d364-fc63-3333-a712-da8d0eca3333",
            "name": "Florists"
          }
        ]
}

**Comment by abenhamdine** [comment]
This module is nothing but a driver for postgres, so if you want to perform some search into the database, you must use a sql clause, such as WHERE... or a json operator if your column has a jsonb datatype.
You should read postgres official documentation : https://www.postgresql.org/docs/9.5/static/functions-json.html

**Comment by brianc** [comment]
Thanks for the help @abenhamdine !
