### ISSUE TITLE
Release client or connection to pool ?

### ISSUE THREAD

**Issue by Brakkar** [brianc/node-postgres#1125]
Hello,

here is my (simplified) setup into a dbsql.js file:

```
var Pool = require( "pg-pool" )
var PgNativeClient = require( "pg-native" )
var pgNativePool   = new Pool( { "Client": PgNativeClient } )

const dbConfig = {
    "user"             : "adminator",
    "database"         : "dbname",
    "port"             : 5432,
    "max"              : 10, // max number of clients in the pool
    "idleTimeoutMillis": 30000 
}
const dbPool = new Pool( dbConfig )

// Later in code:
 dbPool.query( sqlQuery, function( err, result ) {
        // handle an error and callback here
    } )

```

My first question, is: is this properly setup to handled a native pooled connexion ?
Secondly, I don't see how to release the client to the pool ? In setup here https://github.com/brianc/node-postgres there is a 'done()' method to be called to release it, but in my example, I don't see how this is handled. Shouldn't it be handled? Won't this setup cause the max number of clients to be consumed rapidly ?

**Comment by abenhamdine** [comment]
The done() method is provided by the dbPool.connect() call.
You need first to acquire a client from the pool like this : 

```javascript
dbPool.connect(function(errConnect, client, done) {

    client.query(sqlQuery, function(err, result) {
        
        done(); // release the client to the pool here

        // etc
    });
});
```

**Comment by joskuijpers** [comment]
Also, realise that in your code sample you created two pools. One with the Client set and one with the other options. Your pgNativePool variable is unused.

**Comment by Brakkar** [comment]
Thanks for your comments. Here is my new configuration:

```
const pg   = require( "pg" ).native
const pool = pg.Pool

const dbConfig = {
    "user"             : "admin",
    "database"         : "********",
    "port"             : 5432,
    "max"              : 10, // max number of clients in the pool
    "idleTimeoutMillis": 30000 // how long a client is allowed to remain idle before being closed
}

export const dbPool = new pool( dbConfig )
```



and then I have various usage of this such as:

```
export function listGenericQuery( res, sqlQuery: string, callback: Function ) {
    
    // Get list of records
    dbPool.query( sqlQuery, function( err, result ) {
        if ( !L.isEmpty( err ) ) {
           //code......
        }
        
        const records = result.rows
        
        callback( res, records )
    } )
}
```

As you can see I don't "close" with done() anywhere. But I remember reading it's not necessary with pool because it take care of this. Can you please confirm this code is ok without explicit done() ?

Forgive my paranoia but this will soon go production.

Thanks
