### ISSUE TITLE
Transaction with Bluebird. How to use this?

### ISSUE THREAD

**Issue by joseCocodin** [brianc/node-postgres#1126]
```
function withTransaction(fn) {
  return Promise.using(pool.acquireConnection(), function(connection) {
    var tx = connection.beginTransaction()
    return Promise
      .try(fn, tx)
      .then(function(res) { return connection.commit().thenReturn(res) },
            function(err) {
              return connection.rollback()
                     .catch(function(e) {/* maybe add the rollback error to err */})
                     .thenThrow(err);
            });
  });
}
```

**Comment by joseCocodin** [comment]
Solution:
´´´
Promise.promisifyAll(pg, {
    multiArgs: true
});

var transaction = function (fn) {
    return Promise.using(this.pool.connect(), function (connection) {
        return Promise.try(function() {
            return connection.queryAsync('BEGIN').then(function () {
                return fn(connection);
            });
        })
        .then(function (res) {
            return connection.queryAsync('COMMIT').then(function () {
                connection.release();
                return res;
            });
        })
        .catch(function (err) {
            return connection.queryAsync('ROLLBACK').then(function () {
                connection.release();
                throw err;
            })
        });
    });
};

transaction(function (client) {
    return connection.queryAsync(anyQuery).then(function () {
         return connection.queryAsync(anyQuery);
    })
});
´´´

**Comment by vitaly-t** [comment]
You can get a better answer to this by publishing your question on StackOverflow, because the author here has objections to publishing any references to modules that can solve it, that's why I won't put here.
