### ISSUE TITLE
Anonymous Code Block $ Escaping - Error "syntax error at or near "BEGIN""

### ISSUE THREAD

**Issue by LeeGDavis** [brianc/node-postgres#1129]
Hi I'm trying to perform an anonymous code block, but having issues which I believe may be related to escaping bind parameters/parameterized query

Using Postgres 9.5
This works fine when using a non parameterized query and less the escaping of the dollar signs (which I believe I have done incorrectly) on the `DO` and `END`, so curious why I receive the error, "syntax error at or near "BEGIN"" on the query below. I hope it is a simple matter of not escaping the dollar signs correctly, but I'm not sure.

```
DO $$$$
BEGIN
  IF EXISTS (
    SELECT id
    FROM mytable mt
    WHERE mt.name = "ScrappyDoo"
  )
  THEN
    INSERT INTO myothertable (type, name) VALUES ($1, $2);
  ELSE
    INSERT INTO myothertable (type, name) VALUES ($1, $2);
  END IF;
END $$$$;
```

**Comment by brianc** [comment]
Postgres does not support multiple statements in a single query using
parameters. You need to issue each statement with separate call to
client.query.

**Comment by LeeGDavis** [comment]
Thanks @brianc. I was hoping to get around this with an anonymous function.

**Comment by terehov** [comment]
Hey brianc, 

thanks a lot for your great work. I really enjoy using `node-postgres`, usually without any problems. 
However this time I have really a hard time figuring out, how I can create a PLSQL function through `node-postgres`. 
Postico seems to create this function without any problems, however not thorugh `node-postgres`. My use case is quite similar to the one above. 
A function, that reads data and reacts to it. 
I am getting your answer, but I don't understand how to get around it. 

Thanks!

**Comment by charmander** [comment]
@terehov Can you show your attempt?

**Comment by terehov** [comment]
@charmander Thanks.
Is a bit hard to extract, but here we do: 

```
try {
      await dbClient.query(`-- current_user_id function returns the id of the current user if the transaction_token is present and valid
CREATE OR REPLACE FUNCTION _meta.current_user_id() RETURNS uuid AS $BODY$
DECLARE
    v_transaction_token_secret TEXT;
    v_transaction_token TEXT;
    v_parts TEXT[];
    v_user_id TEXT;
    v_timestamp BIGINT;
    v_signature TEXT;
    v_payload TEXT;
BEGIN
    -- Get required values from Auth-table
    SELECT value INTO v_transaction_token_secret FROM _meta."Auth" WHERE key = 'transaction_token_secret';

    -- Read the transaction_token from local variable.
    v_transaction_token := current_setting('auth.transaction_token', true);

    -- Checks that the local variable is not null
    IF v_transaction_token IS NULL THEN
        RAISE EXCEPTION 'Session expired or token invalid.';
    END IF;

    -- Split the token into its parts.
    v_parts := regexp_split_to_array(v_transaction_token, ':');

    -- A transaction_token needs to have 3 parts
    IF array_length(v_parts, 1) != 3 THEN
    	RAISE EXCEPTION 'Session expired or token invalid.';
    END IF;

    -- Write parts into function-variables
    v_user_id := v_parts[1];
    v_timestamp := v_parts[2];
    v_signature := v_parts[3];

    -- Check if the variables are not null
    IF v_user_id IS NULL OR v_timestamp IS NULL OR v_signature IS NULL THEN
        RAISE EXCEPTION 'Session expired or token invalid.';
    END IF;

    -- Recreate the signature-payload to verify token
    v_payload := v_user_id || ':' || v_timestamp || ':' || txid_current() || v_transaction_token_secret;

    -- Hash payload and check if it matches the token-signature
    IF v_signature = encode(digest(v_payload, 'sha256'), 'hex') THEN
        -- If valid return the userId
        RETURN v_user_id::uuid;
    END IF;

    -- Raise exeption because the token is not valid.
    RAISE EXCEPTION 'Session expired or token invalid.';
END;
$BODY$ LANGUAGE plpgsql SECURITY DEFINER STABLE;`);
    } catch (err) {
      console.error(err);
    }
```

Error:
```
{ error: syntax error at or near "  "
    at Connection.parseE (/.../packages/db/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/.../packages/db/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/.../packages/db/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
  name: 'error',
  length: 95,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '1636',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1086',
  routine: 'scanner_yyerror' }
```

**Comment by charmander** [comment]
@terehov That query doesn’t produce an error for me. Are you sure it’s enough on its own? You might want to open a new issue, too.

**Comment by terehov** [comment]
@charmander Oh wow, so you managed to get it run through `pg` `query`? 
Which version did you use? I am using (afaik the latest) 7.4.1.

I am quite positive that this is enough for reproducing it. 

Yeah, I though of creating a new you, but I figured it's pretty much the same as the one above and didn't want to pollute with another issue.

**Comment by charmander** [comment]
@terehov I used 7.4.1 too. If the query comes from one of the files you mentioned, could you upload the file and a checksum?

**Comment by terehov** [comment]
@charmander Thank you so much for your efforts! 
We literally just figured out the problem. There were some invisible utf8 chars hiding, that apparently sneaked in with a copy&paste. 🧐
