### ISSUE TITLE
Promise { <pending> }

### ISSUE THREAD

**Issue by tnsupport** [brianc/node-postgres#1130]
we added a new query in some existing code and now get an error:

// ---from model.js
var pg = require('pg');
var jwt = require('jsonwebtoken');
var bcrypt = require('bcrypt');
var Pool = require('pg').Pool;

var connectString = {user:"xxx", password:"xxx",
    host:"localhost", database:"xxx"};
var pool = new Pool(connectString);
var exports = module.exports = {};

exports.signupsInactiveList = function() {
  var data = pool.query("select * from signups");
  return data;
}

// ---from test.js script:
var res = model.signupsInactiveList();
console.log(res);

all that is returned is the following: 
Promise { <pending> }

since we are not specifying any promises, don't know where this is coming from except maybe in the node v6.5 or in the pg pooling - any ideas ?

**Comment by joskuijpers** [comment]
Pool.query returns a promise. You will need to wait for it to fulfill before printing the result.

```
Model.signupInactiveList().then((data) => console.log(data))```

> On Sep 16, 2016, at 5:24 PM, tnsupport <notifications@github.com> wrote:
> 
> we added a new query in some existing code and now get an error:
> 
> // ---from model.js
> var pg = require('pg');
> var jwt = require('jsonwebtoken');
> var bcrypt = require('bcrypt');
> var Pool = require('pg').Pool;
> 
> var connectString = {user:"xxx", password:"xxx",
> host:"localhost", database:"xxx"};
> var pool = new Pool(connectString);
> var exports = module.exports = {};
> 
> exports.signupsInactiveList = function() {
> var data = pool.query("select * from signups");
> return data;
> }
> 
> // ---from test.js script:
> var res = model.signupsInactiveList();
> console.log(res);
> 
> all that is returned is the following: 
> Promise { }
> 
> since we are not specifying any promises, don't know where this is coming from except maybe in the node v6.5 or in the pg pooling - any ideas ?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

**Comment by felixfbecker** [comment]
This is not 100% correct. query() returns a `Query` object, which is an `EventEmitter`, but also implements a `Promise` interface (aka `Thenable`).

**Comment by menasheh** [comment]
I'm having this same problem now.  How do you get it to wait for the query to fill exactly?

**Comment by felixfbecker** [comment]
Either pass a callback as the last parameter to `query()` or attach a handler with `.then()` on the return value

**Comment by joskuijpers** [comment]
WHat @felixfbecker said. Either use a callback (and use a callback in signupsInactiveList), use Promises and return a promise, or use async/await.
