### ISSUE TITLE
Column names and types for queries with 0 result rows

### ISSUE THREAD

**Issue by rightfold** [brianc/node-postgres#1132]
Is it possible to get the column names and types of the result of an arbitrary query when there are 0 rows in the result? The wiki suggests looking at `rows[0]` but that only works when there is at least one row.

**Comment by vitaly-t** [comment]
`result.fields` contains all the columns information.

**Comment by rightfold** [comment]
Ah, very nice. I'll check that out. Should I update the wiki?
