### ISSUE TITLE
Q: Using custom session param and pooling

### ISSUE THREAD

**Issue by zam6ak** [brianc/node-postgres#1134]
Hi

This is a more of a question, than an issue but I think it may be common one...
I would like to use [PG custom params](https://www.postgresql.org/docs/current/static/runtime-config-custom.html) to capture application user id so it is available to DB level functionality (e.g. triggers).

So, I can do something like 
`set session "myapp.current_user_id" = 1;`

and then later retrieve it by 
`select current_setting('myapp.current_user_id')::int`

Since the driver uses pooling, I would assume, that I cannot set session once (e.g. after user logs in) but during each query......
Is this correct? 

If it is, does driver provide any functionality in this respect to be able to easily specify the key and value of the session param to be set or would I have to call "set session" before each select, insert, update and delete....?

Thanks
Z

**Comment by joskuijpers** [comment]
What I do:
When a new request arrives, I create/get a connection. Then I execute the `set X` query. Then any query after that uses this setting. When the request finishes I end the connection.

No, you don't need to do it before every insert, update or select but you do need it after every connect() or new Client().

So no, 'after the use logs in' is not a thing. You need to set it every time you open a connection (or acquire a connection as you don't know when it is a new or old session).

**Comment by zam6ak** [comment]
Aren't connections pooled and reused? What if, in addition, PgBouncer is used?
If I set user_id at the connection time, and connection is re-used, then wouldn't that mess things up?

**Comment by joskuijpers** [comment]
If PgBouncer is used the situation is completely different.
What I suggested it setting it every time you make a client side 'connection'. This 'connection' is either a fresh connection to the DB server, a connection to pgbouncer or a pooled connection.
So you always set the session value when you start using it (again).

**Comment by zam6ak** [comment]
@joskuijpers Thanks. Does that imply I cannot use convenience api like `pool.query(...)` or ?

**Comment by joskuijpers** [comment]
Yes, it does.
