### ISSUE TITLE
to_date(string, format)

### ISSUE THREAD

**Issue by deejaygeekout** [brianc/node-postgres#1135]
VALUES ($1, $2, $3, $4, to_date($5, 'MM/DD/YY') ..........

Cannot use single quote
Cannot use double quote and will treat as new column.

Any help? following this 

https://www.postgresql.org/docs/7.4/static/functions-formatting.html

**Comment by joskuijpers** [comment]
Why cant you use single quote?

```
Query(".... VALUES (....., to_date($5, 'MM/DD/YY')")
```

**Comment by joskuijpers** [comment]
@deejaygeekout Did you try this out? You should use single quotes for all string values. So use double quotes are backticks around your queries.
