### ISSUE TITLE
Using 'pg' in webpack to Electron return an error trying to requiring pg-native.

### ISSUE THREAD

**Issue by michaeljota** [brianc/node-postgres#1138]
Hi! 

I'm trying to use this bundled with webpack to be used in electron. But it tries to import the pg-native module. I really don't know how to use the native binding in Electron, but at least I would like to be able to use the plain JS driver. 

I read #127 and #838, and commenting the lines mentioned [here](https://github.com/brianc/node-postgres/issues/838#issuecomment-148373862) makes the package works, but I see this most like a workarround. The problem it's not gone, just hided. 

Thanks!

EDIT: You can test this [here](https://github.com/michaeljota/ng2-admin/tree/feature/postgres)

`npm run build:electron`

Main and Renderer process will be packaged in separated files. The Renderer part will be packaged correctly, but when it tries to bundle the Main part the error will be thrown.

**Comment by alexpanov** [comment]
I'm shocked and confused that it's not yet been fixed

**Comment by rozzzly** [comment]
aaaaaaaaaaand its still not. Nor can I find any workarounds :(

**Comment by michaeljota** [comment]
@rozzzly for workarounds you can comment some lines as I said in the description.

**Comment by charmander** [comment]
Does making `pg/native` part of `externals` in the webpack configuration work?

```js
externals: [
    "pg/native",
],
```

**Comment by bkniffler** [comment]
Just tested @charmander solution with Electron, having suffered from the same issue like @michaeljota, works great! I think this should be noticed in the docs and this issue can be closed.

**Comment by evbo** [comment]
As of pg `8.2.1`, I am using this webpack config workaround, which hopefully most can stomach until a permanent fix is released: 
https://github.com/brianc/node-postgres/issues/838#issuecomment-405646013

**Comment by michaeljota** [comment]
Seems like this is the actual solution we need, so I'll close this.
