### ISSUE TITLE
What is the timeout of the client.query() callback?

### ISSUE THREAD

**Issue by christiansaiki** [brianc/node-postgres#1139]
Hey guys, I'm doing an unload in AWS Redshift.
When I'm doing an unload of a small dataset, it usually takes about 5 minutes and I've got a response of client.query() callback.
But when I'm doing an unload of a huge dataset it usually takes about 30 minutes and I never get the client.query() callback. 
Where can I set this timeout? I'd really like to know when the unload has finished.
Thanks.

**Comment by brianc** [comment]
node-postgres doesn't ever time anything out - it could be something built
in to redshift, but I'm not 100% familiar w/ redshift, sorry!

**Comment by christiansaiki** [comment]
Thanks Brian.
I'll try to figure this out.
