### ISSUE TITLE
Cannot find module 'pg-native'

### ISSUE THREAD

**Issue by ashnamuh** [brianc/node-postgres#1140]
I wanted to attach a sentry on the nodejs server that use the Express. So i looked at the [manual](https://docs.sentry.io/clients/node/integrations/express/) and followed. but the error occurred. What's the problem? I'm using the Express `v4.13.4`, node `v4.4.2`.

![image](https://cloud.githubusercontent.com/assets/14067417/18980389/9fa32ba0-870e-11e6-8987-62515cf9d1b2.png)

**Comment by ashnamuh** [comment]
Sorry. It's my mistake.

**Comment by asifrahman001** [comment]
@ashnamuh I am also getting similar error. Can you please tell how was it solved?
