### ISSUE TITLE
?? Where is a simple example of a 'like' query ?!

### ISSUE THREAD

**Issue by rw3iss** [brianc/node-postgres#1144]
Can't figure it out...

select * from blah where name like '%%$1%%' 

will not work... escaping the quotes or anything will not work, I'm assuming cause it's producing something like:
select * from blah where name like '%%'param'%%' 

?

**Comment by ravshansbox** [comment]
maybe 'select * from blah where name like %$1%' ?

**Comment by rw3iss** [comment]
Tried that too, postgres requires the %% I think, but neither work.

**Comment by hoegaarden** [comment]
You need to use `select * from blah where name like $1` and feed `$1` as `%something%` to your prepared statement.

Also postgres uses single `%` for the `LIKE` operator, see [here](https://www.postgresql.org/docs/9.5/static/functions-matching.html).

**Comment by rw3iss** [comment]
Thanks.
Just figured it out, heh. 

queryString = '%%'+queryString+'%%';
var query = "SELECT * from users where email like $1";

**Comment by rw3iss** [comment]
Note that using '%'+queryString+'%' OR '%%'+queryString+'%%' both seem to work the same, oddly enough.

**Comment by hoegaarden** [comment]
> [...] a percent sign (%) matches any sequence of zero or more characters

So there is no real difference between `%`, `%%`, `%%%`, ... in this context.

**Comment by rw3iss** [comment]
Ah right, duh. :p
