### ISSUE TITLE
when a user is logined through the redis session, "Cannot find module 'pg-native'" error occurred

### ISSUE THREAD

**Issue by ashnamuh** [brianc/node-postgres#1145]
related #210 

I'm using nodejs server with express. I wanted to attach a sentry on the server to trace some errors. So i looked at the [manual](https://docs.sentry.io/clients/node/integrations/express/) and followed. But the following error occurred. I had thought the error is my mistake. But i found the error occurred when a user is logined through the redis session. What's the problem? I'm using the Express `v4.13.4`, node `v4.4.2`, npm `v3.10.8`, sequelize `v3.24.3` and pg `v6.1.0`. I need your help!

![image](https://cloud.githubusercontent.com/assets/14067417/19228812/ab0ed58c-8f03-11e6-8260-a82fe9ef3c7e.png)

my app configuration:
```
const express = require('express');
const expressSession = require('express-session');
const raven = require('raven');

const app = express();

app.use(expressSession({
  secret: appConfig.sessionSecret,
  resave: false,
  saveUninitialized: false,
  store: new RedisStore({pass: appConfig.redisPass})
}));

app.use(raven.middleware.express.requestHandler(appConfig.sentryDSN));

/*
middlewares: routes, passport, etc.
*/

app.use(raven.middleware.express.errorHandler(appConfig.sentryDSN));

app.use(handleResponse); // fallthrough error handler
```

If i clean up the `RedisStore` line, Raven is working right. But login is not available.

**Comment by ashnamuh** [comment]
I opened [the same issue](https://github.com/getsentry/raven-node/issues/212) on raven-node's repo. contributor of raven-node said It looks directly like your project is using pg.

**Comment by brianc** [comment]
Looks like raven is requiring `pg-native` for some reason.  You might need to install `pg-native` or update raven to put it in its `package.json` file.
