### ISSUE TITLE
How to insert if not exist?

### ISSUE THREAD

**Issue by crosofg** [brianc/node-postgres#1149]
I tried 
```
 client.query({
      text: 'INSERT INTO users(fbid, name) VALUES($1,$2) '+
            'WHERE NOT EXISTS (SELECT * FROM users WHERE fbid=($1))',
      values:[id,"tom"]});

```
it gives the error 
```
error: syntax error at or near "WHERE"
```
What is wrong here?

**Comment by crosofg** [comment]
tried this
```
  client.query({
      text: ' IF NOT EXISTS(SELECT * FROM users WHERE fbid=($1)) THEN INSERT INTO users(fbid, name) VALUES($1,$2) END IF',
      values:[id,"tom"]});
```
got this
```
error: syntax error at or near "IF"
```

**Comment by erikkrietsch** [comment]
The queries you're trying to execute are not valid SQL. You might try vetting your commands via `psql` prior to embedding them in your application.

To solve your problem, consider using the ["UPSERT"](https://wiki.postgresql.org/wiki/UPSERT) command.

In your case it would look something like this:

```SQL
INSERT INTO users (fbid, name) VALUES (1, 'tom')
ON CONFLICT DO NOTHING;
```

In any case, this is not an issue with the `node-postgres` codebase.

**Comment by crosofg** [comment]
Thanks Closing
