### ISSUE TITLE
DeprecationWarning: using Buffer without 'new'

### ISSUE THREAD

**Issue by leroydev** [brianc/node-postgres#1158]
In Node.js v7.x (which is nowadays the 'current' Node.js branch), a `DeprecationWarning` is shown because of [line 299 of connection.js](https://github.com/brianc/node-postgres/blob/master/lib/connection.js#L299). 

Not a huge problem for now, but would be nice to get rid off I think. :)

Stacktrace:

```
DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
    at Buffer (buffer.js:79:13)
    at Object.<anonymous> (C:\project\node_modules\pg\lib\connection.js:299:19)
```

**Edit**: looks like this is already getting fixed by either #1156 or #1154, my bad!

**Comment by brianc** [comment]
I appreciate the report - it should be fixed soon!

**Comment by abduncan** [comment]
Did this ever get fixed?

**Comment by Zabanaa** [comment]
Still happening to me. I'm using node 7.1.0.

**Comment by leroydev** [comment]
@abduncan Not yet as far as I know. I don't know why this issue was closed.

**Comment by inergy** [comment]
https://github.com/brianc/node-postgres/issues/1163

**Comment by unstephenk** [comment]
Stil having issues with this...

**Comment by charmander** [comment]
@Zabanaa @unstephenk Upgrade to Node 7.1.2.

**Comment by GastonRosso** [comment]
@charmander  I'm on 7.2.0

**Comment by charmander** [comment]
@GastonRosso Sorry, that was a typo; upgrade to 7.2.1.

**Comment by kpturner** [comment]
I am using V7.7.3 and I still get this warning
