### ISSUE TITLE
Q: how to pass the record type

### ISSUE THREAD

**Issue by hoopsoul** [brianc/node-postgres#1161]
hi, could you please tell me how to pass record type in parameter as following? Thanks a lot.
e.g. I have an array [[1, 'John'], [2, 'Jack']], how to pass to query 

``` node
client.query(`
select * from test
where (id, name) = ANY($1)`,  [?]
)
```

as execute

``` sql
select * from test
where (id, name) = ANY(array[(1,'John'), (2,'Jack')])
;
```

Regards

**Comment by rpedela** [comment]
You can use [https://github.com/datalanche/node-pg-format](node-pg-format) to get the desired SQL in your example, but I am not sure it is valid. If not, please open an issue for the library and maybe we can figure out a way to support your use case.

```js
var pg = require('pg');
pg.format = require('pg-format');
var arr = [[1, 'John'], [2, 'Jack']];
console.log(pg.format('SELECT * FROM test WHERE (id, name) = ANY(ARRAY[%L])', arr));
```

**Comment by hoopsoul** [comment]
Thanks, there may be still some problem, I opened an issue here https://github.com/datalanche/node-pg-format/issues/7

**Comment by brianc** [comment]
Closing as it looks like this was fixed in the other repo.
