### ISSUE TITLE
support for promise based for the new async await

### ISSUE THREAD

**Issue by born2net** [brianc/node-postgres#1162]
I was wondering if there is going to be pure promise support version of this library for the new async await, that by the way is already supported in typescript 2.1 now.

tx for a great project,

Sean

**Comment by lalitkapoor** [comment]
@born2net checkout https://github.com/lalitkapoor/node-pg-util

**Comment by born2net** [comment]
ok this is awesome  do you think this will also work with the version of async await in typescript 2.1

**Comment by lalitkapoor** [comment]
I don't see why not.

**Comment by born2net** [comment]
tx man,
not sure if you are into Angular2, but if you are, check me out:

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by lalitkapoor** [comment]
I'll check it out, thanks @born2net

**Comment by Brakkar** [comment]
Still, it would be good to have the official release and doc support he async / await way please.
