### ISSUE TITLE
DeprecationWarning: Using Buffer without `new` will soon stop working.

### ISSUE THREAD

**Issue by muxahuk** [brianc/node-postgres#1163]
node v 7.0.0

Getting warning:
```
(node:8628) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
```
from these line
```javascript
// lib/connection.js line: 299
var emptyBuffer = Buffer(0);
```

**Comment by alpertuna** [comment]
+1

**Comment by kristijanhusak** [comment]
+1

**Comment by TyrfingMjolnir** [comment]
It's flooding my logs, how do I fix this?

**Comment by alpertuna** [comment]
@TyrfingMjolnir
To hide deprecation warning temporary, you may use `node` with `--no-warnings` argument.

**Comment by tclzcja** [comment]
+1

**Comment by EmixMaxime** [comment]
@alpertuna thanks

**Comment by alpertuna** [comment]
It looks warning is over with Nodejs **7.2.1**

**Comment by noinkling** [comment]
@alpertuna Can confirm, thanks for the heads-up.

**Comment by charmander** [comment]
The warning is removed with Node 7.2.1, and some variant of #1154 should take care of the cause.
