### ISSUE TITLE
Accessing datas on the client side 

### ISSUE THREAD

**Issue by antmag** [brianc/node-postgres#1164]
Hello,

I would like to use datas from the databse on my dashboard (html on client side)
Is it possible to access pg variable directly on client side (write and read in the database)

Thanks in advance

Antoine

**Comment by joskuijpers** [comment]
Hi,

Yes this is possible and no you should not be doing this. It is completely unsafe. You should build a middlelayer that talks to the database on the serverside.

**Comment by antmag** [comment]
Thanks a lot :)
What do you mean about middlelayer? Socket.io?

**Comment by joskuijpers** [comment]
I mean a webserver. If you want it real time you could use socket.io on that server
