### ISSUE TITLE
Writing 80K bytea columns

### ISSUE THREAD

**Issue by jdabbs003** [brianc/node-postgres#1166]
I'm trying to insert a row with a bytea column, using a Uint8Array variable.

`pool.queryPool
(
"INSERT INTO DeviceOS (elf_file) VALUES($1::bytea)",
[elf_file],
function(err, result) {...});`

`elf_file` is a `Uint8Array`

The operation fails.  In the callback:
`err.code` ends up being `'22001'`
`err.message` ends up being `'value too long for type character varying(1024)'`

Is this a bug or operator error?  Is `Uint8Array` not a valid type for a **bytea** field?

**Comment by jdabbs003** [comment]
Actually, `elf_file `can be a `Uint8Array` or a `Buffer`.  Same result.  In this case, it's about 80,000 bytes long.

**Comment by rpedela** [comment]
What is your table's schema?

**Comment by jdabbs003** [comment]
**elf_file** is a **bytea** column, Not Null with extended storage.  The other fields are an integer, a bigint, and a character varying 32.

**Comment by rpedela** [comment]
Can you provide a simple but complete example? Can you provide the full psql output for ```\d DeviceOS```

**Comment by charmander** [comment]
`bytea`s need to be passed as `Buffer`s (currently). `Uint8Array`s will be converted to strings (JSON-encoded, specifically) and give unexpected results.
