### ISSUE TITLE
postgres asks me for the password of another user?

### ISSUE THREAD

**Issue by VulcanRav** [brianc/node-postgres#1168]
Hello, I'm pretty new to databases, so I hope I'm not making a stupid question.

By the way, in my app.js file I create a variable to handle connection with the database:

> var connect = "postgres://testadmin:123456@localhost/recipedb";

recipedb is the database, testadmin is the user, 123456 is the password.

Problem is that when I make a request that requires interacting with the server my app crashes asking me for the password of another user:

>/home/aquazi/Desktop/recipe/app.js:32
> 	  if (err) throw err;
> 	           ^
> 
> error: password authentication failed for user "aquazi"
>     at Connection.parseE (/home/aquazi/Desktop/recipe/node_modules/pg/lib/connection.js:554:11)
>     at Connection.parseMessage (/home/aquazi/Desktop/recipe/node_modules/pg/lib/connection.js:381:17)
>     at Socket.<anonymous> (/home/aquazi/Desktop/recipe/node_modules/pg/lib/connection.js:117:22)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:176:18)
>     at Socket.Readable.push (_stream_readable.js:134:10)
>     at TCP.onread (net.js:551:20)

node is 7.1.0, node-postgres latest version, ubuntu 16.04 if it helps

**Comment by robotmayo** [comment]
Does connecting to the database work using PSQL cli tool?

**Comment by lalitkapoor** [comment]
can you share the rest of your code? How are you making a connection to postgres? are you passing the connect variable in to the `pg.connect` function?

**Comment by VulcanRav** [comment]
I'm starting to think that the problem is on me not really understanding the whole connection and communication process (I don't really understand if it is node speaking to the database or if it is the client speaking to the database). I guess it's the server speaking with the database, while the user speaks to the server.

> Does connecting to the database work using PSQL cli tool?

Yes, so does creating a pool connection like in the wiki, it logs with the role I supply him.

This is my code:

```
var connect = "postgres://testadmin:123456@localhost/recipedb";

// executed when root is requested
app.get("/", function (req, res){
    connect.connect(function (err) { // here uses the var connect from before
      if (err) throw err;
      client.query('SELECT * FROM recipes', function (err, result) 
       {if (err) throw err;
        client.end(function (err) {
          if (err) throw err;}); // Ends query function
  }); // Ends connect function
}); // Ends app getfunction (req, res)

```
According to the wiki..it should work..https://github.com/brianc/node-postgres/wiki/Client

But I'm always asked for the password of another role, which is not _testadmin_.

**Comment by lalitkapoor** [comment]
@VulcanRav that code doesn't quite make sense to me.

connect is a string so I don't understand how you are using `connect.connect`. Did you mean `pg.connect(connect, function(error, client done) {`?

Please take a look at some examples online - checkout - https://blog.risingstack.com/node-js-database-tutorial/

**Comment by chrisegner** [comment]
Connection strings are no longer supported it seems.  Switching back to nodejs prior to 6 "fixes" this.  See https://github.com/brianc/node-postgres/issues/1141.  Just spent a few hours on this.  Error message is a red herring.
