### ISSUE TITLE
I'm back

### ISSUE THREAD

**Issue by brianc** [brianc/node-postgres#1173]
Howdy -

I'm back from a very long and very much overdue vacation.  @joskuijpers and I will be spending a few hours this weekend tidying things up & getting some long pending pull requests merged in.  Thanks for your patience!

**Comment by abenhamdine** [comment]
To be frank, I was getting concerned, fearing for an "OSS fatigue".
Hang in there !

**Comment by brianc** [comment]
Thanks! There was some of that, but not enough to knock me down completely - just needed a break.  I could definitely use a few more maintainers help on this project - that invitation always stands. :) ❤️

**Comment by vitaly-t** [comment]
How is it going so far? 😉 

😜

**Comment by brianc** [comment]
Thanks for asking! My parents came to visit this weekend actually so I'm not gonna have time until probably Tuesday or Wednesday of this week.  Also open to pull requests to help fix the build too - I'm honestly not sure exactly what's going on with it yet - will know a lot more once I can sit down for a few hours and look.

**Comment by brianc** [comment]
K got a few things knocked out & am re-running tests on the pending PRs here so when I go through them on Tuesday it'll be easier to figure out what is working now! be back soon!
