### ISSUE TITLE
Select Query removes back slashes in the output

### ISSUE THREAD

**Issue by SathishRaju** [brianc/node-postgres#1174]
I have some urls stored in one of the columns. When selecting data, it removes the back slashes (\) in the result. Could you please let me know if there is any defaults i need to change before querying?

**Comment by joskuijpers** [comment]
What is the type of the column you store the data in?

**Comment by SathishRaju** [comment]
It is varchar(100)

**Comment by charmander** [comment]
How are you making the query, and how are you determining that the values in the database contain backslashes?
