### ISSUE TITLE
Parameter passing in the query of COPY.

### ISSUE THREAD

**Issue by hk768** [brianc/node-postgres#1176]
`pool.query("COPY (SELECT column_name FORM my_table WHERE id = ANY($1)) TO 'file_pathname' DELIMITER ','", [ids], function (err, result) {console.log(err});`
err: bind message supplies 1 parameter, but prepared statement "" requires 0.

**Comment by brianc** [comment]
I don't think the copy command accepts parameterized sql.  That's a postgres thing, not a node-postgres thing. :smile:
