### ISSUE TITLE
how to connect to cloud postgre db from node js

### ISSUE THREAD

**Issue by k07** [brianc/node-postgres#1181]
my code :
 var pg = require("pg");
        var conString = "pg://cbde5a4cc4b3a@ https://phppgadmin-xxx-pr.ice.predix.io/:5433/dd6ba4d649a161f";
 	var client = new pg.Client(conString);
	client.connect();

**500 internal server error**

**Comment by charmander** [comment]
That connection string isn’t well-formed. See https://www.postgresql.org/docs/9.6/static/libpq-connect.html#LIBPQ-CONNSTRING for the correct syntax.
