### ISSUE TITLE
Working with = ANY ($1) with array binding fails in Redshift

### ISSUE THREAD

**Issue by keithrz** [brianc/node-postgres#1186]
Here is my test.  Apologies, I don't have a Redshift database available that you can use to test.  You'll need a Redshift database with table "table_with_ids" with column "my_id" and 2 rows:

my_id
----
1
2

Here is my code:
```
const pg = require('pg');

const query = `
   SELECT count(1) 
     FROM table_with_ids
    WHERE my_id = ANY ($1)`;

const config = {
    // need connection to Redshift database...
};

// instantiate a new client with config
const client = new pg.Client(config);

const bindVars = [[1,2]];

// connect to our database
client.connect((err) => {
    if (err) throw err;

    // execute a query on our database
    client.query(query, bindVars, (err2, result) => {
        if (err2) {
            console.log(err2.detail); // shows odd error
            throw err2;
        }

        // just print the result to the console
        console.log(result.rows[0]); // should output: { count: 2 }

        // disconnect the client
        client.end((err3) => {
            if (err3) throw err3;
        });
    });
});
```
Here is the text returned from the "console.log(err2.detail)" statement:
```
  -----------------------------------------------
  error:  Assert
  code:      1000
  context:   IsA((Node*)arrayExpr->args->tail->data.ptr_value,Const) - 
  query:     509314
  location:  xen_execute.cpp:5593
  process:   padbmaster [pid=20170]
  -----------------------------------------------
```
Here is the stack trace of the error returned:
```
error: Assert
    at Connection.parseE (/my-project-root/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/my-project-root/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/my-project-root/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

```

pg version: 6.1.2
node version: 6.9.2

**Comment by abenhamdine** [comment]
Hmm I think you should use  `= ANY($1::int[]` if you use parameterized queries.

**Comment by keithrz** [comment]
Thanks for the quick suggestion!  I still get the same issue, even with the cast.

FYI, I can get the query to work when querying directly (with or without the suggested cast.)

with cast:
```
SELECT count(1) 
     FROM table_with_ids
    WHERE my_id = ANY ('{{1,2}}');
```

without cast:
```
SELECT count(1) 
     FROM table_with_ids
    WHERE my_id = ANY ('{{1,2}}'::int[]);
```

both succeed.

**Comment by charmander** [comment]
Redshift isn’t PostgreSQL and its documentation suggests it doesn’t entirely support arrays. A possible workaround is [`Client.prototype.escapeLiteral`][1]; try using it on a [serialized][2] array.

  [1]: https://github.com/brianc/node-postgres/blob/7f35240a5ceb7d89c5a72c1297b56a8e4031eaac/lib/client.js#L275
  [2]: https://github.com/brianc/node-postgres/blob/7f35240a5ceb7d89c5a72c1297b56a8e4031eaac/lib/utils.js#L11-L41

**Comment by iyel** [comment]
@keithrz, hey! Did you solve your problem?

**Comment by PranaviC** [comment]
I faced the same issues and managed to get it working with the below code using https://github.com/lib/pq

```
v, _ := pq.Array([]int{1,2,3}).Value()
query := fmt.Sprintf(`select * from table where colID = any('%v'::integer[]);`, v)
rows, err := db.Query(query)
```
Hope it helps someone in the future!
