### ISSUE TITLE
Can this package be bundled with Webpack for a Node project?

### ISSUE THREAD

**Issue by hassankhan** [brianc/node-postgres#1187]
Hi there, 

I'm trying to build a Webpack bundle for an AWS Lambda project and I'm running into a few errors. I have a common package and a project package. The common package sets up a connection and returns a client from `pg`. The project package uses the client to actually execute queries. Currently I'm trying to bundle `pg` in the common package, but I've also tried setting it as an external with not much difference 😢 I've included the error I get when I try and build my project:

```bash
ERROR in ./~/server-libs/dist/bundle.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../type-overrides in /project/node_modules/server-libs/dist
 @ ./~/server-libs/dist/bundle.js 5:11534-11562

ERROR in ./~/server-libs/dist/bundle.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../package.json in /project/node_modules/server-libs/dist
 @ ./~/server-libs/dist/bundle.js 5:11585-11614

ERROR in ./~/server-libs/dist/bundle.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../connection-parameters in /project/node_modules/server-libs/dist
 @ ./~/server-libs/dist/bundle.js 5:11688-11723

ERROR in ./~/server-libs/dist/bundle.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./query in /project/node_modules/server-libs/dist
 @ ./~/server-libs/dist/bundle.js 5:11832-11850

ERROR in ./~/server-libs/dist/bundle.js
Module not found: Error: Cannot resolve module 'pg-native' in /project/node_modules/server-libs/dist
 @ ./~/server-libs/dist/bundle.js 5:11511-11531
```

Webpack configuration for common package:
```js
const path = require('path');

const PATHS = {
  dist : path.resolve(__dirname, 'dist'),
  src  : path.resolve(__dirname, 'src'),
};

module.exports = {
  entry  : './index.js',
  target : 'node',
  output : {
    path          : PATHS.dist,
    filename      : 'bundle.js',
    library       : 'ServerLib',
    libraryTarget : 'umd',
  },
  resolve : {
    extensions : ['', '.js'],
    root       : [ PATHS.src ],
  },
  module : {
    loaders : [{
      test    : /\.js$/,
      loaders : ['babel'],
      exclude : /node_modules/,
    }, {
      test    : /\.json$/,
      loaders : ['json'],
    }],
    noParse : [/pg\/lib\/native/]
  },
  externals : {
    'lodash' : true,
    'moment' : true,
  },
};
```

Webpack configuration for project package:
```js
module.exports = {
  entry  : './handler.js',
  target : 'node',
  module : {
    loaders : [{
      test    : /\.js$/,
      loaders : ['babel'],
      exclude : /node_modules/,
    }, {
      test    : /\.json$/,
      loaders : ['json'],
    }],
  },
};
```

**Comment by manueltimita** [comment]
This issue should be closed, since it's Webpack specific.

@hassankhan, you might want to have a look at the webpack specific issue here: https://github.com/elastic-coders/serverless-webpack/issues/78.

**Comment by brianc** [comment]
closing at the recommendation of @manueltimita  - also I don't know, I have never bundled non-browser code with webpack.

**Comment by brianc** [comment]
@hassankhan I'd be interested in any info you came up with, I can add it to the docs.

**Comment by hassankhan** [comment]
Hi @brianc,

I ended up using Knex so I don't know if it's any help, but my Webpack plugins configuration looks like this:
```
plugins : [
    new webpack.NormalModuleReplacementPlugin(/\.\.\/migrate/, '../util/noop.js'),
    new webpack.NormalModuleReplacementPlugin(/\.\.\/seed/, '../util/noop.js'),
    new webpack.IgnorePlugin(/mariasql/, /\/knex\//),
    new webpack.IgnorePlugin(/mssql/, /\/knex\//),
    new webpack.IgnorePlugin(/mysql/, /\/knex\//),
    new webpack.IgnorePlugin(/mysql2/, /\/knex\//),
    new webpack.IgnorePlugin(/oracle/, /\/knex\//),
    new webpack.IgnorePlugin(/oracledb/, /\/knex\//),
    new webpack.IgnorePlugin(/pg-query-stream/, /\/knex\//),
    new webpack.IgnorePlugin(/sqlite3/, /\/knex\//),
    new webpack.IgnorePlugin(/strong-oracle/, /\/knex\//),
    new webpack.IgnorePlugin(/pg-native/, /\/pg\//),
  ],
```

**Comment by brianc** [comment]
Thanks @hassankhan

**Comment by craigsnyders** [comment]
I've managed to successfully bundle this using `pg@6.2.3` `pg-native@1.10.1 `typescript@2.3.4` + `webpack@2.6.1` + `awesome-typescript-loader@3.1.3` + `@types/pg@6.1.41`.  Made a small repo to illustrate: https://github.com/craigsnyders/serverless-typescript-starter

I think the crucial parts are:
- npm install pg-native (webpack wasn't including this in the output otherwise?!)
- `target: 'node'` in webpack config

**Comment by jgrund** [comment]
FWIW, I got webpack to compile by adding the following to my webpack config (I don't need `pg-native`):

`plugins: [new webpack.IgnorePlugin(/\.\/native/, /\/pg\//)]`

This removes attempted resolution of './native' in https://github.com/brianc/node-postgres/blob/v6.2.3/lib/index.js#L104.

**Comment by evbo** [comment]
As pointed out by @hassankhan, same fix here
https://github.com/brianc/node-postgres/issues/838#issuecomment-405646013
