### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by cbaron** [brianc/node-postgres#1189]
Howdy, I've been using this module a lot over the past 2 years.  Its great.

Just wanted to let you know, if you're not already aware, of the deprecation warning on node v7.2.0:

```(node:6851) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.```

Let me know if I can be of assistance, would be happy to make a pull request.

**Comment by charmander** [comment]
Upgrade to Node 7.2.1 or later; see #1158.
