### ISSUE TITLE
strange read/write sequencing issue

### ISSUE THREAD

**Issue by jcharbo** [brianc/node-postgres#1192]
I'm having a very unusual timing problem with node-postgres against an amazon node instance.  

When I execute the code below it calls a function which among other things inserts a record into the notify table.  It returns the max record id from the notify table.  

Let's say the pk of the new notify record is 1000.  1000 is returned from the function using the exact same notify select statement seen below.  I would then expect the select statement below to return 1000 but it's returning 999 about 25% of the time.  

There must be some strange read/write timing stuff happening that I don't understand.  Can someone with more SQL knowledge please help.

thanks

```
return db.callDBFunction('select * from friendActions()').then(recordSets => {
    console.log('max id ' +recordSets[0]); // this is 1000
    db.getDBInteger('select id from notify order by id desc limit 1', []).then(id => {
        console.log('max id ' + id) // this is 999
    });
});

```

**Comment by charmander** [comment]
What are `callDBFunction`, `friendActions`, `getDBInteger`, and `notify`?

**Comment by jcharbo** [comment]
Hi Charmander, thanks for helping out.  

Calldbfunction is a series of functions that perform the work necessary to grab a pg connection from the pool, run the query, process the cursors and return the results.  

friendactions is a function that inserts into several tables and runs some perform statements as well.

getdbinteger is like calldbfunction but just extracts the first returned field as an id.

notify is simply a table.

I thought that maybe the friendactions function wasn't committing before my next query was being run but I just confirmed that it is not the case.  I added an "insert into a test table command" into the end of the function.  I also added the same insert before selecting from notify in the above code.  The resulting data does show the insert from the function being placed into the table before the insert from nodejs.

All I can figure is that it has something to do with new rows not being available immediately after a commit.  Is that possible?

thanks

**Comment by jcharbo** [comment]
Found the issue.  I'm running the function as a transaction.  After fetching the results I was running `conn.client.query("COMMIT")
`
 instead of
 
```
conn.client.query("COMMIT",[],function(err,results){
//put callback here
});

```

Thanks for your help charmander.

**Comment by charmander** [comment]
Glad to hear you solved it! =)
