### ISSUE TITLE
DeprecationWarning: Using Buffer without `new` will soon stop working

### ISSUE THREAD

**Issue by sarmiena** [brianc/node-postgres#1195]
Version: 6.1.2
macOS Sierra
Getting the following warning when doing require('pg')

DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

**Comment by charmander** [comment]
Upgrade to Node 7.2.1 or later; see #1158.
