### ISSUE TITLE
JSONB field sent to INSERT statement removes keys whose values are 'undefined'

### ISSUE THREAD

**Issue by rightaway** [brianc/node-postgres#1197]
If you do an INSERT statement and one of the fields is JSONB, and it's something like

```js
{
  a: 'a',
  b: 'b',
  c: null,
  d: undefined
}
```

The key `d` gets removed. Shouldn't the JSONB field still contain `d` but be set to `null`?

Is this even expected behavior, or have I done something wrong on my end? I wouldn't expect such behavior, if I didn't want `d` to be in the resulting field I would remove that key from the object. If I set it to undefined I think it should be `null`.

**Comment by sehrope** [comment]
While there's a lot of overlap, Javascript treats `null` and `undefined` as two separate values. Undefined values are not included in JSON stringification of objects:

    > var a = {b: null, c: undefined}
    undefined
    > a
    { b: null, c: undefined }
    > JSON.stringify(a)
    '{"b":null}'

If you want those fields included and appearing as `null` in your serialized JSON, you'll need to explicitly set them as null.

**Comment by charmander** [comment]
As sehrope said, `undefined` and `null` are not the same. If you want `null`, use `null`.
