### ISSUE TITLE
schema config parameter has no effect with pg driver (postgres)

### ISSUE THREAD

**Issue by stefaneg** [brianc/node-postgres#1199]
I trying to get db-migrate to create the migration table in a schema of my choosing, to no avail. After a brief look through the code, it seems to me that the schema attribute in database.json is never used. If I understand the code correctly, the config object is passed directly to the node-postgres driver, which does nothing with the schema attribute.

This issue here is probably relevant, it basically states that schema specification through config is not supported.

https://github.com/brianc/node-postgres/issues/1123

Am I missing something?

**Comment by charmander** [comment]
Did you mean to raise this issue on https://github.com/db-migrate/node-db-migrate? You’re correct that `schema` isn’t a supported option, and I don’t think it’s documented to be supported anywhere here.

**Comment by stefaneg** [comment]
You are quite right, I am barking up the wrong tree here.
