### ISSUE TITLE
timestamp and precision

### ISSUE THREAD

**Issue by williamstein** [brianc/node-postgres#1207]
The TIMESTAMP data type in postgreSQL by default has 6 digits after the decimal point.
If you store this time in PostgreSQL via some method:
```
2017-02-07T19:53:43.242999
```
then read it back with this node-postgres driver, you'll get
```
2017-02-07T19:53:43.242
```

I.e., the driver textually truncates the last 3 digits, rather than rounding to the nearest millisecond.

This bug (or very bad design decision) caused me a large amount of pain recently...

**Comment by charmander** [comment]
See #1200.
