### ISSUE TITLE
Connection terminated error with pooling

### ISSUE THREAD

**Issue by georgesben** [brianc/node-postgres#1215]
Hi everybody !

I have a little problem with my code. I'm trying to request my DB to get the pseudo linked with a specific ID. I'm using the pool as recommended with the documentation but I have an error. I think I'm missing something but I don't know why.

This is my code:
```javascript
function pseudo_utilisateur(id){
    return new Promise(function(resolve, reject){
        let query = `SELECT pseudo FROM ${Tables.user} WHERE id = $1`;
        pool.connect(function(err, client, done){
            client.query(query, [id],function(err, result){
                done();
                if(err){
                    console.log(err);
                    reject("err");
                }
                else{
                    console.log(result);
                    resolve(result.rows[0].pseudo);
                }
            })
        })
    })
}
```

and this is the error I received:
```
Error: Connection terminated
    at Connection.<anonymous> (E:\Cours année 2015 - 2017\Mémoire\mookup\node_modules\pg\lib\client.js:198:29)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:186:7)
    at Socket.<anonymous> (E:\Cours année 2015 - 2017\Mémoire\mookup\node_modules\pg\lib\connection.js:78:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
```

I have read this is a common error when someone uses the client approach. But I don't think I close the connection before reading the results. If I have well understood, the `done()` method is to release the client and the result of the request is in the callback of the client. But maybe I'm wrong.

So can someone help me, please ?
Thank you very much

**Comment by virtulis** [comment]
We're also seeing this error pop up seemingly randomly in the last few days, which is kind of weird since the last release was 2 months ago. But we have probably reinstalled all packages a few times in the last few days, so could it be one of the dependencies?

_Sorry for the useless comment, will try to isolate this tonight_

**Comment by georgesben** [comment]
The bug doesn't appear randomly in my code. Each time I call this piece of code, I have the bug. Maybe this is a problem with my configuration ? I use:

- Node 7.5.0

- Npm 4.0.3

- Pg 6.1.2

Maybe it can help you :)

**Comment by virtulis** [comment]
@georgesben your example works for me though. Are you sure you created the pool correctly and maybe you should check the err sent from connect?

**Comment by georgesben** [comment]
I have already checked that. This is good from the pool. The pool configuration is the following:

```javascript
const pg = require('pg');
const config = {
    user: 'test', //env var: PGUSER
    database: 'alexandrie', //env var: PGDATABASE
    password: 'test', //env var: PGPASSWORD
    port: 5432, //env var: PGPORT
    max: 10, // max number of clients in the pool
    idleTimeoutMillis: 3000, // how long a client is allowed to remain idle before being closed
};
const pool = new pg.Pool(config);
```

**Comment by charmander** [comment]
Does the typical way using `Pool.prototype.query` work for you?

```javascript
function pseudo_utilisateur(id) {
    let query = `SELECT pseudo FROM ${Tables.user} WHERE id = $1`;
    return pool.query(query, [id])
        .then(result => result.rows[0].pseudo);
}
```

**Comment by georgesben** [comment]
I have change the code following your advise:
```javascript
function pseudo_utilisateur(id){
    let query = `SELECT pseudo FROM ${Tables.user} WHERE id = $1`;
    return pool.query(query,[id]).then(function(result){
        console.log("ok !");
        return result;
    },function(error){
        console.log("error !");
        console.log(error);
        return error;
    });
}
```

And this is the error I received:

```
error !
Error: Connection terminated
    at Connection.<anonymous> (E:\Cours année 2015 - 2017\Mémoire\mookup\node_modules\pg\lib\client.js:198:29)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:186:7)
    at Socket.<anonymous> (E:\Cours année 2015 - 2017\Mémoire\mookup\node_modules\pg\lib\connection.js:78:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at TCP._handle.close [as _onclose] (net.js:501:12)
```

**Comment by georgesben** [comment]
I have found the problem. Somewhere in the code there is a `client.end()` for a client coming from the pool. This was a big mistake.

I'm sorry for this ticket. Again, thank you very much for your help ! :)

**Comment by baninaveen** [comment]
I encountered the same issue. but still not yet resolved.

**Comment by abenhamdine** [comment]
@baninaveen please open a separate issue with code of a reproductible example, and exact versions of pg you use, thx !

**Comment by AkhilGopan** [comment]
+1

**Comment by JulesAU** [comment]
I'm still seeing this, somewhat randomly.

```
    "knex": "^0.14.3",
    "pg": "^6.4.0",
```

Possibly not occurring with pg 7.x.

Will update once I'm more certain.

**Comment by JulesAU** [comment]
Confirmed occurred again with:
```
"knex": "^0.14.3"
"pg": "^7.4.1",
```

**Comment by JulesAU** [comment]
@charmander / @elhigu I think this needs to re-opened. The only solution for me was downgrading to 0.13.0 as recommended in https://github.com/tgriesser/knex/issues/2321

**Comment by abenhamdine** [comment]
@JulesAU @AkhilGopan @baninaveen 
again, please open a new issue with reproduction code and the error you see.
It doesn't help to write on a closed issue, which the OP has closed because he has solved his own bug.

**Comment by abenhamdine** [comment]
> @abenhamdine @JulesAU
> I started having the same problem, but only with long time queries, i found a possible solution by setting "idleTimeoutMillis" in the "new Pool" constructor, for example to 20000 (the default value is 10000)
> 
> My environment is:
> 
>     * ubuntu: 18.04
> 
>     * nodejs: 8.11.4
> 
>     * npm: 6.4.1
> 
>     * pg: 7.5.0
> 
> 
> See [node-postgres.com/api/pool#new-pool-config-object-](https://node-postgres.com/api/pool#new-pool-config-object-)

Please reeopened an issued, don't feed a closed one.
