### ISSUE TITLE
Question: Passing `DEFAULT` on INSERT?

### ISSUE THREAD

**Issue by ath88** [brianc/node-postgres#1219]
Hi there,

When doing an insert, you can request that PostgreSQL just uses the default value for that column by passing `DEFAULT` as the value. This is useful because I can then do something like this:

``` 
var newColumnValue = someValueThatMightBeUndefined || "DEFAULT";
```

This clearly doesn't work - since "DEFAULT" will be interpreted as a string. In Perl's DBD:Pg, it is handled by passing a specific internal enumerable variable which will be interpreted as the default string.

I have been looking though the code and documentation and have found no trace of such feature. How do I do this?

**Comment by charmander** [comment]
Using the `DEFAULT` keyword as an alternative isn’t possible with parameterized queries. Some options:

- Use some function to build queries that substitutes `DEFAULT`s for parameters when appropriate:

    ```javascript
    const DEFAULT = Symbol('default');

    const q = (parts, ...optionalValues) => {
        let counter = 0;
        const values = [];

        const text = parts[0] +
            optionalValues.map((value, i) => {
                if (value === DEFAULT) {
                    return 'DEFAULT' + parts[i + 1];
                }

                counter++;
                values.push(value);
                return '$' + counter + parts[i + 1];
            }).join('');

        return { text, values };
    };
    ```

    and

    ```javascript
    const newColumnValue = someValueThatMightBeUndefined || DEFAULT;

    return pool.query(q`INSERT INTO some_table (some_column) VALUES (${newColumnValue})`)
        .then(…);
    ```

- Build the query with a library like [brianc/node-sql][]

- Pass `null`s as values and `coalesce` them to the column’s default selected from somewhere (e.g. `information_schema`)


  [brianc/node-sql]: https://github.com/brianc/node-sql
