### ISSUE TITLE
fire and forget query?

### ISSUE THREAD

**Issue by BardiaAfshin** [brianc/node-postgres#1220]
Does this library support doing a fire and forget query?

I want to execute the query, but not wait for it's results.

**Comment by charmander** [comment]
Sure: execute the query and don’t wait for the results.

```javascript
pool.query('a query');
```

**Comment by BardiaAfshin** [comment]
OMG> I can't believe it!

**Comment by BardiaAfshin** [comment]
Will this work in AWS Lambda? The environment is terminated after 300 seconds.

**Comment by brianc** [comment]
It'll work in lambda but there are a bunch of gotchas around opening too many connections to postgres - if you get hundreds of lambadas spun up at once and they each have a connection pool you'll get thousands of postgres connections potentially, which will almosts certainly cause your postgres db to crash. So you'll need to use something like `pg-bouncer` to help w/ that.

**Comment by BardiaAfshin** [comment]
Right now the query gets terminated with pool.query().

Just tested it on aws . Here's the code

```javascript
'use strict';

console.log('Loading function');

const aws = require('aws-sdk');

const s3 = new aws.S3({ apiVersion: '2006-03-01' });

exports.handler = (event, context, callback) => {



  var Pool = require('pg').Pool;

  var config = {
 ...}


  var client = new Pool(config);

  client.on('error', function(e, client) {
      console.log(e);
  });


  var aws_access_key_id = 'asdf';
  var aws_secret_access_key = 'asdf';
  var token = 'asdf';

  var sql = "COPY public.some_table FROM 's3://"+bucket+'/'+key+"' CREDENTIALS 'aws_access_key_id="+aws_access_key_id+";aws_secret_access_key="+aws_secret_access_key+";token="+token+"' DELIMITER '\\t' GZIP NULL AS '\\000' TRUNCATECOLUMNS;";

  console.log('SQL ===> '+sql);
  client.query(sql);
  console.log('query executed!');
}

```

**Comment by charmander** [comment]
@BardiaAfshin PostgreSQL doesn’t support background tasks; it needs a client to run a query. If your client can’t live long enough to complete the query, maybe you should consider using a more appropriate client – for example, by adding a task to a queue from Lambda and consuming it somewhere else.
