### ISSUE TITLE
Application name for connection

### ISSUE THREAD

**Issue by pankleks** [brianc/node-postgres#1223]
Hello,

Is there a way to pass application name parameter when opening connection?
Have not found it in connection parameters.

Thanks

**Comment by charmander** [comment]
[The property is `application_name`:][1]

```javascript
const pool = new pg.Pool({
    ⋮
    application_name: 'a name',
});
```


  [1]: https://github.com/brianc/node-postgres/blob/33a1c35ad254fcc78de55956ed680e5b00fc5647/lib/connection-parameters.js#L63

**Comment by pankleks** [comment]
Thanks, I have committed update to typing's definition.
