### ISSUE TITLE
Event `notice` needs the query reference

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1226]
I need to execute the same function multiple times against the same client connection, while handling messages that the function may raise.

Unfortunately, event `notice`, doesn't provide any reference to the query that produced the event, so when I'm getting those events, I cannot link them to the correct source query.

The solution, I believe, should be as follows: [when emitting event `notice`](https://github.com/brianc/node-postgres/blob/master/lib/client.js#L207), the third parameter should be the `Query` object as returned from calling `client.query` to execute the query. That way we will get each `notice` with the right query reference that caused the event.

**Comment by vitaly-t** [comment]
@brianc do you think this is even possible?

I have looked through the code, and could see that our [`data` entry point](https://github.com/brianc/node-postgres/blob/master/lib/connection.js#L128) doesn't contain any mapping logic to determine which query owns the notification. Maybe I've missed something.

I know we have `activeQuery` within the `Client` object, but since the `Connection` doesn't provide any mapping (unless I missed it), then I'm not sure how to approach it.

I think you are the only person to figure out how to provide such mapping, if it is possible :wink:

**Comment by brianc** [comment]
On the postgres wire protocol `NOTIFY` doesn't carry any information in its payload about which cilent/query produced the message.  If you want to include custom metadata in the `NOTIFY` payload such as which client/query produced the message you'll have to pass it as a string within the payload manually.

example:

```js
client.query("NOTIFY chan, 'this is my custom payload'")
```
You'll receieve `this is my custom payload` on the `notice` event payload, so you can pass whatever you want in there including json encoded stuff.

**Comment by vitaly-t** [comment]
This is strange. Because if messaging is detached from queries, it makes them identical with the generic `LISTEN` / `NOTIFY` that are based on the channel only. In which case, what's the point they exist in addition to the `LISTEN`/`NOTIFY`?

**Comment by vitaly-t** [comment]
@brianc By the way, today I have finally released the version of [pg-promise](https://github.com/vitaly-t/pg-promise) that pulls the plug on supporting Node.js 0.10 and 0.12, with Node.js 4.x being the new minimum.

Maybe be it is time to do the same for your driver :wink:

For one thing, this solved a few issues I've had with Travis CI trying to support those old versions.
