### ISSUE TITLE
Disable connection pooling.

### ISSUE THREAD

**Issue by nidhhoggr** [brianc/node-postgres#1227]
I am already using connection pooling at the hardware/infrastructure level. With that being said, there is no need for convoluting things by adding connection pooling to the application level as well. What is the best way to disable connection pooling with config parameters. Or is there a different way to do it? I thought setting max connection would be ideal, but not sure if that loads a whole lot of code that isn't needed.

**Comment by charmander** [comment]
Yes, you could set `max` to `Infinity`, `idleTimeoutMillis` to `0`, and `evictionRunIntervalMillis` to something low.

If instead of configuring the application not to make use of its pool you would like to *write* it not to use pools, switch from one `pg.Pool` instance to `pg.Client`s created as necessary.

**Comment by nidhhoggr** [comment]
Thanks. What is the purpose of setting max to Infinity? Sounds sort of unintuitive.

**Comment by charmander** [comment]
The number of clients in the pool is limited by `max`; setting it to `Infinity` would remove the restriction.

It should also be possible to extend `pg.Pool`:

```javascript
class EmptyGenericPool {
    constructor(options) {
        this.acquire = this.create = options.create;
        this.release = this.destroy = options.destroy;
    }
}

class EmptyPool extends pg.Pool {
    constructor(options, Client) {
        super(options, Client);
        this.pool = new EmptyGenericPool();
    }
}
```
