### ISSUE TITLE
Faulty parsing of connection string

### ISSUE THREAD

**Issue by magnusburton** [brianc/node-postgres#1228]
Trying to set up a pg database on Heroku with this dependency when I ran into the following error.

`error fetching client from pool { Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }`

I did some digging and found that the pg pool as parsed my connection string completely wrong. I looking through the pool-object and found this.

`{"domain":null,"_events":{},"_eventsCount":0,"options":{"0":"p","1":"o","2":"s","3":"t","4":"g","5":"r","6":"e","7":"s","8":":","9":"/","10":"/","11":"x","12":"k","13":"j","14":"h","15":"p","16":"u","17":"t","18":"g","19":"f","20":"x","21":"j","22":"h","23":"d","24":"x","25":":","26":"a","27":"d","28":"b","29":"f","30":"9","31":"e","32":"5","33":"2","34":"f","35":"8","36":"b","37":"6","38":"0","39":"a","40":"a","41":"3","143":"4","144":"3","145":"2","146":"/","147":"d","148":"b","149":"6","150":"n","151":"8","152":"k","153":"6","154":"p","155":"h","156":"c","157":"k","158":"r","159":"a","160":"7","max":10,"idleTimeoutMillis":30000,"returnToHead":false,"refreshIdle":true,"reapInterval":1000,"priorityRange":1,"min":0}...}` and it seems like every key in this object is a letter of my connection string.

My code looks like this and I got it straight from the read me. Is the parser faulty or am I totally missing something obvious?

```javascript
var pool = new pg.Pool(process.env.DATABASE_URL);

console.log(JSON.stringify(pool));

pool.connect(function(err, client, done) {
  if (err) return console.error('error fetching client from pool', err);

  client.query('SELECT $1::int AS number', ['1'], function(err, result) {
    done(err);

    if (err) {
      return console.error('error running query', err);
    }

    console.log(result.rows[0].number);
  });
});
```

Many thanks,

**Comment by charmander** [comment]
The `pg.Pool` constructor accepts a configuration object, not a connection string; see https://github.com/brianc/node-postgres/issues/1141#issuecomment-266709632.
