### ISSUE TITLE
[doc] ColumnSet/Column doc, examples

### ISSUE THREAD

**Issue by estaub** [brianc/node-postgres#1231]
Some examples of `ColumnSet`/`Column` usage would be great, especially showing how the various column configs work.

Also, in the docs for `helpers`,
It's unclear what the behavior is when there are different properties in a supplied value _Object_ and a `ColumnSet`.   

For example, for me, it would be desirable if the names of the supplied properties determines the set of columns used (e.g. in helpers.sets or helpers.values); if a supplied value has no `Column`, it behaves as if no `ColumnSet` was supplied; if a `Column` has no value, it is ignored.  I want to think of a `ColumnSet` as providing guidance that I can usually make just one of per entity, regardless of which columns are actually used in each query.

From the current docs, I'm _guessing_ that the behavior is the opposite: the set of columns is controlled by the ColumnSet, ignoring any extra properties, and perhaps nulling any that are missing.

**Comment by vitaly-t** [comment]
What you published here got absolutely nothing to do with this library. From the contents it looks like it was meant for the [pg-promise](https://github.com/vitaly-t/pg-promise) module.

**Comment by estaub** [comment]
@vitaly-t Sorry - must have lost track of where I was.
