### ISSUE TITLE
error in pg/lib/connection.js:136

### ISSUE THREAD

**Issue by acebesmonte** [brianc/node-postgres#1239]
/usr/lib/node_modules/pg/lib/connection.js:136
      self.emit(msg.name, msg);
                   ^

TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (/usr/lib/node_modules/pg/lib/connection.js:136:20)

**Comment by charmander** [comment]
When does this error occur? Can you include a minimal script that produces it?

**Comment by spollack** [comment]
we just hit this same issue in production, which caused a crash. 

this code is in `Connection.prototype.attachListeners`. we are running a slightly older version of the pg driver, but looking at master nothing relevant has changed. it appears that `parseMessage` didn't return an object, as if perhaps the header code was not one handled in the switch statement. (there is no default case here...). I'm happy to open a PR with a guard around the `self.emit(msg.name, msg);` statement. but unfortunately i do not have a repro case. 

cc: @brianc 

```
Apr 17 08:19:33 rivaliq app/worker.4:  /app/node_modules/pg/lib/connection.js:109 
Apr 17 08:19:33 rivaliq app/worker.4:        self.emit(msg.name, msg); 
Apr 17 08:19:33 rivaliq app/worker.4:                     ^ 
Apr 17 08:19:33 rivaliq app/worker.4:  TypeError: Cannot read property 'name' of undefined 
Apr 17 08:19:33 rivaliq app/worker.4:      at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:109:20) 
Apr 17 08:19:33 rivaliq app/worker.4:      at emitOne (events.js:77:13) 
Apr 17 08:19:33 rivaliq app/worker.4:      at TLSSocket.emit (events.js:169:7) 
Apr 17 08:19:33 rivaliq app/worker.4:      at readableAddChunk (_stream_readable.js:153:18) 
Apr 17 08:19:33 rivaliq app/worker.4:      at TLSSocket.Readable.push (_stream_readable.js:111:10) 
Apr 17 08:19:33 rivaliq app/worker.4:      at TLSWrap.onread (net.js:531:20) 
Apr 17 08:19:33 rivaliq heroku/worker.4:  Process exited with status 1 
Apr 17 08:19:34 rivaliq heroku/worker.4:  State changed from up to crashed 
```

**Comment by rotexhawk** [comment]
Running into the same issue.

**Comment by rotexhawk** [comment]
@charmander my bad, it is probably a bug with TypeOrm. If you don't pass that library a right config file it throws the above bug.
