### ISSUE TITLE
parameterized query not working

### ISSUE THREAD

**Issue by win-t** [brianc/node-postgres#1240]
Hi, I used this script to initialize database when creating test environment
```js
client.query( "drop database if exists $1;", [db_name], (err, result) => {
// ...
});
```

but somehow the query error, and this is error log from PostgreSQL server
```
ERROR:  syntax error at or near "$1" at character 25
STATEMENT:  drop database if exists $1;
```
the client send the raw query (including dollar sign) to the server, any idea how to fix this?

**Comment by charmander** [comment]
See #539.
