### ISSUE TITLE
node-postgres simple SELECT is becoming extremely slow (PostgreSQL)

### ISSUE THREAD

**Issue by andrew-medvedev** [brianc/node-postgres#1243]
Hello! I'm developing an server-side app for mobile game backed with postgresql and I'm using pg with Knex("pg": "6.1.2" and "knex": "0.12.6"). Not so long ago I faced a problem with select perfomance degradation.

I've benchmarked my app with 40 fictive ccu. So I measured time between `Query` constructor and `Query.prototype.handleReadyForQuery` and what i've got: 
[pg.txt](https://github.com/brianc/node-postgres/files/834424/pg.txt)
(Array of numbers are representing times to complete particular query ms). For example, take a look at `select count(*) from \"player_battles\" where (\"attacking_player\" = $1 or \"defending_player\" = $2) and attacking_player <> defending_player` - 4429ms, Carl! Unpleasant surprize.

Obviously the problem lies in unoptimized sql or bad indexing, but analyzing logs with pgBadger showed me that: 
[out.zip](https://github.com/brianc/node-postgres/files/834442/out.zip)

Any ideas?

**Comment by vitaly-t** [comment]
The issue is whether with knex or your database indexes/logic.

But it is not related to this driver.
