### ISSUE TITLE
Destroy connection immediately

### ISSUE THREAD

**Issue by ikokostya** [brianc/node-postgres#1244]
I use `pg.Client` for executing simple query:

```js
function connectClient(client) {
    return new Promise((resolve, reject) => {
        client.connect((err) => {
            if (err) {
                reject(err);
            } else {
                resolve();
            }
        });
    });
}

function disconnectClient(client) {
    return new Promise((resolve, reject) => {
        client.end(() => resolve());
    });
}

const client = new pg.Client(options);
connectClient(client)
    .then(() => client.query('SELECT 1'))
    .then(() => disconnectClient(client));
```

Then, after some timeout, I want destroy client immediately, because it's not needed anymore. That's why `Client#end` method is not suitable here.

Is it possible destroy underlying socket using public API:

```js
client.connection.stream.destroy();
```
or I should create [Connection](https://github.com/brianc/node-postgres/wiki/Connection) object manually and work with it?

**Comment by charmander** [comment]
> Then, after some timeout, I want destroy client immediately, because it's not needed anymore. That's why `Client#end` method is not suitable here.

I’m not sure that explains why `Client#end` isn’t suitable. Your example works fine for me and exits immediately.

**Comment by vitaly-t** [comment]
this use of Promise is pointless:
```js
function disconnectClient(client) {
    return new Promise((resolve, reject) => {
        client.end(() => resolve());
    });
}
```
because `client.end()` is synchronous.

**Comment by ikokostya** [comment]
@vitaly-t Why `Client#end` [takes callback](https://github.com/brianc/node-postgres/blob/ce8f215c88583d82b0dde22743f4fdc688942d9b/lib/client.js#L342) and calls it asynchronously?

**Comment by ikokostya** [comment]
@charmander I play with `Client#end` and it works as expected, event if connection isn't ready yet. Thanks.
