### ISSUE TITLE
pg-generator

### ISSUE THREAD

**Issue by ozum** [brianc/node-postgres#1246]
Hi,

I'm author of open source [pg-structure](http://www.pg-structure.com) and [pg-generator](http://www.pg-generator.com) libraries, which are used to access database structure and generate code/documents based on PostgreSQL database.

I would like to know if there is a rule/criteria to add a library to https://github.com/brianc/node-postgres/wiki/Extras page?

Kind Regards,

**Comment by vitaly-t** [comment]
Just add them at the bottom of the [Extras](https://github.com/brianc/node-postgres/wiki/Extras), that's all.

**Comment by brianc** [comment]
@ozum congrats on the libraries & really nice work on the documentation...it looks great!  There isn't really a rule - it's a wiki so it's supposed to be community moderated.  Anyone can feel free to remove anything they found abandoned or completely unuseful from the wiki - I appreciate you asking though! 😄
