### ISSUE TITLE
Chaining queries without having multiple query?

### ISSUE THREAD

**Issue by kdmaris** [brianc/node-postgres#1248]
What is an elegant way of chaining queries in order to handle some business logic like:

1.  Check if something exists using a select

2.  Based on the results of 1, do some operation

Right now, I'm just creating some result arrays to get the row data from query1, then based on the updated results doing query2.

Is there a way to chain these together instead of having `const firstQuery = client.query()` and `const secondQuery = client.query()`?

**Comment by brianc** [comment]
That's really best handled by a higher level library or something in your own app.  I know in my apps it looks something like this:

```js
const logic = async (userId) => {
  const res = await client.query('SELECT * FROM users WHERE user_id = $1', [userId])
  if (!res.rows[0]) {
    return null; // user not found
  }
  const something = await client.query('UPDATE * FROM logins WHERE user_id = #1', [userId])
}

```

The example is contrived but I hope it helps!
