### ISSUE TITLE
Why does this upsert statement not work?

### ISSUE THREAD

**Issue by J0NNYZER0** [brianc/node-postgres#1251]
INSERT INTO assets (id, name, content, asset_type, asset_subtype, thumbnail, created_date)
  VALUES ($1,$2,$3,$4,$5,$6,$7)
    ON CONFLICT (id)
      DO 
        UPDATE 
          SET
          name = assets.name,
          content = assets.content,
          asset_type = assets.asset_type,
          asset_subtype = assets.asset_subtype,
          thumbnail = assets.thumbnail,
          created_date = assets.created_date

**Comment by charmander** [comment]
Does it produce an error? An unexpected result? Nothing at all?
