### ISSUE TITLE
Get whole database as an object with all tables and their fields

### ISSUE THREAD

**Issue by roytz** [brianc/node-postgres#1259]
Is there a function that retrieves the whole database as an object with all tables and their fields?

**Comment by vitaly-t** [comment]
That's called `backup`. See the links below.

*  https://www.postgresql.org/docs/9.6/static/backup-dump.html
* https://www.postgresql.org/docs/9.6/static/backup.html

**Comment by brianc** [comment]
Yeah this wouldn't really be something built into a database driver, but rather something you'd do yourself by executing whatever queries you needed to run to pull that information from the information schema in postgres.  If you write something that's generic and reusable you could even publish it as a standalone module that _consumes_ node-postgres and gives an easy way to get the information schema in a single function call.  Something like

```
const pg = require('pg')
const pgSchema = require('pg-schema')(pg)
const schema = await pgSchema.getSchema() 
```

Then everyone wins!
