### ISSUE TITLE
Using this package with cockroachdb

### ISSUE THREAD

**Issue by aunz** [brianc/node-postgres#1260]
Thanks for the awesome package!
[Cockroachdb](https://www.cockroachlabs.com/docs/build-a-nodejs-app-with-cockroachdb.html) recommends node-postgres driver.

I connected to an instance of cockroachdb successfully but there was a problem 

```js
const pg = require('pg')

const pool = new pg.Pool({
  user: 'user',
  port: 26257
})

pool.query('select 123 as num;')
  .then(r => console.log(typeof r.rows[0].num, r.rows[0].num)) // => string 123
  .catch(console.log)
```

Number `123` was treated as `string` not `number`
`select 123::int as num` and produced typeof `string`
Nonetheless, `select 123::float as num` produced typeof `number` as expected

I understand that this is probably beyond the scope of this package, but it would be much appreciated if you could have a look at this or pointed me to the right direction.

**Comment by vitaly-t** [comment]
You can find the explanation here: http://stackoverflow.com/questions/39168501/pg-promise-returns-integers-as-strings

**Comment by brianc** [comment]
That's super cool that cockroachdb uses the postgres protocol. TIL!

As far as parsing that type, cockroachdb might be returning a different
type oid for `num`.  Whenever pg sees a type oid it doesn't recognize it'll
just pass the type through as a string (in the protocol itself all values
are encoded as strings).  You'll need to find the type OID of that result &
then add the parser yourself if you'd like.

To do that you can do something like....

```js
const client = await pg.connect()
client.connection.on('rowDescription', (msg) => console.log(msg))
await client.query('SELECT 123 as num')
```

You should see it spit out an object to the console - that object will
contain an array of fields with a `dataTypeID` property.  Get that id, and
then do something like

```
pg.types.registerTypeParser(<dataTypeId>, parseFloat)
```

Something like that...I apologize if that doesn't work exactly 100% out of
the gate - i'm typing this from memory in an email, but a tiny bit of
research combined w/ what I put up there should hopefully point you in the
right direction!

Note: parsing 64 bit numbers into a `Number` type in JavaScript _can
result_ in data loss if you have a 64 bit number returned which overflows
JavaScript's 32 bit number representation.  In practice this isn't common
but something to be aware of.

Hope this helps!

**Comment by aunz** [comment]
Thanks @vitaly-t and @brianc for the guidance!!!
After following your direction, I also found a sample code in [node-pg-types](https://github.com/brianc/node-pg-types).

Now, I just need to register the OID:
```js
pg.types.setTypeParser(20, parseInt) // aware that javascript only supports 2^53 bits for int
```
(Cockroachdb treats all [INT](https://www.cockroachlabs.com/docs/int.html) as 64-bit)

**Comment by brianc** [comment]
happy to help @aunz!
