### ISSUE TITLE
A way to get the id of inserted row as callback?

### ISSUE THREAD

**Issue by johhansantana** [brianc/node-postgres#1269]
For inserting a row, the callback just sends back this: 
```json
{
  "command": "INSERT",
  "rowCount": 1,
  "oid": 0,
  "rows": [],
  "fields": [],
  "_parsers": [],
  "RowCtor": null,
  "rowAsArray": false
}
```

Is there a way to get the id of the inserted row?

**Comment by brianc** [comment]
`INSERT INTO foo (name) VALUES ('baz') RETURNING *`

**Comment by jmarca** [comment]
Got to this the long way.  Can you update the docs (specifically at <https://node-postgres.com/features/queries#parameterized-query>) ---to use this syntax?

I've used RETURNING before when doing a data-modifying WITH clause, but I didn't think to add it to a plain insert.  

(also, my way of using it is with async/await...)

Suggestion:

```javascript
const text = 'INSERT INTO users(name, email) VALUES($1, $2) RETURNING *'
const values = ['brianc', 'brian.m.carlson@gmail.com']

// callback
client.query(text, values, (err, res) => {
  if (err) {
    console.log(err.stack)
  } else {
    console.log(res.rows[0])
  }
})

// promise
client.query(text, values)
  .then(res => console.log(res.rows[0]))
  .catch(e => console.error(e.stack))

// async/await, pool

try {
    const pool = new Pool()
    const {rows} = await pool.query(text, values)
    console.log(rows[0])
}catch(e){
   console.error(e)
   setImmediate(() => { throw e })
}
```

**Comment by charmander** [comment]
You don’t always need `RETURNING` and it’s something of a well-known PostgreSQL feature, so I’m not sure it has to be in driver docs.

**Comment by brianc** [comment]
@jmarca I agree you don't always need a `RETURNING` on an insert, but I added a bit more docs based on your example since it couldn't hurt. :smile:

https://node-postgres.com/features/queries#parameterized-query

**Comment by jmarca** [comment]
Yes of course you don't always need "returning", and postgresql inserts typically just return the sparse phrase `INSERT 0 1` or whatnot.  But its been a while, and the way the docs were written, I interpreted the `res => console.log(res.rows[0])` as implying that res.rows[0] would contain the results of the insert.  Of course it doesn't unless you ask for it, but I'd forgotten that.

That's the trouble with switching between different languages and databases...one remembers the broad stokes but forgets the details.

**Comment by thdomingues-dev** [comment]
I'm using KnexJS and have the same problem, solve using "returning"

just like this: // Returns [1]
knex('books')
  .returning('id')
  .insert({title: 'Slaughterhouse Five'})
