### ISSUE TITLE
loop over query results and make more queries

### ISSUE THREAD

**Issue by malickz** [brianc/node-postgres#1270]
Hi, i am having this problem that when i try to make multiple requests i get the following error:
```
cannot get client { error: sorry, too many clients already
    at Connection.parseE (/Users/SaadMalik/workspace/angular-cli/git-repo-visualization/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/Users/SaadMalik/workspace/angular-cli/git-repo-visualization/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/Users/SaadMalik/workspace/angular-cli/git-repo-visualization/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 85,
  severity: 'FATAL',
  code: '53300',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'proc.c',
  line: '340',
  routine: 'InitProcess' }
```

my scenario: i have a table in db which has like 65000 records, i do the throttling from client that client send a request to fetch 100 records each time and on server i make the following request using: 

 

> pool.connect(function(err, client, done) {
>         if(err) {
>           return console.error('cannot get client', err);
>         }
> 
>         client.query('SELECT path from dataTree WHERE dataItemid BETWEEN $1 AND $2', [req.param("start"), req.param("end")], function(err, result) {
>           done(err);
> 
>           if(err) {
>             return console.error('cannot run query', err);
>           }
> 
>           forEach(result.rows, (row) => {
>             client.query('SELECT loc from listData WHERE listId = $1 ', [row.path], function(err, result) {
>               done(err);
> 
>               if(err) {
>                 return console.error('cannot run query', err);
>               }
> 
>               client.query('update newDoc set loc = $1 where path = $2', [result.rows[0].path, 'Documentation'], function(err, result) {
>                 done(err);
>                 if(err) {
>                   return console.error('cannot run query', err);
>                 }
>               });
>             });
>           });
>         });
>       });

**Comment by charmander** [comment]
Are you releasing clients back to the pool when there aren’t any errors? I don’t see a `done();`.

**Comment by malickz** [comment]
yep thats right, i was missing done(), works fine now.. thanks @charmander
