### ISSUE TITLE
How to pass a dynamic number of variables in a parametrized query?

### ISSUE THREAD

**Issue by caub** [brianc/node-postgres#1272]
example (not working):
```js
pool.query(`SELECT id, name FROM test 
              WHERE name IN ($*OrSomething?) LIMIT 10`, 
              ['john', 'jane'])
```

**Comment by caub** [comment]
https://github.com/brianc/node-postgres/wiki/Parameterized-queries-and-Prepared-Statements#parameters-for-clause-where--in- Ok, but a (*) or something would be so much more handy

**Comment by charmander** [comment]
I’m not sure why the rest of the suggestions are there; use the `ANY`.

```js
pool.query(`SELECT id, name FROM test
            WHERE name = ANY ($1) LIMIT 10`,
           ['john', 'jane'])
```

**Comment by caub** [comment]
Ah thanks, missed it
