### ISSUE TITLE
are pooled queries guaranteed to be executed in order?

### ISSUE THREAD

**Issue by dwelle** [brianc/node-postgres#1275]
suppose I synchronously call `query` multiple times:

```
pool.query( "UPDATE ....", () = {} ); // A
pool.query( "UPDATE ....", () = {} ); // B
pool.query( "UPDATE ....", () = {} ); // C
```

Am I guaranteed the queries will execute in order, if using pooling?

From testing it seems it works fine, but previously when I was using `pg.connect()`, the order was random most of the time.

Two things that I thought might have been happening:

- I was initializing the pooling wrong
- the clients from pool were retrieved/assigned using some heuristic that didn't respect the request order (i.e. the query order)

using `pg@6.0.1`

Also a sidenote.. no idea how this is related, but the out-of-order only happened when I called the queries inside a hapi route handler, and not when e.g. executed as a simple node file.

**Comment by brianc** [comment]
They will *not* execute in order unless you have a pool size of 1.  Otherwise the pool internally fans queries out to available connections.  If they end up executing in order for some reason this is probably just because the 1 millisecond delay between dispatching from your app was enough time for postgres to accidentally answer them in the same order they came in?  Basically just serendipity.  But in general, if you want ordering you need to acquire a client from the pool and use it:

https://github.com/brianc/node-postgres/wiki/Transactions

**Comment by dwelle** [comment]
But if the acquire-request is enqueued into the pool, why shouldn't it be dequeued in order, irrespective of when additional clients become available?

Let's say that 3 acquire-requests are sitting in pool after I issue `pool.query` 3x in a row (`A`, `B`, `C`). Let's say that only one client is available in the pool so we should dequeue it and assign it to the `A` request. Then after a while, another DB client is released so we should assign it to the 2nd enqueued request `B` and so on.

If you don't assign [priority](https://github.com/coopernurse/node-pool#poolacquire) to the acquire which it seems you do not, I don't see any reason why it should be dequeued out of order.

**Comment by charmander** [comment]
Sending queries in a certain order doesn’t mean those queries will be received or executed in that order.

**Comment by dwelle** [comment]
I know that HTTP requests can quite easily arrive out-of-order, but accounting for that, I see no reason apart from deliberate design decision to make pg dequeue the pool clients (thus query) requests out-of-order.

There should be no magic preventing it from dequeuing in-order since JS is single-thread.

Only reason for doing it that I see is to convey to the user in no uncertain terms that expecting code to execute in-order is a no-no on server.

Anyway, in a pooling scenario, how would you go about ensuring that older data (PATCH requests) do not override newer data if the requests (thus queries) happen close to each other? Without putting locking logic into every table being updated (fact is, I don't know how to do it easily even _with_ locks).

**Comment by charmander** [comment]
> I know that HTTP requests can quite easily arrive out-of-order, but accounting for that, I see no reason apart from deliberate design decision to make pg dequeue the pool clients (thus query) requests out-of-order.

I wasn’t referring to HTTP requests. PostgreSQL clients may send several messages to the server to make a single query, any of which could be subject to delays, for example.

> Anyway, in a pooling scenario, how would you go about ensuring that older data (PATCH requests) do not override newer data if the requests (thus queries) happen close to each other? Without putting locking logic into every table being updated (fact is, I don't know how to do it easily even with locks).

One way would be to keep a “current revision” field and send its value along with the PATCH; if it’s out of date, reject the change. This (conflict detection) tends to be the right way even ignoring pg.

**Comment by dwelle** [comment]
> I wasn’t referring to HTTP requests. PostgreSQL clients may send several messages to the server to make a single query, any of which could be subject to delays, for example.

Wait.. so a single `pool.query( sql )` may result in _several_ messages being sent to the server?

> One way would be to keep a “current revision” field and send its value along with the PATCH; if it’s out of date, reject the change. This (conflict detection) tends to be the right way even ignoring pg.

Problem with that is:

1. it'll become crazy tedious (+ decrease perf + increase storage size) to do it for every table for every PATCH
2. in a multi-user/multi-browser scenario it's hard to distinguish whether the PATCHes were out-of-order sequential requests by the same client (i.e. browser), or concurrent requests from different clients. Will require storing _at least_ two, maybe three columns (`revision`, `session_id`, ...maybe `user`) -- multiply that by the number of tables where it's necessary to ensure integrity, and number of places where PATCH db query is done..

Alas, I don't see much other possibilities.

**Comment by charmander** [comment]
> Wait.. so a single `pool.query( sql )` may result in several messages being sent to the server?

If it has parameters, yes, but that’s not so important. Even if each client sent one message (in one packet), they could arrive out of order.

> it'll become crazy tedious (+ decrease perf + increase storage size) to do it for every table for every PATCH

Four bytes per row. I’m not seeing where you would have a performance impact.

> in a multi-user/multi-browser scenario it's hard to distinguish whether the PATCHes were out-of-order sequential requests by the same client (i.e. browser), or concurrent requests from different clients.

Those tend to be the same problem. Do you really want a user to be able to update a record based on an outdated version, so long as it’s a different user?

**Comment by dwelle** [comment]
> If it has parameters, yes, but that’s not so important. Even if each client sent one message (in one packet), they could arrive out of order.

Certainly if the DB is a separate server, else I didn't know this was a thing.

> Four bytes per row.

More if we store the `session_id` etc.

> I’m not seeing where you would have a performance impact.

If conflicts will be common, the server will need to check (possibly in separate query) what kind of conflict it was and act accordingly. See below

> Those tend to be the same problem. Do you really want a user to be able to update a record based on an outdated version, so long as it’s a different user?

The opposite.

If it's the same user, you just drop the PATCH request that's a bit older than current revision coz you can assume (within reason) it's just a request mismatch (or you can try to rebase history if nothing else) -- else it'd be a terrible UX to bug the user every time.

If it's a different user, you'll need to resolve the conflict by dragging the user into it.
