### ISSUE TITLE
select columns as variable 

### ISSUE THREAD

**Issue by caub** [brianc/node-postgres#1276]
I'd like to do:

```js
.query('SELECT $1 FROM test', ['foo,bar'])
```
(where `foo,bar` would be a dynamic api parameter)

Is this possible?

**Comment by sehrope** [comment]
No that's not possible. Columns in a SELECT clause are literals and cannot be parameterized.

You'd have to create the SQL yourself. If you are going to do something like this, be careful about whitelisting the acceptable fields and escaping them as identifiers (if it's entirely dynamic which is usually a bad thing).

**Comment by caub** [comment]
Ah ok, it's for optionally filtering out fields in the API, to see better through results, or to save size. Like google drive api `fields` parameter allows to for example.

So I could just filter in JS, if it's just for debug

**Comment by brianc** [comment]
Yah make *sure* you escape any dynamically added column names if they're not white-listed in your app.  Meaning if you take the column names from user input make sure to pass them through something like [this](https://www.npmjs.com/package/pg-escape).

Yah I'd just filter in JS - likely easier to maintain most likely!  

I've also exposed a wrapper to the native libpq C escape function if you want to use what postgres itself ships for escaping: https://github.com/brianc/node-libpq#pqescapeliteralinputstringstring
