### ISSUE TITLE
pg.Pool  doesnt create "min" number connections,  and shuts down (sometimes) after 20 sec

### ISSUE THREAD

**Issue by jacobbogers** [brianc/node-postgres#1278]
this is my project, you can compile  with "npm run build" and "npm start"  https://github.com/jacobbogers/hermes

Why is this shutting down , it has very random behavior, there is a testdatabase I made for this, the connect-url is for now embedded in the code, so dont nag about it please. thank you

**Comment by brianc** [comment]
Unless you can give a much smaller and more self-contained example of behavior that's breaking then all I can guess is you'll need to dig in and do research to figure out what's going on in your project.  I don't understand exactly what you're saying & it sounds like something within your code.

If you want me to dive in and grok your code base and help with application specific issues I'm available as a consultant for an hourly rate and would be happy to help!   Please email me if you're interested in discussing that.
