### ISSUE TITLE
How to get actual SQL that pass into db?

### ISSUE THREAD

**Issue by red010182** [brianc/node-postgres#1282]
In node-mysql 
```
let sql = mysql.format('SELECT * FROM article WHERE id IN (?) and type=?;', [[1,2,3,4,5],'post'])
console.log(sql)
=> SELECT * FROM article WHERE id IN (1,2,3,4,5) and type='post';
```

How do I get the translated SQL (after parameter insertion) that pass to db for debug?

**Comment by brianc** [comment]
http://stackoverflow.com/questions/10720420/node-postgres-how-to-execute-where-col-in-dynamic-value-list-query
