### ISSUE TITLE
Truncates 64-bit integer 

### ISSUE THREAD

**Issue by mattiasmak** [brianc/node-postgres#1283]
When querying a column with a 64-bit integer it gets truncated.

example: 235191684988928001 is 235191684988928000 after the query. I can avoid this by casting it to a string, or is there a better way?

I understand why this is happening, but is it something that can be fixed?

**Comment by benesch** [comment]
@mattiasmak, could you post a minimal reproduction? Unless you've opted into parsing `int8`s by setting `pg.defaults.parseInt8 = true`, the driver should already be handing back strings for all `int8`s.

**Comment by brianc** [comment]
Closing because I haven't heard anything back.  Feel free to re-open if you come up w/ steps to reproduce.
