### ISSUE TITLE
Error `sorry, too many clients already` with pooling

### ISSUE THREAD

**Issue by jfsimon** [brianc/node-postgres#1289]
Hi there,

I have a script who performs concurrent database operations (using `async` functions and `Promise.all()`).  I got series of rejected promises with following message: `Error: FATAL:  sorry, too many clients already`. My PostgreSQL configuration shows `max_connections = 100` and I use the following `pg` setup:

```js
import pg from 'pg';

const pool = new pg.Pool({
    user: 'my_user',
    password: 'my_pass',
    database: 'my_db',
    max: 10,
    idleTimeoutMillis: 30000,
    Client: pg.native.Client
});
```

I start one thread of the script, so it should never consume all 100 connections available!
The `max: 10` should limit concurrent clients to 10, am I right?
Have anyone an idea about what I miss here?

**Edit:** if I increase `max_connections = 300`, the errors disappear.

**Comment by brianc** [comment]
I'd need to see a full sample of code to reproduce the issue, but yeah the
pool should definitely work & limit the number to 10.

**Comment by jfsimon** [comment]
I tried to write a minimalist failing sample, but it don't want fail!
I will search for further clues about this problem, I'll keep you up-to-date.
Thank you for your help (and this great library)!

**Comment by brianc** [comment]
Absolutely!  My pleasure. 😄  Please feel free to come back & re-open if you can root cause the issue.  The max number of connections is shared among *all* connects to postgres including from other apps & scripts - maybe there's something else connected as well?  Anyways - best of luck tracking it down! ❤️

**Comment by gustavo-tailrecursive** [comment]
> Hi there,
> 
> I have a script who performs concurrent database operations (using `async` functions and `Promise.all()`). I got series of rejected promises with following message: `Error: FATAL: sorry, too many clients already`. My PostgreSQL configuration shows `max_connections = 100` and I use the following `pg` setup:
> 
> ```js
> import pg from 'pg';
> 
> const pool = new pg.Pool({
>     user: 'my_user',
>     password: 'my_pass',
>     database: 'my_db',
>     max: 10,
>     idleTimeoutMillis: 30000,
>     Client: pg.native.Client
> });
> ```
> 
> I start one thread of the script, so it should never consume all 100 connections available!
> The `max: 10` should limit concurrent clients to 10, am I right?
> Have anyone an idea about what I miss here?
> 
> **Edit:** if I increase `max_connections = 300`, the errors disappear.

hi, i have a question, how did you increased `max_connections = 300`?

**Comment by jfsimon** [comment]
@gustavo-tailrecursive https://stackoverflow.com/questions/30778015/how-to-increase-the-max-connections-in-postgres?answertab=active#tab-top
