### ISSUE TITLE
Config object mutation

### ISSUE THREAD

**Issue by lenemson** [brianc/node-postgres#1294]
There is a mutation on the config object in [PG.prototype.connect](https://github.com/brianc/node-postgres/blob/master/lib/index.js#L65) at lines 65 to 67, it is problematic because the config object is [serialized](https://github.com/brianc/node-postgres/blob/master/lib/index.js#L57) with `JSON.stringify` and then [used as key](https://github.com/brianc/node-postgres/blob/master/lib/index.js#L70) to store/retrieve the clients pool.

If the config object passed to `pg.connect` doesn't contains either `max`, `idleTimeoutMillis` or `log`, they are added by mutation but AFTER the serialization, so the freshly created pool is stored with the non mutated  serialized config object as a key, causing all subsequent calls to `pg.connect` to use the mutated config object as a key thus using a second pool, letting the first pool unused, forever.

This change has been introduced in the code with this [commit](https://github.com/brianc/node-postgres/commit/796a44f54f2bd65611ae3ca09f3fb7d830a95ab4).

**Comment by lenemson** [comment]
I submitted a tiny PR but it seems that another PR submitted 15 day ago fix this issue https://github.com/brianc/node-postgres/pull/1279.
It's the same fix but with a test, so lets merge this ?

**Comment by brianc** [comment]
Gotcha! Sorry for the delay!
