### ISSUE TITLE
Remove support for node < 4.x

### ISSUE THREAD

**Issue by brianc** [brianc/node-postgres#1298]
Dropping older versions of node out of the travis test matrix, allowing us to move away from some of the extremely old buffer APIs and move a bit more quickly on new features.  For older versions the suggestion will be to use the 6.x trunk.  We'll need to cut a maintenance branch we can back-port any critical security fixes to.

**Comment by vitaly-t** [comment]
You may want to use the same technique as I did within [pg-promise].

Here's the library's entry file: [lib\index.js](https://github.com/vitaly-t/pg-promise/blob/master/lib/index.js).

[pg-promise]:https://github.com/vitaly-t/pg-promise/blob/master/lib/index.js

**Comment by brianc** [comment]
This is complete.
