### ISSUE TITLE
Value from numeric column is returned as string -- is it by design, or a bug?

### ISSUE THREAD

**Issue by 3n-mb** [brianc/node-postgres#1300]
When table has numeric column, returned value is string. Is this by design so as not to loose arbitrary precision? If not, it is a bug.

From int and bigint columns values are returned as numbers. Note that some bigint (64 bit) values will be mangled when pushed into javascript number, 64float, or 50-something integer safe bits.

**Comment by abenhamdine** [comment]
It is by design, see https://github.com/brianc/node-pg-types/issues/52
Notably, see explanations in readme of https://github.com/brianc/node-pg-types/ about integers, which is also true concerning numeric.
