### ISSUE TITLE
Columns with same name from different tables are removed

### ISSUE THREAD

**Issue by ValerioSevilla** [brianc/node-postgres#1305]
Hi,

I have been doing some tests with SQL joins in this library. I have a query like this one (simplified):

```sql
SELECT li.id, li.name, hi.name
FROM LineItem li, HeaderItem hi
WHERE li.header = hi.id
ORDER BY hi.name
```

As you can see, I am querying the field `name` from both tables. The results have this structure:
```json
[
  {
    "id": "...",
    "name": "<Header Name>"
  },
  {
    "id": "...",
    "name": "<Header Name>"
  }
]
```

The table alias is omitted and both `name` fields collide, resulting in less fields than requested. The field that remains is the last one in the list. Looks like the column name is being used as a map key and gets overridden as soon as a column with the same name appears. I assume that if the table alias were kept it would have worked. The only way I know to workaround this is adding an alias to each field:

```sql
SELECT li.id, li.name liName, hi.name hiName
FROM LineItem li, HeaderItem hi
WHERE li.header = hi.id
ORDER BY hi.name
```

... which works fine:

```json
[
  {
    "id": "...",
    "liName": "<Line Name>",
    "hiName": "<Header Name>"
  },
  {
    "id": "...",
    "liName": "<Line Name>",
    "hiName": "<Header Name>"
  }
]
```

**Comment by charmander** [comment]
Correct. Since fields are accessed by name, those names will have to be distinct.

**Comment by brianc** [comment]
You can also set `arrayMode: true` on the query and it will return rows as an array of values - doing that prevents two columns with the same name from clobbering eachother.

99.9% of the time you can just alias one column from one of the tables in your query:

```
const text = 'SELECT a.*, b.name as b_name FROM a join b on a.name = b.name'
const { rows } = await query(text)
console.log(rows[0].name, rows[0].b_name)
```
