### ISSUE TITLE
json_build_object: unexpected behaviour by changing bigint in results

### ISSUE THREAD

**Issue by talkhot** [brianc/node-postgres#1319]
When I run the following as part of a query with PG I get the wrong ID in the query result.
```
ARRAY(
  SELECT
  json_build_object(
    'id', a1.id, -- bigint
    'name', a1.name -- text
  )
  FROM artist
) as artists
```
What I get in the result:
`returned result "[{"id" : 1533947986218845200, "name" : "Mookie Mardi Gra"}]"`

What I should get in the result:
`expected result "[{"id" : 1533947986218845197, "name" : "Mookie Mardi Gra"}]"`

So the correct ID should be **1533947986218845197** where it returns 1533947986218845200.

When I run the same query in for instance pgAdmin I get the right ID.
When I convert the bigint to text I also get the right ID: 
```
  json_build_object(
    'id', a1.id::text,
    'name', a1.name
  )
```

It seems something with the biginit parsing in json_build_object go's wrong?

**Comment by abenhamdine** [comment]
Javascript can't simply handle such big numbers with type Number, see https://github.com/brianc/node-pg-types/blob/master/README.md

**Comment by talkhot** [comment]
Ah thanks for pointing that out! Explains why the number got rounded.

**Comment by vitaly-t** [comment]
You cannot convert 64-bit to integers in JavaScript directly, must use a specialized library for that, or else everything pass bit 53 is rounded.

See related question: [How to do 64bit Integer arithmetic in Node.js?](https://stackoverflow.com/questions/24037751/how-to-do-64bit-integer-arithmetic-in-node-js)

**Comment by charmander** [comment]
(The correct workaround for pg is `::text`; you can make further conversions from there.)
