### ISSUE TITLE
Null rowCount for redshift

### ISSUE THREAD

**Issue by jleclanche** [brianc/node-postgres#1330]
From https://github.com/sqlectron/sqlectron-gui/issues/329 and more specifically, https://github.com/sqlectron/sqlectron-gui/issues/323#issuecomment-309273506

The `rowCount` returned after executing a query on redshift (postgres 8.0 style) is always `null`, even when there *are* rows returned. According to the second issue I linked, this is a problem on the whole postgres 8.x family.

Is this intended? (Given than rows.length can be used I'm not sure it's entirely a problem in pg, but it is inconsistent with 9.x)

**Comment by brianc** [comment]
Yeah unfortunately the PostgreSQL server itself doesn't return the `rowCount` property for `SELECT` statements in their protocol for version 8.x so there's literally no way to get it parsed from the backend.  I'll make a comment on their repo that they should use `res.rows.length` or something similar to get the number of rows returned.
