### ISSUE TITLE
JOINS between tables with overlapping column names 

### ISSUE THREAD

**Issue by zhaosjason** [brianc/node-postgres#1336]
Originally posted a question here: [https://github.com/vitaly-t/pg-promise/issues/350](https://github.com/vitaly-t/pg-promise/issues/350), but moving to this repo because it is more relevant.  Also, not really an issue for me anymore cause I'm doing what I need to in a different way, but I still think it's kinda interesting.

The gist of this issue is that queries with JOINS between tables with overlapping column names only return column data from the last overlapping column.  As a simple example, consider these two tables and the following queries:

Users:
```
 uid | name 
-----+------
  1  |       

(1 row)
```

Sessions:
```
 sid | uid 
-----+-----

(0 rows)
```

Six queries that test different joins and different column orderings (note: pay particular attention to the relative positions of u.uid and s.uid in the SELECT statements):
```
1.  SELECT *                           FROM Users as u LEFT JOIN Sessions as s ON u.uid = s.uid;
2.  SELECT u.uid, u.name, s.sid, s.uid FROM Users as u LEFT JOIN Sessions as s ON u.uid = s.uid;
3.  SELECT s.uid, u.uid, u.name, s.sid FROM Users as u LEFT JOIN Sessions as s ON u.uid = s.uid;

4.  SELECT *                           FROM Sessions as s RIGHT JOIN Users as u ON u.uid = s.uid;
5.  SELECT s.sid, s.uid, u.uid, u.name FROM Sessions as s RIGHT JOIN Users as u ON u.uid = s.uid;
6.  SELECT s.sid, u.uid, s.uid, u.name FROM Sessions as s RIGHT JOIN Users as u ON u.uid = s.uid;
```

In this example, the first two LEFT JOIN queries (<span>#</span>1, <span>#</span>2) return:
```
[ anonymous {
    uid: null,
    name: null,
    sid: null } ]
```

While the first two RIGHT JOINs (<span>#</span>4, <span>#</span>5) return:
```
[ anonymous {
    sid: null,
    uid: 1,
    name: null } ]
```

Query <span>#</span>3 returns:
```
[ anonymous {
    uid: 1,
    name: null,
    sid: null } ]
```

While query <span>#</span>6 returns:
```
[ anonymous {
    sid: null,
    uid: null,
    name: null } ]
```

Running the same queries in psql for reference yields:

Query <span>#</span>1 and <span>#</span>2:
```
 uid | name | sid | uid 
-----+------+-----+-----
  1  |      |     |     
```

Query <span>#</span>4 and <span>#</span>5:
```
 sid | uid | uid | name 
-----+-----+-----+------
     |     |  1  |      
```

Query <span>#</span>3:
```
 uid | uid | name | sid 
-----+-----+------+-----
     |  1  |      |      
```

Query <span>#</span>6:
```
 sid | uid | uid | name 
-----+-----+-----+------
     |  1  |     |      
```

Here we can see where the crux of the problem is.  It seems like when there are conflicting column names, node-postgres just returns the last conflicting column (Can someone confirm?).  In the examples above, this means that depending on the position of User.uid and Session.uid in the results, node-postgres will either return 1 or null for uid.  Specifically, because in queries <span>#</span>3, <span>#</span>4, and <span>#</span>5 User.uid comes after Session.uid, node-postgres returns the "correct" value for uid whereas with the other three queries Session.uid comes last so in those cases null is returned.

I use quotes around "correct" because I guess this technically isn't a bug, but rather just a result of the way node-postgres handles naming conflicts.  I do wonder if there is a better way to deal with these conflicts though.  Thoughts?

// Jason

**Comment by brianc** [comment]
Yah that's an unfortunate by-product of how node-postgres gets rows out.  I recommend using [rowMode: 'array'](https://node-postgres.com/features/queries#row-mode) for this - then you can map the columns to whatever rows you'd like!  Sorry for the headache this can cause in certain situations.

**Comment by brianc** [comment]
You can also alias column names in your queries, which is what ORMs often do to avoid naming conflicts like this...however, that can sometimes be a bit tedious.  

I hope this helps!

**Comment by zhaosjason** [comment]
Ok, sounds good I'll look into those two things.  Thanks for the help!
