### ISSUE TITLE
createdb, create user

### ISSUE THREAD

**Issue by stevenvachon** [brianc/node-postgres#1337]
Is this possible? Would be awesome.

**Comment by charmander** [comment]
```js
await pool.query('CREATE DATABASE some_database')
await pool.query('CREATE USER some_user')
```

**Comment by stevenvachon** [comment]
create user doesn't support parameter bindings on passwords

**Comment by sehrope** [comment]
That's a limitation of the PostgreSQL command syntax itself. Some commands do not allow for parameters. You have to include the string in the SQL as a literal and make sure to properly escape it.

Check out https://github.com/datalanche/node-pg-format or https://github.com/segmentio/pg-escape to handle the escaping.

**Comment by stevenvachon** [comment]
Can't this library try to abstract that limitation?

**Comment by charmander** [comment]
That would be misleading. The modules sehrope linked above are a more appropriate solution.

**Comment by brianc** [comment]
Yah node-postgres does not do *any* query text parsing, we want to keep it close to in-line w/ the raw postgres protocol. This makes it easier to reason about & support & also allows other modules like those above to experiment w/ abstractions.

**Comment by stevenvachon** [comment]
Ok, thank you all.
