### ISSUE TITLE
Unable to insert JSON(B)

### ISSUE THREAD

**Issue by thomas-p-wilson** [brianc/node-postgres#1341]
Versions:
- Postgres 9.6
- node-postgres 6.4.0

Given the following table:
```
CREATE TABLE IF NOT EXISTS "events" (
    "data" JSONB NOT NULL
);
```

Each of the following queries fails in the exact same way:
```
client.query('INSERT INTO events (data) VALUES ($1)', [{a: 'b'}]); // Fails
client.query('INSERT INTO events (data) VALUES ($1)', [JSON.stringify({a: 'b'})]); // Fails
client.query("INSERT INTO events (data) VALUES ('{"a": "b"}')"); // Fails
```

Those queries result in the following error:
```
error: invalid hexadecimal digit: "{"
    at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
{ error: invalid hexadecimal digit: "{"
    at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
  name: 'error',
  length: 332,
  severity: 'ERROR',
  code: '22023',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL statement "SELECT digest((last_id::TEXT || event_body::TEXT)::BYTEA, \'sha1\')"\nPL/pgSQL function fn_event_compute_next_hash(bytea,jsonb) line 11 at SQL statement\nPL/pgSQL function fn_trigger_event_insert_compute_next_hash() line 15 at assignment',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'encode.c',
  line: '150',
  routine: 'get_hex' }
```

Now, of course I immediately examined my procedure, but the problem is I can't replicate the problem if I'm performing inserts from the psql console. So I'm fairly stumped.

From what I can tell, it's complaining about a section where I convert the JSON to text in order to hash it. Thing is, the incoming json is _exactly_ the same between a run of my node script and a psql execution, so it seems bizarre to me that this should be an issue.

Perchance does anyone have thoughts on the matter? Seems like most folks don't have an issue with this sort of thing.

**Comment by brianc** [comment]
Looks like there's some kinda trigger in your db: 

```
where: 'SQL statement "SELECT digest((last_id::TEXT || event_body::TEXT)::BYTEA, \'sha1\')"\nPL/pgSQL function fn_event_compute_next_hash(bytea,jsonb) line 11 at SQL statement\nPL/pgSQL function fn_trigger_event_insert_compute_next_hash() line 15 at assignment',
  ```

Is that something you added? That might be a good place to start lookin' 👀

**Comment by thomas-p-wilson** [comment]
As I noted, I've been examining that trigger. But the problem is I can't
replicate the issue in psql alone. To that end, I was hoping there might be
a quick thought on why node-postgres seems to be sending a different value
or format of the value. When I log the values in the trigger, they _appear_
identical.

**Comment by thomas-p-wilson** [comment]
Also, that said. If there isn't an issue off the top of your head that I
might examine, I'll continue digging on my own. Just wasn't sure if I was
missing something glaring.

**Comment by thomas-p-wilson** [comment]
Most strange. While the error I received seemed to indicate an issue with the JSON I was attempting to insert, the problem was in fact an incorrect data type on another field entirely and the error was just incorrect/misleading/unhelpful. Thanks for taking a look @brianc
