### ISSUE TITLE
Adding pg-reactive to  the wiki page Extras

### ISSUE THREAD

**Issue by haoliangyu** [brianc/node-postgres#1343]
Hey, 

Thanks for building this library. It's a very useful and well designed.

I have developed a library called [pg-reactive](https://github.com/haoliangyu/pg-reactive) to bridge this library and [RxJS 5](https://github.com/ReactiveX/rxjs). The **pg-reactive** is different from the existing [pg-rxjs](https://github.com/jadbox/pg-rxjs) at:
* **pg-reactive** supports [RxJS 5](https://github.com/ReactiveX/rxjs) and later, which is a rewrite of [RxJS 4](https://github.com/Reactive-Extensions/RxJS) (used by `pg-rxjs`) and introduces many breaking changes.
* **pg-reactive** is a lightweight implementation, which uses less code and dependencies.

I would like to add **pg-reactive** to the wiki page [Extras](https://github.com/brianc/node-postgres/wiki/Extras), but I don't have the permission to update it by myself. If you think **pg-reactive** is eligible, could you add it to the list?

``` markdown
[haoliangyu/pg-reactive](https://github.com/haoliangyu/pg-reactive) - a lightweight [RxJS 5](https://github.com/ReactiveX/rxjs) wrapper for `node-postgres`
```

Thanks

**Comment by brianc** [comment]
Added! Thanks & good luck!
