### ISSUE TITLE
How to detect a lost connection outside of the pool?

### ISSUE THREAD

**Issue by sibedge** [brianc/node-postgres#1351]
When we create connections via the new pool we rely on the pool to detect broken connections and re-create the corresponding `Client` object.

But when we need to use the connection directly, by creating our own `Client` outside of the pool, what is the recommended way to diagnose/detect a broken connection?

In a typical scenario we create one global `Client`, on which we execute `LISTEN` at the beginning, and that's it. After that the channel is just sitting there, waiting for a `NOTIFY` to arrive. And how can we detect when the channel got disconnected, so we need to re-create our `Client` and re-do the `LISTEN` query?

**Comment by sibedge** [comment]
Later on I tried adding `client.on('error', handler)`, which does get the errors related to the lost connection, but then we immediately run into this issue: https://github.com/brianc/node-pg-pool/issues/57

As I understand, that issue was fixed for the pool v1.8.0, but it remains within the core library, i.e. when we get the `error` event, we do not get the corresponding `Client` object, so we do not know which client needs to reconnect.

**Comment by charmander** [comment]
```js
client.on('error', error => {
    handler(error, client);
});
```

**Comment by sibedge** [comment]
Oh, I didn't realize that `this` would be pointing at the right `Client`.

@charmander thanks so much!

**Comment by sibedge** [comment]
@charmander a little unrelated, just wanted to ask, if that's ok...

What prompted you to give this advise to other postgresql developers? - 

```
2017-07-01 02:13:17 charmander: don't use pg-promise
2017-07-01 02:13:17 charmander: it's a fork of the previous version with questionable design decisions
```

For one thing, that library is based on the very latest version of `node-postgres`. And for another - what questionable design decisions are you talking about?

**Comment by offero** [comment]
So on error, should you recreate the client instance or reuse the existing one and just have it try to reconnect?

**Comment by charmander** [comment]
@offero Recreate. Clients can only be connected once, even though their API doesn’t really reflect that yet.
