### ISSUE TITLE
Client re-connection doesn't work

### ISSUE THREAD

**Issue by sibedge** [brianc/node-postgres#1352]
I'm running a simple test against the latest `pg`, under Node.js 8.1.2:

```js
const pg = require('pg');

var client = new pg.Client(connection);

function test() {
    client.connect(err => {
        if (err) {
            console.log(err);
            return;
        }
        client.query('select 123', [], (err, data) => {
            if (err) {
                console.log(err);
            } else {
                console.log('DATA:', data.rows[0]);
            }
            client.end();
        });
    });
}

setInterval(test, 1000);
```

And it outputs the following, every time:

```
DATA: anonymous { '?column?': 123 }
DATA: undefined
DATA: undefined
DATA: undefined
DATA: undefined
DATA: undefined
DATA: undefined
DATA: undefined
events.js:182
      throw er; // Unhandled 'error' event
      ^

error: invalid frontend message type 0
    at Connection.parseE (D:\NodeJS\tests\node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (D:\NodeJS\tests\node_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (D:\NodeJS\tests\node_modules\pg\lib\connection.js:129:22)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:588:20)
```

After I successfully call `client.end()`, it will successfully re-connect, successfully execute the query, just won't return any data. This looks odd.

And this - `error: invalid frontend message type 0` doesn't make any sense.

Could somebody, please explain, why we get such an odd output?

**UPDATE**

And if just after creating the client, I add the following:
```js
client.on('error', e => {
    console.log(e);
});
```
The output gets absolutely flooded with a huge error dumb, so big, I can't even paste it here.

**Comment by charmander** [comment]
I’m almost certain clients aren’t meant to be connected more than once (@brianc, could you confirm this?); treat them as unusable after calling `.end()`.

```diff
- var client = new pg.Client(connection);
-
 function test() {
+    var client = new pg.Client(connection);
+
     client.connect(err => {
         if (err) {
             console.log(err);
             return;
         }
         client.query('select 123', [], (err, data) => {
             if (err) {
                 console.log(err);
             } else {
                 console.log('DATA:', data.rows[0]);
             }
             client.end();
         });
     });
 }
```

**Comment by sibedge** [comment]
> I’m almost certain clients aren’t meant to be connected more than once...

And what is the reason for that?

**Comment by charmander** [comment]
They’re wrappers around a connection and should be associated with one connection.

**Comment by brianc** [comment]
Yeah though it's not really documented clients are cheap to instantiate and should be considered 'used up' once they've been disconnected.  There's a bit of a state machine inside the client w/ a bunch of event handlers being established after the connect event.  Your best bet is going to be to throw the old one away & make a new one.  The connection handshake over tcp is the part that takes a little bit of time, but reusing an existing client wouldn't save any time there as reconnecting would still need to happen - it would also introduce additional complexity in ensuring the old event handlers were disposed and the new ones set up correctly.  I'll re-open this & add it to the 7.0 milestone to return an error if a client has `connect` called on it more than once - hopefully that will make things more clear.

**Comment by sibedge** [comment]
It would be nice! The `Client` should throw an error when someone is trying to reconnect or call `.query` after calling `.end()`, the same as `pg-pool` should be throwing an error when someone calls `.connect` or `.query` after `pool.end()` has been called.

**Comment by brianc** [comment]
Closed with #1365

**Comment by waruwaruwaru** [comment]
I have a similar problem. 

`client.connect();
//Create JWT Strategy
//payload is the decode jwt token
const jwtLogin = new JwtStrategy(jwtOptions, function(payload, done) {
  //See if the user ID in the payload exists in our database
  console.log('after connect');
  client.query("SELECT FROM users where id = $1", [payload.sub], function(err, data) {
    // console.log('payload.sub: ', payload.sub);
    console.log('data: ', data);
    console.log('error: ', err);

    console.log('here')
    if (err) { return done(err, false); }
    if (data) {
      console.log('inside data');
      client.end((err) => {
        console.log('client has been disconnected');
        if (err) {
          console.log('there has been error disconnecting from client: ', err);
        }
      });
      return done(null, data);
    } else {
      client.end((err) => {
        console.log('client has been disconnected');
        if (err) {
          console.log('there has been error disconnecting from client: ', err);
        }
      });
      return done(null, false);
    }
  });`

The first time I hit my endpoint that runs this code, everything works fine. I get my data back from the database fetch and it console.logged "client has been disconnected" but when I hit this endpoint again, my code only console.log('after connect') and none of my other code runs. Am I using client.end() incorrectly?

**Comment by charmander** [comment]
@waruwaruwaru Don’t end the client if you want to continue using it. If you want to create a new client each time instead of keeping one open, you’ll have to do just that (`client = new Client(…); client.connect(…)` in `function (payload, done)`). If you want a connection pool (this is the usual case), use `Pool` instead.

**Comment by goodinmech** [comment]
Someone might get misunderstood the comment above, therefore I shall note:

1) Create a new client each time is slow
2) Keeping one open client is unreliable
3) Use a Pool is the right way (https://node-postgres.com/features/pooling)

**Comment by Q-dimi** [comment]
`var express = require('express');
var client = null;
var router = express.Router();

/* GET home page. */

router.get('/sign-up', function (req, res, next) {
    res.render('sign-up', { title: 'Express' });
});

/* submit user to database. */

router.post('/sign-up', async function (req, res) {

    //check email and password

    let errorObject = [];
    let email = req.body.email;
    let password = req.body.password;
    let confirmPassword = req.body.confirmPassword;
    let store_id = (new Date()).getTime().toString(36) + Math.random().toString(36).slice(2);


    if(password !== confirmPassword) { errorObject.push('&match=false') };
    const re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    if(re.test(email) === false) { errorObject.push('&email=false') };


    if(errorObject.length > 0) {
         errData = '';
         errorObject.map(v => errData += v);
         res.redirect(`/sign-up?paramErr=true${errData}`);
         return;
    } 

    //check if user exists and submit or return back

    client = await require('../db').init();

    let session_data = await insertIntoUsers(email, password, store_id);

    if(session_data.status === false) { 
        await require('../db').close(); 
        res.redirect(`/sign-up?stackErr=true${session_data.response}`);
        return;
    }
    
    req.session.email = session_data.email;
    req.session.store_id = session_data.store_id;
    req.session.id = session_data.id;

    await require('../db').close(); 
    res.redirect(`/seller?${JSON.stringify(session_data)}`);
    
});

/* insert into users. */

async function insertIntoUsers(email, password, store_id) {

    const text = 'INSERT INTO users(email, pwd, store_id) VALUES($1, $2, $3) RETURNING *';
    const values = [email, password, store_id];
    let res;

    try {

        res = await client.query(text, values);

        return { 
            status: true,
            id: res.rows[0].id,
            email: res.rows[0].email,
            store_id: res.rows[0].store_id,
        }

    } catch (err) {
        
        return {
            status: false,
            response: '&err=' + err
        }

    } 

}

module.exports = router;




`




`const { Client } = require('pg');

var client = null;

//init connection

async function initConn() {

  client = new Client({
      user: 'postgres',
      host: 'localhost',
      database: 'farm',
      password: 'Alexander456!!!',
      port: 5432,
    });

  client.connect(err => {
      if (err) {
          console.log(err);
      } else {
        console.log('connected 1')
      }
  });

  console.log('-----------------------------------------returning client-------------------------------------------------');

  return client;

}

//close connection

async function closeConn() {
  console.log('-------------------------------------------------------------------ending client-----------------------------------------------');
  return await client.end();
}


  module.exports = { 
    init: () => { return initConn() },
    close: () => { return closeConn() }
  }
`




I am not sure but I think when exporting the client connection from a script, you have to close the connection in the same script like i am doing here or copy the memory address of the client from where you are exporting to the importing module and close like that. I am just not sure how to retrieve the memory address of when you create the connection. 

I have tried to disconnect from the importing module while connecting from the exporting and for whatever reason, it seemed not to work... I am unsure why
