### ISSUE TITLE
inserting bytea column

### ISSUE THREAD

**Issue by prtome** [brianc/node-postgres#1353]

**Comment by prtome** [comment]
Hello,
I am trying to insert a bytea column, and I am a little bit lost with what I see when I search for info.

I am simply inserting it like this:
      insert into  logos(logo_blob) values($1);

where logo_blob is of type bytea, and will never be very big. 

I am using express-fileuploader to upload the file and read the image, so $1 is the data part of

     data: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 48 00 48 00 00 ff e1 00 5e 45 78 69 66 00 00 4d 4d 00 2a 00 00 00 08 00 01 87 69 00 04 00 00 00 01 00 00 ... >,
     encoding: '7bit',
     mimetype: 'image/jpeg',

I am doing it correctly ? Would a simple select then give me back the image ? I am trying to get it out with a psql command to check it but I get a damaged file, so I am wondering at which point I am in error. Thank for pointers to the correct direction.

**Comment by charmander** [comment]
Yes, that looks like it should work fine. What does your “damaged file” look like?

**Comment by prtome** [comment]
Thanks, now that I know that part should be ok, I could find where I was wrong in retrieving the data
it works now, I was doing wrong my retrieve from db. I was trying from psql - wanting to check if the image was ok.
This query works when retrieving , from the cmd line:
        psql  -t -A -o "/tmp/imagetest.jpg" -c  "SELECT encode(logo_blob,'base64') FROM 
logos LIMIT 1";
        base64 -D < /tmp/imagetest.jpg > ./toto.jpg

toto.jpg is perfect. Now to get that on the web ;)
