### ISSUE TITLE
Removing event listeners on closed clients

### ISSUE THREAD

**Issue by sibedge** [brianc/node-postgres#1354]
Reading the code, I can't figure out whether or not it is required to remove event listeners from the `Client` (when created directly), after calling method `.end()`.

For example, if I had `client.on('notification', handler)`, and then at some point I call `client.end()`, do I still need to do `client.removeListener('notification', handler)` or not?

I think it would be a good idea for method `Client.end()` to call `this.removeAllListeners()`, to avoid leaks and the ambiguity.

**Comment by charmander** [comment]
It’s not required, no, unless you hold a reference to the unusable client around for some reason – and breaking a manual `emit()` after `end()` doesn’t make sense.
