### ISSUE TITLE
Query not works

### ISSUE THREAD

**Issue by gabriel7493** [brianc/node-postgres#1357]
I have this error when I want to execute a query

`C:\Users\Familia\Documents\Programacion\Proyectos\Freelance\Social Network Spain API\apirest\node_modules\pg\lib\query.js:206
    self.values = self.values.map(utils.prepareValue);
                              ^

TypeError: self.values.map is not a function
    at Result.Query.prepare (C:\Users\Familia\Documents\Programacion\Proyectos\Freelance\Social Network Spain API\apirest\node_mod
ules\pg\lib\query.js:206:31)
    at Result.Query.submit (C:\Users\Familia\Documents\Programacion\Proyectos\Freelance\Social Network Spain API\apirest\node_modu
les\pg\lib\query.js:168:10)
    at Client._pulseQueryQueue (C:\Users\Familia\Documents\Programacion\Proyectos\Freelance\Social Network Spain API\apirest\node_
modules\pg\lib\client.js:337:24)
    at Connection.<anonymous> (C:\Users\Familia\Documents\Programacion\Proyectos\Freelance\Social Network Spain API\apirest\node_m
odules\pg\lib\client.js:178:10)
    at emitOne (events.js:101:20)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (C:\Users\Familia\Documents\Programacion\Proyectos\Freelance\Social Network Spain API\apirest\node_modul
es\pg\lib\connection.js:133:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)`

I let you the code I wrote:
server.js:
`apiRoutes.post('/authenticate', function(req, res) {
	if (!req.body.username || !req.body.password) {
		res.json({
			success: false,
			msg: 'Please pass name and password'
		});
	} else {
		var parameters = new Array(req.body.username, req.body.password);
		User.getUser(parameters, req, res);
	}
});`

user.js:
`var db = require('../database/connection');

var queryGetUser = 'SELECT * FROM adm_usuarios WHERE nombre=$1 AND password_digest=$2';

var getUser = function(parameters, req, res) {
	var user = '';	
	db.executeQuery(queryGetUser, parameters, function(result) {
		console.log(queryGetUser);
		if (!req || !res) {
			user = result;			
		} else {
			if (result.rows.length) {
				res.status(404).json({
					success: false,
					msg: 'User not found'
				});
			} else if (result.rows.length > 0) {
				user = result.rows[0];
				res.status(200).json(user);
			}
		}
	});	
}

module.exports.getUser = getUser;`

connection.js:
`var Pool = require('pg').Pool;

var pool = new Pool({
	user: 'postgres',
	password: '',
	host: '127.0.0.1',
	database: 'spainapi',
	max: 10,
	idleTimeoutMillis: 1000
});

pool.executeQuery = function(query, arguments, callback) {
	pool.connect(function(err, client, done) {		
		if (err) {
			return console.error('error fetching client from pool: ', err);
		}

		client.query(query, arguments, function(err, result) {
			done(err);
			if (err) {
				return console.error('error running query: ', err);
			}
			callback(result);
		});
	});
};

module.exports = pool;`

**Comment by brianc** [comment]
I appreciate you filing an issue here & would like to try and help; however, I receive multiple issues & request for help on a nearly daily basis and having properly formatted code is something that really makes triaging things easier - could you update your issue text by applying some [proper formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to your code? thanks!

**Comment by charmander** [comment]
Enable strict mode; your use of the name `arguments` for a parameter conflicts with the usual `arguments`. Nothing to do with pg.
