### ISSUE TITLE
error: invalid input syntax for integer: "ALL"

### ISSUE THREAD

**Issue by danizavtz** [brianc/node-postgres#1360]
Hello, i'm running in trouble when executing a node query using this lib.
Here is the piece of code:
```
 var sql = 'SELECT t."id", t."serialNumber", t."storeCode" FROM terminal t LIMIT $1';
        postgres.client.query(sql,[req.query.limit || 'ALL'], function(err, results) {
        }

```

here is the error:
 invalid input syntax for integer: "ALL"

but this is a perfect sintax when running query directly in psql.
here is the desired value for the SQL.
`SELECT  * FROM terminal LIMIT ALL;`

I'm using the current release version 6.4

**Comment by sehrope** [comment]
The `$1` is a parameter so the command get's invoked with `'ALL'` as a literal, not an identifier. You can't specify it as a parameter as identifiers need to be included in the SQL itself. This is similar to how you can't do `CREATE TABLE $1 ...` to parameterize the table name.

You'll need to either have an if/then logic to generate the SQL with the `... LIMIT $1` if `req.query.limit` is a number or with `... LIMIT ALL` suffixed if it's the string `'ALL`' (or remove the LIMIT clause in that case as it's not needed).

**Comment by danizavtz** [comment]
Thanks. This is the work around i used:

`sql = 'SELECT * FROM terminal LIMIT '.concat(req.query.limit ? req.query.limit : 'ALL');`

omitting the column names for better understanding.

**Comment by sehrope** [comment]
Make sure that you've validated that `req.query.limit` is a number or instead use parameters in the case where it's meant to be a numeric limit (best option).

Otherwise it's susceptible to SQL injection. Ex: If `req.query.limit = '1; DELETE FROM some_other_table'` bad things™ happen...

**Comment by charmander** [comment]
`req.query` indeed looks client-controlled. At the very least, `.concat(req.query.limit ? parseInt(req.query.limit) : 'ALL')`.

**Comment by danizavtz** [comment]
I have a middleware function that validate the body, query and params.
for that i'm using express-validator
Thanks for the advices.
