### ISSUE TITLE
Please add example with connection string

### ISSUE THREAD

**Issue by mariusa** [brianc/node-postgres#1361]
Previous versions were used with
```
pg.connect(process.env.DATABASE_URL, function (err, client, done) {
..
})
```

With pg7, how does that work? Would you please add an example, besides the current 
```
  user: 'foo', //env var: PGUSER
  database: 'my_db', //env var: PGDATABASE
```

Maybe
```
var config = {
  connection_string: process.env.DATABASE_URL,
  max: 10, // max number of clients in the pool
};
```
?

Hope it won't require a separate module just for this
https://www.npmjs.com/package/pg-connection-string

Thanks!

PS: docs mention pg7, but no estimated release date. Any estimate?

**Comment by charmander** [comment]
See https://node-postgres.com/features/connecting#connection-uri:

```diff
 var config = {
-  connection_string: process.env.DATABASE_URL,
+  connectionString: process.env.DATABASE_URL,
   max: 10, // max number of clients in the pool
 };
```
