### ISSUE TITLE
Generic connection strings

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1362]
I have just developed a generic version of URL connection strings - [connection-string](https://github.com/vitaly-t/connection-string) that can offer this driver complete flexibility in how and what connection parameters it decides to support, without the need to update any dependencies.

@brianc 

Maybe this is something you would consider for v7 of the library? This would become a milestone to eventually supporting all that vast set of parameters that PostgreSQL can use when connecting.

**Comment by charmander** [comment]
```
> url.parse('protocol://user:password@hostname:12345/seg1/seg2?p1=val1&p2=val2', true)
Url {
  protocol: 'protocol:',
  slashes: true,
  auth: 'user:password',
  host: 'hostname:12345',
  port: '12345',
  hostname: 'hostname',
  hash: null,
  search: '?p1=val1&p2=val2',
  query: { p1: 'val1', p2: 'val2' },
  pathname: '/seg1/seg2',
  path: '/seg1/seg2?p1=val1&p2=val2',
  href: 'protocol://user:password@hostname:12345/seg1/seg2?p1=val1&p2=val2' }
```

**Comment by vitaly-t** [comment]
@charmander cheers, I'm well aware of the `url` module in Node.js.

The key differences from my module:

* It supports fully-optional syntax (see examples [here](https://github.com/vitaly-t/connection-string/wiki#optional-use-cases)), which is quite important
* It works in all browsers the same (not that it matters here)

**Comment by charmander** [comment]
I don’t think supporting a syntax that looks extremely similar to libpq’s (https://www.postgresql.org/docs/current/static/libpq-connect.html#AEN45571) but isn’t is a good idea.

**Comment by vitaly-t** [comment]
@charmander could you, please revise your answer, I don't understand what it is saying for or against :)

**Comment by charmander** [comment]
“Fully-optional syntax” isn’t the syntax libpq supports. It’s something new that looks confusingly similar. I am against introducing it.

**Comment by vitaly-t** [comment]
It would let `node-postgres` fill up the missing details with the values from the `pg.defaults`, as it does for the objects, making the whole connection thing consistent.

**Comment by caub** [comment]
URL#searchParams / URLSearchParams is probably more the way to go

**Comment by vitaly-t** [comment]
@caub `URLSearchParams ` only gives you access to the parameters, it doesn't give you access to the rest of the connection values.

**Comment by caub** [comment]
and new URL(connectionString) or course, for the others params

**Comment by vitaly-t** [comment]
@caub just a few examples where Node.js URL will fail to parse:

```js
new URL('localhost:123');
new URL('postgres://user@');
new URL('postgres://user:password@');
```
there are plenty more, in fact. That's because the standard implementation is fixed to an ideal URL presentation, it doesn't support optional parameters, so if you want to provide defaults for those - you can't.

**Comment by brianc** [comment]
I think this is best handled in userland. If you want to support non-standard conforming URLs the best place to do so would be in your own apps.  I am happy to add this to the wiki though if you'd like as an additional library one could use in their own apps.
