### ISSUE TITLE
Option to auto-convert case

### ISSUE THREAD

**Issue by stevenvachon** [brianc/node-postgres#1370]
When `insert`ing/etc, it could convert from camelCase to snake_case, and the reverse when `select`ing/etc.

[pg-camelcase](https://npmjs.com/pg-camelcase) attempted this years ago. I don't know if it still works but its API is so terrible that I don't wish to try it. The idea, however, is very interesting to me.

**Comment by stevenvachon** [comment]
This is better off done elsewhere: https://github.com/tgriesser/knex/issues/2084

**Comment by brianc** [comment]
👍   I usually use `_.snakeCase` and friends to do this in my apps at the data access layer. 

https://lodash.com/docs/4.17.4#snakeCase

**Comment by serge-nikitin** [comment]
@brianc Can you please add an example in FAQ how you do camelCase transformation in result? It looks like pg-camelcase is outdated.

**Comment by sebnyberg** [comment]
I case someone else comes across this problem. I solved it by quoting and selecting the snake_cased properties as their camelCase equivalents.

```javascript
class UserRepository {
    public static propertyNames = ["id", "name", "last_logged_on"];
    public static tableName = "user";

    // returns [`"user"."id" as "id"`, `"user"."name" as "name"`, `"user"."last_logged_on" as "lastLoggedOn"]
    public static selectString = getSelectStrings(
        UserRepository.propertyNames,
        UserRepository.tableName).join(", ");

    ....

    public static getAll() {
        const sql = `
            select ${UserRepository.selectString}
            from ${UserRepository.tableName}
        `
    ...
```

The quoted string is generated using lodash:

```javascript
import { camelCase } from 'lodash';

export function getSelectStrings(snakeCasedProperties, tableName) =>
    snakeCasedProperties.map((prop) => `"${tableName}"."${prop}" as "${camelCase(prop)}"`);
```
