### ISSUE TITLE
Insert Fails with jsonb_populate_recordset

### ISSUE THREAD

**Issue by PythonDevOp** [brianc/node-postgres#1371]
I am trying to insert an array of JSON into Postgres. Everything appears to run successfully (the table gets created), but there is no data inserted, and no error given. I am using the async/await method for transactions, but I can't understand what is failing.

```
(async() => {

    const client = await pool.connect()

    let val= [
        {"table_pk":1,"NAME":"my Great Name","ROLE":"name1"},
        {"table_pk":2,"NAME":"new Name","ROLE":"name1"},
        {"table_pk":3,"NAME":"someone's funny name","ROLE":"name1"}
        ]

    try {
        await client.query('BEGIN');
        await client.query('DROP TABLE IF EXISTS myTable')
        await client.query(`CREATE TABLE myTable(table_pk INTEGER PRIMARY KEY, name TEXT, role TEXT)`)

        await client.query(`INSERT INTO myTable SELECT * FROM jsonb_populate_recordset(NULL::myTable, $1::jsonb)`,[JSON.stringify(val)]);
        await client.query('COMMIT');
    }
    catch (e) {
        await client.query('ROLLBACK');
        throw e
    }
    finally {
        client.release();
    }
})().catch(e => console.error(e.stack))
```
I am pretty sure it has to do with the single quoted item, but I thought that putting it into a param like $1 would escape the quotes. Is there something I am missing?

**EDIT**
Was missing an INSERT. I updated the code to reflect changes. I see data being inserted now, but missing values.

**Comment by charmander** [comment]
Transactions aren’t nestable, and you’re releasing the same client multiple times. Look into [savepoints][1] for something close (if you need it at all; nesting looks like it might have just been a mistake here).

  [1]: https://www.postgresql.org/docs/current/static/sql-savepoint.html

**Comment by PythonDevOp** [comment]
Yes, that was a copy/paste error with the two try/await client.query('BEGIN') statements, as it is not like that in my code. I just updated it above. 

What do you mean by releasing the same client multiple times? I thought a transaction would hold onto the same client throughout?

**Comment by charmander** [comment]
Where is `table` defined for `${table}`?

**Comment by PythonDevOp** [comment]
It was passed into the function I am running. I am going to update the code in one minute to address something I found strange.

**Comment by PythonDevOp** [comment]
I updated the example. Basically I was missing an INSERT, and now that it is there, I can insert but there are missing values for cols NAME and ROLE after insert. The table_pk field gets populated though.

**Comment by charmander** [comment]
You’ve put the property names in uppercase, but the column names are lowercase. `jsonb_populate_recordset` is case-sensitive.

**Comment by PythonDevOp** [comment]
Thanks! I did not know that.
