### ISSUE TITLE
7.0.0 Breaks sequelize support

### ISSUE THREAD

**Issue by thiloo** [brianc/node-postgres#1372]
When running the pg model in 7.0.0 with sequelize a connection error occurs. No connection can be established.

The message reads:
"TypeError: connection.query(...).on is not a function"

This error does disappear when downgrading the package to 6.3.0. 

Modules used besides pg are sequelize 4.3.2 and pg-hstore 2.3.2

**Comment by vitaly-t** [comment]
It was deprecated with a warning message in 6.4, due to be removed in v7.x, and so it is.

No more events on query requests. Use either callbacks or promises.

**Comment by brianc** [comment]
@thiloo - I introduced deprecation warnings about a month ago & you're welcome to stay on `pg@6.x` until the author upgrades.  Using the event emitter style for flow control on the result set wasn't something recommended or documented for quite a while.  It's still possible for the author of sequlize to go down this route if they need to:

https://node-postgres.com/guides/upgrading#client-query-submittable-

However it also shouldn't be hard to move from event-emitter to callback or promise style - they have advantages of making the external API easier to reason about and will unlock future advantages of me being able to allocate fewer objects internally when using promises/callbacks and hopefully get some performance improvements in the long term.

Cheers!

**Comment by thiloo** [comment]
@brianc thank you for clarifying. It seems `sequelize` is on it. https://github.com/sequelize/sequelize/pull/7888
