### ISSUE TITLE
pool.totalCount

### ISSUE THREAD

**Issue by jerboar** [brianc/node-postgres#1376]
```
/*jshint node:true */
'use strict';
var config = require('../config/config');
var pg = require('pg');
var pool = new pg.Pool(config.db);

pool.on('error', function (err, client) {
    console.error('idle client error', err.message, err.stack);
});

module.exports.count = function () {
    console.log(pool.totalCount);
    return pool.totalCount;
};
```
pool.totalCount undefined
am i doing something wrong?

**Comment by vitaly-t** [comment]
`totalCount` is a function that returns the count.

**Comment by vitaly-t** [comment]
Most likely that's because you are using an older driver version. That property exists only in version 7.

**Comment by brianc** [comment]
You can upgrade `pg-pool` independently if you want to use it with an earlier version of `pg`:

```
npm i pg pg-pool@2
```

then in code
```js
const Pool = require('pg-pool')
const pool = new Pool()
console.log(pool.totalCount)
```

Please lemme know if you're already using `pg@7` and not seeing the total count.
