### ISSUE TITLE
Negative PostgresInterval milliseconds is positive

### ISSUE THREAD

**Issue by jhihn** [brianc/node-postgres#1380]
I'm not sure if this is in your library (I'm using pg-promise) but I think it would be at your layer.
I realized that when dealing with negative intervals, the milliseconds is positive.

    PostgresInterval { days: -13, minutes: -40, seconds: -17, milliseconds: 545.936 }

I'd expect it to be negative, so that if the second and milliseconds components are added, that would result in -17.546 and not -16.454 ?

**Comment by charmander** [comment]
This is ultimately a bug in https://github.com/bendrucker/postgres-interval:

```shellsession
$ node -p "require('postgres-interval')('-13 days -00:40:17.545936')"
PostgresInterval { days: -13, minutes: -40, seconds: -17, milliseconds: 545.936 }
```

I’ll get a pull request ready. Thanks for the report!

**Comment by charmander** [comment]
(And yes, this is definitely a bug and not some odd-but-intentional choice. Justification for breaking backwards compatibility:

```shellsession
$ node -p "require('postgres-interval')('-13 days -00:00:00.545936').toPostgres()"
-13 days 0.545936 seconds
```
)
