### ISSUE TITLE
client.end() doesn't always return a promise

### ISSUE THREAD

**Issue by bridgelabs** [brianc/node-postgres#1381]
For some background, every call to our database comes from short-lived AWS Lambda functions, so we can't use a connection pool. As a result, we're creating and managing our own client objects. Since the connectionTimeoutMillis option only works when using pools, we are manually calling client.connection.stream.destroy() if the client.connect() call takes more than 3 seconds. This causes client.connect() to error, in which we first call client.end(), and then we create a new client object to try calling client.connect() again. The problem is that client.end() doesn't return a promise in this scenario, so the code hangs.

This code reproduces the problem on v7.0.1:

```javascript
function getClient(retryCount) {
  retryCount = retryCount ? retryCount : 0;
  var client = new pg.Client(pgConfig);
  client.on("error", function(error) {
    client.idle_error = error;
  });
  var connectionTimeout = setTimeout(function() { client.connection.stream.destroy() }, 3000);
  return client.connect().then(function() {
    clearTimeout(connectionTimeout);
    return Parse.Promise.as(client);
  }, function(error) {
    if(retryCount < 10) {
      return client.end().then(function() {
        return getClient(retryCount+1);
      });
    }
    return Parse.Promise.error(error);
  });
}
```

I also want to give a big thanks to the maintainers of this project because you have made working with PostgreSQL a breeze!

**Comment by charmander** [comment]
If connecting fails, you can assume the client doesn’t need to be disconnected, so remove the `client.end()` and `return getClient(retryCount + 1)` directly.

**Comment by bridgelabs** [comment]
Thanks, that fixes my current issue, but I think there is still a bug in the client.end() implementation. It looks like if client.end() gets called when client.activeQuery exists, then a promise is never returned.

From /lib/client.js:

```javascript
Client.prototype.end = function (cb) {
  this._ending = true
  if (this.activeQuery) {
    // if we have an active query we need to force a disconnect
    // on the socket - otherwise a hung query could block end forever
    this.connection.stream.destroy(new Error('Connection terminated by user'))
    return
  }
  if (cb) {
    this.connection.end()
    this.connection.once('end', cb)
  } else {
    return new global.Promise((resolve, reject) => {
      this.connection.end()
      this.connection.once('end', resolve)
    })
  }
}
```
