### ISSUE TITLE
util.escapeValue

### ISSUE THREAD

**Issue by chiluap** [brianc/node-postgres#1387]
Hi there,

I was looking for a way to escape values by their type to make Bulk-INSERTS.

something like: 

util.escapeValue(<value>, [type]);

```javascript
util.escapeValue('2017-07-26T14:07:35.106000', 'timestamp without time zone');
// => ('2017-07-26T14:07:35.106000')::timestamp without time zone
util.escapeValue('some unescaped text', 'text');
// => ('some unescaped text')::text
util.escapeValue('23', 'integer');
// => 23
```

does this exist here ?
Looked around found nothing...sorry

Thanks for the good work with node-postgres b.t.w.

maybe start with something like:

```javascript
sqlEscape(value, type) {
        if (value === null || _.isEmpty(value)) {
            return '';
        }
        value = value.replace("'", "''");
        return "('" + value + "')::" + type;
 }
```

**Comment by abenhamdine** [comment]
Personally I use https://github.com/datalanche/node-pg-format for this.

**Comment by vitaly-t** [comment]
@chiluap you can use the method from here: https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise

**Comment by charmander** [comment]
Use arrays: https://github.com/brianc/node-postgres/issues/957#issuecomment-295583050

**Comment by chiluap** [comment]
@charmander: That's the trick. Thank you.
