### ISSUE TITLE
connectionTimeoutMillis doesn't work

### ISSUE THREAD

**Issue by bydga** [brianc/node-postgres#1390]
Im trying to use the connTimeoutMilis feature (respond error when a connection from a pool cannot be obtained within specified limit) - and it doesnt work.

Here is a minimal example:

```coffee
{ Pool } = require 'pg'

process.on 'uncaughtException', (err) -> console.log "uncaught", err

pool = new Pool
	connectionString: "tcp://usr:pass@XXX.us-west-2.rds.amazonaws.com/db_name?ssl=true"
	max: 3
	connectionTimeoutMillis: 10000

pool.on 'error', (e, client) -> console.log 'pool.on.err', e

pool.connect (e, client, done) ->
	console.log "first", e
	pool.connect (e, client, done) ->
		console.log "second", e
		pool.connect (e, client, done) ->
			console.log "third", e
			pool.connect (e, client, done) ->
				console.log "fourth", e

```

output: 
```
$ coffee pg.coffee
first undefined
second undefined
third undefined
```

and nothing more, no error thrown, no err callback being called..

versions:
```
$ npm ls | egrep "pg|postgr"
├─┬ pg@7.0.2
│ ├── pg-connection-string@0.1.3
│ ├── pg-pool@2.0.1
│ ├─┬ pg-types@1.12.0
│ │ ├── postgres-array@1.0.2
│ │ ├── postgres-bytea@1.0.0
│ │ ├── postgres-date@1.0.3
│ │ └── postgres-interval@1.1.1
│ ├─┬ pgpass@1.0.2
```

**Comment by brianc** [comment]
Thanks for the fabulous bug report. I'll look at this ASAP.

**Comment by brianc** [comment]
:white_check_mark: small self contained steps to reproduce
:white_check_mark: listing of all the versions in use

Thanks for the nice bug report! I'll look at this ASAP.

**Comment by charmander** [comment]
@brianc, is this the intended behaviour of `connectionTimeoutMillis`? i.e. should it only apply when connecting, or should it apply when the pool has reached its limit and the caller has to wait for the next available client as well?

**Comment by ghafran** [comment]
There is a bug with 7.x where the pooled client never closes, no matter what the **connectionTimeoutMillis** is set to.

Even after calling done, the connection remains open indefinitely.
`
this.pool.connect(function (err, client, done) {
done();
});
`

This works fine with 6.1.0. We have reverted back to 6.1.0 until this is resolved because its causing connection leaks.

**Comment by charmander** [comment]
@ghafran This issue is about `connectionTimeoutMillis`, not `idleTimeoutMillis`.

**Comment by brianc** [comment]
@charmander thanks for drawing my attention back to this one. Got lost in the never-ending issue shuffle.  I wanted `connectionTimeoutMillis` to apply both when initially connecting and waiting for a client from a full pool.  The thinking behind that is you're calling `connect` either time regardless so it should always behave the same way.  Likewise `pool.query` should reject after `connectionTimeoutMillis` if the timeout is exceeded.  I'll look at this right away.

**Comment by brianc** [comment]
@bydga - My apologies for the delay in responding here to the bug; I get a _lot_ of issues and sometimes they slip off my radar...I've fixed it [here](https://github.com/brianc/node-pg-pool/pull/70).  👏  Please install the newest version of `pg-pool` and see if it fixes your issue!

Thanks

If you or your company benefit from node-postgres and have the means, please consider supporting my work on [Patreon](https://www.patreon.com/node_postgres).
