### ISSUE TITLE
Question: how to properly set datestyle on pooled connections

### ISSUE THREAD

**Issue by bydga** [brianc/node-postgres#1393]
When using the `pool.connect` & `client.release` approach, I'm setting the `set datestyle = iso mdy` as a first query to have my date-types parsed properly.

However, how to do it with the `pool.query` call? Since the connection returned is random - and might be an existing one recently returned to the pool as well as a newly established one..

Im not sure, if setting pg.types.setTypeParser for all the date/datetime/timestamp with/without timezone is a way I want to go..

Suggestions?  :)

**Comment by charmander** [comment]
You can create a client type for use with the pool providing custom startup configuration:

```javascript
const pool = new pg.Pool({
    Client: class extends pg.Client {
        getStartupConf() {
            return Object.assign(super.getStartupConf(), {
                DateStyle: 'ISO,MDY',
            });
        }
    },
    ⋮
});
```

It might be nice to have an option along these lines, though:

```javascript
class pool = new pg.Pool({
    connectionOptions: {
        DateStyle: 'ISO,MDY',
    },
    ⋮
});

**Comment by bydga** [comment]
hm, i've solved it by doing 
```coffee
pool.on "connect", (client) ->
    client.query "SET DATESTYLE = iso, mdy"
```

but your solution looks better :)

**Comment by brianc** [comment]
I added this to the [documentation](https://node-postgres.com/api/pool#-code-pool-on-39-connect-39-client-client-gt-void-gt-void-code-)
