### ISSUE TITLE
Put new documentation in extra repo

### ISSUE THREAD

**Issue by deyhle** [brianc/node-postgres#1395]
First, congrats to the quite good documentation at https://node-postgres.com!
I just stumbled upon a typo (programmatic example on https://node-postgres.com/features/connecting#programmatic, "new Client" example has duplicate `password` parameter instead of `database`) and wanted to fix that with a pull request, but could not find the code for the website anywhere. As it seems to be outside of this repo and I also couldn't find a repo looking like it in your github account, I assume it is not public yet?

**Comment by Spaxe** [comment]
Same here, congrats on the awesome doc!

I also have a question regards to the use of `client.release()` at https://node-postgres.com/features/transactions, but the `release()` function is not documented anywhere.

I've tracked it down at https://github.com/brianc/node-pg-pool/blob/master/index.js#L17 and would really love to improve the documentation where I can! ⭐️

**Comment by abenhamdine** [comment]
@Spaxe see also https://github.com/brianc/node-postgres/issues/1302

**Comment by charmander** [comment]
@Spaxe `release` is documented at https://node-postgres.com/api/pool#release-err-error-.

**Comment by brianc** [comment]
Hey thanks for pointing out the typos. I've fixed 'em!  The long term plan is to open source the docs, but I'm not ready to yet.  In the mean time feel free to report any other issues you find with them here or point out places they're unclear or could be better. Thanks!
