### ISSUE TITLE
Error with parameterized query

### ISSUE THREAD

**Issue by gregoryfm** [brianc/node-postgres#1396]
I'm trying to do a parameterized query like the [documentation](https://node-postgres.com/features/queries#parameterized-query).

When I do this, works normally.
```
const sql = 'SELECT * FROM users WHERE id = 1'
client.query(sql, (err, res) => {
  if (err) {
    console.log(err)
  } else {
    console.log(res.rows[0])
  }
})
```

But like this, doesn't works.
```
const sql = 'SELECT * FROM users WHERE id = $1'
const params = [1]
client.query(sql, params, (err, res) => {
  if (err) {
    console.log(err)
  } else {
    console.log(res.rows[0])
  }
})
```

Follow the error message:
> { error: cannot insert multiple commands into a prepared statement
>     at Connection.parseE (/home/gregory/workspace/learnnode/node_modules/pg/lib/connection.js:567:11)
>     at Connection.parseMessage (/home/gregory/workspace/learnnode/node_modules/pg/lib/connection.js:391:17)
>     at Socket.<anonymous> (/home/gregory/workspace/learnnode/node_modules/pg/lib/connection.js:129:22)
>     at emitOne (events.js:115:13)
>     at Socket.emit (events.js:210:7)
>     at addChunk (_stream_readable.js:252:12)
>     at readableAddChunk (_stream_readable.js:239:11)
>     at Socket.Readable.push (_stream_readable.js:197:10)
>     at TCP.onread (net.js:588:20)
>   name: 'error',
>   length: 116,
>   severity: 'ERRO',
>   code: '42601',
>   detail: undefined,
>   hint: undefined,
>   position: undefined,
>   internalPosition: undefined,
>   internalQuery: undefined,
>   where: undefined,
>   schema: undefined,
>   table: undefined,
>   column: undefined,
>   dataType: undefined,
>   constraint: undefined,
>   file: 'postgres.c',
>   line: '1195',
>   routine: 'exec_parse_message' }

**Comment by brianc** [comment]
Is that the _actual_ query text you're using?  That error is because postgres doesn't support a multi-command prepared statement.  Your actual query probably has 2 different commands separated by a semi-colon like:

```
const queryText = 'INSERT INTO foo(bar) values($1); INSERT INTO baz(zug) values($1)`
const params = [1]
pool.query(queryText, params)
```

which postgres doesn't support.

**Comment by gregoryfm** [comment]
Hi @brianc thanks for answer.
Sorry I forgot, my sql has the set schema at first.

Like: `const sql = 'set schema \'node\'; SELECT * FROM users WHERE id = $1'`

I don't found in documentation where I define a different schema.

**Comment by brianc** [comment]
nice! Glad we got it sorted out! 💃
