### ISSUE TITLE
Add pg-error-constants to "Extras" page in Wiki

### ISSUE THREAD

**Issue by LinusU** [brianc/node-postgres#1397]
I just published a package that exports all of the error constants, could potentially be useful to someone. What do you think about adding it to the ["Extras" page in the Wiki](https://github.com/brianc/node-postgres/wiki/Extras)?

GitHub: https://github.com/LinusU/pg-error-constants
Npm: https://www.npmjs.com/package/pg-error-constants

**Comment by brianc** [comment]
awesome! adding it. Sorry the wiki is locked - it was getting vandalized over and over so I had to lock it.

**Comment by brianc** [comment]
added!

**Comment by LinusU** [comment]
Awesome 🙌
