### ISSUE TITLE
pg module in Sequelize not working with transactions on Postgres-XL

### ISSUE THREAD

**Issue by omkar100100** [brianc/node-postgres#1401]
**NPM PACKAGES:**
"pg": "^4.4.3",
 "sequelize": "^4.4.2",

**CODE SNIPPED:**
NodeService.prototype.createNode=function(node,app){
   return models1.sequelize.transaction({isolationLevel: 
   models1.Sequelize.Transaction.ISOLATION_LEVELS.SERIALIZABLE}, t1 => {
            return new Promise(function(resolve, reject){
                models1.QuorumNode.create(node,{transaction:t1})
                .then(function(node){
                    resolve(node);
                })
            })

    })
}

**SUCCESSFULL ON POSTGRES**
-----------------------------
POST /node - - ms - -
Executing (c1a665fe-8360-4567-bbf8-c40b3770f12f): START TRANSACTION;
Executing (c1a665fe-8360-4567-bbf8-c40b3770f12f): INSERT INTO "public"."QuorumNode" ("id","NodeName","createdAt","updatedAt") VALUES (DEFAULT,'NodeName1-00','2017-08-07 06:21:49.000 +00:00','2017-08-07 06:21:49.000 +00:00') RETURNING *;
Executing (c1a665fe-8360-4567-bbf8-c40b3770f12f): COMMIT;
POST /node 200 410.296 ms - 169

**ON POSTGRES-XL**
--------------------------
**VERSIONS USED:**
------------------
postgressql : 9.5.6
postgres XL : 9.5r1.5

Executing (3dad455b-4036-4b36-a724-05a4e07f07f8): START TRANSACTION;
Executing (3dad455b-4036-4b36-a724-05a4e07f07f8 ): SET SESSION TRANSACTION ISOLAT                                   ION LEVEL SERIALIZABLE;
Executing (3dad455b-4036-4b36-a724-05a4e07f07f8): INSERT INTO "s1"."Node"("id","NodeName","createdAt","updatedAt") VALUES (DEFAULT,'TestName','2017-08-0                                        6 14:47:39.000 +00:00','2017-08-06 14:47:39.000 +00:00') RETURNING *;
Unhandled rejection **SequelizeDatabaseError: cannot execute INSERT in a read-only transaction**
    at Query.formatError (/home/user1/test/code/service/s1/node_modules/sequelize/lib/dialects/postgres/query.js:338:16)
    at /home/user1/test/code/service/s1/node_modules/sequelize/lib/dialects/postgres/query.js:86:18

**Comment by charmander** [comment]
Does the operation work with any other tool or driver?

Please pare down your example to something small and self-contained that only uses pg if possible, and [format it][github-markdown] properly.


  [github-markdown]: https://guides.github.com/features/mastering-markdown/

**Comment by vitaly-t** [comment]
The issue isn't relevant to this driver.

@omkar100100 your own code is the very answer to your problem:

**On Postgres:**

```
START TRANSACTION;
INSERT INTO "public"."QuorumNode"...
```

**On Postgres-XL:**

```
START TRANSACTION;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
INSERT INTO "s1"."Node"...
```

i.e. you specifically set your transaction to Read-Only and thus disallow any write operations inside it, so the server tells you exactly: `cannot execute INSERT in a read-only transaction`.
