### ISSUE TITLE
pool.activeCount is always undefined

### ISSUE THREAD

**Issue by abenhamdine** [brianc/node-postgres#1402]
Hi Brianc,

It looks like `pool.activeCount` (https://node-postgres.com/api/pool#-code-pool-totalcount-int-code-) is always undefined : 

my code : 
```js
pool.on('connect', (client) => {
	console.log(`Nb of clients in pool : total = ${pool.totalCount} idle = ${pool.idleCount} active = ${pool.activeCount}`);
});
```

console : 
```bash
Nb of clients in pool : total = 2 idle = 0 active = undefined
Nb of clients in pool : total = 3 idle = 1 active = undefined
Nb of clients in pool : total = 3 idle = 1 active = undefined
Nb of clients in pool : total = 8 idle = 2 active = undefined
Nb of clients in pool : total = 8 idle = 2 active = undefined
Nb of clients in pool : total = 8 idle = 2 active = undefined
Nb of clients in pool : total = 8 idle = 3 active = undefined
Nb of clients in pool : total = 8 idle = 3 active = undefined
```

Since `activeCount` is simply (per docs) `pool.totalCount - pool.idleCount` perhaps `activeCount` is not necessary and it's just a documentation issue ?

versions: 
```
node 8.2.1
pg@7.1.0
```

**Comment by brianc** [comment]
Oh yeah you're right that's just bad documentation. I meant to document `waitingCount` which can be helpful: it's the number of requests waiting for a client, but all clients are checked out.  Will update docs right away, thanks!

**Comment by brianc** [comment]
Fixed! https://node-postgres.com/api/pool#-code-pool-waitingcount-int-code-

**Comment by abenhamdine** [comment]
Ah thx !

**Comment by brianc** [comment]
Absolutely! Still on for un verre de vin a Paris en septembre?

**Comment by abenhamdine** [comment]
yes definitely ! I see you have read "French language: the good parts" 😄

**Comment by brianc** [comment]
:dancer:
