### ISSUE TITLE
404 from Express Project Structure Link

### ISSUE THREAD

**Issue by andymans** [brianc/node-postgres#1403]
Hi,
On your external site (https://node-postgres.com)
From the sidebar Item "Express + ...."
This url (shown in the content) goes nowhere
https://node-postgres.com/examples/project-structure

**Comment by brianc** [comment]
Thanks @andymans! Fixed!! :clap: :pray: 

If you or your company benefit from node-postgres and have the means, please consider supporting my work on [Patreon](https://www.patreon.com/node_postgres).
