### ISSUE TITLE
Docs: error in the async/await Pooling example?

### ISSUE THREAD

**Issue by mariuslundgard** [brianc/node-postgres#1410]
I had issues with running out of connections when starting out from the async/await example in the docs.

```js
// async/await - check out a client
(async () => {
  const client = await pool.connect()
  try {
    const res = await pool.query('SELECT * FROM users WHERE id = $1', [1])
    console.log(res.rows[0])
  } finally {
    client.release()
  }
})().catch(e => console.log(e.stack))
```

Should `pool.query` actually be `client.query` here?

**Comment by charmander** [comment]
It should be `client.query`, yes, but that shouldn’t make you run out of connections; it’ll just acquire two clients instead of one and release them both as usual.

Which version of pg-pool do you have installed? #1404 might be coming into effect; try 2.0.3.

**Comment by brianc** [comment]
Thanks for the report @mariuslundgard - I fixed the docs to be more consistent.  Like @charmander said - if you run out of connections that might be a bug so if you're on the most recent version & you see that please don't hesitate to open up another issue. 🙏
