### ISSUE TITLE
inserting a point datatype trying to evaluate as a string

### ISSUE THREAD

**Issue by PaulCannell** [brianc/node-postgres#1411]
Im trying to generate and insert and update statement using param queries
ex
rawSql = "insert into mytable (id, location) values ($1, $2);"
arrParams = ["12", "point(31.865668, -28.737904)"]
conn.query(rawSql, arrParams, function(err, result) ....

it yields ERROR: invalid input syntax for type point: as the error and quite correctly so as the generated SQL is insert into mytable (id, location) values ("12", "point(31.865668, -28.737904)");
as opposed to insert into mytable (id, location) values ("12", point(31.865668, -28.737904));

Am I being thick or is this a bug? or is there a way todo this that I dont know about. Did some googling but didnt get much luck. We DONT have postgis installed on the instance which is why I havnt looked into that package.

- Paul C

**Comment by sehrope** [comment]
The format is outlined in the PostgreSQL docs: https://www.postgresql.org/docs/current/static/datatype-geometric.html#AEN6990

You need to remove the "point" prefix from the parameter value: `(31.865668, -28.737904)`

The parentheses are optional so can also be used as: `31.865668, -28.737904`

Depending on the SQL you may also need to add a cast to the usage of the parameter. Ex: `SELECT $1::point`. In this case you wouldn't have to as as the server would be able to determine that it needs to convert your untyped literal parameter to a point to insert it into that column.

**Comment by PaulCannell** [comment]
Thank you. I like it when my stupidity is the problem
