### ISSUE TITLE
Docs: wrong version in 2017-08-12 announcement

### ISSUE THREAD

**Issue by peggyl** [brianc/node-postgres#1412]
Doesn't look the docs are on a branch in this repo or another by Brian, but I saw an incorrect version in this announcement - https://node-postgres.com/announcements#2017-08-12-code-execution-vulnerability

Instead of `7.0.2`, the fix for the minor version is on `7.0.3`. 

Thanks for the fix!

**Comment by brianc** [comment]
Thanks for the reports! Still working on cleaning up the docs repo, so it's
private, but I'll roll both of these fixes out tonight!! :heart:

**Comment by brianc** [comment]
By both I mean this and #1411 - that's what I get for responding to an issue via email. 🙃

**Comment by brianc** [comment]
Thanks again @peggyl - fixed this now!

**Comment by peggyl** [comment]
Hey @brianc, I think you meant `7.0.3` and `7.1.2` (the website now says 7.0.2. and 7.1.3). 

Thanks! 😄

**Comment by brianc** [comment]
gah sorry about that! :man_facepalming:

**Comment by brianc** [comment]
Fixed it...hopefully for real this time!
