### ISSUE TITLE
pool.on('error', ...) doesn't catch timeout to database

### ISSUE THREAD

**Issue by iyel** [brianc/node-postgres#1416]
"pg": "^7.1.0"
database: RedShift

This is what I catch using try catch on running ```async pool.query()```
```sh
Error running query.  { Error: connect ETIMEDOUT 10.68.64.175:5439
  at Object.exports._errnoException (util.js:1018:11)
  at exports._exceptionWithHostPort (util.js:1041:20)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
code: 'ETIMEDOUT',
errno: 'ETIMEDOUT',
syscall: 'connect',
address: '10.68.64.175',
port: 5439 }
```

This code doesn't run
```js
pool.on('error', (err) => {
  /* eslint-disable no-console */
  console.error('idle client error', err.message, err.stack);
});
```

**Comment by brianc** [comment]
pool only emits errors on _idle_ clients: https://node-postgres.com/api/pool#-code-pool-on-39-error-39-err-error-client-client-gt-void-gt-void-code-

In your case the query call is timing out so you're supposed to handle that error in the query callback or `catch` block if youre using async/await.

If you or your company benefit from node-postgres and have the means, please consider supporting my work on [Patreon](https://www.patreon.com/node_postgres).
