### ISSUE TITLE
`copyFrom` not working as documented

### ISSUE THREAD

**Issue by bobvanderlinden** [brianc/node-postgres#1420]
The readme indicates that this library supports `COPY FROM`. The documentation refers me to `node-pg-copy-streams`. There it is stated that I should use the library as follows:

```js
var stream = client.query(copyTo('COPY my_table TO STDOUT'));
```
This results in the following error:
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: dest.on is not a function
```

Since `pg-copy-streams` doesn't seem to be updated recently, I gathered it might be incompatible with recent changes in `node-postgres`. However the note in the readme that this library supports `COPY FROM` threw me off.

What is the right way to do `COPY FROM`?

**Comment by charmander** [comment]
I can’t reproduce this. Can you include a complete script and your version of pg, please?

**Comment by bobvanderlinden** [comment]
I'm sorry for the bad reporting on my part. When starting a fresh project and creating a minimal example it works as expected. It must be something else in my existing project that conflicts with the call.

Just for anyone else running into the issue somehow. This is what I used in my fresh example project:

```js
const { Client } = require('pg');
const { from: copyFrom, to: copyTo } = require('pg-copy-streams');

function readData(client) {
  return new Promise((resolve, reject) => {
    const stream = client.query(copyTo('copy my_table to stdout'))
    stream.on('data', function(data) {
      console.log(data.toString());
    })
    stream.on('error', function(err) {
      reject(err);
    })
    stream.on('end', function() {
      resolve();
    })
  })
}

function writeData(client) {
  return new Promise((resolve, reject) => {
    const stream = client.query(copyFrom('copy my_table from stdin'))
    stream.on('end', function() {
      resolve();
    })
    stream.on('error', function(err) {
      reject(err);
    })
    stream.write('2\ta\n')
    stream.write('3\tb\n')
    stream.write('4\tc\n')
    stream.end()
  })
}

async function run() {
  const client = new Client();
  await client.connect();
  await client.query('delete from my_table')
  await writeData(client);
  await readData(client);
}

run();
```

Using:

* Node 8.4.0
* node-postgres 7.1.2
* node-pg-copy-streams 1.2.0
