### ISSUE TITLE
Parse bits to booleans

### ISSUE THREAD

**Issue by igabesz** [brianc/node-postgres#1422]
Querying `bit` type returns `"0"` instead of `false` or `0`. I don't see any reasons to have string results instead of booleans. I have read these but I don't think these problems are present here: 
https://github.com/brianc/node-postgres/issues/339
https://github.com/brianc/node-postgres/issues/378

Can this be fixed?

**Comment by charmander** [comment]
`bit` is equivalent to `bit(1)`, and all `bit(n)`s are strings. If you want a boolean, use a boolean (including the cast `1::bit::boolean`).
