### ISSUE TITLE
Please provide a Changelog

### ISSUE THREAD

**Issue by dunkelstern** [brianc/node-postgres#1433]
I am currently updating some projects that have used prior versions of this and i can't seem to find a Changelog. The major version changed so I suspect breakage. The only thing I can currently do is look at all commits or just update and hope for the best.

**Comment by sehrope** [comment]
There already is a changelog that gets regular updates: https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md

**Comment by abenhamdine** [comment]
> The major version changed so I suspect breakage

For sure because this module follows semver.
You should also see https://node-postgres.com/guides/upgrading

**Comment by brianc** [comment]
what @sehrope and @abenhamdine said is spot on.  Please let me know if you have any other specific questions around upgrading!
