### ISSUE TITLE
Problem with usage pg

### ISSUE THREAD

**Issue by BratSinot** [brianc/node-postgres#1440]
I install 'pg', by "npm install pg". After i got error:
> Failed
>
 >to compile.
>
>./node_modules/pg/lib/connection-parameters.js
>Module not found: Can't resolve 'dns' in '/home/hacker/PRJ/unidb/node_modules/pg/lib'

After that, i install 'dns' by "npm install dns". And got an error:
> Failed to compile.
>
>./node_modules/pg/lib/native/client.js
>Module not found: Can't resolve 'pg-native' in '/home/hacker/PRJ/unidb/node_modules/pg/lib/native'

After that, i install 'pg-native' by "npm install pg-native". And got an error:
>Compiled with warnings.
>
>./src/index.js
>  Line 5:   'Client' is assigned a value but never used  no-unused-vars
>  Line 35:  Useless constructor                          no-useless-constructor
>
>./node_modules/defaultable/defaultable.js
>49:13-31 Critical dependency: the request of a dependency is an expression
>
>./node_modules/bindings/bindings.js
>76:22-40 Critical dependency: the request of a dependency is an expression
>
>./node_modules/bindings/bindings.js
>76:43-53 Critical dependency: the request of a dependency is an expression
>
>Search for the keywords to learn more about each warning.
>To ignore, add // eslint-disable-next-line to the line before.

What wrong with NodeJS? Why so many problems? What i done wrong?
P.S. NodeJS 6.11.2.

**Comment by abenhamdine** [comment]
> What i done wrong?

I'd say nothing, usually `npm install pg` is all you have to do.
I suggest you either to delete your `node_modules` folder and make a fresh npm install, or to start a brand new repo.

You could also try to install with `yarn` rather than `npm`, it sometimes fix things.

**Comment by brianc** [comment]
Yeah not being able to find `dns` is weird - that's a node core dependency. You might also want to try to re-install node itself.

**Comment by charmander** [comment]
This looks like client-side-targeted webpack? You can’t use pg in the browser. If this wasn’t an attempt to do that, webpack is probably misconfigured.

**Comment by wanderrful** [comment]
@charmander Are you saying that it's not possible to use pg in the usual way to connect to a database when you are running the app on your local machine?  Because this dns thing prevents it from working? I ask because I'm running into this problem implementing a connection to a Heroku Postgres database for an app I'm working on and found this thread while debugging.

**Comment by charmander** [comment]
@wanderrful No, this issue was about using webpack targeting browser JavaScript. pg runs on Node, not in the browser.

**Comment by marcoippolito** [comment]
I'm having the same problem: 

    ./node_modules/pg/lib/connection-parameters.js
    Module not found: Error: Can't resolve 'dns' in '/home/marco/webMatters/vueMatters/axios--04-    
    finished/node_modules/pg/lib'

    (base) marco@pc01:~/webMatters/vueMatters/axios--04-finished$ vue info

    Environment Info:

      System:
        OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
        Yarn: Not Found
        npm: 6.14.3 - ~/.nvm/versions/node/v12.15.0/bin/npm
      Browsers:
        Chrome: 80.0.3987.163
        Firefox: 74.0
      npmPackages:
        vue: ^2.6.11 => 2.6.11 
        vue-hot-reload-api:  2.3.4 
        vue-loader: ^14.2.4 => 14.2.4 
        vue-router: ^3.0.1 => 3.0.1 
        vue-style-loader:  4.1.2 
        vue-template-compiler: ^2.6.11 => 2.6.11 
        vue-template-es2015-compiler:  1.9.1 
        vuex: ^3.0.0 => 3.0.0 
      npmGlobalPackages:
        @vue/cli: 4.2.3


I then uninstalled pg via npm:

    (base) marco@pc01:~/webMatters/vueMatters/axios--04-finished$ npm uninstall pg
    npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must 
    install peer dependencies yourself.
    npm WARN babel-loader@7.1.2 requires a peer of webpack@2 || 3 but none is installed. You 
    must install peer dependencies yourself.
    npm WARN file-loader@1.1.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. 
    You must install peer dependencies yourself.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12    
    (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 
    fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

    added 2 packages from 1 contributor, removed 17 packages, updated 1 package and audited 
    11065 packages in 3.199s

    23 packages are looking for funding
      run `npm fund` for details

    found 7 low severity vulnerabilities
      run `npm audit fix` to fix them, or `npm audit` for details

I installed yarn

    (base) marco@pc01:~/webMatters/vueMatters/axios--04-finished$ npm install yarn --global
    /home/marco/.nvm/versions/node/v12.15.0/bin/yarn -> /home/marco/.nvm/versions/node/v12.15.0/ 
    lib/node_modules/yarn/bin/yarn.js
    /home/marco/.nvm/versions/node/v12.15.0/bin/yarnpkg -> /home/marco/.nvm/versions  
    /node/v12.15.0/lib/node_modules/yarn/bin/yarn.js
    + yarn@1.22.4
    added 1 package in 0.238s

and installed pg through yarn:

    (base) marco@pc01:~/webMatters/vueMatters/axios--04-finished$ yarn add pg
    yarn add v1.22.4
    info No lockfile found.
    $ npx npm-force-resolutions
    npx: installed 5 in 0.765s
    warning package-lock.json found. Your project contains lock files generated by tools other than 
    Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies 
    caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
    [1/4] Resolving packages...
    Couldn't find any versions for "mkdir" that matches "0.5.3"
    ? Please choose a version of "mkdir" from this list: 0.0.2
    warning Resolution field "minimist@1.2.3" is incompatible with requested version 
    "minimist@^1.2.5"
    warning babel-core > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and 
    not recommended for usage due to the number of issues. Please, upgrade your dependencies to 
    the actual version of core-js@3.
    warning babel-core > babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and 
    not recommended for usage due to the number of issues. Please, upgrade your dependencies to 
    the actual version of core-js@3.
    warning webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see 
    https://github.com/lydell/urix#deprecated
    warning webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: 
    https://github.com/lydell/resolve-url#deprecated
    [2/4] Fetching packages...
    info fsevents@1.2.12: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from 
    installation.
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    success Saved lockfile.
    success Saved 469 new dependencies.


But again...:

    Failed to compile.

    ./node_modules/pg/lib/connection-parameters.js
    Module not found: Error: Can't resolve 'dns' in '/home/marco/webMatters/vueMatters/axios--04-
    finished/node_modules/pg/lib'

How to solve the problem?

**Comment by Steven-Somer** [comment]
I had the same issue when I was not paying attention and installed `pg` in the react native app instead of the nodejs backend.

**Comment by xargr** [comment]
this errors seems to comes from build in browser environment where all server lbs don't exist
