### ISSUE TITLE
Missing "connectionString" in ConnectionConfig interface

### ISSUE THREAD

**Issue by kazagkazag** [brianc/node-postgres#1447]
Hi, `ConnectionConfig` interface has no `connectionString` member, so I can't provide `connectionString`. According to the doc, this should be possible:

https://node-postgres.com/features/connecting:

`You can initialize both a pool and a client with a connection string URI as well.`

**Comment by abenhamdine** [comment]
> Hi, ConnectionConfig interface has no connectionString member, so I can't provide connectionString. 

Yes it has : 
https://github.com/brianc/node-postgres/blob/f66379f5fe01d8e9c491b0b2d1f352334783858f/lib/connection-parameters.js#L43-L51

**Comment by kazagkazag** [comment]
Well, maybe I chose wrong project for that issue. I mean interface defined in @types/pg for typescript... So I think that issue should be closed?

**Comment by abenhamdine** [comment]
Yes, tsypescript definitions aren't in this repo but in DefinitelyTyped project. 
And they are indeed not to date, there's a pending PR to update them accordingly to pg 7.x api.

see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18558

**Comment by kazagkazag** [comment]
Oh, ok, sorry, thx for information.

**Comment by abenhamdine** [comment]
You welcome. Could you please close this issue ?
