### ISSUE TITLE
Bigint id returns as number instead of string

### ISSUE THREAD

**Issue by pleerock** [brianc/node-postgres#1450]
When I execute following query:

```sql
INSERT INTO "message" DEFAULT VALUES  RETURNING "id"
``` 
returns:

```js
[ anonymous { id: 1 } ]
```

when "id" is `bigint`, shouldn't it return a stringified id: `[ anonymous { id: "1" } ]` ?

**Comment by abenhamdine** [comment]
no, because of number javascript limitations
see the readme in https://github.com/brianc/node-pg-types
see also for numeric https://github.com/brianc/node-postgres/issues/1300
Be caution  : this limitation applies also to count() since it returns int8 in pg,

**Comment by abenhamdine** [comment]
Oups, looks like I misread your question, which is actually the opposite, sorry 😲 
So yes, it should be stringified, except if it's actually an int4 (integer type in sql), or you have overriden the types parser.

**Comment by vitaly-t** [comment]
Every `bigint` and `bigserial` must be returned as a string, unless you override the type and make it return an integer.

**Comment by charmander** [comment]
I’m unable to reproduce this. Can you provide a self-contained script that demonstrates the problem?

**Comment by brianc** [comment]
closing as we haven't heard anything in a while

**Comment by castarco** [comment]
I'm actually suffering from this same problem, but with `pg` 8.7.1 , in any case, there are many wrapping layers on top of it, such as `pg-promise`, and `massivejs` on top of all of that.

I'm trying to pin down where the conversion is happening (because I assume that it's correctly converted to string at some point), but it's not trivial because of how many layers I have, async breaking stacktraces, and the extreme dynamic nature of JS (so the IDE can't help me at all to identify which objects correspond to which code).

**Comment by castarco** [comment]
More context, I managed to find the point where some values are changed:

```
  | <><><><><><><><><><><><><><><><><><><>
  | In handleDataRow (pg / query.js):
  |
  | msg.fields:
  | [
  |   '1732840692841839592',
  |   '3',
  |   'DESK-180-081502',
  |   '3793341115721622470',
  |   '{6494188851820580676}'
  | ]
  |
  | this._result.parseRow(msg.fields)
  | {
  |   id: 1732840692841839600, <-- changed from string to number :(
  |   clientCode: '3',
  |   name: 'DESK-180-081502',
  |   divisionId: 3793341115721622500, <-- changed from string to number :(
  |   hierarchyLevelIds: [ '6494188851820580676' ]
  | }
  | <><><><><><><><><><><><><><><><><><><>
```

**Comment by castarco** [comment]
Ok, final comment, in case some other people find themselves in the same position. As expected, the bug was not in `node-postgres`' packages. I found this code on our side, which was the culprit:

```typescript
  const db = await massive(...) // We're using MassiveJS, but the problem is not related to that

  const types = db.pgp.pg.types // this comes from `pg-types` package
  types.setTypeParser(types.builtins.INT8, parseFloat) // <-- the culprit
```
