### ISSUE TITLE
Fails to error on queries inside a transaction after a lost connection

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1454]
When we execute a lengthy operation inside a transaction, and the connection is suddenly lost during that time, then any query we execute on the `client` after that become stuck, i.e. they report nether success no error:

```js
'use strict';

const Pool = require('pg-pool');

const cn = {
    database: 'newone',
    port: 5433,
    user: 'postgres'
};

const p = new Pool(cn);

p.on('error', error => {
    // do nothing
});

p.connect((err, client, release) => {
    if (err) {
        console.log('Failed to connect:', err);
        return;
    }
    const test = async function () {
        try {
            await client.query('BEGIN');
            await client.query('SELECT pg_sleep(10)'); // connection breaks during this one
            await client.query('COMMIT');
            console.log('success!');
        } catch (e) {
            console.log('about to rollback...'); // this is reported
            await client.query('ROLLBACK'); // this one is stuck, never reporting an error, if the error was due to lost connection
            console.log('rollback finished'); // this is never reported, if we are here because of lost connection
        } finally {
            release();
            p.end();
        }
    };

    test();
});
```

I've tried both `pg-pool` directly and via `node-postgres`, versions 6.x and 7.x - all the same.

**Expected Behavior**

Executing any query against `client` at that point should immediately report an error that informs us of the lost connectivity.

**Comment by charmander** [comment]
Related (and closed for some reason?): #632, #718

**Comment by vitaly-t** [comment]
One of those old bugs was kind-of more specific, even though the issue was a broad one, and the other one had too much code, not easy to see what the issue is.

My example is much easier to read and debug, and it is 100% reproducible, and quite generic, i.e. it is not that the `ROLLBACK` fails at that point, it is any query.

**Comment by vitaly-t** [comment]
@charmander seems like #1322 is yet another dupe. This is one devious bug! 😈

**Comment by charmander** [comment]
*That’s* the one I was looking for! Thanks. Good thing it’s open.

**Comment by brianc** [comment]
Nice! Thanks for reporting this - I'll try to look at this this weekend.

**Comment by vitaly-t** [comment]
@brianc any luck? Do you need help with it? 😉

**Comment by vitaly-t** [comment]
Two week-ends out, still nothing?

**Comment by brianc** [comment]
Sorry for the delay: I broke a bone & haven't been @ the computer much, and when I am at the computer I have to work so I can pay my bills.  One thing that would help is adding to your example above some code to manually kill the connection.  Right now to simulate a connection drop I have to kill postgres, which doesn't work if I want to run the test in CI or automatically.  Would it be possible to create a fully self-contained script that demonstrates the error without requiring manual intervention to kill the connection?  That would be super helpful.

**Comment by vitaly-t** [comment]
> One thing that would help is adding to your example above some code to manually kill the connection

To temporarily kill all connections to your test database, execute the following SQL in pgAdmin:

```sql
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='my-database-name';
```

You must provide the correct database name in the query, and make sure to execute it from a connection to a different database, or else you will be killing the current pgAdmin connection, which often causes it to crash the UI.

**Comment by brianc** [comment]
gotcha! Thanks! It's a slow road but I'm gettin' better 😄

**Comment by vitaly-t** [comment]
@brianc Are you still on sick? It's been almost 2 month since the last commit.

**Comment by vitaly-t** [comment]
**UPDATE**

This issue appears to be even more severe, as it affects solutions running on a thin WiFi connection, i.e. the issue keeps happening even with small transactions that execute longer due to the slow network.

@charmander @brianc Guys, any chance to see a solution to this?

**Comment by vitaly-t** [comment]
While there is no fix for this, for now I am using the following work-around:

```js
try {
         await client.query('BEGIN');
         await client.query('SELECT pg_sleep(10)'); // connection breaks during this one
         await client.query('COMMIT');
         console.log('success!');
     } catch (e) {
         if(e.client && e.client.startsWith('57')) {
             // ERROR: Operator Intervention, cannot execute ROLLBACK
             // ERROR CODES: https://www.postgresql.org/docs/9.6/static/errcodes-appendix.html
         } else {
              await client.query('ROLLBACK');
           }
    }
```

**Comment by charmander** [comment]
I can’t reproduce this with your test script; `await client.query('ROLLBACK')` throws as expected. (Were you testing on a version of Node that shows unhandled promise rejection warnings? There’s no `.catch()` on `test()`.)

**Comment by charmander** [comment]
Nevermind, I was testing on the wrong branch – #1503 fixes this as well.

**Comment by vitaly-t** [comment]
Confirmed. This now works.
