### ISSUE TITLE
docs typo in transactions

### ISSUE THREAD

**Issue by dwelle** [brianc/node-postgres#1456]
in first exapmple, it should be `require('pg')`:

![image](https://user-images.githubusercontent.com/5153846/30556302-a0981b6c-9caa-11e7-9c6d-877a81b3ea2b.png)

**Comment by abenhamdine** [comment]
Where do you see that ?
Because it's supposed to be fixed (see https://github.com/brianc/node-postgres/issues/1437) and I don't see it in node-postgres.com

**Comment by dwelle** [comment]
My mistake for not linking to it.. I indeed still see it on https://node-postgres.com/features/transactions even when I disable cache in chrom devTools.
