### ISSUE TITLE
Question: Should pooled backends be showing as <IDLE> after returning?

### ISSUE THREAD

**Issue by codingthat** [brianc/node-postgres#1459]
Legacy project here with node-postgres 5.10.  I've so far yet to see any backend with `<IDLE>` instead of a query for the Current Query column in pgAdminIII's "Statistics" tab for our server.  Is this normal, or is our app doing connection pooling incorrectly?

(It seems to call done() properly after a query is done returning data, per the docs at the time, for what it's worth.)

**Comment by charmander** [comment]
If you write a small script that connects a single client, runs a query, and doesn’t `end()` the client, does it show as idle?

**Comment by brianc** [comment]
yeah the client will be idle unless it's in the middle of running a query when you refresh the statistics.  I'm not sure exactly what query powers that tab, but I know the tests rely on this column being set when queries are run: https://github.com/brianc/node-postgres/blob/master/test/integration/client/query-error-handling-prepared-statement-tests.js#L42
