### ISSUE TITLE
Maximum number of placeholders in query ?

### ISSUE THREAD

**Issue by Musinux** [brianc/node-postgres#1463]
Hello,

I'm currently using pg v7.3.0 and node v7.3.0 and I have some applications that need to insert a relatively big set of data at once, in postgres.

This being said, I made some performance checks to choose whether I should do a succession of little inserts, row by row, or a big, unique insert with VALUES (1, 2, 3), (4, 5, 6) ...

When I did this, the latter clearly showed better results, but I encountered an error that I don't understand. This is the minimum working example of the behavior: in substance, inserting 6554 rows of 10 columns into a table named "crash" consisting of 10 text columns from Col1 to Col10

```javascript
const { Pool } = require('pg')

const pool = new Pool({
  database: 'postgres',
  user: 'mydatabase',
  password: 'mysecretpassword',
  host: 'localhost',
  port: 5432
})

let rows = 6554
let cols = 10
let data = []
let col = []

for (let i = 0; i < cols; i++) col.push('' + i)
for (let i = 0; i < rows; i++) data.push(col)

const columnsDefinition = 'Col1 text, Col2 text, Col3 text, Col4 text, Col5 text, ' + 
             'Col6 text, Col7 text, Col8 text, Col9 text, Col10 text'

pool.query(`DROP TABLE IF EXISTS crash`)
.catch(console.error) // catch the "table didn't exist" error
.then(() => pool.query(`CREATE TABLE crash (${columnsDefinition})`))
.then(() => {
  // generate the VALUES ($1, ... $n), ($n+1, ... $m) ... string
  let total = rows * cols
  let placeholders = '('
  for (let i = 0; i < total; i++) {
    if (i % cols === 0 && i !== 0) {
      placeholders += '), ('
    } 
    
    placeholders += '$' + (i + 1)
    
    if (i % cols !== cols - 1) {
      placeholders += ', '
    } 
  } 
  placeholders += ')'
  
  // transform the data set into a single dimension array
  let values = data.reduce((a, b) => a.concat(b))
  
  // this is where it fails
  return pool.query({ text: `INSERT INTO crash VALUES ${placeholders}`, values })
})
.catch(err => console.error('err', err))
```

Under the 6554 rows limit, the request works. with this and beyond, this is the error that I ran into:
```bash
$ node minimal_error.js
err { error: bind message supplies 4 parameters, but prepared statement "" requires 65540
    at Connection.parseE (/home/louis/test/bench_postgres/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/home/louis/test/bench_postgres/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/home/louis/test/bench_postgres/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 141,
  severity: 'ERROR',
  code: '08P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1536',
  routine: 'exec_bind_message' }
```

Do you have any clue about this crash ? I know that I can avoid this by splitting my request into multiple parts but I'd like to understand  whether it's a node proglem (string size), a pg problem (query evaluation, number of substitution params), of a postgres problem.

Louis

**Comment by abenhamdine** [comment]
You can't pass more than 65535 parameters in a parameterized query with postgres 9.x, it's a postgres limit.

**Comment by Musinux** [comment]
Okay, thank you !

**Comment by charmander** [comment]
Use arrays: https://github.com/brianc/node-postgres/issues/1116#issuecomment-283854402, https://github.com/brianc/node-postgres/issues/957#issuecomment-295583050,

**Comment by Musinux** [comment]
Thank you very much @charmander !

I saw before these suggestions of using arrays but I didn't understand them. Pretty clever.
I seeked for some potential limits on the number of rows you can add at once with this method, but I couldn't find any. Do you have some clues about this ?
