### ISSUE TITLE
Suppress DeprecationWarning

### ISSUE THREAD

**Issue by Amposter** [brianc/node-postgres#1466]
Error: 

`DeprecationWarning: Using the automatically created return value from client.query as an event   emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
`

This causes issues in our build pipeline because it gets picked up by `stderr`. Is there any way to suppress this warning?

**Comment by super-cache-money** [comment]
+1
If there was an environment variable flag we could set, that'd be great...

**Comment by brianc** [comment]
Yeah I'm using [util.deprecate](https://nodejs.org/api/util.html#util_util_deprecate_function_string) to emit the warning - it provides a few different ways to disable those warnings.  I don't think it supports environment variables alone, but should be easy to set `process.noDeprecation` based on your own env var in CI.
