### ISSUE TITLE
Documentation site sidebar is cut-off

### ISSUE THREAD

**Issue by Varriount** [brianc/node-postgres#1467]
When viewing the current website documentation through Chrome (version 61.0.3163.100) the sidebar listing sections of the documentation is cut-off. 
![image](https://user-images.githubusercontent.com/524596/31256265-6b93b180-a9ff-11e7-9fd8-abbeeac67eee.png)

**Comment by tim-phillips** [comment]
This can be closed since the new documentation has launched.

https://node-postgres.com/
