### ISSUE TITLE
Migrations functionality, recommended libs?

### ISSUE THREAD

**Issue by dbkaplun** [brianc/node-postgres#1471]
Hi all,

I am wondering, is there built-in migrations functionality in `node-postgres`? The [Extras](https://github.com/brianc/node-postgres/wiki/Extras) page in the wiki doesn't seem to list any migration tools either.

Thanks for reading!

**Comment by charmander** [comment]
There isn’t anything built into pg, no.

**Comment by vitaly-t** [comment]
@dbkaplun [node-db-migrate](https://github.com/db-migrate/node-db-migrate).
