### ISSUE TITLE
Check if pool is active or not

### ISSUE THREAD

**Issue by mayankagr009** [brianc/node-postgres#1477]
QUERY 1: In the below code, before calling any function of Pool, how do I make sure that pool is active ?? Is there any in built function for that?

    const { Pool } = require('pg');
    var pool = new Pool(); //global variable, used by multiple modules

    function f1(){
    /*
    Check here if pool is active or not. If active, then execute following code otherwise re-initiate pool
    */
     pool.connect(...)
      }

If I don't check it, then following error may occur if pool is not in active state (may have been ended by some other module).

     Error: Cannot use a pool after calling end on the pool

Query 2: What happens if I don't end the pool i.e. pool remains active forever?

**Comment by charmander** [comment]
Don’t call `.end()` on the pool if you want to continue using it. Call it once when you want to shut down your entire app. If you have some unusual situation that requires this, set it to `null` after calling `pool.end()` to indicate that it needs to be recreated.

If you don’t end the pool and there’s no idle timeout, it could continue to hold connections open indefinitely, yes.

**Comment by mayankagr009** [comment]
This is what currently I am doing, but I guess there should be a proper way of checking this.

**Comment by mayankagr009** [comment]
Although there is no requirement to end the pool, what if error occurs while ending pool? According to you, what should be done... Initiate a new pool or use the current one? At this point, it would be unclear whether the pool has properly ended or not.

**Comment by charmander** [comment]
Why are you creating multiple pools?

**Comment by mayankagr009** [comment]
I am only using a single pool. Once the pool is initiated, only that pool is used. 
But I am just handling it in code. If a request is received to create a new pool, following steps are followed:
1. If pool already exists, then that pool is ended.
2. New pool is created.

Actually, the main purpose of asking this question was to handle error scenarios in my application, so that the application does not break at any point. If current pool stops working (not a correct way of saying, I mean due to unknown reasons pool gets finished/ended), then application should  automatically create a new pool. That's why I wanted to know how to check the validity of pool.

**Comment by charmander** [comment]
The pool can’t stop working or be ended without you calling `.end()`. Clients in the pool can produce errors, which you handle by attaching an `error` listener to the pool; they won’t break the pool itself.

**Comment by mayankagr009** [comment]
If that's the case , then I guess I need not to worry about handling pool related errors. :)

**Comment by basperheim** [comment]
Just evaluate the Pool instance's 'ended' attribute like in the following code:
```js
if (client.ended !== true) {
  // do stuff here
}
```
