### ISSUE TITLE
docs: missing semicolons

### ISSUE THREAD

**Issue by mattikl** [brianc/node-postgres#1480]
I noticed some missing semicolons in https://node-postgres.com/features/pooling:

```js
(async () => {
```
These lines need a semicolon before them, otherwise they get parsed as a function invocation on the previous line. This causes errors that might be very confusing for someone trying to learn the topics.

Btw, great job on the docs!

**Comment by langpavel** [comment]
automatic semicolon insertion is heavy… oh… don't worry, this can be a mistake of human who write the doc. Or not… be clever and don't copy what you see, rethink every word and hit your pleasure :smiling_imp:
