### ISSUE TITLE
[DISCUSSION] Add section to README: "Who uses node-postgres"

### ISSUE THREAD

**Issue by jpls93** [brianc/node-postgres#1481]
I think it would be nice to have a section that displays open-source projects which show how they use `pg` in their code.

Context:
I need to learn PostgreSQL as fast as possible. I'm currently learning by reading the docs and through trial and error. I'd be grateful for links from anyone who has an open-source CRUD app using `pg` as part of their stack.

**Comment by cymen** [comment]
It would be a pretty big list -- npmjs.com has [1,909 dependents at the moment](https://www.npmjs.com/package/pghttps://www.npmjs.com/package/pg) (see Dependents on lower right).

**Comment by langpavel** [comment]
I'm using it and if there will be better alternative then I switch :smiling_imp: But there is no better alternative, so I will stay :rofl:

**Comment by brianc** [comment]
Yah I'd rather not at this point add a list as it'd be pretty long and hard to cultivate.   I think the download count from npmjs should suffice.
