### ISSUE TITLE
Setting PGOPTIONS when connecting (environment variable / connection parameter)

### ISSUE THREAD

**Issue by cjnqt** [brianc/node-postgres#1482]
The documentation says 
`node-postgres uses the same environment variables as libpq to connect to a PostgreSQL server` 

Libpq supports setting PGOPTIONS on the connection, but it seems that node-postgres doesn't? Is there any way to specify PGOPTIONS (these: https://www.postgresql.org/docs/9.1/static/libpq-envars.html)

**Comment by langpavel** [comment]
`PGOPTIONS` is used only by `psql` command, not by `libpq` itself, so documentation here is correct.
Documentation at postgres pages lies :sweat_smile:
*I searched source codes of postgres*
