### ISSUE TITLE
net.Stream is not a constructor

### ISSUE THREAD

**Issue by Dhaval8087** [brianc/node-postgres#1486]
Hello ,

I have used pg-pool as mentioned below and my app is create-react-app

```import Pool from 'pg-pool';

const connectionConfig = { 
    user: 'postgres',
    password: 'sa123*',
    host: 'localhost',
    port: '5432',
    database: 'telestudent',
    ssl: true
  }
  const pool = new Pool(connectionConfig);
  pool.connect().then(client => {
    client.query('select $1::text as name', ['pg-pool']).then(res => {
      client.release()
      console.log('hello from', res.rows[0].name)
    })
    .catch(e => {
      client.release()
      console.error('query error', e.message, e.stack)
    })
  })
```
I got the error from connection.js so I have debug it and I found that stream is pass undefined in config and it will try to instantiate and fire a error error coming from below mentioned line in connection.js
**this.stream = config.stream || new net.Stream()**
please help me I have already spent a lot of time 

Thanks,
Dhaval

**Comment by abenhamdine** [comment]
Please format your code https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by Dhaval8087** [comment]
@abenhamdine :sorry , I have formatted it

**Comment by Dhaval8087** [comment]
@abenhamdine 
Node: 6.11.5
pg:7.3.0
pg-pool:2.0.3
in local I have installed pgAdmin4 and postgreSQL10

**Comment by abenhamdine** [comment]
Very weird, I've never seen this error personnaly.
Is that your whole code or just a part ?

**Comment by Dhaval8087** [comment]
I have used creat react app with electron. But for connectin postgreSql i just write above mentione code in component and try to connect it from my home component but when my application start immediate this error encounter.

**Comment by abenhamdine** [comment]
Your code seems correct, probably something is messing up your stream somewhere in the net chain.

**Comment by Dhaval8087** [comment]
Yes i have debug it and in config object stream is undefined in connection.je constructors

**Comment by Dhaval8087** [comment]
@abenhamdine 
Please find the sample code here [https://www.dropbox.com/s/qk2nspd6hl2xgjq/pgtest.rar?dl=0](url) you just need to execute below mentioned command 
npm install
replace the pg/lib/index.js content with root folder index.txt otherwise it will give you native required error 
npm run dev

**Comment by brianc** [comment]
@Dhaval8087 - are you trying to run node-postgres in the browser? It only works if you run it in a node process on the backend.  Exposes your database in the browser might be an interesting exercise but it's rife with pretty epic security concerns and is well outside the scope or intent of this module.  If you're running in electron you can only use node-postgres in the __non-browser__ process.

**Comment by sanjuP7** [comment]
Hello,
**Code:** 
_const pg = require('pg')
const pool = new pg.Pool({
	user:'postgres',
	host:'localhost',
	password:'sanju@tim123',
	database:'postgres',
	port:5432,
})

pool.connect((err,db,done) => {
	if(err){
		return console.log(err);
	} else {
		db.query('SELECT * from public.laps',(err,table) => {
			if(err){
				return console.log(err);
			} else{
				console.log(table)
			}
		})
	}
})_

**Error:** 
_TypeError: net.Stream is not a constructor
new Connection
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/lib/connection.js:13
  10 | var Connection = function(config) {
  11 |   EventEmitter.call(this);
  12 |   config = config || {};
> 13 |   this.stream = config.stream || new net.Stream();
  14 |   this.lastBuffer = false;
  15 |   this.lastOffset = 0;
  16 |   this.buffer = null;
View compiled
new Client
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/lib/client.js:26
  23 | 
  24 | this._types = new TypeOverrides(c.types);
  25 | 
> 26 | this.connection = c.connection || new Connection({
     | ^  27 |   stream: c.stream,
  28 |   ssl: this.connectionParameters.ssl
  29 | });
View compiled
push../node_modules/pg/node_modules/pg-pool/index.js.module.exports.push../node_modules/pg/node_modules/pg-pool/index.js.Pool._create
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/pg-pool/index.js:87
  84 | 
  85 | Pool.prototype._create = function (cb) {
  86 |   this.log('connecting new client')
> 87 |   var client = new this.Client(this.options)
  88 | 
  89 |   client.on('error', function (e) {
  90 |     this.log('connected client error:', e)
View compiled
Pool._createResource
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:325
  322 | this._count += 1
  323 | this._log('createResource() - creating obj - count=' + this._count + ' min=' + this._factory.min + ' max=' + this._factory.max, 'verbose')
  324 | var self = this
> 325 | this._factory.create(function () {
      | ^  326 |   var err, obj
  327 |   var clientCb = self._waitingClients.dequeue()
  328 |   if (arguments.length > 1) {
View compiled
Pool.dispense [as _dispense]
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:313
  310 |       return clientCb(err, objWithTimeout.obj)
  311 |     }
  312 |     if (this._count < this._factory.max) {
> 313 |       this._createResource()
  314 |     }
  315 |   }
  316 | }
View compiled
Pool.acquire
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:391
  388 |     callback = process.domain.bind(callback)
  389 |   }
  390 |   this._waitingClients.enqueue(callback, priority)
> 391 |   this._dispense()
  392 |   return (this._count < this._factory.max)
  393 | }
  394 | 
View compiled
push../node_modules/pg/node_modules/pg-pool/index.js.module.exports.<anonymous>
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/pg-pool/index.js:111
  108 | Pool.prototype.connect = function (cb) {
  109 |   return this._promiseNoCallback(cb, function (resolve, reject) {
  110 |     this.log('acquire client begin')
> 111 |     this.pool.acquire(function (err, client) {
  112 |       if (err) {
  113 |         this.log('acquire client. error:', err)
  114 |         if (cb) {
View compiled
push../node_modules/pg/node_modules/pg-pool/index.js.module.exports.push../node_modules/pg/node_modules/pg-pool/index.js.Pool._promiseNoCallback
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/pg-pool/index.js:74
  71 | }
  72 | 
  73 | Pool.prototype._promiseNoCallback = function (callback, executor) {
> 74 |   return callback
  75 |     ? executor()
  76 |     : new this.Promise(executor)
  77 | }
View compiled
push../node_modules/pg/node_modules/pg-pool/index.js.module.exports.push../node_modules/pg/node_modules/pg-pool/index.js.Pool.connect
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/pg-pool/index.js:109
  106 | }
  107 | 
  108 | Pool.prototype.connect = function (cb) {
> 109 |   return this._promiseNoCallback(cb, function (resolve, reject) {
  110 |     this.log('acquire client begin')
  111 |     this.pool.acquire(function (err, client) {
  112 |       if (err) {
View compiled
Module../src/components/LeaderBoard.js
C:/Users/Administrator/Desktop/sanju/gp-bike/src/components/LeaderBoard.js:57
  54 | 	port:5432,
  55 | })
  56 | 
> 57 | pool.connect((err,db,done) => {
  58 | 	if(err){
  59 | 		return console.log(err);
  60 | 	} else {_



I am facing Above Issue, which Showing net.Stream is not a constructor.
if Anyone have any idea please help me out
