### ISSUE TITLE
array_agg results come as strings

### ISSUE THREAD

**Issue by Canop** [brianc/node-postgres#1487]
Let's say I have this query:

	select
	tag,
	array_agg((player, (select name from player where player.id=player))) players
	from player_tag
	group by tag;

Then the `players` property of the fetched rows comes as a string like this:
     
       '{"(4,Alice)","(5,Bob)","(3,Carl)"}'

Is there a clean and efficient way to get a proper array of objects (or an array of arrays) ? Or should I just do the aggregation client-side in Javascript?

**Comment by charmander** [comment]
You can use [`json[b]_agg`][1] instead:

```sql
SELECT
    tag,
    jsonb_agg(jsonb_build_object('id', player, 'name', player.name)) AS players
FROM player_tag
    INNER JOIN player ON player = player.id
GROUP BY tag;
```

  [1]: https://www.postgresql.org/docs/current/static/functions-json.html
