### ISSUE TITLE
Support Array Parameters

### ISSUE THREAD

**Issue by pleerock** [brianc/node-postgres#1490]
For example I have following expression:

```sql
SELECT * FROM "users" "user" WHERE "user"."id" IN ($1)
```

And I want to set $1 an array value. Mysql driver supports this feature and its really convenient feature I would really really like to see in pg package as well.

Thank you

**Comment by abenhamdine** [comment]
use ANY :  
```sql
SELECT * FROM table WHERE id = ANY ($1)
`

**Comment by pleerock** [comment]
Im asking this not for my personal usage, Im asking it for [typeorm](https://github.com/typeorm/typeorm). Users often use `IN` and I can't force them to use ANY instead.

**Comment by abenhamdine** [comment]
If you can't use any, you could use template strings : 
```sql
 WHERE "user"."id" IN (${[1, 2, 3].join(', ')})
```

There are probably some modules in the wild to do something like that, with escaping.

**Comment by vitaly-t** [comment]
> There are probably some modules in the wild to do something like that, with escaping.

Inside [pg-promise](https://github.com/vitaly-t/pg-promise), for example, it is done like this:

```js
WHERE "user"."id" IN ($1:csv)
```
i.e. comma-separated values are escaped each according to their JavaScript type.

**Comment by pleerock** [comment]
> If you can't use any, you could use template strings :
> WHERE "user"."id" IN (${[1, 2, 3].join(', ')})
> There are probably some modules in the wild to do something like that, with escaping.

right, Im asking about out-of-the-box solution

**Comment by abenhamdine** [comment]
You can also use pg-format to format & escape sql string before passing it to node-postgres :  

```js
const format = require('pg-format');

const myArray = [ 1, 2, 3 ]

const sql = format('SELECT * FROM t WHERE c1 IN (%L)', myArray)
```

**Comment by pleerock** [comment]
as I already told I need out-of-the-box solution, having to install a separate module for such generic operation is a complexity.

**Comment by charmander** [comment]
> Users often use IN and I can't force them to use ANY instead.

I don’t see why not? `= ANY` is the correct solution here. Parameters are not a driver invention, either, and breaking consistency with PostgreSQL prepared statements to support bad code doesn’t seem useful.

**Comment by devonik** [comment]
The ANY keyword works well here. In plain postgres it would be look like `SELECT * FROM tbl WHERE id = ANY (ARRAY[1, 2]);` see here https://stackoverflow.com/questions/34627026/in-vs-any-operator-in-postgresql
