### ISSUE TITLE
Get query executed for each response object in multi-query mode?

### ISSUE THREAD

**Issue by ashking** [brianc/node-postgres#1491]
Is there a way to get the corresponding SQL query for each of the result sets when multi-query is executed? 

For instance, when executing `select 1; select 2;` should show the corresponding queries in the result set.

**Comment by abenhamdine** [comment]
Since 7.0, result from multi-statement text queries such as SELECT 1; SELECT 2; are returned as an array of results instead of a single result with 1 array containing rows from both queries.

**Comment by brianc** [comment]
thanks @abenhamdine!  Yah - as far as getting the actual query text: postgres doesn't echo that back in the responses so you'll have to keep track of it yourself, @ashking .

**Comment by abenhamdine** [comment]
oups, looks like I misread the issue, I thought the OP was asking for multi-results feature,  thanks for the catch up !
