### ISSUE TITLE
Binary mode doesn't correctly handle large integers

### ISSUE THREAD

**Issue by justinj** [brianc/node-postgres#1492]
Text mode (for lack of any better option) converts integers that can't fit into a JavaScript number into strings, however, this doesn't work with binary mode:

```
client = new Client({
  user: 'justin',
  host: 'localhost',
  port: 5432,
  database: 'justin',
  binary: true
});

client.connect();

client.query({
  text: 'SELECT 99999999999+$1 AS b',
  values: [3]
}, (err, r) => {
  console.log(r.rows[0], err);
  process.exit(0);
});
```

When `binary` is `false`, this prints:
```
anonymous { b: '100000000002' } null
```
when `binary` is `true`, it prints
```
anonymous { b: '\u0000\u0000\u0000\u0017Hv�\u0002' } null
```

**Comment by charmander** [comment]
You would need to set a binary parser for `int8`s, since one isn’t built in:

```js
'use strict';

const pg = require('pg');

const OID_INT8 = 20;

const client = new pg.Client({
  host: '/var/run/postgresql',
});

pg.types.setTypeParser(OID_INT8, 'binary', buffer => {
  let high = buffer.readInt32BE(0);
  let low = buffer.readUInt32BE(4);
  let sign = '';

  if (high < 0) {
    high = ~high + (low === 0);
    low = (~low + 1) >>> 0;
    sign = '-';
  }

  const digits = [];

  do {
    const carry = high % 10;
    high = high / 10 >>> 0;

    const t = 0x100000000 * carry + low;
    digits.push(t % 10);
    low = t / 10 >>> 0;
  } while (low !== 0 || high !== 0);

  return sign + digits.reverse().join('');
});

client.connect(error => {
  if (error) {
    throw error;
  }

  client.query({
    text: 'SELECT 99999999999 + $1 AS b',
    values: [3],
    binary: true,
  }, (error, result) => {
    if (error) {
      throw error;
    }

    console.log(result.rows[0]);
    client.end();
  });
});
```

**Comment by benesch** [comment]
Well gosh, that's surprising! Looks like the driver used to ship with a binary `int8` parser, but it was removed in fb5520bb8 ca. July 2015. The changelog claims:

> Due to the low usage & required compiled dependency this will be pushed into a 3rd party add-on

But it looks like you've got a pretty nifty implementation there with no native dependencies. Any chance we talk you into shipping that in node-pg-types? :)

**Comment by charmander** [comment]
Oh, nice find! I wasn’t aware that was removed. This implementation isn’t as efficient as it could be, though – I’ll put together something better for pg-types.

On the other hand, parsing `int8`s into strings isn’t fantastic in the first place… throwing on non-safe-integers tends to be more useful, and `::text` on the server side works in the rest of the cases.

**Comment by benesch** [comment]
Woohoo, thanks @charmander! Much appreciated.
