### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by eddyhdzg** [brianc/node-postgres#1496]
Can someone pass me a simple script to connect postgres to node.js?

I found that the documentation changed in comparison to previous youtube videos.

I have my tables and my server running, just I'm not able to connect both.

**Comment by abenhamdine** [comment]
https://node-postgres.com/#getting-started is not clear enough ?

**Comment by eddyhdzg** [comment]
No

**Comment by charmander** [comment]
https://node-postgres.com/features/pooling#single-query

**Comment by langpavel** [comment]
@eddyhdzg It should be simple as passing connection string into:
```js
const c = new pg.Connection({connectionString: '...'});
await c.query(...);
```

**Comment by brianc** [comment]
The docs are a work in progress and I intend to improve them over time.  In the mean time unless you can provide more specifics there's nothing else I can do here.
