### ISSUE TITLE
Documentation: environment variable PGHOST!=dns (sth like database.server.com isn't allowed it's only for ip-adresses)

### ISSUE THREAD

**Issue by ffischer1984** [brianc/node-postgres#1497]
Hi,
on your website (https://node-postgres.com/features/connecting) are these parameters:
 PGUSER=dbuser \
  PGHOST=database.server.com \
  PGPASSWORD=secretpassword \
  PGDATABASE=mydb \
  PGPORT=3211 \
  node script.js

In my Opinion PGHOST has a false value cause PGHOST only allows IP-Adresses (https://www.postgresql.org/docs/9.2/static/libpq-envars.html). For a dns like  database.server.com you have to use the parameter PGHOSTADDR

**Comment by charmander** [comment]
You have it backwards – `PGHOSTADDR` is for addresses.

**Comment by ffischer1984** [comment]
hmmn I've read the postgresql.org documentation and yeah it seems you're right. The funny thing is, I tried both with an amazon postgresql instance hostname and only the `PGHOSTADDR ` established a connection. So in my opinion sth is wrong isn't it?
