### ISSUE TITLE
currentSchema/pg-connection-string

### ISSUE THREAD

**Issue by sth-fish** [brianc/node-postgres#1499]
hello,

I see pg-connection-string version used is 0.1.3, which is quite outdated.
Current version of pg-connection-string published to npm is  2.0.0, which includes changes to support currentSchema parameter.

Any plans to upgrade version so that schema will be supported, or are there any complications?

**Comment by vitaly-t** [comment]
Even version 2.0.0 is outdated, in what it supports.

Related: #1470

**Comment by brianc** [comment]
I can bump the version, it just might require a semver major bump. I'll look into it.  You can also consume the module yourself in the mean time and pass the parsed connection info direction to the client/pool constructor.

**Comment by uLan08** [comment]
Any news on this?

**Comment by vitaly-t** [comment]
@uLan08 #1689

**Comment by charmander** [comment]
Changed in 698993ec6d082ccd8be87404be3995364c08c7fa, first released in pg@8.1.0.
