### ISSUE TITLE
Properly handling transactions with node-postgres

### ISSUE THREAD

**Issue by honestserpent** [brianc/node-postgres#1504]
Issue was also posted on [node-pg-pool](https://github.com/brianc/node-pg-pool/issues/84)

There is no example in the documentation. I am wondering how to properly run transactions with node-postgres.

Here is what I have come up with. Suppose there is a function that needs to run an insert and an update in a transaction.

```
function foo(){
  return new Promise((resolve, reject)=>{
      var iq = 'insert into foo ("id", "data") values (1, "foo")';
      var uq = 'update foo set data = "foo1" where id=1';
      pool.connect().then(client => {
        var q = client.query('begin transaction')
          .then(() => {
            return client.query(insert_query);
          }).then(qresult => {
            return client.query(update_query);
          }).then(qresult => {
            return client.query('commit');
          }).then(qresult => {
            client.release();
            resolve();
          }).catch(err => {
            return client.query('rollback');
              .then(qresult => {
                // rilascia il client
                client.release();
                reject(err);
              }).catch(err=>{
                reject(err);
              });
          });
      }).catch(err => {
        reject(err);
      });
  });
}
```

I am wondering if this is the correct way to handle transactions and all the possible events and errors that could occur while running in order to properly rolling back the transaction and releasing the client to the pool.

If this is ok, maybe the doc can be updated to include this example?

**Comment by abenhamdine** [comment]
This library is low level by design, and there's no built-in specific methods to manage transactions.
So it's up to the user to use whatever flow-control logic he wants (promises, async.js...) to run commit, queries and rollback if need be, as you did.

**Comment by honestserpent** [comment]
@abenhamdine I know it is low-level by design, and that's why it so performant! ;)

I am wondering if the flow I have done is good or has flaws, aka it either lacks some form of error control or it is unnecessarly over complicated :)

**Comment by charmander** [comment]
A bit simpler with only native promises:

```js
function foo() {
  return pool.connect().then(client =>
    client.query('begin')
      .then(() => client.query('insert into foo ("id", "data") values (1, "foo")'))
      .then(() => client.query('update foo set data = "foo1" where id=1'))
      .then(() => client.query('commit'))
      .catch(error =>
        client.query('rollback')
          .catch(() => {})
          .then(() => Promise.reject(error)))
      .finally(() => client.release());
}
```

With async functions:

```js
async function foo() {
  const client = await pool.connect();

  try {
    await client.query('begin');
    await client.query('insert into foo ("id", "data") values (1, "foo")');
    await client.query('update foo set data = "foo1" where id=1');
    await client.query('commit');
  } catch (error) {
    await client.query('rollback').catch(() => {});
    throw error;
  } finally {
    client.release();
  }
}
```

**Comment by honestserpent** [comment]
@charmander thank you for your response.

Your promise-based solution seems the same as mine (am I missing something?). I'm not exactly sure what you mean with native promises.

But anyway, shouldn't there also be a catch for possible pool.connect() errors?

**Comment by charmander** [comment]
Not if all you’re doing in the catch is rejecting a promise. See https://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it.

The point is that it’s the same but “a bit simpler”, yes

**Comment by honestserpent** [comment]
thank you very much, i'll go back and study more about promises :)

**Comment by honestserpent** [comment]
@charmander just wanted to tell you that it looks like finally is not a native promise function.
