### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by ayanez17** [brianc/node-postgres#1506]
I'm getting the following error:
(node:13969) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: getaddrinfo ENOTFOUND  foo.bar.us-east-2.rds.amazonaws.com  foo.bar.us-east-2.rds.amazonaws.com:5432

My code is the following:

```
var express = require('express');
var router = express.Router();
const {
  Pool,
  Client
} = require('pg')


const forward_get = (req, res, next) => {
  console.log("PROBEID");
  console.log(req.params.probeid);
  const client = new Client({
    user: 'user',
    host: ' foo.bar.us-east-2.rds.amazonaws.com',
    database: dbname',
    password: 'password',
    port: 5432,
  })
  client.connect()

  client.query('SELECT * FROM daily_aggregation', (err, res) => {
    console.log(err, res)
    client.end()
  })

}








// If the request is a schools request then it forwards the request to forward_get
/* GET users listing. */
router.get('/:probeid', forward_get);

module.exports = router;
```

What could be causing this error ?

**Comment by abenhamdine** [comment]
client.connect() is asynchronous, you can't call connect() then query() like that.
You should call client.query in the connect() callback or use promise or async/await

**Comment by charmander** [comment]
In this example, you have a space at the beginning of your `host`, and the Markdown behind your error message shows the same thing. Is there a space at the beginning of your real host as well?

**Comment by ayanez17** [comment]
Yes. That is what it was. The space was preventing me to connect. In regards to calls, what is the difference between making a client and a pool?

Thanks!

**Comment by charmander** [comment]
A client can only run one query at once. If you wanted to run more than one at once, you would have to use multiple clients. To achieve that, you could create a client for every query, but you might create too many clients at the same time that way, and each query gets the overhead of creating a new connection. Pools manage multiple clients for you instead, keeping them open so they can be reused and limiting their number.
