### ISSUE TITLE
Example in node-postgres.com doesn't work

### ISSUE THREAD

**Issue by mzalazar** [brianc/node-postgres#1510]
The example in "Transactions" section (CODE TITLED: "A pooled client with callbacks") doesn't work, please FIX IT... so everybody using this library will benefit, thanks!

**Comment by charmander** [comment]
@brianc Specifically:

1. `require('client')` → `require('pg')`
2. `pool.connect` is missing an error check

@mzalazar If you were referring to something other than one of the above, please provide details.

**Comment by mzalazar** [comment]
Thanks A LOT! now is clear as water ;-)

**Comment by charmander** [comment]
Overlapping: #1456
