### ISSUE TITLE
Native Promise slow(((

### ISSUE THREAD

**Issue by masksnytko** [brianc/node-postgres#1512]
https://github.com/brianc/node-postgres/blob/9870c86fde2f489b7f5ad900ac1b4b9ff514e110/lib/client.js#L377

I recommend using bluebirdjs
const Promise = require("bluebird");

**Comment by charmander** [comment]
Callbacks are supported, so you can use Bluebird’s `promisify` to get a Bluebird promise. (The `Pool` constructor also allows a `Promise` type to be passed in, though it doesn’t apply to clients. Maybe it should.)

**Comment by gajus** [comment]
> Callbacks are supported, so you can use Bluebird’s promisify to get a Bluebird promise. (The Pool constructor also allows a Promise type to be passed in, though it doesn’t apply to clients. Maybe it should.)

This appears to be no longer the case.

Is there a way to pass a custom Promise implementation to node-postgres?

The stack trace for async/ await indeed sucks.

**Comment by charmander** [comment]
> This appears to be no longer the case.

@gajus I’m not sure what you mean; nothing’s changed here.

**Comment by gajus** [comment]
> @gajus I’m not sure what you mean; nothing’s changed here.

I don't see an option to pass Promise constructor to Pool constructor.

https://node-postgres.com/api/client#client-api

**Comment by charmander** [comment]
@gajus It’s missing from the new documentation, but still exists. (#1518 will also add it to `Client` after #1503 is resolved.)

**Comment by fanatid** [comment]
@masksnytko do you have benchmarks which shows how much native slower compare to bluebird in current package?
