### ISSUE TITLE
How could I get original wkb string from Postgres/PostGIS?

### ISSUE THREAD

**Issue by wucangeo** [brianc/node-postgres#1514]
I imported geometry data with PostGIS tools to Postgres database, the sample records are as follows.
`1	supermarket	0101000000D5CCCCCCCC465E40129DD7D825423F40`

node-postgres query from postgres, but get geojson type data, instead of wkb string.

Here's my code.

``` javascript
  const { Pool, Client } = require("pg");
  const client = new Client(db.getPgConfig());
  client.connect();
  var sql = `select geom from ${tableName} where gid =1`;
  var result = await client.query(sql);
  client.end();
```

The result is as follow.
```json
{"type":"Point","coordinates":[121.04773,30.88909]}
```

BUT, I want the original data,which is wkb string, like `0101000000D5CCCCCCCC465E40129DD7D825423F40`.
How could I get it ?

Thx a lot!

**Comment by sehrope** [comment]
You need to do it in the query by explicitly calling the conversion function to get the binary representation of the value. Pretty sure it's `ST_AsBinary(...)`: http://www.postgis.net/docs/ST_AsBinary.html

That would return a `bytea` that you could represent as hex.

**Comment by wucangeo** [comment]
@sehrope 
It works! You save me time!
