### ISSUE TITLE
Not work on Heroku

### ISSUE THREAD

**Issue by ChrisWongAtCUHK** [brianc/node-postgres#1515]
Thank for support in advance. 
My source code is on [GitHub](https://github.com/ChrisWongAtCUHK/hello-world-chriswongatcuhk/blob/master/server.js)
It seems that only the following code make error in the app.

```node.js
var pg = require("pg");
```
I have asked Heroku for support. They reply me on using heroku logs --tail

Success
![Success](https://i.imgur.com/E217ina.png)

Error
![Error](https://i.imgur.com/8vLW16m.png)

**Comment by charmander** [comment]
> I have asked Heroku for support. They reply me on using heroku logs --tail

What did `heroku logs --tail` show?

**Comment by charmander** [comment]
https://github.com/ChrisWongAtCUHK/hello-world-chriswongatcuhk/blob/509a8f76cb59979a351f2025a56e74be36b73f09/package.json#L9

pg 7 doesn’t support Node 0.12 anymore. Please upgrade to Node 8.

**Comment by ChrisWongAtCUHK** [comment]
It works. Many thanks.

**Comment by ChrisWongAtCUHK** [comment]
Well done@

2017-11-21 0:30 GMT+08:00 Charmander <notifications@github.com>:

**Comment by ChrisWongAtCUHK** [comment]
It works for a few days. Not long after(about 2 days ago), it does not work again, the connection seems working, but no select statement could be used. I have try select statement on the db in heroku, it works at the moment.
Thanks in advance.

**Comment by ChrisWongAtCUHK** [comment]
I think there is some failure in my function. Let me check if first.
