### ISSUE TITLE
"JOIN" queries not working

### ISSUE THREAD

**Issue by scottmangiapane** [brianc/node-postgres#1516]
Hello,

Thanks for making this project :)
I've noticed that when my query has a "JOIN" in it, some columns are omitted.

For example, if I use this query:
```
SELECT *
FROM   customer c
       JOIN address a
         ON c.address_id = a.address_id;
```

The resulting JSON object has all the correct fields (for both customer and address) but is missing data for the last two columns. It does this on other JOIN queries I've tried, always missing the last two columns.

**Comment by charmander** [comment]
“Missing data” how? Can you show the output produced by pg (through `console.log`) and the output produced when running the query in psql?

**Comment by scottmangiapane** [comment]
Sure.

Here is what the example query from my original post looks using psql in terminal. Sorry it's so long...
(not real names and emails, it's just an example database)
![screen shot 2017-11-20 at 8 15 54 pm](https://user-images.githubusercontent.com/16295236/33049811-c6a7569a-ce2f-11e7-8d5b-77bdec28f4bb.png)

But here is what I get when I execute the example query using this nodejs module.
![screen shot 2017-11-20 at 8 19 20 pm](https://user-images.githubusercontent.com/16295236/33049927-4498333a-ce30-11e7-9069-bc994e06c557.png)

Notice that although there are 18 fields being returned (which is the correct amount), each row only has 16 elements. Specifically the "phone" and one of the "last_update" column entries are missing.

**Comment by charmander** [comment]
`phone` isn’t missing. `address_id` and `last_update` appear twice, and JavaScript objects can’t have two properties with the same key. You can give them distinct aliases in your query or set [`rowMode: 'array'`][pg-rowmode] to access fields by index.


  [pg-rowmode]: https://node-postgres.com/features/queries#row-mode

**Comment by scottmangiapane** [comment]
Ah, I meant the second address_id, not phone number. Which would also be explained by what you said about javascript objects.

I did not know about `rowMode: 'array'`, that fixes my problem! Thank you very much :)
