### ISSUE TITLE
idle client error This socket is closed Error: This socket is closed

### ISSUE THREAD

**Issue by AliAtrash** [brianc/node-postgres#1517]
I simply made a user profile page. When I load it while testing I get this error a few seconds after the profile loads: 

```
idle client error This socket has been ended by the other party Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:355:12)
    at Connection.end (/Users/aa/Documents/Fonk/Node-Web/node_modules/pg/lib/connection.js:313:22)
    at global.Promise (/Users/aa/Documents/Fonk/Node-Web/node_modules/pg/lib/client.js:410:23)
    at Promise (<anonymous>)
    at Client.end (/Users/aa/Documents/Fonk/Node-Web/node_modules/pg/lib/client.js:409:12)
    at Pool._remove (/Users/aa/Documents/Fonk/Node-Web/node_modules/pg-pool/index.js:135:12)
    at Timeout.setTimeout (/Users/aa/Documents/Fonk/Node-Web/node_modules/pg-pool/index.js:38:12)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

A few seconds later I get this error: 

```
Error: Connection terminated by user
    at Client.end (/Users/aa/Documents/Fonk/Node-Web/node_modules/pg/lib/client.js:402:36)
    at Pool._remove (/Users/aa/Documents/Fonk/Node-Web/node_modules/pg-pool/index.js:135:12)
    at Timeout.setTimeout (/Users/aa/Documents/Fonk/Node-Web/node_modules/pg-pool/index.js:38:12)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

The above happens without any data exchange with server after loading. And then after around 30 secs I get this error: 

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
```

I don't know if the the first error is causing the rest but all of them freeze the server ability to respond or refresh for more than 30 secs, and sometimes it totally breaks and restart. 

Any idea?

**Comment by charmander** [comment]
Can you reduce it to a small script that can be used to reproduce the problem, and post that here with your Node and pg versions, please?

**Comment by AliAtrash** [comment]
Thank you, @charmander, for your reply. Here is my code simplified: 

The query:

`module.exports.profile_reader = function(id, callback) {
    const pool = require(__dirname + '/../../models/db')
    pool.connect(function(err, client, done) {
        if (err) {
            return console.error('reader_all: error fetching client from pool', err)
        }
        function workReader(entry, callback) {
            client.query("select * from profiles where user_id = $1", [id], function(err, result) {
                done()
                if (err) {
                    return console.error('reader_all: error in reading works =', err)
                } else {
                    callback(result.rows)
                }
            })
        }
    })
}`

Rendering the profile page:

`reader_all.profile_reader(nb_id, function(callback) {
    res.render('profile', {
        data: callback2,
        currentPage: '/profile'
    })
})`

Pool configuration: 

`const pg = require('pg')
const url = require('url')
const Pool = require('pg-pool')
let config
const psqlUrl = process.env['POSTGRESQL_URL']
const params = url.parse(psqlUrl)
const auth = params.auth.split(':')
config = {
    user: auth[0],
    password: auth[1],
    host: params.hostname,
    port: params.port,
    database: params.pathname.split('/')[1],
    max: 20,
    idleTimeoutMillis: 20000,
}
const pool = new Pool(config)
pool.on('error', function(err, client) {
    console.error('idle client error', err.message, err.stack);
})
module.exports.query = function(text, values, callback) {
    console.log('query:', text, values)
    return pool.query(text, values, callback)
}
module.exports.connect = function(callback) {
    return pool.connect(callback)
}`

Versions: 
Node v8.0.0
pg 7.3.0 

I hope you can help!

**Comment by charmander** [comment]
`workReader` is never called here. Can you reduce it to one script that doesn’t involve the database wrapper or template rendering, and run it yourself to ensure the example still causes the error to appear?

**Comment by AliAtrash** [comment]
Thank you for your patience! Now I am running this: 

```const express = require('express')
const app = express()

app.listen(3000, function() {
    console.log('Server running at http://127.0.0.1:/3000')
})

const pg = require('pg')
const url = require('url')
const Pool = require('pg-pool')

let config = {
    user: '',
    database: 'newbeesdb',
    password: '',
    host: 'localhost',
    port: 5432,
    max: 20,
    idleTimeoutMillis: 20000
}

const pool = new Pool(config)

pool.on('error', function(err, client) {
    console.error('idle client error', err.message, err.stack)
})

module.exports.query = function(text, values, callback) {
    console.log('query:', text, values);
    return pool.query(text, values, callback)
}

module.exports.connect = function(callback) {
    return pool.connect(callback)
}

app.get('/', function(req, res) {
    
    pool.connect(function(err, client, done) {
        if (err) {
            return console.error('Error in fetching client from pool', err)
        }

        client.query("select * from newbees where id = 131", function(err, result) {
            done()
            if (err) {
                return console.error('Error in reading a user:', err)
            } else {
                res.send(result.rows)
            }
        })

    })
})
```

The above works fine without the error! Any suggestion/advice on what could be generating the error in my code? I'm not a super expert.

Thank you

**Comment by AliAtrash** [comment]
Hey @charmander ,

I just went to `index.js` which is inside `node_modules/pg-ppl` and commented out the line `client.end()` and the error stopped showing! 

Am I doing anything wrong here? Any bad consequences?

**Comment by charmander** [comment]
> The above works fine without the error!

You need a version that does produce the error. Start with a copy of your project and remove unimportant parts, then keep removing parts until the error stops happening. Post the last version with an error in its entirety.

**Comment by AliAtrash** [comment]
Hello @charmander , 
Finally I could reduce the code that reproduces the error into one block. Here it is: 

```
const express = require('express')
const app = express()

// server
app.listen(3000, function() {
    console.log('Server running at http://127.0.0.1:/3000')
})

// home route
app.get('/', function(req, res) {
    newbees_reader_all(58, function(outcome) {
        res.send(outcome)
    })
})

// database reader
function newbees_reader_all(bb_id, callback) {

    // pool config
    const pg = require('pg')
    const url = require('url')
    const Pool = require('pg-pool')
    var pool_config = {
        user: '',
        database: 'newbeesdb',
        password: '',
        host: 'localhost',
        port: 5432,
        max: 20,
        idleTimeoutMillis: 5000,
    }
    const pool = new Pool(pool_config)
    pool.on('error', function(err, client) {
        console.error('idle client error', err.message, err.stack)
    })
    module.exports.query = function(text, values, callback) {
        console.log('query:', text, values);
        return pool.query(text, values, callback)
    }
    module.exports.connect = function(callback) {
        return pool.connect(callback)
    }

    pool.connect(function(err, client, done) {

        if (err) {
            return console.error(err)
        }

        var newBeesAllData = []

        // work
        function workReader(callback) {
            client.query("select * from works where newbee_id = $1", [bb_id], function(err, result) {
                done()
                if (err) {
                    return console.error(err)
                } else {
                    newBeesAllData.push(result.rows)
                    callback()
                }
            })
        }

        // skills
        function skillsReader(callbackSkills) {
            client.query("select skills.name from skills, newbees_skills where skills.id = newbees_skills.skill_id and newbees_skills.newbee_id = $1", [bb_id], function(err, result) {
                done()
                if (err) {
                    return console.error(err)
                } else {
                    newBeesAllData.push(result.rows)
                    callbackSkills()
                }
            })
        }

        // education
        function educationReader(callbackEducation) {
            client.query("select * from education where newbee_id = $1", [bb_id], function(err, result) {
                done()
                if (err) {
                    return console.error(err)
                } else {
                    newBeesAllData.push(result.rows)
                    callbackEducation()
                }
            })
        }

        // languages
        function languagesReader(callbackLanguages) {
            client.query("select languages.name, newbees_languages.level from languages, newbees_languages where newbees_languages.language_id = languages.id and newbees_languages.newbee_id = $1", [bb_id], function(err, result) {
                done()
                if (err) {
                    return console.error(err)
                } else {
                    newBeesAllData.push(result.rows)
                    callbackLanguages()
                }
            })
        }

        // references
        function referencesReader(callbackReferences) {
            client.query("select * from workreferences where newbee_id = $1", [bb_id], function(err, result) {
                done()
                if (err) {
                    return console.error(err)
                } else {
                    newBeesAllData.push(result.rows)
                    callbackReferences()
                }
            })
        }

        // certificates
        function certificatesReader(callbackCertificates) {
            client.query("select * from certificates where newbee_id = $1", [bb_id], function(err, result) {
                done()
                if (err) {
                    return console.error(err)
                } else {
                    newBeesAllData.push(result.rows)
                    callbackCertificates()
                }
            })
        }

        workReader(function() {
            skillsReader(function() {
                educationReader(function() {
                    languagesReader(function() {
                        referencesReader(function() {
                            certificatesReader(function() {
                                return callback(newBeesAllData)
                            })
                        })
                    })
                })
            })
        })

    })
}
```

I can tell that the problem is in the queries because when I read only from one table I don't get the error. But I need to read from all these tables and push the results into an array in a particular sequence in order to generate a complete user profile in templates. 

Something important to mention: this code used to work fine before. It's either packages update or a mistake I have done somewhere that made it generate this error. 

I hope now you can solve it (and teach me something for that matter)!

**Comment by charmander** [comment]
You’re making several queries on the same client, but calling `done()` after each one. `done()` should only be called once, after you’re completely done with the client. So remove all `done()`s in `client.query` callbacks, and call `done()` once at the end before `callback(newBeesAllData)`.

**Comment by sehrope** [comment]
Your code also has a number of issues unrelated to the node-postgres driver:

* You shouldn't be creating a new pool for each request. The pool should be created once and reused.
* You shouldn't be modifying `module.export` within a request.
* Take a look and understand NodeJS Promises and/or the async library rather than the pyramid of heavily nested callbacks.

**Comment by AliAtrash** [comment]
@charmander 
Problem solved! Thanks a ton, life saver! 

@sehrope 
Thank you for the advice. 
The pool in my app it's not as you see here. I wrote the pool configurations in a file and I reference it everywhere I need to connect to database like this:
```const pool = require(__dirname + '/../../models/db')```
Does referencing it create a new pool every time? Please let me know if you can :)

**Comment by sehrope** [comment]
Referencing the same pool object like that is fine. You can skip the `__dirname ` too as `require(...)` handles relative path against the current file; so just `require('../../models/db')`.

For the rest of the code look into the Promises / async and likely skip directly creating connections from the pool via `pool.connect(...)`. For non-transactional queries you're better off using `pool.query(...)` so you don't have to deal with connection management.
