### ISSUE TITLE
documentation -> pool -> release or done

### ISSUE THREAD

**Issue by pankleks** [brianc/node-postgres#1522]
What is the correct way or returning connection back to the pool?

https://node-postgres.com/features/pooling

Documentation uses `done` in first example `callback` and `release` in `promise`.

Is it intentional to use  different method based on `callback` or `promise` usage?

**Comment by charmander** [comment]
Yes, that’s intentional. You can use `client.release()` with the callback API, though; see https://github.com/brianc/node-postgres/issues/1302#issuecomment-304269624.

**Comment by pankleks** [comment]
Thanks!
