### ISSUE TITLE
Proper handling of transaction using promises

### ISSUE THREAD

**Issue by honestserpent** [brianc/node-postgres#1525]
I made a gist on how to properly handle transactions using pg and promises
Hopefully it is right and it can be added to the documentation.

You can find the gist [here](https://gist.github.com/honestserpent/647bd76231b8b2b695380d42a4bc1999)

**Comment by charmander** [comment]
That documentation already exists: https://node-postgres.com/features/transactions#a-pooled-client-with-async-await

**Comment by honestserpent** [comment]
@charmander that is with async/await, i don't see anything with promises?

**Comment by charmander** [comment]
async/await is promises.

**Comment by honestserpent** [comment]
@charmander well yes, I just thought maybe explict promises would have been useful

Not a problem though :)
