### ISSUE TITLE
Unable to connect to Redshift with temporary credentials

### ISSUE THREAD

**Issue by andynepo** [brianc/node-postgres#1528]
We have a Redshift cluster with the user name '_master_'
By calling "_getClusterCredentials_" from AWS-SDK we obtain a temporary user name & password that look like this:
user => 'IAM:master'
password => 'AfZwma3akQkth93uAJW1V*****7M6IaSqzWgaWfrCFaRem6vtbLEeek1wuVXOl2sw=='

Using "native" credentials (_master/****_) in Client or Pool work fine.
With the temporary credentials we are getting an error "_password authentication failed for user "IAM:master"_".

However, if we use the same temporary credentials in _SQL Workbench_, it connects. The same temporary credentials work fine with the _psycopg2_ python library. So it is not the credentials issue.

**Comment by mukk85** [comment]
Not sure if related, but I am also getting authentication errors after upgrading from 6.2.3 and using a pool.

**Comment by tobilg** [comment]
I have the same issue. Are there any updates?

**Comment by andynepo** [comment]
Yes. You have to specify "ssl: true" in the params argument when creating the Pool object:
      const params = {
        host: process.env.rsh_host,
        port: process.env.rsh_port,
        database: process.env.rsh_dbName,
        user: data.DbUser,
        password: data.DbPassword,
        max: 10,
        _ssl: true_
      };

const pool = new Pool(params);

**Comment by tobilg** [comment]
Adding the `ssl: true` parameter indeed works. Thanks a lot @andynepo!
