### ISSUE TITLE
Error: role "cgroves3" does not exist

### ISSUE THREAD

**Issue by cgroves3** [brianc/node-postgres#1538]
I am experiencing the same issue faced in #868 . Is there any way to get this working without using environment variables?

**Comment by cgroves3** [comment]
Maybe I misunderstand how to make a connection. I am passing a config object with connection information as shown in the "Connecting" section of you site using the Pool and receiving the "role 'cgroves3' does not exist."

**Comment by charmander** [comment]
Can you show the exact code you’re using to connect, please?

**Comment by cgroves3** [comment]
The config json file has the same structure as shown in the "Connecting section" 

database.js
`'use strict';

const fs = require('fs');
const { Pool } = require('pg');

var configPath = "./database/config.json";
fs.readFile(configPath, (err, data) => {
    if (err) {
        module.exports = new Pool();
    }
    else {
        module.exports = new Pool(data);
    }
});`

controller.js
`'use strict';
const db = require('../database/database');

class IssueController {
    getAll(req, res) {
        var userId = "";
        var sql = "select now() as CURRENT_DATE";
        var dates = [];

        //const client = db.connect();

        db.query(sql).then((queryRes) => {
            for (var i = 0; i < queryRes.rows; i++) {
                var date = queryRes.rows[i].current_date;
            };
            db.end();
            res.json(dates);
        })
            .catch((err) => { res.status(500).json(err) });
    }
}

module.exports = IssueController;`

**Comment by ryan-copperleaf** [comment]
module.exports = new Pool(JSON.parse(data));

and don’t just ignore read errors; throw!

**Comment by cgroves3** [comment]
ok thanks.
