### ISSUE TITLE
The number of rows and the number of fields do not match.

### ISSUE THREAD

**Issue by LeeBeomYong** [brianc/node-postgres#1539]
I queried as follows.

- QUERY

client.query("select 1+1, 3.0/4, 'abcd' as col2", [], function (err, res) {
            if (err) throw err;
            console.log(res);
});

The query returned the result as follows.

- RESELT

Result {
  command: 'SELECT',
  rowCount: 1,
  oid: null,
  rows:
   [ anonymous { '?column?': '0.75000000000000000000', col2: 'abcd' } ],
  fields:
   [ Field {
       name: '?column?',
       tableID: 0,
       columnID: 0,
       dataTypeID: 23,
       dataTypeSize: 4,
       dataTypeModifier: -1,
       format: 'text' },
     Field {
       name: '?column?',
       tableID: 0,
       columnID: 0,
       dataTypeID: 1700,
       dataTypeSize: -1,
       dataTypeModifier: -1,
       format: 'text' },
     Field {
       name: 'col2',
       tableID: 0,
       columnID: 0,
       dataTypeID: 705,
       dataTypeSize: -2,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers:
   [ [Function: parseInteger],
     [Function: noParse],
     [Function: noParse] ],
  RowCtor: [Function: anonymous],
  rowAsArray: false,
  _getTypeParser: [Function: bound ] }

Do not match the number of rows and the number of fields?

**Comment by abenhamdine** [comment]
I think columns with the same name are overidden by the parser, i already noticed that. 
It surprised me because pg admin for instance automatically dedups columns names.

**Comment by charmander** [comment]
See https://github.com/brianc/node-postgres/issues/1516#issuecomment-345888019

**Comment by LeeBeomYong** [comment]
I solved it with rowMode. 
Thank you.
