### ISSUE TITLE
Postgres RDS SSL issue

### ISSUE THREAD

**Issue by polizz** [brianc/node-postgres#1540]
I'm having issues just connecting with SSL.

I researched your old issues and found one similar [here](https://github.com/brianc/node-postgres/issues/643):

```
  ssl: {
    ca: [fs.readFileSync(path.resolve('./rds-ssl-ca-cert.pem'), 'ascii')]
  }
```
, but that format is slightly different than what your docs currently show:

Node is blowing up without even an error when I use that.

I also tried this:

```
  ssl: {
    rejectUnauthorized: false,
    ca: fs.readFileSync(`${__dirname}/rds-combined-ca-bundle.pem`),
  },
```

But all I'm getting is this error:

```
TypeError: Cannot read property 'then' of undefined
server.js:30
    at Object.<anonymous> (/Users/awpaul/projects/field-es-indexer/src/server.js:31:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

I only have the one public AWS pem file to reference, so the other two you show in your docs are inapplicable to me I believe. Any direction would be helpful.

I'm confirmed SLL is required and working from pgadmin, but I'm not even getting the typical server rejection message ```FATAL: no pg_hba.conf entry for host "host.ip", user "someuser", database "postgres", SSL off```, so I think this is a node-side issue.

**Comment by charmander** [comment]
What is `src/server.js:31`?

**Comment by polizz** [comment]
```
30     pgPool.connect(options)
31       .then(() => {
32         kafkaConnect();
```

**Comment by charmander** [comment]
Options should be passed to the `Pool` constructor (`const pgPool = new pg.Pool(options)`); `.connect()`’s only parameter is a callback.

**Comment by polizz** [comment]
I must be blind, thanks for pointing it out.
