### ISSUE TITLE
Connection terminated unexpectedly

### ISSUE THREAD

**Issue by swirlsky** [brianc/node-postgres#1542]
When the computer loses the connection to the internet while pg is connected to a database, this error is thrown.
[
![untitled](https://user-images.githubusercontent.com/27681171/34270080-433c821a-e687-11e7-8c8f-048a61d7b2fb.png)
](url)

Is this an internal error in pg, or am I supposed to somehow handle it in my node.js app?
(Sorry, for the image format, I couldn't copy-paste from XTerm.)

**Comment by abenhamdine** [comment]
You can handle the error on the pool : 

```js
const pool = new Pool()
pool.on('error', (err) => {
  console.error('An idle client has experienced an error', err.stack)
})
```

see also https://github.com/brianc/node-postgres/issues/1324 for more background
