### ISSUE TITLE
Optimize

### ISSUE THREAD

**Issue by masksnytko** [brianc/node-postgres#1551]
The size is known, it is more efficient to create an array of the required length

https://github.com/brianc/node-postgres/blob/a664983cbb6317a7d7e1fdae87583658ab8920db/lib/connection.js#L469
https://github.com/brianc/node-postgres/blob/a664983cbb6317a7d7e1fdae87583658ab8920db/lib/connection.js#L518

Do not use shift as it is linear and with the growth of the queue from 100 requests, which is very easy, there is a significant slowdown, you need to use something like this https://github.com/masksnytko/queue.o

https://github.com/brianc/node-postgres/blob/a664983cbb6317a7d7e1fdae87583658ab8920db/lib/client.js#L46
https://github.com/brianc/node-postgres/blob/a664983cbb6317a7d7e1fdae87583658ab8920db/lib/client.js#L352

In general, the code is not the worst for you, but there is a huge amount of optimizations, I wrote my decision, trying to squeeze the maximum speed and simplicity into 400 lines of code
https://www.npmjs.com/package/pg.io

Thank you for attention!

**Comment by charmander** [comment]
> The size is known, it is more efficient to create an array of the required length

Show benchmarks

> Do not use shift as it is linear and with the growth of the queue from 100 requests

You should be using a pool, not the query queue on a single client. The query queue is a bit of a misfeature.
