### ISSUE TITLE
pg.io 10x times faster pg (benchmark)

### ISSUE THREAD

**Issue by masksnytko** [brianc/node-postgres#1552]
```js
const pg = require('pg');

const DB = new pg.Pool({
    user: 'postgres',
    password: 'password',
    database: 'database',
    max: 8
});

var k = 0;
console.time('pg');
for (var i = 0; i < 100000; i++) {
    DB.query('SELECT 1', (err, res) => {
        if (++k === 100000) {
            console.timeEnd('pg');
        }
    });
}
```
pg: 12041.082ms

```js
const PG = require('pg.io');

const DB = new PG({
    user: 'postgres',
    password: 'password',
    database: 'database',
    max: 8
});

var k = 0;
console.time('pg');
for (var i = 0; i < 100000; i++) {
    DB.query('SELECT 1', (err, res) => {
        if (++k === 100000) {
            console.timeEnd('pg');
        }
    });
}
```
pg: 1169.044ms

**Comment by brianc** [comment]
Thanks for the info - I'll look at possible speed improvements we can implement here.  And, as always, totally open to pull requests that'll improve performance.

**Comment by charmander** [comment]
It turns out pg-pool uses `Array#shift()` for its query queue too; that will affect cases like this with thousands of queued queries especially. I have a simple enough fix ready, but there are probably enough outstanding pg-pool pull requests to deal with for now. =)

**Comment by masksnytko** [comment]
https://github.com/brianc/node-postgres/issues/1551
I told you about this)))

**Comment by charmander** [comment]
That’s the client query queue, not the pool query queue =)
