### ISSUE TITLE
pg.Client.connect() function taking a lot of time.

### ISSUE THREAD

**Issue by oshin-gupta** [brianc/node-postgres#1554]
var pg = require("pg");
var dbConfig= "postgres://user_name:password@localhost:5432/db_name";
const client = new pg.Client(dbConfig);
 client.connect()
 .then(function (connection) {
  console.log("Database connected");
    })
    .catch(function (error) {
        console.log(error);
        logger.error(error);
    });

**Comment by charmander** [comment]
How much time, exactly? Is `psql` also affected?
