### ISSUE TITLE
inconsistent response with native query from datagrip

### ISSUE THREAD

**Issue by liz282907** [brianc/node-postgres#1562]
i have query the postgres via the pg interface with the following query:
```
const sql = `SELECT count(*) from cl_project.emails_test
WHERE  emails_test.subject ~* '\[.+\].*android'
AND label ISNULL
AND subject ~* '(feature|request)'`

 pool.query(sql).catch(err=>{
        console.log(err)
    }).then((values)=>{
        console.log(values.rows.length)
    })
```
and at the same time i test the raw sql via datagrip.
however they give the different answer. 
datagrip: 3076 while pg: 760 .and i test some other cases , it seems that often the case. pg return much fewer results than the normal one.
any idea of it?

**Comment by charmander** [comment]
> `\[.+\]`

This text is part of a template string, and template strings still support backslash escapes; you’re sending `'[.+].*android'` to the server. You can double the backslashes or use a `String.raw` template tag.
