### ISSUE TITLE
Please, share examples how to write files to bytea field

### ISSUE THREAD

**Issue by Aparus** [brianc/node-postgres#1566]
Hello. Thanks for your library. 
Sorry for question. But I can't find examples, how to write and read files to/from bytea fields. 
Can someone share with me examples or link to documentation?

**Comment by charmander** [comment]
They’re retrieved as [`Buffer` objects][1], and you can pass `Buffer`s as `bytea` parameters to queries.

  [1]: https://nodejs.org/api/buffer.html

**Comment by GitStorageOne** [comment]
Hello!
Is there a way to save relatively large file, like 50mb using buffer limited to 5Mb?
Idea is to not load entire file in one buffer (to save some memory) and send file partially.
