### ISSUE TITLE
error: could not determine data type of parameter

### ISSUE THREAD

**Issue by marshallford** [brianc/node-postgres#1569]
Hello! I am running into an error when using a parameterized query and I pass a param that is not actually used in the query. Now I understand that I could refactor my code to strip out unused params beforehand but my queries are somewhat "generated" and I am hoping to avoid adding more ORM like helper functions to my codebase. Regardless of the reason behind keeping stray params in the query, this seems like a bug.

After speaking with someone on IRC I decided to make an issue as I am now a little more certain that this is not an issue with my codebase. Below is the query, the params, and the error. Thank you!

```
UPDATE ti_user SET (email,firstname,lastname,phone) = ($5,$6,$7,$8)
WHERE ti_user.uuid = $9
RETURNING uuid as "uuid",username as "username",tenant as "tenant",inactive as "inactive",cp_type as "cpType",email as "email",firstname as "firstname",lastname as "lastname",phone as "phone";
  
[ 'admin@test.com',
  'public',
  false,
  'admin',
  'admin@test.com',
  'test',
  'test1',
  '123-456-7890',
  1 ]
error: error: could not determine data type of parameter $1

**Comment by charmander** [comment]
pg doesn’t parse queries, so it can’t determine when you’ve skipped a parameter and send a dummy type and value for it. Consider using a query builder, like [node-sql][] or [Knex.js][].

  [node-sql]: https://github.com/brianc/node-sql
  [Knex.js]: http://knexjs.org/
