### ISSUE TITLE
Please help with memory drain

### ISSUE THREAD

**Issue by MihaelIsaev** [brianc/node-postgres#1571]
**Environment**
```
node: v9.5.0 (also tested on v8.9.4)
pg lib: v7.4.1
postgres db: v10.1
OS: macOS High Sierra
```

Hello,

I'm trying to develop my app with postgres database and I need to insert hundreds of thousands rows, but I faced with huge memory drain while insertions.
I've created a little test code to reproduce my problem.
Could you please take a look and maybe give me some suggestions is there my mistake in the code, or node itself or `pg` lib draining the memory.

Here is my test code

```
const { Pool, Client } = require('pg')
const pool = new Pool({
    user: 'postgres',
    host: '127.0.0.1',
    database: 'test',
    password: 'qwerty',
    port: 5432
})
const test = async () => {
    for (let i = 0; i < 100000; i++) {
        await new Promise(resolve => {
            pool.query('INSERT INTO "public"."TestTable" VALUES(DEFAULT) RETURNING "id";', (err, res) => {
                resolve()
            })
        })
    }
    pool.end()
}
test()
```

This code inserts 100 000 rows one by one.
If TestTable's id cloumn is Integer then it eats 55Mb of RAM
But if as in my case TestTable's id column is uuid then it eats 500Mb of RAM

How can I avoid this huge memory drain?
It looks like memory drain depends on how much data postgres returns after insertion...

In real project I'm trying to insert a lot of data and as it won't freeing up RAM at all my app just hangs after insertion of 500k rows with uuids (at around 3Gb of RAM usage)
I tried to null everything everywhere but it doesn't help me, my app still drain the RAM.

Thank you in advance.

**Comment by charmander** [comment]
I can’t reproduce this; memory use stays constant for all 500,000 rows. How is `TestTable` defined? Are you running with a debugger attached?

**Comment by vitaly-t** [comment]
@MihaelIsaev is your example a hypothetical? If it is not, then it is a horrible way to insert many records. You are supposed to group such inserts into multi-row insert queries.
