### ISSUE TITLE
Feature request : send parameterized queries without preparing them

### ISSUE THREAD

**Issue by laurentdebricon** [brianc/node-postgres#1573]
if you want to run a query with params, node pg will always "prepare" the request :

```
Query.prototype.requiresPreparation 
  // prepare if there are values
  if (!this.values) { return false }
  return this.values.length > 0

```

But, PostgreSQL supports PQexecParams, so if you want to go really fast, you just throw your query with values without having to prepare it first, thus removing two extra round trips to the server.  You can also use PQsendQueryParams to do it asynchronously.

**Comment by charmander** [comment]
> But, PostgreSQL supports PQexecParams

`PQexecParams` is a libpq function that sends [the same set of messages as pg does][1].

  [1]: https://github.com/postgres/postgres/blob/bf6c614a2f2c58312b3be34a47e7fb7362e07bcb/src/interfaces/libpq/fe-exec.c#L1478
