### ISSUE TITLE
Package main should point to index

### ISSUE THREAD

**Issue by arichiardi** [brianc/node-postgres#1574]
Hello folks!
I have recently had a problem with importing this package and realized that the `main` field in `paxhage.json` does not point to `lib/index.js`.

Would you be interested in a small patch?

While it is true that it seems to work fine in a standard node environment, the `package.json` doc requires a module there and other less lenient tools are failing.

What do you think?

**Comment by charmander** [comment]
`./lib` *is* a module by virtue of containing an `index.js`; you should report a bug with the failing tools.
