### ISSUE TITLE
Switching to use SSL throws error relation doesn't exist

### ISSUE THREAD

**Issue by anshukch** [brianc/node-postgres#1576]
>Node Version: v6.11.1
Postgres Version: postgres (PostgreSQL) 9.6.1
pg Version: ```{
    "pg": "^4.3.0",
    "pg-query-stream": "^0.7.0",
    "pgsql-write-builders": "0.0.5",
}```
Minimum snippet to replicate the problem: Wasn't sure how to. Would love to see one myself and learn.

So, I was trying to enable SSL on my working DB. Changed the associated config in postgresql.conf, created self signed certificates, restarted postgres, changed the connection string to use '?sslmode=require' and when I run the app it doesn't throw error and I'm getting results.

Then I try this alternative way to specify **ssl: true** along with **connectionString** in an object and I get the error while running the query - the relation doesn't exist.

I change back to parameterised connection or to no SSL and there is no problem. I hope I'm not overlooking something too obvious here.

Could someone help me understand please why it's happening? And, the other important question I have is how to see if my postgres connections are indeed using SSL? I don't see trace of it in postgres log.

Please let me know if more info is required.

Thanks,
Anshu

**Comment by charmander** [comment]
Are you able to upgrade to pg 7.4.1? It’ll be easier to help if the bugs fixed between 4.3.0 and the latest version can be ruled out.

**Comment by anshukch** [comment]
I might try that. I'll look for details related to changes between the two versions. But could you please tell me if there might be any breaking change in the migration? Also, how to see if my postgres connections are indeed using SSL?

Thanks for replying. Will try it in an hour or two and let you know.

**Comment by anshukch** [comment]
Hey @charmander ! I upgraded to following config:

>```{"pg": "^7.4.1", "pg-query-stream": "^1.1.1",  "pgsql-write-builders": "1.1.0"}```

I still get the same error.

**Comment by charmander** [comment]
Can you show how you’re creating the client or pool?

**Comment by anshukch** [comment]
This if my `issueConfig.js`

    var _ = require("lodash");
    var endpoint = parseEndpoint(process.env.NODE_API_ENDPOINT || "http://127.0.0.1:9000");
    
    function parseEndpoint(s) {
        s = s.replace(/^https?:|\//g, "").split(":");
        return {
            host: s[0],
            port: s[1] ? parseInt(s[1]) : 80
        };
    }
    
    var config = _.defaults({
        name: "Node API Server",
        port: process.env.PORT,
        host: endpoint.host,
        djangoApiEndpoint: process.env.DJANGO_API_ENDPOINT,
        sessionSecretKey: process.env.DJANGO_SECRET_KEY || "this-is-not-a-secure-key",
        sessionPrefix: "session:",
        mongo: process.env.MONGOLAB_URI,
        postgres: {
            connectionString: process.env.DATABASE_URL,
            ssl: true
        },
        postgresReadRep: {
            connectionString: process.env.READSLAVE_DATABASE_URL || process.env.DATABASE_URL,
            ssl: true
        },
    }, { // local defaults
        port: endpoint.port,
        host: endpoint.host,
        djangoApiEndpoint: "http://localhost:8000",
        sessionSecretKey: "this-is-not-a-secret-key",
        mongo: "mongodb://127.0.0.1:27017/myappname",
        postgres: "postgres://postgres:postgres@127.0.0.1/myappname",
        postgresReadRep: "postgres://postgres:postgres@127.0.0.1/myappname",
        celery: {
            BROKER_URL: process.env.RABBITMQ_BIGWIG_URL || "amqp://guest:guest@localhost:5672"
        }
    });

This is my `issuePostgres.js`

    "use strict";
    const { Client } = require('pg');
    var QueryStream = require("pg-query-stream");
    var VError = require("verror");
    var config = require("../issueConfig");
    var sqlBuilder = require("pgsql-write-builders");
    
    function ConnectAndQuery(conf) {
    
        function queryStream(sql, params, cb) {
            if (!cb) {
                cb = params;
                params = null;
            }
            const pg = new Client(conf);
            pg.connect();
            var stream = pg.query(new QueryStream(sql, params)).on("end", done);
            if (cb) cb(null, stream);
        }
    
        function query(sql, params, cb) {
            if (!cb) cb = params;
            const pg = new Client(conf);
            pg.connect();
            pg.query(sql, params, (err, res) => {
                if (err) err = new VError(err);
                cb(err, res);
            });
        }
    
        function select(sql, params, cb) {
            if (!cb) cb = params;
    
            query(sql, params, function (err, results) {
                if (err) return cb(err);
    
                if (!results || results.rowCount === 0)
                    return cb(null, []);
    
                cb(null, results.rows);
            });
        }
    
        return {
            connStr: conf,
            queryStream: queryStream,
            query: query,
            select: select
        };
    }
    
    module.exports = {
        readDb: new ConnectAndQuery(config.postgresReadRep),
        db: new ConnectAndQuery(config.postgres)
    };

My `pg_hba.conf`

	hostssl  all  all  127.0.0.1/32  trust

	#    host  all  all  127.0.0.1/32  trust

	hostssl  all  all ::1/128  trust

	hostssl  all  all  0.0.0.0/0  trust

Relevant `package.json` section

	{"pg": "^7.4.1”, "pg-query-stream": "^1.1.1”, "pgsql-write-builders": "1.1.0"}

I pasted complete code for brevity. I also have few details to add to problem statement. 

1) I found that `sslmode=require` also failed with `no pg_hba.conf entry for host "127.0.0.1", user "postgres", database "myappname", SSL off` error after I forced SSL by replacing all **host** with **hostssl**. But then when I uncomment the line above it works without error and I presume it's because of a no SSL handshake with Postgres.

2) When I use `issueConfig.js`, I have seen three errors till now:
a) FATAL:  no pg_hba.conf entry for host "127.0.0.1", user "eureka", database "eureka", SSL off
b) terminating connection due to administrator command
c) the relation doesn’t exist

Error a is happening now. Error b happened yesterday night and Error c happened even before yesterday night. So, am confused and I think I might be making some silly one here. Please let me know your thoughts. Thanks!

**Comment by charmander** [comment]
Try a smaller example – no environment-based configuration, no pg-query-stream, no `ConnectAndQuery`. Just create a client with some configuration:

```js
"use strict";

const pg = require("pg");

const client = new pg.Client({
    // ⋮
    ssl: true,
});
```

and run the query that fails:

```js
client.connect(error => {
    if (error) throw error;

    client.query("…", (error, result) => {
        if (error) throw error;
        console.log(result);
        client.end();
    });
});
```

(That would be the starting point for the “smallest possible snippet of code to reproduce the problem” the README refers to.)
