### ISSUE TITLE
Add sql-template-strings call-out to the documentation

### ISSUE THREAD

**Issue by claytongulick** [brianc/node-postgres#1578]
Frustratingly, I just wrote my entire backend using long lists of numbered params - $1, $2, $3, $4 ...etc... really wishing I had named parameters the whole time.

So, I was thinking about creating a patch for node-postgres to accept named parameters, but I saw it had already been done/considered/rejected: https://github.com/bwestergard/node-postgres-named

I didn't feel comfortable monkey patching node-postgress with that solution, so I thought, 'wow, wouldn't it be cool if I wrote a neat little es6 template string utility to do this for me?' - then I found https://github.com/felixfbecker/node-sql-template-strings .

Granted, it's completely my fault I blundered ahead doing it that way instead of investigating a better solution from the start, but a little call out to that project in the official node-postgres docs would save people like me a lot of time/rewriting, and close some of the named parameter feature request issues I see cropping up.

Thanks!!

**Comment by charmander** [comment]
A partial list of tools that can be used with pg is in the GitHub Wiki: https://github.com/brianc/node-postgres/wiki/Extras

**Comment by claytongulick** [comment]
Wow, how did I miss that? Thanks!

**Comment by vitaly-t** [comment]
@charmander 

How to update the list of Extras? It is closed to read-only, and cannot be PR-d either.

**Comment by charmander** [comment]
Added this package to the aforementioned Extras wiki page, which might move to https://node-postgres.com/ in some form someday.
