### ISSUE TITLE
relation with OID #### does not exist

### ISSUE THREAD

**Issue by antonlytvyniuk** [brianc/node-postgres#1579]
Hello,
When existing query like folowing
insert into table (column_1, column_2, ..., column_n)
select $11, $12, ... $1n
union all
select $21, $22, ... $2n
union all
....
select $m1, $m2, ... $mn

Sometimes I have error relation with OID #### does not exist.
PG server 8.3

**Comment by charmander** [comment]
I don’t think that’s likely to have anything to do with node-postgres. Maybe upgrade to PostgreSQL 10.2.
