### ISSUE TITLE
Parameterized query suggestion

### ISSUE THREAD

**Issue by qwang07** [brianc/node-postgres#1581]
When I try this query, it returns an error:
```
db.query(`
    UPDATE
      products as p
    SET
      updated_at = 1520601181393, "category" = t."category"
    FROM
      (VALUES ($1,$2),($3,$4)) AS t (id,category)
    WHERE
      p.id = t.id AND
      p.store = 1
    RETURNING
      p.id,
      p.title,
      p.status,
      p.condition,
      p."productInfo",
      p.price,
      p.note,
      p.created_at,
      p.updated_at
`, [1,2,3,4])
=> error: operator does not exist: integer = text
```
Before query was submited, it will transfer [1,2,3,4] to ['1','2','3','4'] by `self.values = self.values.map(utils.prepareValue)` in `pg` module, and then it use `quoteParamValue` to add quote to each value.  I think this is not good. I suggest number should stay as number without transfer to string when we passed it. Because if I want to pass number in string, I will directly pass ['1','2','3','4'] to the query. Depends on type of value, number can substitute directly into query text without quote.

**Comment by charmander** [comment]
Parameters without specified types (which all pg parameters using documented APIs are) are assumed to be `text` in that context:

```
=> PREPARE q AS SELECT 1 = t.id FROM (VALUES ($1)) AS t (id);
ERROR:  operator does not exist: integer = text
LINE 1: PREPARE q AS SELECT 1 = t.id FROM (VALUES ($1)) AS t (id);
```

Add a cast so PostgreSQL can infer the right type for all parameters:

```sql
⋮
FROM
  (VALUES ($1::int, $2::int), ($3, $4)) AS t (id, category)
⋮
```
