### ISSUE TITLE
JSON arrays from postgres and parsing the *right way* with node-pg

### ISSUE THREAD

**Issue by andresrivero** [brianc/node-postgres#1586]
Is this the correct way to receive a json array and process it? I feel like I'm either doing the node-postgres parsing wrong or the select is off. In psql I get what I want [{key:value,...},...]. But when I try to do res.send of the added row of the result it's just empty, that or it only shows 1 row. I have to do the code below to get anything printed in express + node-postgres:

```
router.get('/riderequests', function(req, res) {
   if (Object.keys(req.query).length === 0) {
    var client = new pg.Client(conString);
    client.connect();
    var ridequery = "select array_to_json(array_agg(row_to_json(t))) from ( select request_id, rider_first_name from current_ride_requests ) t"
  
    var rideq = client.query(ridequery);
 
    rideq.on("row", function (row, result) {

      result.addRow(row);
    
    });


    rideq.on("end", function (result) {
      
      if ('row_to_json' in result.rows[0]) {
        res.send(result.rows[0].row_to_json);

      } else if ('array_to_json' in result.rows[0]) {
        res.send(result.rows[0].array_to_json);

      } 

      res.end();
  
    }); 
   }
```
I feel like I'm missing something simple. This is the text sample from that SQL btw: [{"request_id":1,"rider_first_name":"Sally"},{"request_id":2,"rider_first_name":"Driverdude"},{"request_id":3,"rider_first_name":"Driverdude"}]

**Comment by charmander** [comment]
The definition of `result` is missing from that snippet. There’s no benefit to using an explicit `Result` object, though; instead, you should provide a single callback. The pool also offers a more convenient way to connect a client; it can be configured so clients don’t remain connected after being released. (The snippet is also missing `client.end()` – was that what `res.end()` was supposed to be?)

```js
var pool = new pg.Pool({
  connectionString: conString,
});

router.get('/riderequests', function (req, res, next) {
  pool.query(
    "select jsonb_agg(to_jsonb(t)) from (select request_id, rider_first_name from current_ride_requests) t",
    function (err, result) {
      if (err) {
        next(err);
        return;
      }

      res.send(result.rows[0].jsonb_agg);
    }
  );
});
```

Here, `pool.query` releases the client for you. The rewritten version is compatible with the latest version of pg (7.4.1); please upgrade to it. The result should be the same as when you run the query

```sql
select jsonb_agg(to_jsonb(t)) from (select request_id, rider_first_name from current_ride_requests) t
```

in psql. Be aware that it can be `NULL` when `t` is empty.

**Comment by andresrivero** [comment]
Thanks for the input! This makes a lot more sense.
