### ISSUE TITLE
Inserting JSON into an JSONB array column

### ISSUE THREAD

**Issue by LarsBuur** [brianc/node-postgres#1588]
I have a table like so:
```
CREATE TABLE stories
(
    id integer NOT NULL DEFAULT nextval('stories_id_seq'::regclass),
    messages jsonb[] DEFAULT ARRAY[]::jsonb[]
 )
```
I have inherited the system and the schema is not easily changed. 

In multiple issues, people talk about stringified objects but not arrays but it seems that they normally talk about a jsonb column and not jsonb[] column.

I am looking for an example on how to insert into my table and how to update. I am fine with updating everything. I do not need a fancy jsonb query where only some of the json object is updated.

say we have a very simple object like:

```
const story = {
  id: 1,
  messages:[{msgId:1, msg:'message one'}, {msgId:2, msg:'message two'}]
}
```
How do I insert this into my stories table?
How do I update this in my stories table?

I have tried multiple variations like so:
```
const updateQry = "UPDATE stories SET messages = ($1)::JSONB[]  WHERE id=$2 RETURNING *";
const res =  await db.query(updateQry, [story.messages, story.id]);
```
both with story.messages stringified etc.

Any help would be much appreciated.

**Comment by LarsBuur** [comment]
Another attempt:
```
const updateQry = 'UPDATE stories set messages=ARRAY[$1]  WHERE id=$2 RETURNING *';
const res =  await db.query(updateQry, [story.messages, story.id]);
```

**Comment by charmander** [comment]
This should have worked:

> ```js
> const updateQry = "UPDATE stories SET messages = ($1)::JSONB[]  WHERE id=$2 RETURNING *";
> const res =  await db.query(updateQry, [story.messages, story.id]);
> ```

What error did it produce?

**Comment by LarsBuur** [comment]
Thank you so much. For some reason, it works now and I must have made a typo. Closing.
