### ISSUE TITLE
"INTERVAL $1" is not parameterized 

### ISSUE THREAD

**Issue by haoliangyu** [brianc/node-postgres#1593]
I have a query like this

``` sql
UPDATE
  my_table
SET
  expire_after = now() + INTERVAL $1
RETURNING *
```

and try to parameterize the query with

``` javascript
pg.query(my_query, ['30 seconds'])
```

It doesn't work and throws an error :-(

```
ERROR:  syntax error at or near "$1" at character xxx
```

**Comment by charmander** [comment]
`INTERVAL '…'` is an interval literal; you would use `$1::interval` to interpret a parameter as an interval. (Passing `[30]` and adding `$1 * INTERVAL '1 second'` might also be appropriate.)

**Comment by haoliangyu** [comment]
The `$1::interval` doesn't work for me but the `$1 * INTERVAL '1 second'` works. Thanks for the tips.

**Comment by tienzochi** [comment]
What if we need it for the GENERATE_SERIES? Like GENERATE_SERIES(
                    DATE_TRUNC($5, $2::timestamp),
                    DATE_TRUNC($5, $3::timestamp),
                    '1 $5')
Where $5 is hour, day, week, or month?
