### ISSUE TITLE
Need a way of actively read data

### ISSUE THREAD

**Issue by eduardobcastro** [brianc/node-postgres#1595]
It is going to be necessary to build [Async Iterators](https://github.com/tc39/proposal-async-iteration) and to interrupt data transferring.

Something like this:
`const {done, row} = await query.read()`

**Comment by charmander** [comment]
Are you looking for [cursors](https://node-postgres.com/api/cursor)?

**Comment by eduardobcastro** [comment]
Thanks @charmander. Didn't know about that. I suggest mentioning it in docs.
