### ISSUE TITLE
(node:252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'submit' of undefined

### ISSUE THREAD

**Issue by ermarkar** [brianc/node-postgres#1597]
Here is the full detail 
https://stackoverflow.com/questions/49348254/how-to-connect-heroku-postgres-database-in-nodejs

And the version is 7.4.1

**Comment by sehrope** [comment]
You don't have a `.catch(...)` handler on the outer `connect(...)` call so a connection error becomes an unhandled promise rejection.

Instead of manually managing clients via `connect(...)` and `release(...)`, you'll have an easier time using `pool.query(...)`: https://node-postgres.com/api/pool#pool-query

**Comment by ermarkar** [comment]
I have added 

module.exports = {
    query: (query, callback) => {
        console.log(query);
        pool.connect().then(client => {
            return client.query()
                .then((result) => {
                    client.release();
                    console.log(result.rows)
                    callback(null, result.rows[0]);
                })
                .catch(err => {
                    client.release();
                    callback(err, null);
                });
        }).catch(err=>{
            console.log("Issue",err)
        })
    }
}

Then I got this error:

Issue TypeError: Cannot read property 'submit' of undefined
    at Client.query (D:\PROJECTS\PuWifi\GitHubForHeroKu\PuWifi\node_modules\pg\lib\client.js:368:21)
    at pool.connect.then.client (D:\PROJECTS\PuWifi\GitHubForHeroKu\PuWifi\src\db\db-connect.js:26:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by charmander** [comment]
```js
return client.query()
```

You didn’t pass the query here.

**Comment by ermarkar** [comment]
Oh thanks :)
