### ISSUE TITLE
client.query is not a function

### ISSUE THREAD

**Issue by prtome** [brianc/node-postgres#1599]
Hello,
I am obviously missing something. I am moving from connect to pool
I am doing something wrong here. since I get the error: client.query is not a function.

        var pg = require('pg');
        const pgPool = require('../middleware/db');
then in the route  

       const client =  pgPool.connect();
       var myQuery = "select AddAccount($1,$2,$3,$4)";
       var hash = bcrypt.hashSync(req.body.password, 10);
      try {
          const result =  client.query(myQuery,[req.body.dbname,req.body.nurschema,req.body.nurschema,hash]); ////// HERE THE ERROR
         client.release();
         if(result.rows[0]['AddAccount'] == 1) {
               return res.render("enter_super",  {success: "user registered."});
         } else {
              return res.render("enter_super", {erreur: "Sorry. Schema does not exists."});
         }
       } catch(err){
            return res.render("enter_super", {erreur: "Sorry. That username already exists. Try again."});
       }

I know the connection works, since I am using also postgres to store the sessions, and the table fills, so my db.js correctly connects to the db. What am I missing ? thanks for your help.

**Comment by charmander** [comment]
`pgPool.connect()` returns a promise; so does `client.query()`. In this case, you can also replace all the connection management with a single `pgPool.query()` call.

Using the asynchronous version of `bcrypt.hash` would be a good idea too. `hashSync` means not being able to handle any other requests in the same process for the duration of the hashing.
