### ISSUE TITLE
unix socket

### ISSUE THREAD

**Issue by brianc** [brianc/node-postgres#16]
better support & documentation for connecting to PostgreSQL server via unix socket

**Comment by tematema** [comment]
How I can use unix domain sockets instead of TCP to connect now?

**Comment by Lekensteyn** [comment]
@tematema Use a connection object and specify the directory to the Unix domain sockets. See above examples and the note at https://github.com/brianc/node-postgres/wiki/pg#pgdefaultshost

**Comment by jasonpolites** [comment]
The wiki has changed since the last comment here was posted, and the new docs don't seem to make any mention of using a socket path.  Is there an updated reference somewhere?

**Comment by charmander** [comment]
@jasonpolites It appears to be missing from the new documentation. The option is `host`, anyway:

```js
const pool = new pg.Pool({
    host: '/var/run/postgresql',
});
```

**Comment by jasonpolites** [comment]
Ack.  Thanks!
