### ISSUE TITLE
Query queue should be cleaned on client.end()?

### ISSUE THREAD

**Issue by arichiardi** [brianc/node-postgres#1600]
Hello, I am having the dreaded lambda hanging-after-a-query issue.

Basically, my code executes the query, which resolves fine, then calls `.end()` on the client in order to free up resources and wipe the event loop that otherwise would be considered "active" by AWS, which won't return.

There is a hackish solution to this problem, I would say a workaround, but I wanted to understand what in the event loop is still active.

It seems from [here](https://github.com/brianc/node-postgres/blob/master/lib/client.js#L397) that `queryQueue` is never flushed/emptied/drained.

This is a wild guess but maybe it needs to be?

**Comment by charmander** [comment]
Can you show a minimal example of a script that doesn’t exit after `.end()`, please?

**Comment by arichiardi** [comment]
Sure, something like this, pseudo-code, I am using it from ClojureScript:

```javascrept
var client = new Client()
client.connect()
  .then(() => client.query(stmt, params))
  .then((data) => {
      client.end()
      return data
 }
```

I am still debugging if I am doing something wrong on my side. The query itself takes 30-40 ms but the lambda returns after 8s.

**Comment by arichiardi** [comment]
Sorry after profiling it seems like the `.connect()` call is the one giving me problems:

```
{
    "pid": 1,
    "level": 30,
    "elapsed-ms": "8063.693584",
    "tag": "db-connection",
    "msg": "elapsed time: 8063.693584 msecs",
    "time": "2018-03-28T19:33:41.317Z",
    "v": 0
}
```

**Comment by sehrope** [comment]
That code doesn't handle errors. If the query has an issue then `client.end()` will never be called. If you're going to be manually managing connections (and you kind of have to in a Lambda as pools will have other issues), you need to ensure it get closed regardless of the outcome of the `.query(...)` calls.

**Comment by arichiardi** [comment]
That is not the issue, as I am handling the errors elsewhere, but thanks for sharing. I think this issue is misnamed and it looks like unrelated to `node-postgres`. Please allow some more time for further debugging

**Comment by arichiardi** [comment]
I think this issue can be closed, I will open a new one in case. It seems that the original problem was not actually the problem :smile: Thanks for answering so quickly though!
