### ISSUE TITLE
one connection multiple parallel transactions

### ISSUE THREAD

**Issue by zhuming** [brianc/node-postgres#1609]
I create one transaction by query('BEGIN'), and within this transaction, I will have a promiseChain1, where in each step, a sql will be executed. the last step is to do a query('COMMIT'), and catch(err=>query('ROLLBACK'))

psuedo code: BEGIN.then(SQL1_1).then(SQL1_2).then(SQL1_3).then(COMMIT).catch(ROLLBACK)

And I will create another transaction by query('BEGIN') again, and similar to the previous one, another promiseChain2 will be created, similar to the previous one. pseudo code: BEGIN.then(SQL2_1).then(SQL2_2).then(COMMIT).catch(ROLLBACK)

The last thing I will do is to call Promise.all([promiseChain1, promiseChain2]).then(...)

depending on the time of each sql statement execution takes, order of the two BEGINs, two COMMITs/ROLLBACKs and other sql statements from both chains may be random, right?
<pre>
BEGIN
SQL1_1
        BEGIN
SQL1_2
        SQL2_1
        SQL2_2
        COMMIT
SQL1_3
ROLLBACK
</pre>
But since two "transactions" are actually using the same connection, I think the result will be very different than what I expect.
In this case, SQL1_1, SQL1_2, SQL2_1 and SQL2_2 will be committed, but SQL1_3 will be rolled back.

**Comment by charmander** [comment]
> But since two "transactions" are actually using the same connection, I think the result will be very different than what I expect.

Yes, it won’t work. (If the transactions overlap, the second `BEGIN` and the second `COMMIT` or `ROLLBACK` will do nothing.) You would need to use two connections.
