### ISSUE TITLE
citext[] not deserialized

### ISSUE THREAD

**Issue by rbaumier** [brianc/node-postgres#1620]
Hello!

```
create extension if not exists citext;
create table tb(field citext[]);
insert into tb(field) values(array['a','b']);
```
on node, running a simple select, we get..
```
[{ field: '{a,b}' }]
``` 
..as a result, where..
```
[{ field: [ 'a', 'b' ] }]
```` 
..would be expected (I guess).

**Comment by sehrope** [comment]
The default handling for a datatype that doesn't have an explicit parser is to return back the text representation of the type. As citext isn't a core type (it's part of the contrib extension) it doesn't have a fixed OID so there isn't a parser pre-registered for it. See https://github.com/brianc/node-pg-types/pull/5 for the same issue but regarding hstore (another contrib module).

If you want it automatically handled you'll need to determine the OID of the citext and citext[] types and register the array parsers for them manually. It *may* vary from database to database as the assigned OID depends on the order the extension was installed so having it be truly dynamic by looking up the OID at runtime and then registering it dynamically is likely your best bet.

**Comment by hi2u** [comment]
@rbaumier How did you go about solving this?

The different OID values is an issue across different servers.

But even when I try hard-coding the OID for a specific server like:

```typescript
types.setTypeParser(17464, (val: string) => {
    // this function never runs
});
```

It never actually runs my formatter.  If I hard code other numbers like 1184 for a regular (non-array) TIMESTAMPTZ it does work for them.

I'm using Knex, which itself uses pg, not sure if/why that would change anything here though.

But ideally, I'd love some solution that doesn't require hard-coded OIDs (or needing to look them up at runtime).
