### ISSUE TITLE
DeprecationWarning: Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by merlinpatt** [brianc/node-postgres#1624]
I get this DeprecationWarning after getting what seems to be a disconnection error.

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: getaddrinfo ENOENT localhost 5432
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

Is this something I need to be handling since this seems to be a connection issue? Or does this need to be handled internally in the node-postgres library?

If I need to be handling it, how do you suggest I handle disconnections?

**Comment by charmander** [comment]
pg doesn’t use promises internally; you may have a `.connect()` or `.query()` somewhere missing error handling (a `.catch()` that produces an error response, logs the error, propagates it somewhere else, …).

**Comment by JonathanFu** [comment]
Hi @merlinpatt,
@charmander is right, you need to add handle for `.connect()`.

I notices there are several similar questions for this issue.
Sadly, all official docs don't mention catching the connection error in `.connect()`. 
All docs for `.connect()` are below styles which is a bit misleading. 

```js
const { Client } = require('pg').Client
const client = new Client()
client.connect()
client.query('SELECT NOW()')
  .then(result => console.log(result))
  .catch(e => console.error(e.stack))
  .then(() => client.end())
```

For this error, you can do the following way to catch both connection and query error.
```js
const { Client } = require('pg').Client
const client = new Client()
client.connect().then(
  () => client.query(query))
 .then(res => {
    console.log(res.rows) 
  })
 .catch(e => {
    console.error(e.stack)
  })
.then(() => client.end())
```
