### ISSUE TITLE
Docs: Getting Started: Wrap await code in async IIFE

### ISSUE THREAD

**Issue by anishkny** [brianc/node-postgres#1629]
Before:
```
const { Client } = require('pg')
const client = new Client()

await client.connect()

const res = await client.query('SELECT $1::text as message', ['Hello world!'])
console.log(res.rows[0].message) // Hello world!
await client.end()
```

After:
```
const { Client } = require('pg')
const client = new Client()

(async () => {
  await client.connect()
  
  const res = await client.query('SELECT $1::text as message', ['Hello world!'])
  console.log(res.rows[0].message) // Hello world!
  await client.end()
})();
```

Meta: Are the docs open sourced? Do you accept fixes from the community?

**Comment by charmander** [comment]
> Meta: Are the docs open sourced?

They aren’t yet.

**Comment by anishkny** [comment]
Great! Closing in favor of https://github.com/brianc/node-postgres-docs/pull/87

**Comment by chris-trotter** [comment]
FYI the code here is wrong. A semi colon needs to be added before the async function is invoked.  See https://github.com/brianc/node-postgres-docs/commit/a9bbef8fa5cc71e795e5b17c2cbd87401dd4af90
