### ISSUE TITLE
Unnable to connect to PostgreSQL from NodeJS

### ISSUE THREAD

**Issue by MinionAttack** [brianc/node-postgres#1632]
I am trying to connect to a PostgreSQL database and make some queries but I'm unable to make it works. Looking at the [Documentation](https://node-postgres.com/guides/upgrading#client-query-submittable-) I'm trying this method:

```
const { Client, Query } = require('pg');

...........

let client = new Client(connectionString);
client.connect();
const query = client.query(new Query('SELECT ST_GeometryType($1) FROM $2.$3 LIMIT 1', [column, schema, tableName]));
console.log(JSON.stringify(query, null, 2)); //Debug purposes
query.on('row', (row) => {
    switch (row[0]) {
        case 'ST_LineString':
            geometryValue = 'LineString';
            break;
        case 'ST_MultiLineString':
            geometryValue = 'MultiLineString';
            break;
        case 'ST_Polygon':
            geometryValue = 'Polygon';
            break;
        case 'ST_MultiPolygon':
            geometryValue = 'MultiPolygon';
            break;
        case 'ST_Point':
            geometryValue = 'Point';
            break;
        case 'ST_MultiPoint':
            geometryValue = 'MultiPoint';
            break;
        default:
            break;
    }
});
query.on('end', (res) => {
    if(result.rows[0] === undefined){
        console.log('No data retrieved from DB');
    }
    client.end();
});
query.on('error', (res) => {
    console.log("Something went wrong: " + res);
});
```

Debugging, I can see that on query the values are stored fine:

```
{
  "text": "SELECT ST_GeometryType($1) FROM $2.$3 LIMIT 1",
  "values": [
    "column",
    "schema",
    "table"
  ],
  "portal": "",
  "_result": {
    "command": null,
    "rowCount": null,
    "oid": null,
    "rows": [],
    "fields": [],
    "_parsers": [],
    "RowCtor": null,
    "rowAsArray": false
  },
  "_results": {
    "command": null,
    "rowCount": null,
    "oid": null,
    "rows": [],
    "fields": [],
    "_parsers": [],
    "RowCtor": null,
    "rowAsArray": false
  },
  "isPreparedStatement": false,
  "_canceledDueToError": false,
  "_promise": null,
  "domain": null,
  "_events": {},
  "_eventsCount": 0
}
```

I've executed the query on pgAdmin/CLI an works fine, returning the desired result that I'm expecting but seems that trying to execute the query on the script doesn`t works.

What I'm missing? Thanks.

**Comment by charmander** [comment]
Parameters represent values, not identifiers (like column, schema, or table names). You need to put those directly into the query by string concatenation:

```javascript
const { Client } = require('pg');

(async () => {
    let client = new Client({ connectionString });
    await client.connect();

    let result = await client.query(
        `SELECT ST_GeometryType(${column}) FROM ${schema}.${tableName} LIMIT 1`);
    let row = result.rows[0];
    // ⋮
})();
```

making sure, of course, that the values of each originate from your program and not from input. (Use `client.escapeIdentifier(…)` if you need to accept arbitrary names from a privileged source.)

**Comment by MinionAttack** [comment]
Thanks for the answer, I've tried your suggestion but it isn't works. I'm going to see if there is a problem with my environment.

Regards.

**Comment by charmander** [comment]
> but it isn't works

Does that mean it throws an error, or…?

**Comment by MinionAttack** [comment]
No error its throw:

```
async function CheckGeometryType(tableName, column) {

    const schema = 'schema';
    let geometryValue = undefined;
    const connectionString = 'postgres://user:pass@host:port/db';

    let client = new Client(connectionString);
    await client.connect();
    console.log('Before');
    let result = await client.query(`SELECT ST_GeometryType(${column}) FROM ${schema}.${tableName} LIMIT 1`);
    console.log('After');
    console.log(JSON.stringify(result, null, 2));
    switch (result.rows[0]) {
        case 'ST_LineString':
            geometryValue = 'LineString';
            break;
        case 'ST_MultiLineString':
            geometryValue = 'MultiLineString';
            break;
        case 'ST_Polygon':
            geometryValue = 'Polygon';
            break;
        case 'ST_MultiPolygon':
            geometryValue = 'MultiPolygon';
            break;
        case 'ST_Point':
            geometryValue = 'Point';
            break;
        case 'ST_MultiPoint':
            geometryValue = 'MultiPoint';
            break;
        default:
            break;
    }

    await client.end();

    return geometryValue;
}
```
The function it's called inside a _For_ loop. None of the _console.log()_ are printed, and the console doesn't shows any error.

**Comment by sehrope** [comment]
If nothing is being printed at all then maybe check the invocation of the function to ensure that you're issuing an await on the result and wrapping it in a try/catch to see if any errors are silently being ignored.

The `result.rows[0]` is referencing the entire first row as an array, not the value of the first column of that row.  You need to either use array mode or give the queried column a name that can be referenced:

```
const sql = `
    SELECT ST_GeometryType(${client.escapeIdentifier(column)}) AS geo_type
    FROM ${client.escapeIdentifier(schema)}.${client.escapeIdentifier(tableName)}
    LIMIT 1`
const result = await client.query(sql);
if (result.rows.length === 0) {
    return null;
}
const geoType = result.rows[0].geo_type;
switch(geoType) {
    // ...
}
```

**Comment by MinionAttack** [comment]
Thanks for the answer @sehrope , I've cheked on the for loop with a simple:

```
console.log('In');
classTypeParsed = CheckGeometryType(tableName, fieldName);
console.log('Out');
```
And the console prints both messages. But inside the function, the only print I can do it's before:

`let result = await client.query.....`

I've surrounded the code with a try/catch to see if there is any error but nothing it's throw, even I have changed:

`if (result.rows.length === 0) {
    return null;
}`

to this:

```
if (result.rows.length === 0) {
   throw 'No data retrieved from DB';
}```

But nothing it's shown.

**Comment by sehrope** [comment]
You need to await the result of the `CheckGeometryType(...)` call:

```
console.log('In');
// Add "await" here:
classTypeParsed = await CheckGeometryType(tableName, fieldName);
console.log('Out');
```

**Comment by sehrope** [comment]
And it's usually a good idea to throw actual Errors, not strings:

```
throw new Error('No data received from DB');
```

**Comment by MinionAttack** [comment]
So this means, I've to make `async` all the functions? Because the for it's on a function (A1), and to can put `await` I need make it `async`, so the function (A2) where I call (A1) have to be `async` also an so on. Or there is a way to avoid this?

P.D: I'm learning nodejs by myself, sorry for the dummy questions.

**Comment by sehrope** [comment]
Async functions return Promises that you can invoke `.then(...)` or `.catch(...)` on to handle the result. The caller either needs to be async (so that they can "await" the Promise) or the return value needs to be handled directly as a Promise. I'd suggest reading up a bit more on Promises as it'll make async more clear as well.

**Comment by MinionAttack** [comment]
Ok, thanks!
