### ISSUE TITLE
Cannot use a pool after calling end on the pool

### ISSUE THREAD

**Issue by sarathjasrin** [brianc/node-postgres#1635]
I'm using pg in **aws lambda**. If I run a query it's running on first time.  Then the second try it's giving above error.
Should I leave pool without end .

```
const { Pool }=require("pg");
const pool=new Pool({
    host:"xyz.rds.amazonaws.com",
    user:"sarath",
    password:"abcd",
    database:"company",
    port:5432
});
```

```
Database(query, data) {
        return new Promise((resolve, reject) => {
            pool.query(query,data,(err,res)=>{
                pool.end();
                if(err) return reject(err);
                return resolve(res);
            });

        });
    }
```

**Note:** It's working as expected in my local machine.

**Comment by charmander** [comment]
>  Should I leave pool without end .

Yes. Only end the pool when you no longer intend to use it. `pool.query` also already returns a promise:

```javascript
Database(query, data) {
    return pool.query(query, data);
}
```

**Comment by sarathjasrin** [comment]
@charmander  it's working fine with local machine. Not on the AWS Lambda. I tried without ending the pool but function exited with error

`Task timed out after 10.01 seconds`

**Comment by charmander** [comment]
@sarathjasrin You have to end the pool, but not before you’re done making queries.

**Comment by sarathjasrin** [comment]
@charmander I'm ending the pool after the query run. 
The problem is using the lambda. I'm calling the lambda through the API Gateway. I'm getting the result at the first call from the second call it's giving the above error.

**Comment by thanhlevu** [comment]
just uncomment it:         //pool.end();

**Comment by benjie** [comment]
I haven't tried this (I don't really use Lambda); but my guess would be that you could use the `callbackWaitsForEmptyEventLoop: false` setting on your Lambda and leave the pool open. This way the next request can benefit from the pool being available already (potentially even with a warm client) but Lambda can send the result without waiting for the client/pool to be released. Be careful that you're not doing any other background work through, as that could be aborted.

https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html

**Comment by ngervasi** [comment]
I confirm: `callbackWaitsForEmptyEventLoop: false` is the way to go.
