### ISSUE TITLE
Parameterized query with crosstab / tablefunc

### ISSUE THREAD

**Issue by bergur** [brianc/node-postgres#1637]
Hi

I am having trouble using parameters in my crosstab query. The code is as follows.

```javascript
const sql = `SELECT * FROM crosstab('
    SELECT timabil, stettarfelag, heildarlaun AS laun
    FROM medaltol WHERE flokkur = $1 AND stettarfelag in (40,41,42)
    ORDER BY 1,2;
')
AS medaltol(timabil character(6), "40" integer, "41" integer, "42" integer)`            
        
const params = ['SAMTALS'];

return pool.query(sql, params).then(res => res.rows);
```
Error I get is 

> bind message supplies 1 parameters, but prepared statement "" requires 0

Edit: I realize that the parameter of crosstab function is a string, but shouldn't I avoid string concatenation. Is this approach safe?

```javascript
const sql = `SELECT * FROM crosstab('
    SELECT timabil, stettarfelag, heildarlaun AS laun
    FROM medaltol WHERE flokkur = ${flokkur} AND stettarfelag in (40,41,42)
    ORDER BY 1,2;
')
AS medaltol(timabil character(6), "40" integer, "41" integer, "42" integer)`            
        
const params = [];

return pool.query(sql, params).then(res => res.rows);
```

**Comment by sehrope** [comment]
You can't use parameters with `crosstab(...)`. You'll need to add the values into the SQL itself. 

Make sure to escape the parameter values as literals prior to concatenation. The pg-format (https://www.npmjs.com/package/pg-format) module might be helpful for this.

**Comment by bergur** [comment]
Thank you for your answer.
