### ISSUE TITLE
Postgres queries using the 'IN' operator return an empty result set

### ISSUE THREAD

**Issue by wmelton** [brianc/node-postgres#1642]
Executing this query returns an empty result set: 

`SELECT object_id FROM public."Events" WHERE parent_id = $1 AND object_id IN ($2) GROUP BY object_id`

This is the code executing: 

`const ids = "'15370eac-bfc4-4f91-931c-bbd87307695d','bbc5b779-4fdc-40b5-ba8b-aa3c0da90356','cc222ff9-a721-440d-aae6-0aa225c2b3a4'";`

`const items = await pgPool.query(
            "SELECT object_id FROM public.\"Events\" WHERE parent_id = $1 AND object_id IN ($2) GROUP BY object_id",
            [parent_id, ids]
          );`

This is the result: 

`Result {
  command: 'SELECT',
  rowCount: 0,
  oid: null,
  rows: [],
  fields:
   [ Field {
       name: 'object_id',
       tableID: 20737,
       columnID: 4,
       dataTypeID: 1043,
       dataTypeSize: -1,
       dataTypeModifier: 259,
       format: 'text' }],
  _parsers:
   [ [Function: noParse],
     [Function: parseBigInteger],
     [Function: parseBigInteger] ],
  RowCtor: null,
  rowAsArray: false,
  _getTypeParser: [Function: bound ] }`

I have verified it is not a formatting issue as I have tried creating a string representation of the array list with and without implict quotations. E.g.: 

`'15370eac-bfc4-4f91-931c-bbd87307695d','bbc5b779-4fdc-40b5-ba8b-aa3c0da90356','cc222ff9-a721-440d-aae6-0aa225c2b3a4'`

vs 

`15370eac-bfc4-4f91-931c-bbd87307695d,bbc5b779-4fdc-40b5-ba8b-aa3c0da90356,cc222ff9-a721-440d-aae6-0aa225c2b3a4`

I have verified that if executed directly against the db via a Postgres client in query format the correct result set is returned.

**Comment by wmelton** [comment]
As additional information, if (for debug purposes) you paste the list in to the query, the result from pg is correct. E.g. 

`const items = await pgPool.query( "SELECT object_id FROM public.\"Events\" WHERE parent_id = $1 AND object_id IN ('15370eac-bfc4-4f91-931c-bbd87307695d','bbc5b779-4fdc-40b5-ba8b-aa3c0da90356','cc222ff9-a721-440d-aae6-0aa225c2b3a4') GROUP BY object_id", [parent_id] )`

**Comment by sehrope** [comment]
The issue is that $2 in your query is being passed as the entire string. It's not being interpreted as an array. That means that the `IN (...)` clause is looking for an id that matches concatenated comma separated values which, it doesn't find, so hence no rows returned.

Try this:

```
const ids = ['15370eac-bfc4-4f91-931c-bbd87307695d','bbc5b779-4fdc-40b5-ba8b-aa3c0da90356','cc222ff9-a721-440d-aae6-0aa225c2b3a4'];

const items = await pgPool.query( "SELECT object_id FROM public.\"Events\" WHERE parent_id = $1 AND object_id = ANY($2::uuid[]) GROUP BY object_id", [parent_id, ids] );
```

The parameter has been changed to an array and the `IN (...)` has been changed to a `= ANY(...)` with the $2 parameter explicitly cast as a uuid array.

**Comment by wmelton** [comment]
Our column is defined as varchar(255) so modifying your recommendation worked for us: 

`'SELECT object_id FROM public.\"Events\" WHERE parent_id = $1 AND object_id = ANY($2) GROUP BY object_id", [parent_id, ids]'`

Thanks for your help and incredibly fast response!
