### ISSUE TITLE
Getting error connection slots are reserved for web service application

### ISSUE THREAD

**Issue by adviner** [brianc/node-postgres#1643]
I'm having a problem with my node/express web application.  When I run a certain page and pressing the button to get the data over and over,
eventually, I get an error:

remaining connection slots are reserved for non-replication superuser connections

I've seen this error when I run it as a normal script.  But the fix to it was just to call pool.end() and that resolved my problem.
But pool.end() isn't recommended for web services.  I can increase my connection in Postgres but was wondering if there is another solution before I do that?

In my index.js (express app). I initialize my function

const DBContext = require('./commons/pg_context');
...
...
const dbPool = new Pool(nconf.get(`${process.env.NODE_ENV}:pool_config`));
const dbContext = DBContext(dbPool);

Code: pg_context.js

module.exports = (db_context) => {

	let context = db_context;

	const api = {

		query: async (sql, params = []) => {

			const client = await context.connect();

			try
			{
				const res = await client.query(sql, params);
				return res;

			}
			catch(err){
				throw new Error(err);
			}
			finally{
				client.release();
			}
		}
	}
	
	return api;
}

Here is an example of a function that uses the query;

userAppPermission: async(dbContext, application_id, account_id) => {

	let parameters = [];
	let sql = '';

	try
	{
		const misc = options.misc;

		parameters = [application_id, account_id];
		sql = `select *
					from access.user_application_access
					where application_id = $1 and account_id = $2`;

		const resp = await dbContext.query(sql, parameters);
		if(!resp.is_enabled)
			throw new Error('User is not enabled for application');

		return {
			is_admin: resp.is_admin
		}

	}
	catch(err){
		log.error(`access.userAppPermission \r\n${err}\r\n${sql}\r\n${JSON.stringify(parameters)}\r\n`);
		throw new Error(err.message);	
	}

}

Here in my config file:

"venuePool": {
"user": "some user",
"database": "some database",
"password": "some password",
"host": "some host",
"port": 5432,
"ssl": false,
"max": 20,
"min": 4,
"idleTimeoutMillis": 30000

**Comment by charmander** [comment]
You should make sure the pool’s `max` is attainable. Lower it from 20 if it isn’t possible for the app to have 20 connections open.

Also, `Pool` objects already have a `query`:

```js
const api = {
	query: (sql, params) => context.query(sql, params),
};
```

**Comment by adviner** [comment]
Thanks for the information.  Quick question in your example.  Does it mean that neither:

const client = await context.connect();
client.release();

have to be called anymore?
I was just looking at the example in the documents and it has a section on single queries:

Single query

const { Pool } = require('pg')

const pool = new Pool()

pool.query('SELECT * FROM users WHERE id = $1', [1], (err, res) => {
  if (err) {
    throw err
  }

  console.log('user:', res.rows[0])
})


Using the example you gave me what happens if I use it for several queries and release is not called:

const resp1 = await dbContext.query("some sql 1", parameters);
const resp2 = await dbContext.query(s"some sql 2", parameters);
const resp3 = await dbContext.query("some sql 3", parameters);

I'm asking because it states:

If you don't need a transaction or you just need to run a single query,

Thanks

**Comment by charmander** [comment]
Right, `pool.query(…)` is the equivalent of `pool.connect()`, `client.query(…)`, and `client.release()`.
