### ISSUE TITLE
How to insert multiple rows with array field in a single query?

### ISSUE THREAD

**Issue by Shekhrozx** [brianc/node-postgres#1644]
My table fields are like that:
`id: pk integer`
`name: text`
`info: integer[]`
I am gonna insert multiple rows in a single query. 
```
client.query(
    "INSERT INTO mytable (name, info) SELECT * FROM UNNEST ($1::text[], $2::int[])",
    [
         ["John", "Adam", "Mark"],
         [[1,2,3,4], [2,3,5,4],[4,4,5,8]]
    ]
)

```
But I got the error:
`     error: column "info" is of type integer[] but expression is of type integer.  `
How can I do this?

**Comment by Shekhrozx** [comment]
I tried to do that way` $2::int[][]`. But it gave the same error.

**Comment by charmander** [comment]
Sorry, I forgot that PostgreSQL doesn’t have arrays of arrays. (Kind of an important thing to forget.) pg-format might work, as described in https://github.com/brianc/node-postgres/issues/957#issuecomment-200000070. Other than that… there’s manual string conversion, which is not very nice:

```js
client.query(
    "INSERT INTO mytable (name, info) " +
        "SELECT name, info::int[] FROM UNNEST ($1::text[], $2::text[]) AS t (name, info)",
    [
         ["John", "Adam", "Mark"],
         [[1,2,3,4], [2,3,5,4],[4,4,5,8]].map(a => '{' + a + '}')
    ]
)
```

**Comment by gajus** [comment]
See:

* https://github.com/gajus/slonik#sqlunnestlist
* https://github.com/gajus/slonik#slonik-recipes-inserting-large-number-of-rows

**Comment by retorquere** [comment]
@charmander will that work when one of the elements within the array has quotes (either double or single or both)?

**Comment by charmander** [comment]
@retorquere No, that example was specific to `int`s. If you want text, you could use `require('pg/lib/utils').prepareValue`, which includes this more versatile array encoding: https://github.com/brianc/node-postgres/blob/5a92ba3701e576b91697e653c6c369500811e9e5/lib/utils.js#L14-L43

Passing a JSON parameter might be a better choice.

**Comment by retorquere** [comment]
I settled on a JSON parameter, works nicely.

Any chance that at some point it'd just be possible to insert multiple semi-colon separated statements in one query?

**Comment by charmander** [comment]
That’s already possible when there are no parameters. With parameters, no; pg doesn’t parse queries.

**Comment by retorquere** [comment]
Could I use node-postgres to make a parametrized query into a flat string; concat a bunch together, and then send those in one go?

**Comment by charmander** [comment]
You could use a combination of `prepareValue` and [pg-format][] to do that.

[pg-format]: https://www.npmjs.com/package/pg-format

**Comment by charmander** [comment]
@Nielsbishere The cast from `text` is necessary:

```sql
SELECT ints::smallint[] FROM unnest ($1::text[]) AS t (ints)
```

My guess is that this will never be added to pg, because it’s not something that’s missing from pg.

**Comment by charmander** [comment]
Generic answer to the original question using JSON:

```js
client.query(
    `INSERT INTO mytable (name, info)
     SELECT name, info FROM jsonb_to_recordset($1::jsonb) AS t (name text, info int[])`,
    [
        JSON.stringify([
            {name: "John", info: [1, 2, 3, 4]},
            {name: "Adam", info: [2, 3, 5, 4]},
            {name: "Mark", info: [4, 4, 5, 8]},
        ]),
    ]
)
```
