### ISSUE TITLE
Syntax error when using SET with bindings

### ISSUE THREAD

**Issue by joelmukuthu** [brianc/node-postgres#1648]
Hi,

I'm running into an error when running:

```js
client.query({ 
  text: 'SET "foo.foo" = $1', 
  values: ["foo"] 
}); // syntax error at or near "$1"
```

but this passes:

```js
client.query(`SET "foo.foo" = 'foo'`);
```

Full code to reproduce:

```js
const { Pool } = require('pg'); // version 7.4.3
const pool = new Pool(); // configured via env variables

const foo = async () => {
  const client = await pool.connect();
  await client.query({ text: 'SET "foo.foo" = $1', values: ["foo"] });
};

foo().catch(console.log);
```

Is this expected or am I doing something wrong?

**Comment by charmander** [comment]
That’s expected; you can’t prepare `SET` commands. (They don’t really accept a value in that way, either – see *value* at https://www.postgresql.org/docs/current/static/sql-set.html#id-1.9.3.167.6.) An alternative is to use `client.escapeLiteral`, since string constants are supported syntax:

```javascript
client.query('SET "foo.foo" = ' + client.escapeLiteral("foo"))
```

**Comment by joelmukuthu** [comment]
Great, thanks for the explanation!
