### ISSUE TITLE
Using graphql on large result errors out

### ISSUE THREAD

**Issue by adviner** [brianc/node-postgres#1650]
I'm using the following in a web application
node 10.10
postgres 10
OS: Windows/Linux

I'm using the following code to make my queries:

File: index.js
const dbPool = new Pool(nconf.get(`${process.env.NODE_ENV}:venuePool`));
const dbContext = DBContext(dbPool);

let options = {
    dbContext: dbContext,
    ...
}

app.use('*', (request, response, next) => {
req.venue = options;
next();
});

Then in the grapql I pull the options.dbContext to use select1(), select() etc

File: pg_context.js

module.exports = (db_context) => {

	let context = db_context;

	const api = {

		select1: async(sql, params = [])  => {
			try
			{
				const res = await context.query(sql, params);
				if(res !== undefined && res.rows.length > 0)
					return res.rows[0];
				else
					throw new Error('No entry found');
			}
			catch(err){
				throw new Error(err);
			}
		},

		select: async(sql, params = [])  => {

			try
			{
				const res = await context.query(sql, params);
				if(res !== undefined)
					return res.rows;
				else
					throw new Error('No entry found');
			}
			catch(err){
				throw new Error(err);
			}
		}	
	}
}		

My database config params:

            "ssl": false,
            "max": 200,
            "idleTimeoutMillis": 1000,
            "connectionTimeoutMillis": 10000

My postgres conf (using pgtune)

	max_connections = 200
	shared_buffers = 512MB
	effective_cache_size = 6GB
	maintenance_work_mem = 512MB
	checkpoint_completion_target = 0.7
	wal_buffers = 16MB
	default_statistics_target = 100
	random_page_cost = 1.1
	work_mem = 13107kB
	min_wal_size = 1GB
	max_wal_size = 2GB

my graphql query:

	query Q($first_name:String!, $last_name:String!,
			$initial_book_date_option:String!, $order_by:JSON!){   
		
	  queryInmates(first_name:$first_name, last_name:$last_name){
		id, first_name, last_name, middle_name, sex
		jail_inmate{
		  id, inmate_id, number, release_date,
		  jail_bookings(initial_book_date_option:$initial_book_date_option,
		  order_by:$order_by){
			id, number, initial_book_date, current_intake_date, release_date
		  }
		}
	  }
	}

So this return a large result and the first set of the result has data, but eventually, the data will have errors in the array.

ex:

    {
      "message": "Error: Error: connect ECONNREFUSED 127.0.0.1:5432",
      "locations": [
        {
          "line": 6,
          "column": 5
        }
      ],
      "path": [
        "queryInmates",
        243,
        "jail_inmate"
      ]
    },
     {
        "id": "f29874d0-5202-11e8-b048-17a13476491e",
        "first_name": "KIRSTI ANNE",
        "last_name": "QUINTANAR",
        "middle_name": "ELIZABETH",
        ...
     }

I thought that const res = await context.query(sql, params);
would automatically return to the pool.  Am I missing anything?  Am I not using the pool correctly, since this seems to be the issue of running out?  I'm only using one Pool() instance for all web request.  Should I make a new instance for each web request?

 I even tried using the promise with the same results example:

		select1: async (sql, params = []) => {

			return new Promise((resolve, reject) => {
			
		        context.connect((err, client, done) => {

		            if (err) {

		            	done();
		                reject(err.message);

		            } else {

		                client.query(sql, params, (err, results) => {

		                	client.release();

		                    if (err) {
		                        reject(err.message);
		                    } else {
								if(results !== undefined && results.rows.length > 0)
									resolve(results.rows[0]);
								else
									reject('No entry found');
		                    }
		                });
		            }
		        });
			});
		},

For the sake of testing I increased postgres 
max_connections = 1000 and node pg "max": 1000
I get less of the ECONNREFUSED.

**Comment by adviner** [comment]
OK, I modified my express app to make sure that for each request only one Pool() is created.
I add to the request a variable called venue.dbInmateDataExchangeContext 
I check if the object is null:
                                let dbContext  = null;
				if(ast.venue.dbInmateDataExchangeContext === null){
					
					dbContext = await misc.dbConnection('inmateDataExchangePool');
					ast.venue.dbInmateDataExchangeContext = dbContext;
				}
				else
					dbContext = ast.venue.dbInmateDataExchangeContext;

If it is then I create an instance and assign it back to the request variable venue.dbInmateDataExchangeContext 

All the other methods I use have the same logic inside to get the connection.   I also put a log in the if statement, to identify which method needed to create a new Pool().  So when I look at the log file I see that only the first call creates an instance of the Pool.  All the other functions called from the initial function are using the instance already created.  Basically, all the other methods are using dbContext from the else statement.

I do it only once and restart the server just to make sure there are no dangling instances.  But I still get the exact error.  I'm at a loss on why my single test is running out of connection?
If anyone can give me any tips or ideas in figuring this out, please.

**Comment by adviner** [comment]
Update, I stuck pgBouncer in front of postgres and using that.  I no longer have any pooling issues.

**Comment by charmander** [comment]
> My database config params:
>
> ```javascript
>         "ssl": false,
>         "max": 200,
>         "idleTimeoutMillis": 1000,
>         "connectionTimeoutMillis": 10000
> ```

If `max_connections` is the same as the pool max, any connections coming from elsewhere will cause problems. Does setting this to the pg default of 10 stop the errors?

> I'm only using one Pool() instance for all web request. Should I make a new instance for each web request?

One instance for all requests is correct.

**Comment by adviner** [comment]
Originally I had the max at only 50 but was encountering the errors.  I just kept increasing as I kept playing with the values.
