### ISSUE TITLE
pooled query takes twice as long

### ISSUE THREAD

**Issue by S2-** [brianc/node-postgres#1654]
version of Node: v8.11.2
version of Postgres: PostgreSQL 9.5.12 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609, 64-bit 

I have a strange problem with pooled queries:
The query is quite complicated and takes about 1 and ½ seconds to execute on my little postgres server.
When I execute the query with pgAdmin it takes 1.5 seconds. When I execute the query with `client.query(q...` it takes 1.5 seconds, but when I execute the query with `pool.query(q, ...` it takes a lot more.
I made a little testcase to test this, because I can't understand why this happens.

```
var Client = require('pg').Client;
var Pool = require('pg').Pool;

var pgpool = new Pool({
	user: 'n3wz',
	password: 'x',
	host: 'localhost',
	database: 'n3wz',
	max: 10, // max number of clients in pool
	min: 4,
	idleTimeoutMillis: 1000
});

const client = new Client({
	user: 'n3wz',
	password: 'x',
	host: 'localhost',
	database: 'n3wz'
});
client.connect();

var qparams = [
	...
];

var q = `
<long complicated query I'd like to spare you>
`;

var newestPooled = function(cb) {
	var s = new Date();
	pgpool.query(q,
		qparams,
		function(err, res) {
			var e = new Date();
			console.log('pooled: ' + ' ' + (e - s) / 1000);
			cb(null, res);
		}
	);
};

var newest = function(cb) {
	var s = new Date();
	client.query(q,
		qparams,
		function(err, res) {
			var e = new Date();
			console.log('client: ' + ' ' + (e - s) / 1000);
			cb(null, res);
		}
	);
};

//client
setTimeout(function() {
	newest((err, res) => {
		if (err) console.log(err);
		client.end()
	});
}, 2000);


//pooled
setTimeout(function() {
	[1, 2, 3, 4, 5].forEach(function(i) {
		newestPooled((err, res) => {
			if (err) console.log(err);
		});
	});
}, 4000);
```

this script outputs
```
client:  1.278
pooled:  3.651
pooled:  3.726
pooled:  3.733
pooled:  3.726
pooled:  3.766
```

I am sure I am doing something wrong, but why does the `client` executed query take 1.2 seconds, and the pooled query 3.7?
Am I doing something wrong?

**Comment by charmander** [comment]
You’re running the pooled query 5 times at once. If you run the non-pooled query 5 times at once, you’ll see the same behaviour.
