### ISSUE TITLE
query don't work in node but work in postgres

### ISSUE THREAD

**Issue by Grigsuv** [brianc/node-postgres#1657]
Node version - 8.9.4 pg module version - 7.4.3

this query

`UPDATE test.new_orders`
`SET properties = properties || '{"statusid":1,"updatedAt":"2018-5-24 14:51:43"}'`
`WHERE to_timestamp((properties ->> 'updatedAt'),'YYYY-MM-DD HH24:MI:SS.US') <= now() - INTERVAL '20 seconds'`
`AND properties ->> 'partitionid' = '6';`

in node gives `

    Result {
    command: 'UPDATE',
    rowCount: 0,
    oid: null,        rows: [],        fields: [],
    _parsers: [],        RowCtor: null,        rowAsArray: false,
    _getTypeParser: [Function: bound ] }

but in postgres it always updates 3 rows. What's the point? How deal with this?
``

P.S. This is my method

      getUpdatableOrdersAndUpdateStatuses(partitionid,orderProperties,interval) {
    return new Promise((resolve, reject) => {
        let query = `UPDATE test.new_orders
                        SET properties = properties || '${orderProperties}'
                     WHERE to_timestamp((properties ->> 'updatedAt'),'YYYY-MM-DD HH24:MI:SS.US') <= now() - INTERVAL '${interval}'
                     AND properties ->> 'partitionid' = '${partitionid}';`;
                     // test query = 'select * from test.new_orders'
                     console.log(query);         
        SQL.query(query, (err, res) => {
            if (err) {
                console.log(err);
                return reject(err);
            }
            console.log(res);
            return resolve(true);
        })
    });
}

test query(select * from test.new_orders) gives normal result

<!DOCTYPE html>
<html>
<head>
 and data `
</head>
<body>
<table border="1" style="border-collapse:collapse">
<tr><th>orderid</th><th>properties</th></tr>
<tr><td>5281</td><td>{&quot;tarifid&quot;: &quot;1&quot;, &quot;statusid&quot;: 1, &quot;createdAt&quot;: &quot;2018-05-24T13:40:57.544955&quot;, &quot;updatedAt&quot;: &quot;2018-5-24 14:46:49&quot;, &quot;partitionid&quot;: &quot;6&quot;}</td></tr>
<tr><td>15</td><td>{&quot;tarifid&quot;: &quot;1&quot;, &quot;statusid&quot;: 1, &quot;createdAt&quot;: &quot;2018-05-24T14:38:57.609023&quot;, &quot;updatedAt&quot;: &quot;2018-5-24 14:46:49&quot;, &quot;partitionid&quot;: &quot;6&quot;}</td></tr>
<tr><td>152</td><td>{&quot;tarifid&quot;: &quot;1&quot;, &quot;statusid&quot;: 1, &quot;createdAt&quot;: &quot;2018-05-24T14:39:11.655951&quot;, &quot;updatedAt&quot;: &quot;2018-5-24 14:46:49&quot;, &quot;partitionid&quot;: &quot;6&quot;}</td></tr></table>
</body>
</html>

**Comment by Grigsuv** [comment]
Forgot to add  'AT TIME ZONE 'My timezone''

**Comment by dpkg-i-foo-deb** [comment]
> Forgot to add 'AT TIME ZONE 'My timezone''

You have saved me, I have been struggling through this all day long
