### ISSUE TITLE
The module take default user

### ISSUE THREAD

**Issue by bbaltatu** [brianc/node-postgres#1658]
Hi,
I developed a NodeJS app using pg module. The app works ok on my computer, but when I am trying to run the app from server with pm2 and send pg config object in env the pg module crash and return an  "error: database "bogdan" does not exist"
I observe that the database name can be "bogdan" (my linux user ) or "root" , depend on what users appear in pm2 list.
I think the pm2 ignore the credentials and take the users as default .
How can I solve this issue ?
Thank you.
Bogdan

**Comment by bbaltatu** [comment]
I found the issue. Was my mistake.
In the config object instead "database" i have "dbName" .. The db parameter was not found and probably the module take sade database name as username

**Comment by theGlenn** [comment]
I actually have the same issue, I'm trying to connect with without `database` since there is none, but it falls back to the value specified in `user`.

```ts
    const client = new Pool({
      user: process.env.MYSQL_USER as string,
      host: process.env.MYSQL_HOST as string,
      password: process.env.MYSQL_PASSWORD as string,
      port: process.env.MYSQL_PORT as unknown as number,
    });
```
