### ISSUE TITLE
How many pools per project

### ISSUE THREAD

**Issue by spimou** [brianc/node-postgres#1659]
Hi there,
I use node 8.11.1, express 4.16.3, pg 7.4.2 and PostgreSQL 10 and PostGIS. I would like to use two pools in the same project : 
one for the front-end users and one for the CMS users, after they successfully login. Every pool has different database privileges. In both front-end and CMS, there are some spatial queries also. 

It makes sense to use two different pools, but according to the documentation ". You generally want a limited number of these in your application and usually just 1."

So, what do you suggest, should I use two pools? What are the criteria that render two pools viable or not? What should I watch out for?

Thank you

**Comment by brianc** [comment]
Two pools is fine. You dont want an unbounded number of pools but several
wont be any issue. Too many pools will create too many connections and
crash postgres but were talking about several thousand pools at least.

**Comment by spimou** [comment]
Thank you for the answer Brian. May I suggest that you mention somewhere in the pool documentation, that maybe two pools are fine, one for the front-end users and one for the logged-in, CMS users. Or you could explain what makes many pools not viable. 

Keep up the good work.
