### ISSUE TITLE
Wiki: generic connection-string

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1667]
Please add [connection-string](https://github.com/vitaly-t/connection-string) to the list of extras, as a generic, fully optional syntax connection string parser and generator.

I intended to have it replace the current connection string, but found little support for doing so.

The project also has a separate branch to be released soon that will support the multi-host syntax that's needed here, in order to properly support PostgreSQL 10.0 and later.

**Comment by azran4u** [comment]
Hi
Have you released the multi host support feature?
Thanks,
Eyal

**Comment by vitaly-t** [comment]
@azran4u Not yet, but I will ;)

**Comment by azran4u** [comment]
Thanks, i'll wait..

**Comment by vitaly-t** [comment]
Support for multiple hosts has been implemented in version 0.6.0 of the library.

@azran4u

**Comment by azran4u** [comment]
Thanks for the update!

**Comment by vitaly-t** [comment]
Guys, if you need help switching from `pg-connection-string` to this library, don't hesitate to ask! :wink:

**Comment by vitaly-t** [comment]
Can we have this added, please? It was asked 1 year ago.

**Comment by charmander** [comment]
Added.
