### ISSUE TITLE
Problems with parameterized queries pgpool-II version 3.6.6 (subaruboshi) + NodeJS

### ISSUE THREAD

**Issue by jers0** [brianc/node-postgres#1671]
Hello everyone,

Excuse me I do not speak English very well, I'm Spanish. I will try to explain my problem as well as possible.

I'm having problems to perform parameterized queries with NodeJS and the node-postgres library (https://github.com/brianc/node-postgres).

When the query is not parameterized I receive a response from the server without any problem and everything works fine, but when I parameterize it I never receive a response from the server, it keeps thinking.

I've been reading and I've already seen some threads where they talked about similar problems in previous versions of pgpool2 (https://github.com/brianc/node-postgres/issues/1255)

In local environment and without pgpool2 the parameterized queries also work correctly. It is not a syntax problem in the code, since local works correctly, but not in production!

The connection to the database in production is established correctly, and if the queries are not parameterized by the server response correctly.

Could someone help me with this? Maybe some configuration problem of pgpool2?

Someone with the same problem ??

A greeting and thanks to all.

**Comment by rkaw92** [comment]
Hi,
I'm not a user of pgpool myself, but check this out: https://www.pgpool.net/mantisbt/view.php?id=345
(I just found a lot of pgpool-related reports yesterday when searching for another bug.)

**Comment by jers0** [comment]
@rkaw92 Thank you very much, it seems that there is a patch that fixes the problem. Besides, this patch is already included in version 3.6.7, I'm going to ask the system administrator to update to version 3.6.7 and if this solves the problem I'll let you know in this thread.

**Comment by charmander** [comment]
Are you using a version older than 3.6.5?

**Comment by jers0** [comment]
@charmander Thanks for your interest, as my systems administrator informs us, our current version of pgpool2 is 3.6.6

**Comment by jers0** [comment]
@rkaw92 @charmander  Hello everyone, we have updated to version 3.6.11 of pgpool2 and the problems with the parameterized queries have disappeared. Everything worked perfectly.

Thank you very much, greetings.
