### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by t3ndai** [brianc/node-postgres#1676]
I enjoy using node-postures. But I think, the engine used for the documentation should be changed. the whole side bar is un-scrollable, in webkit browsers.

**Comment by jinjor** [comment]
I found just adding two lines fixes this problem, but not sure how to modify the doc engine or where to send PR.

```diff
  @media (min-width: 1010px)
  .aside {
      position: fixed;
+    overflow-y: scroll;
+    height: calc(100% - 50px);
  }
```

**Comment by charmander** [comment]
@jinjor See #1683

**Comment by charmander** [comment]
The sidebar is scrollable in the latest design.
