### ISSUE TITLE
Documentation PRs

### ISSUE THREAD

**Issue by stephenhuh** [brianc/node-postgres#1683]
Love this library,

Found some errors/typos on the documentation and was looking to open a PR. Is that on Github somewhere? Couldn't find it.

**Comment by charmander** [comment]
See also #1395

**Comment by brianc** [comment]
Thanks Stevie -  I have a project to clean up the code & put it on github
soon!  Sorry for the delay on that.  I need to fix where it's hosted too
because it's a bit hard to deploy right now.

**Comment by petetnt** [comment]
I got a few small fixes I'd love to push too 👍

**Comment by charmander** [comment]
https://github.com/brianc/node-postgres-docs :tada:
