### ISSUE TITLE
`field.format` is returned as `'text'` even for integers

### ISSUE THREAD

**Issue by mhkeller** [brianc/node-postgres#1688]
When I query a test table, which, as you can see from the `res.rows` value, has strings and integers, the `field.format` value is returned as `'text'` for all of them. The `_parsers` array appears to be returning the proper parsers.

```
Result {
  command: 'SELECT',
  rowCount: 6,
  oid: null,
  rows:
   [ { id: 1, name: 'jim', occupation: 'land surveyor', height: 70 },
     { id: 2, name: 'francis', occupation: 'conductor', height: 63 },
     { id: 3, name: 'alfred', occupation: 'foo', height: 32 },
     { id: 4, name: 'foo', occupation: 'bar', height: 23 },
     { id: 5, name: 'bar', occupation: 'foo', height: 33 },
     { id: 6, name: 'roger', occupation: 'harris', height: 10 } ],
  fields:
   [ Field {
       name: 'id',
       tableID: 16419,
       columnID: 1,
       dataTypeID: 23,
       dataTypeSize: 4,
       dataTypeModifier: -1,
       format: 'text' },
     Field {
       name: 'name',
       tableID: 16419,
       columnID: 2,
       dataTypeID: 25,
       dataTypeSize: -1,
       dataTypeModifier: -1,
       format: 'text' },
     Field {
       name: 'occupation',
       tableID: 16419,
       columnID: 3,
       dataTypeID: 25,
       dataTypeSize: -1,
       dataTypeModifier: -1,
       format: 'text' },
     Field {
       name: 'height',
       tableID: 16419,
       columnID: 4,
       dataTypeID: 23,
       dataTypeSize: 4,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers:
   [ [Function: parseInteger],
     [Function: noParse],
     [Function: noParse],
     [Function: parseInteger] ],
  RowCtor: null,
  rowAsArray: false,
  _getTypeParser: [Function: bound ] }
```

**Comment by charmander** [comment]
The format is either text or binary, and it’s how the PostgreSQL server sent the fields in its response to node-postgres. You’ll get text for everything unless there are binary parameters (IIRC), and the format won’t have any effect on the value you get back except for types node-postgres doesn’t know how to parse.

If you’d like to know the type of the field, that’s in `dataTypeID` as an OID.

```sql
=> SELECT oid, typname FROM pg_type WHERE oid IN (23, 25);
 oid | typname 
-----+---------
  23 | int4
  25 | text
(2 rows)
```

**Comment by mhkeller** [comment]
Got it, thanks. I'll make a lookup table.

**Comment by mhkeller** [comment]
@charmander do you know where I can find a lookup for the `dataTypeModifier` field? They're not in `pg_type` and I can't seem to find any obvious table that contains them.

**Comment by mhkeller** [comment]
An update for anyone finding this, it seems you can do `select a.attname, a.atttypid, a.atttypmod, format_type(a.atttypid, a.atttypmod) from pg_attribute a where attname = 'geom'` and that will return some `oid` `dataTypeModifier` combinations but it, in the PostGIS context, it seem to have anything for `Line` and `MultiLine` geometries which are returned by `node-pg` as `dataTypeID: 16393` and `dataTypeModifier: -1` which is the same as geometries returned by an `ST_Multi(geom)` transformation.
