### ISSUE TITLE
Update pg-connection-string to 2.0.0

### ISSUE THREAD

**Issue by joelmukuthu** [brianc/node-postgres#1689]
v2 has been out for a while now with some nice [new features](https://github.com/iceddev/pg-connection-string/commits/master). I couldn't reliably determine what the breaking changes were, otherwise I would have a created a PR.

Sorry if I missed this but are there some reservations against updating to v2?

**Comment by vitaly-t** [comment]
Related: #1667

**Comment by vitaly-t** [comment]
Another one open again - #1848

**Comment by charmander** [comment]
Changed in 698993ec6d082ccd8be87404be3995364c08c7fa, first released in pg@8.1.0.
