### ISSUE TITLE
Querying DB results are not accurate

### ISSUE THREAD

**Issue by SreeNivas15** [brianc/node-postgres#1691]
Hi,

I am not sure, whether this issue is encountered by anyone earlier with version 7.4.3.
In my project, I am using npm pg with version 7.4.3. By using this version, I got the new postgres sql connection by passing valid username, password and DB host details. After getting connection, I tried to fetch the data in below manner:

I have one array<object> which holds sample data as below:

names = [{name: 'Sreenivas}, {name: 'Siva'}]

In my test case, I am querying pg db by looping based on names.length. Example query as below:

for(let i =0; i < names.length; i++) {
   const dbConnection = this.postGresDBConnection;
   let result = await dbConnection.executeQuery(`select first_name, last_name, mobile_number from employees where first_name like '${names[index].name' }`, []);
console.log(result.rows);
}
In above case, my script will execute the query 2 times and I am expecting both the results should retrieve (Assume data exists with both the names).

But, While running, DB retrived the data for the first object (i.e.Sreenivas) and do not return with the name Siva. I copied the query and executed manually in postgres DB and got the results as expected.

Later I realized that native client querying  by passing SELECT 1 for the first object and SELECT 0 for the second.

Here, SELECT 0 is not returning any data eventhough data exists in the DB..

Could someone try to look into this issue.

Thanks in Advance,
Sreenivas

**Comment by sehrope** [comment]
Please format your code with markdown[1] and if possible post a more complete example reproducing the issue.

[1]: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by charmander** [comment]
```js
let result = await dbConnection.executeQuery(`select first_name, last_name, mobile_number from employees where first_name like '${names[index].name' }`, []);
```

This `${…}` is a syntax error. As sehrope said, please show a complete example, and make sure it’s real code.
