### ISSUE TITLE
Got a parameter parsing error

### ISSUE THREAD

**Issue by xiaobo1234** [brianc/node-postgres#1693]
Here is my code
```
const sql = `
  SELECT COUNT(id) FROM articles
    WHERE content #> '{ "images" }' @> '[{ "name": "$1" }]'
`;
const { rows } = await db.query(sql, [imageName]);
```
Note
```
The type of column 'content' is 'jsonb', formatted like '{ "images": [{ "name": "xxx.jpg" }], "text": "article text" }'.
I'm parsing variable 'imageName' into '$1', but failed with error.
```
And I've got this error
`bind message supplies 1 parameters, but prepared statement \"\" requires 0`
Thought I've found a solution with using 'jsonb_build_object' function but my PostgreSQL version is only 9.4.
At last, I have to change my code below
```
const sql = `
  SELECT COUNT(id) FROM articles
    WHERE content #> '{ "images" }' @> $1
`;
const { rows } = await db.query(sql, [JSON.stringify([{ name: imageName }])]);
```
But I'm wondering is there a more beautiful way to solve this problem?

**Comment by charmander** [comment]
You can continue passing just the `imageName` as a parameter if you build the `jsonb` value in the query:

```js
const sql = `
  SELECT COUNT(id) FROM articles
    WHERE content->'images' @> jsonb_build_array(jsonb_build_object('name', $1))
`;
const { rows } = await db.query(sql, [imageName]);
```

Or, slightly shorter but maybe less readable:

```sql
SELECT COUNT(id) FROM articles
  WHERE content->'images' @> ('[]' || jsonb_build_object('name', $1))
```

**Comment by charmander** [comment]
> Thought I've found a solution with using 'jsonb_build_object' function but my PostgreSQL version is only 9.4.

Sorry, I missed this. `||` won’t work, then, and you’ll need to use `json_build_object` and cast to `jsonb`.
