### ISSUE TITLE
Pool.end() sometimes dosn't work

### ISSUE THREAD

**Issue by Grigsuv** [brianc/node-postgres#1695]
Hi,I need to close pg connections,have this code ` 

![screenshot from 2018-07-20 12-21-27](https://user-images.githubusercontent.com/33725011/42991699-7101852a-8c17-11e8-9a81-9a5c9f0cbe65.png)

when I run more than 1 containers  of this program my connections getting stuck,more than 10,even 30 ,
program every 3 seconds making select query.

before this query functions was this `

![screenshot from 2018-07-20 12-27-55](https://user-images.githubusercontent.com/33725011/42992000-5afd943e-8c18-11e8-8e72-9dfb2c0e6907.png)

I was getting the same issue.
Solution?

**Comment by vitaly-t** [comment]
Closing the pool gets stuck when you call it while running a query that's stuck. The pool cannot release a currently blocked connection.

**Comment by Grigsuv** [comment]
In my application I am working with 2 databases,at first some `SELECT` query from `main_db` then some logic + insert in other db,and it's doing the same every 3 seconds,I don't think that the whole process would take more that 1-2 sec so it must automatically  close  connections because they have nothing to do,In 1st example every time it creates `pool` making query,put result into variable and closes the pool,what is wrong?Maybe this is some bug?

**Comment by charmander** [comment]
Can you show the code related to the other query?

**Comment by Grigsuv** [comment]
@charmander other db's query making like 2nd screenshot(other pool),it is insert query

**Comment by Grigsuv** [comment]
![screenshot_20180721_093726](https://user-images.githubusercontent.com/33725011/43032525-ed0f4b86-8cc9-11e8-8079-ecddf3b73e48.png)

**Comment by sehrope** [comment]
You need to add error handling for the `await k.query(text)` piece. Otherwise if it throws an error the pool will never be closed as the `pool.end()` will never be called. Separately, the `params` and `callback` parameters aren't being referenced at all in `test(...)`.

Should be something like:

```js
async test (text, params) {
    const pool = new Pool(main_db);
    try {
        const result = await pool.query(text, params);
        return result.rows;
    } finally {
        await pool.end();
    }
}
```

Creating a new pool for each request and then shutting it down is the same as directly creating a single client, just with more overhead. The pool creation could be replaced with:

```js
async test (text, params) {
    const client = new Client(main_db);
    await client.connect();
    try {
        const result = await pool.query(text, params);
        return result.rows;
    } finally {
        await client.end();
    }
}
```

**Comment by Grigsuv** [comment]
So it's normal that connections? I think I don't get errors because more then 2 week I was using method `main_query` (then started use `test` bcs 20+ connections (-__-) ),there was no error

**Comment by Grigsuv** [comment]
@sehrope @charmander  @vitaly-t

**Comment by Grigsuv** [comment]
Now I my app. after `main_db` query ends,and when I run 3 pods of this app. connections getting stuck :(

**Comment by Grigsuv** [comment]
Problem was that transport layout takes so much time that other processes  aren't able to make query every 3 sec and connections got stacked

**Comment by AxelTerizaki** [comment]
I have the same issue. here's what I'm doing : 

- Created a pool with `const pool = new Pool()`
- Made a transactuion function that creates a new client from my pool (using `const client = pool.connect()`) 
- This client runs queries
- At the end I call `client.query('COMMIT')` and then `client.release()`
- When the transaction is over, I call `pool.end()` but it gets stuck.

When trying to display counters, `idleCount` is set to 1, and `totalCount` to 2. 

I'm not sure of what I'm doing wrong here honestly, apart that `end()` won't work. Is there no way to display which client is stuck and terminate it?
