### ISSUE TITLE
[Suggestion] generic type for rows of QueryResult 

### ISSUE THREAD

**Issue by almothafar** [brianc/node-postgres#1696]
I think this should be awesome if you can support generic types for rows in QueryResult 

To change this: 

```
export interface QueryResult extends QueryResultBase {
    rows: any[];
}
```

To something like:

```
export interface QueryResult<T> extends QueryResultBase {
    rows: T[];
}
```
And for sure apply for the rest of interfaces, like `QueryArrayResult` and `ResultBuilder`.
Currently, in my project I do something like: 

```
export interface GenericQueryResult<T> extends QueryResult {
    rows: T[];
}
```

And working without issues, but will be nice if that is already by default like that.

**Comment by sehrope** [comment]
This module doesn't have any typing as it's pure JS and the Typescript typings aren't part of this repo. They're part of DefinitelyTyped and any changes should be submitted there: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pg/index.d.ts

Something like this should maintain backwards compatibility as well:

```typescript
// Add generic row type to QueryResult defaulting to any
export interface QueryResult<RowT = any> extends QueryResultBase {
    rows: RowT[];
}

// Add generic to query(...) overloads:
query<RowT = any>(queryConfig: QueryConfig): Promise<QueryResult<RowT>>;
```

**Comment by almothafar** [comment]
Thanks, i'll do, my fault :)
