### ISSUE TITLE
Simplify identifier escaping logic

### ISSUE THREAD

**Issue by gajus** [brianc/node-postgres#1699]
Unless I am overlooking something, then this code:

https://github.com/brianc/node-postgres/blob/6c840aabb09f8a2d640800953f6b884b6841384c/lib/client.js#L306-L322

can be simply expressed as:

```js
'"' + identifier.replace(/"/g, '""') + '"'

```

Didn't rush to create a PR as it isn't clear whats the reason the function is defined as is at the moment.

**Comment by charmander** [comment]
Yep, feel free to make a PR or just comment if you’re unavailable and I can change it.

**Comment by vitaly-t** [comment]
From own code:

```js
function formatSqlName(name) {
    return '"' + name.replace(/"/g, '""') + '"';
}
```

So yes, this is the correct way to escape SQL names/identifiers.

**Comment by gajus** [comment]
> This doesn't just escape it, but it first check if escaping is needed at all, because it is nicer to read identifiers without "", if they can be used as an open name.

This seems to ignore the possibility that an identifier is also a keyword, i.e. `select` would break the code.
