### ISSUE TITLE
create database and table schema via pg

### ISSUE THREAD

**Issue by HaoyangFan** [brianc/node-postgres#1702]
hi I am new to `pg` and just wonder that if it possible to use `pg` to do the following steps:

1. create a database and connect to it, like this in `psql`
```
create database example
grant all privileges on database example to someuser
\c example
```

2. create the table via schema, whose equivalent in `psql` is 
```
create table schema1 {
  id uuid not null,
  username varchar(128) not null unqiue,
  ...
}
with (oids = false)
```

I am looking at the docs but find no methods for those actions. Any help will be appreciated

**Comment by sehrope** [comment]
Those `CREATE ...` commands are regular SQL just like running a `SELECT ...`. There's no special functions for those commands. You can execute them the same way via `pool.query('CREATE TABLE ...')`.

PostgreSQL (the server) requires connecting to a database so in your example you'd first connect to one database (likely the default "postgres") and run the `CREATE DATABASE example` commands. Then connect again to the "example" database and run the "CREATE TABLE ...` commands.
