### ISSUE TITLE
Distinguish between database connection/server error and postgres error

### ISSUE THREAD

**Issue by HaoyangFan** [brianc/node-postgres#1705]
Reading the post #1453, I want to confirm if I understand the idea correctly:

If `err` does not have a `name` property, like this ( I intentionally set the port number to be 5433 to make the connection failed), then it will mean the error occurs not due to postgres schema, but due to the server exception
```
 { Error: connect ECONNREFUSED 127.0.0.1:5433
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5433 }
```

On the other hand, if the error has a `name` property whose value is just `error`, then it is basically telling us that the error occurs due to the `postgres`, where our query probably violates some integrity constraints etc

**Comment by brianc** [comment]
Yeah that sounds right - the errors from the postgres server have a lot of metadata attached to them.\

https://github.com/brianc/node-postgres/blob/master/lib/connection.js#L542
