### ISSUE TITLE
Asynchronous problems encountered by the package pool

### ISSUE THREAD

**Issue by Adherentman** [brianc/node-postgres#1710]
## First I encapsulated a query function：
```typescript
const pool = new Pool(env.pgPoolConfig);

const query = async (text: any, parm?: any) => {
	const connect = await pool.connect();
	pool.on('error', (error) => {
		console.error('error event on pool (%s)', error);
	});
	connect.on('end', () => {
		console.log('end event on client');
		pool.end();
	});
	try {
		const res = await connect.query(text, parm);
		return res;
	} catch (error) {
		throw new Error(error);
	} finally {
		await connect.release();
		console.log('release success');
	}
};

export default query;
```
## Then：
```typescript
(async () => {
	try {
		const res = await query(`SELECT NOW()`);
		console.log(res.rows[0]);
	} catch (error) {
		console.log(error);
	}
})();
```
In the terminal, the `release success` is printed before `res`. I think it should be `release success` after the `res` comes out. I don't know if `release success` is correct before `res`.
<img width="425" alt="wx20180827-002012 2x" src="https://user-images.githubusercontent.com/26477346/44630388-2884a800-a98f-11e8-8b4e-b6441f5c2b18.png">

**Comment by sehrope** [comment]
No that's correct as the finally block (with the printing of "release success") executes before the calling function continues. The value of `res` is already populated but the function won't return it back to the caller in the return statement until *after* it runs the finally block.
