### ISSUE TITLE
Get query result and store in global variable

### ISSUE THREAD

**Issue by davidshare** [brianc/node-postgres#1714]
Hi I am trying to check if a username exists before performing an insert. However, I cannot get the result of the query outside of the client call. I have tried using the method as a middleware in my routes, it blocks the app from running correctly and I don't know why. Please how do I get the value of db result outside of this block?

```js
  static checkDuplicateEmail(request, response, next) {
    if (request.email) {
      const query = `SELECT * FROM users WHERE email ='${request.email}'`;

      client.query(query)
        .then((dbResult) => {
          if (dbResult.rows[0]) {
            return response.status(406)
              .json({
                statusCode: 406,
                message: 'Sorry this email is taken',
                success: 'fail',
              });
          } return next();
        }).catch((err) => { response.status(500).send(err.message); });
    }
  }
```

**Comment by charmander** [comment]
This is more of a JavaScript/Express question than a pg question. Does `request.email` exist? You probably need to call `next()` when it doesn’t. See https://stackoverflow.com/questions/14220321/how-do-i-return-the-response-from-an-asynchronous-call for some information about getting results back from asynchronous operations.

For some advice that does apply to databases, though, you should use a query parameter –

```sql
SELECT * FROM users WHERE email = $1
```
and
```js
client.query(query, [request.email])
```
– to avoid SQL injection. See https://node-postgres.com/features/queries#parameterized-query.
