### ISSUE TITLE
Handling client.connect error (async/await)

### ISSUE THREAD

**Issue by ViktorQvarfordt** [brianc/node-postgres#1716]
I have the following basic "hello world" code:

```js
const { Client } = require('pg')
const client = new Client()

async function main() {
  try {
    await client.connect({ connectionString: '...' })
  } catch (err) {
    console.log('error:', err)
    return
  }

  const res = await client.query('SELECT $1::text as message', ['Hello world!'])
  console.log(res.rows[0].message) // Hello world!
  await client.end()
}

main()
```

And my connection fails (rejected because the remote hasnt opened the port) then I don't get a reasonable error output, instead I see the following.

```
C:\...\node_modules\pg\lib\client.js:123
      return callback(err)
             ^

TypeError: callback is not a function
    at Connection.connectingErrorHandler (C:\...\node_modules\pg\lib\client.js:123:14)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.reportStreamError (C:\...\node_modules\pg\lib\connection.js:71:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

The [docs](https://node-postgres.com/features/connecting) say that client.connec() returns a promise, but it seems it doesn't.

**Comment by ViktorQvarfordt** [comment]
Sorry, i messed up by putting the connectionString as an argument to `connect` rather than `Client`.

**Comment by ViktorQvarfordt** [comment]
Regardless, it is not nice that `connect` is inconsistent in what it returns (promise or not)

**Comment by charmander** [comment]
`connect` can’t also return a promise when it thinks you’re passing a callback – errors would mean unhandled rejections – but it should check the type of the argument synchronously to avoid this.
