### ISSUE TITLE
Multi-query is atomic?!

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1717]
Opening this issue, following this: [multi-query is atomic?](https://stackoverflow.com/questions/52111972/node-postgres-multi-query-is-atomic)

This was originally posted against `pg-promise`, but quick tests revealed that's how `node-postgres` works, surprisingly. And I am totally caught up by this revelation myself. I was sure that when executing a multi-query string the operation wasn't atomic, but turns out that it is.

### Steps to reproduce

Execute something like this with a single call to the `query` method:

```sql
INSERT INTO table VALUES(1, 2);INSERT INTO table VALUES(3, 4);bla-bla
```

### Expected results

Two records are inserted, and then an error is thrown, about the invalid `bla-bla` query.

### Actual results

The two inserted records are rolled back, following the last-query error, even though we do not use any transaction 😮

**Comment by charmander** [comment]
Yes, it’s in a transaction. That’s how the PostgreSQL protocol works. Compare [libpq][1]:

> The command string can include multiple SQL commands (separated by semicolons). Multiple queries sent in a single `PQexec` call are processed in a single transaction, unless there are explicit `BEGIN`/`COMMIT` commands included in the query string to divide it into multiple transactions.


[1]: https://www.postgresql.org/docs/10/static/libpq-exec.html#LIBPQ-EXEC-MAIN

**Comment by vitaly-t** [comment]
Thank you for clarifying. This was somehow lost in translation, it seems.
