### ISSUE TITLE
Transaction serialization_failure errors are not relayed to the application

### ISSUE THREAD

**Issue by AndreiBorac** [brianc/node-postgres#1721]
An application cannot detect serialization_failure when using isolation level serializable. In the below example, two invocations of a counter incrementing function both appear to succeed. However, the counter is only incremented once. It is highly desirable that one of the processes should be able to detect that the transaction was cancelled and print abort.

    const { Pool, Client } = require("pg");
    
    const pg_pool = (new Pool({
        host: "localhost",
        port: 5432,
        user: "counter",
        password: "counter",
        database: "counter"
    }));
    
    const increment = (async () => {
        const client = await pg_pool.connect();
        
        try {
            await client.query("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");
            
            await client.query("BEGIN");
            
            const res1 = await client.query("SELECT * FROM counters WHERE id = 0");
            console.log(res1);
            
            const prior = res1.rows[0].value;
            console.log("prior=" + prior);
            
            res = await client.query("UPDATE counters SET value = $1 WHERE id = 0", [ prior + 1 ]);
            console.log(res);
            
            res = await client.query("COMMIT");
            console.log(res);
            
            console.log("success");
        } catch (e) {
            await client.query("ROLLBACK");
            throw e;
        } finally {
            client.release();
        }
    });
    
    increment();
    increment();

    > node server.js
    
    Result {
      command: 'SELECT',
      rowCount: 1,
      oid: null,
      rows: [ { id: 0, value: 10 } ],
      fields:
       [ Field {
           name: 'id',
           tableID: 16730,
           columnID: 1,
           dataTypeID: 23,
           dataTypeSize: 4,
           dataTypeModifier: -1,
           format: 'text' },
         Field {
           name: 'value',
           tableID: 16730,
           columnID: 2,
           dataTypeID: 23,
           dataTypeSize: 4,
           dataTypeModifier: -1,
           format: 'text' } ],
      _parsers: [ [Function: parseInteger], [Function: parseInteger] ],
      RowCtor: null,
      rowAsArray: false,
      _getTypeParser: [Function: bound ] }
    prior=10
    Result {
      command: 'SELECT',
      rowCount: 1,
      oid: null,
      rows: [ { id: 0, value: 10 } ],
      fields:
       [ Field {
           name: 'id',
           tableID: 16730,
           columnID: 1,
           dataTypeID: 23,
           dataTypeSize: 4,
           dataTypeModifier: -1,
           format: 'text' },
         Field {
           name: 'value',
           tableID: 16730,
           columnID: 2,
           dataTypeID: 23,
           dataTypeSize: 4,
           dataTypeModifier: -1,
           format: 'text' } ],
      _parsers: [ [Function: parseInteger], [Function: parseInteger] ],
      RowCtor: null,
      rowAsArray: false,
      _getTypeParser: [Function: bound ] }
    prior=10
    Result {
      command: 'UPDATE',
      rowCount: 1,
      oid: null,
      rows: [],
      fields: [],
      _parsers: [],
      RowCtor: null,
      rowAsArray: false,
      _getTypeParser: [Function: bound ] }
    Result {
      command: 'COMMIT',
      rowCount: null,
      oid: null,
      rows: [],
      fields: [],
      _parsers: [],
      RowCtor: null,
      rowAsArray: false,
      _getTypeParser: [Function: bound ] }
    success
    Result {
      command: 'UPDATE',
      rowCount: 1,
      oid: null,
      rows: [],
      fields: [],
      _parsers: [],
      RowCtor: null,
      rowAsArray: false,
      _getTypeParser: [Function: bound ] }
    Result {
      command: 'COMMIT',
      rowCount: null,
      oid: null,
      rows: [],
      fields: [],
      _parsers: [],
      RowCtor: null,
      rowAsArray: false,
      _getTypeParser: [Function: bound ] }
    success

**Comment by sehrope** [comment]
This isn't a driver issue, your BEGIN and SET TRANSACTION ... are out of order. Changing the transaction isolation level needs to happen after the transaction starts as the first operation in the new transaction.

From the server docs:  (https://www.postgresql.org/docs/current/static/sql-set-transaction.html)

> The SET TRANSACTION command sets the characteristics of the current transaction. It has no effect on any subsequent transactions. SET SESSION CHARACTERISTICS sets the default transaction characteristics for subsequent transactions of a session. These defaults can be overridden by SET TRANSACTION for an individual transaction.

Otherwise the new transaction will revert to the default transaction isolation level which is likely READ COMMITTED. You can verify this by adding a logging statement to print the value of SHOW TRANSACTION ISOLATION LEVEL.

**Comment by AndreiBorac** [comment]
Ah that solves it, thanks.
