### ISSUE TITLE
Async calls broken

### ISSUE THREAD

**Issue by BC89** [brianc/node-postgres#1722]
await is only valid in async function node version 8.11.1 on all async calls

**Comment by wlaurance** [comment]
Hi, @BC89 any example code for us to look at?

Thanks!

**Comment by BC89** [comment]
const pg = require('pg');

const config = {
    host: ‘’,
    // Do not hard code your username and password.
    // Consider using Node environment variables.
    user: ‘’,
    password: ‘’,
    database: ‘’,
    port: 5432,
    ssl: true
};

module.exports = function (context, req) {

    context.log('JavaScript HTTP trigger function processed a request.');

    const client = new pg.Client(config);

    await client.connect();

    await client.end();

    //context.done();
};

Using Azure Functions with Node but am a nube to both and really just trying to execute some prototype code base on the examples you provide.
Worker was unable to load function appointments: 'SyntaxError: await is only valid in async function' []

**Comment by vitaly-t** [comment]
The library supports Node.js 4.5 and later, while most of its code examples are with `async`, which implies the use of Node.js `harmony` branch that became default since v7.11.

@BC89 
So nothing is broken, you just misunderstood that examples show the latest syntax.

**Comment by charmander** [comment]
`await` isn’t specific to pg. You should get acquainted with how it and promises work, as they’ll come up a lot when using Node. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by supreetpal** [comment]
It might be useful to add some note that the "This is the simplest possible way to connect..." example in `Getting Started` does not work on copy+paste. :)

**Comment by CanDoAnything** [comment]
@supreetpal  Yes -- i agree --- was just copy-pasting and ran into the same issue ;)
