### ISSUE TITLE
Is there a way to execute a COPY command as a superuser

### ISSUE THREAD

**Issue by saishav7** [brianc/node-postgres#1725]
I'd like to execute a copy command on a postgreSQL db hosted by RDS. I don't have superuser access and was wondering if there's a way around it. (similar to how psql has \COPY)

**Comment by sehrope** [comment]
Yes, you can execute non-super user COPY commands using STDIN and STDOUT. See https://github.com/brianc/node-pg-copy-streams for the separate module that provides this functionality atop the pg driver.
