### ISSUE TITLE
How to get uuid back from database as bytes rather than string?

### ISSUE THREAD

**Issue by rightaway** [brianc/node-postgres#1726]
I'd like to get a uuid column from the database as bytes, for example a Buffer, rather than a string. How can I do this with node-postgres?

**Comment by sehrope** [comment]
You can change the parsed value of any data type by overriding the type handler. See here for more details: https://github.com/brianc/node-pg-types

You can also get the database to transform the value from a UUID to a bytea (byte array) which will be parsed as a Buffer in node. It's a bit of a kludge but may be useful for a one-off query as you don't have to mess around with changing type handlers:

```sql
=> SELECT decode(replace(some_uuid::text, '-', ''), 'hex')
   FROM (SELECT 'e7fb5692-e92c-4725-9640-07880bf64f16'::uuid AS some_uuid) t;
               decode               
------------------------------------
 \xe7fb5692e92c4725964007880bf64f16
(1 row)
```
