### ISSUE TITLE
Query.types is not documented (correctly)

### ISSUE THREAD

**Issue by redneb** [brianc/node-postgres#1727]
This is a minor issue with the documentation and the comments inside the code.

According to the [docs](https://node-postgres.com/api/client), the `QueryConfig` object (and thus, also the `Query` constructor) has a member called `types`, but the docs say nothing about what kind of values it accepts. According to [a comment in the code](https://github.com/brianc/node-postgres/blob/e7602bc67862ea41c579f382060b3fbd066cdc25/lib/connection.js#L214), `types` must be something like `['int8', 'bool']`. But [a few lines further down](https://github.com/brianc/node-postgres/blob/e7602bc67862ea41c579f382060b3fbd066cdc25/lib/connection.js#L231), it is treated like an integer. Based on my testing, this integer appears to be the `oid` of the type.

So maybe the comment should be removed and possibly add an explanation of the purpose of `types` in the documentation. A possibly better option would be to change `types` to accept something like `['int8', 'bool']`, but I am not sure if it's worth it.

**Comment by charmander** [comment]
An example for `types` no longer appears in the docs.
