### ISSUE TITLE
Wiki: Add sql to the extras

### ISSUE THREAD

**Issue by lucleray** [brianc/node-postgres#1729]
Hi 👋

We love pg and we use it a lot so we made [**sql**](https://github.com/sequencework/sql), a tiny module to create query objects with template literals :
```js
const query = sql`select * from movies where author = ${author}`
const result = await db.query(query)
```

It has some [**nice shorthands with pg**](https://github.com/sequencework/sql#shorthand-for-postgres) :
```js
const movies = await sql.many(db)`select * from movies`
const movie = await sql.one(db)`select * from movies where id = ${id}`
```

Maybe it could be added to the extra page in the wiki ? 

Thanks for this great module !

**Comment by charmander** [comment]
Added, since a less popular package with a similar purpose is also there.

**Comment by lucleray** [comment]
Thanks!
