### ISSUE TITLE
Values from string columns have plenty of spurious trailing spaces

### ISSUE THREAD

**Issue by inad9300** [brianc/node-postgres#1738]
This is the first time I use node-postgres... I'm working with a nutritional database, and when I run the same query through psql and though node-postgres, the results are totally different.

#### With psql
```sql
select long_desc, length(long_desc) from food_des limit 1;

--  long_desc            | length 
-- ----------------------+--------
--  Butter, salted       |     14 
```

#### With node-postgres
```js
import * as pg from 'pg'

const db = new pg.Pool({
    database: '...',
    user: '...',
    password: '...',
    host: 'localhost',
    port: 5432,
    max: 16
})

db.query('select long_desc from food_des limit 1')
    .then(res => console.log(res.rows[0].long_desc, res.rows[0].long_desc.length))
    .catch(err => console.error(err))

// Butter, salted                       200
```
Where are all these extra characters coming from?

**Comment by sehrope** [comment]
Check if the data type of the `long_desc` column is `char(...)`. If so, then the string representation will be right padded with whitespace and trailing whitespace is disregarded for most string related functions including comparison and length:

```sql
=> SELECT x::text, x, length(x) FROM (SELECT 'test'::char(20) AS x) t;
  x   |          x           | length 
------+----------------------+--------
 test | test                 |      4
(1 row)
```

See here for more details: https://www.postgresql.org/docs/current/static/datatype-character.html

The driver is receiving the right padded value and from its perspective its just a string. You can either trim it on the driver side or change the DB to use a regular `text` type instead (I'd suggest doing this).

**Comment by inad9300** [comment]
You are totally right, thank you! I just ported a MySQL database to Postgres, and I hadn't seen this issue before, so I was quite surprised. Probably the driver I was using was taking care of this.

Actually I think I will recreate the database using `varchar` instead of `char` possibly everywhere.

Thanks once again.
