### ISSUE TITLE
Expose an API for `util.prepareValue`

### ISSUE THREAD

**Issue by serv** [brianc/node-postgres#1740]
`util.prepareValue` is a useful method that is a helper function for parameterizing the query values.
https://github.com/brianc/node-postgres/blob/master/lib/utils.js#L156

However, it doesn't seem like there is a way to access this method on its own.

What do you think about having this method be exposed as a public method that people can use?

**Comment by serv** [comment]
Thanks for the tip.

**Comment by gaearon** [comment]
Is it considered a public API?

**Comment by charmander** [comment]
@gaearon Not sure about the initial intent, but it’s one now!
