### ISSUE TITLE
setTypeParser not applied to json_build_object values?

### ISSUE THREAD

**Issue by drulia** [brianc/node-postgres#1743]
Not sure if this is by design, but I have noticed that values returned by `json_build_object` are not being processed by `setTypeParser` function. Even if I specify in the query of what type the value will be, it is still ignored.

Example: having this set `pg.types.setTypeParser(1114, (val) => val === null ? null : moment(val));`
and running same query with only difference of how values are selected will return different results.
```
SELECT time_column FROM test_table
```
`time_column` is instance of moment
```
SELECT json_build_object('time_column', time_column) FROM test_table
```
`time_column` is a string with date coming straight from database

Is this a bug or it is expected behavior?

Running 7.5.0 version.

**Comment by vitaly-t** [comment]
This library doesn't parse returned JSON objects when you request those, only standard row results.

**Comment by drulia** [comment]
Probably should be a note in docs about this.

**Comment by vitaly-t** [comment]
You document what a library does, not things a library doesn't do.

**Comment by drulia** [comment]
I see your point, but when it says that you can override type parsing and doesn't mention that it does not apply to json functions, it can be misleading and lead to avoidable bugs.
Anyway, I should have posted this in node-pg-types.

**Comment by sehrope** [comment]
The result of `json_build_object(...)` is of type `json`. There's no additional typing for the contents of the fields within the JSON as PostgreSQL itself doesn't provide or even track that information. From the server's perspective it's just "json" without any detail about what's inside.

If you want to do something specific to transform a value to a Date or moment object you'll have to either override the parser for the json type itself (either globally or on that one query) or transform the result (probably easier).
