### ISSUE TITLE
Wiki: Add krauter to extras page

### ISSUE THREAD

**Issue by brandon-d-mckay** [brianc/node-postgres#1750]
Hi,

I integrated my module with pg and was wondering if you'd want to add it to the "Extras" wiki page. [krauter](https://github.com/brandon-d-mckay/krauter) is a module based on the [Express](https://github.com/expressjs/express) router, which allows you to simply put strings (and a few other types) directly into your routes and have them automatically generated into parameterized query middleware. This makes it really quick to set up an API and greatly reduces the amount of boilerplate code that you need to write.

Let me know if you have any questions/comments!

Thanks!

**Comment by charmander** [comment]
Added.
