### ISSUE TITLE
Query - Is not null Error 

### ISSUE THREAD

**Issue by srunicornio** [brianc/node-postgres#1761]
Hi there,

Im getting error in this basic parametrised query. It seems like I can't bind NOT NULL in parametrised params. Why is that?

```
const query = 'SELECT * FROM backgrounds WHERE (active IS $1)'
const params = ['NOT NULL']
const res = await pg.query(query, params)
```

**Comment by joelmukuthu** [comment]
`IS NULL`, `IS NOT NULL` are SQL clauses that cannot be parameterised. See a more detailed answer [here](https://github.com/brianc/node-postgres/issues/1751#issuecomment-431012230)
