### ISSUE TITLE
Pool.query() does not throw error with full stack trace

### ISSUE THREAD

**Issue by kevin-leptons** [brianc/node-postgres#1762]
Issue of  **Pool.query()**.

Errors which are throw form Pool.query() does not contains full error stack trace. Please throw standard error with full stack trace.

**Comment by joelmukuthu** [comment]
Hi, could you post the incomplete stack trace and the code that generates the error? Without knowing more about your case however, I’m guessing that it might have something to do with [this infamous bug in node](https://github.com/nodejs/node/issues/11865), which can’t be fixed in this library

**Comment by kevin-leptons** [comment]
Hi Joe,

Yes, I got it, my case is similar like that. Now I know that we can't fix it in this library. What can we do in this case?, or just wait for node.js team?.

**Comment by joelmukuthu** [comment]
You can try some of the workarounds suggested in that issue:

- https://github.com/AndreasMadsen/trace
- https://github.com/artdecocode/erotic
- Bluebird promises with `BLUEBIRD_LONG_STACK_TRACES=1`. You can configure the promise constructor to use and then set the BLUEBIRD_LONG_STACK_TRACES environment variable when running the application:

```js
const bluebird = require('bluebird');
const { Client, Pool } = require('pg');

const pool = new Pool({
  Promise: bluebird
});

// for this one, only available in pg@7.6.0 and up:
const client = new Client({
  Promise: bluebird
});
```

```bash

**Comment by kevin-leptons** [comment]
Thank Joel, I will try all of it. I also let this issue is open to show that it should be solve, some how.

**Comment by charmander** [comment]
@joelmukuthu’s covered it all; stack traces get lost by default in JavaScript when asynchronous tasks aren’t direct calls.

**Comment by phiresky** [comment]
Now that [zero-cost async stack traces](https://v8.dev/blog/fast-async) are part of Node (v12) by default, it would be great if this could be reconsidered. I'm not sure what the reason is that this is still broken in node-pg, maybe because node-pg doesn't use native promises or native async functions?

**Comment by brianc** [comment]
> I'm not sure what the reason is that this is still broken in node-pg

the reason is this project has been maintained almost entirely by myself and 1 other person for the past decade and we're buried under bug reports, feature requests, internal priorities.  Also, the world has fallen into a global pandemic causing me significant anxiety attacks.  Also, we still support versions of node back to 6.0.

**Comment by brianc** [comment]
> maybe because node-pg doesn't use native promises or native async functions?

with the 9.0 internals re-write i'll be starting as soon as I can catch my emotional breath I'm going to investigate switching fully async/await (as much as possible) internally.  We'll see how the perf of that is, but if that works you _might_ just get this (and every other feature ever since it's open source) for free!

**Comment by phiresky** [comment]
No problem, sorry that I appeared to be demanding stuff for free. Mainly I think this issue could be reopened, since the original reason where this was not possible at all due to node restrictions is gone.

**Comment by brianc** [comment]
ah gotcha! Yeah no worries - I get a _lot_ of email and you know tone of
voice and stuff doesn't carry well over text. :p   I'll definitely keep
this in mind when I'm working on performance over the next few months.  I
also think the current stack traces are gross and hard to deal with so I'm
all for fixing them! First up I want to get perf up a bit - some benchmarks
locally w/ some experiments I've done are showing upwards of 40-50% speed
increase in some cases.

**Comment by tolmekian1453** [comment]
Not sure if I'm doing something wrong, but nothing in the above conversation or similar ones elsewhere worked.

This is what I did, works. Dunno if it'll work on older Node versions.
```
const executeSql = async function(conn, q, args) {
  // gets the stack before the error, otherwise it's the emitResult stuff
  const stack = new Error().stack 
  try {
    return await conn.query(q, args)
  } catch(err) {
  console.error(stack)
  throw err
}
```

**Comment by mcapodici** [comment]
> 
> 
> > I'm not sure what the reason is that this is still broken in node-pg
> 
> the reason is this project has been maintained almost entirely by myself and 1 other person for the past decade and we're buried under bug reports, feature requests, internal priorities. Also, the world has fallen into a global pandemic causing me significant anxiety attacks. Also, we still support versions of node back to 6.0.

A big thank you. I don't know how popular FOSS maintainers do it all 👍 .

**Comment by pauldraper** [comment]
> Also, we still support versions of node back to 6.0.

Given that Node 6 was EOL'd April 2019, that's just crazy.

**Comment by phiresky** [comment]
I've made a PR to fix this: https://github.com/brianc/node-postgres/pull/2983
