### ISSUE TITLE
TypeError: pgClient is not a constructor

### ISSUE THREAD

**Issue by prtome** [brianc/node-postgres#1766]
I cannot find this in the docs, but are there reserved keywords ?
when I have

        var { Client }= require('pg');
        const client = new Client({
               user: 'dbuser',
              host: 'database.server.com',
             database: 'mydb',
               password: 'secretpassword',
               port: 3211,
           })

Everything is ok , but if I change Client to pgClient  (var { pgClient}  and new pgClient  I get

         TypeError: pgClient is not a constructor

thanks

**Comment by sehrope** [comment]
No this isn't a reserved keyword issue. It's just a JS error. The JS feature is called destructuring assignment. You can read more about how it works here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring

The name of the class is `Client` so it only works on one line if you use the same name as the property.

These two are the equivalent:
```js
const { Client } = require('pg');
const Client = require('pg').Client;
```

And so are these two:

```js
const { pgClient } = require('pg');
// This will be undefined since the property on pg is "Client" no "pgClient"
const pgClient = require('pg').pgClient;
```

If you want the variable to be named something else locally you can rename it like this:

```js
const pgClient = require('pg').Client;
```

**Comment by prtome** [comment]
Thanks ! just shown my ignorance !

**Comment by Samandarxon** [comment]
--ES module:
import pg from 'pg';
const Client = pg.Client
