### ISSUE TITLE
parameterized queries

### ISSUE THREAD

**Issue by kellengreen** [brianc/node-postgres#1772]
Quick question:

What would a simple parameterized query like this get turned into before being sent to the database?
```js
await client.query('SELECT * FROM foo WHERE id = $1;', [1])
```

I would have guessed something along these lines:
```sql
PREPARE temp(int) AS 
    SELECT * FROM foo WHERE id = $1;
EXECUTE temp(1);
DEALLOCATE temp;
```

But my logs only show `unnamed` being executed.
```log
LOG:  execute <unnamed>: SELECT * FROM foo WHERE id = $1;
DETAIL:  parameters: $1 = '1'
```

**Comment by vitaly-t** [comment]
My understanding is that what you assumed to be executed is in fact a TSQL overhead for Prepared Statements, while this driver can submit requests that are treated as Prepared Statements automatically.

I'm just guessing :wink:

**Comment by sehrope** [comment]
The node-postgres driver uses the extended query protocol which splits things into separate parse / bind / execute steps: https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

**Comment by kellengreen** [comment]
Got it, thank you.

**Comment by esatterwhite** [comment]
I'm a little confused by the postgres docs on the extended query. The `bind` step in this case converts the above from

```sql
SELECT * FROM foo WHERE id = $1;  [100]
```
to 

```sql
SELECT * FROM foo WHERE id = 100
```

and the `execute` step is effectively sending the equivalent of a hard-coded query to postgres?
