### ISSUE TITLE
Same command used in PSequel and terminal not returning expected results.

### ISSUE THREAD

**Issue by TravJav** [brianc/node-postgres#1782]
I believe there may be something wrong with the lib. At first I thought it was the way I prepared my query but started testing it on different clients ( PSequel using Mac Osx , terminal mac/linux and pg admin) all of these are returning exactly what I expect - the only one that is not is this package, the results i'm receiving are just a [
    []
]

or rather empty rows when it should be returning 3 records. Please find the query I am using below.
```

`getRoutine(username, user_id) {
    return new Promise(function (resolve, reject) {
        const client = new pg.Client(connectionString);
        client.connect()
            .then(() => console.log('connected'))
            .catch(err => console.error('connection error', err.stack))
        const text = "SELECT EXISTS(SELECT relationship_status FROM relationships FULL OUTER JOIN users ON users.user_id = relationships.user_one_id OR users.user_id = relationships.user_two_id WHERE users.username = $1 OR users.user_id = $2 AND relationships.relationship_status = 1)"
        const values = [username, user_id]
        const query = client.query(text, values)
            .then(res => {
                if (res.rows[0].exists === true) {
                    // find way to do this in single query
                    const text = "SELECT routine.workout, routine.personal_record, routine.workout_id, routine.upload_date FROM routine LEFT OUTER JOIN users ON users.user_id = routine.owner_id  WHERE users.username = $1"
                    const values = [username]
                    const query = client.query(text, values)
                        .then(data => {
                            resolve(data.rows)
                        })
                        .catch(error => {
                            console.log(error)
                            reject();
                        })
                } else {
                    reject();
                }
            })
            .catch(error => {
                console.log(error)
                reject();
            })
    });
}`
```

**Comment by charmander** [comment]
What’s `username`? Is `if (res.rows[0].exists === true) {` being entered? Can you reduce this to a self-contained script, along the lines of the following, show exactly what it logs, and show exactly what you’re comparing it to in psql?

```js
"use strict";

const pg = require('pg');

(async () => {
    const client = new pg.Client(…);
    await client.connect();
    const result = await client.query(
        "SELECT * FROM routine LEFT JOIN users ON users.user_id = routine.owner_id \
         WHERE users.username = $1",
        ["string literal"]);
    console.log(result);
    client.end();
})();
```

**Comment by hardchor** [comment]
I'm observing the same with an `EXISTS` query, might be related?

```sql
SELECT *
FROM (VALUES ('Jim'), ('Jack'), ('John')) AS v (name)
WHERE NOT EXISTS(
  SELECT *
  FROM users u
  WHERE u.name = v.name
)
```

**Comment by TravJav** [comment]
@charmander the if (res.rows[0].exists === true) { just return a true or false this is working and not in question, although you're right i should have left this out. The only query that is behaving mal is the second one that your outlined in your snippet. I will create a detailed update once I am more available in the evening, thanks.

**Comment by TravJav** [comment]
![query](https://user-images.githubusercontent.com/16505078/49486474-95b89c80-f80c-11e8-8c8d-1b02e315d773.png)
Photo illustrates the same query I am using in the backend. This particular client is called PSequel (verson 1(1.5.3))using Mac high sierra 10.13.6 for my OS.  I have been using postman for the GET request but also my Angular 6 app; both are receiving the same result which are is an empty rows. 

Here you can find the simplified code. please keep in mind the param $1 is just holding a name. In This case it's a known user ( same user I used to get results back in other client app )

```
var pg = require('pg');
var production = require('../../Config/config')
const connectionString = production.amazon

class SetRoutine {

    getRoutine(username, user_id) {
        return new Promise(function (resolve, reject) {
            const client = new pg.Client(connectionString);
            client.connect()
                .then(() => console.log('connected'))
                .catch(err => console.error('connection error', err.stack))
           
                        const text = "SELECT routine.workout, routine.personal_record, routine.workout_id, routine.upload_date FROM routine LEFT OUTER JOIN users ON users.user_id = routine.owner_id  WHERE users.username = $1"
                        const values = [username]
                        const query = client.query(text,values)
                            .then(data => {
                                console.log(data.rows)
                                resolve(data.rows)
                            })
                            .catch(error => {
                                console.log(error)
                                reject();
                            })
                })
                .catch(error => {
                    console.log(error)
                    reject();
                })
 }
}

```

**Comment by TravJav** [comment]
Postman. Response from backend or the query in question.
![client_demo](https://user-images.githubusercontent.com/16505078/49487956-acfa8880-f812-11e8-8525-31814e3d1e30.png)

**Comment by TravJav** [comment]
@hardchor perhaps, I cannot give you a definitive answer though. My only recommendation would be to isolate the issue to this lib if you have not already done so. Check out the postgres client I mentioned for Mac if you're using that os ( super handy and light) http://www.psequel.com/

**Comment by charmander** [comment]
`%20helloKitty%20` and `helloKitty` are different.

**Comment by hardchor** [comment]
@TravJav yeah I did test it from the CLI and the same query produces different results, which is why I assumed it might be related to your issue.
