### ISSUE TITLE
client.query converts select items to lower-case

### ISSUE THREAD

**Issue by wickermoon** [brianc/node-postgres#1786]
Everytime I try to call

```
return this.pool.connect()
		.then(client =>
		{
			return client.query("SELECT clientId, userId FROM oauth_tokens WHERE token = $1", [accessToken])
			.then(result =>
			{
				client.release();
				return !!result.rows[0];
			})
			.catch(error =>
			{
				client.release();
				throw new Error(error.message);
			});
		});
```

pg returns with the following error: 
message: 'column "clientid" does not exist',
name: 'server_error',

And it is correct. clientid does not exist. It even asks me mockingly, whether I meant clientId, which...yes, I did mean and I also did write. What's happening here?

**Comment by charmander** [comment]
For posterity: you need to quote `"clientId"` and `"userId"` to preserve case.

…`!!result.rows[0]`?

```js
return this.pool.query('SELECT FROM oauth_tokens WHERE token = $1', [accessToken])
    .then(result => !!result.rows[0]);
```
