### ISSUE TITLE
Massive.js is not working with auto-increment fields

### ISSUE THREAD

**Issue by andrerpena** [brianc/node-postgres#1791]
Hi. Thanks for this fantastic tool.

I'm trying to run a very simple example: 

```
massive({
  host: '127.0.0.1',
  port: 5432,
  database: 'crm',
  user: 'hyperforms',
  password: 'hyperforms'
}).then((db: any) => {
  db.contact.save({
    full_name: 'andre pena'
  }).then((andre: any) => {
    console.log(andre)
    process.exit(0)
  }).catch((ex: any) => {
    console.log(ex)
    process.exit(1)
  })
})

```

This is my `contact` table:

```
create table contact
(
  id   serial not null
    constraint contact_pk
      primary key,
  text integer
);

```

`db.contact` has an `id` column which is an auto-increment primary key. This is what is happening:

- If I specify the `id`: It works
- If I don't specify the `id`: Save returns an empty array `[]`, with no errors but nothing is inserted.
- If I specify a null or undefined `id`: It fails with these details: `Failing row contains (null, null).`

Any idea on how to fix this?

Thank you very much

**Comment by charmander** [comment]
`text integer` but you’re trying to insert a `full_name`? Anyway, this issue probably belongs on https://github.com/dmfay/massive-js/issues.

**Comment by vitaly-t** [comment]
@andrerpena You should open it against Massive.js, and not here.

**Comment by andrerpena** [comment]
@vitaly-t Haha what's got into me. I though I was there. 😂 Thanks mate.
