### ISSUE TITLE
Promise/Async connect() returning undefined client.

### ISSUE THREAD

**Issue by chriseaton** [brianc/node-postgres#1795]
Using the latest version: 7.7.1
node 10.14.2

When I try to utlize any of the async code -either via async/await or via promises, the client always comes back undefined. What's odd is it does definitely connect after an await, because if I do a pool.query it succeeds (but only if I call connect) but no client object is ever returned. Super weird.

```
pool.connect()
  .then(client => {
//client = undefined
...
});
```
    
```
async function() {
let client = await pool.connect();
//client = undefined.
}
```

**Comment by chriseaton** [comment]
If I use the callback method, it works fine:

```
SQLPool.connect((err, client, done) => {
    //client = { ... } not undefined!
});
```

no idea what I'm missing - any help would be appreciated.

**Comment by vitaly-t** [comment]
@chriseaton In the meantime, if proper use of TypeScript is a priority in your project, consider using [pg-promise], which ships with embedded [TypeScript] support.

[pg-promise]:https://github.com/vitaly-t/pg-promise
[TypeScript]:https://github.com/vitaly-t/pg-promise/tree/master/typescript

**Comment by chriseaton** [comment]
Looks like it was something related to the outer function not being callet/used in a async way - never quite found the root cause, but I was using it with express within a template rendering function, which ultimately needed a special setup to run asynchronously. Once we updated the rendering code pg worked as expected.
