### ISSUE TITLE
pool.end() not executing (seemingly)

### ISSUE THREAD

**Issue by johnrichardrinehart** [brianc/node-postgres#1802]
I have something like the below in my codebase. The callback in `pool.end()` doesn't get called before the program terminates. If I move `process.exit(0)` into the callback like
```js
pool.end(() =>
  console.log('Closed pool.');
  process.exit(0);
});

```
then my program just hangs, waiting to execute that callback. What's going on?

```js
const { Pool } = require('pg');
let pool = new Pool();

pool.connect()
    .then(
        (success) => console.log('Connected successfully.'),
        (error) => console.log('Failed to connect successfully.'))

process.on('SIGINT', () => {
    pool.end(() => {
        console.log('Closed pool.');
    });
    process.exit(0);
})
```

**Comment by sehrope** [comment]
You're not releasing the connection you retrieved via `pool.connect()`. The `pool.end()` function does not close connections that are in use by your app. It waits for them to gracefully finish. See https://github.com/brianc/node-pg-pool/blob/d7f6ed0c7cb7f546211ae3c90e6f1d50b7bcd383/index.js#L120

Either stick to using `pool.query(...)` (preferred as it automatically handles all of this) or ensure that anything that calls `pool.connect()` eventually releases its connection.

Usual practice for standalone scripts is to just `process.exit(...)` and not bother actually ending the pool. When the program exits the sockets will get closed by the OS. Ending the pool is more for when you're dynamically creating a pool in an app that will not be exiting when the work with the pool is finished. If you're gonna exit the app without waiting for specific things to complete then you might as well just `process.exit(...)` immediately.

**Comment by johnrichardrinehart** [comment]
@sehrope, I completely understand. I had thought that `.connect()` was required to run before any `.query()`s could be executed. Of course this isn't the case. I exclusively use `pool.query()` now and I no longer have the problem described above.
