### ISSUE TITLE
client.end() when client has query in flight causes unhandled promise rejection

### ISSUE THREAD

**Issue by jedwards1211** [brianc/node-postgres#1803]
There are similar issues about unhandled promise rejections on `Pool`s, but the advice there is to add an `error` listener to the `Pool`.

However, when using just a `Client` (not a `Pool`), even if the `Client` has an `error` listener and query promise rejection is caught, ending it while a query is in flight will cause an unhandled promise rejection within `pg` internals:

```js
UnhandledPromiseRejectionWarning: Error: Connection terminated
    at Connection.con.once (/Users/andy/postgres-shard-coordinator/node_modules/pg/lib/client.js:199:9)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Connection.emit (events.js:208:7)
    at Socket.<anonymous> (/Users/andy/postgres-shard-coordinator/node_modules/pg/lib/connection.js:76:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:557:12)
```
Obviously this runs the unnecessary risk of crashing the process in future versions of node.

@brianc @charmander there should be no problem with propagating the connection terminated error to the in-flight query, right?

**Comment by charmander** [comment]
> there should be no problem with propagating the connection terminated error to the in-flight query, right?

That’s probably what’s happening – a promise being created for a query somewhere that you’re not handling.

Can you create a minimal script that produces this error?

**Comment by jedwards1211** [comment]
I haven't been able to get to the bottom of it -- I was observing very weird behavior where the rejection was unhandled by the surrounding `try`/`catch` block, yet adding `.catch(() => {})` within the `try` would handle the error.  It was one of those situations where I wondered if Babel or node itself has a bug...sadly, I've already ended up refactoring away the code that was causing the issue.
