### ISSUE TITLE
I don't realy understand why my insert querie doesnt work

### ISSUE THREAD

**Issue by Jaman-dedy** [brianc/node-postgres#1805]
I'm building up a nodejs api, my first step was to set the api with data structure and all endpoints were working right good, but now I want to implment crud with persistance and opted to use posgresql, all config runs good because the get endpoint works with no matter but i'm blocked with the post endepoint. can any one help please.... find below my code

```js
router.post('/', (req, res, next) => {
  const data = {
    firstname: req.body.firstname,
    lastname: req.body.lastname,
    othername: req.body.othername,
    email: req.body.email,
    phoneNumber: req.body.phoneNumber,
    username: req.body.username,
    registered: req.body.registered,
    isAdmin: req.body.isAdmin
  };

  pool.connect((err, client, done) => {
    const query = 'INSERT INTO users(firstname, lastname, othername, email, phoneNumber, username, registered, isAdmin) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *';
    const values = [data.firstname, data.lastname, data.othername, data.email, data.phoneNumber, data.username, data.registered, data.isAdmin];

    client.query(query, values, (error, result) => {
      done();
      if (error) {
        res.status(400).json({ error });
      }
      res.status(202).send({
        status: 'SUccessful',
        result: result.rows[0]
      });
    });
  });
});
```
find below the screenshot of the same code for good previewing
![image](https://user-images.githubusercontent.com/46047244/50829040-db0c4480-134b-11e9-84e4-07600e688e3f.png)

here is the concer table (users) with colums
![user](https://user-images.githubusercontent.com/46047244/50828440-1574e200-134a-11e9-84c9-ae458b8a9882.PNG)

when I try to send the request body via postman, I get back the 400 error status and the folowing output in the body

![image](https://user-images.githubusercontent.com/46047244/50828635-9b912880-134a-11e9-90ba-dcfd02b6a82e.png)

and the same code throw in my editor this error

![image](https://user-images.githubusercontent.com/46047244/50828719-d3986b80-134a-11e9-873d-5f9628fc5fb8.png)

Need a help please, I've been trying with any means but i'm still blocked.... thanks in advance

**Comment by sehrope** [comment]
Wrap your code example with three backticks so the entire block gets formatted (see [here](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code)).

Your error case isn't returning from the function so it continues to the success case which tries to access the `.rows`  property.

```js
if (error) {
    res.status(400).json({ error }); // <== this should be "return res.status(...)"
}
```

Separately, rather than manually managing the connection pool use via the connect function, use `pool.query(...)`. It's much easier and less error prone.

**Comment by brianc** [comment]
I formatted your code for you to make it more readable.

@sehrope is right on - you need an else statement.  Also, [this](https://node-postgres.com/api/pool#pool-query-callback-err-error-result-pg-result-gt-void) is a helpful thing when you're not doing transactions.

**Comment by Jaman-dedy** [comment]
I try to do as said and I modified the code

```
router.post('/', (req, res, next) => {
  const { firstname, lastname, othername, email, phoneNumber, username, registered, isAdmin } = req.body;

  pool.query('INSERT INTO users (firstname, lastname, othername, email, phoneNumber, username, registered, isAdmin) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)', [firstname, lastname, othername, email, phoneNumber, username, registered, isAdmin], (error, results) => {
    if (error) {
      throw error;
    }
    res.status(201).send('User added with');
  });

});

```
but it throw a new error

![image](https://user-images.githubusercontent.com/46047244/50850264-0742b800-1382-11e9-845b-d5d1a1e3e41e.png)
