### ISSUE TITLE
blocking node with large result sets

### ISSUE THREAD

**Issue by houmanb** [brianc/node-postgres#181]
We have a table with more than 1x10ˆ6 entries. We use the evented API for data retrieval. 
Although ignoring the row event (for debugging purposes) the node server is blocked during data processing.
Using the non-native mode the node server is not blocked but responding extremely slow (up to 5 secs instead of 100 mis).
In the native mode the node server is completely blocked and allocates more than 2Gig of RAM.

In order to dive into the problem we tried to use your own "large-datatset-bench.js" with slightly different number of rows (1x10ˆ6).
The execution times with respect to number of items to be inserted does not increase in a linear manner (as expected).

What we have noticed during both test cases was the fact that the Postgres backend processes did not use more than 1.5 % of CPU time.

**Comment by 131** [comment]
Hi @brianc, sorry to bother you here.
It's 2018, node 10 is going to be LTS, and async generators are here.

Do you have plans to integrate async generators cursors into pg-cursors ?

**Comment by davedoesdev** [comment]
This also works, but I'm not sure of the effect on Postgres itself:

```diff
--- lib/connection.js.orig	2019-05-01 09:35:31.971886784 +0100
+++ lib/connection.js	2019-05-01 09:37:31.497934470 +0100
@@ -113,17 +113,20 @@
 
 Connection.prototype.attachListeners = function (stream) {
   var self = this
-  stream.on('data', function (buff) {
-    self._reader.addChunk(buff)
-    var packet = self._reader.read()
-    while (packet) {
-      var msg = self.parseMessage(packet)
-      var eventName = msg.name === 'error' ? 'errorMessage' : msg.name
-      if (self._emitMessage) {
-        self.emit('message', msg)
+  stream.on('readable', function () {
+    var buff;
+    while (buff = this.read()) {
+      self._reader.addChunk(buff)
+      var packet = self._reader.read()
+      while (packet) {
+        var msg = self.parseMessage(packet)
+        var eventName = msg.name === 'error' ? 'errorMessage' : msg.name
+        if (self._emitMessage) {
+          self.emit('message', msg)
+        }
+        self.emit(eventName, msg)
+        packet = self._reader.read()
       }
-      self.emit(eventName, msg)
-      packet = self._reader.read()
     }
   })
   stream.on('end', function () {
```
