### ISSUE TITLE
Not possible to set custom types on a query anymore

### ISSUE THREAD

**Issue by mitar** [brianc/node-postgres#1810]
[This line](https://github.com/brianc/node-postgres/blob/3828aa86081491282c118884c245b4a19619f02e/lib/query.js#L35) gets passed types, but [constructor does not even use it](https://github.com/brianc/node-postgres/blob/72db7902fa9edb5fb9d436c27379dd74d4c9452f/lib/result.js#L15). It is possible currently to set custom types only per client, not per query anymore. :-(

**Comment by charmander** [comment]
Fixed by #1825 (pg@7.10.0).
