### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by hnasr** [brianc/node-postgres#1812]
I'm running into trouble using node-postgres. I'm using Node v10.15.0 and pg@7.8.0  on my mac 

here is my code
```javascript
const {Client} = require('pg')
const client = new Client()
client.connect(
    {
        user: 'postgres',
        host: 'husseinmac',
        database: 'husseindb',
        password: 'postgres',
        port: 5432,
      }
)
client.query('SELECT NOW()')
.then(result => console.log(result))
.catch(e => console.error(e.stack))
.finally(() => client.end())

```

I'm getting this error when I run the code 
I also tried all the sample code on the node-postgres site and all of them gave the same error.

/Users/HusseinNasser/javascript/nodepg/node_modules/pg/lib/client.js:140
      return callback(err)
             ^
TypeError: callback is not a function
    at Connection.connectingErrorHandler (/Users/HusseinNasser/javascript/nodepg/node_modules/pg/lib/client.js:140:14)

Any help would be approciated. 
Thanks!

**Comment by sehrope** [comment]
The object with connection details goes in the `pg.Client(...)` constructor and `client.connect()` is called either with no parameters (to return a Promise) or with a single function (for callback style):

```js
const client = new Client({
        user: 'postgres',
        host: 'husseinmac',
        database: 'husseindb',
        password: 'postgres',
        port: 5432,
});
client.connect()
  .then(() => {
    // Client is now connected
  })
  .catch((err) => {
    console.error('Error connecting: %s', err);
  });
```

**Comment by hnasr** [comment]
Thanks @sehrope for the prompt reply, that did the trick and make sense! closing this issue..
