### ISSUE TITLE
LOAD DATA LOCAL INFILE support

### ISSUE THREAD

**Issue by shlomitgilo** [brianc/node-postgres#1817]
Hi,
I get a syntax error, trying to execute:
_LOAD DATA INFILE 'data.csv' INTO TABLE myTbl
    FIELDS TERMINATED BY ',' 
    LINES TERMINATED BY '\r\n';_

Isn't this command supported?

(Trying LOAD DATA LOCAL is not helping)

**Comment by sehrope** [comment]
That's not a driver issue. That syntax is specific to MySQL / MariaDB. It won't execute on a PostgreSQL database.

If you want to stream a large amount of data from a file into a table check out the COPY command. You can use it with the pg module via the helper pg-copy-streams: https://github.com/brianc/node-pg-copy-streams
