### ISSUE TITLE
db.query vs client.query inside a transaction

### ISSUE THREAD

**Issue by Rc85** [brianc/node-postgres#1819]
I'm sort of stoked as to why db.query executes asynchronous with client.query inside a transaction.

     (async() => {
         try {
              await client.query('BEGIN');
              await client.query('UPDATE users SET user_id = 1');
              let user = await db.query('SELECT * FROM users);
               
              await client.query('COMMIT');
         } catch (e) {
              await client.query('ROLLBACK');
              throw e;
        }
     }

In this case, db.query are getting results before the above UPDATE query completes. Does async/await not play a role here? I brought up this issue because in my actual code, the line `let user` is actually `let user = controller.session.retrieve(req.session.user.user_id)`, and in it, it uses db.query.

**Comment by charmander** [comment]
`client.query` uses the client that’s in the transaction. `db.query` uses some other client from the pool, so the effects of the transaction aren’t visible to it in the `SELECT * FROM users` that runs before the commit.
