### ISSUE TITLE
Transaction is aborted

### ISSUE THREAD

**Issue by gisticinc** [brianc/node-postgres#1826]
I am using [pg/transaction][1] to handle a complex process. It can be simplified as this:

    async() => {
        const client = await new Pool().connect();
        try {
            await client.query("BEGIN");
            await client query("query 1");
            try {
                await client query("query 2");
                // Some error happen
            } catch(err) {
                console.log(err);
            }
            await client query("query 3");
            await client query("COMMIT");
        } catch(err) {
            await client.query("ROLLBACK");
        } finally {
            client.release
        }
    }

The problem is that when query2 returns an error, the client fails to execute query3 even I don't Rollback the process. The error it returns is `current transaction is aborted, commands ignored until end of transaction block`. Is this what supposed to happen? If so, how can I ignore the error and keep the transaction running?

  [1]: https://node-postgres.com/features/transactions

**Comment by charmander** [comment]
> Is this what supposed to happen?

Yes.

> If so, how can I ignore the error and keep the transaction running?

Create a [savepoint][1] before the query that might fail and roll back to it in the `catch`.

[1]: https://www.postgresql.org/docs/devel/sql-savepoint.html

**Comment by EzzatOmar** [comment]
Is there there a way to return the original error instead of `current transaction is aborted, commands ignored until end of transaction block`?

**Comment by charmander** [comment]
@EzzatOmar Not that I know of. You should generally handle the error when it first happens.
