### ISSUE TITLE
Client does not return results when connecting over Unix sockets

### ISSUE THREAD

**Issue by supriyo-biswas** [brianc/node-postgres#1827]
I'm trying to use node-redis over an Unix socket and retreive a result, as shown:

```js
const { Client } = require('pg')
const client = new Client({host: '/var/run/postgresql'})
client.query('select now()', () => console.log(arguments))
```

Unfortunately, this never returns a result. However, when I try to connect using the `psql -h /var/run/postgresql` command, I can do so perfectly.

Am I missing something here?

**Comment by charmander** [comment]
The client needs to be connected:

```js
client.connect(error => {
    if (error) throw error;
    client.query('select now()', (...args) => console.log(...args))
});
```
