### ISSUE TITLE
Avoiding sending the same value multiple times

### ISSUE THREAD

**Issue by gajus** [brianc/node-postgres#1834]
I am planning to implement this feature in Slonik:

https://github.com/gajus/slonik/issues/5

and I was wondering if there was any interest to instead implement this at the `node-postgres` level or if there is a reason why this is not being done already?

**Comment by gajus** [comment]
Turns out there is a good reason not to do it. Updated the original issue.

**Comment by sehrope** [comment]
Combining duplicate parameter values together would be out of scope for the pg driver as it's meant to execute commands as provided.

Also, PostgreSQL allows you to reference the same parameter multiple times so it's only sent once on the wire:

```js
const result = await pool.query('SELECT $1, $1, $1, $1, $1', ['foobar']);
```
