### ISSUE TITLE
How to configure types only for a particular instance of node-postgres?

### ISSUE THREAD

**Issue by gajus** [brianc/node-postgres#1838]
It appears that the only way to configure type parser is by doing so globally, i.e.

```js
var types = require('pg').types
types.setTypeParser(20, function(val) {
  return parseInt(val)
});

```

– https://github.com/brianc/node-pg-types

I would like to restrict type parsing to a particular connection.

Is there an API at the moment to do so?

**Comment by gajus** [comment]
This could be as simple as allowing to override `types`.

https://github.com/brianc/node-postgres/blob/fcd0f02210f532bf2d823ea05105f4aaade389eb/lib/index.js#L34

**Comment by charmander** [comment]
`pg.types` is a convenience reexport; pg itself doesn’t use that property. You can override type parsing by configuration (i.e. per client or pool) by passing something that satisfies the necessary interface in the `types` property, the most convenient something [I’m aware of][1] being a `TypeOverrides` from [pg/lib/type-overrides.js][2]:

```js
const TypeOverrides = require('pg/lib/type-overrides');

const OID_INT8 = 20;

const types = new TypeOverrides();
types.setTypeParser(OID_INT8, BigInt);

const pool = new pg.Pool({
    ⋮
    types,
});

const client = new pg.Client({
    ⋮
    types,
});
```


[1]: https://github.com/charmander/pg-auto/blob/eb91aed645e19073fc5428bd67d5c57393b543c4/pool.js#L5
[2]: https://github.com/brianc/node-postgres/blob/fcd0f02210f532bf2d823ea05105f4aaade389eb/lib/type-overrides.js

**Comment by gajus** [comment]
Is there a way to override `TypeOverrides` after pool has been instantiated?

```js
const client = new pg.Client({});

client._types = types;

```

The latter does not seem to do the trick.

Will debug this further on my own (seems like I could definitely override the query getTypeParser, https://github.com/brianc/node-postgres/blob/fcd0f02210f532bf2d823ea05105f4aaade389eb/lib/client.js#L459), but if there is a better way, please let me know.

**Comment by charmander** [comment]
> Is there a way to override `TypeOverrides` after pool has been instantiated? … `new pg.Client`

On a pool or a client? What you wrote should work fine for a *client* for queries after the assignment. `Client.prototype.setTypeParser`/`Client.prototype.getTypeParser` exist too. On a pool, you can assign arbitrary client options after instantiation, so set `pool.options.types`.

**Comment by gajus** [comment]
Thank you

**Comment by gajus** [comment]
Just in case anyone comes across this, if you are using `pg-native`, you also need to override `client.native._types`. See https://github.com/gajus/slonik/commit/009a2124264d267681ed9a680db10d94e3990dae.
