### ISSUE TITLE
How to perform row level security on prostgreSQL?

### ISSUE THREAD

**Issue by akdj** [brianc/node-postgres#1845]
Hello!

I am trying to secure the access control of my service serve with an authentication by user, and also by setting a [row level security](https://www.postgresql.org/docs/9.5/ddl-rowsecurity.html) on my database postgreSQL.

However I don't know how to perform it with pg. how to set the user identity to one specific user in the query to the db?

Are there someone who already try this?

thank you

**Comment by sehrope** [comment]
You'll likely need to switch roles on the fly based upon the executing user. You can have a single set of credentials for the pool with the ability to SET ROLE to the role specific to the active user. 

The pg driver doesn't handle things like this directly but you can add your own wrapper to simplify things. See https://github.com/brianc/node-postgres/issues/1598#issuecomment-374919852 for one example of how to handle this.

**Comment by akdj** [comment]
Hi, 
thank you!  I will try it :smile:

**Comment by akdj** [comment]
I close it for the moment, will re open it if i need help :)
