### ISSUE TITLE
returned results structure and fields + simple escaping?

### ISSUE THREAD

**Issue by foo123** [brianc/node-postgres#1846]
The documentation does not mention the structure of the result object from a query apart from `.rows` field (if a select query). Specificaly how can I retreive last insertId (if insert query) or number of affected rows if update/delete/insert query? These should be mentioned in the documentation.

Also is there a method for simple escaping of (string) values (for example `node-mysql2` client has similar methods to escape both values and ids/fields). Is there similar method for pg client?

I am making a DBAL for node which handles various drivers and I would like to normalise the query results from all those drivers into a result object of my own.

Thank you!

**Comment by charmander** [comment]
> The documentation does not mention the structure of the result object from a query apart from .rows field (if a select query). … number of affected rows if update/delete/insert query

That is documented: https://node-postgres.com/api/result#-code-result-rowcount-int-code-

> how can I retreive last insertId

In PostgreSQL, you use `RETURNING id` as part of the query. It’s not a driver-specific thing.

> Also is there a method for simple escaping of (string) values (for example node-mysql2 client has similar methods to escape both values and ids/fields). Is there similar method for pg client?

[pg-format](https://github.com/datalanche/node-pg-format) exists, but you should use parameters.

**Comment by foo123** [comment]
Thanks for the answer. Did not find this documentation earlier. Very helpful.

For `lastInsertId` i use another approach, if last query is `INSERT` or `REPLACE` query i do another subquery `SELECT lastval()` which returns last insert id. Thus user using the DBAL does not have to explicitly return the id or alter her original queries.
