### ISSUE TITLE
Build query using pg-format

### ISSUE THREAD

**Issue by richlewis14** [brianc/node-postgres#1853]
Hi

Is it possible to construct my query dynamically depending upon what parameters are passed through, so if I pass this Object to the below method

    QueryObject {
      day: 'tomorrow',
      leagueName: 'England Premier League',
      homeTeam:
        { columnOne: 'column_1',
          columnOneValue: '80' },
     awayTeam:
       { columnOne: 'column_2',
         columnOneValue: '100' } 
    }

    function buildConditions(queryObject) {
      const columns = [];
      const conditions = [];
      const values = [];

      if (typeof queryObject.homeTeam.columnOne !== 'undefined') {
        columns.push(queryObject.homeTeam.columnOne);
        conditions.push('%I = $1');
        values.push(queryObject.homeTeam.columnOneValue);
      }

      if (typeof queryObject.awayTeam.columnOne !== 'undefined') {
        columns.push(queryObject.awayTeam.columnOne);
        conditions.push('%I = $2');
        values.push(queryObject.awayTeam.columnOneValue);
      }

      return {
        where: conditions.length ? conditions.join(' AND ') : '1',
        values,
        columns,
      };
    }

It seems like I am pretty close but i get the error `Error: too few arguments`

    const conditions = buildConditions(queryObject);
    console.log(conditions);
    // { where: '%I = $1 AND %I = $2, values: [ '100', '100' ], columns: [ 'column_1', 'column_2' ] }
    const string = 'SELECT * FROM fixtures WHERE ' + conditions.where + ', ' + conditions.columns.join(', ');
    console.log(string)
    // SELECT * FROM fixtures WHERE %I = $1 AND %I = $2, column_1, column_2
    sql = format(string);

Seems I get the error when passing the string into `format`

What I don't understand at this point is if I was to construct the query as below, it works
    
    sql = format("SELECT * FROM fixtures WHERE %I = $1 AND %I = $2", queryObject.homeTeam.columnOne, queryObject.awayTeam.columnOne);

**Comment by charmander** [comment]
```js
sql = format('…, column_1, column_2');
```

isn’t the same as

```js
sql = format('…', column_1, column_2);
```

You have to pass those column names as *arguments* to `format`, like the error said.

**Comment by richlewis14** [comment]
Thank you for the answer, any ideas on how I pass the names as arguments when trying to piece together the query with different components so to speak

**Comment by charmander** [comment]
```js
format('SELECT * FROM fixtures WHERE ' + conditions.where, ...conditions.columns)
```

Consider also using a query builder

**Comment by richlewis14** [comment]
Thank you so much, cannot tell you how much this helps, and that ... notation in ES6, so powerful
