### ISSUE TITLE
Rollback issues

### ISSUE THREAD

**Issue by madeken** [brianc/node-postgres#1854]
This program will never terminate, as the rollback query infinitely blocks:

```
const { Pool } = require('pg')
const pool = new Pool()

async function main() {

  const client = await pool.connect()

  try {
    await client.query('BEGIN');
    await client.query('SELECT $1', [{x: 1n}]);
    await client.query('COMMIT')
  } catch (e) {
    await client.query('ROLLBACK')
    throw e
  } finally {
    client.release()
  }

  console.log('great success! Terminated!');
}

main();
```

Note, the value `1n` works,  `{x: 1}` works, but `{x: 1n}` is where the problems start

**Comment by sehrope** [comment]
That's a syntax error:

```js
> const params = [{x: 1n}];
const params = [{x: 1n}];
                    ^

SyntaxError: Invalid or unexpected token
```

It's not running any of it as the main function is not successfully parsed as a function. Add a print statement (`console.log('Starting...')`) as the first line of `main()` and you'll see that it's not printed.

**Comment by madeken** [comment]
@sehrope  You might want to update your version of node =)  `1n` is just short for `BigInt(1)` which is something only supported in recent versions of v8

**Comment by madeken** [comment]
It is throwing an error actually: `TypeError: Do not know how to serialize a BigInt` the problem is that now the code goes to do a `ROLLBACK` and just hangs there. I assume when throwing an error, it's left the `client` in a bad state.
