### ISSUE TITLE
I cant rollback inside a transaction

### ISSUE THREAD

**Issue by gustavopiucco** [brianc/node-postgres#1859]
```
const client = await pool.connect()
try {
  await client.query('begin')
  (...)
  if (condition) {
    await client.query('rollback') //does not work
  }
  (...) //queries here are still being committed
  await client.query('commit')
}
catch (e) {
  await client.query('rollback')
}
finally {
  client.release()
}
```

How do I force rollback inside a transaction if a condition matches?

**Comment by vitaly-t** [comment]
It should work, if you use `await` in front.

**Comment by gustavopiucco** [comment]
> It should work, if you use `await` in front, to synchronize the workflow.

Unfortunately it does not work. I was able to make it work by throwing an exception instead of sending rollback, so the commit is not sent and in catch block  the rollback is done, theoretically....

**Comment by gustavopiucco** [comment]
Ops, thee lack of await was typos only... still not working.

**Comment by joelmukuthu** [comment]
@gustavopiucco, you need to `return` to halt execution, or add an `else` to the `if` statement

**Comment by gustavopiucco** [comment]
> @gustavopiucco, you need to `return` to halt execution, or add an `else` to the `if` statement

Yep, I was throwing an exception to stop the execution. But any 'commit' sent after 'rollback' should not be ignored by Postgres? Would not that be the basics of running a transaction? I got confused

**Comment by charmander** [comment]
`ROLLBACK` ends your transaction. Statements continue to work after a transaction like they do before a transaction. `COMMIT` does nothing outside of a transaction (https://www.postgresql.org/docs/current/sql-commit.html#id-1.9.3.53.7), but even if it were an error, the queries before it would take effect.
