### ISSUE TITLE
How to create a "set" in JS

### ISSUE THREAD

**Issue by greenpdx** [brianc/node-postgres#1865]
Postgres has a column in (set) that allows multiple values.
example
```
SELECT * FROM table WHERE col in (1,2,3,4,5);
```
so if col = 1 or 2 or 3 or 4 or 5 is true.
I have tried
```
let set = [2,3,4]
pool.query('SELECT * FROM main WHERE idx in ($1)', [set])
pool.query('SELECT * FROM main WHERE idx in ($1)', set)
pool.query('SELECT * FROM main WHERE idx in $1', [set])
pool.query('SELECT * FROM main WHERE idx in $1', set)
```
1.  invalid input syntax for integer: "{"2","3","4"}"
2. error: bind message supplies 3 parameters, but prepared statement "" requires 1
3.  error: syntax error at or near "$1"
4. error: syntax error at or near "$1"

How do you do this?

**Comment by sehrope** [comment]
Use `ANY`: https://www.postgresql.org/docs/current/functions-comparisons.html#id-1.5.8.28.16

```js
let set = [2,3,4];
pool.query('SELECT * FROM main WHERE idx = ANY($1)', [set]);
```

**Comment by greenpdx** [comment]
Great it works! Thanx
