### ISSUE TITLE
Can't insert more than two values into query

### ISSUE THREAD

**Issue by aarondtaveras** [brianc/node-postgres#1870]
Hi, I'm trying to insert a record into my database that has 7 columns, and therefore 7 VALUES within the `values: [ ]`. 

Here is the schema for my `merchant` table: 

 ```
merchant_id | first_name | addr_id | fico | dob | ssn | phone | email | last_name
-------------+------------+---------+------+-----+-----+-------+-------+-----------
```

My insertion function is as follows: 

```
async function insertMerchant(merchant){
    const query = {
        text: 'INSERT INTO merchant(first_name,last_name,dob) VALUES($1,$2,$3)',
        values: [
                merchant.first_name,
                merchant.last_name,
                // 'merchant.dob'
                ]
        }
pool.query(query,(err,res) => {
    if(err){
        return err;
    } else {
        return res.rows[0];
    }
})
}
```

This code works fine as intended, however when I uncomment the `merchant.dob` line all of a sudden no records are inserted into my DB. There is no error thrown, and my server returns a 200 status. My db just fails to be updated with any of the new values. I have tested to see if it is the parameters, but any combination of database columns works, i.e: if I insert with merchant.dob and merchant.first_name it works, so the issue is not specifically with the `dob` column. 

**A record is only inserted when I have two or less parameters**. Is there something I missed in the docs or is this a weird bug?

**Comment by charmander** [comment]
`return err;` doesn’t do anything. Did you mean:

```js
const res = await pool.query(query);
return res.rows[0];
```

**Comment by aarondtaveras** [comment]
@charmander You're right, returning `err` didn't do anything. I assumed that by returning `err` I'd return a rejected promise implicitly, but that wasn't the case. When simply returning `res.rows[0]` I'm greeted by proper errors (finally!) -- however catching these errors are going uncaught. Thanks for the catch!
