### ISSUE TITLE
how to check for pg-native without triggering console.error message

### ISSUE THREAD

**Issue by kevinburkenotion** [brianc/node-postgres#1871]
See https://github.com/DataDog/dd-trace-js/issues/522, the library tries to wrap pg-native calls, but if pg-native is not installed this triggers a console error.

**Comment by vitaly-t** [comment]
So why did you open an issue here? Check for if pg-native is installed on your side, and that's it.

https://stackoverflow.com/questions/11600684/check-if-a-node-js-module-is-available

**Comment by chadfurman** [comment]
What do you mean why?  When I use node-postgres, it throws an error during runtime:

![image](https://user-images.githubusercontent.com/635170/57201888-e6bfee80-6f6c-11e9-9314-abea4aec3be7.png)

Why are you depending on a library that you're not including?

**Comment by vitaly-t** [comment]
Looks like you didn't install `pg-native` properly. Try removing `node_modules`, and reinstall everything, and then `pg-native` also. The latter definitely missing.

**Comment by charmander** [comment]
It looks like the linked bug is fixed.
