### ISSUE TITLE
Provide "no-op" driver for helping write unit tests for query builders

### ISSUE THREAD

**Issue by oranoran** [brianc/node-postgres#1878]
Users could use help from knex in unit testing their own query-building code.

Unit tests can look like this:
1. Init knex with a 'unittest' driver (and any of the supported dialects)
2. Build and run some query with knex
3. Ask knex what the generated query was, and get it as a simple, user-friendly string
4. Compare the generated query with an expected query

For the last 2 steps, I already have some code which can be used. This code is used today with knex.on('query') to format any query into a nice string, including embedding of bind variables right into the query string for developer convenience. Pasting this code in a comment.

**Comment by oranoran** [comment]
```JavaScript
function toString(knexSqlWithBindings) {
  const sql = breakToLines(knexSqlWithBindings.sql);
  const sqlParts = sql.split('?');
  const result = interleaveBindings(sqlParts, knexSqlWithBindings.bindings);
  return result.join('');
}

function breakToLines(rawSql) {
  const withLineBreaks = rawSql.replace(
    / (and|where|from|group by|having) /g,
    "\n $1 "
  );
  const withBetweenUnbroken = withLineBreaks.replace(/( between .*?)\n( and)/gm, "$1$2");
  return withBetweenUnbroken;
}

function interleaveBindings(sqlParts, bindings) {
  return bindings.map(bindingToString).reduce(function (arr, v, i) {
    return arr.concat(v, sqlParts[i + 1]);
  }, [sqlParts[0]]);
}

function bindingToString(b) {
  if ((typeof b) === 'number') {
    return b;
  } else if (b instanceof Date) {
    return `'${b.toISOString()}'`;
  } else {
    return `'${b}'`;
  }
}
```

**Comment by vitaly-t** [comment]
It won't much use for the Prepared Statements, as those are formatted by the server.

**Comment by charmander** [comment]
> Users could use help from knex in unit testing their own query-building code.

Did you mean to raise this issue in knex, then? pg doesn’t include a query builder.
