### ISSUE TITLE
Ability to force *not* loading native client

### ISSUE THREAD

**Issue by gabegorelick** [brianc/node-postgres#1894]
node-postres supports setting `NODE_PG_FORCE_NATIVE` to force the loading of the native client, but there's no way to force it to *not* load the native client:

```js
if (typeof process.env.NODE_PG_FORCE_NATIVE !== 'undefined') {
  module.exports = new PG(require('./native'))
} else {
  module.exports = new PG(Client)

  // lazy require native module...the native module may not have installed
  module.exports.__defineGetter__('native', function () {
    delete module.exports.native
    var native = null
    try {
      native = new PG(require('./native'))
    } catch (err) {
      if (err.code !== 'MODULE_NOT_FOUND') {
        throw err
      }
      /* eslint-disable no-console */
      console.error(err.message)
      /* eslint-enable no-console */
    }
    module.exports.native = native
    return native
  })
}
```

This can cause spurious warnings about pg-native module not found. See https://github.com/sequelize/sequelize/issues/3781 for an example caused by cloning node-postgres objects.

Potential solution: support a `NODE_PG_NO_LOAD_NATIVE` environment variable. Setting this would cause the `native` getter to not be defined. Setting both `NODE_PG_NO_LOAD_NATIVE` and `NODE_PG_FORCE_NATIVE` could throw an error. 

I'm happy to throw together a PR if there's support for something like this.

**Comment by seeden** [comment]
I see Cannot find module 'pg-native' in my logs. This will help

**Comment by rasilva-mission** [comment]
Does anyone know how to run pg without 'pg-native'? 
`ERROR in ./node_modules/pg/lib/native/client.js
Module not found: Error: Can't resolve 'pg-native' in 'C:\Users\xxxxxx\Documents\projects\xxxxxx\node_modules\pg\lib\native'`

This project compiles electron windows app and I don't want to include the native module just need client.

**Comment by imjordanm** [comment]
I am looking for this same solution. All I need is a way of not forcing pg-native, which I can't use because of its libpq dependency causing build failures. Like OP said, if there was an environment variable to bypass the above lazy require module, that would be a life-saver. The last version that works without pg-native is 3.6.4, but that has it's own issues for me with a missing helper.js file.

**Comment by charmander** [comment]
@imjordanm Last version of what? pg doesn’t require pg-native.

**Comment by imjordanm** [comment]
It does, if you look at the code OP posted there is no way of getting around require("./native") which in turn calls pg-native. 

This is the error code unless you install pg-native:

ModuleNotFoundError: Module not found: Error: Can't resolve 'pg-native' in '/mnt/d/Backup/Jordan/Jordan/Web/projects/gamifynow/node_modules/pg/lib/native'

The issue for me is that pg-native has libpq as a dependency and I need to apt-get libpq-dev in order for it to work, which I can't when hosting on Netlify. So I can't use pg-native.

**Comment by charmander** [comment]
> It does, if you look at the code OP posted there is no way of getting around require("./native") which in turn calls pg-native.

```js
if (typeof process.env.NODE_PG_FORCE_NATIVE !== 'undefined') {
```

```js
  // lazy require native module...the native module may not have installed
  module.exports.__defineGetter__('native', function () {
```

If you don’t define the `NODE_PG_FORCE_NATIVE` environment variable and don’t access `pg.native`, `require("./native")` will never be called.

If you’re using some kind of bundler that looks at `require`s statically, there’s typically a way to add an exception.

**Comment by imjordanm** [comment]
Thanks for your quick response. I have tried adding and removing the env variable, and all the imports I can think of. Is there some way of not accessing pg.native? I am using create-react-app/webpack. I tried installing react-app-rewired and customize-cra to try ignore native but couldn't get it to work either.
``
new webpack.IgnorePlugin(/.\/native/)

module.exports = override(babelExclude([path.resolve("pg/lib/native")]));
``
Perhaps I am not putting the right paths?

**Comment by charmander** [comment]
https://github.com/brianc/node-postgres/issues/1187#issuecomment-303770070 suggests

```js
new webpack.IgnorePlugin(/pg-native/, /\/pg\//),
```

**Comment by imjordanm** [comment]
I greatly appreciate your help, it made me go back and have a better look at my webpack configuration. I managed to solve it and will leave what I did here incase someone gets stuck in the same place. This is for people using netlify-lambda alongside node-postgres:

Netlify-lambda has its own [webpack config](https://github.com/netlify/netlify-lambda#webpack-configuration) and so the webpack config to exclude the native module needs to be here instead.
```
//webpack-functions.js
const webpack = require("webpack")

module.exports = {
    plugins: [new webpack.IgnorePlugin(/pg-native/, /\/pg\//)]
  };
```
```
//package.json
"build:server": "netlify-lambda build src/functions --config webpack-functions.js"
```

**Comment by gabegorelick** [comment]
Making `native` non-enumerable is potentially a better solution than `NODE_PG_NO_LOAD_NATIVE`, but it's potentially a breaking change.

**Comment by papb** [comment]
Hello, I am very happy to see this going forward, we in Sequelize [have a lot of users complaining about `Cannot find module 'pg-native'`](https://github.com/sequelize/sequelize/issues/3781).

However, my opinion about this (from an outsider perspective, who doesn't really know the internals of what's going on though), is that the existence of this getter itself is a bit strange, no?

Why is this seemingly magical getter necessary? Couldn't it be simply a `.getNative()` instead?

**Comment by papb** [comment]
Hello, I am very happy to see this going forward, we in Sequelize [have a lot of users complaining about `Cannot find module 'pg-native'`](https://github.com/sequelize/sequelize/issues/3781).

However, my opinion about this (from an outsider perspective, who doesn't really know the internals of what's going on though), is that the existence of this getter itself is a bit strange, no?

Why is this seemingly magical getter necessary? Couldn't it be simply a `.getNative()` instead?

**Comment by gabegorelick** [comment]
> Why is this seemingly magical getter necessary? Couldn't it be simply a .getNative() instead?

That would be a much bigger breaking change. I think simply making `native` non-enumerable, as proposed in #1992, solves all of the issues that I am aware of without breaking all but the most contrived usages.

**Comment by papb** [comment]
Hmm, ok, makes sense :)

**Comment by charmander** [comment]
As of pg 8.0, `native` isn’t enumerable. (Cloning modules still sounds like a bug in sequelize or in the use of sequelize, though.)

**Comment by AWare** [comment]
This seems to really break badly with parcel as a bundler.
