### ISSUE TITLE
Replace semver?

### ISSUE THREAD

**Issue by lukeed** [brianc/node-postgres#1898]
Hey there,

Are you willing to swap out the `semver` dependency for something much, _much_ smaller? 

Your [usage is very basic & minimal](https://github.com/brianc/node-postgres/blob/8ba1d2c5728bf41c663f05063e7b2cfc05421925/lib/native/client.js#L13), so it's a little bit of a pity that 17% of `pg`'s size is going towards `semver` for a simple check.

<img width="1275" alt="Screen Shot 2019-05-22 at 2 29 18 PM" src="https://user-images.githubusercontent.com/5855893/58210411-2ccfbe80-7c9e-11e9-90f1-fc6ac66b9079.png">

> Source: https://bundlephobia.com/result?p=pg@7.11.0

Albeit biased, I would suggest [`semiver`](https://github.com/lukeed/semiver) to do what you need – it's only 180B. I just released it, but historically I've used it to do the same `process.version` check that `pg` is doing. I've verified that the underlying `Intl.Collator` class is available in Node 4.x.

If desired, I'd be happy to PR the change.
If not, sorry for the noise :) Just trying to help out.

**Comment by charmander** [comment]
Note: it’s 12 KB, and it isn’t loaded if you don’t use `pg.native`. I don’t think it’s worth changing.

**Comment by brianc** [comment]
The thing I like about the actual semver package is its controlled by the `npm` github account and is very unlikely to be turned over to some rando maintainer who'll sneak in malicious code.  Since pg is never installed into the browser I'm not super concerned w/ it's size...particularly 12KB.

**Comment by lukeed** [comment]
Okay 👍 But bloatware is still bloatware, regardless of where it's run. Code size and efficiency is still important in Node.js environments, especially since, as an ecosystem, we still don't compile server code w/ tree-shaking and dead-code elimination on by default. This results in actual $ costs – the practice/attitude, not this individual dependency of course.

It's not about the "swap" package here. Happy to follow-up with a change for inlining the 3-4 lines of code you actually need.
