### ISSUE TITLE
Are Simultaneously Active Pool Connections Limited by UV_THREADPOOL_SIZE?

### ISSUE THREAD

**Issue by Gi60s** [brianc/node-postgres#1901]
I've recently learned that the [OracleDB package for node uses the libuv library](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-123-connections-and-number-of-threads) to attach pooled connections to threads running on the Node process. This effectively limits the number of connections that can communicate with the database at one time to 4 connections. I might have 100 connections to the database, but only 4 can actually work with the database at the same time. The limit of 4 can be adjusted up to 128 if you set the environment variable `UV_THREADPOOL_SIZE`.

Does this package run into that same limitation that the OracleDB package hits?

**Comment by charmander** [comment]
The pure JavaScript driver doesn’t. I don’t *think* pg-native does either, because it waits for a readable event before calling `PQgetResult`, but I could be wrong and haven’t tried it to make sure.

**Comment by Gi60s** [comment]
I ran a load test to see what the behavior would be and wanted to share my results.

I used [Artillery](https://artillery.io) to load test a server that I created. The server made a simple request to the Postgres database with a query that simply slept for 2 seconds. As Artillery ramps up the requests it quickly would become a database connection nightmare if this package (pg) was limited by the default `UV_THREADPOOL_SIZE`.

For the database I used the official [Postgres Docker image](https://hub.docker.com/_/postgres).

**Code**

```js
const consola = require('consola')
const express = require('express')
const { Pool } = require('pg')

const pool = new Pool({
  user: 'postgres',
  host: 'localhost',
  database: 'postgres',
  password: 'password',
  port: 5432,
  // max: 100
})

pool.query('SELECT NOW()', async (err, res) => {
  if (err) {
    consola.fatal('Unable to connect to the database')
  } else {
    consola.success('Connected to the database')

    const app = express()

    app.get('/', async (req, res) => {
      const start = Date.now()
      try {
        const {rows} = await pool.query('SELECT pg_sleep(2)')
        const durr = String((Date.now() - start) / 1000)
        consola.info(durr)
        res.set('content-type', 'text/plain')
        res.status(200)
        res.send(durr)
      } catch (err) {
        consola.error(err)
        res.sendStatus(500)
      }
    })

    app.listen(3000, err => {
      if (err) {
        consola.fatal('Unable to start server')
        consola.error(err)
      } else {
        consola.success('Server listening on port 3000')
      }
    })

  }
})

```

**First Test**

The first test I ran used the default pool size of 10 and these were the results:

```
Summary report @ 10:40:18(-0600) 2019-05-31
  Scenarios launched:  900
  Scenarios completed: 710
  Requests completed:  710
  RPS sent: 6
  Request latency:
    min: 2006.1
    max: 118885.6
    median: 60423.4
    p95: 113834.5
    p99: 118838.1
  Scenario counts:
    0: 900 (100%)
  Codes:
    200: 710
  Errors:
    ESOCKETTIMEDOUT: 115
    ECONNRESET: 75
```

Simplified that says that the fastest response was 2 seconds (remember the 2 second sleep on the query). The median request under load took 60 seconds. The worst responses to 119 seconds.

**Test 2**

In this test I specified to the pg package that it could use 100 connections in the pool. The results were much better:

```
Summary report @ 10:54:53(-0600) 2019-05-31
  Scenarios launched:  900
  Scenarios completed: 900
  Requests completed:  900
  RPS sent: 27.74
  Request latency:
    min: 2001.4
    max: 2035.7
    median: 2003.5
    p95: 2006.1
    p99: 2006.6
  Scenario counts:
    0: 900 (100%)
  Codes:
    200: 900
```

In this case the worst performing request and best peforming request both took 2 seconds. I did not overwrite node's default `UV_THREADPOOL_SIZE`, so the conclusion is that the pg package does not run into the `UV_THREADPOOL_SIZE` limitation.

**Conclusion**

Don't worry about `UV_THREADPOOL_SIZE` with the pg package. It doesn't use threads.
