### ISSUE TITLE
Segmentation fault in query

### ISSUE THREAD

**Issue by olegario96** [brianc/node-postgres#1905]
I have the following query:

```
let text = 	`SELECT v.hash AS "_id", u.email, s.name, v.timestamp FROM `;
text += 	`"Users" AS u, "Stores" AS S, "VirtualClicks" AS v WHERE `;
text += 	`"storeId"=s.id AND "userId"=u.id ORDER BY TIMESTAMP OFFSET $1 LIMIT $2;`;
const vClicksPaginated = {
	text,
	values: [offset, LIMIT]
};
return (await this.pg.query(vClicksPaginated)).rows;
```

But when executed my terminal says:

```
Segmentation fault
```

I have no idea why this is happening. I have similar queries to this that never corrupt the memory.

**Comment by charmander** [comment]
Is this with the libpq driver (`pg.native`)? Which version of Node are you using, and on which OS?

**Comment by olegario96** [comment]
```
$ node --version
v10.16.0
$ uname -a
Linux ip-10-0-1-214 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
```

What do you mean with `Is this with libpq driver (pg.native)?`?

**Comment by charmander** [comment]
> What do you mean with “Is this with the libpq driver (`pg.native`)”??

How did you create `this.pg`?

**Comment by olegario96** [comment]
```
this.pg = new Client({ connectionString: process.env.DATABASE_URL });
```

**Comment by charmander** [comment]
What is `Client`?

**Comment by olegario96** [comment]
```
const { Client } = require('pg');

```

**Comment by brianc** [comment]
If you're not using `pg-native` this is probably an issue w/ your system/install of node.  Without using `pg-native` (and it looks like you're just using `pg`) then all we're doing is pure javascript stuff which should *never* segfault.

**Comment by brianc** [comment]
@olegario96 any update on this? If you're not using native bindings its probably something w/ your operating system or install of node.  Please feel free to re-open if you're still experiencing this!
