### ISSUE TITLE
better stacktrace or error for invalid sql

### ISSUE THREAD

**Issue by mo** [brianc/node-postgres#1910]
I'm porting a semi-large node+mysql app to node+postgres, so I have some "?" characters in my queries that needs to be replaced with "$1" etc. When I try to start the app I get the error below. It would be nice if this error was more user friendly. For example, the stacktrace doesn't contain any of my files so I cannot see where in my code the invalid query is invoked.

Is there some debugging feature I can use to get a better stacktrace or otherwise find the invalid query that I need to fix?

```
error: syntax error at end of input
    at Connection.parseE (/home/username/projectname/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/home/username/projectname/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/home/username/projectname/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by sehrope** [comment]
Not built in but you can add a helper to your code that provides this type of thing. It's also a useful place to add optional query logging or publishing of errors to a centralized reporting system. The docs site has a bit about it here: https://node-postgres.com/guides/project-structure

The idea is to have your own `query(...)` wrapper where you can do additional steps before or after any command. So something like this:

```js
// your-app/config/db.js 
const pool = new pg.Pool({ /*... */});

export function query(text, params) {
    const { stack } = new Error(); // Save the caller's stack
    return pool.query(text, params)
         .catch((err) => {
             console.error('Error executing query text=%j error=%s', text, err);
             console.error('Calling stack: %s', stack);
             throw err; // rethrow error so caller gets the rejection
         });
}
```

Then in the rest of your app you'd use that `query(...)` function so errors would automatically get logged with the caller's stack. Watch out though as there may be sensitive info in either the query text or the error message.

FYI, this is a common issue for anything that hops across async code. Do a search for "node long stack traces" for some more generalized way of addressing it.

**Comment by mo** [comment]
ah right, excellent... thank you so much for posting this @sehrope
