### ISSUE TITLE
Why don't return error stack if rollback in the commit function

### ISSUE THREAD

**Issue by JandenMa** [brianc/node-postgres#1911]
## Situation
I use the codes below to execute a transaction, and I try to get error stack in `catch` if `commit` throw error. But it doesn't work.
```javascript
/**
 * @description Commit many sqls in one transaction, and will rollback all if exist one sql execute failed.
 * @param {Object} pool postgesql pool instance
 * @param {Array<String>} sqls Any sql you want to commit. Add them in an array.
 * @param {Array<Array>} params If you use placeholder (such as $1,$2), you should pass this props to set values.And the length of this array should be eauql to the sqls array. So you push an empty array into it though you don't use placeholder.
 * @author Janden Ma
 */
const Transaction = async (pool, sqls = [], params = []) => {
  // note: we don't try/catch this because if connecting throws an exception
  // we don't need to dispose of the client (it will be undefined)
  const client = await pool.connect();
  const resArray = [];
  try {
    await client.query('BEGIN');
    console.log('TRANSACTION BEGIN');
    await sqls.map(async (sql, i) => {
      const res =
        params[i].length > 0
          ? await client.query(sql, params[i])
          : await client.query(sql);
      resArray.push(res);
    });
    const res = await client.query('COMMIT');
    /* 
      Because client.query('COMMIT') will handle the rollback in its inner function, 
      and only resolve, not reject. For this reason, we can not catch errors if anything 
      throw errors when commit. Well we use codes below to catch it.  -- by Janden Ma
    */
    if (res.command.toUpperCase() === 'ROLLBACK') {
      throw new Error('Sorry, something error causes abort');
    }
    console.log('TRANSACTION COMMIT');
    return resArray;
  } catch (e) {
    console.log('TRANSACTION ROLLBACK: ', e);
    await client.query('ROLLBACK');
    throw e;
  } finally {
    client.release();
  }
};
```

## My guess
I guess that client.query('COMMIT') will handle the error and execute rollback in its inner function, and only resolve, not reject. For this reason, we can not catch errors if anything throw errors in `commit`.  Well, the `rollback` in `catch` block is to catch errors and execute rollback when any error throw from our own codes, not for the `commit`.

## Expect
I hope we can catch error stacks from `commit`, I know we can not rollback in transaction if it has already rollback. Could you resolve it that don't execute `roolback` in the inner function if we wanna catch errors stacks and execute `rollback` by ourselves.

**Comment by sehrope** [comment]
This part is wrong: 

```js
await sqls.map(async (sql, i) => {
      const res =
        params[i].length > 0
          ? await client.query(sql, params[i])
          : await client.query(sql);
      resArray.push(res);
    });
```

Calling `.map(...)` returns an array and you need to call `Promise.all(...)` to await all of them. Otherwise if you call `await` on a non-promise it will immediately resolve to the value (i.e. the array).

Rather than use `.map(...)` you probably want to execute the commands sequentially so that they only execute after the previous commands complete:

```js
const results = [];
for(let i=0;i<sqls.length;i++) {
    const result = await client.query(sqls[i], params[i]);
    results.push(result);    
}
```

One other thing to keep in mind is handling the connection being permanently broken. Otherwise the broken connection will return to the pool to cause issues forever. The simple solution is whenever an error occurs to call `release(err)` to evict the connection. A bit more intelligent is to try to rollback and if the rollback fails, then evict the connection, otherwise release without evicting it.

So something like this:

```js
try {
    await client.query('BEGIN');
    // Do work ...
    await client.query('COMMIT');
    // Transaction succeeded so retain connection in pool
    client.release();
    // Return the work
    return results;
} catch (err) {
    try {
        await client.query('ROLLBACK');
        // Rollback succeeed so retain connection in pool
        client.release();
    } catch (rollbackErr) {
        // Rollback failed so discard connection
        client.release(rollbackErr);
    }
    // Throw the original error
    throw err;
}
```

**Comment by JandenMa** [comment]
@sehrope Thanks for your answers first.
First of all, actually I used `array.forEach` instead of `array.map` in my project. Well, is there any difference between `array.forEach` and `for loop` for this situation?
For the `try..catch..`, I guess you mean that place the `rollback` in `try..catch..` block, if throw error when rollback, evict the connection. Exactly?

**Comment by sehrope** [comment]
> First of all, actually I used array.forEach instead of array.map in my project. Well, is there any difference between array.forEach and for loop for this situation?

No you can't use `.forEach(...)` either as, similar to `.map`, it does not wait for the completion of the previous iteration before proceeding to the next one. An await within the inside of a `for( ... ) { ... }` loop does wait for completion prior to proceeding.

> For the try..catch.., I guess you mean that place the rollback in try..catch.. block, if throw error when rollback, evict the connection. Exactly?

Yes.

**Comment by JandenMa** [comment]
@sehrope  OK, good to know. I really appreciate it. 🥇

**Comment by JandenMa** [comment]
## Final Solution
```javascript
const Transaction = async (pool, sqls = [], params = []) => {
  // note: we don't try/catch this because if connecting throws an exception
  // we don't need to dispose of the client (it will be undefined)
  const client = await pool.connect();
  const resArray = [];
  try {
    await client.query('BEGIN');
    console.log('TRANSACTION BEGIN');
    await Promise.all(
      sqls.map(async (sql, i) => {
        const res =
          params[i].length > 0
            ? await client.query(sql, params[i])
            : await client.query(sql);
        resArray.push(res);
      })
    );
    await client.query('COMMIT');
    console.log('TRANSACTION COMMIT');
    // Transaction succeeded so retain connection in pool
    client.release();
    console.log('TRANSACTION RELEASE');
    // Return the work
    return resArray;
  } catch (err) {
    try {
      console.log('TRANSACTION ROLLBACK: ', err);
      await client.query('ROLLBACK');
      client.release();
      console.log('TRANSACTION RELEASE');
    } catch (e) {
      console.log('ROLLBACK ERROR: ', e);
      // Rollback failed so discard connection
      client.release(e);
    }
    throw err;
  }
};
```
