### ISSUE TITLE
TypeError: net.Socket is not a constructor

### ISSUE THREAD

**Issue by consystoc** [brianc/node-postgres#1916]
The task: 
Connect the Postgresql 11 database to the project on React to get data from there.

What I did to connect to the database:
Created a new React project:
```cmd
create-react-app PGTestProject
```
Then I tried to connect to the database. The actions listed in the ["Getting started"](https://node-postgres.com/) section are not enough to get started with the package. For example, it does not indicate how to change the connection parameters to the database. Without this, it is impossible to connect to the created database.

The actions listed in the ["Connecting"](https://node-postgres.com/features/connecting)  section  are also not enough. The error "net.Socket is not a constructor"

App.js:

```javascript
import React from 'react';

import logo from './logo.svg';
import './App.css';

async function getDatafromDB(){
    const { Pool, Client } = require('pg')

       const pool = new Pool({
        user: 'postgres',
        host: 'server_ip',
        database: 'mydb',
        password: 'password',
        port: 5432,
    })

    pool.query('SELECT NOW()', (err, res) => {
        console.log(err, res)
        pool.end()
    })

    const pool = new Pool({
        user: 'postgres',
        host: 'server_ip',
        database: 'mydb',
        password: 'password',
        port: 5432,
    })
    client.connect()

    client.query('SELECT NOW()', (err, res) => {
        console.log(err, res)
        client.end()
    })
}

function App() {
    getDatafromDB();
    return (
        <div className="App">
            <header className="App-header">
                <img src={logo} className="App-logo" alt="logo"/>
                <p>
                    Edit <code>src/App.js</code> and save to reload.
                </p>
                <a
                    className="App-link"
                    href="https://reactjs.org"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Learn React
                </a>
            </header>
        </div>
    );
}

export default App;

```
An error occurs in the browser console:
TypeError: net.Socket is not a constructor

**Comment by charmander** [comment]
You can’t run pg in the browser. It runs in Node.

**Comment by dflynn20** [comment]
Why can't it be run in the browser? There must be a way to connect a website table to Postgres SQL databases.

**Comment by ngervasi** [comment]
And send credentials over the wire?
If you really want to skip the backend have a look at AWS Amplify and GraphQL.

**Comment by charmander** [comment]
@dflynn20 I can think of three categories of in-browser pg:

1. really terrible and insecure ideas
2. cases where it’s easy to proxy queries through a Node backend
3. niche uses that are not worth inserting abstractions over Node net interfaces into pg to cater to (unless you want to sponsor brianc for their implementation)

If you have an exception, please share the details that would justify support.

Remember that browsers don’t support plain sockets anyway.

**Comment by micimize** [comment]
@charmander what about deploying to [cloudflare workers](https://workers.cloudflare.com/)?

**Comment by micimize** [comment]
The real answer to this is that it is not technically possible, as [there is no TCP support in browsers](https://stackoverflow.com/a/17337074/2234013), and no plan for it

**Comment by charmander** [comment]
@micimize Cloudflare workers don’t run in the browser, as far as I know.

**Comment by aleksasdev** [comment]
Jesus JS, I just want to make a freakin' TCP socket, I don't need your node hand holding, I know how to establish a secure connection with RSA and AES, and I just want to connect to my python server and handle backend that way. Really pisses me off how I spent 3 hours and still can't set up a simple TCP connection to my python server because of this silliness...
