### ISSUE TITLE
How to enable "reWriteBatchedInserts" through node driver?

### ISSUE THREAD

**Issue by pushpa446** [brianc/node-postgres#1919]
We are referencing jdbc psql driver https://jdbc.postgresql.org/documentation/head/connect.html
In jdbc driver there is a connection parameter called `reWriteBatchedInserts` which helps improving performance.
We are trying find this parameter in node psql driver here https://github.com/brianc/node-postgres/blob/master/lib/connection-parameters.js but could not find it.
Ex: Found below connection parameters for a pg connection

``ConnectionParameters {
  user: 'postgres',
  database: 'mydb',
  port: 5432,
  host: 'localhost',
  password: '*******',
  binary: false,
  ssl: false,
  client_encoding: '',
  replication: undefined,
  isDomainSocket: false,
  application_name: undefined,
  fallback_application_name: undefined,
  statement_timeout: false,
  query_timeout: false }``

Is there a way we can do `reWriteBatchedInserts` with node driver?

**Comment by sehrope** [comment]
There's no such property for this node driver. That property is a client side optimization specific to the Java JDBC driver. It's meant to work within the limitations of the JDBC API when the user does not have full control of the SQL being executed to change it to something specific to Postgres.

The node-postgres driver is specific to Postgres (as opposed to the JDBC which is a generic interface) so presumably you have some flexability on what you're executing. For maximixing performance check out using either the COPY command (usually the fastest) or using arrays to pass many parameters at once. Both are supported by the node-postgres driver and are significantly faster than using individual INSERT commands.
