### ISSUE TITLE
Empty JSON arrays in SELECT with COALESCE are returned as '[]' string

### ISSUE THREAD

**Issue by AxelTerizaki** [brianc/node-postgres#1920]
Hello.

My question might be postgreSQL related more than node-pg related, but I'm drawing a blank as to what could cause this issue.

I'm doing selects on a few columns which are all JSONB in postgres. Some of them can be `null` however, and in this case, node-pg returns them as `null` correctly, but I would have liked to return an empty JSON array instead, so I did this :

`SELECT COALESCE(ak.singers, to_jsonb('[]'::text)) AS singers ... `

PostgreSQL returns no particular error, and in pgadmin I'm getting `[]` in a JSONB type column.

However, once I'm getting this with node-pg, I get a string `[]` instead of a JSON empty array. 

Example in my database with two different fields. One is non-empty, the other is. I've put a console log of the `rows` object in node-pg's response : 

```
 origins:
   [ { tid: '938de218-5343-4865-94d3-fb33f2eaa152',
       i18n: [Object],
       name: 'TV Show',
       short: 'TV',
       types: [Array],
       aliases: [] } ],
  platforms: '[]',
```

Platforms is returned as a string even though in pgadmin the column is definitely JSONB and there's only `[]` inside (empty array)

So is there something I'm doing wrong or is it a bug on node-pg's side ? Or is it intended behavior ? Should I parse the returned rows and change `[]` to empty arrays ?

Thanks in advance

**Comment by charmander** [comment]
> `to_jsonb('[]'::text)`

That’s `'"[]"'::jsonb`. You’re looking for `'[]'::jsonb`.

**Comment by AxelTerizaki** [comment]
I confirm it works, thanks for helping me out @charmander !
