### ISSUE TITLE
Provide function to use different password for each connect (AWS RDS using IAM Credentials)

### ISSUE THREAD

**Issue by kellertobias** [brianc/node-postgres#1924]
We just moved from a self hosted postgres to AWS RDS.
One huge benefit is, that using RDS, we don't need to manage crendentials anymore but can rely on the AWS IAM Credentials for RDS.

However, these passwords are obtained using an API and are only valid for 15 Minutes. So if we use a connection pool, and allow these connections to close and reopen, the password will not be valid anymore after 15 minutes.

Is there a way to use the conection pool and providing them a function with which they can obtain a new password?

**Comment by sehrope** [comment]
Duplicate of https://github.com/brianc/node-postgres/issues/1873

This isn't currently possible with the built-in pool but has been requested before. AFAIK, there's no objection to the feature, it's just that nobody has implemented it yet.

**Comment by kellertobias** [comment]
Jep, this is a dupe. Thanks.

/close
