### ISSUE TITLE
Connection flag to disable prepared statements

### ISSUE THREAD

**Issue by cagdastulek** [brianc/node-postgres#1933]
As far as I see in the source code, it is not possible to pass a flag like `prepared_statements: false` to pg client config. Is it possible to add this feature?

Thank you.

**Comment by charmander** [comment]
When would a feature like that be useful?

**Comment by cagdastulek** [comment]
Our database suffers memory issues and one suggestion was to disable prepared statements.

**Comment by charmander** [comment]
You would have to rewrite everything to [format values into the query first][pg-format] to avoid parameters. Also, prepared statements without names aren’t cached anywhere, so that advice probably doesn’t apply to node-postgres.

[pg-format]: https://github.com/datalanche/node-pg-format

**Comment by cagdastulek** [comment]
According to the following part of the Postgresql document, each prepared statement is cached as an unnamed prepared statement and then dropped in next unnamed prepared statement request. I wonder if this causes memory pressure on Postgresql.
https://www.postgresql.org/docs/10/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

Your advise is one option but otherwise it does not look hard to modify `requiresPreparation` in `/lib/query.js` to check for a parameter to enable/disable prepared statements.

**Comment by charmander** [comment]
> Your advise is one option but otherwise it does not look hard to modify `requiresPreparation` in `/lib/query.js` to check for a parameter to enable/disable prepared statements.

And throw an error if it does? That’s extremely niche. You can accomplish this by monkeypatching/via a wrapper if it helps you refactor for testing.

**Comment by lastmjs** [comment]
> You can accomplish this by monkeypatching/via a wrapper if it helps you refactor for testing.

@charmander Can you give me some detail on how I would accomplish this kind of monkeypatching? I'm trying to get node-postgres prepared statements to work with transaction pooling on RDS, and it's proving extremely difficult (all prepared statements are session pinned). Getting rid of prepared statements would be a solution to this, but I'm not sure how to go about it. I am using Knex as well as node-postgres directly, so somehow being able to intercept very query to apply this would be nice.
