### ISSUE TITLE
Query object is never returned anymore.

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#1944]
In earlier versions of the library, when we used method `query` with the callback function, the method itself would return the [Query] object.

But now, if we pass in the callback, method `query` returns `undefined`.

Is this by design, or is it a bug? Any documentation reference?

[Query]:https://github.com/brianc/node-postgres/blob/master/lib/query.js#L16

**Comment by charmander** [comment]
It’s by design. (It also returned a promise in pg 6, IIRC.) I can’t reference a changelog entry because there isn’t a changelog, but the possible return types by signature [are documented](https://node-postgres.com/api/client/#client.query).

**Comment by vitaly-t** [comment]
Documentation only mentions return of Promise when there is no callback passed in. But when we do pass a callback in, it doesn't mention what is supposed to be returned in that case.

**Comment by vitaly-t** [comment]
By the way, even the latest version of TypeScript for the library still says that `Query` is returned.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/42490ec316d5ef5220eeeed4366d668b1ccb0332/types/pg/index.d.ts#L160

**Comment by charmander** [comment]
> Documentation only mentions return of Promise when there is no callback passed in. But when we do pass a callback in, it doesn't mention what is supposed to be returned in that case.

It shows it in the signatures – `=> void`.

> It used to be `Query`, but now `undefined`, I wonder why that happened.

Because it switched to `Promise` when promises were first introduced, which became an especially noticeable problem when Node added unhandled rejection warnings, and there wasn’t much reason to start returning `Query` again after that. The `Submittable` API is already pretty niche; I’m not sure when you’d use it together with a callback, but it’s not worth the API complexity.

**Comment by vitaly-t** [comment]
So the official signature is now incorrect then....

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/42490ec316d5ef5220eeeed4366d668b1ccb0332/types/pg/index.d.ts#L174

**Comment by charmander** [comment]
> So the official signature for the method is now incorrect then....

Right.

**Comment by vitaly-t** [comment]
Maybe then this issue should be open? - 

* To get the TypeScripts updated
* To update documentation to say that nothing is returned when the callback is passed in
