### ISSUE TITLE
[documentation] Example is not working

### ISSUE THREAD

**Issue by makarov-roman** [brianc/node-postgres#1945]
Hi, when I trying to run example from date / timestamp / timestamptz I always getting error:
```error: syntax error at end of input```
Most likely this syntax is not supported:
``` const insertText = 'INSERT INTO dates(date_col, timestamp_col, timestamtz_col'```

pageURL: https://node-postgres.com/features/typesq

Thanks

**Comment by sehrope** [comment]
Yes it looks like that example got truncated. It's missing the ` VALUES ( ...)` The one at the top is incorrect too as `::string` should be `::text`.

The docs are now in their own repo so you can open an issue or submit a PR to fix it there: https://github.com/brianc/node-postgres-docs

**Comment by makarov-roman** [comment]
Thanks, will do.
