### ISSUE TITLE
Postgres `sslmode` parameter support

### ISSUE THREAD

**Issue by charlie-wasp** [brianc/node-postgres#1949]
I can't figure out clearly, is `sslmode` parameter supported for connection strings? As I can see in [pg-connection-string](https://github.com/iceddev/pg-connection-string), `sslmode` isn't parsed, but I can see its [mention](https://github.com/brianc/node-postgres/blob/master/lib/connection-parameters.js#L109) in the codebase.

I use `pg-promise` in my project, and I have `sslmode` parameter in the Postgres connection string from Google Cloud. So I can't connect due to the `database "dbname?sslmode=disable" does not exist`, that's why I'm asking :)

**Comment by vitaly-t** [comment]
You can, for the time being use generic [connection-string](https://github.com/vitaly-t/connection-string) to parse it, and use the connection object with any parameters that you want.

Other than that, I submitted a [PR there](https://github.com/iceddev/pg-connection-string/pull/32) sometime ago, but it's still just hanging there.

**Comment by charlie-wasp** [comment]
Thank you, I already found out that problem lies on fact in `typeorm`, not `pg-promise`

But I still wonder, what are reasons behind current state of affairs? Why I have to parse connection string myself beforehand?

**Comment by vitaly-t** [comment]
There's some discrepancy between this driver and what that old parser can do. It was somewhat updated lately, but the old version is still referenced here, hence the mess. At least if you parse it yourself, you can be certain at how it works :)

**Comment by charmander** [comment]
The option is called `ssl`, so if you want it to come from pg-connection-string, it looks like it’s `?ssl=…`. (I don’t think using a different connection string parser will change that.) See the line above with `{ sslmode: this.ssl }` when the `ssl` option isn’t an object.

**Comment by charmander** [comment]
This is probably an oversight in implementing PostgreSQL-connection-URI-compatible options, though, maybe related to [`ssl=true` also existing][1]:

> For improved compatibility with JDBC connection URIs, instances of parameter `ssl=true` are translated into `sslmode=require`.


[1]: https://www.postgresql.org/docs/11/libpq-connect.html#id-1.7.3.8.3.6

**Comment by ikokostya** [comment]
I think documentation should be improved in this place. There are valid constructor calls:

```ts
new Client({ ssl: false });
new Client({ ssl: 'verify-full' });
new Client({
    ssl: {
        sslmode: 'verify-ca'
    }
});
```

**Comment by vitaly-t** [comment]
> I don’t think using a different connection string parser will change that.

What is different - this driver continues to use an ancient version of [pg-connection-string](https://github.com/iceddev/pg-connection-string), and for no good reason.

**Comment by charmander** [comment]
@vitaly-t I’m not sure what “What makes a difference” means. Anyway, mixing pg options and libpq options into the same connection URI syntax is a mistake, in my opinion. Switching to “generic connection-string”, which uses (now, an unspecified superset of) the MongoDB connection string spec instead of the libpq implementation would also be a mistake.

**Comment by MilamBardo** [comment]
I have sslmode parameter in the Postgres connection string from Digital Ocean.  

I'm trying to use generic connection-string to set the ca certificate (in a similar way to https://github.com/nextauthjs/next-auth/issues/396), but I am failing. 

Is it possible to set ssl?  I'm trying to use setDefaults, but nothing is getting picked up when I print the connection string.  Gracious apologies if I am doing something incorrect.

const a = new ConnectionString('postgresql://@myserver:myport/mydb?sslmode=require');

a.setDefaults({ssl: {
    cert: fs.readFileSync('./certs/ca-certificate.crt').toString()
},
sslrootcert:  fs.readFileSync('./certs/ca-certificate.crt').toString(),
user: 'guest', 
password: 'pass123'
});

User and password get picked up, but neither ssl nor sslrootcert appear.  I know I am doing something wrong, but not sure what.
