### ISSUE TITLE
More - rowMode: 'values', ...etc

### ISSUE THREAD

**Issue by uasan** [brianc/node-postgres#1955]
Hi.

In others languages (PHP, Python, ...etc) wrappers for `libpq` implemented more modes result query.

`rowMode: 'one'` - return rows[0]
`rowMode: 'values'` - return rows.map( row => row[0] )
`rowMode: 'value'` - return rows[0][0]

Examples use cases:
```JS
// fetch one row
client.query(
  'SELECT * FROM table WHERE id=$1',
  rowMode: 'one'
);
// fetch flat array values
client.query(
  'SELECT id FROM table',
  rowMode: 'values'
);
// fetch one value
client.query(
  'SELECT count(*) FROM table',
  rowMode: 'value'
);
```
Now needed custom helper functions that in a loop transform the format of the result.
But this is a double job, because the result formation loop was also carried out inside the `result.js`.

I can create a PR to update the`result.js`

Ok?

**Comment by gajus** [comment]
Slonik implements `any`, `anyFirst`, `many`, `manyFirst`, `maybeOne`, etc. It is built on top of node-postgres.

https://github.com/gajus/slonik#slonik-query-methods

**Comment by charmander** [comment]
`rowMode` normally affects the type of the `rows` property on a result object. Affecting it in stranger ways (is the entire result object replaced? does `rows` become a single object? does the property get renamed to `row`/`value`/`column`?) is too much API complexity for something that can be put on top so easily, IMO.

**Comment by brianc** [comment]
yeah I think most of this should be served by something else, like slonik, pg-promise, orms, etc.  Want to keep this library doing its best to expose & represent the full postgres protocol in an easy to use, performant way.  Convenience utilities are best to be layered on top via composability of npm packages or in your own application code.
