### ISSUE TITLE
Is there a difference between passing hex or buffer when writing bytea?

### ISSUE THREAD

**Issue by gajus** [brianc/node-postgres#1958]

**Comment by charmander** [comment]
Hex is much, much less efficient (twice as many bytes, decoding overhead).

**Comment by gajus** [comment]
> Hex is much, much less efficient (twice as many bytes, decoding overhead).

Compared to? Is node-postgres using binary protocol to transfer buffers?

**Comment by charmander** [comment]
> Compared to? Is node-postgres using binary protocol to transfer buffers?

Compared to a buffer. Yes, it is.
