### ISSUE TITLE
How to parallelize query execution?

### ISSUE THREAD

**Issue by cmmash** [brianc/node-postgres#1959]
Hi! First of all, awesome work with the lib!

Onto my problem: I've got a report dashboard which uses many functions like this one per API request:

```
getTaskCounts: async function() {
  const all = await this._getTaskCountStats({})
  const declined = await this._getTaskCountStats({status: 'declined'})
  const approved = await this._getTaskCountStats({status: 'approved'})
  const pending = all - (+declined + +approved);
  const internal = await this._getTaskCountStats({source: 'internal'})
  const external = await this._getTaskCountStats({source: 'external'})
  const declinedTotalTime = await this._getTaskTimeToAction({status: 'declined'});
  const approvedTotalTime = await this._getTaskTimeToAction({status: 'approved'});
  const avgResponseTime = +parseFloat((+declinedTotalTime + +approvedTotalTime)/all).toFixed(2);
}
```

Now each of the inner function calls with a preceding `await` makes a `pool.query` call to postgres. But I'd like to execute all of these in parallel. Any way to do that? Searched the docs and google with a few keywords for my problem but nothing examplifying came up. So is this possible ? Like do something like this:

```
queries.push(innerFunc1());
...
queries.push(innerFuncN());
Promise.all(queries).then(allQueriesData => {
...
});
```

Thanks!

**Comment by sehrope** [comment]
Use a `Promise.all(...)` on your service functions. Under the covers if they're using a pool to connect to the database then it will run in parallel up to the concurrency level of the pool (max connections).

So something like:

```js
async function getFoo() {
    // Use a pooled client
    const result = await pool.query('SELECT ...');
    const row = resul.rows[0];
    if (!row) return null;
    return row.foo;
}

async function getTaskCounts() {
    const [foo, bar, baz] = await Promise.all([
        getFoo(),
        getBar(123),
        getBaz('abcd'),
    ]);
    // Do stuff with foo, bar, and baz
}
```

If you intend for all of the commands to use the same connection, say because they're transactionally related, then you should await each one at a time.

**Comment by vitaly-t** [comment]
> If you intend for all of the commands to use the same connection, say because they're transactionally related, then you should await each one at a time.

One typically wants to release the connection at the end of it, which makes `Promise.all` unusable, i.e. one needs to settle the list of promises, or else you will end up trying to execute them against a released connection.

**Comment by cmmash** [comment]
Thanks guys, this really helped me a lot in cutting total API call times by 40-60%.
