### ISSUE TITLE
Syntax error on ADD CONSTRAINT

### ISSUE THREAD

**Issue by byrnem** [brianc/node-postgres#1960]
Trying to execute the following command gives me a syntax error.  When I run the same command in Postico it has no problem. Are you not able to add a constraint with pg.query? It lets me DROP the constraint without issue.
**Postgres version:** 10.6
**node-postgres version:** tried both 7.7.1 and 7.12.1

```javascript
let sql = 'ALTER TABLE t1 ADD CONSTRAINT t1_fk FOREIGN KEY (t2_id) REFERENCES t2 (id)';
client = await poolTarget.connect();
await client.query(sql);
```

This gives `error: syntax error at or near "ADD CONSTRAINT"`
```javascript
{
  name: 'error',
  length: 104,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '16',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1128',
  routine: 'scanner_yyerror'
}
```

I've spent a day searching the internet/source and trying to figure out this issue but getting nowhere. I have to sync some data from another database, so I TRUNCATE my target table then insert the data from the other database. The problem is that there are other tables that have a foreign key referencing this data, so it won't let me delete the data. Because our constraint is Not Deferrable, I was going to drop the constraints on the other tables and then add them back again after the data is loaded. I can't do cascading deletes because we are not updating all of the tables.

I've tried it with/without: quotes, "public", NOT DEFERRABLE, etc.

This line works fine:
`await client.query('ALTER TABLE t1 DROP CONSTRAINT t1_fk')`

So why does the ADD CONSTRAINT fail?!?  Is this not possible with node-postgres or am I missing something?

**Comment by vitaly-t** [comment]
This is 100% a server-side error, which means you will get the same from running the SQL command elsewhere (pgAdmin or psql), so it is not a valid issue to open here.

**Comment by charmander** [comment]
I can’t reproduce a syntax error using that code. Try checking for invisible characters that didn’t make it into the text of the GitHub issue.
