### ISSUE TITLE
How do you parameterize UUID

### ISSUE THREAD

**Issue by jsphkm** [brianc/node-postgres#1969]
When making a query with UUID, how do you parameterize the UUID value?

This doesn't seem to work:
```
const text = 'SELECT * FROM users WHERE id::text IN ($1)';
const values = [ uuid ];

pool.query(text, values, (err, res) => { ...
```

**Comment by tycrek** [comment]
How did you solve this?

**Comment by d-jiang** [comment]
@tycrek https://github.com/brianc/node-postgres/issues/1642#issuecomment-387851345

change `IN (...)` to `= ANY(...)`
