### ISSUE TITLE
Pool error

### ISSUE THREAD

**Issue by jsphkm** [brianc/node-postgres#1970]
Can I get a more in depth explanation about pool on error?
```js
pool.on('error', (err, client) => {
  console.error('Unexpected error on idle client', err)
  process.exit(-1);
});
```

I got this error message and I would like to know when and how the error event was called
```
NodeError: Cannot call write after a stream was destroyed
````

**Comment by yesIamFaded** [comment]
Waiting over 18 days for a response lmao. :x:

**Comment by charmander** [comment]
You can look at `err.stack`.
