### ISSUE TITLE
Query on a JSONB column fails to find any record given a JSON array as a query param.

### ISSUE THREAD

**Issue by Cali93** [brianc/node-postgres#1972]
Hi everyone, I am trying to query a JSON column on my PostgreSQL DB. On the "contact" table, the column "emails" is a JSON array like so:
`[  { "email": "test@test.com", "default": false } ,  { "email": "test2@test.com", "default": true }  ]`
This is the query I'll end up executing in order to find any contacts that already has any of the provided emails:
`SELECT * FROM "contact" "contact" WHERE emails::jsonb @> ANY (ARRAY ['[{ "email": "test@test.com" }]','[{ "email": "test5@test.com" }]']::jsonb[])`
However, I'd like to pass the values inside the ARRAY [...] as a param but it doesn't work. As a work around I have to do something like this( I might be vulnerable to an SQL Injection ):
```javascript
    const formattedEmails = emails.map(({ email }) => `'[{ "email": "${email}" }]'`);
    const potentialContactDuplicates = await getConnection()
      .createQueryBuilder()
      .select('*')
      .from(Contact, 'contact')
      .where(`emails::jsonb @> ANY (ARRAY [${formattedEmails}]::jsonb[])`)
      .getRawMany();
```
I've tried various ways, however as I am a noob with JSON in SQL so it might not be an issue.
Any ideas of how I could improve my code ? Thanks in advance.

PS: I am using TypeORM but they use the pg module under the hood so that's why I am posting this here.

**Comment by sehrope** [comment]
To have the parameter sent as an array you'll need to map the internal values to JSON yourself first:

```js
async function stuff() {
    const sql = `
        SELECT $1::jsonb[];
    `;
    const value = [
        [1, 2, 3],
        { foo: 123 },
        { bar: 456 },
        { baz: "test" },
    ];
    try {
        // Try using value directly (will fail)
        await pool.query(sql, [value]);
    } catch (err) {
        console.error('Error: %s', err.message);
    }

    // Try using explicitly serialized array (will succeed)
    const arrayOfText = value.map(item => JSON.stringify(item));
    const result = await pool.query(sql, [arrayOfText]);
    console.log('Success: %j', result.rows[0]);
}
```

Output:
```text
Error: malformed array literal: "{{"1","2","3"},"{\"foo\":123}","{\"bar\":456}","{\"baz\":\"test\"}"}"
Success: {"jsonb":[[1,2,3],{"foo":123},{"bar":456},{"baz":"test"}]}
```

Otherwise the driver will try to serialize the items in the array (which themselves are arrays) as arrays rather than JSON.

Arrays have been in Postgres long before JSON was added so they have priority as a data type for implied serialization as parameters.

**Comment by Cali93** [comment]
@sehrope Thanks for the tip, I've already tried that and `$1::jsonb[]` outputs  `query failed: SELECT * FROM "contact" "contact" WHERE emails::jsonb @> ANY (ARRAY $1::jsonb[]) -- PARAMETERS: [["[{\"email\":\"test@test.com\"}]","[{\"email\":\"test2@test.com\"}]"]]
error: { error: syntax error at or near "$1"`

However when I do this the following, it works fine considering formattedEmails' length is 2,:
`    // if its length was different, then it would crash
    const formattedEmails = emails.map(({ email }) => JSON.stringify([{ email }]));
    const sql = `SELECT * FROM "contact" "contact" WHERE emails::jsonb @> ANY (ARRAY [$1, $2]::jsonb[])`;
    const potentialContactDuplicates = await getManager().query(sql, [...formattedEmails]);
