### ISSUE TITLE
Document `escapeLiteral` and `escapeIdentifier`

### ISSUE THREAD

**Issue by jmm** [brianc/node-postgres#1978]
Hello, thanks for the work on this.

I'm new to this library and was surprised not to be finding any escaping functions. But I managed to find https://github.com/brianc/node-postgres/pull/396.

It seems these are part of the public API and just seemingly aren't documented, so if that's correct this is a request to document them.

Also, since `Pool` otherwise appears to be a superset of the `Client` API, would it make sense for them to be available there as well?

Thanks

**Comment by brianc** [comment]
The docs are open source and open to contribution, would love to help you add docs about this over there! https://github.com/brianc/node-postgres-docs

As far as adding it to pool as well? Nah, I thinking having only 1 place to access a function is probably overall easier to reason about than putting it on the pool _as well_ though I'll admit having those functions be on the client _prototype_ was a weird decision made long ago.  Probably should just be exported as top level funcs or something nowadays...but anyways it is what it is.

One thing to note about escaping parameters - you're better off using parameterized SQL.  I realize that's not _always_ an option.
