### ISSUE TITLE
pool.end resolves before pool.query

### ISSUE THREAD

**Issue by mslatt** [brianc/node-postgres#1979]
I was expecting the pool.end callback/promise to resolve after the last pool.query finishes to help with code flow control, but that doesn't happen:
```
pool.query(query).then(res => console.log('done'))
pool.query(query).then(res => console.log('done'))
pool.end().then(() => console.log('end'))
```
result:
```
done
end
done
```
Is there a reason for this, can't this be changed so pool.end resolves after pool.query?

**Comment by ngervasi** [comment]
Try:
`pool.query(query).then(res => {
   pool.query(query2).then(res2 => {
      pool.end().then(() => console.log('end'));
   })
})`

**Comment by mslatt** [comment]
@ngervasi yes that would call pool.end after the last query finished, but this issue is for the case of calling pool.end before the last pool.query finishes, seems like pool.query should resolve first, but I can code around that
