### ISSUE TITLE
Obtain nullability information of returned fields

### ISSUE THREAD

**Issue by inad9300** [brianc/node-postgres#1981]
Hi Brian!

I was wondering if there is any way to check whether a selected field is nullable or not. Not only for columns, but more generally for any selected value (for example, some native postgres functions may return null).

The field metadata currently contains `dataTypeModifier`. Could that be what I want? I did not manage to find information online about this field.

If this information is not part of the returned metadata at the moment, could it be made so? Or, is there a workaround that you can think of?

Thanks!
Daniel

**Comment by charmander** [comment]
Nullability is a constraint you can put on some things (like columns) in PostgreSQL, but it isn’t part of a type. [Looking up tables’ definitions][1] might help (`SELECT is_nullable FROM information_schema.columns WHERE …`), but there’s no way to get that information for functions or fields of returned rows in general.


[1]: https://www.postgresql.org/docs/devel/information-schema.html

**Comment by inad9300** [comment]
That sucks... 😕

But thanks for your answer!
