### ISSUE TITLE
Notices are Errors, not Messages

### ISSUE THREAD

**Issue by ab-pm** [brianc/node-postgres#1982]
(related to #1735)

I think `parseN`/`parseE` are broken https://github.com/brianc/node-postgres/blob/e4578d2c7bca60cfb02ec004daa22c8ff810140e/lib/connection.js#L635-L640 https://github.com/brianc/node-postgres/blob/e4578d2c7bca60cfb02ec004daa22c8ff810140e/lib/connection.js#L592-L604

It looks like the one should create a `Message` and the other should create an `Error`, depending on the `.name`. However, `parseE` does always construct the `input` message with `.name === 'error'`, so the `else` path is never hit.

**Comment by charmander** [comment]
Rediscovered this for #2020. I don’t think the change was intentional, but it’s existed since 2.4.0 so it’ll have to stay that way in 7.x at least. It doesn’t really make sense to expose `Message`-compatible objects either – `length` is meaningless to library users, and `name` almost so.

**Comment by charmander** [comment]
Interested in changing this as part of 8.0, @brianc?

**Comment by brianc** [comment]
Good idea!
