### ISSUE TITLE
React Native App won't start anymore.

### ISSUE THREAD

**Issue by yesIamFaded** [brianc/node-postgres#1983]
Hi Guys for some reason my app that was working normal yesterday doesnt start up today :/

React Native version: 0.59.8 //// But also tried with 0.59.5 and 0.59.9

Steps To Reproduce
1 .Just start up the App.
2. It was working normally yesterday and today its bugged

Describe what you expected to happen:

So I have a RN app which I have for a few months now and i started to continue with it yesterday.
Everything was working fine yesterday but for some reason it is not working today.

No matter if I start it up with:

npm start
npm run android ( react-native run-android )
npm start -- --reset-cache + npm run android
it always crashes with some different code.

I tried many fixes but none of them work for me.

I tried to link gesture-handler again and reinstalling it.
tried using jetifier
deleted node-modules and reinstalled it
and some other fixes like updating packages...
=> for some reason I always get an error even though it was working yesterday

ty for your help Faded.

package.json file :
![Unbenannt](https://user-images.githubusercontent.com/48751859/65749030-9278ff00-e105-11e9-9bcc-9a50201dab0a.PNG)

Snack, code example, screenshot, or link to a repository:

case npm start:
Metro Bundler starts up fine if I refresh the app i get:

![npm start](https://user-images.githubusercontent.com/48751859/65749037-99a00d00-e105-11e9-8b62-6944944cde14.PNG)

case npm run android (react-native run-android) :

![npmRunandroid](https://user-images.githubusercontent.com/48751859/65749048-9e64c100-e105-11e9-9779-dd17577edfeb.PNG)

case npm start -- --reset-cache and npm run android:
Metro bundler starts normally but then when runing npm run android =>
![npmreset](https://user-images.githubusercontent.com/48751859/65749054-a45aa200-e105-11e9-89f6-5f8d63aacc01.PNG)

any ideas where the probleme may be ?

**Comment by charmander** [comment]
`util` is a built-in Node module. The issue is with your react-native setup. Unrelated to pg.

**Comment by yesIamFaded** [comment]
I opened this issue on React Natives github but I got send here because they said it is related to pg module. If I dont use pg it actually works so I think you are wrong.

**Comment by boromisp** [comment]
Since pg is a node js library, it doesn't declare its dependency on node's built-in modules. To use it under react native you might have to install additional dependencies, for example `util`, as discussed here: https://github.com/facebook/react-native/issues/526.
