### ISSUE TITLE
Receving a lot of "timeout" issues. Will adding :keepAlive" and "idleTimeoutMillis" help solve this ?

### ISSUE THREAD

**Issue by SaugataDutta** [brianc/node-postgres#1984]
We are seeing this issue recently, where PostgreSQL has not been under much load but all DB statements are getting connection time-outs. We have set a DB_CONNECTTION_TIMEOUT set at 10 secs.
```
host: DB_HOST,
    port: DB_PORT,
    database: DB_NAME,
    user: DB_USER,
    password: DB_PASSWORD,
    pg: pg,
    max: 15,
    connectionTimeoutMillis: 10000,
    statementTimeout: 10000
```
> err: {
  message: "timeout exceeded when trying to connect"
  stack: "Error: timeout exceeded when trying to connect
   at Timeout.setTimeout [as _onTimeout] (/app/node_modules/pg-pool/index.js:199:27)
   at ontimeout (timers.js:436:11)
   at tryOnTimeout (timers.js:300:5)
   at listOnTimeout (timers.js:263:5)
   at Timer.processTimers (timers.js:223:10)"
  type: "Error"
}

>

**Comment by brianc** [comment]
Probably? It sounds like an issue w/ your database server & not pg directly.  Please feel free to reopen this if you can reproduce it in a self-contained gist or script...then I can take a look at it and fix anything on pg's side.
