### ISSUE TITLE
Any way to turn off autocommit?

### ISSUE THREAD

**Issue by mithildeeva** [brianc/node-postgres#1986]
I need to execute a query (which writes data to a cursor) and then have to `FETCH FROM <cursor>`. Issue is that once the query is run, because of autocommit the cursor ceases to exist when I next run `FETCH FROM <cursor>`. So how do I turn off autocommit.

Also, I don't want to write `BEGIN;`, `COMMIT;` on application side as that'll complicate things

**Comment by boromisp** [comment]
To turn off "autocommit" you have to explicitly begin and end the transaction.
You could do this by following the documentation here: https://node-postgres.com/features/transactions.
Alternatively, you could switch to a higher level library, like [pg-promise](https://github.com/vitaly-t/pg-promise#transactions), that will do it for you.
