### ISSUE TITLE
Adding to the query limit 50 offset 0 produces error

### ISSUE THREAD

**Issue by rukonmin** [brianc/node-postgres#1989]
In psql (11.5 (Ubuntu 11.5-1.pgdg18.04 + 1)), both queries do not produce errors below, but if you call them in pg, you get two different results: one without an error and the other with an error ..

It does not throw an error if you run the query below, pool.query (query, []), where query:
```
select 
           tbl.*
from ( 
        select u.* from users u
        ) as tbl
```
If you add **limit 50 offset 0** to the queries.
Throws an error if you run the query below, pool.query (query, []), where query:
```
select 
           tbl.*
from ( 
        select u.* from users u
        ) as tbl
limit 50 offset 0
```
error: subquery in FROM must have an alias
    at Connection.parseE (F:\@rao\rrs\node_modules\pg\lib\connection.js:604:11)
    at Connection.parseMessage (F:\@rao\rrs\node_modules\pg\lib\connection.js:401:19)
    at Socket.<anonymous> (F:\@rao\rrs\node_modules\pg\lib\connection.js:121:22)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 186,
  severity: 'ОШИБКА',
  code: '42601',
  detail: undefined,
  hint: 'Например, FROM (SELECT ...) [AS] foo.',
  position: '41',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'gram.y',
  line: '11897',
  routine: 'base_yyparse'
}
{
  message: 'подзапрос во FROM должен иметь псевдоним',
  detail: undefined,
  code: '42601',
  severity: 'ОШИБКА'
}

**Comment by vitaly-t** [comment]
I think you got confused. This is not a Russian forum.

**Comment by vitaly-t** [comment]
I have tested it, and running this query does not throw any error with the driver:

```sql
select tbl.* from (select u.* from users u) as tbl limit 50 offset 0
```

Perhaps the query you are actually executing isn't what you think it is.

**Comment by rukonmin** [comment]
sorry, it's my fault. i had 2 queries. the second with error.
`select count(*) from ( select * from user ) `
