### ISSUE TITLE
feature request: automatic prepared query (eg:)

### ISSUE THREAD

**Issue by cekvenich** [brianc/node-postgres#1990]
name: can be just be == text: (eg: 'SELECT * FROM user WHERE id = $1' )

So I don't have to worry about duplicate strings or edits

**Comment by charmander** [comment]
Isn’t there a length limit of 63 or 64 characters? I suppose you could hash it.

**Comment by vitaly-t** [comment]
@charmander According to this library - yes:

https://github.com/brianc/node-postgres/blob/e4578d2c7bca60cfb02ec004daa22c8ff810140e/lib/connection.js#L239

**Comment by brianc** [comment]
I don't understand the feature request exactly? Are you saying you want to automatically use a prepared statement for queries & bypass the 'parse' stage the 2nd time the same query is executed on the same connection?  If that's the case - i'd rather leave that "higher level feature" to consumers of the lib and leave it explicit here in `pg`.  Doing things automatically has often caused issues in the past as this is the low level driver and should be explicit and un-opinionated when possible.

**Comment by abenhamdine** [comment]
@cekvenich are you looking for https://github.com/felixfbecker/node-sql-template-strings ?

**Comment by cekvenich** [comment]
@abenhamdine  no, I am not. 

@brianc argument taxes 2 strings. Seems that if you has you can bring it down to one argument passed.
