### ISSUE TITLE
No exception on failed query

### ISSUE THREAD

**Issue by jimcullenaus** [brianc/node-postgres#1991]
## Observed Behaviour

Our application lost its connection to the database, but kept on running just fine. The next time it attempted to make a query, nothing in particular happened.

This is the function where the query is made:

```ts
public async executeQuery(query : QueryConfig) : Promise<any> {
	try {
		let data = await this.client.query(query);
		return data['rows'];
	} catch (error) {
		Logger.error(`[QueryHandler.executeQuery] Error executing query ${query.name}: ${error.message}`);
		throw new Error(`Error executing query ${query.name}`);
	}
}
```

This function is called from within a class called `QueryHandler` that takes a `Client` parameter in its constructor, and is instantiated as follows:

```ts
const queryHandler = new QueryHandler(new Client());
```

The error log in the exception handler of `executeQuery` did not occur, and nor was the exception passed up the chain to where it would be displayed to alert the user of a problem. Thus, our application was running and silently ignoring failures for an extended period.

## Expected Behaviour

When a database call fails, an exception should be thrown. Especially so if the reason for the failure was an inability to contact the database.

**Comment by brianc** [comment]
I don't know of any instances where the client fails to emit an error when it disconnects - if you can reproduce it in a self-contained script I can take a look at it.  I'm guessing in this case you might be adding a `.on('error')` or something to the client somewhere else and swallowing the error.  Either way, feel free to open this back up if you can reproduce this with a script - then I can take a look at it and fix it!
