### ISSUE TITLE
release(true) what it does

### ISSUE THREAD

**Issue by pankleks** [brianc/node-postgres#1997]
Hello,

Quick question (I read the docs) but I don't really understand what is difference between calling `release()` from `release(true)`.

For example:
- pool has 1 connection
- I create client from pool (conn 1 is used)
- I `release()` conn1 is returned to pool
- I create another client from poll (conn 1 is used)

If in above example I would use `release(true)` what would be the difference?

Thanks!

**Comment by charmander** [comment]
The difference is that `release(true)` closes the connection. In your example, that means `release(true)` would create a new connection for the second `connect()`, rather than reusing the first.
