### ISSUE TITLE
Connecting a PostgreSQL via ssh

### ISSUE THREAD

**Issue by mariusbob** [brianc/node-postgres#2003]
I am using Postico to connect to a PostgreSQL database and now I am trying to build a small node.js application which connects to db and makes some queries.

The thing is that I have to connect to a ssh server before actually connecting to the PostgreSQL db. Is it possible with this module? I didn't find some information on docs webpage.

Attaching bellow the Postico config I am using right now and wanting to do the same from nodejs by using this module.
<img width="648" alt="Screenshot 2019-11-07 at 16 24 05" src="https://user-images.githubusercontent.com/1532570/68397440-df77d880-017b-11ea-8ee3-0c1f54199ad9.png">

**Comment by charmander** [comment]
You can set up port forwarding with OpenSSH:

```sh
mkdir -p remote-postgres
ssh -N -L remote-postgres/.s.PGSQL.5432:database_hostname:5432 username@ssh_host
```

then connect to that with pg:

```js
new Pool({
    host: '/path/to/remote-postgres',
    user: 'db_username',
    password: 'dbPassword',
    database: 'db_name',
})
```

That’s probably close to what Postico does.

**Comment by mariusbob** [comment]
yeah. That's what I am already doing when connecting to database from my node.js app.
I was wondering if this module supports that. Or should I use another one for ssh connection. 
Found ssh2 but I am not sure it works.

**Comment by charmander** [comment]
SSH is definitely outside the scope of this library. ssh2 would probably work (someone was doing that in #1999); I’m just not sure when it’d be worth the effort for development, considering it’s so straightforward and still scriptable with OpenSSH.

**Comment by mariusbob** [comment]
yeap...that is what i wanted to find out...This issue can be closed.
Thanks for the replies!

**Comment by alesak23** [comment]
See https://github.com/mscdex/ssh2/issues/67 for working example of using ssh2
