### ISSUE TITLE
server conn crashed

### ISSUE THREAD

**Issue by gajus** [brianc/node-postgres#2005]
```
[2019-11-08T20:11:48.335Z] ERROR (50) (@slonik): query execution produced an error
poolId:       01DS69ES6KXFCM0B1CH27ECFJF
connectionId: 01DS6A2S6KWCXE825NPWXRK0B4
queryId:      01DS6A9W7EAEJX8KDN3Z13PJVK
error:
  severity: ERROR
  code:     08P01
  name:     Error
  message:  server conn crashed?
  stack:
    """
      Error: server conn crashed?
          at /srv/node_modules/pg/lib/native/client.js:210:25
          at processTicksAndRejections (internal/process/task_queues.js:75:11)
    """

```

This error originates from `pg`.

What is this error?

**Comment by boromisp** [comment]
Actually it seems to be coming from pgbouncer: https://github.com/pgbouncer/pgbouncer/blob/834917d41e19dee5d14f726bcebd02ee082fa3a9/src/server.c#L481

**Comment by gajus** [comment]
Yes, the origin was indeed pgbouncer.

If I recall correctly, this was happening when connections were terminated due to `idle_in_transaction_session_timeout`.

I have worked around this as such:

https://github.com/gajus/slonik/commit/d2f59166fd98c59ea68a222e366d29e31460fcb6

I don't believe there is anything that `node-postgres` should do about it other than reporting the error on the client as it already does.
