### ISSUE TITLE
min connections in pool does not work/exist, documentation issue

### ISSUE THREAD

**Issue by ericpearson** [brianc/node-postgres#2011]
I am reposting issue #1869. The docs listed here https://www.npmjs.com/package/pg-pool indicate you can specify a minimum amount of connections to keep open. But this functionally does not exist anywhere in the code except in the type file as a config option.

Are there plans to implement this feature otherwise please remove it from the documentation as it is misleading. Thank you.

Original post:
```
let pool = new Pool({
        database: connectionConfig.database,
        port: connectionConfig.port,
        nolimit: connectionConfig.nolimit,
        user: connectionConfig.user,
        password: connectionConfig.password,
        host: connectionConfig.host,
        min: 1
    });
```
Expected:
At least one connection is always established

Actual:
I receive a removed event with pool.totalCount equals to zero. After that my process is terminated.

**Comment by sehrope** [comment]
The `min` property has been removed from the README for pg-pool a few months ago (see https://github.com/brianc/node-pg-pool/commit/70d5c0995852fba68391a5d4a19e234043d86198) but a new version has not yet been published to NPM.

**Comment by vitaly-t** [comment]
@sehrope Nice to find out like this...

**Comment by charmander** [comment]
The updated README has made it into a published version.

**Comment by enhanse** [comment]
Loopback 4 documentation references the `min` property as well.
https://loopback.io/doc/en/lb4/PostgreSQL-connector.html#connection-pool-settings

**Comment by rynop** [comment]
Is there a workaround/another way to keep `min` connections established?

**Comment by champikasam** [comment]
I also have a requirement to maintain a given, minimum number of connections to the database. Is there a known workaround to achieve this? I noticed that PgBouncer supports this but i prefer to use node-postgres if a viable workaround is available.
