### ISSUE TITLE
Connection terminated unexpectedly with long running query

### ISSUE THREAD

**Issue by bartpeeters** [brianc/node-postgres#2018]
I am running the following query: `select long_running_function()`, which is a function that can take up to 20 minutes to complete.

I am using connection a configuration which only changes the following parameters: port, user and database. The rest of the parameters are left the default value, so query_timeout and statement_timeout are still default: no timeout. 

I am running version 7.12.1 of pg and version 3.0.0 of pg-native.

I get the following error when using the non-native client:
```
/app/node_modules/pg/lib/client.js:252
      : new Error('Connection terminated unexpectedly')
        ^
Error: Connection terminated unexpectedly
    at Connection.con.once (/app/node_modules/pg/lib/client.js:252:9)
    at Object.onceWrapper (events.js:286:20)
    at Connection.emit (events.js:198:13)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:133:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
I also tried using the native client which gives the following error:
```
/app/node_modules/pg-native/index.js:154
  var err = new Error(message || this.pq.errorMessage())
            ^
Error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

    at module.exports.Client._readError (/app/node_modules/pg-native/index.js:154:13)
    at module.exports.Client._read (/app/node_modules/pg-native/index.js:203:17)
    at PQ.emit (events.js:198:13)
```

I have also tried using a pool, which gives the same problem.

In my database logs, which is postgres 11 running the timescaledb extension version 1.5.1, I always get the following log message when this happens:
```
LOG:  unexpected EOF on client connection with an open transaction
```

The function keeps running on the database and eventually completes. If I use a database client like dbeaver to execute the function I never get any errors.

Can anybody help me with how to go about debugging this error?
Postgres says the client is the one erroring, while the client says postgres is erroring and I don't really know where to look.

Both my node app and my postgres database are running in docker containers.

**Comment by sehrope** [comment]
This sounds like a TCP keep alive issue (not specific to this driver). It can occur when you have a NAT in between the client and database (ex: connecting from behind a home router to a remote server) or when there's virtualized networking in between in Docker / container based environments. When the connection eventually gets dropped both sides think the other closed the connection.

There's an old Docker issue that sounds similar: https://github.com/moby/moby/issues/31208. Try setting a custom TCP keep alive to see if that resolves  it.

**Comment by bartpeeters** [comment]
I executed the query `select pg_sleep(1800)` and it completed without problems. 

It seems like it has to do with the fact that the query I'm running is very intensive, aggregating data and then deleting old data.

**Comment by charmander** [comment]
> If I use a database client like dbeaver to execute the function I never get any errors.

From inside the container? How about with psql?

**Comment by bartpeeters** [comment]
I no longer seem to have these errors after restarting my system. So im closing this issue, which probably didn't even have anything to do with this library.

But still thanks a lot for the help!
