### ISSUE TITLE
There is no possibility to check if connection went successfully.

### ISSUE THREAD

**Issue by damianprzygodzki** [brianc/node-postgres#2019]
There is no possibility to check if connection went successfully. We can just hope and than check in query.

It should throw an error...
```
 try {
  await client.connect();
} catch (err) {
}
```

For now - it never catch anything.

**Comment by damianprzygodzki** [comment]
Whats more:

```
client.connect()
        .then(() => {
          console.log('connected');
        })
        .catch(err => {
          console.log(err);
        });
```

Even if there is no db to connect, i sometimes got `Error: Client has already been connected. You cannot reuse a client.`

**Comment by charmander** [comment]
> For now - it never catch anything.

In many cases where connection is failing pg can’t know if the connection is just slow. Eventually something should time out. There are a few [pool options][1] that you can configure lower if you need to. (I recommend using a pool even if you only need one client.)

> Even if there is no db to connect, i sometimes got `Error: Client has already been connected. You cannot reuse a client.`

You’re misusing the API in some way. It’s not clear exactly how, but calling `connect` twice on the same `Client` object is never valid.


[1]: https://node-postgres.com/api/pool/
