### ISSUE TITLE
Passwordless login only works with the native client

### ISSUE THREAD

**Issue by bjourne** [brianc/node-postgres#202]
Below shows me trying to connect to the "tngfooty" database using a unix domain socket without specifying a password. If I use the native client, it works. With the javascript client, authenticaton fails.

```
pg = require 'pg'
# If this line is omitted, password authentication will fail.
# pg = pg.native
pg.connect 'postgresql:///tngfooty', (err, client) ->
    console.log err
    client.query 'select now() as when', (err, result) ->
        console.log 'Row count: %d', result.rows.length
        console.log 'When: %s', result.rows[0].when
```

(sorry for the  coffeescript)

**Comment by ryanb** [comment]
I ran into this and ended up setting `PGHOST='/var/run/postgresql'` env variable so it does a peer connection to the socket instead of through localhost. You may need to set it to `/tmp` or wherever the socket is.
