### ISSUE TITLE
connectionString to TLSv1.3 works in python, but here got an error: connection requires a valid client certificate

### ISSUE THREAD

**Issue by segatrade** [brianc/node-postgres#2024]
Use this connectionString:

`connectionString = "postgresql://db_user:'pass%w@ord'@11.11.111.111:5555/postgres?ssl=true&sslcert=/home/username/.ssh/client.crt&sslkey=/home/username/.ssh/client.key&sslrootcert=/home/username/.ssh/ca.crt&"`

Got an error:

`error: connection requires a valid client certificate`

Also tried:
`ssl=1` - same error?
`sslmode=verify-full` - just ignore ssl

Same string with `sslmode=verify-full` works perfect in python

Nodejs version: v12.13.1
Ubuntu 18.04 WSL
OpenSSL 1.1.1  11 Sep 2018
PostgreSQL server TLSv1.3

import ssl
ssl.OPENSSL_VERSION
'OpenSSL 1.1.1  11 Sep 2018'

**Comment by charmander** [comment]
pg doesn’t have support for all connection string options yet (actually, none of the `ssl` ones). You can work around it with a configuration like this:

```js
({
    connectionString,
    ssl: {
        ca: fs.readFileSync('/home/username/.ssh/ca.crt'),
        cert: fs.readFileSync('/home/username/.ssh/client.crt'),
        key: fs.readFileSync('/home/username/.ssh/client.key'),
    },
})
```
