### ISSUE TITLE
Syntax error at or near

### ISSUE THREAD

**Issue by igibliss00** [brianc/node-postgres#2025]
I'm looking to query two total counts of data depending whether a field is before today's date or after.
```js
 const res = await client.query('SELECT COUNT("*") SUM(CASE WHEN "endDate" = CAST (current_date + INTERVAL "1 day" AS timestamp) THEN 1 ELSE 0 END) FROM "Booking" LEFT JOIN "User" ON ("Booking"."renter"="User"."id") GROUP BY "renter"')
```
However, I'm getting the error:
`error: syntax error at or near ""1 day""`

I tried without the CAST function: 
```js
const res = await client.query('SELECT COUNT("*") SUM(CASE WHEN "endDate" = current_date + INTERVAL 1 day AS timestamp THEN 1 ELSE 0 END) FROM "Booking" LEFT JOIN "User" ON ("Booking"."renter"="User"."id") GROUP BY "renter"')
```
but, I get the same error.

If I eliminate the quotation around `1 day`, I get an error saying that there is a syntax error at or near 1.

**Comment by charmander** [comment]
The syntax is `INTERVAL '1 day'`, with single quotes.

**Comment by igibliss00** [comment]
> The syntax is `INTERVAL '1 day'`, with single quotes.

Can't do single quotes since the outer quote is also a single quote

**Comment by charmander** [comment]
https://www.google.com/search?q=how+to+put+single+quotes+in+a+single+quoted+string+in+javascript
