### ISSUE TITLE
Seeking Help: (TypeError): net.Socket is not a constructor, When Following Guide

### ISSUE THREAD

**Issue by Dmo16** [brianc/node-postgres#2032]
Following this guide on the node-postgres.com site: 

[https://node-postgres.com/guides/project-structure](url)

I have setup my project structure to reflect the suggested guide.

Despite this, when I try to make a call to the `db.query` function as the guide shows, I get the error: 

`Unhandled Rejection (TypeError): net.Socket is not a constructor`

I am calling the function from an `actions.js` file like this: 

`
    db.query('SELECT * FROM allUsers', (err, res) => {
        if (err) {
            console.log(err)
        }
        console.log(res)
    });
`
The guide shows that they are using this same functionality from a `routes/user.js` file.

Am I doing something wrong? 

The action call is triggered by a user logging into the app.

Note: The query mentioned above is merely meant to be a test for me to make sure everything is wired up.

**Comment by charmander** [comment]
Are you trying to use pg in client-side code instead of Node.js, or running it through a bundler that’s configured to target a browser?

**Comment by williamleiby** [comment]
@charmander 

I'm getting a similar error to @Dmo16 above and I am trying to execute pg in client side code instead of on my Node.js back-end.
