### ISSUE TITLE
Query hangs forever

### ISSUE THREAD

**Issue by tapz** [brianc/node-postgres#2038]
My query hangs forever. No timeout, nothing. Tested with node 8, 10 and 12 and pg 7.14.0 and 7.15.1. Is it possible to enable some debug logging to know what is happening?

```
const sourceDatabase = new Client({
    connectionString: 'postgres://...',
    ssl:  {
      rejectUnauthorized: false
    },
    connectionTimeoutMillis: 15000
  });

const res = await sourceDatabase.query('SELECT * FROM users');
// NEVER GETS HERE
```

**Comment by sehrope** [comment]
You need to call `client.connect()` to connect the client. Otherwise the query will be queued up to execute once the client is connected (which never happens).

```js
const client = /* ... */;
await client.connect();
const result = await client.query('SELECT ...');
```

Or use a connection pool as it will handle connecting and subsequently releasing / closing the client.

**Comment by tapz** [comment]
Thanks! Had accidentally removed that line :-)
