### ISSUE TITLE
Event loop blocked

### ISSUE THREAD

**Issue by dknapp47** [brianc/node-postgres#2043]
While tracking down some issues that were blocking the event loop, we added the blocked-at module to our app and set the threshold to 50ms. We see a number of blocks that look like this:

Event loop blocked for 103.65371801757813 milliseconds [ '    at Socket.connect (net.js:918:7)',
  '    at Connection.connect (/usr/src/app/node_modules/pg/lib/connection.js:51:17)',
  '    at Client._connect (/usr/src/app/node_modules/pg/lib/client.js:88:9)',
  '    at Client.connect (/usr/src/app/node_modules/pg/lib/client.js:232:10)',
  '    at Pool.connect (/usr/src/app/node_modules/pg-pool/index.js:207:12)',

We are trying to determine if this is a real issue or a symptom of another issue.  Any suggestions would be welcome.

We are using pg 7.15.2 and pg-pool 2.0.8.

**Comment by brianc** [comment]
If you're not using the native bindings I can't imagine any reason at all the event loop would be blocked.   The native bindings use libqp which is _mostly_ non-blocking but does a few blocking things during its initial connect.  It looks like the line in question reported is during the connect routine which isn't very CPU intensive at all.  If you have a small self-contained piece of code I can take a deeper look for you though!

**Comment by dknapp47** [comment]
Thanks for the quick response Brian. I will see if we can reproduce it in an isolated piece of code.

**Comment by dknapp47** [comment]
Our app is a Loopback app. I have reproduced the issue with a minimal Loopback app.  I will now try to reproduce it in pure node.js.

Here are the logs from the minimal Loopback app in case they trigger any ideas:

checking client timeout
connecting new client
new client connected
pulse queue
no queued requests
Event loop blocked for 30.699608032226564 milliseconds [ '    at Socket.connect (net.js:918:7)',
  '    at Connection.connect (/Users/davidknapp/block-test/node_modules/pg/lib/connection.js:54:17)',
  '    at Client._connect (/Users/davidknapp/block-test/node_modules/pg/lib/client.js:102:9)',
  '    at Client.connect (/Users/davidknapp/block-test/node_modules/pg/lib/client.js:288:10)',
  '    at Pool.newClient (/Users/davidknapp/block-test/node_modules/pg-pool/index.js:208:12)',
  '    at Pool.connect (/Users/davidknapp/block-test/node_modules/pg-pool/index.js:183:10)',
  '    at PostgreSQL.executeSQL (/Users/davidknapp/block-test/node_modules/loopback-connector-postgresql/lib/postgresql.js:166:13)',
  '    at /Users/davidknapp/block-test/node_modules/loopback-connector/lib/sql.js:651:10',
  '    at /Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:259:9',
  '    at doNotify (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)',
  '    at PostgreSQL.ObserverMixin._notifyBaseObservers (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)',
  '    at PostgreSQL.ObserverMixin.notifyObserversOf (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)',
  '    at PostgreSQL.ObserverMixin.notifyObserversAround (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:228:15)',
  '    at PostgreSQL.SQLConnector.execute (/Users/davidknapp/block-test/node_modules/loopback-connector/lib/sql.js:650:8)',
  '    at PostgreSQL.find [as all] (/Users/davidknapp/block-test/node_modules/loopback-connector/lib/sql.js:1460:8)',
  '    at invokeConnectorMethod (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/dao.js:172:21)',
  '    at /Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/dao.js:1755:7',
  '    at doNotify (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)',
  '    at doNotify (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)',
  '    at doNotify (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)',
  '    at doNotify (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)',
  '    at Function.ObserverMixin._notifyBaseObservers (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)',
  '    at Function.ObserverMixin.notifyObserversOf (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)',
  '    at Function.ObserverMixin._notifyBaseObservers (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)',
  '    at Function.ObserverMixin.notifyObserversOf (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)',
  '    at Function.ObserverMixin._notifyBaseObservers (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)',
  '    at Function.ObserverMixin.notifyObserversOf (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)',
  '    at Function.ObserverMixin._notifyBaseObservers (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)',
  '    at Function.ObserverMixin.notifyObserversOf (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)',
  '    at Function.find (/Users/davidknapp/block-test/node_modules/loopback-datasource-juggler/lib/dao.js:1753:10)',
  '    at SharedMethod.invoke (/Users/davidknapp/block-test/node_modules/strong-remoting/lib/shared-method.js:270:27)',
  '    at HttpContext.invoke (/Users/davidknapp/block-test/node_modules/strong-remoting/lib/http-context.js:297:12)',
  '    at phaseInvoke (/Users/davidknapp/block-test/node_modules/strong-remoting/lib/remote-objects.js:695:9)',
  '    at runHandler (/Users/davidknapp/block-test/node_modules/loopback-phase/lib/phase.js:135:5)',
  '    at /Users/davidknapp/block-test/node_modules/async/dist/async.js:3110:16',
  '    at replenish (/Users/davidknapp/block-test/node_modules/async/dist/async.js:1011:17)',
  '    at /Users/davidknapp/block-test/node_modules/async/dist/async.js:1016:9',
  '    at eachLimit$1 (/Users/davidknapp/block-test/node_modules/async/dist/async.js:3196:24)',
  '    at Object.<anonymous> (/Users/davidknapp/block-test/node_modules/async/dist/async.js:1046:16)',
  '    at runHandlers (/Users/davidknapp/block-test/node_modules/loopback-phase/lib/phase.js:144:13)',
  '    at /Users/davidknapp/block-test/node_modules/async/dist/async.js:3110:16',
  '    at replenish (/Users/davidknapp/block-test/node_modules/async/dist/async.js:1011:17)',
  '    at /Users/davidknapp/block-test/node_modules/async/dist/async.js:1016:9',
  '    at eachLimit$1 (/Users/davidknapp/block-test/node_modules/async/dist/async.js:3196:24)',
  '    at Object.<anonymous> (/Users/davidknapp/block-test/node_modules/async/dist/async.js:1046:16)',
  '    at Phase.run (/Users/davidknapp/block-test/node_modules/loopback-phase/lib/phase.js:148:9)',
  '    at /Users/davidknapp/block-test/node_modules/loopback-phase/lib/phase-list.js:256:13',
  '    at /Users/davidknapp/block-test/node_modules/async/dist/async.js:3110:16',
  '    at replenish (/Users/davidknapp/block-test/node_modules/async/dist/async.js:1011:17)',
  '    at iterateeCallback (/Users/davidknapp/block-test/node_modules/async/dist/async.js:995:17)',
  '    at /Users/davidknapp/block-test/node_modules/async/dist/async.js:969:16',
  '    at /Users/davidknapp/block-test/node_modules/async/dist/async.js:473:16',
  '    at replenish (/Users/davidknapp/block-test/node_modules/async/dist/async.js:1006:25)',
  '    at iterateeCallback (/Users/davidknapp/block-test/node_modules/async/dist/async.js:995:17)',
  '    at /Users/davidknapp/block-test/node_modules/async/dist/async.js:969:16',
  '    at /Users/davidknapp/block-test/node_modules/async/dist/async.js:473:16',
  '    at replenish (/Users/davidknapp/block-test/node_modules/async/dist/async.js:1006:25)',
  '    at iterateeCallback (/Users/davidknapp/block-test/node_modules/async/dist/async.js:995:17)',
  '    at /Users/davidknapp/block-test/node_modules/async/dist/async.js:969:16',
  '    at /Users/davidknapp/block-test/node_modules/strong-remoting/lib/remote-objects.js:671:7',
  '    at process._tickCallback (internal/process/next_tick.js:61:11)' ]
remove idle client

**Comment by dknapp47** [comment]
I was not surprised that I could not reproduce it in a simple express app. I went back to the minimal Loopback app and added a custom method that calls the connector executeSQL method (the one just before the call to pg-pool in the trace above) and there was no blocking. I now suspect that this is some kind of issue in the Loopback code. I will close this while I follow that path. Thanks again for the quick response and a great package.

**Comment by brianc** [comment]
Glad you figured out what it was! Thanks for the follow up!

**Comment by dknapp47** [comment]
Brian - could you please take a quick look at this relate issue in the Loopback project:

https://github.com/strongloop/loopback/issues/4298

We have a simple loopback app that is reproducing the problem and have added detailed async operation logging. It appears that the offending async resource is a TCPWRAP. Does that indicate anything to you?

Thanks,
Dave

**Comment by brianc** [comment]
if you're not using the native bindings (it doesn't look like you are) then there's no way for the event loop to be blocked as `pg` only uses built-in non-blocking node APIs.  If you can reproduce the issue in an entirely self-contained script outside of the loopback framework (I'm not familiar with that framework) then I'll happily take a look!  But if it's a loopback benchmarky internals thing there isn't much I can do.

**Comment by dknapp47** [comment]
@brianc Thank you for your patience. You are right. pg was not blocking but was instead being blocked. We are zeroing in on the sources of the Loopback issue that is the cause in this issue strongloop/loopback#4298. Thanks again for all your help and the great package.
