### ISSUE TITLE
Many records to JS TypedArray

### ISSUE THREAD

**Issue by uasan** [brianc/node-postgres#2046]
Hi.
I need fetch many (100k+) rows from table, in row only one column type - int4.

```JS 
const result = query('SELECT "int4_value" FROM generate_series(1, 100001) int4_value');
const typedArray = Int32Array(result.rows.length);

// This over used memory and utilization proc
result.rows.forEach((row, index) => {
  typedArray[index] = row.int4_value;
});
```
I want a more effective solution.
So as not to load data into the JS array, get the whole result as a ArrayBuffer

Something like this:
```JS 
const result = query({
  text: 'SELECT "int4_value" FROM generate_series(1, 100001) int4_value',
  type: 'arrayBuffer',
});

const typedArray = Int32Array(result.arrayBuffer);
```
Is this possible?

**Comment by brianc** [comment]
you'd need to cast the data _inside_ postgres into a binary datatype or something that can be represented as a buffer.  Something like [this](https://www.postgresql.org/docs/9.1/datatype-binary.html) maybe?  The way things are represented at a protocol layer once it leaves postgres as multiple rows, each row is sent to the client over the wire one at a time.  The client could theoretically collect these rows into an array buffer...it still wouldn't be incredibly efficient.  If you wanted to collect these into an array buffer "client side" you could use [a stream](https://github.com/brianc/node-postgres/tree/master/packages/pg-query-stream) to do it...

Interested on how you figure this out eventually, lemme know!

**Comment by uasan** [comment]
Yes, I was thinking about aggregating an many of records into one record on a Postgres server.
I could not aggregate int4 to binary type (if you know, tell me how to do this in SQL?)
But I was able aggregate records to JSON
```SQL
SELECT jsonb_agg("int4_value") FROM LIMIT 200000
```
This is better, but still a lot of memory is wasted.

This use case not for stream, 100k+ iterations for one row, no fast.
If aggregation in a binary format will be more effective than JSON, then this is the right decision.

**Comment by brianc** [comment]
> (if you know, tell me how to do this in SQL?

sorry! Don't know actually - I googled for it a bit but didn't find anything.

**Comment by sehrope** [comment]
You can use the "...send(...)" functions to serialize server side datatypes to their on the wire representations:

```txt
=> \df int*send*
                              List of functions
   Schema   |      Name      | Result data type | Argument data types | Type 
------------+----------------+------------------+---------------------+------
 pg_catalog | int2send       | bytea            | smallint            | func
 pg_catalog | int2vectorsend | bytea            | int2vector          | func
 pg_catalog | int4send       | bytea            | integer             | func
 pg_catalog | int8send       | bytea            | bigint              | func
 pg_catalog | interval_send  | bytea            | interval            | func
(5 rows)
```

 For integers that's big endian bytes. You can then join them all together via string_agg:

```sql
SELECT string_agg(int4send(x), '') FROM generate_series(1,10) x;
```

```txt
                                     string_agg                                     
------------------------------------------------------------------------------------
 \x0000000100000002000000030000000400000005000000060000000700000008000000090000000a
```

That'll still have the full memory pressure on the server to create the aggregate result and the client to read it as one chunk, but if you really need everything in one bytea then you could try that as it's simple and direct. 

If that does not work try cursors / COPY to get the data streamed out and aggregate it yourself. If you know how many results are coming then you can even pre-allocate the target Buffer to exactly fill in the results.

**Comment by uasan** [comment]
Thank you very much.
Your example works fine in SQL, but I have a problem on Node.js, make In32Array from Buffer result, this is what goes
```JS
const res = await pool.query(
  "SELECT string_agg(int4send(x), '') as data FROM generate_series(1,10) x"
);

const data = res.rows[0].data;

const int32Array = new Int32Array(
  data.buffer, data.byteOffset, data.length / Int32Array.BYTES_PER_ELEMENT
);

console.log(int32Array);
```

print:
```
Int32Array [
   16777216,  33554432,
   50331648,  67108864,
   83886080, 100663296,
  117440512, 134217728,
  150994944, 167772160
]
```
I suspect that the problem is with offset or aligning bytes, but more than an hour of googling a working solution has not given.
Thanks anyway!

**Comment by uasan** [comment]
The question, the Postgres protocol, transfers binary data as a string (hex encoding), it takes a lot of memory, i.e. in my case the binary format (hex text) is not much better than the JSON text format?

**Comment by sehrope** [comment]
The Int32Array constructor treats each element in the Buffer as a value so you'll get data.length elements (not 4-bytes at a time). I don't think there's a direct way to convert it without some extra module (would be really easy in C...). You can do it manually via:

```js
const int32Array = new Int32Array(data.length / 4);
for(i=0;i<arr.length;i++) {
    int32Array[i] = data.readInt32BE(i * 4);
}
console.log(int32Array);
```

This outputs:

```text
Int32Array [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
```

Not sure how slow that'd be at scale though.

You're better off allocating it once and reading the results via a cursor. That way it'll scale out to any number of entries and node only needs to allocate memory for a fixed number of rows. Try something like this:

```js
const pg = require('pg');
const Cursor = require('pg-cursor');

function readCursor(cursor, count) {
    return new Promise((resolve, reject) => {
        cursor.read(count, (err, rows, result) => {
            if (err) {
                return reject(err);
            }
            return resolve(rows);
        });
    });
}

async function main() {
    const NUM_ROWS = 250000;
    const CHUNK_SIZE = 1000;
    const started = Date.now();
    const client = new pg.Client(process.env.DATABASE_URL);
    await client.connect();
    try {
        const sql = 'SELECT x FROM generate_series(1, $1) x';
        const cursor = new Cursor(sql, [NUM_ROWS]);
        client.query(cursor);

        const array = new Int32Array(NUM_ROWS);
        let index = 0;
        do {
            const rows = await readCursor(cursor, CHUNK_SIZE);
            if (rows.length === 0) {
                break;
            }
            rows.forEach(row => {
                array[index++] = row.x;
            });
        } while (true);
        const elapsed = Date.now() - started;
        console.log('Elapsed=%s ms ; Last Entry=%s', elapsed, array[array.length - 1]);
    } finally {
        client.end();
    }
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((err) => {
        console.error('%s', err.stack);
        process.exit(1);
    });
```

I'm getting about .5 seconds to run that for 250K entries:

```txt
Elapsed=465 ms ; Last Entry=250000
```

You can play with NUM_ROWS and CHUNK_SIZE to see how it effects memory and speed.

**Comment by uasan** [comment]
>  I don't think there's a direct way to convert it without some extra module

This is terrible )

I will try with the cursor, I think it will not be fast but smoothly and cheaply from memory.
Thanks!

**Comment by uasan** [comment]
Unfortunately cursors are slow, they are beneficial when the result does not fit in memory, but not in speed.

The problem is that I need to quickly release the connection, so this time is more critical than memory consumption.

I'm using aggregation in JSON:
```JS
console.time('Elapsed');

const res = await pool.query(
  'SELECT jsonb_agg(data) as data FROM generate_series(1, 250000) data'
);

const data = new Uint32Array(res.rows[0].data);
console.timeEnd('Elapsed');
```
```
Elapsed: 181.99ms
```

**Comment by charmander** [comment]
> I suspect that the problem is with offset or aligning bytes, but more than an hour of googling a working solution has not given.

> The Int32Array constructor treats each element in the Buffer as a value so you'll get data.length elements (not 4-bytes at a time).

`.buffer` is the backing `ArrayBuffer`, and `.byteOffset` and `.length` are used correctly. It’s the right approach, just for the wrong endianness.

Is the manual loop not better? There’s also the option of:

```js
const data = res.rows[0].data;

data.swap32();

const int32Array = new Int32Array(
  data.buffer, data.byteOffset, data.length / Int32Array.BYTES_PER_ELEMENT
);
```
