### ISSUE TITLE
pg.Result.fields isn't always an array

### ISSUE THREAD

**Issue by songsanli** [brianc/node-postgres#2056]
After [this commit](https://github.com/brianc/node-postgres/commit/e5d46749c0e41498da8451622dd3ed2218f717bd#diff-16be60eca5ce2d08e46c4822f4f56606R20), `pg.Result.fields` will be an array only after `pg.Result.addFields()` is called.

However, `pg.Result.addFields()` is called only in the callback of `RowDescription` event, which is dispatched by pg in response to a SELECT, FETCH, etc query. If I send sqls like `create SCHEMA hello`, the `pg.Result.fields` will remain undefined. This behavior is different from [the doc](https://node-postgres.com/api/result):

> Every result will have a fields array.

Please heve a look. Thanks.

**Comment by brianc** [comment]
ahh dang yeah I need to fix that, sorry about the hassle there.  I cut the end of my finger off on NYE  🤕 and juuust about healed up but haven't realy been able to type effectively up until yesterday...I'll get a change for backwards compatibility (+ a test for this) released ASAP (1-2 days 🤞 )
