### ISSUE TITLE
pg-query-stream runs VERY slow

### ISSUE THREAD

**Issue by gabrieldodan** [brianc/node-postgres#2058]
Hi,

I have noticed that ``pg-query-stream`` runs very slow compared to ``pg`` , about 10x slower ...Tested on

```
pg 7.17.0
pg-query-stream 2.1.2
node 12.14.0
postgresql 10
```

The old versions of ``pg`` and ``pg-query-stream`` works fine , ``pg 6.1.2`` and ``pg-query-stream 1.0.0``

Any idea?

Thanks!
Gabriel

**Comment by charmander** [comment]
How about the latest pg with an older pg-query-stream (2.0.0 or… 1.1.2?)? pg-query-stream had a fair number of changes made to it recently for correctness, although I’m not sure exactly how the versions worked out in the end.

**Comment by gabrieldodan** [comment]
Better, tested with pg-query-stream 2.0.0   Still a performance difference but not that huge

**Comment by brianc** [comment]
I'm going to release a new major version of pg-query-stream in about 1 hour.  The internals are substantially re-written.  Interested in if you see more performance improvements!  Also, I plan on working hard and long on performance for pg@9.0.  This module has collected some cruft and kept old, strange API design decisions around for a long time in the name of backwards compatibility or me not having enough time to get to things.  That's changing for 2020.  I had plans to already start on a bunch of this work, but cut the end of my finger off on NYE...now that I can (mostly) type okay again the work has resumed!  Stay tuned...just writing changelog entry for pg-query-stream@3.x and will push it.

**Comment by mike-marcacci** [comment]
That sounds like quite a new year! Best of luck!

**Comment by brianc** [comment]
my work day got a little out of control & I didn't get a chance to release - wanted to wait for a review on it & now its a bit late...would rather release in the AM when I get up so I'll do this w/ my morning coffee tomorrow.  Sorry for the delay!

**Comment by brianc** [comment]
hmmm sorry for not following up here sooner...I released pg-query-stream@3.0 a while ago...hopefully the performance issues are resolved for you now!  If they're not, please feel free to repoen w/ more info.
