### ISSUE TITLE
v7.17.1 - stream issue in Node.js < v8

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#2068]
In v7.17.1, with `pg-query-stream` 3.0.0, I am getting error under Node.js < v8

```
TypeError: stream.destroy is not a function
```

For example, I am testing it under Node.js v7.10.1

@brianc It seems that after changing from method `close` to method `destroy` on the stream, we lost compatibility with Node.js v7 and earlier.

**Comment by brianc** [comment]
Ah thanks for the heads up, I'll include a note about that in the changelog. 💃   Since it's semver major I'm fine w/ it dropping support for node < 8.  I'm planning on dropping support for node < 10 in a few days w/ pg@8.0 too! 👏

**Comment by vitaly-t** [comment]
@brianc  Is there any technological limitation that Node.js v8 is causing? i.e. what will be the justification for not supporting Node.js v8?

**Comment by brianc** [comment]
Mostly that node 8 is end of life...I think following along w/ the node LTS release cycle is a pretty manageable way to figure out which versions of node to target for support from pg.  I'd like modernize the codebase of pg & use newer features of v8 that don't exist in older versions of node (async/await for example!).  I think for folks running 2-3 year old verions of node they'll need to stay pinned to older versions of pg.

**Comment by vitaly-t** [comment]
@brianc The reality is such, many companies are stuck with older versions of Node.js in production, and dropping support for the sake of chasing Node.js release cycle will lock out a huge user base, without good reason. Therefore, I would advise against that, and not to drop older Node.js unless there is a good reason for it.

If you want to bring in `async`/`await`, it went official since Node.js 7.6.0, which is what I am supporting in pg-promise as the minimum version. And there wasn't any big change in Node.js that would be worth dropping older Node.js

**Comment by brianc** [comment]
Hmm let's continue the discussion over at #2062 - the plan for a long while has been to drop support for earlier versions of node.  I could be persuaded to keep node 8 in the test matrix & continue to support it...but that'd be as far back as I think is reasonable to go.
