### ISSUE TITLE
Issue with pg-query-stream dest.on is not a function

### ISSUE THREAD

**Issue by nhumrich** [brianc/node-postgres#2072]
Using the example code in pg-query-stream, you get an error that dest.on is not a function. 

Here is my code:
```node
const pg = require('pg')
const QueryStream = require('pg-query-stream')

let p = new pg.Pool({host: 'localhost', user: 'postgres', database: 'postgres'})
p.connect((err, client, done) => {
   if (err) throw err;
   const query = new QueryStream('SELECT * FROM generate_series(0, $1) num', [1000000])
   const stream = client.query(query)
   //release the client when the stream is finished
   stream.on('end', done)
   stream.pipe(console.log)
}
```

and I get the following error:
```
Uncaught TypeError: dest.on is not a function
    at PgQueryStream.Readable.pipe (_stream_readable.js:714:8)
    at PendingItem.callback (repl:7:10)
    at Pool._acquireClient (/home/nhumrich/project/node_modules/pg-pool/index.js:267:21)
    at /home/nhumrich/project/node_modules/pg-pool/index.js:230:21
    at Connection.<anonymous> (/home/nhumrich/project/node_modules/pg/lib/client.js:234:7)
    at Object.onceWrapper (events.js:411:26)
    at Connection.emit (events.js:316:22)
    at Connection.EventEmitter.emit (domain.js:545:15)
```

pg-query-stream version 3.0.0

**Comment by brianc** [comment]
ah that should be an easy fix - I can take a look at it tomorrow.  In the mean time, this should work:

```
const query = new QueryStream('bla bla')
client.query(query)
query.on('end', done)
```

basicaly `pg.Client.query` isn't returning the thing you pass it...that function is incredibly overloaded and I might have missed this case.

**Comment by brianc** [comment]
got a bit stuck at work today - will look @ this tomorrow!

**Comment by brianc** [comment]
I am looking at this...I don't think it's very straight forward to support things other than query configs from `pool.query` - `pool.query` is a helper method that checks out a client, dispatches a query, and then releases the client.  If there's an error checking out a client `pool.query` needs to reject...so for the time being it needs to return a promise.  I'll update the documentation to reflect that if you need to dispatch a stream you need to check the client out and dispatch it.  There's some work I can do to make this work in a non-hacky way...(e.g. the stream could emit an error if you can't connect) but it requires solidifying the `Submittable` concept a bit more thats on the docket for 9.0 work.  For now I'm going to update the documentation and mark this as a feature request.

**Comment by brianc** [comment]
oh wait a second...grr I misread your example.  sorry...one moment

**Comment by brianc** [comment]
You can't pipe a stream to `console.log` - you'll want to pipe to `process.stdout` or `process.stderr` - `console.log` is not a writable stream.

**Comment by charmander** [comment]
This isn’t `pool.query`, though, according to the bug description:

> ```js
> let p = new pg.Pool({host: 'localhost', user: 'postgres', database: 'postgres'})
> p.connect((err, client, done) => {
>    if (err) throw err;
>    const query = new QueryStream('SELECT * FROM generate_series(0, $1) num', [1000000])
>    const stream = client.query(query)
>    //release the client when the stream is finished
>    stream.on('end', done)
>    stream.pipe(console.log)
> }
> ```

(I haven’t reproduced it to confirm that it’s accurate, though. It’s not representative of the real test case at least in that there’s a missing parenthesis, for example.)

**Comment by AlexGalays** [comment]
That one caught me good as it's both wrong in the documentation and TS typings.

Only to then find out `pg-query-stream` is outdated and doesn't work anyway:

![image](https://user-images.githubusercontent.com/1375586/106485873-5734d000-64b1-11eb-8d82-892f99046069.png)
