### ISSUE TITLE
Pool.on('error'... doesn't fire up when `ERROR:  relation does not exist at character..`

### ISSUE THREAD

**Issue by damianprzygodzki** [brianc/node-postgres#2077]
I am catchin promise reject by try-catch, and also am attached to `error` event on Pool - but no one fires up when there is no table found!

**Comment by sehrope** [comment]
Pool error events are only issues for idle connections. You won't see them for commands you issue via `pool.query(...)` or on a checked out connection (retrieved via `pool.connect()`).

The `query(...)` API for this driver returns a Promise (which would reject on error) if no callback is specified. If a callback is specified as the last parameter then it will be invoked with the error:

```js
const sql = 'SELECT * FROM non_existentent_table';

// This will be a Promise rejection / throw in an await:
pool.query(sql);

// This will not reject because it will invoke the callback:
pool.query(sql, (err, result) => {});
```

**Comment by damianprzygodzki** [comment]
I assumed it should work that way. But there is no catch on error (without callback).

**Comment by sehrope** [comment]
Does running a successful query work? Ex: `SELECT 1`. If not, is it just hanging as it cannot connect?

If that works, show a full example that reproduces your lack of error and include the versions of pg, node, and the postgres server.

**Comment by NAlexPear** [comment]
I've run into this issue too on Postgres 12.3, Node 14.4, and `pg` 8.2.1. I've created a repo for repro-ing the issue [here](https://github.com/NAlexPear/pg-promise-reject-demo). The relevant `index.js` bits:

```javascript

const { Pool } = require('pg')

const pool = new Pool({
  // working connection info
})

const testProcess = async () => {
  try {
    const { rows: workingResult } = await pool.query('SELECT 1')

    // this should work
    console.log('test query', workingResult)

    const { rows: failingResult } = await pool.query('SELECT * FROM notatable')

    // this should never appear under any circumstance
    console.log('failing query', failingResult)
  } catch(error) {
    // this ^ should be the SQL error ("no relation notatable", etc) from the second query
    // but that SQL error is never registered as 'caught'
    // and this error never appears in the console
    console.error(error)
  }
}

testProcess()
```
