### ISSUE TITLE
jest reports open handlers when connecting with `ssl=true` to a local PostgreSQL (no SSL support)

### ISSUE THREAD

**Issue by cyrille-arundo** [brianc/node-postgres#2079]
**Expected behavior**

when testing a connection with ssl=true to a local PostgreSQL server (no SSL support),
jest should report OK

**Actual behavior**
when testing a connection with ssl=true to a local PostgreSQL server (no SSL support),
jest reports:
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
Done in 61.39s.  
```

**Note:**
It works fine if the connection string contains:

- correct username and password
- correct username and incorrect password

If fails with :

- correct username and password but with ssl=true

**Steps to reproduce**
Clone and run minimum test case at:
https://github.com/cyrilleverrier/pgtest

**Environment**
Version of pg: 7.17.1
OS type (Linux/Windows/Mac): PostgreSQL 9.6.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
Version of Node.js: v13.6.0

**Comment by charmander** [comment]
The `emit('error')`s in lib/connection.js not caused by an error event on the stream are missing code to destroy the stream.

**Comment by brianc** [comment]
I get a 404 when I try to access your minimum test case @cyrille-arundo

**Comment by vitaly-t** [comment]
@brianc The link he provided is wrong, should be [https://github.com/cyrilleverrier/pgptest](https://github.com/cyrilleverrier/pgptest).

**Comment by cyrille-arundo** [comment]
@brianc I forgot to push the git repo to my public account. It is fixed now, you can try to clone https://github.com/cyrilleverrier/pgtest

- https://github.com/cyrilleverrier/pgtest is the test case that uses `node-postgres` library.
- https://github.com/cyrilleverrier/pgptest is the test case that uses `pg-promise` library.

**Comment by cyrille-arundo** [comment]
@brianc  Thank you. I verified the fix works well :+1:
