### ISSUE TITLE
comparing Date to JSONB Date

### ISSUE THREAD

**Issue by pankleks** [brianc/node-postgres#2088]
Hello,

I have a table `test` with column `c` of type `jsonb` with object containing JS date in key `dt`

If I run following query directly on postgress:
`SELECT * FROM test WHERE (c#>>'{dt}')::TIMESTAMP = '2020-01-30T10:12:18.120Z';`

It properly returns 1 record.

If I run same query with pg-node:
```
SELECT * FROM test WHERE (c#>>'{dt}')::TIMESTAMP = $1
```
And pass JS date object with `2020-01-30T10:12:18.120Z` as `$1`

It does not return record anymore.

**Comment by charmander** [comment]
JavaScript `Date`s are instants in time, so pg passes them to the server assuming `timestamptz` (the PostgreSQL type that represents an instant in time). Casting that to `timestamp` just drops the time zone information.

There are lots of different potential fixes depending on what you’re trying to do:

- If the JSON value has time zone information that can be parsed as `timestamptz` (e.g. `Z`),

    ```sql
    SELECT * FROM test WHERE (c#>>'{dt}')::timestamptz = $1
    ```

- If you know which time zone the JSON value should use,

    ```sql
    SELECT * FROM test WHERE (c#>>'{dt}')::timestamp AT TIME ZONE 'UTC' = $1
    ```

- If you’re comparing timezoneless timestamps, pass a string as a parameter, not a `Date`. (If you got the `Date` from another query, that’s a pg issue; see the end of https://github.com/brianc/node-postgres/issues/993#issuecomment-267684417 for how to disable incoming `timestamp` conversion.)

    In this case, if you know that the format of the JSON value matches, comparing them as text without going through `timestamp` at all would be easiest.

**Comment by pankleks** [comment]
thank you
