### ISSUE TITLE
retry query if deadlock

### ISSUE THREAD

**Issue by gajus** [brianc/node-postgres#2092]
Not sure if this is something that should be handled by node-postgres or a client like Slonik (https://github.com/gajus/slonik/issues/144), but it would be desirable that the client automatically retries queries if a deadlock is detected.

**Comment by brianc** [comment]
Yeah I think retry behavior is really nice, but definitely served by a higher level module.  Every time I've added "automatically do ______" to this lib it's ended up being a mistake as it's consumed by so many various different things, the best path is to exactly expose an interface to postgres & let consuming libs build on fancier features.  I try to give the minimal number of opinions so it's maximally useful for the widest number of consumers.  Really my focus after 8.0 is going to be building better test coverage for the various SSL modes, and a whole bunch of performance work.  Looking forward to checking out slonik more!
