### ISSUE TITLE
Windows: Postgresql 12.1 facing TypeError: net.Stream is not a constructor

### ISSUE THREAD

**Issue by sanjuP7** [brianc/node-postgres#2095]
Hello,
**Code:** 

```js
const pg = require('pg')
const pool = new pg.Pool({
	user:'postgres',
	host:'localhost',
	password:'xxxx',
	database:'postgres',
	port:5432,
})

pool.connect((err,db,done) => {
	if(err){
		return console.log(err);
	} else {
		db.query('SELECT * from public.laps',(err,table) => {
			if(err){
				return console.log(err);
			} else{
				console.log(table)
			}
		})
	}
})
```
**Error:** 
_TypeError: net.Stream is not a constructor
new Connection
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/lib/connection.js:13
  10 | var Connection = function(config) {
  11 |   EventEmitter.call(this);
  12 |   config = config || {};
> 13 |   this.stream = config.stream || new net.Stream();
  14 |   this.lastBuffer = false;
  15 |   this.lastOffset = 0;
  16 |   this.buffer = null;
View compiled
new Client
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/lib/client.js:26
  23 | 
  24 | this._types = new TypeOverrides(c.types);
  25 | 
> 26 | this.connection = c.connection || new Connection({
     | ^  27 |   stream: c.stream,
  28 |   ssl: this.connectionParameters.ssl
  29 | });
View compiled
push../node_modules/pg/node_modules/pg-pool/index.js.module.exports.push../node_modules/pg/node_modules/pg-pool/index.js.Pool._create
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/pg-pool/index.js:87
  84 | 
  85 | Pool.prototype._create = function (cb) {
  86 |   this.log('connecting new client')
> 87 |   var client = new this.Client(this.options)
  88 | 
  89 |   client.on('error', function (e) {
  90 |     this.log('connected client error:', e)
View compiled
Pool._createResource
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:325
  322 | this._count += 1
  323 | this._log('createResource() - creating obj - count=' + this._count + ' min=' + this._factory.min + ' max=' + this._factory.max, 'verbose')
  324 | var self = this
> 325 | this._factory.create(function () {
      | ^  326 |   var err, obj
  327 |   var clientCb = self._waitingClients.dequeue()
  328 |   if (arguments.length > 1) {
View compiled
Pool.dispense [as _dispense]
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:313
  310 |       return clientCb(err, objWithTimeout.obj)
  311 |     }
  312 |     if (this._count < this._factory.max) {
> 313 |       this._createResource()
  314 |     }
  315 |   }
  316 | }
View compiled
Pool.acquire
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:391
  388 |     callback = process.domain.bind(callback)
  389 |   }
  390 |   this._waitingClients.enqueue(callback, priority)
> 391 |   this._dispense()
  392 |   return (this._count < this._factory.max)
  393 | }
  394 | 
View compiled
push../node_modules/pg/node_modules/pg-pool/index.js.module.exports.<anonymous>
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/pg-pool/index.js:111
  108 | Pool.prototype.connect = function (cb) {
  109 |   return this._promiseNoCallback(cb, function (resolve, reject) {
  110 |     this.log('acquire client begin')
> 111 |     this.pool.acquire(function (err, client) {
  112 |       if (err) {
  113 |         this.log('acquire client. error:', err)
  114 |         if (cb) {
View compiled
push../node_modules/pg/node_modules/pg-pool/index.js.module.exports.push../node_modules/pg/node_modules/pg-pool/index.js.Pool._promiseNoCallback
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/pg-pool/index.js:74
  71 | }
  72 | 
  73 | Pool.prototype._promiseNoCallback = function (callback, executor) {
> 74 |   return callback
  75 |     ? executor()
  76 |     : new this.Promise(executor)
  77 | }
View compiled
push../node_modules/pg/node_modules/pg-pool/index.js.module.exports.push../node_modules/pg/node_modules/pg-pool/index.js.Pool.connect
C:/Users/Administrator/Desktop/sanju/gp-bike/node_modules/pg/node_modules/pg-pool/index.js:109
  106 | }
  107 | 
  108 | Pool.prototype.connect = function (cb) {
> 109 |   return this._promiseNoCallback(cb, function (resolve, reject) {
  110 |     this.log('acquire client begin')
  111 |     this.pool.acquire(function (err, client) {
  112 |       if (err) {
View compiled
Module../src/components/LeaderBoard.js
C:/Users/Administrator/Desktop/sanju/gp-bike/src/components/LeaderBoard.js:57
  54 | 	port:5432,
  55 | })
  56 | 
> 57 | pool.connect((err,db,done) => {
  58 | 	if(err){
  59 | 		return console.log(err);
  60 | 	} else {_

I am facing Above Issue, which Showing net.Stream is not a constructor.
if Anyone have any idea please help me out 

**having:** 
npm version : 6.13.7
pg version : 5.2.1
postgresql : 12.1

**Comment by brianc** [comment]
did you run your code through webpack or are you running it in the browser?  `View Compiled` seems like a not normal thing to have in your stacktrace in node.  node-postgres is made to run inside node...it wont work in a browser environment (because `net.Stream` does not exist in the browser).  If you're running it through webpack to use in a lambda or something you'll need to make sure you're exposing [the proper node](https://webpack.js.org/configuration/node/) packages to your compiled code.
