### ISSUE TITLE
LOCK query returns on a table already locked in exclusive mode instead of waiting

### ISSUE THREAD

**Issue by shivansh** [brianc/node-postgres#2096]
I'm writing an application which allocates unique ports to clients from a table
of available ones. On acquiring a port, that entry is deleted from the table.
I'm currently experimenting with using a lock on the entire table when the
transaction begins.

```js
async acquire() {
  const client = await this.pool.connect();
  try {
    await client.query('BEGIN');
    await client.query('LOCK TABLE ports IN ACCESS EXCLUSIVE MODE');
    const res = await client.query('SELECT * FROM ports FETCH FIRST ROW ONLY');
    const freePort = res.rows[0].port;
    await client.query('DELETE FROM ports WHERE port = $1', [freePort]);
    await client.query('COMMIT');
    return freePort;
  } catch(err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}
```

For demo purposes, the table contains a single row, and the entire table is
locked before calling `acquire()`. This is shown below in the psql command line -

```
ports=> select * from ports;
 port
------
    1
(1 row)

ports=> begin;
BEGIN
ports=> lock table ports in access exclusive mode;
LOCK TABLE
```

Now `acquire()` is called by two separate processes running parallely, which
stop initially since the lock is held. Once the lock is freed (via the psql
command line), one of the processes (_P1_) acquires the lock and proceeds.
However, the other process (_P2_) also **seems** to be acquiring the lock at
the same time as it immediately proceeds to the next line, performs the
`SELECT` query and fails on the next line with the following trace -

```
(node:55749) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at PortManager.acquire (/Users/I512663/code/cloud-native-backing-services/core/port-manager/src/PortManager.js:33:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/I512663/code/cloud-native-backing-services/core/port-manager/src/integration.js:39:16
(node:55749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:55749) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Ideally process _P2_ should wait until process _P1_ releases the lock, but this
doesn't seem to be the case. Any help will be appreciated.

**Comment by brianc** [comment]
I'm not familiar w/ the acquire lock semantics in postgres really, but my hunch is you'll need to do some kind of `while` loop and check the result returned from the acquire lock query.  It likely contains information on whether the lock was acquired or not.  I'm not sure this is a bug w/ this library as pg doesn't do anything fancy with your queries, it just sends them & waits for the results...it's likely in how you're handling the results that will need to change.

**Comment by charmander** [comment]
Please make sure you’re showing the exact code you’re running. This can’t be it, because there’s a syntax error caused by a stray quote:

```js
await client.query('DELETE FROM ports WHERE port = $1', [freePort]');
```

**Comment by shivansh** [comment]
@charmander My bad, updated the snippet.

**Comment by shivansh** [comment]
> I'm not familiar w/ the acquire lock semantics in postgres really, but my hunch is you'll need to do some kind of `while` loop and check the result returned from the acquire lock query. It likely contains information on whether the lock was acquired or not. I'm not sure this is a bug w/ this library as pg doesn't do anything fancy with your queries, it just sends them & waits for the results...it's likely in how you're handling the results that will need to change.

@brianc The problem is that the response of the LOCK query doesn't contain any information that the lock wasn't actually acquired. The response in both the processes is same, shown below -

```
Result {
  command: 'LOCK',
  rowCount: null,
  oid: null,
  rows: [],
  fields: [],
  _parsers: [],
  _types: TypeOverrides {
    _types: {
      getTypeParser: [Function: getTypeParser],
      setTypeParser: [Function: setTypeParser],
      arrayParser: { create: [Function: create] }
    },
    text: {},
    binary: {}
  },
  RowCtor: null,
  rowAsArray: false
}
```

One workaround would be to remove the LOCK query and update the SELECT query to use NOWAIT, something along the lines of -
```
SELECT * FROM ports FETCH FIRST ROW ONLY FOR UPDATE NOWAIT
```
In that case the error message rightly indicates that the lock couldn't be acquired -
```
(node:61327) UnhandledPromiseRejectionWarning: error: could not obtain lock on row in relation "ports"
```
I can proceed with using this workaround, but I'm also interested in finding out what the issue might be with the former approach.

**Comment by charmander** [comment]
> The problem is that the response of the LOCK query doesn't contain any information that the lock wasn't actually acquired.

Without `NOWAIT`, isn’t the lock always acquired by the time the query returns without an error? I think the issue here is just that:

- the table has one row
- client 1 acquires lock
- client 2 waits on lock
- client 1 finds row
- client 1 deletes row
- client 1 releases lock
- client 2 acquires lock
- client 2 finds nothing
- client 2 reads `res.rows[0].port`, but `res.rows[0]` is `undefined` because the table is empty

**Comment by shivansh** [comment]
@charmander I was somehow getting confused with the results of the actual stress tests that I was running, but your analysis is perfect for this case. Thank you!
