### ISSUE TITLE
Need clarification regarding pg-native

### ISSUE THREAD

**Issue by Kankan-0** [brianc/node-postgres#2098]
https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/native/client.js#L11 
requires the 'pg-native' module. However, in the package.json(https://github.com/brianc/node-postgres/blob/master/packages/pg/package.json#L21) there is no mention of pg-native package. So, when I install pg and use it, sometimes it gives me an error of can't find module pg-native, although the functionality works well. Can anyone help me understand why there's no mention of pg-native in package.json file?

Thanks

**Comment by charmander** [comment]
lib/native/client.js isn’t loaded unless you access `pg.native`. See https://node-postgres.com/features/native/.
