### ISSUE TITLE
Different behavior calling .end() on a non connected Client between 7.17 and 7.18

### ISSUE THREAD

**Issue by InExtremaRes** [brianc/node-postgres#2108]
Calling `client.end()` on a `Client` not connected in `pg@7.17.1` fails with an error message

```plain
Socket is closed
```

However in `pg@7.18.1` the same call just hangs indefinitely. I'm using the promise-based call (without the callback) and `await`ing the promise to fulfil.

Is this an expected change?

If the context matters, I have a wrapper around a `Client` and I'm "unit testing" that a call to its closing function throws if the wrapped client is not connected. Before I was just calling `.end()` on the inner client but now the test fails since the promise never fulfilled.

If the change is expected, is there a way of knowing if a given `Client` is connected?

**Comment by brianc** [comment]
nope! not an expected change. hanging indefinitely is never my intended
behavior! i didn't really think about what would happen if you call .close
on an unconnected client.  i think it should just silently do
nothing...what do you think? i can write a test for this behavior and
ensure it stays consistent going forward

**Comment by InExtremaRes** [comment]
Yep. As long a it is consistent and documented a `noop` looks good to me. But still I think there should be a public way of knowing if a client is connected. I think there is a `_connected` property but seems to be private.

In our case we _do want_ to throw in that case since it can only happen due a developer mistake and not as a normal flow path; our wrapper can throw if the inner client is not connected and `pg.Client` can then just do nothing if `.end()` is called. Is that possible?
