### ISSUE TITLE
process.env.DATABASE_URL

### ISSUE THREAD

**Issue by iToto** [brianc/node-postgres#211]
I am using Heroku and for some reason, when I use process.env.DATABASE_URL to connect I get a connection error. When I set all the credentials manually (URL, username, password, db, port) the connection works.

I am relatively new to heroku and nodejs, and am having a hard time finding any documentation for my errors. Anyone else using this library with Heroku and have it working?

**Comment by Combobox-steamy** [comment]
> It's alright, I figured it out... I didn't know we could not access env vars on local machines. I had to create a env file to hold all my data and now it works. Sorry for the confusion guys, still getting used to Heroku and Node.js.





https://lnkr.fun/0a6f7a8
