### ISSUE TITLE
Question about pooling performance concern.

### ISSUE THREAD

**Issue by vdegenne** [brianc/node-postgres#2129]
Hi, just a question about performance.
I am kind of new in database usage, if I understand correctly pooling is used to request opened client to reduce connection time delay.
I saw in the documentation most of examples use a single pool object, for instance :

```javascript
const pool = new Pool();

pool.connect(...).
```

I want to take some time to care about the foundation of my application that's why I am asking you this because no matter how many times I read the documentation I still couldn't make a decision.

Is using one pool object throughout the whole application ok ? I know using one client is a bad idea but what about pools ?

For instance, is it ok to have a database module like `database.js`

```javascript
import {Pool} from 'pg';

const pool = new Pool({
  ...
});

export {pool};
```

and then in logic files (e.g. `usersManager.js`) :

```javascript
import {pool} from './database.js';

class UsersManager {
  static async getUsers () {
    const result = await pool.query('select * from users');
    ...
  }
}
```

-Or- is it better to use `new Pool` everytime I want to pull a client and make a query on a functional level ?

**Comment by sehrope** [comment]
For long running applications (ex: a web app), you want one pool created at application startup.

See https://node-postgres.com/guides/project-structure for project structuring examples.

Having multiple pools, managing the lifecycle of starting / stopping pools, or creating them on the fly would only be necessary in more unusual applications (ex: your database changes on the fly without your application restarting).

**Comment by vdegenne** [comment]
How did I miss this part in the documentation ? Thanks for confirming.
