### ISSUE TITLE
update case expressions data type error

### ISSUE THREAD

**Issue by houkk** [brianc/node-postgres#2130]
ENV:
node-postgres: `7.18.1`
pg: `11.6`

I know that the default data type is strings.
However, Why only the `update case expression` will report an error ?

```
let sql = 'update inventory.test_1 set test_num = case id when 5 then $1 when 6 then $2 end where id in (5,6) returning id'
let values = [11, 22]
```
The db type of colume 'test_num' is `int2`.

Error message follows:
```
error: column "test_num" is of type smallint but expression is of type text
```

**Comment by vitaly-t** [comment]
Have you tried executing it via PgAdmin or PSQL? The error will probably be the same, in which case it is a pure SQL issue, and not relevant to this library.

**Comment by houkk** [comment]
@vitaly-t 
The `prepareValue` in utils.js will convert integer to string.

**Comment by houkk** [comment]
@vitaly-t 
The `prepareValue` in utils.js will convert integer to string.

**Comment by charmander** [comment]
That string conversion is just for use in the text-format PostgreSQL protocol. This query will produce the same error anywhere the parameter types aren’t specified (including psql, like @vitaly-t said).

Specify the parameter types:

```sql
update inventory.test_1 set test_num = case id when 5 then $1::int2 when 6 then $2::int2 end where id in (5,6) returning id
```
