### ISSUE TITLE
Client unique identifier

### ISSUE THREAD

**Issue by wtcross** [brianc/node-postgres#2131]
I have interest in reporting on pg-pool events. Based on my observation there isn't a unique identifier for an instance of a client. Would adding a uuid property to the client class be something you would accept as a contribution?

**Comment by charmander** [comment]
You can do this by passing a different client type to the pool constructor:

```js
class UuidClient extends Client {
    constructor(options) {
        super(options);
        this.uuid = generateUuid();
    }
}

const pool = new Pool({
    Client: UuidClient,
});
```

**Comment by brianc** [comment]
You could do something like this in yer own app p easily:

```
const pool = new Pool()
pool.on('acquire', (client) => client.uuid = uuid())
```

**Comment by brianc** [comment]
https://github.com/brianc/node-postgres/blob/master/packages/pg-pool/index.js#L242
