### ISSUE TITLE
Create table can't be parameterized

### ISSUE THREAD

**Issue by ghivert** [brianc/node-postgres#2132]
Hi!

Just encountered what I think is a bug (or probably a security feature but didn't see in the docs).

Here's a minimal working example:

```javascript
const { Client } = require('pg')

const main = async () => {
  const client = new Client()
  await client.connect()
  await client.query('create table $1 (id int primary key)', ['test'])
  await client.end()
}

main()
```

If create table is followed by $1, then pg returns a syntax error near $1. Is that normal?

**Comment by brianc** [comment]
yah - you can't use parameters as table names, postgres doesn't allow it.  I was looking for the docs on exactly where you can put parameters but wasn't able to find it.  You can [use these escape functions](https://github.com/brianc/node-postgres/blob/1c8b6b93cfa108a0ad0e0940f1bb26ecd101087b/packages/pg/lib/client.js#L408) if you're taking user input in to decide on a table name, though probably want more sanitation than that.

**Comment by ghivert** [comment]
Ok thanks for the answer ! 

I ended up writing table names in the files. To give a little bit context, I’m [working on a package able to require SQL directly from files](https://github.com/ghivert/stonebraker) and I’m using PG for all my queries. I naively tried to use parameters in table names in another project using my package. 😅

Maybe I could try to PR something in the docs to avoid future users to end up in a situation like me?

**Comment by brianc** [comment]
ah that's super cool! I wrote something similar a while ago: https://github.com/brianc/node-querybox but it doesn't extract the named parameters out for you.

Yeah please feel free to PR to the docs - always open to PRS!

**Comment by charmander** [comment]
Duplicate of #1798
