### ISSUE TITLE
TypeScript types for returned values

### ISSUE THREAD

**Issue by bfelbo** [brianc/node-postgres#2133]
It would be amazing to combine this library with something like https://github.com/SweetIQ/schemats or https://github.com/nettofarah/postgres-schema-ts to get types for queries.

The other libraries could do the heavy lifting with Postgres.js looking up the types from the TypeScript interfaces that those libraries generate.

Only supporting simple column selects would already be amazing. For instance, here's a common query:
```
const data = await pool.query(`
  select api_level, system, brand from device
`)
```
Knowing that `api_level` is a number, `system` is an enum and `brand` is a string would help catch many bugs.

**Comment by vitaly-t** [comment]
What does it have to do with this driver?

**Comment by Urigo** [comment]
agreeing with @vitaly-t but I would also add that schemats and postgres-schema-ts are generating types for schema, not for queries...
https://github.com/adelsz/pgtyped is generating types for queries

**Comment by bfelbo** [comment]
I see. I'll close this issue then. Thanks for making me aware of pgtyped!
