### ISSUE TITLE
Client connection wasted after client.query('ROLLBACK')

### ISSUE THREAD

**Issue by ocalde** [brianc/node-postgres#2145]
I am working on a very basic tool for running SQL statements from files inside of a transaction, in which I read a file containing several SQL statements, and if everything goes fine, I log a record in a DB table; otherwise I rollback the transaction. 

As I iterate through a list of files, I was thinking of using a single client connection obtained from the pool, and use it for all the files I'm processing, to release that connection after iterating through all files.

However, it seems after the first rollback, next record cannot be processed as it seems client connection gets screwed up, throwing this error even though I begin a new transaction:

> `current transaction is aborted, commands ignored until end of transaction block`

Is this the correct behavior, or should I obtain a new client connection using pool.connect() on each file iteration?

```
let client;
  pool.connect()
    .then((pgClient) => {
      client = pgClient;
      return fs.readdir('src/changelog/files');
    })
    .then((files) => {
      const promises = [];

      files.sort().forEach((fileName) => {
        let errorMessage;
        promises.push(
          client.query('BEGIN')
            .then(() => fs.readFile(`src/changelog/files/${fileName}`, 'utf8'))
            .then((fileContentsSQL) => client.query(fileContentsSQL))
            .then((res) => client.query('INSERT INTO changelog (file_name, status) VALUES ($1, $2)', [fileName, 'SUCCESS']))
            .then((res) => client.query('COMMIT'))
            .catch((txnErr) => {
              errorMessage = txnErr.message;
              client.query('ROLLBACK');
            })
            .then((res) => client.query('INSERT INTO changelog (file_name, status, error_message) VALUES ($1, $2, $3)', [fileName, 'FAILURE', errorMessage]))
            .catch((otherError) => { console.log(otherError.message); }),
        );
      });

      return Promise.all(promises);
    })
    .catch((err) => {
      console.log(err.message);
    })
    .finally(() => {
      client.release(true);
    });
```

**Comment by brianc** [comment]
```
 .catch((txnErr) => {
              errorMessage = txnErr.message;
              client.query('ROLLBACK');
            })
```
You're not returning the promise here, and so the `catch` promise isn't waiting for `ROLLBACK` query to complete.

Highly suggest you use async/await if your environment allows it...it makes spotting this kinda stuff way easier!

**Comment by ocalde** [comment]
Thank you very much @brianc sorry I haven't noticed that, at first it was like 
`.catch((txnErr) => client.query('ROLLBACK'))`
That's why when I added the errorMessage line, forgot to add the return statement.

**Comment by brianc** [comment]
glad you figured it out!
