### ISSUE TITLE
v8.0.0 changelog?

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#2150]
Could we, please have the list of all the changes that v8.0.0 brings, compared to v7.18.2?

I am cautious about simply upgrading the dependency in `pg-promise`, not to bring in many new bugs because I do not know the scope of changes here.

And your [changelog](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md) contains nothing.

**Comment by brianc** [comment]
Oh good point - I updated [here](https://node-postgres.com/announcements#2020-02-25) with a bit of details on all the breaking changes but forgot to include something similar in the changelog. Will do!

**Comment by vitaly-t** [comment]
First thing where my tests failed... there used to be `Pool` class that represented the connection pool, but now its name is `BoundPool` suddenly.

```js
expect(pool.constructor && pool.constructor.name).toBe(`Pool`); // fails, succeeds for 'BountPool' now
```

**Comment by brianc** [comment]
yeah that was a change to make inheriting from the pool possible w/ es6 classes.  Other than the actual _name_ of the constructor changing hopefully this doesn't impact anything else.

**Comment by 1valdis** [comment]
+1, it would be nice to see 8.0.0 reflected in the CHANGELOG.md.

**Comment by brianc** [comment]
> +1, it would be nice to see 8.0.0 reflected in the CHANGELOG.md.

yup was just an oversight on my part, doing now
