### ISSUE TITLE
npm ERR! Failed at the pg-query-native@1.2.0 install script.

### ISSUE THREAD

**Issue by akanduri** [brianc/node-postgres#2153]
Hello,
Facing issue in Windows, here is the error, can you please help me on this issue.

Error:

gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:191:23)
gyp ERR! stack at ChildProcess.emit (events.js:198:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WORKSPACE\Service\node_modules\pg-query-native
gyp ERR! node -v v10.18.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pg-query-native@1.2.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pg-query-native@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by brianc** [comment]
I don't have the time to maintain native builds on windows, nor do I have access to a windows environment. I recommend using the pure javascript version of the library.

**Comment by akanduri** [comment]
Thank you for the prompt reply, could you please describe more on **pure javascript version of the library.** what exactly needs to do for the windows system.

I really appreciate your help

**Comment by brianc** [comment]
oh it looks like you're trying to install `pg-query-native` and you opened this issue on the wrong repository.

https://github.com/zhm/node-pg-query-native

**Comment by brianc** [comment]
if you want to install `node-postgres` (this repository) just run `npm i pg` or `yarn add pg`
