### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by raziEiL** [brianc/node-postgres#2156]
I am sending a query to a nonexistent table and expect to catch an error but got UnhandledPromiseRejectionWarning and my app stuck.
Code:
```js
// callback attempt
client.query("UPDATE locale SET lang = 'en' WHERE id = '1'", err => {
    console.log(err ? "err" : "okay");
});
```
```js
// promise attempt
client.query("UPDATE locale SET lang = 'en' WHERE id = '1'")
    .then(() => { console.log("then") })
    .catch(() => { console.log("catch") }); 
```
I did not got any console.log messasges... I'm so confused.
```js
(node:11872) UnhandledPromiseRejectionWarning: error: relation "locale" does not exist
    at Connection.parseE (d:\web\discord_bot\node_modules\pg\lib\connection.js:600:48)
    at Connection.parseMessage (d:\web\discord_bot\node_modules\pg\lib\connection.js:399:19)
    at Socket.<anonymous> (d:\web\discord_bot\node_modules\pg\lib\connection.js:115:22)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```
os: win10
"pg": "^8.0.0",
node v12.16.1

**Comment by brianc** [comment]
Is that the exact code from your app? I just tried that exact code locally in this repo and it worked.  Here's the script I ran:

```
const Client = require('./lib').Client

const client = new Client()

client.connect().then(() => {

  client.query("UPDATE locale SET lang = 'en' WHERE id = '1'")
    .then(() => { console.log("then") })
    .catch(() => { console.log("catch") }); 
})
```

it outputs the word `catch`...

I appreciate the bug report! This is concerning if its happening commonly...though tbh it's the first I've heard of it.  Is it possible you could provide an entirely self-contained script I could run to produce the issue?

**Comment by raziEiL** [comment]
I spent half a day to figure out what's going on (huge project). My apologies for false report. I just have one unhandled query in code. Thank you for answering.

**Comment by brianc** [comment]
oooof I've been there & feel your pain! Sorry you had to go through that.
How did you end up tracking it down, out of curiosity?  Always on the hunt
for tips on how to find those buggers.
