### ISSUE TITLE
Delimiter issues: "unterminated dollar-quoted string at or near"

### ISSUE THREAD

**Issue by DnOberon** [brianc/node-postgres#2167]
I'm attempting to run this query and running into an issue

```
pool.query(`CREATE OR REPLACE FUNCTION unpack_import_row()
	RETURNS TRIGGER
	language plpgsql
as $$
DECLARE
BEGIN
    IF NEW.data_json IS NOT NULL THEN
    	INSERT INTO data_staging(data, data_source_id, import_id)
    	SELECT value, imports.data_source_id, imports.id
    		FROM jsonb_array_elements((SELECT data_json from imports WHERE imports.id = NEW.id))
    		CROSS JOIN imports WHERE imports.id = NEW.id;
    END IF;

	RETURN NULL;
END;
$$;`)
```

Whenever I attempt to run I get the following error
```
unterminated dollar-quoted string at or near "$$
DECLARE
BEGIN
    IF NEW.data_json NOT NULL THEN
        INSERT INTO data_staging(data, data_source_id, import_id)
        SELECT value, imports.data_source_id, imports.id
                FROM jsonb_array_elements((SELECT data_json from imports WHERE imports.id = NEW.id))
                CROSS JOIN imports WHERE imports.id = NEW.id"
```

My assumption is that the driver is parsing my original query wrong, separating it at the first semi-colon. I'm wondering what the best way to get around this error might be?

**Comment by brianc** [comment]
The driver doesn't parse queries at all - it passes them entirely unaltered to the backend....it's likely there's an error w/ your query text.  Does the same query work in `psql`?

**Comment by DnOberon** [comment]
Same query runs fine through multiple different tools :\

**Comment by DnOberon** [comment]
I'm an idiot, please close this. This is an error previous code, not yours. Sorry!

**Comment by brianc** [comment]
haha you're not an idiot! We all make mistakes - I make this kinda mistake
all the time.  I thought there was a bug w/ nest.js the other day. No. Just
a bug w/ my brain. :p
