### ISSUE TITLE
Problem connecting on Node 14

### ISSUE THREAD

**Issue by dioslibre** [brianc/node-postgres#2174]
`pg.client.connect()` does not resolve, and no errors either.

**Comment by brianc** [comment]
what version of pg are you using? All tests are passing on master right now so it might be a config issue w/ your setup or an older version of pg which had an incompatibility w/ node@14

**Comment by cinek260** [comment]
I had problems using `knex` and `pg` with version `8.0.2`, after updating `pg` to version `8.0.3` everything is working well

**Comment by dioslibre** [comment]
I'm using version 8.0.2. will update now.

**Comment by dioslibre** [comment]
Confirmed. Version 8.0.2 was the culprit. Closing this.
