### ISSUE TITLE
Cannot connect to localhost db

### ISSUE THREAD

**Issue by renatonolo** [brianc/node-postgres#2175]
Hello.
I installed my postgres on a server on aws, open 5432 port to remote connection and I connected with successful.

But now I sent my project to the server and config my node-postgres environments to connect locally (i tryed 127.0.0.1, localhost and the local ip) and I cant connect. 

I am using the same user that I used o remote connection, the same database and the same password.

Somebody can help me?

**Comment by charmander** [comment]
Can you show the configuration in each case, the code, and the error message?

**Comment by renatonolo** [comment]
Yeah of course.
Some informations that I forget to said in first post is that I am using Pool connection with environment variables on process.env, but I already tryed to use connection string and object config.

Below it's my db.ts file (where I connect to the DB):
```typescript
import { Pool, QueryResult } from "pg";
import * as named from 'node-postgres-named';

export default class Database {

  private pool: Pool;

  constructor() {
    this.pool = new Pool();
  }

  async query(sql: string, ps?: object): Promise<QueryResult> {
    const client = await this.pool.connect();
    named.patch(client);

    try {
      return await client.query(sql, ps as any);
    } catch(err) {
      console.error(`Error to run query: `, sql, ps);
      console.log(err);

      return {
        rows: undefined,
        rowCount: undefined
      } as QueryResult;
    } finally {
      client.release();
    }
  }
}
```

On my remote .env file I am setting this variables:
```javascript
PGHOST=xxx.xxx.xxx.xxx <-- My remote IP
PGUSER=postgres
PGDATABASE=db
PGPASSWORD=postgres
PGPORT=5432
```

And my .env file it`s the same file, but I changed my IP to 'localhost'.
I tryed with 127.0.0.1 and the machine ip (172.xxx.xxx.xxx).

**Comment by charmander** [comment]
And the error message?

**Comment by renatonolo** [comment]
I don't get any error message, only the connection timeout.

**Comment by renatonolo** [comment]
PS.: I am using Node v14 on server and v12 on local development.

I saw in some new issues that this can be the probably problem.
I'll test with Node v12 on server.

**Comment by renatonolo** [comment]
After downgrade from NodeJS v14.0.0 to NodeJS v12.16.2, the connection works.

**Comment by charmander** [comment]
Upgrade to pg 8.0.3.
