### ISSUE TITLE
Error working with LargeObject API

### ISSUE THREAD

**Issue by Yone-e** [brianc/node-postgres#2176]
Trying to execute `SELECT lo_creat(?)` using `pg.Client.query()`. I'm getting error: 'syntax error at or near ")"'.

"node" 12.16.1, "pg" 8.0.2, "PostgreSQL" 12.0
```
const { Client } = require('pg'); 
...
const client = new Client({
  host: <host>,
  port: <port>,
  database: <database>,
  user: <user>,
  password: <password>,
});
await client.connect();
await client.query("SET SCHEMA '<schema>'"); // everything is fine
await client.query('SELECT lo_creat(?)', [0x00060000]); // throws error here
...
```

**Comment by charmander** [comment]
The [PostgreSQL syntax for parameters](https://node-postgres.com/features/queries/#Parameterized%20query) is `$n`, so you need to replace `?` with `$1`.
