### ISSUE TITLE
do not work with nodejs version 14

### ISSUE THREAD

**Issue by taoqf** [brianc/node-postgres#2181]
works fine with 13 and `pg-pool`, but will wait at connecting to database.

**Comment by brianc** [comment]
https://github.com/brianc/node-postgres/issues/2180

Please lemme know if upgrading to `v8.0.3` doesn't fix the issue - but should be fixed there, thanks!

**Comment by taoqf** [comment]
Thanks, `v8.0.3` works great.

**Comment by brianc** [comment]
glad to hear! LMK if anything else weird pops up for you!
