### ISSUE TITLE
Packages required using relative file paths causes issues when using workspaces

### ISSUE THREAD

**Issue by paprikati** [brianc/node-postgres#2188]
If you have conflicting versions of packages in your project for whatever reason, then requiring them 'relatively' is dangerous as the file structure might be different.

For example, in [`connection-fast`](https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/connection-fast.js) at line 15, you have

```
const { parse, serialize } = require('../../pg-protocol/dist')
```

This relies on these packages being installed inside the same `node_modules` folder, which I believe isn't a safe assumption

**Comment by vitaly-t** [comment]
Have you encountered an actual problem, or is it just a hypothetical?

**Comment by paprikati** [comment]
I encountered it myself.
I had two different versions of `postgres-manager` installed in the same yarn workspace.
They required different versions of `pg`, but both relied on the same version of `pg-protocol`. This meant that the nested `pg` didn't have a `pg-protocol` to find.

I resolved this by ensuring I only had one version of `postgres-manager` in the workspace. But it is possible that there would be a genuine use case for running two versions of `pg` in the same workspace, and this should not be blocked by something like this.

**Comment by brianc** [comment]
@paprikati good catch - that was hanging out from earlier experiementation...didn't mean for it to be in the normal require path just yet...either way I have a fix up now!

**Comment by vitaly-t** [comment]
@brianc  Nice! Will there be a release today? :wink:

**Comment by brianc** [comment]
yah! I gotta figure out how to support the `no-verify` ssl option in a
perfectly backwards compatible way - I thought I had but...i very very
subtly changed it & that broke the native driver so gonna take another pass
at this:
