### ISSUE TITLE
bind message supplies 1 parameters, but prepared statement "" requires 0

### ISSUE THREAD

**Issue by anirudhgiri** [brianc/node-postgres#2192]
Code :
```javascript
const query = 'SELECT * FROM users WHERE username = \'$1\';';
    const params = ['myusername'];
    client.query(query,params).then((result) => {
```
Error :
`error : bind message supplies 1 parameters, but prepared statement "" requires 0`

Hello!
 I'm trying to use parameterized queries in node-postgres but I'm being met with the error above. Even though the query requires a parameter ($1), and I'm supplying the parameter through the variable `params`, I get this error telling me the prepared statement requires 0 parameters.

**Comment by sehrope** [comment]
Don't quote the `$1`, otherwise PostgreSQL thinks it's a literal. You also do not need the semicolon:

```js
const query = 'SELECT * FROM users WHERE username = $1';
```

**Comment by anirudhgiri** [comment]
Ah. Thanks a ton!
