### ISSUE TITLE
Connection kills promise. Lost, nowhere to be found

### ISSUE THREAD

**Issue by nhumrich** [brianc/node-postgres#2193]
I have a new computer, and on my new computer, node postgres isn't connecting. The behavior is very very strange. 

Given the following code:
```node
const { Client } = require('pg')
const client = new Client({host: 'localhost', username: 'guest', password: 'guest', database: 'postgres'})

client.on("error", (err) => console.error("connection error", err));

async function run() {
    try {
      console.log('hello')
      await client.query('select pg_sleep(2)')
      console.log('done')
    } catch (error) {
      console.log('error',error);
   }
 return 1
};

run().catch((e) => {console.log(e)})
```

The following script never prints anything except 'hello'. Doesnt print an error, doesnt print 'done'. Just prints 'hello' and then ends immediately. It almost like the Promise is just getting killed. No error messages, nothing.
I am pretty confident the issue is somewhere in this library. 

- [x] Can connect to postgres using psql
- [x] Can connect to postges using python + sqlalchemy
- [x] Can connect to postgres using node + postgres.js
- [ ] Can connect to postgres using node + node-postgres (pg)

I am using postgres version 12.2, node-postgres version 7.18.2, node version 14.1.0

Any suggestions on what to look at to help fix the problem?

**Comment by charmander** [comment]
You haven’t started a connection attempt, so the query sits in a the query queue but doesn’t actually enqueue any work for Node.

```js
await cllient.connect();
```

**Comment by nhumrich** [comment]
Adding in `client.connect()` doesnt change anything. I have updated the above snippet.

**Comment by nhumrich** [comment]
Oddly, if I try with the native bindings by adding `.native` on the very first line, it all works. Without native bindings, it doesnt. 
Sadly, that isn't a workaround for me because I need the cursors

**Comment by nhumrich** [comment]
Ok, issue is fixed by updating to pg version 8.  Thanks for this library!
