### ISSUE TITLE
pg-pool: .end never resolves

### ISSUE THREAD

**Issue by morigs** [brianc/node-postgres#2199]
Reproduction:
```ts
const pool = new Pool({
  host: 'db',
  user: 'postgres',
  password: 'postgres',
});
await pool.connect();
await pool.end(); // hangs here
```

Cause: [this condition](https://github.com/brianc/node-postgres/blob/0729130c5747d09030bead21cbc5baa5731ffb9a/packages/pg-pool/index.js#L112)
`pool.connect` creates new client and `pool.end` doesn't close existing clients (and doesn't throws an error when there are clients in the pool).
It seems pool should remove all clients when `.end` is called

**Comment by charmander** [comment]
It waits for clients to be closed, because it can’t know whether they’re still in use. Something could be added here, but remember that leaking clients is always really bad.

**Comment by brianc** [comment]
yeah we could add `pool.end(force: boolean)` which would force close all clients, which would result in any checked out client likely throwing an error and closing all their sockets immediately.  Might not be an incredibly pleasant way to shut things down, but it could be the nuclear option.  Honestly though like @charmander said _typically_ if you're calling `pool.end()` and your app is just hanging and not terminating this indicates you're leaking clients somewhere....its really a best practice kinda thing to ensure you have predictable shutdown when you want it, including in tests, and leave the "terminate everything immediately" situations to unhandled exceptions where you want to bring the whole process down.

**Comment by morigs** [comment]
I do not create any clients except when calling `pool.connect()`. Does this mean that this function is causing a leak (with one client lol)?

**Comment by charmander** [comment]
@morigs Sort of. It’s not a leak that will grow and exhaust the pool, but in general you need to release clients back to the pool:

```js
const client = await pool.connect();
// …
client.release();
```

**Comment by morigs** [comment]
@charmander Oh dear, my bad. Now I see note about `release` after `connect` in the docs. Thanks!
