### ISSUE TITLE
Exceptions - Can I access SQL

### ISSUE THREAD

**Issue by markddrake** [brianc/node-postgres#2201]
When you print a Postgres exception using console.log() it appears to have a SQL attribute. However when you try to access e.SQL it is undefined. Is there a way to access the SQL ? What I actually want to do is trim the list of parameters from it, as it can be very long when doing bulk inserts.

**Comment by charmander** [comment]
> When you print a Postgres exception using console.log() it appears to have a SQL attribute.

Can you show the relevant output?

**Comment by markddrake** [comment]
Brain Fart.. Sorry
