### ISSUE TITLE
Select not returning when using accentuation

### ISSUE THREAD

**Issue by LuizGMX** [brianc/node-postgres#2203]
I'm trying to use a word with accentuation in my WHERE clause but it's not working.
And when I retrieve data that cotains a word with accentuation i always get "�" in place.

**Comment by charmander** [comment]
Please show the relevant code and output, and, if possible, a minimal script to reproduce the problem.

**Comment by LuizGMX** [comment]
`router.get("/filtraEspecialidade", function (req, res) {    

    async function listaEspecialidades() {

        await db.connect()

        var result;
        result = await db.query(`
    SELECT te.des_especialidade 
    FROM arq_medico am
    INNER JOIN arq_medico_especialidade ame ON ame.id_medico = am.id_medico
    INNER JOIN tab_especialidade te ON te.id_especialidade = ame.id_especialidade
    WHERE am.ind_status = 'Ativo' AND EXISTS (SELECT 1 FROM arq_agendap WHERE am.id_medico = arq_agendap.id_medico LIMIT 1) 
`)        
        res.send(result.rows);

    }
    listaEspecialidades();

});`

**Comment by charmander** [comment]
Where are the accents? Where is the output?

Anyway, respond with the encoding you’re sending:

```js
res.set('Content-Type', 'text/plain; charset=utf-8')
```

**Comment by LuizGMX** [comment]
Here's the output
![image](https://user-images.githubusercontent.com/44658199/81438761-ab3d9e80-9143-11ea-9757-482d0b41e043.png)

**Comment by LuizGMX** [comment]
![image](https://user-images.githubusercontent.com/44658199/81440916-34a2a000-9147-11ea-8d51-42b31a8f577e.png)

**Comment by LuizGMX** [comment]
Any help?

**Comment by charmander** [comment]
Can you show the results of that query using another tool, like psql? Are they correct in that case?

**Comment by LuizGMX** [comment]
yes it's correct, see: 
![image](https://user-images.githubusercontent.com/44658199/81482905-b27eae00-9210-11ea-9f08-9727f0f2afcc.png)

**Comment by LuizGMX** [comment]
Hi, can someone help me?

**Comment by boromisp** [comment]
Please execute the following queries both in node.js, and in the environment that returns the expected characters (pgAdmin?) and show us the results.

```sql
SHOW client_encoding;
SHOW server_encoding;
```

**Comment by LuizGMX** [comment]
![image](https://user-images.githubusercontent.com/44658199/81594879-f819b300-9397-11ea-90e2-333d8eb78c7e.png)
![image](https://user-images.githubusercontent.com/44658199/81594952-0d8edd00-9398-11ea-98f2-964fb6c7dfb7.png)
![image](https://user-images.githubusercontent.com/44658199/81595005-26978e00-9398-11ea-8b5f-972f021ecad6.png)
![image](https://user-images.githubusercontent.com/44658199/81595032-344d1380-9398-11ea-8828-c8657b327f3b.png)

**Comment by LuizGMX** [comment]
Any help?

**Comment by LuizGMX** [comment]
Someone?

**Comment by boromisp** [comment]
Storing anything other then ASCII in SQL_ASCII will cause a lot of pain because SQL_ASCII databases [do not encode or decode the text](https://www.postgresql.org/docs/current/multibyte.html).

If it is doable you should [change the encoding](https://stackoverflow.com/questions/5090858/how-do-you-change-the-character-encoding-of-a-postgres-database) of your database to utf8.

I'm not sure, if there is any other workaround with node.js.

**Comment by LuizGMX** [comment]
UnfortunatelyI can’t change it because the database is not mine.

De: Peter B<mailto:notifications@github.com>
Enviado:terça-feira, 12 de maio de 2020 10:16
Para: brianc/node-postgres<mailto:node-postgres@noreply.github.com>
Cc:Luiz Gustavo<mailto:luizguestape54@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [brianc/node-postgres] Select not returning when using accentuation (#2203)


Storing anything other then ASCII in SQL_ASCII will cause a lot of pain because SQL_ASCII databases do not encode or decode the text<https://www.postgresql.org/docs/current/multibyte.html>.

If it is doable you should change the encoding<https://stackoverflow.com/questions/5090858/how-do-you-change-the-character-encoding-of-a-postgres-database> of your database to utf8.

I'm not sure, if there is any other workaround with node.js.

**Comment by boromisp** [comment]
You should definitely try to have the database converted.

The only other option I can see is to experiment with the [`convert` / `convert_to` / `convert_from`](https://www.postgresql.org/docs/current/functions-string.html#FUNCTIONS-STRING-OTHER) functions and use them in every query.

The real encoding of your stored data is probably not utf8, but the default encoding of your OS in your locale.
You are going to have to convert between that encoding and the `client_encoding` (utf8).

**Comment by brianc** [comment]
> However this config option is buggy ([isn't used everywhere](https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/connection.js#L147)) right now.

It's been a bit lower priority as encodings are a bit finicky & there are larger fish to fry ATM, but I'm definitely open for a PR to fix this @boromisp!  Only for encodings node natively supports for now though, I don't want to take another dependency on `iconv-lite` or anything.

As far as using `SQL_ASCII` with non-ascii characters...yeah you definitely don't wanna be doing that!

**Comment by LuizGMX** [comment]
Thank you guys for your help!

**Comment by boromisp** [comment]
@LuizGMX
The workaround I've posted before (manually setting the client_encoding) doesn't work for input, only output, so WHERE condition, INSERT value, etc. will still use utf8 encoding.
