### ISSUE TITLE
Encoding situation

### ISSUE THREAD

**Issue by Ygarasab** [brianc/node-postgres#2204]
Hey, I'm working on a litle api that is using node-postgres, but i'm having some encoding issues

I've made a query through a Client, and got the following response:

```
[
  { value: 2, text: 'cent¡metros' },
  { value: 1, text: 'metros' },
  { value: 5, text: 'pacotÆos' },
  { value: 4, text: 'pacotes' },
  { value: 3, text: 'unidades' }
]
```
So, i've got ¡ instead of í and Æ instead of ã.

I wondered if it was a pg issue but the database cli showed the correct carachters.

I'm brazilian, so this sort of character will be quite common to enter the database, and I really don't know how to solve that :/

**Comment by vitaly-t** [comment]
Looks like your client encoding isn't set right, which is not relevant to this library.

**Comment by Tubskleyson** [comment]
Oh, i tried set it like this:

```
new Client({
            user: 'myuser',
            host: 'localhost',
            database : 'mydb',
            password : 'topsecretpassword',
            client_encoding: 'utf8',
            port : 5432
        })
```

Isn't utf8 the right encoding? Or should I set it up other way?

**Comment by Tubskleyson** [comment]
Sorry for that, got a little bit confused with the mobile aplication buttons

Still need help c:

**Comment by Ygarasab** [comment]
Hey, I figured ou what happened

So, it turns out that the problem was in the windows prompt encoding, you see, I did some entries there, and they looked just fine in the terminal, but when i looked at it anywhere else, the encoding just seemed outta place. So I tried making some entries with especial carachter through the API I was doing, and when I tried to get then the encoding was OK.

So yeah, no issue with the module and power shell == bad
