### ISSUE TITLE
db.end() doesn't close connection

### ISSUE THREAD

**Issue by LuizGMX** [brianc/node-postgres#2205]
I open an at the end i close it with await db.close(), but when whenever another function tries to connect again, I get the error message saying that I cant reuse a connection.

router.get("/filtraEspecialidade", function (req, res) {
    async function listaEspecialidades() {
        await db.connect()
        var result;
        result = await db.query(`
    SELECT te.des_especialidade 
    FROM arq_medico am
    INNER JOIN arq_medico_especialidade ame ON ame.id_medico = am.id_medico
    INNER JOIN tab_especialidade te ON te.id_especialidade = ame.id_especialidade
    WHERE am.ind_status = 'Ativo'
    AND EXISTS (SELECT 1 FROM arq_agendap WHERE am.id_medico = arq_agendap.id_medico LIMIT 1) 
`)

       await db.end()
        res.set('Content-Type', 'text/plain; charset=utf-8')
        res.send(result.rows);
    }
    listaEspecialidades();
});

**Comment by vitaly-t** [comment]
Connection are represented by the `Client` interface. Those are non-reusable. Once closed, the connection cannot be restored on the same `Client` object.

But you shouldn't re-connect on each HTTP request, that's total misuse of connections. You should use a connection pool instead.

**Comment by LuizGMX** [comment]
got it thank yout
