### ISSUE TITLE
Support options/PGOPTIONS connection parameter/environment variable

### ISSUE THREAD

**Issue by rafiss** [brianc/node-postgres#2214]
Postgres describes this parameter here: https://www.postgresql.org/docs/9.1/libpq-connect.html#LIBPQ-CONNECT-OPTIONS. This driver should support passing through the parameter, or reading it from an environment variable.

This was previously requested in this issue: https://github.com/brianc/node-postgres/issues/1482 I believe that issue was closed mistakenly. Here is [the Postgres source code](https://github.com/postgres/postgres/blob/7dd777938bbeae8113f73849920a5b19bef723d9/src/interfaces/libpq/fe-connect.c#L253) that looks at this parameter.

It looks like the fix would be in the `ConnectionParameters` object. I am happy to create a PR to addrss this issue.
https://github.com/brianc/node-postgres/blob/70cf4dc6edbe1e4d5b6e4ddbe9ebaabc656ff738/packages/pg/lib/connection-parameters.js#L121-L126

**Comment by brianc** [comment]
yeah I don't understand the use case of that param exactly but happy to
review a PR about it.  Should be easy to support in both the native & pure
JS version.  The key would just be making sure it has test coverage as the
tests are the only way I can reliably maintain the codebase for years when
some of the features added are things I don't use directly (at least not
_yet_) :)
