### ISSUE TITLE
I am getting error in pg:"8.2.0"

### ISSUE THREAD

**Issue by rakibl45** [brianc/node-postgres#2222]
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1142:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}

**Comment by charmander** [comment]
Is your PostgreSQL server running (on localhost, on that port)? Are you able to connect with anything else?

Also, please make sure to use the latest version, which is 8.2.1.

**Comment by olaven** [comment]
Having the same issue on `8.2.1`. I am able to connect with pgadmin.

**Comment by brianc** [comment]
@olaven would need more info to help you diagnose.  It's 99.99% related to your environment. Either how your postgres is configured (does it allow connections over non-unix sockets?) or how you're configuring the client to connect.

**Comment by olaven** [comment]
@brianc Thanks for the quick response. 
In my case, I just discovered that the error was due to me not understanding docker containers/linking. See https://github.com/microsoft/vscode-dev-containers/issues/369

Sorry about the noise!

**Comment by brianc** [comment]
no worries - glad you figured it out!

**Comment by mriedem** [comment]
This can be closed, right? Sounds like it's not a problem in node-postgres.
