### ISSUE TITLE
v4.4.3 query hangs on migration to new environment

### ISSUE THREAD

**Issue by mjacksonest** [brianc/node-postgres#2224]
I don't expect you to troubleshoot such an old version, v4.4.3, but we are trying to pull off a migration without the extra burden of extensive code changes.

Code that executes without error in a legacy environment, hangs intermittently when migrated to a kubernetes based deployment.

The issue manifests as complete radio silence after processing rows.  The row events fire and it gets through thousands of rows, but then there is nothing, no additional events off either client or query objects.  We do have successful runs, but every so often it hangs like described.

We are not using the native bindings.  I will try swapping in native bindings as a next quick fix attempt, but any insights you might have on things to try, save upgrading to latest, would be helpful.

**Comment by mjacksonest** [comment]
The task with an issue was using two versions of pg 😱 
The second was coming into a library that was broken out and the version version eventually diverged.
I'll confirm if this addressed the issue.

**Comment by brianc** [comment]
haha glad you got it figured out!  FWIW upgrading probably wont be* too bad*.
V 4 is pretty old, but the number of drastic breaking changes between major
versions has been pretty low...I'm just really really mindful of backwards
compatibility so do a semver major for anything that could be breaking.
