### ISSUE TITLE
node-postgres on Arch Linux does not connect to server

### ISSUE THREAD

**Issue by southball** [brianc/node-postgres#2227]
I have problems using node-postgres on my Arch Linux installation. The database has a new user created, and I can login and execute queries with `psql` on that machine and on the host machine.

The code I am using to try is as follows:

```js
const { Client } = require('pg');

const client = new Client({
    host: 'localhost',
    user: 'judgeserver',
    password: '<redacted>',
    port: 5432,
    database: 'judgeserver',
});

async function main() {
    console.log('Begin');
    await client.query('SELECT 1')
        .then(console.log)
        .catch(console.error);
}

// Prevent process from quitting
setTimeout(() => {}, 50000);

main();
```

The same problem happens also when `Client` is replaced with `Pool`, or when I used `connectionString: "postgresql://judgeserver:<redacted>@localhost:5432/judgeserver"`.

The program does not give any error. When I watch the log of PostgreSQL with log level set to `debug5`, there is no new log message when I execute this script, while there are log messages when I connect with `psql` and execute queries with `psql`.

I want to ask if there is anything I can do to debug the issue, including if there are any options in `node-postgres` to increase the log messages/verbosity.

---

**System information:**

OS: Arch Linux
PostgreSQL version: 12.3
node-postgres version: tried on both 7.18.2 and 8.2.1

**Comment by charmander** [comment]
When using `Client` instead of `Pool`, you need to call `client.connect()`. Which version of Node is this?

**Comment by southball** [comment]
Sorry, I seem to have resolved the issue but I do not know why, and I am sorry for missing `client.connect()`. Client with `client.connect()` and Pool are both working now.

Regarding node version, I have just tried again on Node 14.3.0 (both Arch and NVM), and Node 12 (NVM). Both of them are working now.
