### ISSUE TITLE
Async Example Wrong?

### ISSUE THREAD

**Issue by dschinkel** [brianc/node-postgres#2228]
Why does your example show async/await but the `Client` function is not async?  My IDE instantly detected that there is no async function to await on when I pasted in your example after installing pg.

`await client.connect()` is awaiting a standard non-async function here

```
const { Client } = require('pg')
const client = new Client()
await client.connect()
const res = await client.query('SELECT $1::text as message', ['Hello world!'])
console.log(res.rows[0].message) // Hello world!
await client.end()
```

I mean am I missing something?

**Comment by dschinkel** [comment]
If you have to wrap everything in an IIFE please state that in all examples...it's not inferred to some.

**Comment by charmander** [comment]
Duplicate of #1631
