### ISSUE TITLE
Sorting not working properly when uisng parameterized queries

### ISSUE THREAD

**Issue by jakjs21jdkw** [brianc/node-postgres#2233]
I am running into an issue where my select statement is not returning results in the correct order when using parameterized queries. For example, using the postgres console I can execute the query
`SELECT * FROM <database> ORDER BY <column> DESC NULLS LAST OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;`
and this will return results in the correct order. I can execute the the statement above using text only, and it will work fine. However, if I parameterize the query using something like this:
`SELECT * FROM <database> ORDER BY $1 DESC NULLS LAST OFFSET $2 ROWS FETCH NEXT $3 ROWS ONLY;`
the query does not return with nulls last and the table remains in a random order.
The sorting issue is present when the columns have null values or have empty strings.

I am on version 8.2.1.

**Comment by sehrope** [comment]
That query is using the value of the parameter as a constant in the order by clause so it's effectively:

```sql
SELECT ...
FROM  ...
ORDER BY 'some-constant' DESC
```

You cannot use $1, $2, ... etc parameters for identifiers like column names. You need to have it be part of the query itself.

To prevent SQL injection, use something like pg-format (https://www.npmjs.com/package/pg-format) to incorporate the column name in the SQL.

You can also implement this in a fixed SQL using CASE ... WHEN ... logic though it requires the column names to be fixed and is a bit less efficient than determining the column in advance in the query:

```sql
SELECT t.*
FROM some_table t
ORDER BY
  CASE $1
    WHEN 'foo' THEN t.foo
    WHEN 'bar' THEN t.bar
  END
```

For that to work the data types also need to align (can't have one be text and another be a number without additional casting or complexity) so you're usually better off using the pg-format approach.

**Comment by jakjs21jdkw** [comment]
Using pg-format worked. I was able to do `format("%s", <column>)`. Thanks @sehrope

**Comment by sehrope** [comment]
@jakjs21jdkw Do no use `%s` as that does a plain replacement. You should use `%I` so that the value gets escaped as an identifier. Otherwise you're prone to SQL injection.

**Comment by jakjs21jdkw** [comment]
Good catch. Thank you again @sehrope
