### ISSUE TITLE
A problem with connection - it stops receive notification after a while

### ISSUE THREAD

**Issue by budarin** [brianc/node-postgres#2234]
I've setup PG Client
```js
const client = new pg.Client({
    connectionString: `postgres://${user}:${password}@${host}:5432/`,
    keepAlive: true,
});

client.connect().then(() => {
    client.on('error', (error) => {
        console.log('error', error);
    });

    client.on('end', () => {
        console.log{ 'PgClient is end.');
    });

    client.on('notification', (notification) => console.log('received', notification));

    client.query('LISTEN chanell_1');

}).catch((error) => {
    console.log('PG Client connection error');
});
```

after some timeout PG Client stops receiving notification from server without `end` or `error` events
Postgres is setup as Docker service in overlay network type

**Comment by brianc** [comment]
If you're using `notification` you'll typically want to manually connect a long lived client outside the pool and manage it yourself...leaving a client in the pool with notifications being listed for is bad as the pool will close idle clients.

**Comment by budarin** [comment]
@brianc I don't use pg.Pool - I use pg.Client for listening

**Comment by sehrope** [comment]
If the connection is idle, this is likely a TCP timeout. If there is a NAT in between the client and server, it's possible for the connection to be silently dropped. Until you issue a write to the socket you wouldn't notice the breakage as neither end receives a notification.

Check if TCP keep alives are enabled. This is usually a system wide setting. It's not something specific to the driver.

You can also try periodically running a dummy query (ex: `SELECT 1`) to check once per minute if the connection is alive with some short timeout. If not, end the connection and create a new one.

As it's possible for the connection to be killed anyway (ex: if the PG server kills your backend), you should be handling this case anyway. That way you can bounce your DB server and the application will heal itself once it's back online.

**Comment by budarin** [comment]
@sehrope I try to run PG and client at the same machine

it also strange for me - if the connection is broken for any reason, why does the client not respond to the break with any of the events?

**Comment by sehrope** [comment]
If everything is local it should detect the broken TCP connection. If there's any network hops or virtualization in between, it might not until an actual read or write is attempted. Even then depending on how things are broken for the network it might just hang unless timeouts have been setup.

**Comment by budarin** [comment]
@sehrope  when I was talking about the timeout I was referring to the timeout activity with db

**Comment by boromisp** [comment]
The only reliable way I've found way to detect a broken connection on clients I use for notifications, is to periodically execute a dummy query on it.

One way to trigger this dummy query is using the [`socket.setTimeout`](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback) method:

```js
client.connection.stream.on('timeout', () => { /* execute query * /);
client.connection.stream.setTimeout(60000);
```

Also make sure to set a reasonable timeout for this query (manually with `global.setTimeout`, or with the `query_timeout` configuration option), because with half-open TCP connections the query could hang indefinitely.

**Comment by vitaly-t** [comment]
@budarin 

One has to watch the connection, and auto-restore listeners when a new connection is established.

This is why there are several specific libraries that implement reliable listeners, like [node-pg-pubsub](https://github.com/voxpelli/node-pg-pubsub), etc.

I also spent a lot of time doing this with `pg-promise`, which resulted into [pg-listener](https://github.com/vitaly-t/pg-listener).

**Comment by budarin** [comment]
I found the problem: TCP TCP / IP.
By default, it is not configured the same way on different devices and operating systems.

My solution to this problem was:
```
client = new pg. Client({
    connectionString,
    keepAlive: true,,
});
```

and configuring the TCP/IP Protocol parameters that all Docker services have:
```
sysctl:
    network.IPv4.tcp_keepalive_time: 480
    network.IPv4 Protocol. tcp_keepalive_intvl: 60
    network.IPv4.tcp_keepalive_probes: 9
```
