### ISSUE TITLE
Unable to get duplicate columns from table

### ISSUE THREAD

**Issue by ksaketh19** [brianc/node-postgres#2237]
When we do a self join a table like this 

```SELECT c.CustomerID, c1.CustomerID FROM Customers c, Customers c1 where c.CustomerID != c1.CustomerID AND c.country=c1.country;```

It returns only one CustomerID in the res.rows. However it has two fields in Fields object

We tried to hit the postgres directly through terminal and able to get two duplicate columns

**Comment by sehrope** [comment]
This driver defaults to returning rows as an object with field names as properties. If there are multiple fields with the same name, only one will be available on the result row object (I think the last one).

To have both columns show up you need to give it an alias (`some_column AS some_alias_name`) in your query:

```sql
SELECT
  c.CustomerID,
  c1.CustomerID AS "OtherCustomerID"
FROM Customers c
  , Customers c1
WHERE c.CustomerID != c1.CustomerID
  AND c.country=c1.country
```

Alternatively you can use the "arrayMode" for results: https://node-postgres.com/api/result That will provide the result rows as an array in the order they appear in the query.

I'd suggest column alias approach, not the array mode approach. It's easier to reason about and it's a good practice when writing SQL to give each resulting field a unique name.
