### ISSUE TITLE
Please support the IN operator

### ISSUE THREAD

**Issue by mcandre** [brianc/node-postgres#2238]
Many PostgreSQL users are used to the traditional `IN` operator rather than the `ANY` operator. Can the library be updated to work better with `IN` queries?

**Comment by charmander** [comment]
It can’t. `IN` requires a list of values in the text of the query, and pg doesn’t change the text of queries. It’s better to learn how parameters work.

**Comment by brianc** [comment]
What problems w/ in queries are you having?  The library's purpose is to provide a fast, stable, and __low level__ connection to postgres.  That means we don't do any modification or parsing of your queries in any way...
