### ISSUE TITLE
pg.connect hangs

### ISSUE THREAD

**Issue by ghost** [brianc/node-postgres#224]
Hello there!

I'm interested in a guideline for using this module in more than one .js file. 

Currently we are doing the following:
1) require the module in each file
2) assign it to a local variable of that file (i.e: var pg = require('pg'); )
3) use pg.connect and, therefore, the pool to create new clients.
4) we call connect on every CRUD method in our models.

We are facing random hang outs while executing mocha tests  (at on one point the tests stop running but not always the same pg.connect call) so it seems no more connections are available for pg client.

How we should handle pg connections?

Thank you in advance,

Regards

**Comment by Alchemist0823** [comment]
> ```js
> function(err, client) {
> ```

Thanks. that's very helpful
