### ISSUE TITLE
Major performance issues with bytea performance

### ISSUE THREAD

**Issue by regevbr** [brianc/node-postgres#2240]
Hi,

I encountered the exact same issue as #1286 wheres a simple query to retrieve a 100mb bytea column from a one table, one row DB takes forever and causes the cpu to spike at 100%, rendering my node instance unresponsive.

After investigating, I think I found the cause in the `pg-protocol` package https://github.com/brianc/node-postgres/blob/ea6ac2ad2313af57159b10a0292c0c178e8e0923/packages/pg-protocol/src/parser.ts#L91-L93

Which suffers from the same thing as the original issue - too many allocations and buffer copies going around. I believe the fix introduced back then in https://github.com/brianc/node-packet-reader/pull/3 should solve the problem here.

**Comment by lognaturel** [comment]
Just started running into this and feeling very grateful to see it’s been fixed for a while now already! Thank you, @regevbr, @brianc. 😊
