### ISSUE TITLE
Passing parameters to `IN`

### ISSUE THREAD

**Issue by retrohacker** [brianc/node-postgres#2242]
Heya, how would one go about passing parameters to a query with `IN`?

For example:

```SQL
SELECT *
FROM people
WHERE name in ($1)
```

I've tried to use:

```js
pg.query(query, [['drake', 'zoey']], cb)
```

But I don't get results back when both `drake` and `zoey` are in the table.

However the following does seem to work:

```js
pg.query(query.replace(/\$1/, ['drake', 'zoey'].map(v => `'${v}'`).join(','), cb)
```

**Comment by boromisp** [comment]
For this kind of parameter formatting you need an sql generator library. I would advise against rolling your own.

I'm pretty sure there are [many](https://github.com/brianc/node-postgres/wiki/Extras) examples, I've personally use pg-promise for this purpose:
https://github.com/vitaly-t/pg-promise/blob/master/README.md#csv-filter

**Comment by charmander** [comment]
You can use `= ANY` instead:

```sql
SELECT *
FROM people
WHERE name = ANY ($1)
```

**Comment by charmander** [comment]
Duplicate of #1452

**Comment by charmander** [comment]
> However the following does seem to work:
>
> ```sql
> pg.query(query.replace(/\$1/, ['drake', 'zoey'].map(v => `'${v}'`).join(','), cb)
> ```

(and, to be clear, definitely *do not* do this. It’s an SQL injection vulnerability.)

**Comment by retrohacker** [comment]
<3 thank you
