### ISSUE TITLE
How to create a theme for BandagedBD?

### ISSUE THREAD

**Issue by TailsTheFox890** [brianc/node-postgres#2244]
This link https://github.com/Gibbu/BetterDiscord-Themes/tree/master/RadialStatus has a theme for a person, I downloaded it and I like it. When I create my own theme, it doesn’t work for me. I wanted to try to do as he did, nothing worked. Someone can tell how to create a theme and to work and not so that doesn't work?

**Comment by charmander** [comment]
Seems unrelated to PostgreSQL?

**Comment by TailsTheFox890** [comment]
> Seems unrelated to PostgreSQL? … [again](https://github.com/brianc/node-postgres/issues/2152)?

No. I finished the bot a long time ago and figured it out myself
it was a long time ago, I forgot my account password, it was too lazy to restore.

**Comment by charmander** [comment]
But why are you asking questions about Discord in the bug reports of a project that isn’t related to Discord at all?

**Comment by TailsTheFox890** [comment]
> But why are you asking questions about Discord in the bug reports of a project that isn’t related to Discord at all?

I just can't find other places to ask. Either I can’t do anything at all, or there is a problem with registration. I ask where I can, even if they don’t do it in one place or another, there are places where they don’t answer at all, or they don’t answer adequately.

**Comment by charmander** [comment]
Okay. Well, this repo is nevertheless probably a worse choice than all of those other places.
