### ISSUE TITLE
Create/Drop Schema query parameters not working

### ISSUE THREAD

**Issue by mikelax** [brianc/node-postgres#2247]
# Overview

It appears that [parameterized queries](https://node-postgres.com/features/queries) are not working for create / drop schema statements. 

Here is an code snippet with error output:

```javascript
async function createSchema () {
  try {
    await pool.query('create schema $1', ['testschema1'])
  } catch (err) {
    console.log(`error: ${err}`)
  }
}

createSchema()
```

The error output is:  `error: error: syntax error at or near "$1"`

### node
14:00 $ node --version
v12.16.1

### pg
8.2.1

**Comment by sehrope** [comment]
This is not a driver bug. The PostgreSQL server does not support parameters for identifiers.

For this type of thing you need to use dynamic SQL. Take a look at [pg-format](https://www.npmjs.com/package/pg-format) for handling escaping the values to ensure you do not have SQL injection.

**Comment by mikelax** [comment]
ok, thanks @sehrope I was wondering if that might be the case. Thanks for clarifying, I'll close this.

**Comment by Envek** [comment]
I faced it when I tried to `DROP DATABASE` and `CREATE DATABASE`. It would be better if there was some note in [the docs](https://node-postgres.com/features/queries#parameterized-query).

**Comment by brianc** [comment]
docs are open source! feel free to add some notes & I'll adjust them if you don't have time to get 'em just perfect. 😄

**Comment by Envek** [comment]
@brianc here it is: https://github.com/brianc/node-postgres-docs/pull/94

**Comment by brianc** [comment]
beautiful! thanks! :heart:
