### ISSUE TITLE
Required dependencies as devDependencies in pg-cursor

### ISSUE THREAD

**Issue by Tymek** [brianc/node-postgres#2249]
I've got some problems using a package with `pnpm`

```
Cannot find module 'pg/lib/result.js' from 'node_modules/.pnpm/pg-cursor@2.2.1/node_modules/pg-cursor/index.js'

    Require stack:
      node_modules/.pnpm/pg-cursor@2.2.1/node_modules/pg-cursor/index.js
...
```

In **`pg-cursor`, should we move `pg` from `devDependencies` to `peerDependencies`?** PR welcome? I belive this can solve my issue.

**Comment by charmander** [comment]
> In pg-cursor, should we move pg from devDependencies to peerDependencies? PR welcome?

Yep!
