### ISSUE TITLE
How to insert data in this way

### ISSUE THREAD

**Issue by togetupinfo** [brianc/node-postgres#2251]
How to insert data in this way
 thanks！

Sql：

 INSERT INTO public.instance(
	 instance_series_key, sop_instance_uid, sop_class_uid, instance_number, metadata, create_time, instance_study_key)
	VALUES (123,'123','1234',1,'','2020-6-24 17:46:03',123),(123,'123','1234',1,'','2020-6-24 17:46:03',123)

This way doesn't work.

    var values = [[123,'123','1234',1,'','2020-6-24 17:46:03',123],[123,'123','1234',1,'','2020-6-24 17:46:03',123]]
    const query = {
        name: 'test',
        text: 'INSERT INTO public.instance(instance_series_key, sop_instance_uid, sop_class_uid, instance_number, metadata, create_time, instance_study_key) VALUES ($1, $2,$3, $4,$5, $6,$7 );',
        values: values,
        rowMode: 'array',
      }
    pg_pool.query(query, (err, result) => {
        if (err) {
            throw err
        } 
        console.log(result)
    })

**Comment by boromisp** [comment]
- `unnest` with multiple array parameters: https://github.com/brianc/node-postgres/issues/957#issuecomment-295583050
 - `jsonb_to_recordset` with a single array of objects parameter: https://github.com/brianc/node-postgres/issues/1644#issuecomment-595231696
 - `COPY` from file: https://github.com/brianc/node-pg-copy-streams
 - Dynamic prepared statement generation:
```js
// Returns a string in this format:  'VALUES ($1,$2,$3),($4,$5,$6)'
function buildValues(rows, cols) {
  return 'VALUES ' + Array.from({ length: rows })
    .map(
      (_, r) =>
        '(' + Array.from({ length: cols })
          .map((_, c) => '$' + (r * cols + c + 1))
          .join(',') + ')',
    )
    .join(',');
}

const query = {
  text: `
INSERT INTO public.instance(
  instance_series_key, sop_instance_uid, sop_class_uid,
  instance_number, metadata, create_time, instance_study_key
) ${buildValues(values.length, values[0].length)};`,
  // Don't forget to flatten the values array.
  values: values.flat(),
};
```
 - Or you could construct the entire query dynamically with interpolated values, using something like the the pg-promise library's insert helper: https://vitaly-t.github.io/pg-promise/helpers.html#.insert:
```js
const pgp = require('pg-promise')();

const table = 'instance';
const columns = [
  'instance_series_key', 'sop_instance_uid', 'sop_class_uid',
  'instance_number', 'metadata', 'create_time', 'instance_study_key'
];

// Turn the `values` into array of objects
values = values.map(row => columns.reduce((obj, col, i) => {
  obj[col] = row[i];
  return obj;
}, {}));

const query = { text: pgp.helpers.insert(values, column, table) };
```

**Comment by vitaly-t** [comment]
@boromisp Version that uses the source array directly:

```js
const pgp = require('pg-promise')();

const columns = [
  'instance_series_key', 'sop_instance_uid', 'sop_class_uid', 'instance_number', 'metadata', 'create_time', 'instance_study_key'
].map((name, index) => ({name, init: c => c.source[index]}));

const cs = new pgp.helpers.ColumnSet(columns), {table: 'instance'});

const insertSql = pgp.helpers.insert(values, cs);
```
