### ISSUE TITLE
This dependency was not found: * dns in ./node_modules/pg/lib/connection-parameters.js

### ISSUE THREAD

**Issue by HTG-YT** [brianc/node-postgres#2258]
I am currently using `pg` with Vue.js, and I am currently trying to get my development server up and running. However, I got this error:
``` INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                         13:42:33
This dependency was not found:

* dns in ./node_modules/pg/lib/connection-parameters.js

To install it, you can run: npm install --save dns
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
```

It seems like the `dns` dependency is not found, however I do find the dns dependency in the node standard library:
![image](https://user-images.githubusercontent.com/39023054/85915732-84b2fe80-b87c-11ea-8e96-78acb9c28d92.png)

And I am very curious what is the problem here.

**Comment by HTG-YT** [comment]
Node version: 12.4.0
pg version: 8.2.1

**Comment by brianc** [comment]
Node postgres isn't made to run in the browser.  It's a node only (server side) module which relies on node internals such as dns, net, buffer, ssl, etc...
