### ISSUE TITLE
Using postgres json functions return bigserial/bigint columns as integer instead of string

### ISSUE THREAD

**Issue by shivam-witbybit** [brianc/node-postgres#2265]
Using postgres json functions like json_agg, json_build_object or to_jsonb() are returning bigserial/bigint fields as a number even though it should be returning them as string because of being INT8.

For example - 

```sql
create table IF NOT EXISTS animals(
  id bigserial primary key,
  body jsonb
);

create table IF NOT EXISTS animal_name(
  id bigserial primary key,
  name text,
  animal_id bigint references animals(id)
);

INSERT INTO animals ("body")
VALUES ('{"Dog": "Golden Retriever"}');

INSERT INTO animal_name ("name", "animal_id")
VALUES ('Shawn', 1);

```

Now when I run the query

```js
pool.query(
  `select a.*, to_jsonb(an.*) as animal_info from animals a left join animal_name an on an.animal_id = a.id`,
  (err, res) => {
    console.log(res.rows);
  }
);
```

I get the result as `[ { id: '1', body: { Dog: 'Golden Retriever' }, animal_info: { id: 1, name: 'Shawn', animal_id: 1 } } ]` Here both id and animal_id are numbers when it should be returned as string. This is also happening with almost all json functions in postgres

My system/software specs: 

- Windows 10 Pro 64 bit
- NodeJS v12.17.0
- postgreSQL version 11
- pg library version 8.2.1

**Comment by sehrope** [comment]
The `json` and `jsonb` datatypes are sent from the server to the client as serialized JSON text. They do not have any type information for the source fields. JavaScript defaults parsing via `JSON.parse(...)` deserializes JSON numbers to JavaScript Number (not BigInt).

If you want to deserialize to other data types (e.g. BigInt or Date), then you'll need to do it yourself.
