### ISSUE TITLE
[pg-query-stream] connection type parsers not applied to streamed rows

### ISSUE THREAD

**Issue by aravindanve** [brianc/node-postgres#2270]
The type overrides configured at the pool or client level are not applied to the rows returned by the stream. However it works if type overrides are explicitly passed to the QueryStream

```js

const typeInt8 = 20;
const types = new TypeOverrides();

types.setTypeParser(typeInt8, value => 'test');

const pool = new pg.Pool({ types });

pool.connect((err, client, release) => {
  client.query('select 1::int8 as num;', (err, result) => {
    console.log('query:', result.rows[0]);
  });

  client
    .query(new QueryStream('select 1::int8 as num;'))
    .pipe(new stream.Transform({
      objectMode: true,
      transform(chunk) {
        console.log('implicit:', chunk);
      }
    }))

  client
    .query(new QueryStream('select 1::int8 as num;', null, { types }))
    .pipe(new stream.Transform({
      objectMode: true,
      transform(chunk) {
        console.log('explicit:', chunk);
      }
    }))
});
```

Outputs
```bash
query: { num: 'test' }
implicit: { num: '1' }
explicit: { num: 'test' }
```

**Comment by aravindanve** [comment]
https://github.com/brianc/node-postgres/blob/f0bf3cda7b05be77e84c067a231bbb9db7c96c39/packages/pg/lib/client.js#L542-L544

This seems to be the problem, adding the following line to the bottom of the PgQueryStream constructor fixes the issue:
```js
class PgQueryStream extends stream.Readable {
  constructor(text, values, config = {}) {
    ...
    this._result = this.cursor._result;
  }
  ...
```

Should I send a PR?

**Comment by brianc** [comment]
Thanks for pointing that out! A PR would be fabulous :heart:

**Comment by aravindanve** [comment]
Done https://github.com/brianc/node-postgres/pull/2271

Also, while writing the test I noticed that `rowMode` is not falling back to client config as well. But the same fix did not work. It appears that the fault may be on `pg` client's end? I am not sure yet, but from a cursory look, it appears that pg client does not pass on `rowMode` configuration to the query at all.
