### ISSUE TITLE
Unhandled rejection error: password authentication failed for user "success computer"

### ISSUE THREAD

**Issue by Ruhulcse** [brianc/node-postgres#2285]
![Untitled](https://user-images.githubusercontent.com/20565147/87825725-7b3e0600-c82c-11ea-8219-9013b971b074.png)

i am getting this error when i am going to connect. as though it is working from psql shell perfectly with same password.

**Comment by charmander** [comment]
How are you creating your configuration? Judging by `POSTGRES_USERNAME=postgres`, “success computer” wasn’t the intended user, so something is going wrong between there and where it becomes the `user` property of the pg options.

**Comment by Ruhulcse** [comment]
> How are you creating your configuration? Judging by `POSTGRES_USERNAME=postgres`, “success computer” wasn’t the intended user, so something is going wrong between there and where it becomes the `user` property of the pg options.

i have set POSTGRES_USERNAME=postgres but why it is showing me my computer user name 'success computer"? where can i find the solution ?

**Comment by charmander** [comment]
pg reads libpq environment variables, like `PGUSER`, as documented at https://node-postgres.com/features/connecting/#environment-variables. If you want to use different environment variable names, you’ll have to create an options object from them to pass to pg – https://node-postgres.com/features/connecting/#programmatic.
