### ISSUE TITLE
issue connection to azure postgress db

### ISSUE THREAD

**Issue by faisalil** [brianc/node-postgres#2288]
I am having an issue connecting to an azure postgress db. the user name for the connection must have an at in azure. 
so faisal@company as an example. 

every time I try to connect, I am getting "[next-auth][error][adapter_connection_error] error: Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format."
I tried to escape via \ and %40 and nothing worked. Any idea?

**Comment by charmander** [comment]
`%40` should work, if using a connection string. Can you show how you’re creating the pg configuration?
