### ISSUE TITLE
big insert with parameters does not supply all parameters required

### ISSUE THREAD

**Issue by mateuszzdyb** [brianc/node-postgres#2292]
Hi. I've recevided this error:
bind message supplies 1274 parameters, but prepared statement "" requires 66810
while doing an insert of 6681 rows, 10 params for each row. 
I've read that there was similar problem with PHP ( https://stackoverflow.com/questions/10794786/pg-query-params-failing-at-24464-parameters-does-it-have-a-cap-php?rq=1 )
from where "The over the wire protocol used by postgres indicates that the number of parameters used is passed as a signed 2 byte integer, which 90000 obviously does not fit into.

It looks like the php driver just ignores what won't fit into the 2 byte integer - 90000 is 0x015f90, if you just take the low 2 bytes of that then you get 0x5f90 which is 24464. Break your insert into smaller batches and you should be ok"

is there any way to make it possible using pg as a single batch? 1274 parameters as a limit is a tiny amount.

**Comment by sehrope** [comment]
You can use arrays of parameters to pass multiple rows worth of data in a single command:

```sql
INSERT INTO foo
(a, b, c)
SELECT
  t.a,
  t.b,
  t.c
FROM UNNEST($1::text[], $2::int[], $3::date[]) t(a,b,c)
```

There's still some overall limitations on the total size of the message packet and anything getting into the 100s of MB should be batched into something more reasonable. But it's much better then the limits for using individual parameters. Makes for more more legible SQL as well v.s. 1000s of `VALUES (...)` clauses.

**Comment by brianc** [comment]
It shouldn't be limiting you to 1274.  There's nothing in `pg`'s code that puts a limit on the number of parameters - postgres itself has a limit of 32k (Int16 max value) - do you have a self-contained reproducible script that shows it can't support more than 1274 parameters?

**Comment by mateuszzdyb** [comment]
here it is:
`//dependencies
const pg=require('pg');
//config
const ds={
    host: 'xxx',
    port: xxx,
    database: 'xxx',
    user: 'xxx',
    password: 'xxx',
    client_encoding: 'utf8',
    max: 20 // use up to 30 connections
    }
//requiring pool
pool_ds=new pg.Pool(ds);


//creating object
var dats=[]
for(i=0;i<7000;++i){
    var data={}
    data.date='date'+i
    data.open='open'+i
    data.high='high'+i
    data.low='low'+i
    data.close='close'+i
    data.adjusted_close='adjusted_close'+i
    data.volume='volume'+i
    data.exchange='exchange'+i
    data.hashed_ticker='hashed_ticker'+i
    dats.push(data)
}
const items={code_ticker:'our_symbol',
            data:dats}


function saveSingleStockAction(singlestock){
    //console.log('in savings',singlestock)
    var symbol=singlestock.code_ticker
    var data=singlestock.data
    //create query
    //var Query='INSERT INTO historicals_parent (code_ticker,date,open,high,low,close,adjusted_close,volume) VALUES'
    var data_l=singlestock.data.length
    var add='';
    //if we have notjhing for a particulr stock
    if(data_l===0){
        //we close the symbol
        console.log('stock',symbol,'has no data whatsoever')
        resolve(symbol)
        return symbol
        }
    var query=`INSERT INTO historical_parent(
        code_ticker, date, open, high, low,
        close, adjusted_close , volume , exchange , hashed_ticker) VALUES
        `
    var add=' '
    let valuesArray=[]
    //iterating over array of values
    for(let a=0;a<data_l;++a){  
        //savind code_ticker
        valuesArray.push(symbol)                                  
        let date=data[a].date||null;
        //if(a===0){console.log('date',date,'or')}
        valuesArray.push(date)
        let open=data[a].open||null;
        valuesArray.push(open)
        let high=data[a].high||null;
        valuesArray.push(high)
        let low=data[a].low||null;
        valuesArray.push(low)
        let close=data[a].close||null;
        valuesArray.push(close)
        let adjusted_close=data[a].adjusted_close||null;
        valuesArray.push(adjusted_close)
        let volume=data[a].volume||null;
        valuesArray.push(volume)
        let exchange=data[a].exchange||null;
        valuesArray.push(exchange)
        //getting hashed_ticker
        let bigint=data[a].hashed_ticker||null;
        valuesArray.push(bigint)
        //creating add 
        var add=add+ `( $`+Number(a*10+1)+` ,$`+Number(a*10+2)+` ,$`+Number(a*10+3)+` ,$`+Number(a*10+4)+ ` ,$`+Number(a*10+5) 
        //             code_ticker,          date,              open,            high,                        low,
        +` ,$`+Number(a*10+6)+` ,$`+Number(a*10+7)+` ,$`+Number(a*10+8)+` ,$`+Number(a*10+9)+` ,$`+Number(a*10+10)+`), `
        //          close,          adjusted_close ,            volume ,        exchange ,          hashed_ticker) 
        }
    //removing last coma
    add=add.substring(0,add.length-2)
    //finishing touch
    var finisher= ' ON CONFLICT ON CONSTRAINT historical_parent_hashed_ticker_date_constraint DO UPDATE SET code_ticker=excluded.code_ticker, date=excluded.date, open=excluded.open, high=excluded.high, low=excluded.low, close=excluded.close, adjusted_close=excluded.adjusted_close, volume=excluded.volume, exchange=excluded.exchange;' 
    const queryf=query+add+finisher;
    //console.log('query',queryf)

    console.log('values',valuesArray)
    // generating a multi-row insert query:
    //executing query
    pool_ds.connect((err,dbs,done)=>{
        if(err){
            console.log('connecting error',err)
            done()
            }
            else{
                dbs.query(queryf,valuesArray,(err,done)=>{
                    if(err){
                        console.log('saving stock historicals error',err)
                        dbs.release()
                        }
                        else{
                            console.log('confirm',symbol)
                            dbs.release()
                            return
                            }
                    })
                }
        })                             
    }

saveSingleStockAction(items)`

**Comment by mateuszzdyb** [comment]
sorry, seems that github uses "`"  symbol for code, which i used in the script as well

**Comment by charmander** [comment]
Like the explanation you originally quoted and @brianc both said, the limit is 32,767 parameters. The value in the error message comes from the way the number actually passed is truncated to 16 bits.

```js
> 66810 & 0x7fff
1274
```

And the answer to your question of how to do it is in @sehrope’s comment :)
