### ISSUE TITLE
password authentication failing for empty password 

### ISSUE THREAD

**Issue by dopey** [brianc/node-postgres#2297]
Recently switched from postgres 10 -> postgres 12.3 (Ubuntu 12.3-1.pgdg20.04+1). 

node-postgres 8.3 (but also was failing with 7.x)

I'm using the default `postgres` user which should have an empty password. For postgres10 I was sending in `{ ... , password: "", ...}`, but with postgres12.3 I get the error: 

```
error: password authentication failed for user "postgres"
    at Parser.parseErrorMessage (/home/travis/build/smallstep/web/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/home/travis/build/smallstep/web/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/home/travis/build/smallstep/web/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/home/travis/build/smallstep/web/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 102,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '330',
  routine: 'auth_failed'
}
```

I've tried setting the password to `undefined`, `null`, and just removing the field all together and nothing works.

I can do `psql -U postgres` from the command line and I am not prompted for a password. 

If I change all local connections to be `trust` (rather than `md5`) in the pg_hba.conf then node-postgres is able to connect. 

What am I doing wrong in my node-postgres client connection?

**Comment by charmander** [comment]
Empty passwords aren’t valid in PostgreSQL; psql is probably authenticating some other way, and the postgres user probably doesn’t have a password. (You can confirm with `SELECT passwd FROM pg_shadow WHERE usename = 'postgres'`.)

Try the socket:

```js
{
    host: '/run/postgresql',
    user: 'postgres',
}
```

**Comment by vitaly-t** [comment]
How you set your password from the client is completely irrelevant.

When you activate no-password authentication on the server, it will automatically ignore any password that the client provides.

**Comment by dopey** [comment]
Yep, this was exactly the case. I think travis creates a user `postgres` with password `<empty string>` by default. The over the socket connections were working (`psql`) because `postgres` was set to `trust` those without password auth. I had to set the password for the `postgres` user and then was able to connect with clients over localhost.
