### ISSUE TITLE
Why not KISS for transactions?

### ISSUE THREAD

**Issue by mustafamunawar** [brianc/node-postgres#2298]
I believe the transactions docs are **complicated**: https://node-postgres.com/features/transactions
Why not just use multple statments in a single query. e.g. 

`pool.query('begin; insert1; insert2; insert3; delete1; update1; commit;')`

_Note: the begin and commit statements are optional. In a multi-statement query, they will automatically be added, per Postgres docs. see also https://github.com/brianc/node-postgres/issues/1717_

This has a few distinct benefits:

- can use pool.query()
- much simpler to write
- single trip to server (performance)

Why would I want to use the complicated method found in the docs page? The only reason I can think of is to know which individual statement had an error. I believe in most use cases, one just cares if a transaction succeeded or not. 

Maybe I'm missing something fundamental. But if the above method is viable, I believe it should be mentioned clearly in the docs.

**Comment by charmander** [comment]
Multi-statement queries can’t be parameterized, and queries often need to use parameters.

**Comment by mustafamunawar** [comment]
Thanks for the reply.

Are parameterized queries the primary reason for not using the simplified approach? In that case, do parameterized queries have any benefit besides SQL injection performance? Are there any performance benefits? 

If SQL injection is the only concern, then a small convenience function can solve this, such as that found at https://github.com/datalanche/node-pg-format. The above query would then take the form:

var query=format('begin; insert1; insert2; insert3; delete1; update1; commit;', param1, param2, param3) 
pool.query(query)

**Comment by charmander** [comment]
> Are parameterized queries the primary reason for not using the simplified approach? In that case, do parameterized queries have any benefit besides SQL injection prevention? Are there any performance benefits?

They might be a significant a user of the library wouldn’t run a whole transaction in a single query call, sure. Yes, parameterized queries offer performance benefits – in particular, when the parameters use their binary serialization (e.g. bytea, which has to be converted to hex if you want to put it in query text). Parsing them is also faster and cacheable, and they can be prepared ahead of time for typechecking.

Remember, you can wrap the transaction logic in a reusable function, and that’s already built into some libraries ([pg API wrappers](https://github.com/brianc/node-postgres/wiki/Extras#api-wrappers), [query builders](https://knexjs.org/#Transactions)).

**Comment by mustafamunawar** [comment]
Thanks. Certainly, passing BYTEA is a good use case. 

You mention: _Parsing them is also faster and cacheable, and they can be prepared_
Is this true? I believe that an unnamed prepared statement is created. I believe this may actually be less peformant, since it is recreated/discarded for every query. From the Postgre docs:

> “unnamed” prepared statement and portal exist. Although these behave largely the same as named objects, operations on them are optimized for the case of executing a query only once and then discarding it, whereas operations on named objects are optimized on the expectation of multiple uses.

Even if named prepared statements are used, for most queries will not benefit greatly: From the Node Postgres docs:

> Most of your queries will likely not benefit much, if at all, from using prepared statements

I thus believe for most use cases, the approach I outlined is significantly better. It is much easier--just a single statement without worrying about manually issuing a begin/end. This also makes it less error-prone. And it is actually more performant, since a single trip to the server is needed.

**Comment by mustafamunawar** [comment]
So, finally what I am asking is that the docs be updated. A small blurb on the "easy" way to do transactions would be of great to users of this library. Is this possible?

**Comment by brianc** [comment]
A super common pattern for transactions is not just to do a series of related insert statements with known parameters ahead of time, it's to do queries which depend on the output from one another.  There is no way to simplify this really.  Plenty of libraries offer a simpler interface for running transactions _on top of_ pg.  The docs are open source too so feel free to contribute if you have any ideas on how to improve them! ❤️
