### ISSUE TITLE
Dynamic authentication info

### ISSUE THREAD

**Issue by pauldraper** [brianc/node-postgres#2301]
[AWS IAM Authentication](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.html) uses AWS IAM permissioning to generate a temporary (15 minute) password when connecting to the database.

Ideally, there would be a way to have a credentials provider that generated the credentials for each physical connection.

```js
const pool = new Pool({
  user: 'dbuser',
  host: 'database.server.com',
  database: 'mydb',
  port: 3211,
  async dynamic(config) {
    const password = ''; // retrieve and cache password
    return { ...config, password };
  }
});
```

**Comment by sehrope** [comment]
@pauldraper There is :smile: https://github.com/brianc/node-postgres/pull/1926
