### ISSUE TITLE
Question: what is the recommended module for named parameters

### ISSUE THREAD

**Issue by agorina** [brianc/node-postgres#2312]
I see multiple options but they are either come with some highly-opinionated wrappers on top of the core API, or seem lacking support and outdated. Do you have any library to recommend?

**Comment by brianc** [comment]
I typically use `pg` and `sql-template-strings` for named parameter support.

```js
const sql = require('sql-template-strings')
const pg = require('pg')

const pool = new pg.Pool();
const { rows } = pool.query(sql`
  SELECT * FROM users WHERE name = ${name}
`);
```

There's very little magic involved and you remain in full control of your sql.  But...there are a bunch of other options - I just have used them; probably plenty are great.

**Comment by vitaly-t** [comment]
@agorina Have you looked at [pg-promise](https://github.com/vitaly-t/pg-promise)? It has extensive support for [named parameters](https://github.com/vitaly-t/pg-promise#named-parameters).

**Comment by charmander** [comment]
Seconding @brianc’s recommendation for template-string-based solutions. Actual named parameters are a bad idea, because the library implementing them can’t know the context they’re being used in in the query without including an SQL parser (I don’t think any do), and risk making a bad substitution because of it.

**Comment by vitaly-t** [comment]
> Actual named parameters are a bad idea, because the library implementing them can’t know the context they’re being used in in the query without including an SQL parser (I don’t think any do), and risk making a bad substitution because of it.

The only concern  - SQL injection is catered for through escaping all values correctly. The context by itself does not pose any real threat. Named parameters create necessary flexibility that are not allowed by the server itself.

**example:**

```sql
SELECT ${table} WHERE ${col} = ${value}
```

- something you cannot do with the server's own parameters, but is essential to many database designs.

```

**Comment by charmander** [comment]
> The only concern - SQL injection is catered for by escaping all values correctly.

That’s not the only concern; silently doing the wrong thing is also a concern. It’s impossible to escape values correctly when you don’t know the context in which they appear.

> **example:**
>
> ```sql
> SELECT * FROM ${table} WHERE ${col} = ${value}
> ```

From a skim of the readme, it looks like that’s not quite the syntax that would be used. You can implement the same thing with template strings, though.

**Comment by vitaly-t** [comment]
> It’s impossible to escape values correctly when you don’t know the context in which they appear.

Well, in case of [pg-promise](https://github.com/vitaly-t/pg-promise), for example, the context is present for the most part, through [Formatting Filters](https://github.com/vitaly-t/pg-promise#formatting-filters)

For example, if you have the following input:

```js
const input = {
    table: 'my-table',
    columns: ['first', 'second', 'third'],
    condition: {
        col1: 'first',
        value: 123
    }   
};
```

the formatting engine lets you write it like this:

```sql
SELECT ${columns:name} FROM ${table} WHERE ${condition.col1} = ${condition.value}
```

which gives a very nice readable context, and the extra protection that you mentioned.

**Comment by charmander** [comment]
The risk is the special syntax being introduced unintentionally, e.g. by a different special-purpose query formatter or just by mistake. Maybe your library is intended to never be used with a query formatted by a different library, and you classify parameters introduced in the wrong place as another one of those mistakes users have to watch out for; it’s just an approach I don’t recommend, because I think it introduces needless potential for type confusion and has no advantages over tagged templates.

**Comment by vitaly-t** [comment]
>  has no advantages over tagged templates

It has plenty, starting as the essential tool for simple generating of multi-row insert and update queries, something you cannot do with tagged templates. [Usage example](https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise).

**Comment by charmander** [comment]
You can do that with tagged templates (or better approaches entirely). I don’t really want to make a long(er) thread about it, though.

**Comment by agorina** [comment]
To answer the question addressed to me above: yes, I have looked at this library and a few more mentioned on this thread: https://github.com/brianc/node-postgres/issues/268. Thanks for the input.
