### ISSUE TITLE
 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by paul-thomas0** [brianc/node-postgres#2314]
Issue type:

[x] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[x] postgres
[ ] cockroachdb
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

TypeORM version:

[ ] latest
[ ] @next
[ *] 0.2.17 (or put your version here)

Steps to reproduce or a small repository showing the problem:

RangeError: Maximum call stack size exceeded at DerivedLogger. [as verbose] (d:\exp_workspace\neutrinos-srm\server\node_modules\winston\lib\winston\create-logger.js:95:19) at LoggerTypeorm.logQuery (d:\exp_workspace\neutrinos-srm\server\build\utils\ndefault-sql\ExecuteSql\LoggerTypeorm.js:9:21) at PostgresQueryRunner. (d:\exp_workspace\neutrinos-srm\server\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:165:55) at step (d:\exp_workspace\neutrinos-srm\server\node_modules\tslib\tslib.js:141:27) at Object.next (d:\exp_workspace\neutrinos-srm\server\node_modules\tslib\tslib.js:122:57) at fulfilled (d:\exp_workspace\neutrinos-srm\server\node_modules\tslib\tslib.js:112:62) at processTicksAndRejections (internal/process/task_queues.js:93:5)

I am trying a INSERT for more than 10,000 records. It works fine when record set is <=5000.

**Comment by charmander** [comment]
If you can reproduce this using only pg, please add that information here. Otherwise, closing for typeorm/typeorm#6589.

**Comment by MrIzzat** [comment]
Has anyone been able to figure this out?
