### ISSUE TITLE
How to get the actual SQL string of a client.query that contains parameters?

### ISSUE THREAD

**Issue by kovkev** [brianc/node-postgres#2325]
Say we have:

```
client.query('SELECT $1', [2]).then(res => {})
```

How can we get the *actual* SQL sent to postgres? There must be a way to get the string `SELECT 2` somehow.

Thank you!

kovkev

**Comment by abenhamdine** [comment]
IIRC you can't, because in a parameterized query, parameters are subsituted by the posgres server, not by the client.

**Comment by charmander** [comment]
Yep! That is the actual SQL sent to Postgres.

**Comment by kovkev** [comment]
Is there a way to get the postgres server to return to the client what the actual query was?

**Comment by abenhamdine** [comment]
> Is there a way to get the postgres server to return to the client what the actual query was?

you need to log queries on the server (perhaps with a specific pg extension, I don't remember exactly)
