### ISSUE TITLE
nodej 12/10 pg native Segmentation Fault, node 8 fine

### ISSUE THREAD

**Issue by aarontract** [brianc/node-postgres#2332]
Im working on a web app hosted on AWS as an elastic beanstalk instance, node is crashing after calling pool.connect.
It was working fine under nodejs v8, but after updating from 8(8.17.0) to 12(12.18.3) or 10 it was crashing as soon as pool.connect was called.

I am running pg 8.3.3, pg-native 3.0.0.

I'm adding postgresql96-devel.x86_64 as the PostgreSQL client library on the instances.  This is the latest version that is available to yum.  

After doing a bit of debugging I can see this error just after .connect is called:
kernel: [   84.296607] node[3943]: segfault at 3f0 ip 00007f836cc04c3b sp 00007f83557fd0a0 error 4 in libssl.so.1.0.2k[7f836cbdc000+66000]

Could OpenSSL be an issue?

This is how I'm calling connect:

```
const {Pool} = require('pg').native;
const _connString = process.env.APP_DB_CONN_STRING;
const pool = new Pool({
  connectionString: _connString,
})
pool.connect( function(err, client, done) {..
```

If i remove .native it runs, or if i roll back to nodejs v8 it also runs.  

Anybody got any tips?

**Comment by aarontract** [comment]
On nodejs 12.18.3 to 12.18.0 and 12.16.3 
 ./node -pe process.versions shows `openssl: '1.1.1g'`

But node 12.16.2 has `openssl: '1.1.1e'`, I switched it back to this version of nodejs and its now working again.

**Comment by aarontract** [comment]
I thought I had fixed this but it looks like AWS had rolled back to nodejs v8 without reporting it.  I rebuild the environment and i started seeing the segfault again after pool.connect() was run. 

It seems like it is related the the version of opensssl version in node, 
I can get nodejs 8.17/10.14.1 to run that uses opens ssl 1.1.0{x}, all later versions are on 1.1.1{x} and i see the error.

This is from running # node -pe process.versions

I have tried quite a few different versions of PG, 7 to 8.3.3, I am logging it out using logger.info('PG VERSION', require('pg/package.json').version);

Again anybody got any tips or things to try next?

**Comment by charmander** [comment]
Yes, OpenSSL is the issue. I recommend using the JavaScript driver (with the most recent Node available to you). To get the native driver working, you’d have to recompile libpq.

**Comment by aarontract** [comment]
Thanks, @charmander, by "using JavaScript driver", do you mean not using .native version?

**Comment by charmander** [comment]
Right!

**Comment by aarontract** [comment]
Thanks again @charmander 
I have noticed that the system (AWS Elastic Beanstalk instance) has openssl 1.1.0, is that going to be part of the issue that it doesnt match the nodejs version when node-gyp goes to compile?

I have seen a note on node-libpq page
`Note: for Node.js equal or greater to version 10.16.0 you need to have at least OpenSSL 1.1.1 installed.`
