### ISSUE TITLE
Query without connect

### ISSUE THREAD

**Issue by christopheSeeka** [brianc/node-postgres#2334]
Hello, im a bit confuse, i'm using the following:

```
const { Pool } = require("pg");
const pool = new Pool({ user: etc... })
pool.query(`insert into config values ($1) `, ["xxxx"], (err, result) => {
            if (err) {
              console.log(err);
            } else {
              console.log("Updated config table lastindex to: " + response.data[0].value);
            }
            initSync(response.data[0].value);
          });
```

It all work but at no point i do any pool.connect or so, is it automatique? we don't needs use connect/end?

Thanks in advance

**Comment by sehrope** [comment]
Yes it's automatic.

The `pool.connect(...)` function checks out a connection from the pool. If none exists then it may create a new one or wait for an existing one to be returned (depends on the pool size). You also have to return the connection to the pool via `client.release(...)`.

The `pool.query(...)` function is a helpful wrapper to check out a connection (via `pool.connect(...)`), execute a single command, and then return the connection to the pool. It's convenient so you do not have to remember to return the connection.

If you do not have a use case to re-use the same connection then it's recommended to use `pool.query(...)`.

**Comment by christopheSeeka** [comment]
Thanks for the infos.
