### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yokkkoso** [brianc/node-postgres#2335]
When I try to `npm i pg` I get this error:
`npm ERR! Unexpected end of JSON input while parsing near '...ATURE-----\r\n"},"eng'`

Node version: 12.18.3

**Comment by charmander** [comment]
This is an npm error, and probably not related to how pg is packaged. Try running the command again, maybe with `npm cache verify` first. Make sure your npm is up to date.

**Comment by yokkkoso** [comment]
> This is an npm error, and probably not related to how pg is packaged. Try running the command again, maybe with `npm cache verify` first. Make sure your npm is up to date.

This work! Thx =d
