### ISSUE TITLE
DatabaseError class should be public

### ISSUE THREAD

**Issue by garaboncias** [brianc/node-postgres#2340]
We need to handle Database errors in higher level, and we wan't to check if error come from db, and in that case error code is a specific code. Please export DatabaseError class from `node-postgres` to able to achieve that.

```typescript
// Current workaround but its hacky.
import { DatabaseError } from 'pg-protocol/dist/messages';

/** https://www.postgresql.org/docs/current/errcodes-appendix.html */
enum postgresErrorCodes {
    read_only_sql_transaction = '25006'
}

   if (error instanceof DatabaseError && error.code == postgresErrorCodes.read_only_sql_transaction) {
      // handle write modification tries
   }
```

**Comment by tcarrio** [comment]
@garaboncias just a heads up, the fix for this was just merged. Keep an eye out for the next release 😁

**Comment by brianc** [comment]
Release went out! pg@8.4.0

**Comment by tcarrio** [comment]
Crazy fast @brianc . Thanks for updating us here too ❤️

**Comment by garaboncias** [comment]
Thank you for your support and kindness!
