### ISSUE TITLE
Changes in 8.0?

### ISSUE THREAD

**Issue by djmitche** [brianc/node-postgres#2342]
I see a nice summary of what changes when upgrading to 7.0, but nothing about 8.0.  #2047 has some discussion of what might or might not go into that release, but I don't see any indication there or elsewhere about what the breaking changes are.  Are there any, aside form node versions?  If so, could a new section of the docs describe those changes?

**Comment by eschwartz** [comment]
Here's what I'm seeing:
https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#pg800
https://node-postgres.com/announcements#2020-02-25

That second link includes descriptions of a number of breaking changes.

**Comment by djmitche** [comment]
Ah, thanks!

Perhaps an "Upgrading to 8.0" section pointing to the second link?  I don't see a repo for the node-postgres.com site, but I'd be happy to make a PR for it.

**Comment by sehrope** [comment]
@djmitche The website is this repo: https://github.com/brianc/node-postgres-docs

**Comment by djmitche** [comment]
Ah, thanks!
