### ISSUE TITLE
TypeError: this.Client is not a constructor

### ISSUE THREAD

**Issue by jefmenegazzo** [brianc/node-postgres#2349]
When using version 8 of the pg (with version 7 the problem does not happen), there is a problem in the execution with the code compiled for production via webpack. Running the project compiled by the webpack in a bundle.js with all dependencies, the following error occurs:

`Unable to connect to the database (database_name). Retrying (1)... -> (TypeError: this.Client is not a constructor`

Strangely, this happens when I have more than two connection pools with databases. Analyzing the pg code, I found in `./index` the following code:

```javascript
var PG = function (clientConstructor) {
  this.defaults = defaults
  this.Client = clientConstructor
  this.Query = this.Client.Query
  this.Pool = poolFactory(this.Client)
  this._pools = []
  this.Connection = Connection
  this.types = require('pg-types')
}

if (typeof process.env.NODE_PG_FORCE_NATIVE !== 'undefined') {
  module.exports = new PG(require('./native'))
} else {
  module.exports = new PG(Client)

  // lazy require native module...the native module may not have installed
  Object.defineProperty(module.exports, 'native', {
    configurable: true,
    enumerable: false,
    get() {
      var native = null
      try {
        native = new PG(require('./native'))
      } catch (err) {
        if (err.code !== 'MODULE_NOT_FOUND') {
          throw err
        }
        /* eslint-disable no-console */
        console.error(err.message)
        /* eslint-enable no-console */
      }

      // overwrite module.exports.native so that getter is never called again
      Object.defineProperty(module.exports, 'native', {
        value: native,
      })

      return native
    },
  })
}

```

For some reason, the code `new PG (require ('./ native'))` when compiled for production returns an empty object `{}` instead of the client function. I solved this problem by adding `.default` to the requires:

```javascript
module.exports = new PG(require('./native').default)

native = new PG(require('./native').default)
```

 I believe it is interesting to incorporate for the next version.

**Comment by charmander** [comment]
Mismatches in the behaviour of `require` between Node and Webpack are Webpack configuration issues.
