### ISSUE TITLE
TypeError: con.connect is not a function when calling Client.connect()

### ISSUE THREAD

**Issue by ShayD16** [brianc/node-postgres#2354]
```
import dbConfig from '../dbConfig';
const { Client } = require('pg');
module.exports = {
  query: async (text, params) => {
    const client = new Client(dbConfig);
    await client.connect();
    const res = await client.query(text, params);
    console.log(res)
  }
};
```

DB Config is:
```
{
  port: process.env.DB_PORT,
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  connectionTimeoutMillis:5000
}
```
Constantly prints `TypeError: con.connect is not a function`

I tried with several different databases, both local and hosted(I can connect to them through DBeaver) and all of the are giving me the same issue. Is it something wrong with my code?

**Comment by vitaly-t** [comment]
You do not even have `con.connect` anywhere in your code example, which suggests the error happens elsewhere.

**Comment by charmander** [comment]
This can happen if you pass a `connection` option that isn’t a connection. Does `dbConfig` definitely not contain a property named `connection`?

**Comment by ShayD16** [comment]
@charmander 
This is the body of dbConfig
```
{
  port: process.env.DB_PORT,
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  connectionTimeoutMillis:5000
}
```
Verified with stringified console log.

@vitaly-t con.connect is called in the library, I am sorry I didn't paste the full log output at the moment.

I suspect this was caused by a syntax issue in my code and not an issue with the library, wanted to see if anyone else faced this issue.

**Comment by brunolnetto** [comment]
@ShayD16 How did you solve this issue? I have the precise same annoying error.

**Comment by ShayD16** [comment]
If I recall correctly this was a node version issue. Node version 12 worked, not 14.
Needed a pg lib upgrade to work with node 14.
If this doesn't work let me know I'll revisit the details

**Comment by brunolnetto** [comment]
Warm compliments. I write a NodeJS app boilerplate. In case you are willing to further help, it is on repository https://github.com/web-needle/sappio

**Comment by AbdulHussain1** [comment]
@ShayD16 I am facing the same issue while connecting with PG, the con.connect() error is showing in the pg/lib/client.js file. What pg version did you use in your project . I am using Node 16.13.0 and PG 8.0.0

**Comment by ShayD16** [comment]
@AbdulHussain1 `"pg": "^8.7.1",`
