### ISSUE TITLE
TypeError: Class constructor Client cannot be invoked without 'new'

### ISSUE THREAD

**Issue by hansnull** [brianc/node-postgres#2356]
Hi,

appmetrics is not happy with changes made from 8.3.0 to 8.3.2:
```
TypeError: Class constructor Client cannot be invoked without 'new'
    at new newFunc (node_modules\appmetrics\lib\aspect.js:101:26)
    at E:\qlikwrite_server\node_modules\knex\lib\dialects\postgres\index.js:111:26
    at new WrappedPromise (node_modules\async-listener\es6-wrapped-promise.js:13:18)
    at Client_PG.acquireRawConnection (node_modules\knex\lib\dialects\postgres\index.js:110:12)
    at create (node_modules\knex\lib\client.js:291:39)
```
I cannot identify the root cause, but with 8.3.0 it is working fine. Any help appriciated.

**Comment by Miladiir** [comment]
Sorry to bother, but is there any update on this? I am seeing the same error on pg@8.5

**Comment by charmander** [comment]
`pg/lib/client`’s `Client` became a class in 8.3.2. I’m not sure if that should have been considered a breaking change, but it’s not going to change back, so whatever attaches appmetrics to its constructor is going to need to use a class-compatible approach.

**Comment by charmander** [comment]
> whatever attaches appmetrics to its constructor

Oh, that’s appmetrics itself: https://github.com/RuntimeTools/appmetrics/blob/4862e6882e85b63ea22c55cb4b273f17ef4820cb/probes/postgres-probe.js#L62-L71

This code hasn’t been updated since June 21st, 2017. It doesn’t look like it supports pg-pool or promises.
