### ISSUE TITLE
Parameter for WHERE clause removes first character

### ISSUE THREAD

**Issue by NickParks** [brianc/node-postgres#2357]
Hello,

I'm fairly new to Postgres & node pg. I'm running into an issue with an `WHERE` clause right now where I have this id:
`3hu4e2n9ksk`. 

I need to do a query like so: `SELECT * FROM users WHERE id = $1`. Running this query gives me this error:
```
error: syntax error at or near "hu4e2n9ksk"
```

It's removing the first character `3` from the string, I assume because node pg is thinking it's an int? I'm honestly not sure. I've tried researching how to force the search parameter to be parsed as a string using `$1::text` but that didn't work. Some research into `pg.types` didn't get me very far either.

Any help with this would be great, thank you!

**Comment by boromisp** [comment]
It looks like you aren't using prepared statement or a standard query formatting library, because you are executing this query, where the string is not quoted:

```sql
SELECT * FROM users WHERE id = 3hu4e2n9ksk;
```

You should either use prepared statements and/or a query building library:

```js
const id = '3hu4e2n9ksk';

// Prepared statement
pool.query('SELECT * FROM users WHERE id = $1', [id]);

// Prepared statement with friendlier syntax 
const sql = require('sql-template-strings');

pool.query(sql`SELECT * FROM users WHERE id = ${id}`);

// Building query string with substituted parameters
const format = require('pg-format');

pool.query(format('SELECT * FROM users WHERE id = %L', id));
```

**Comment by NickParks** [comment]
Sorry, I should've clarified. I am using prepared statements. Like the following:

```
let userId = '3hu4e2n9ksk';
pool.query('SELECT name FROM users WHERE id = $1', [userId]);
```

This still removes the `3` in the query.

**Comment by charmander** [comment]
Is the type of `users.id` `int`?

**Comment by NickParks** [comment]
`user.id` is a currently of type `varchar` in our DB.

**Comment by charmander** [comment]
Can you create a self-contained script that reproduces the error and post the whole thing, including versions of Node, pg, and PostgreSQL? It’ll narrow down the possibilities a lot, like `pool` not being a `pg.Pool` instance, pure JS vs. native driver, and differences compared to the actual code.

The complete error object, with properties like the stack trace and `where`, will also help.

**Comment by NickParks** [comment]
Well, great news. I went to go strip out the code to paste it here, then I saw that this project was using an extremely old version of our Database wrapper that handles error reporting/logging/etc. Updating that to our newest fixed the issue.

It was not actually passing the `values` parameter properly to the pool query.

So sorry for the confusion here, should've covered all my bases first.
