### ISSUE TITLE
pg-protocol support for Postgres Server v13

### ISSUE THREAD

**Issue by mightypenguin** [brianc/node-postgres#2361]
Currently I get a "key" type error with typescript.
Changing to Postgresql v12 fixes the problem.

CENTOS 8
Installed from PGDG (main postgresql repo)
x86_64

**Comment by brianc** [comment]
hmmm that's not good - do you have any code to reproduce this or more details?  What's the `key` type error?  Also, I don't think typescript should have anything to do w/ the error if its a postgres thing. I can set up postgres 13 locally & start developing against it and add it to the CI matrix.  I just ran the test suite against it and everything worked fine on my end, so might be an issue w/ your code.

**Comment by brianc** [comment]
what code is triggering this error? Looks like a SASL connection routine issue...we do have test coverage for that, but we haven't added postgres 13 to the matrix yet.

**Comment by mightypenguin** [comment]
As always, this was my bad.
It turns out I was not specifying the PGPASSWORD environment variable.
So this was a credentials issue that was cleverly hidden by an obtuse error message.
Once I specified the correct PGPASSWORD environment variable the error went away.
Thanks for working with me on this. Now I can use PG13!

For references here's my test program:
`const knex = require('knex');

const CONFIG_INFO = {
    client: 'pg',
    connection: {
        host:'127.0.0.1',
        user:'postgres',
        database: 'postgres'
        //password: process.env.PGPASSWORD
        //get password from PGPASSWORD or other method
    },
};

async function main()
{
    const db = knex(CONFIG_INFO);
    await db.raw(`SELECT 'teststring';`);
    console.log('SUCCESS');
    process.exit(0);
}

main();
`

**Comment by brianc** [comment]
Glad you got it sorted out!
