### ISSUE TITLE
SSL connection - is there a way to provide certificates not with .pem format

### ISSUE THREAD

**Issue by TomRed97** [brianc/node-postgres#2370]
Hello. I want to connect to DB with SSL. In documentation, I see one method only -
ssl {
      ca: fs.readFileSync(clientCert).toString(),
      cert: fs.readFileSync(clientCert).toString(),
      key: fs.readFileSync(clientKey).toString(),
}

But the problem is that my certificates' format is not .pem
I have .cert and .pk8

And I try to provide SSL in connectionString like that
connectionString: `postgresql://${connection.user}:${connection.password}@${connection.host}:${connection.port}/${connection.database}?ssl=true&sslcert=${clientCert}&sslkey=${clientKey}&sslrootcert=${clientCert}`,

But it doesn't work
So my question - is there a way to implement SSL connection with not .pem format or provide JDBC properties

**Comment by brianc** [comment]
The `ssl` config is forwarded unmodified directly to node's [`tls.connect`](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) function - anything that function supports is supported here.  Anything it  _doesn't_ support is out of scope of this library (I try to keep as much magic out as possible) & could probably be handled by another npm module you run your certs through before passing them to the config for node-postgres.

**Comment by TomRed97** [comment]
Thank you and one more question can we pass some options to the JDBC driver itself? or it is impossible and the only way to use another library for SSL connection with crt and pk8 files.

**Comment by charmander** [comment]
There is no JDBC (Java, essentially) driver involved – only a pure JavaScript one or a libpq one. Which options were you hoping to add?

**Comment by TomRed97** [comment]
ssl=true&sslcert=postgres.crt&sslkey=postgres.pk8&sslrootcert=postgres.crt 
thiese options are used in connection url like
jdbc:postgresql://${host}:${port}/${database}?ssl=true&sslcert=postgres.crt&sslkey=postgres.pk8&sslrootcert=postgres.crt 

But ok, thank you, if this lib doesn't use JDBC driver under the hood I have no questions.
I will try to do something.
Thank you.
