### ISSUE TITLE
All results from SELECT query have the same ID!?!? 

### ISSUE THREAD

**Issue by KemikalGeneral** [brianc/node-postgres#2377]
Hi!

Hope you can help.

I'm running a SELECT query with a couple of joins, all of the data is correct but all of the rows are returned with the same ID. 

These are the queries I've tried:

---

This runs fine and returns the expected results, but obviously isn't joining any tables:
```
router.get("/", async (req, res) => {
    try {

        const getAllTasks = await db.query("SELECT * FROM tasks");

        res.json(getAllTasks.rows);

    } catch (e) {
        console.log(e.message);
    }
});
```

---

This returns the correct data, but all the rows have the same ID:
```
router.get("/", async (req, res) => {
    try {

        const getAllTasks = await db.query("" +
            "SELECT * FROM tasks " +
            "join rooms on rooms.id = tasks.room_id " +
            "join room_groups on room_groups.id = rooms.room_group_id " +
            "join sectors on sectors.id = room_groups.sector_id");

        res.json(getAllTasks.rows);

    } catch (e) {
        console.log(e.message);
    }
});
```

---

I thought it might be because I wasn't declaring the columns, so I tried this, but it's the same as above (correct data, wrong row ID's):
```
router.get("/", async (req, res) => {
    try {

        const getAllTasks = await db.query("" +
            "SELECT " +
            "tasks.id, " +
            "tasks.task_name, " +
            "tasks.duration, " +
            "rooms.id, " +
            "rooms.room_name, " +
            "room_groups.id, " +
            "room_groups.group_name, " +
            "sectors.id, " +
            "sectors.sector_name, " +
            "sectors.price_per_hour_weekday, " +
            "sectors.price_per_hour_weekend " +
            "FROM tasks " +
            "join rooms on rooms.id = tasks.room_id " +
            "join room_groups on room_groups.id = rooms.room_group_id " +
            "join sectors on sectors.id = room_groups.sector_id");

        res.json(getAllTasks.rows);

    } catch (e) {
        console.log(e.message);
    }
});
```

---
Just to add to matters, if I run any of these queries from the command line, all the row ID's are correct.

Hopefully I've just missed something, but I can't see what.

Any help would be greatly appreciated,

Many thanks =)

- Node v12.17.0
- NPM v6.2.0
- Postgres v10.4
- PG v8.3.3

**Comment by brianc** [comment]
You're joining 3 tables, each with an `id` field.  `pg` tries to map the column names to an object. In the event of a column name collision it doesn't know what to do.  Try something like this:

```
SELECT task.id as "taskId", room.id as "roomId"
```

etc - then the names will map into the object without collision.  You could also try

```
client.query({  text: 'SELECT * ....', rowMode: 'array' })
```
to return an array of fields and map it into an object however you'd like

**Comment by KemikalGeneral** [comment]
@brianc 

WOW... thank you so much! 

I very rarely even get a reply when I ask (on other packages), let alone a definitive answer that works =)

Thank you very much, all the best
