### ISSUE TITLE
pg issues with Windows 10

### ISSUE THREAD

**Issue by nabeelnv** [brianc/node-postgres#2388]
Successfully able to connect node js with PostgreSQL using pg in windows7. Same code is not getting connected to the postgres on windows10. No error or success messages. Any known issues of pg with Windows 10?

I am using pool and the code is not entering in to the **pool.query** block at all. Looks like its skipping it and not connecting to db. Usually pool.query will error out even if the password is incorrect  or any other error etc. But here, no error log or anything. 

Is there any way to find out if its trying to connect to db?

**Comment by brianc** [comment]
I don't know of any issues related to windows. Are you using the native driver or pure js?

**Comment by nabeelnv** [comment]
I am using pure js. The same connection is working fine in windows7. Installation of pg (npm install pg) success without any error/warning. Still no response from the code, skipping **pool.query** all the time

**Comment by Subuday** [comment]
The same problem!

**Comment by charmander** [comment]
Which versions of pg and Node.js are you using?

**Comment by Subuday** [comment]
Yes, the problem was when I used the pg 7.14 version and Node.js 14. The solution is to use the newest version of pg.

**Comment by brianc** [comment]
Yeah - you need to use pg>=8.0 for node.js 14.  I need to go back and do a patch version on the pg@7.x branch line and add an 'engines' entry to the package.json there.
