### ISSUE TITLE
how to pass table record type into function

### ISSUE THREAD

**Issue by pankleks** [brianc/node-postgres#2391]
Hello,

I have a function which gets record type as an input, as such.
I'm trying to execute it with $1 parameter passed as object of key/value:

```
{
column1: 123,
column2: "abc"
}
```

but during execution I got postgres exception `malformed record literal ...`

How I should pass such parameters? Thank you!

**Comment by boromisp** [comment]
Passing the individual values like `SELECT some_function(($1, $2)::record)` should work.

**Comment by pankleks** [comment]
thank you
