### ISSUE TITLE
Support a password function for the client configuration

### ISSUE THREAD

**Issue by benkeil** [brianc/node-postgres#2396]
If you use e.g. AWS Aurora Postgres with IAM authentication it is hard to deal with it in the code.

It would be nice that I can use a function to return the password, like this:

```typescript
const signer: RDS.Signer = ...
const params: RDS.Signer.SignerOptions = ...

return new pg.Pool({
  max: 1,
  host: databaseConnection.clusterEndpoint,
  port: databaseConnection.port,
  database: databaseConnection.database,
  user: databaseConnection.username,
  password: async () => signer.getAuthToken(params),
  ssl: true,
});
```

**Comment by sehrope** [comment]
You can do exactly that. This was added in #1926.

Check your pg version as you may be on an older version that does not support that feature. It was added [v7.12.0](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#7120).

**Comment by benkeil** [comment]
Then the types are still wrong...

```
// Type definitions for pg 7.14
...
export interface ClientConfig {
    user?: string;
    database?: string;
    password?: string;
    port?: number;
    host?: string;
    connectionString?: string;
    keepAlive?: boolean;
    stream?: stream.Duplex;
    statement_timeout?: false | number;
    parseInputDatesAsUTC?: boolean;
    ssl?: boolean | ConnectionOptions;
    query_timeout?: number;
    keepAliveInitialDelayMillis?: number;
    idle_in_transaction_session_timeout?: number;
    application_name?: string;
    connectionTimeoutMillis?: number;
}
```

**Comment by vitaly-t** [comment]
Oh yeah, you betcha! They have always been wrong, that's why I had to write [my own declaration for this library](https://github.com/vitaly-t/pg-promise/blob/master/typescript/pg-subset.d.ts), one that I could update properly, in a timely manner (it is only a sub-set that I need).

**Comment by mikicho** [comment]
Hey,
I'm trying to connect to Postgres Aurora with IAM Authentication same as @benkeil and it seems like my password function never get called and I get:
```
error: pg_hba.conf rejects connection for host "my-ip", user "db_user", database "db_name", SSL off
```
I'm using `pg` 8.5.1.

**Comment by sehrope** [comment]
@mikicho HBA (Host Base Access control) rules get applied by the server before requesting client authentication. So if your connection is rejected for HBA reasons then it will not invoke your client side password function. Check the pg_hba.conf file of your server and ensure that it has an entry allowing you to connect from the machine where you client is running.

**Comment by mikicho** [comment]
@sehrope Thanks. I succeed to connect to the DB with the token via `psql`.
Isn't it mean that my machine is allowed to connect to the database?

**Comment by sehrope** [comment]
Make sure to enable SSL in your pg client config. RDS does not let you connect with auth tokens over plaintext connections. That's the "`... SSL off`" part that error message.

It works from psql because psql defaults to trying with SSL first.

**Comment by mikicho** [comment]
@sehrope Thanks.
I set `ssl: true` and now I get:
```
Error: unable to get local issuer certificate
```

Is `psql` use some default certificate?
(I'm running in a docker container)

**Comment by sehrope** [comment]
psql defaults to enabling SSL but not checking the server's certificate: https://www.postgresql.org/docs/current/libpq-ssl.html ("prefer" mode)

This driver was changed a few versions back to be more secure by default so the default is to reject untrusted certificates. To mimic the "prefer" behavior, set the `rejectUnauthorized` to true. Or, even better, specify the CA certificates for your database so the server's certificate is validated.

**Comment by mikicho** [comment]
> set the rejectUnauthorized to true

I guess you mean `false` (it's working! thanks!)
