### ISSUE TITLE
Version 8 and async_hooks

### ISSUE THREAD

**Issue by lroal** [brianc/node-postgres#2404]
After upgrading to pg@8 I experience trouble with async_hooks. I am using as async_hooks as a continuation local storage for savng the current connection to the database. In some situations, after receiving the rows from postgres server, the context seems to be lost. This is because async_hooks is not able to track the async execution chain properly. This could be caused by some socket reuse or similar in pg.
I am using [node-cls](https://www.npmjs.com/package/node-cls)  for context tracking. And this again is used by the orm [rdb](https://www.npmjs.com/package/rdb). I am the author of both. I had to downgrade pg dependency to v7 to make it work again.

Have you any idea what is causing this ?

**Comment by brianc** [comment]
would you be able to create a self-contained script that demostrates the
problem (with only pg modules if possible)? Then we could create a test
case for it and dive in

**Comment by lroal** [comment]
Actually, I am not able to reproduce. The error seems to be magically gone now. Or perhaps it just occurs in rare circumstances with high load or something similar. I will let you know if I am able to reproduce.
