### ISSUE TITLE
new pg-query-stream publish is missing the dist folder

### ISSUE THREAD

**Issue by contra** [brianc/node-postgres#2408]
3.4.0 (published 4hrs ago) was published without the dist folder, which causes this error.

```
Cannot find module '/node_modules/pg-query-stream/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by dynamikus** [comment]
yup same here. 3.4.0 is published without dis folder.

**Comment by brianc** [comment]
okay i found the problem, PR incomming

**Comment by brianc** [comment]
Sorry about that - that was a new feature added & it wasn't included in the prepublish script.

I published a fix at `pg-query-stream@3.4.1` - please let me know if its good for you!

**Comment by contra** [comment]
Works for me - thanks.

**Comment by brianc** [comment]
yah sorry about that!
