### ISSUE TITLE
cursor.read is not a function when using cursor

### ISSUE THREAD

**Issue by askmike** [brianc/node-postgres#2410]
Apologies for this PR, as I'm sure it's not a code issue. Also mad respect for maintaining this open source project!

I'm trying to run the cursor example:

    const { Pool } = require('pg')
    const Cursor = require('pg-cursor')
    const pool = new Pool()
    const client = await pool.connect()
    const cursor = client.query(new Cursor('select * from generate_series(0, 5)'))
    cursor.read(100, (err, rows) => {
      if (err) {
        throw err
      }
      assert(rows.length == 6)
      cursor.read(100, (err, rows) => {
        assert(rows.length == 0)
      })
    })

And I'm getting:

    TypeError: cursor.read is not a function

versions:

    node v9.8.0
    pg@8.5.0
    pg-cursor@2.5.0
    UNMET PEER DEPENDENCY pg-native@>=2.0.0 <- I assume this means I'm not using native bindings

EDIT, I'm running it in on a pool that is also doing different queries (non cursor) at the same time.

**Comment by brianc** [comment]
Thanks. 😄 
That's weird...it looks like [you're using it right, based on the test here](https://github.com/brianc/node-postgres/blob/master/packages/pg-cursor/test/pool.js#L15).

Lemme see if I can repro your issue locally.

**Comment by brianc** [comment]
also, that's a p old version of node! It _should_ work though (though technically non-LTS versions that old aren't supported)

**Comment by askmike** [comment]
> also, that's a p old version of node!

Will see if updrading helps.

Just added this to my OP:

> EDIT, I'm running it in on a pool that is also doing different queries (non cursor) at the same time.

I'll try to isolate the cursor usage outside the pool to see it it persists

**Comment by brianc** [comment]
I just ran this:
```js
const { Pool } = require("pg");
const assert = require("assert");
const Cursor = require("pg-cursor");
const pool = new Pool();
const run = async () => {
  const client = await pool.connect();
  const cursor = client.query(
    new Cursor("select * from generate_series(0, 5)")
  );
  cursor.read(100, (err, rows) => {
    console.log("hit");
    if (err) {
      throw err;
    }
    assert(rows.length == 6);
    cursor.read(100, (err, rows) => {
      assert(rows.length == 0);
      client.end();
    });
  });
};

run();
```
with:

```
$ node --version
v9.8.0
```
$ yarn list
yarn list v1.22.10
├─ buffer-writer@2.0.0
├─ inherits@2.0.4
├─ packet-reader@1.0.0
├─ pg-connection-string@2.4.0
├─ pg-cursor@2.5.0
├─ pg-int8@1.0.1
├─ pg-pool@3.2.2
├─ pg-protocol@1.4.0
├─ pg-types@2.2.0
│  ├─ pg-int8@1.0.1
│  ├─ postgres-array@~2.0.0
│  ├─ postgres-bytea@~1.0.0
│  ├─ postgres-date@~1.0.4
│  └─ postgres-interval@^1.1.0
├─ pg@8.5.0
│  ├─ buffer-writer@2.0.0
│  ├─ packet-reader@1.0.0
│  ├─ pg-connection-string@^2.4.0
│  ├─ pg-pool@^3.2.2
│  ├─ pg-protocol@^1.4.0
│  ├─ pg-types@^2.1.0
│  └─ pgpass@1.x
├─ pgpass@1.0.4
│  └─ split2@^3.1.1
├─ postgres-array@2.0.0
├─ postgres-bytea@1.0.0
├─ postgres-date@1.0.7
├─ postgres-interval@1.2.0
│  └─ xtend@^4.0.0
├─ readable-stream@3.6.0
│  ├─ inherits@^2.0.3
│  ├─ string_decoder@^1.1.1
│  └─ util-deprecate@^1.0.1
├─ safe-buffer@5.2.1
├─ split2@3.2.2
│  └─ readable-stream@^3.0.0
├─ string_decoder@1.3.0
│  └─ safe-buffer@~5.2.0
├─ util-deprecate@1.0.2
└─ xtend@4.0.2
Done in 0.06s.
```

and it worked fine for me

**Comment by askmike** [comment]
Yep, running that script in standalone works fine for me too - just having problems in an app that uses the pool for other queries too, let me see if I can isolate into a sample use case.

**Comment by askmike** [comment]
@brianc wops implementation bug on my end. You don't have to explicitly call `pool.connect` for normal queries (where you pass a string instead of a cursor instance), eg. you can do:

    const pool = new Pool();
    const res = await pool.query("select * from generate_series(0, 5)");
    console.log(res.rows);

And we weren't doing this for the other queries. But this seems not supported when using a cursor (where you don't `await` the query but instate iterate more granually), you have to call `connect()` explicitly. Our other code is pretty old, so could be that pool API changed over time and we didn't update our old code.

**Comment by brianc** [comment]
glad we got it sorted! 👯
