### ISSUE TITLE
Kind of strange error

### ISSUE THREAD

**Issue by SagarPattnayak** [brianc/node-postgres#2411]
The connection works fine in my Prod environment. However today after deploying to dev i am getting a strange error. Have never seen this before.

"errorType": "TypeError",
    "errorMessage": "Cannot use 'in' operator to search for 'key' in true",
    "stack": [
        "TypeError: Cannot use 'in' operator to search for 'key' in true",
        "    at Socket.<anonymous> (/var/task/node_modules/pg/lib/connection.js:86:19)",
        "    at Object.onceWrapper (events.js:422:26)",
        "    at Socket.emit (events.js:315:20)",
        "    at Socket.EventEmitter.emit (domain.js:483:12)",
        "    at addChunk (_stream_readable.js:295:12)",
        "    at readableAddChunk (_stream_readable.js:271:9)",
        "    at Socket.Readable.push (_stream_readable.js:212:10)",
        "    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)"
    ]

Any pointer please?

**Comment by vitaly-t** [comment]
It is probably [this change](https://github.com/brianc/node-postgres/pull/2407).

Now that `ssl` is a boolean, operand `in` is no longer valid.

https://github.com/brianc/node-postgres/blob/ebe412cf243be35d21ead496d736755217933266/packages/pg/lib/connection.js#L86

There some tests missing for this.

**Comment by brianc** [comment]
> It is probably this change.
no, I haven't released #2407 yet.  

@SagarPattnayak - I'll release the changes merged with #2407 and it should fix things.  If you don't want to wait for the fix, don't pass `ssl: "true"` with `true` as a _string_ and you should be fine.  Alternatively, wait for the next patch version (due today) and the problem should be fixed for you.

**Comment by brianc** [comment]
@SagarPattnayak - published pg@8.5.1 -- install it & give it a try. It should fix your issue.

**Comment by SagarPattnayak** [comment]
Dear @brianc 
Thanks for taking care of this so quickly. This is working fine now.

Best
Sagar
