### ISSUE TITLE
pg-query-stream version + compatibility

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#2412]
`pg-query-stream` has been fully revamped in the latest release, with at least one breaking change - changing the class name again, from `PgQueryStream` to `QueryStream` (see [PR #2476](https://github.com/brianc/node-postgres/pull/2376)).

There are libraries out there that validate the object by its class name, so those would all need to be updated.

The request is here that `pg-query-stream` version should have been upped to 4.0.0, or not with the minor version increment.

Please, either bring the version to 4.0.0 (preferable), or rename the class back to `PgQueryStream` (this will require TypeScript update as well, so the first option is better).

---

Note that this is the second time such a change happens. Which means there should be a test added for the class name, to make sure people stop changing it. Internal class names are often important, being the only way an object instance can be validated.

**Comment by chyzwar** [comment]
@brianc I made that change. I saw that tests, documentation and definitely typed where using QueryStream as name. Let me know what do you think ?

**Comment by vitaly-t** [comment]
@chyzwar I think we should keep the name as is, just up `pg-query-stream` package version to 4.0.0, and that's it.

**Comment by charmander** [comment]
> There are libraries out there that validate the object by its class name

That doesn’t sound like a good idea.

**Comment by brianc** [comment]
> There are libraries out there that validate the object by its class name

Yeah there's an argument that you could say any change is a breaking change.  What if an external library validated a function by the contents of calling `.toString()` on the function.  Any lines of code in the function change...breaking change!

I'm fine to bump the version if there's a material issue caused by this, but I'd like to see an actual example in the wild before just calling this a breaking change because the name of a class changed.  It sounds more like pedantry than an actual issue.

**Comment by vitaly-t** [comment]
@brianc Your `pg-query-stream` is for integration with other modules. How are those supposed to determine that the object they are passed in is indeed of type `QueryStream`? How to validate for that?

**Comment by brianc** [comment]
> How to validate for that?

I would imagine something like...

```js
const QueryStream = require('pg-query-stream')

if (something instanceof QueryStream) {
  // we have a stream!
}
```

that also works like this

```js
const ICanCallThisAnythingIWant = require('pg-query-stream')
if (something instanceof ICanCallThisAnythingIWant) {
  // we have a stream!
}
```

Does that work?

**Comment by vitaly-t** [comment]
@brianc Nope, it doesn't. The modern NodeJS has gotten too progressive, one might say. These days you have things like `docker` that manages to isolate modules, so `instanceof` fails when applied across two isolated docker containers, even though the module is the same. So I'm trying to stay away from the `instanceof` approach.

**Comment by brianc** [comment]
Sorry - not following what you're saying about docker - how can you require modules from one docker container into another? I don't do super advanced stuff w/ docker.

Also, not following what you mean about including the actual module type in your project, could you show me a code sample or example here?  I still think checking the `name` of a class and changing behavior based on that is a brittle approach to things, but I can do a semver major bump if required.

**Comment by vitaly-t** [comment]
Within docker, it is possible to load the same module multiple times, each within isolated environment, so if you create a class object in one, pass it into the other, then `instanceof` is suddenly not working, JavaScript sees it as 2 separate classes.

> not following what you mean about including the actual module type in your project

When you want to add support for `QueryStream`, you shouldn't need to include the module itself. The latter is done by the module that uses your module. Including into module that doesn't really need it only creates problem - extra dependency, plus possible version conflict.

> I still think checking the name of a class and changing behavior based on that is a brittle approach to things

I have explained the best I could why and why it doesn't work, so not much option there.

> but I can do a semver major bump if required.

Yes, please, it would make life easier, since the last version suddenly changed the class name.
