### ISSUE TITLE
travis-ci.org shutdown / travis-ci.com migration

### ISSUE THREAD

**Issue by sehrope** [brianc/node-postgres#2418]
On Dec 31st, 2020, Travis is going to be shutting down travis-ci.org:

https://docs.travis-ci.com/user/migrate/open-source-repository-migration#frequently-asked-questions

I think we can migrate the driver to use .com. There may be a bit of slow down as they've changed the FOSS tier concurrency a bit (IIUC, from 5 concurrent tasks to 4), but I think it should be fine.

Creating this issue to track the migration as we've got just a bit over a month to make the change.

**Comment by brianc** [comment]
I think I'm gonna upgrade to paid tier.  I've been waiting for 12+ hours recently for it to finish running tests which is...way too long.

**Comment by brianc** [comment]
okay according to their docs it's slow on `.org` because of all this migration stuff, before I upgrade I'll wait & see if it's faster at `.com`.  Thanks for letting me know btw, I just kicked off the migration.

**Comment by brianc** [comment]
kk we're up at least basically right now, i'll see how it behaves here in a min https://travis-ci.com/github/brianc/node-postgres/builds/204521356

**Comment by sehrope** [comment]
Ha! I just realized I posted this here even though I was looking into something for the Java driver (pgjdbc) at the time.

Thanks for following up and updating it. Looks like it started building on .com!

**Comment by brianc** [comment]
Well cool - the `.com` is working now. Thanks for the heads up!

**Comment by vitaly-t** [comment]
@brianc Best is to re-open this issue, and move everything into the new [Github Actions](https://github.com/features/actions) :wink:
