### ISSUE TITLE
compatability table

### ISSUE THREAD

**Issue by maikelmclauflin** [brianc/node-postgres#2428]
anybody have any compatability tables? i ran into an issue where, when trying to connect node-postgres `^7.18.2` to a docker image: `postgres:11.9` i kept getting a timeout. upgrading to latest worked

**Comment by brianc** [comment]
https://node-postgres.com/#version-compatibility

pg should be compatible with __all__ versions of postgres >= 9. 

There was unfortunately a breaking change on some internal stream APIs in node 14, but otherwise any version of pg should work w/ all LTS versions of node.

**Comment by maikelmclauflin** [comment]
ah, that's probably what it was. i upgraded to node 14 for the lts cut. thanks!
