### ISSUE TITLE
[Feature Request] Type parser for nullable types

### ISSUE THREAD

**Issue by Ericnr** [brianc/node-postgres#2446]
I'd like to be able to wrap nullable types in an Option monad from FP libs like https://github.com/hqoss/monads. A type parser that runs for every nullable type after the first type parser would cover this use case.

**Comment by charmander** [comment]
Every type is nullable in PostgreSQL.

**Comment by Ericnr** [comment]
you could still have a function run on every column without a not null constraint, _if_ node-pg has that info when querying

**Comment by brianc** [comment]
The type parsing is fully customizable and you can totally supply your own types.  Unfortunately, whether or not the column is nullable is not something that's exposed at the protocol level at query time, so you'd have to treat every column as null or have some logic in your app that applied the Option monad to fields on a column by column basis based on schema knowledge you have in your app.

**Comment by Ericnr** [comment]
cool, thanks!
