### ISSUE TITLE
problem with max connection in pgpool

### ISSUE THREAD

**Issue by abaharian** [brianc/node-postgres#2452]
I am using your pg pool in a project with node.js and postgreSQL. I've set the max pool size equal to 100, but when the requests from client exceeded 100, pgpool starts to establish new connections. But I need it return an Error or wait my request until at least 1 connection become free.
Actually I want to set a "bounded max"  or something like that. Is there any way to set a "Bounded max" that ensures me the pool size will NEVER exceed it?

**Comment by sShidi** [comment]
The Same Problem here too 😑

**Comment by sehrope** [comment]
That's how the pool works now. Try this out:

```js
const pg = require('pg');

const pool = new pg.Pool({
    max: 5,
});

const STATE = [];
const STARTED = Date.now();

function printState() {
    console.log('%s - %s', ('' + (Date.now() - STARTED)).padStart(6), STATE.join(' '));
}

function updateState(id, value) {
    STATE[id] = value;
    printState();
}

async function doStuff(id) {
    updateState(id, 'C');
    const client = await pool.connect();
    try {
        updateState(id, 'Q');
        await client.query('SELECT pg_sleep(1 + random())');
    } finally {        
        client.release();
    }
    updateState(id, 'F');
}

async function main() {
    await Promise.all([...Array(10)].map((_, i) => doStuff(i)));
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((err) => {
        console.error('%s', err);
        process.exit(1);
    })
```

At any given time there's at most 5 (the max pool size) active clients (state = Q):

C = Connecting
Q = Querying
F = Finished

```text
     0 - C
     4 - C C
     4 - C C C
     5 - C C C C
     5 - C C C C C
     5 - C C C C C C
     5 - C C C C C C C
     5 - C C C C C C C C
     5 - C C C C C C C C C
     5 - C C C C C C C C C C
    12 - C Q C C C C C C C C
    13 - C Q Q C C C C C C C
    14 - Q Q Q C C C C C C C
    14 - Q Q Q Q C C C C C C
    17 - Q Q Q Q Q C C C C C
  1110 - F Q Q Q Q C C C C C
  1111 - F Q Q Q Q Q C C C C
  1247 - F F Q Q Q Q C C C C
  1247 - F F Q Q Q Q Q C C C
  1474 - F F Q F Q Q Q C C C
  1474 - F F Q F Q Q Q Q C C
  1647 - F F F F Q Q Q Q C C
  1647 - F F F F Q Q Q Q Q C
  1653 - F F F F F Q Q Q Q C
  1653 - F F F F F Q Q Q Q Q
  2583 - F F F F F F Q Q Q Q
  2601 - F F F F F F F Q Q Q
  2861 - F F F F F F F F Q Q
  3616 - F F F F F F F F F Q
  3653 - F F F F F F F F F F
```

Any pool size is per node process. If you're using something like the cluster module then you'll have a totally separate pool per node process so you'll need to adjust the sizes and server limits accordingly.

**Comment by abaharian** [comment]
dear sehrope;
Thanks for your detailed response. I am going to check this way, So I am closing this issue and if this don't solve the problem, I will reopen it.


Thanks a lot,
Sincerely
Ardeshir
