### ISSUE TITLE
WHERE clause over row_to_json

### ISSUE THREAD

**Issue by christopheSeeka** [brianc/node-postgres#2463]
I'm using the following query to retrieve some data from my postgres db:

```
pool.query(`
  SELECT a.*, row_to_json(u.*) as users 
  FROM artworks a INNER JOIN users u USING(address) 
  WHERE (a.flag != ($1) OR a.flag IS NULL) 
  ORDER BY a.date DESC LIMIT 1000`, 
["ILLEGAL"]).then(users => {
  if (users) {
    res.json(users.rows);
  } 
  }).catch(err => {
    next(err);
  })
```
I now also want add a condition for users in the WHERE clause so i added the following:

**_AND u.status == ($2)_**

```
pool.query(`
  SELECT a.*, row_to_json(u.*) as users 
  FROM artworks a INNER JOIN users u USING(address) 
  WHERE (a.flag != ($1) OR a.flag IS NULL) 
  AND u.status == ($2) 
  ORDER BY a.date DESC LIMIT 1000`, 
["ILLEGAL", "VERIFIED"]).then(users => {
  if (users) {
    res.json(users.rows);
  } 
  }).catch(err => {
    next(err);
  })
```
But i'm getting the following error:

_**operator does not exist: character varying == unknown**_

Any idea what i'm doing wrong please?

Thank you in advance.

**Comment by charmander** [comment]
The SQL “equals” operator is `=`, not `==`.

**Comment by christopheSeeka** [comment]
It works... now i feel a bit stupid :) But thank you very much for the help!
