### ISSUE TITLE
how to extent some function in `client`

### ISSUE THREAD

**Issue by chenkai0520** [brianc/node-postgres#2476]
now i use this way 
```js
async function getClient() {
  const client = await pool.connect();
  client.runSql = runSql;
  return client;
}
```

Is there a way？ like 
```js
pool.prototype.runSql = runSql;

async function getClient() {
  const client = await pool.connect();
  return client;
}
```
so i can

```js
const client = getClient();
client.runsql()
```

**Comment by charmander** [comment]
Both `pg.Client` and `pg.Pool` can be inherited from, and `Pool`’s constructor supports replacing the `Client` type it uses.

```js
class MyClient extends pg.Client {
  runSql() {
    ⋮
  }
}

const pool = new Pool({
  ⋮
  Client: MyClient,
});
```

**Comment by chenkai0520** [comment]
> Both `pg.Client` and `pg.Pool` can be inherited from, and `Pool`’s constructor supports replacing the `Client` type it uses.
> 
> ```js
> class MyClient extends pg.Client {
>   runSql() {
>     ⋮
>   }
> }
> 
> const pool = new Pool({
>   ⋮
>   Client: MyClient,
> });
> ```

thank you ，it solved my problem，
