### ISSUE TITLE
Tablespaces

### ISSUE THREAD

**Issue by spiderlord202** [brianc/node-postgres#2491]
Can I use tablespaces in pg somehow, I want to increase my db storage space by using one in my node.js application.
Sources: 
 [https://www.postgresqltutorial.com/postgresql-create-tablespace/](https://www.postgresqltutorial.com/postgresql-create-tablespace/)
 [https://www.postgresql.org/docs/9.4/app-createdb.html](https://www.postgresql.org/docs/9.4/app-createdb.html)

**Comment by vitaly-t** [comment]
And what exactly prevents you from using it as it is?

**Comment by spiderlord202** [comment]
I have tried using it. I would never ask for help on a module without trying to use it. I just need to know where the data is held, Like is it stored in the node applictaion pg is being run on or its being run remotely and if it is being held in the node app where exactly is it stored e.g what directory? The reason why I am asking whether or not it uses tablespaces becuse I found a hosting provider that offers a good amount of storage that I think could be useful.

**Comment by brianc** [comment]
The data would be held inside postgres, not in your node application.  Node-postgres strives to be as stateless as it can be and doesn't write any files or store very much at all in memory for the lifetime of your application other than the initial connection config you provide to the client/pool.
