### ISSUE TITLE
Timescale Connection Issue

### ISSUE THREAD

**Issue by Karan96Kaushik** [brianc/node-postgres#2494]
### Issue
Getting a rejection while trying to connect to TimescaleDB managed server
Additional Info,
1. the connection is working in python (psycopg2 module), pgAdmin and DBeaver from the same machine
2. pg version 8.5.1
3. node version 15.11.0
4. pg_hba hosts are set to allow all
5. No SSL pg configuration

### Code - Error
```js
const { Client } = require('pg')
// No SSL
let connectionString= "postgresql://USER:PW@HOST:PORT/DBNAME"

const client = new Client({connectionString})

;(async () => {
    await client.connect()

    const res = await client.query('SELECT $1::text as message', ['Hello world!'])
    
    console.log(res.rows[0].message) // Hello world!
    await client.end()
})()
```
``` 
error: no pg_hba.conf entry for host "MY_IP", user "USER", database "DBNAME", SSL off
at Parser.parseErrorMessage (/home/samsepiol/Documents/gitWorkspace/Irasus_Middleware/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/samsepiol/Documents/gitWorkspace/Irasus_Middleware/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/samsepiol/Documents/gitWorkspace/Irasus_Middleware/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/samsepiol/Documents/gitWorkspace/Irasus_Middleware/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 153,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '495',
  routine: 'ClientAuthentication'
}```

**Comment by vitaly-t** [comment]
https://stackoverflow.com/questions/25000183/node-js-postgresql-error-no-pg-hba-conf-entry-for-host

**Comment by sehrope** [comment]
@Karan96Kaushik Try connecting over SSL. If the HBA is rejecting non-SSL connections but psql is working from the same source, then it's probably connecting with SSL without you explicitly asking for it because the default in psql is "prefer" (i.e. try using SSL if it's available, otherwise retry without SSL). With the nodejs pg driver you have to explicitly decide to use SSL as the driver does not try to reconnect.

**Comment by Karan96Kaushik** [comment]
@vitaly-t 
I have tried all this, as mentioned before pg_hba is set to allow all hosts

**Comment by Karan96Kaushik** [comment]
@sehrope 
It was an ssl issue, SSL connection was failing due to self signed certificate setting ```NODE_TLS_REJECT_UNAUTHORIZED='0'``` fixed it

Thanks for the help

**Comment by vitaly-t** [comment]
> I have tried all this, as mentioned before pg_hba is set to allow all hosts

How did you try all this before, if the accepted answer there tells you right away to use SSL, which was exactly your problem?
