### ISSUE TITLE
Search an integer array fails, invalid syntax for integer

### ISSUE THREAD

**Issue by dl-husky73** [brianc/node-postgres#2495]
I am referencing JSON / Array issue #442 

RN - 65
Node - 14
Express - 4.1

I have a very simple PG Query that works fine in Postgre:
SELECT * from table1 where field1 @> '{619327}'
Field1 is an Integer Array with intarray extension, index.  

In PG Tried Several Iterations with no success -> 
  const url = "SELECT * from table1 where field1 @> '{$1}'   Error: invalid input syntax for type integer: "$1" at character 45
  const url = "SELECT * from table1 where field1 @> '${1}'::json
  const url = "SELECT * from table1 where field1 @> '$1'::json
  const url = "SELECT * from table1 where field1 @> '{$1}'::jsonb
  const url = "SELECT * from table1 where field1 @> '$1'::jsonb  Error:Token Invalid. :CONTEXT: JSON data, line 1: $...
  return client.query(url, addValues) 

I saw #442 and tried a few things. I am not exactly sure what to do. Anyone solve this problem for an Integer? 

Struggling.

**Comment by charmander** [comment]
```sql
SELECT * FROM table1 WHERE field1 @> $1
```

**Comment by dl-husky73** [comment]
Thanks for the quick reply! I know the Intarray extension on an Integer multi-array requires to use {}.  I would have felt pretty silly if it was a straight forward application. 

I changed to above and got the following errors:
2021-03-16 01:49:23[19492]:ERROR: malformed array literal: "619327"
2021-03-16 01:49:23 [19492]:DETAIL: Array value must start with "{" or dimension information.
2021-03-16 01:49:23 [19492]:STATEMENT: SELECT * from table1 where field1 @> $1 and guid=$2

**Comment by charmander** [comment]
When you pass the parameter, it needs to be as an array (or the string form of an array). So if you had:

```js
client.query("SELECT * FROM table1 WHERE field1 @> $1 AND guid = $2", [619327, someGuid])
```

the version with a correct parameter value would be this:

```js
client.query("SELECT * FROM table1 WHERE field1 @> $1 AND guid = $2", [[619327], someGuid])
```

**Comment by dl-husky73** [comment]
The first option worked, thanks for the feedback!  
client.query("SELECT * FROM table1 WHERE field1 @> $1 AND guid = $2", [[619327], someGuid]) worked which 
showed up as '{619327}'
