### ISSUE TITLE
Vertica 9.x pg_cursor returns all rows in the table.

### ISSUE THREAD

**Issue by markddrake** [brianc/node-postgres#2496]
Long Shot I know. Trying to use node_postgres against Vertica.

Problem I am encountering is that when I attempt to query a table using a cursor all the rows are returned, even if ask for 50, and if I ask for the next 50, I get all the rows again.

```
const cursor = this.connection.query(new Cursor(tableInfo.SQL_STATEMENT))
    let rows = await new Promise((resolve,reject) => {
	   cursor.read(50,(err,rows) => {
		 if (err) reject(err)
	     resolve(rows);
	   })
	})
	let x = 1;
	while (rows.length > 0) {
      console.log(rows.length)
      rows = await new Promise((resolve,reject) => {
	    cursor.read(50,(err,rows) => {
		  if (err) reject(err)
	      resolve(rows);
	    })
	  })
	  x++;
	  if (x > 10) break;
    }
```

returns 
```
2021-03-17T05:39:46.398Z [INFO][PIPELINE][SERIAL][Vertica][FILE]: Processing 1 Tables
918843
918843
918843
918843
918843
918843
918843
918843
918843
918843
```

My sql is as follows...

```
select CAST("PROD_ID" AS VARCHAR) "PROD_ID",CAST("CUST_ID" AS VARCHAR) "CUST_ID","TIME_ID",CAST("CHANNEL_ID" AS VARCHAR) "CHANNEL_ID",CAST("PROMO_ID" AS VARCHAR) "PROMO_ID",CAST("QUANTITY_SOLD" AS VARCHAR) "QUANTITY_SOLD",CAST("AMOUNT_SOLD" AS VARCHAR) "AMOUNT_SOLD" from "SH"."SALES" t
```

The cast NUMBERIC as VARCHAR is to avoid NUMERICS coming back  as true or false..

I realize I'm probably on a hiding to nothing here but just wondered if anyone had any ideas before I abandon this project. The node-vertica driver appears to have been abandoned so that's not a realistic alternative.

**Comment by markddrake** [comment]
I tried digging into the code to see there was anything obvious but it looks like you simply send a message to the server requesting 'n' rows and expect the server to honor it. I'm guessing that Vertica simply does not honor the row count and "that's all she wrote", or should it be 'that's everything you wrote" :). Please let me know if I am missing something...

**Comment by markddrake** [comment]
Slept on it and this appears to work as expected

```
const query = new Query(tableInfo.SQL_STATEMENT)
    const result = this.connection.query(query)
	let count = 0;
    try {
	  const rows = await new Promise((resolve,reject) => {
        query.on('row', row => {
	       count++
        })
        query.on('end', () => {
          console.log('query done')
  	      resolve(count)
       })
       query.on('error', err => {
         console.error(err.stack)
 	     reject(err)
       })
	 })
	 console.log('Rows Processed',rows)
	} catch (e) {
	  console.log(e);
    }
	process.exit()
```
```
query done
Rows Processed 918843
```

**Comment by markddrake** [comment]
If I use this model can I pause() and resume() ?

**Comment by brianc** [comment]
There is no way to `pause` or `resume` the client unless you pause the underlying stream which you can access at `client.connection.stream`.  I've never done this myself but it _should_ work?  Its a bit hacky but worth a shot.  To your original question & answer yeah its likely vertica is ignoring the request for a certain number of rows, which is unfortunate.

**Comment by markddrake** [comment]
Thanks Brian, I'l give it a shot and report back... Any idea about numerics coming back as TRUE / FALSE..

**Comment by markddrake** [comment]
Thanks Brian.. That appears to work as required. I'll do a lot more testing and let you know.

**Comment by markddrake** [comment]
Was able to run all of my regression tests successfully
