### ISSUE TITLE
cannot connect to Redshift using this library

### ISSUE THREAD

**Issue by delmotte** [brianc/node-postgres#2497]
```
const pg = require('pg');
const connectionString = 'postgres://username:password@host:port/dbname';
const client = new pg.Client({ connectionString });

console.log('ok');
client.connect(console.log);
client.on('error', console.log);
client.on('notification', console.log);
client.on('end', console.log);
client.on('notice', console.log);
```

It just logs 'ok' and the process exits.

Did I miss something?

Note: I can connect to Redshift using psql CLI but not with the library, it doesn't seem to be an issue with creds or auth.

**Comment by delmotte** [comment]
I had to install pg-native and use require('pg').native to make it work ;)

**Comment by charmander** [comment]
Which version of Node and which version of pg?
