### ISSUE TITLE
Process will exit when pg restarting

### ISSUE THREAD

**Issue by yjhmelody** [brianc/node-postgres#2499]
```
D:\work\patractlabs\decoder\node_modules\pg-protocol\src\parser.ts:357
        : new DatabaseError(messageValue, length, name)
          ^
error: terminating connection due to administrator command
    at Parser.parseErrorMessage (D:\work\patractlabs\decoder\node_modules\pg-protocol\src\parser.ts:357:11)
    at Parser.handlePacket (D:\work\patractlabs\decoder\node_modules\pg-protocol\src\parser.ts:186:21)
    at Parser.parse (D:\work\patractlabs\decoder\node_modules\pg-protocol\src\parser.ts:101:30)
    at Socket.<anonymous> (D:\work\patractlabs\decoder\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:376:20)
    at Socket.EventEmitter.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:279:9)
    at Socket.Readable.push (node:internal/streams/readable:218:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:192:23)
```

I don't know how to catch this error.

**Comment by charmander** [comment]
You need to attach an `error` event listener to the pool:

```js
pool.on('error', console.error);
```

and attach one every time you retrieve a client from the pool (not necessary for `pool.query`):

```js
const client = await pool.connect();
client.on('error', console.error);
```

*and* remove it before putting it back in the pool:

```js
client.off('error', console.error);
client.release();
```

or instead of doing that, if you just want to log the errors and leave error handling up to rejected promises from queries, it’s probably fine to add listeners that last for the lifetime of the pooled connection (which should probably be the pg default for pooled clients that aren’t listening for anything):

```js
pool.on('error', console.error);

pool.on('connect', (client) => {
    client.on('error', console.error);
});
```

**Comment by yjhmelody** [comment]
I need to retry when meet network error. I find that if i don't call `pool.on('error', console.error);`, sometimes the nodejs will exit with  the error. Even that I catch all errors I known.

**Comment by charmander** [comment]
The error event on `pool` is only raised for clients that are idle in the pool, and a client that raises an error event also starts rejecting queries sent to it, so as long as you’re retrying on query errors, it should be fine not to do anything special with the error events.

**Comment by yjhmelody** [comment]
BTW, there are some easy way to catch network relatived error? I catch them and match the error message string currently.

**Comment by charmander** [comment]
If the error you’d like to handle has a `code` property, that’s a good choice. If it doesn’t (i.e. it’s a non-query error constructed by pg), there’s probably no better way than what you have yet, unfortunately.

**Comment by yjhmelody** [comment]
thanks！
