### ISSUE TITLE
How define primary key that consists of more than one column?

### ISSUE THREAD

**Issue by James-Clark12** [brianc/node-postgres#2502]
On creating a table I want to define my primary key as two columns.

The postgres docs document that it can be done like this:

```
CREATE TABLE TABLE (
	column_1 data_type,
	column_2 data_type,
	… 
        PRIMARY KEY (column_1, column_2)
);
```

I can't find any examples of how to do it with node-postgres and the following throws a syntax error:

```
    await client.query(
      "CREATE TABLE testTable (userId TEXT NOT NULL, listName TEXT NOT NULL, listContents TEXT NOT NULL) PRIMARY KEY (userId, listName)"
    );
```

What is the correct way of doing this?

**Comment by charmander** [comment]
The `PRIMARY KEY (…)` part goes inside the parentheses as seen in the docs:

```sql
CREATE TABLE testTable (userId TEXT NOT NULL, listName TEXT NOT NULL, listContents TEXT NOT NULL PRIMARY KEY (userId, listName))
```

(this is more of a general PostgreSQL question than a driver question)

**Comment by James-Clark12** [comment]
This is really obvious, I don't know why but for some reason I was convinced that specifically for node-postgres it had to go on the outside of the parentheses.  Thank you charmander.
