### ISSUE TITLE
Pool query on React

### ISSUE THREAD

**Issue by vd999** [brianc/node-postgres#2505]
<CLOSED>

**Comment by vd999** [comment]
I am running this on Postman, the first image is the input whilst second is output I'm recieving.

**Comment by sehrope** [comment]
Format your code blocks with markdown so that others can more easily read it: https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

And describe the actual problem or error.

**Comment by vd999** [comment]
> Format your code blocks with markdown so that others can more easily read it: https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code
> 
> And describe the actual problem or error.

Fixed, apologies this is my first time using this site.

**Comment by sehrope** [comment]
Log the parameter values prior to running the query. They're probably null which could be either from missing middleware (no body parser) or the wrong request type (GET vs POST).

Either way it's likely not an issue with this driver.
