### ISSUE TITLE
error: terminating connection due to administrator command

### ISSUE THREAD

**Issue by lokzzor** [brianc/node-postgres#2509]
Good evening, could you tell me how to cope with the error. I've tried everything already.
Different scenarios of server operation have different manifestations.
1) If the database is turned off, the server tries to connect every 15 seconds, and if the connection is successful, it connects;
2) If the database is running the server connects;
3) If the database is running and I turn off the database for the test, then the server crashes from the first or second connection, and in the code script it does not get into an error.
I attach screenshots of the code
Can you recommend any solutions?
![1](https://user-images.githubusercontent.com/36513909/113519258-b7202380-9593-11eb-9098-4d53af420cd8.png)
![2](https://user-images.githubusercontent.com/36513909/113519260-b8515080-9593-11eb-8cd2-b6a0eed8a8ea.png)

**Comment by sehrope** [comment]
You need to add error event listeners on clients. For historical reasons it's a bit complicated to get it right. See here for more details: https://github.com/brianc/node-postgres/issues/2499#issuecomment-805477725

Also, you should change the credentials for that server. They're visible in the screenshot.
