### ISSUE TITLE
Cannot create DDL statement with parameterized SQL

### ISSUE THREAD

**Issue by yaroslavyal** [brianc/node-postgres#2511]
Hi, I try to create a view with parameterized SQL, but I receive an error `bind message supplies 1 parameters, but prepared statement "" requires 0`
Here is example
```
const res = await pool.query(`
      CREATE VIEW test_view AS
      SELECT $1 AS "column"
    `, ['testvalue'])
```
Can anyone help me with this issue?

**Comment by sehrope** [comment]
You cannot use parameters when defining a view. You need to escape the value and inline it as a string literal:

```
const req = await pool.query(`CREATE VIEW test_view AS SELECT 'testvalue' AS column`);
```

Check out pg-format for a module to handle escaping: https://www.npmjs.com/package/pg-format

**Comment by yaroslavyal** [comment]
Thanks, @sehrope. Will check it
