### ISSUE TITLE
Issue with "with"?

### ISSUE THREAD

**Issue by letto4135** [brianc/node-postgres#2520]
Using a query to get results ordered by a certain value when using a skiptoken instead of limit offset because this has more consistent performance, the query works just fine running from dbeaver but returns "Error: syntax error at end of input" when running with QueryStream.

```
with pos as (
        select row_number() over(order by "ModificationTimestamp" ASC) as rnum, listingkey
        from "table"
        where get_bit(channel, 0) = 1
)
select rp.*, pos."rnum" as skiptoken FROM "table" rp, pos WHERE rp."listingkey"=pos."listingkey" AND pos."rnum" > 100 LIMIT 1
```

**Comment by charmander** [comment]
Can you show the JavaScript code? Also, does the query work when pg-query-stream isn’t involved, i.e. with a simple pg `pool.query`/`client.query`?

**Comment by letto4135** [comment]
It is the same error with both pool.query and client.query. The sql here is copy/pasted from the log right before the call.

**Comment by letto4135** [comment]
Don't mind me, I'm just over here trying to use an if/else statement without an else block... That was my issue... The query went into the QueryStream and then into a different QueryStream type method instead of doing one or the other...
