### ISSUE TITLE
While retrieving Timestamp values from DB it is adding 4 hours to it.

### ISSUE THREAD

**Issue by SagarPattnayak** [brianc/node-postgres#2525]
Hi,
I am using "pg" in one of my nodeapp. The timestamp values i insert programmatically is inserting correct time. However while retrieving the same via pool.query, it is adding 4 hours to it. How to address this?

File1 is from DB & File2 id while retrieving. 
![File1](https://user-images.githubusercontent.com/74406707/115532516-7f172100-a2b3-11eb-8f68-27af0f27f466.png)
![File2](https://user-images.githubusercontent.com/74406707/115532548-89d1b600-a2b3-11eb-9b33-4e62d3cdbd41.png)

Appreciate any feedback suggestion.

**Comment by charmander** [comment]
See https://github.com/brianc/node-postgres/issues/2390#issuecomment-719984206. If your column represents moments in time, though – it sounds like it does – it should probably be a `timestamp with time zone`. That data type works intuitively in pg.

**Comment by vitaly-t** [comment]
`timestamp with time zone` = `timestamptz` 😉

**Comment by SagarPattnayak** [comment]
I have tried both with timestamp and timestamptz datatype. Same issue. So as a work around I am using varchar as datatype for datetime fields.

**Comment by charmander** [comment]
If the same thing is happening with `timestamptz`, there’s probably something incorrect about one of the queries involved, the way you’re processing the results, or the way you’re passing in the parameter. Without seeing any code it’s hard to say though.

**Comment by themaick** [comment]
Read my comment here https://github.com/brianc/node-postgres/issues/2530#issuecomment-827441164

**Comment by jpschw** [comment]
For anyone else having trouble - You're probably testing locally and it's picking up your local timezone from NodeJS.
Put this at the start of your program if you intend to always work in the same timezone across all envs:
process.env.TZ = "UTC+0";

**Comment by mfvas** [comment]
Another way to "fix" this is to set:

`pg.defaults.parseInputDatesAsUTC = true;`

which makes it assume that all your DB timestamps are in UTC time.
