### ISSUE TITLE
Why does pg.Cursor still use callbacks?

### ISSUE THREAD

**Issue by Bluenix2** [brianc/node-postgres#2545]
Looking at the [the pg.Cursor API documentation](https://node-postgres.com/api/cursor) it appears to be using callbacks, is there a reason that there hasn't been a switch to the Promises API introduced in ES6?

Other parts of the package shows the usage of promises. As can be seen [here](https://node-postgres.com/features/queries).

**Comment by sehrope** [comment]
All of that code predates Promises by many years and nobody has gotten around to adding it. It's common for anybody using the Cursor API in modern applications to add their own Promise wrapper. Ex: https://github.com/sehrope/postgres-with-nodejs-code/blob/85fd7acf5b4e1be5a124bbf39c68bbc2e5591489/src/00026-memory-usage-with-cursor.js#L5-L15

I think it'd be fine to add it directly to the `Cursor.read(...)` function. It could mirror the query API and check if the second parameter is not defined, and if so, return the result as a Promise. The close function is a bit trickier as right now the callback is not required so changing it to return a Promise (when there's no callback) could lead to a dangling Promise in existing code.
