### ISSUE TITLE
Using parameters with an ARRAY constructor

### ISSUE THREAD

**Issue by cantide5ga** [brianc/node-postgres#2551]
Should I expect this to work?

```
const sql = `
...
WITH
	t AS (INSERT INTO thing (arg) VALUES(ARRAY $1) RETURNING id),
...
`

pool.query(sql, ['[10, 20, 30]', ...]);
```
$1 is not being parameterized, causing error `"syntax error at or near \"$1\""`

It works via psql cli:
```
> \set arr [10, 20, 30]
...
> WITH
>	t AS (INSERT INTO thing (arg) VALUES(ARRAY :arr) RETURNING id),
...
```

**Comment by charmander** [comment]
The parameter represents a value rather than text that gets inserted into the query. The correct version looks like this:

```js
const sql = `
...
WITH
	t AS (INSERT INTO thing (arg) VALUES ($1) RETURNING id),
...
`;

pool.query(sql, [[10, 20, 30], ...]);
```

The array parameter gets passed as a JavaScript array directly and there’s no `ARRAY` in the query.
