### ISSUE TITLE
How to insert row with bytea field?

### ISSUE THREAD

**Issue by fossegrim** [brianc/node-postgres#2557]
The docs does not mention how to insert a row with a field of type bytea. Which Node datatype can I insert in bytea? I tried a binary string, but that did not work and i got ```error: invalid byte sequence for encoding "UTF8": 0x00```.

**Comment by sehrope** [comment]
You can insert Buffer (https://nodejs.org/dist/latest-v14.x/docs/api/buffer.html) values into bytea fields.

**Comment by fossegrim** [comment]
> You can insert Buffer (https://nodejs.org/dist/latest-v14.x/docs/api/buffer.html) values into bytea fields.

Thank you, I will try that.

**Comment by fossegrim** [comment]
Great, that worked for me. Closing.
