### ISSUE TITLE
Optional columns on update

### ISSUE THREAD

**Issue by Zyles** [brianc/node-postgres#2559]
I don't see it mentioned in the docs if it is possible, like when using an ORM or query builder to only update specified columns.

For example if I want to update just one field out of three and I have an object or an array with values:

`{ name: 'Foobar' }`

Full query:
`const query = 'UPDATE product SET (name, sku, description) = ($1, $2, $3) WHERE product_id = $4 RETURNING *'`

Is there a way to make the field names and values dynamic so I can only update the name field?

`const query = 'UPDATE product SET (name) = ($1) WHERE product_id = $2 RETURNING *'`

I am forced to pass every value even those I do not wish to change.

**Comment by charmander** [comment]
Not really. I’d use a query builder for this type of query even if not others.

**Comment by lokeshchoudhary-lc** [comment]
@Zyles  hey did you find a way to do it can you help with the code

**Comment by brianc** [comment]
```js
const namesToUpdate = ['name', 'sku']
if (updateDescription) {
  namesToUpdate.push('description')
}
const query = `UPDATE product SET (${namesToUpdate.join(', ')}) = (${namesToUpdate.map((_, i) => '$'+(i+1)).join(', ')) WHERE product_id = $${namesToUpdate.length +1}`

```

something like that should do it

**Comment by Zyles** [comment]
@lokeshchoudhary-lc 

I switched to Knex since I ran into more issues like this which essentially forces me to build my own query builder in the end.

In Knex it is simple:

```
const updateProductData = { name: "Foobar" }

const queryResult = await this.knex('product').update(updateProductData).where('sku', sku).returning('*')
```

**Comment by lokeshchoudhary-lc** [comment]
@Zyles  thanks for the knex code .
so how did you write your own query builder , can I get some suggestions/advice on how to do that.
Some code example..🙂

**Comment by Zyles** [comment]
@lokeshchoudhary-lc I didn't because it was a waste of time. I used https://github.com/knex/knex

**Comment by lokeshchoudhary-lc** [comment]
@brianc  Your solution worked , but it has only one problem , say like when i feed in two paramaters like name and dob it work , and gives a query like this 
UPDATE users SET (name,dob) = ($1, $2) WHERE user_id = $3 ,
 but when i only want to update the name it gives this type of query
 UPDATE users SET (name) = ($1) WHERE user_id = $2 , 
and it doesn't work , and give an error like this

"source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression"

do you have any solution to this

**Comment by charmander** [comment]
@lokeshchoudhary-lc Add `ROW`:

```js
const query = `UPDATE product SET (${namesToUpdate.join(', ')}) = ROW (${namesToUpdate.map((_, i) => '$'+(i+1)).join(', ')) WHERE product_id = $${namesToUpdate.length +1}`
```

Or with the id as the first parameter:

```js
const query = `UPDATE product SET ${namesToUpdate.map((col, i) => `${col} = $${2 + i}`)}) WHERE product_id = $1`
```
