### ISSUE TITLE
How to update multiple keys all in one query?

### ISSUE THREAD

**Issue by webb24h** [brianc/node-postgres#2562]
I have a database table with json_b
`id | info(json_b)`

I'm trying to update the table with node with parameterized query but terminal returns this error
`error: syntax error at or near "dob"`

How can I do this update in one query?

This is my query
```
var fname = JSON.stringify(data.first_name);//John
var lname = JSON.stringify(data.last_name);//Doe
var dob = JSON.stringify(data.dob);//1899-01-01
var userid = JSON.stringify(data.userid);//66

const text = "UPDATE users set info = info || '{'dob': '"+dob+"', 'first_name': '"+fname+"', 'last_name': '"+lname+"'}' WHERE id=$1 RETURNING*";
const values = [userid];

pool.query(text, values, (err, res) => {

if (err) {

//log errors
console.log(err.stack);

//return error to client

} else {

//success update 
console.log(res.rows);

}
});
```

**Comment by boromisp** [comment]
Take a look at `jsonb_build_object` here: https://www.postgresql.org/docs/current/functions-json.html.

Or alternatively `... SET info = info || $1::jsonb ...` if you can construct the json object in javascript.

**Comment by webb24h** [comment]
> Take a look at `jsonb_build_object` here: https://www.postgresql.org/docs/current/functions-json.html.
> 
> ```js
> pool.query(`UPDATE users SET info = info || jsonb_build_object(
>     'dob', $1, 'first_name', $2, 'last_name', $3
>   ) WHERE id = $4`,  [data.dob, data.first_name, data.last_name, data.userid],
> );
> ```
> 
> Or alternatively `... SET info = info || $1::jsonb ...` if you can construct the json object in javascript:
> 
> ```js
> pool.query(
>   "UPDATE users SET info = info || $1::jsonb WHERE id = $2", 
>   [JSON.stringify({dob: data.dob, first_name: ...}), data.userid],
> );
> ```

With your second query 
```
pool.query(
"UPDATE users SET info = info || $1::jsonb WHERE id = $2 RETURNING*", 
[JSON.stringify({dob: data.dob, first_name: data.first_name, last_name: data.last_name}), userid], (err, res) => {});
```
How do you update second-third level keys? Updating the address for instance?

This is what the json looks like
```
{
'dob' :'',
'first_name': fname,
'last_name': lname,

'address' : {
'timezone' : '',
'door_number': '',
'street': '',
'appt': '',
'city': '',
'state_province': '',
'zip_postal_code': '',
'country': '',
}
}
```

**Comment by boromisp** [comment]
This is more of a generic PostgreSQL question, not related to the nodejs driver.

https://www.postgresql.org/list/
https://dba.stackexchange.com/questions/tagged/postgresql+json
https://stackoverflow.com/questions/tagged/postgresql+json

If you just want to change the city, ` jsonb_set` or `jsonb_set_lax` might be what you are looking for (https://www.postgresql.org/docs/current/functions-json.html):

```sql
info = jsonb_set(info, '{address,city}', $1::text)
```

If you want to "deep merge" the values, then you have to merge the address separately:

```sql
info = info || $1::jsonb || jsonb_build_object(
  'address', info -> 'address' || $1::jsonb -> 'address',
)
```

**Comment by webb24h** [comment]
> This is more of a generic PostgreSQL question, not related to the nodejs driver.
> 
> https://www.postgresql.org/list/
> https://dba.stackexchange.com/questions/tagged/postgresql+json
> https://stackoverflow.com/questions/tagged/postgresql+json
> 
> If you just want to change the city, ` jsonb_set` or `jsonb_set_lax` might be what you are looking for (https://www.postgresql.org/docs/current/functions-json.html):
> 
> ```sql
> info = jsonb_set(info, '{address,city}', $1::text)
> ```
> 
> If you want to "deep merge" the values, then you have to merge the address separately:
> 
> ```sql
> info = info || $1::jsonb || jsonb_build_object(
>   'address', info -> 'address' || $1::jsonb -> 'address',
> )
> ```

Yes I do know how to change single values on a second-third level with postgres. I'm not that of a noob. That's not the question. The question is how to do this with multiple values all at once in one single query like in your second query?
