### ISSUE TITLE
Cannot use param(s) in CREATE VIEW query

### ISSUE THREAD

**Issue by alxndrsn** [brianc/node-postgres#2563]
`pg` version: `8.6.0`

When trying to create a view with a parameterised prepared statement, an error is thrown:

```
> pool.query(`CREATE VIEW views_view_${Math.floor(Math.random()*1000000)} AS SELECT * FROM information_schema.views WHERE table_schema=$1`, [ 'information_schema' ]).then(console.log).catch(console.error);
Promise { <pending> }
> error: bind message supplies 1 parameters, but prepared statement "" requires 0
...
```

When executing the same query, but with params hardcoded, everything seems OK:

```
> pool.query(`CREATE VIEW views_view_${Math.floor(Math.random()*1000000)} AS SELECT * FROM information_schema.views WHERE table_schema='information_schema'`).then(console.log).catch(console.error);
Promise { <pending> }
> Result {
  command: 'CREATE',
...
```

**Comment by sehrope** [comment]
This is not a driver issue. Views cannot have parameters. They need to have all values inlined as literals.

If you're building this on the fly then consider something like pg-format to handle escaping the values for direct inclusion in the SQL: https://www.npmjs.com/package/pg-format

If you do you actually want something like a parameterized view, PostgreSQL has fantastic support for functions and using `LANGUAGE SQL` for the function allows it to be inlined in other queries similarly to how views are optimized: https://wiki.postgresql.org/wiki/Inlining_of_SQL_functions#Inlining_conditions_for_table_functions

**Comment by alxndrsn** [comment]
@sehrope thanks for clarifying :slightly_smiling_face:
