### ISSUE TITLE
update on conflict 

### ISSUE THREAD

**Issue by kafcioo** [brianc/node-postgres#2571]
Hi I'm trying to write a INSERT statement where on conflict it will just overwrite the record how can I do this ?
I'm using this format to make a query statement 

const text = 'INSERT INTO users(name, email) VALUES($1, $2) RETURNING *'
const values = ['brianc', 'brian.m.carlson@gmail.com']**

**Comment by charmander** [comment]
This is a general PostgreSQL question, not specific to the node-postgres driver.

```sql
INSERT INTO users (name, email) VALUES ($1, $2)
  ON CONFLICT DO UPDATE SET (name, email) = ($1, $2)
  RETURNING *
```

https://www.postgresql.org/docs/current/sql-insert.html
