### ISSUE TITLE
Connecting to databases that don't support SSL

### ISSUE THREAD

**Issue by Badestrand** [brianc/node-postgres#2572]
Hello

In my app I connect to databases where the user supplies the access details and I don't know whether the PG server supports SSL or not.

If I use the "normal" SSL connect (the one from the docs) then I get an error if the server doesn't support SSL. Is there a good way to handle it or should I try with SSL first and if I get the error I try it again but without SSL?

Or is there maybe an option that I can set so the client automatically tries both?

**Comment by charmander** [comment]
It sounds like ideally the user should supply whether it uses SSL. Falling back to non-SSL on failure makes it easy to accidentally break it and defeats its MITM protection.

**Comment by Badestrand** [comment]
Okay, I thought there would be a simpler way. Thanks for the reply!
