### ISSUE TITLE
LIKE SQL causing Break

### ISSUE THREAD

**Issue by kiruthihan10** [brianc/node-postgres#2574]
When passing LIKE condition in query parameter with % causing a syntax error
`SELECT * FROM recipe WHERE name LIKE %$1%;`

This causes,
`error: syntax error at or near "%"`

**Comment by kiruthihan10** [comment]
Alternate route found in this link
[https://stackoverflow.com/questions/19471756/how-to-make-a-like-search-in-postgresql-and-node-js](url)

**Comment by sehrope** [comment]
The '%' needs to part of the parameter or part of a literal string in single quotes: `'%'

You need to either perform the concatenation in SQL:

```sql
SELECT *
FROM recipe
WHERE name LIKE ('%' || $1 || '%')
```

Or have the % be in the parameter value itself:

```js
const name = "some value";
const sql = "SELECT * FROM recipe WHERE name LIKE $1";
const params = ['%' + name + '%'];
return client.query(sql, params);
```
