### ISSUE TITLE
Function with jsonb argument

### ISSUE THREAD

**Issue by rightaway** [brianc/node-postgres#2576]
If you call a function with jsonb argument and pass it a plain string, it throws `invalid input syntax for type json`. You have to call JSON.stringify on the string to make it work. But if you pass a number, boolean or object it works without calling anything. Shouldn't the various types be treated consistently and all of them require JSON.stringify or none of them?

**Comment by charmander** [comment]
Maybe! But the reason it works this way is that pg serializes the values before having any information from PostgreSQL about what the expected types are, so it has to guess. Each JavaScript type maps to multiple PostgreSQL types that are serialized in different ways – it just so happens that the serialization for booleans and numbers is the same between JSON and PostgreSQL text.

In short:

- number and boolean work by coincidence
- object is a convenience
- array and string are ambiguous and not serialized as JSON by default

**Comment by rightaway** [comment]
@charmander How do you pass `'null'::jsonb` as a query argument? `null` in javascript becomes plain `null` not `'null'::jsonb`.

**Comment by charmander** [comment]
@rightaway `"null"` (`=== JSON.stringify(null)`)
