### ISSUE TITLE
Could not find jsonpath variable "1"

### ISSUE THREAD

**Issue by ulvidamirli** [brianc/node-postgres#2577]
This is my query:

`const allPrograms = await pool.query(
            "SELECT id, jsonb_path_query(fee::jsonb, '$[*] ? (@.nationality == $1).amount') AS example FROM items
        ,[\"national\"]);"`

And I get this error:
`Could not find jsonpath variable "1"`

How can I solve it?
I think there should be an option to use anything other than $ sign.

I use PostgreSQL 13.

**Comment by charmander** [comment]
See the example in [the documentation for `jsonb_path_query`](https://www.postgresql.org/docs/current/functions-json.html):

> `jsonb_path_match('{"a":[1,2,3,4,5]}', 'exists($.a[*] ? (@ >= $min && @ <= $max))', '{"min":2, "max":4}')` → `t`

and apply it given that parameters are SQL expressions:

```js
const allPrograms = await pool.query(
    "SELECT id, jsonb_path_query(fee::jsonb, '$[*] ? (@.nationality == $nationality).amount', $1) AS example FROM items",
    [{nationality: ["national"]}]
);
```
