### ISSUE TITLE
How to log queires?

### ISSUE THREAD

**Issue by Unbuttun** [brianc/node-postgres#2580]
Is there any way to log queries, and it's parameter while using this library?

The option provided [here](https://github.com/brianc/node-postgres/issues/433) does not work and is giving types error.

Feature request - maybe an inbuilt logger than can be enabled by simply doing logger:true while initializing the client.

**Comment by brianc** [comment]
There's no currently built in logger.  I recommend [wrapping](https://node-postgres.com/guides/project-structure) the library w/ a small lib in your project so you can handle various things in whichever way is best suited to your project.  Node doesn't really have a standard "blessed" logger & I'd rather not add any overhead to the lib by logging things.  There are also _potential_ security concerns around logging query text (and/or parameters) as they can contain sensitive information so it's something best left up to user space code to handle!  You can also monkey patch the query method on the client instance if that's how you like to roll.
