### ISSUE TITLE
pg-pool Exception

### ISSUE THREAD

**Issue by hartalex** [brianc/node-postgres#2582]
TypeError: client.ref is not a function
at BoundPool._pulseQueue (../node_modules/pg-pool/index.js:140:14)

I'm using pg@8.6.0 which, as of today, now installs pg-pool@3.4.0

**Comment by brianc** [comment]
That's unfortunate - AFAIK there's no way to retroactively update the old package to have it use the older version of pg-pool.  I suggest you either upgrade `pg` to `8.7.0` or add `pg-pool@3.3.0` to your package.json.  I can patch `pg-pool` to not blow up if that method is missing as well.

**Comment by charmander** [comment]
@brianc Might want to unpublish pg-pool@3.4.0 and publish it as pg-pool@4.0.0, with the appropriate `peerDependencies` change?

**Comment by brianc** [comment]
I'm patching pg-pool w/ semver patch to only call ref if it exists, so it'll maintain backwards compat w/ version mismatch.  I'll be more careful about about the semver in the peerDeps in the future (I think a peerDep mismatch would still only throw a warning message out though, yeh?)

**Comment by brianc** [comment]
k released new semver patch of pg-pool which should work with much older versions of pg - sorry about that!

**Comment by maxime-lenne** [comment]
Thanks !
