### ISSUE TITLE
Error: client.ref is not a function 

### ISSUE THREAD

**Issue by ellagwithington** [brianc/node-postgres#2584]
Hello, 
We use pg in our project, which has a pg-pool dependency such that every time we build a new docker container, it gets the latest version of pg-pool. This afternoon, when running a new container, it appears that the addition of the ref method in "Allow Node to exit if the pool is idle (#2568)" seems to be causing the project to fail with no changes to our code.  In cloud run I get this error:
![screen_shot_2021-07-27_at_3 29 21_pm](https://user-images.githubusercontent.com/85177653/127232716-91446f43-0971-4191-bb12-496acb05d06c.png)

https://github.com/brianc/node-postgres/blob/684cd09bcecbf5ad5f451fdf608a3e9a9444524e/packages/pg-pool/index.js#L140
There is no way to default to an earlier version of pg-pool within the project, so I was hoping I could get some help fixing this issue. 
Thank You!

**Comment by brianc** [comment]
yeah...sorry about that

https://github.com/brianc/node-postgres/issues/2582
https://github.com/brianc/node-postgres/pull/2583

should have a fix out in a few min

**Comment by fluggo** [comment]
@brianc Didn't the pg-pool package depend on the version of pg with the ref/unref methods added?

**Comment by brianc** [comment]
@fluggo kinda - pg-pool doesn't depend on pg, pg depends on pg-pool (i know...) and pg's dep allows semver minor floating.  So if you have an old version of pg installed at exactly `8.6` it'll install the latest semver minor `pg-pool` which requires `client.ref` to exist.  Kinda weird peer dependency issue.  Publishing a new semver patch of pg-pool will make it work w/ older versions of node-postgres.

**Comment by ellagwithington** [comment]
Thanks!

**Comment by brianc** [comment]
thank _you_ for your patience! Takes a bit to push a patch because i wait for tests to run

**Comment by brianc** [comment]
k released new semver patch of pg-pool which should work with much older versions of `pg` - sorry about that!
