### ISSUE TITLE
client.ref is not a function

### ISSUE THREAD

**Issue by KenSuenobu** [brianc/node-postgres#2585]
Using version 3.4.1:

```
TypeError: client.ref is not a function
    at BoundPool._pulseQueue (/opt/cc-server/node_modules/pg-pool/index.js:140:14)
    at /opt/cc-server/node_modules/pg-pool/index.js:176:37
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by KenSuenobu** [comment]
This code has left us in a horribly broken state.  Please advise if there's a fix coming.  Thanks!

**Comment by brianc** [comment]
what version of pg do you have installed?

**Comment by brianc** [comment]
I just tested this with this setup:

package.json
```json
{
  "name": "testing",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "pg": "8.5.0",
    "pg-pool": "3.4.1"
  }
}
```

index.js
```js
const pg = require("pg");

const pool = new pg.Pool();

pool.query("select now()").then(() => pool.end());

```

Also tried with pg@8.6 and pg@8.7 - everything works fine for me.

**Comment by KenSuenobu** [comment]
Yeah, looks like it was an issue with our install.  Some dependency was using an older pool library.  We used a different approach, and it's working fine now.  False alarm!

**Comment by brianc** [comment]
good to hear! thanks!
