### ISSUE TITLE
App won't start in engine unix when using node-postgres

### ISSUE THREAD

**Issue by janliska** [brianc/node-postgres#2590]
Hi guys,

I'm having issues starting application when using [nginx unit](http://unit.nginx.org/).
Container starts but it ends in loop of `/usr/local/bin/docker-entrypoint.sh: Waiting for control socket to be removed...` and it never finishes.
When I remove the postgres client all works well. I've tried to close the client connection on sigterm but with no luck.

Did anybody meet the same issue?

I've prepared simple demo app to reproduce the issue: https://github.com/janliska/pgsql-nginx-unit-issue

**Comment by brianc** [comment]
looks like your app (in your example repo at least) is establishing a single postgres connection & never closing it.  

you might want to try passing `allowExitOnIdle` to the pool:

```
const pool = new pg.Pool({ allowExitOnIdle: true })
```
or set a very short `idleTimeoutMillis` on the pool & use a connection pool for this.  That way connections will be closed gracefully if they're not in use, allowing for a "clean" exit.

**Comment by janliska** [comment]
I've tried to close the client connection on sigterm (actually not only sigterm, also signint, exit and bunch of others), but it didn't help. It is not in the repo, but I tried something like `process.on('SIGTERM', () => client.close());`.

But I'll try the pool, thanks for tip :-)

**Comment by brianc** [comment]
@rightaway  https://github.com/brianc/node-postgres-docs/pull/151

**Comment by brianc** [comment]
closing unless I hear something else - @janliska hope you got everything worked out on your end!
