### ISSUE TITLE
How to provide values of complex types to parameterized statements?

### ISSUE THREAD

**Issue by Quelklef** [brianc/node-postgres#2594]
For instance, how can I use `node-postgres` to execute the parameterized statement `SELECT $1::circle[]` with the value `ARRAY[ '<(0, 0), 1>'::circle ]` assigned to `$1`?

None of the following work:

- `client.query('SELECT $1::circle[]', [ [{ x: 0, y: 0, radius: 1 }] ])`
- `client.query('SELECT $1::circle[]', ['{ <(0, 0),1> }'])`
- ``client.query('SELECT $1::circle[]', [`'{ <(0,0),1>'::circle }`])``
- ``client.query('SELECT $1::circle[]', [`ARRAY[ '<(0,0),1>'::circle ]`])``

All fail with `error: invalid input syntax for type circle: "<(0"` or similar.

**Comment by Quelklef** [comment]
Oh, MWE:

```javascript
(async () => {
  const pg = require('pg');
  const client = new pg.Client();
  await client.connect();

  const attempts = [
    { x: 0, y: 0, radius: 1 },
    '<(0, 0),1>',
    `'<(0,0),1>'::circle`,
    `ARRAY[ '<(0,0),1>'::circle ]`,
  ]

  for (const attempt of attempts) {
    try {
      await client.query('SELECT $1::circle[]', [attempt]);
    } catch (e) {
      console.log(e + '');
    }
  }

  await client.end();
})();
```

**Comment by Quelklef** [comment]
I've been playing with `node-postgres` and poking through the codebase for a little while.

1. If I'm not mistaken, a call like `client.query(q, [v])` will send the strings `q` and a stringified version of `v` over to Postgres to handle.
2. And it *seems*, based on my investigations so far, that Postgres requires that the parameter values strings (i.e., `v`) are literal-syntax only. I'm not positive about this, though.
3. Unfortunately, I think that literal syntax doesn't *exist* for `circle[]`. As far as I can tell, a `circle` literal must be written using `'data'::type` form (or similar), but array literals don't support this syntax for their elements (try `SELECT $${}$$::int[]` vs `SELECT $${ '1'::int }$$::int[]`).

If these three are all true, then providing a `circle` as a query parameter in `node-postgres` is impossible. This would be extremely unfortunate, and also pretty surprising.

Do you have any thoughts on this?

**Comment by Quelklef** [comment]
Ah, I think I found the relevant part of the PostgreSQL protocol documentation. In [48.2.3](https://www.postgresql.org/docs/9.3/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY) (Extended Query):

> Parameter data types can be specified by OID; if not given, the parser attempts to infer the data types in the same way as it would do for untyped literal string constants.

One way I can think to fix this is for `node-postgres` to implement prepared statements by actually using `PREPARE` and `EXECUTE`...

```
y=> prepare q as select $1::circle[];
PREPARE
y=> execute q( ARRAY[ '<(0,0),1>'::circle ] );
    circle
---------------
 {"<(0,0),1>"}
(1 row)
```

... but I don't want to get ahead of myself.

**Comment by sehrope** [comment]
The data type is only specified once as an array type. Not once for each value in the array. Array literals of complex types are possible but you have to escape the inner commas of the complex types text representation:

```
postgres=# SELECT '{<(0\,0)\,1>,<(0\,0)\,2>}'::circle[];
          circle           
---------------------------
 {"<(0,0),1>","<(0,0),2>"}
(1 row)
```

See here for details on escaping array literals: https://www.postgresql.org/docs/current/arrays.html#ARRAYS-IO

You can use that same literal value as a query parameter. You'll still need to add the cast to the parameter usage, i.e. "SELECT $1::circle[]` to indicate the type.

**Comment by Quelklef** [comment]
Holy shit, thank you so much! Seriously, I've spent hours on this, and you've solved it in a single sentence. Thank you.

**Comment by charmander** [comment]
To be clear, this should work too:

```sql
client.query('SELECT $1::circle[]', [['<(0,0),1>']])
```
