### ISSUE TITLE
How to add $1 into json path in the query?

### ISSUE THREAD

**Issue by ulvidamirli** [brianc/node-postgres#2598]
This is the query I am using:

    app.get("/items/:data", async (req, res) => {

        const { data } = req.params;

        query = `
            SELECT items.discount
            FROM items
            WHERE items.discount @? '$[*] ? (@.discount[*].shift == $1)'
            `
        try {

            const obj = await pool.query(query, [data]);
            res.json(obj.rows[0])

        } catch(err) {

            console.error(err.message);

        }
    });

I get this error:

    error: bind message supplies 1 parameters, but prepared statement "" requires 0

How can I solve this issue?

**Comment by charmander** [comment]
I don’t know if there’s a cleaner way to build jsonpath values, but this filter:

```sql
WHERE items.discount @? $1
```

and this parameter value:

```js
`$[*] ? (@.discount[*].shift == ${JSON.stringify(data)})`
```

are the general idea of an approach that should work.

**Comment by ulvidamirli** [comment]
Thank you for your solution. Does this approach has any `SQL injection` vulnerability? For example, `SQL injection` in `JSON path`. The value (`$1`) is coming from the client.

**Comment by charmander** [comment]
Not if you remember to use `JSON.stringify` where jsonpath expects JSON. (And it’d be jsonpath injection instead of SQL injection, which is bad – allows arbitrary queries against your column – but not nearly *as* bad.)
