### ISSUE TITLE
Novice Developer request: Add back promises portion of documentation

### ISSUE THREAD

**Issue by stephepush** [brianc/node-postgres#2603]
Hi, 
I'm more of a novice developer and I worked with Node-postgres a couple of years ago and was really impressed with it. I have been trying to get my mind around async await, but it's been a real struggle. I was pretty sure that I used regular promises the first time I made a tiny project using this driver, and looked on the wayback machine to previous versions of the documentation and there were portions of documentation dedicated to using regular promises. Could those portions make a return? Or is there a reason why they disappeared? 

Thanks

**Comment by charmander** [comment]
async/await is regular promises. The node-postgres API hasn’t changed in that respect; the examples just use the returned promises differently. Translations of those examples to manual `.then` is something novice developers are rarely going to want, but you don’t need to understand anything pg-specific to do it; it’s a fundamental part of Node.

**Comment by stephepush** [comment]
Async/Await is syntactical sugar added on to promises that I really don't need if I or others are still learning promises, but I guess adding a third example (that were seemingly previously deleted) for those who don't need to be bogged down with that sugar while simply trying to build a project isn't what a novice would need. This is a shame imo rare opinion.
