### ISSUE TITLE
Update/Insert over multiple clients with transactions hangs

### ISSUE THREAD

**Issue by crxo** [brianc/node-postgres#2605]
Firstly, thank you for this amazing package!

When I run the following snippet on my machine, it hangs on the UPDATE statement (prints up to "3" and then never continues). Note that it doesn't exit, just doesn't resolve the UPDATE.

**Node version:** v16.8.0 (Mac OS 11.5.1 20G80)
**PostgreSQL version:** 13.4 (via Docker)
**pg version:** 8.7.1

```js
const pg = require("pg");

async function main() {
  console.log("**STARTED**");

  const pool = new pg.Pool();
  const outerClient = await pool.connect();
  const innerClient = await pool.connect();

  await outerClient.query("BEGIN");
  console.log(1);
  await outerClient.query(
    `INSERT INTO "people" ("id", "name") VALUES (1, 'John') ON CONFLICT ("id") DO UPDATE SET name = 'John'`
  );
  console.log(2);
  await innerClient.query("BEGIN");
  console.log(3);
  await innerClient.query(`UPDATE people SET name = 'Toby' WHERE id = 1`);
  console.log(4);

  console.log("**FINISHED**");
  return true;
}

main();
```

```sql
create table people (
  id integer,
  name text not null,
  primary key (id)
);

insert into people (id, name) values (1, 'Frank');
```

As you can see, there are two clients `outerClient` and `innerClient`. My assumption would be that the the INSERT and UPDATE shouldn't affect each other since they are on different connections in different transactions.

I've probably got this completely wrong :) But any assistance would be much appreciated. Thanks again for the great work!

Let me know if I can provide more information.

**Comment by boromisp** [comment]
Query `pg_locks` with `WHERE NOT granted` condition to check if the inner query is waiting on the transaction of the outer query to end.

**Comment by crxo** [comment]
> Query `pg_locks` with `WHERE NOT granted` condition to check if the inner query is waiting on the transaction of the outer query to end.

That's it. How did I miss that!! :|

Thanks so much @boromisp
