### ISSUE TITLE
PGSSLMODE=no-verify is not equivalent to { ssl: { rejectUnauthorized: false } }

### ISSUE THREAD

**Issue by aboqasem** [brianc/node-postgres#2607]
My app only works with `PGSSLMODE=no-verify` and not `{ ssl: { rejectUnauthorized: false } }`.

Otherwise it will err with: `no pg_hba.conf entry for host...`.

Is this the expected behavior?

```shell
"pg": "^8.7.1",
"typeorm": "^0.2.37",
"@nestjs/typeorm": "^8.0.2"
```

**Comment by charmander** [comment]
What’s the full error and full configuration?

**Comment by aboqasem** [comment]
Thank you for your response, while trying to reproduce the issue I noticed that the problem is with the session not the DB, the connection of the session was not secured that is why 😅. Sorry!

**Comment by aboqasem** [comment]
@sryze did you make sure the session's connection is also secure?

```ts
import connectPg from 'connect-pg-simple';
import expressSession from 'express-session';

const PgStore = connectPg(expressSession);

export const session = expressSession({
  // ...
  store: new PgStore({
    // ...
    conObject: {
      // ...
      ssl: /* should be same as ConnectionConfig.ssl */,
    },
  }),
});
```

**Comment by aboqasem** [comment]
From [docs](https://www.postgresql.org/docs/current/libpq-connect.html):

```
postgresql://[userspec@][hostspec][/dbname][?paramspec]
```

Try adding `?sslmode=no-verify` at the end of the URI, which is equivalent to the above.

```ts
const db = pgp(`${process.env.DATABASE_URL}${process.env.DATABASE_SECURE === "true" ? '?sslmode=no-verify' : ''}`);
```
