### ISSUE TITLE
Connection pool exhausted

### ISSUE THREAD

**Issue by klippas-rob** [brianc/node-postgres#2613]
In a Microsoft Teams bot, each INSERT is leaving and idle connection - UPDATE/DELETE/SELECT are not.
After client.release(), pool.totalCount and pool.idleCount are both 0.

INSERT/UPDATE/DELETE use a common function that gets a connection, performs the query, and releases the connection, within a BEGIN/COMMIT/ROLLBACK transaction.

Using this:
```SELECT count(*),state FROM pg_stat_activity GROUP BY 2;```

Postgres returns this before the app is launched:

```
 5       NULL, 
 1       active
```

After the app is launched:

```
 5       NULL, 
 1       active
 1       idle
```

After insert brianc/node-postgres-docs#1

```
 5       NULL, 
 1       active
 2       idle
```

After insert brianc/node-postgres-docs#2, etc.

```
 5       NULL, 
 1       active
 3       idle
```

Taking the same code and using it in a simple test program, it works, returning the connection after each INSERT.
I'm at a loss as to how to solve this.

Thanks in anticipation of your help.

**Comment by charmander** [comment]
There's probably a bug in your code, and it's very hard to be more specific about where that might be other than the obvious of some pool operation being involved. Maybe show the common routine? Most of all, though, keep trying at that test program – you should always be able to reduce an application down to a minimal reproduction by removing one thing at a time.

**Comment by klippas-rob** [comment]
You were correct - user error.
