### ISSUE TITLE
How to integrate express with postgres?

### ISSUE THREAD

**Issue by TheMrHabibi** [brianc/node-postgres#2615]
I want to use the same pool object on different javascript files. For example:
I have the main pg-pooler connection file:
```js
// db.js
const { Pool } = require('pg')
const pool = new Pool({ /* ... */ })

module.exports = pool
```

Then, i want to load in my controller file:
```js
// index.controller.js
const pool = require('../db.js') // load the pooler file

module.exports = (req, res) => {
  pool.query() // query using the pool object
  // ...
}
```

The **PROBLEM** is: I want to use the same pool object without recreating it in another controller file:
```js
// user.controller.js
const pool = require('../db.js') // i dont want to recreate the new pool object, but i want to use the same object as index.controller.js uses

module.exports = (req, res) => {
  pool.query() // query using the same pool object as index.controller.js
  // ...
}
```

Anyone can help me? The summary is: **I want to use the same pool object on different controller files**.

**Comment by brianc** [comment]
https://node-postgres.com/guides/async-express
