### ISSUE TITLE
Variable 'PG' implicitly has type 'any' in some locations where its type cannot be determined.ts(7034)

### ISSUE THREAD

**Issue by a4khalaf** [brianc/node-postgres#2616]
```node-postgres``` working completely fine when file type is ```.js``` but when it's ```.ts``` it gives me this error

`Variable 'PG' implicitly has type 'any' in some locations where its type cannot be determined.ts(7034)`

**Comment by brianc** [comment]
Hey @a4khalaf - couple things:

1) This is most likely related to your consumption/usage of pg or the way typescript is set up in your project.  I use typescript almost exclusively at work & haven't run in to this issue.  

2) Without seeing multiple files from your project and your typescript config this will be nearly impossible to debug.

3) I don't (currently, though I plan to in the future) maintain the type definitions for the core `pg` module, and this is an issue related to the type definitions, not the driver behavior itself.

Hopefully you got this figured out - don't hesitate to stop by in the future if you run into anything else; hopefully I can be of more help then!
