### ISSUE TITLE
How to send the result and not the Promise <pending> to req.on('data', ... ?

### ISSUE THREAD

**Issue by blaasvaer** [brianc/node-postgres#2621]
I'm trying to get some db data on a request and send it as part of the response.

I'm using the:

```
	req.on('data', ( chunk ) => {
		body += chunk;
	});

	req.on('end', () => {
		controller.addBody( body );
	})
```
approach – never mind the controller.addBody() part, it's just the way I do it with my controllers – and send the response using:

```
res.end( string );
```

When I (in my controller functions) do:
```
return JSON.stringify({
	'stuff' : 'here'
});
```
it works just fine.

But when I do:
```
model.get('resources')
.then( ( result ) => {
	return JSON.stringify( result );
});
```
I can log the output just fine ... it's just that now I return a promise to the req.on('data', ... ) instead of a string or buffer.

How can I make a request wait for async data calls when using pg?

I've found myself sprinkling async/await all over the place ... kind of losing track of what's going on. I guess it's a simple solution, I just can't wrap my head around it in this context.

**Comment by blaasvaer** [comment]
Well, seemed the 'solution' was to turn the complete requestHandler (yeah, the function you pass to http.createServer ... ) into an async function, so I could add await in front of the calling method for the response:

`response_output = await controller.route.action();`

To be honest, I'm not to fond of the async/await syntactical sugar ... it makes things harder to read – I guess it 'hides' to much under the hood to make things readable. Now I've just added a bit of async/await here and there and ... voilà. Well, that's definitely not the 'feeling' I get when doing this ...

**Comment by sehrope** [comment]
This is a generic express / async question. It's not related to this driver.

There is an example of using the pg driver with express with async/await on the docs site: https://node-postgres.com/guides/async-express

You can also search for "express async await" and there's plenty of guides explaining how to structure your project.

**Comment by blaasvaer** [comment]
Thanks. Don’t know why you claim this is Express (it’s not). But anyway, you’re right it’s not the lib ... I did figure it out in the end.
