### ISSUE TITLE
node-pg tries to parse my semantic version string to a date/time

### ISSUE THREAD

**Issue by Prophet32j** [brianc/node-postgres#2626]
I'm getting a `DateTimeParseError` trying to execute a parameterized query. Here is my error stack:

```
"error: date/time field value out of range: \"8.0.3\"",
        "    at Parser.parseErrorMessage (/var/task/node_modules/pg-protocol/dist/parser.js:287:98)",
        "    at Parser.handlePacket (/var/task/node_modules/pg-protocol/dist/parser.js:126:29)",
        "    at Parser.parse (/var/task/node_modules/pg-protocol/dist/parser.js:39:38)",
        "    at TLSSocket.<anonymous> (/var/task/node_modules/pg-protocol/dist/index.js:11:42)",
        "    at TLSSocket.emit (events.js:314:20)",
        "    at TLSSocket.EventEmitter.emit (domain.js:483:12)",
        "    at addChunk (_stream_readable.js:297:12)",
        "    at readableAddChunk (_stream_readable.js:272:9)",
        "    at TLSSocket.Readable.push (_stream_readable.js:213:10)",
        "    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)"
```

Here is the relevant SQL for the query:
```sql
SELECT
    model_id,
    version_timestamp
  FROM model_version
  WHERE 
    model_id=$1
  AND
    version_number=$2
```

Here is the relevant code:
```javascript
const results = await client.query(sql.selectModelByVersion, [ id, versionNumber ])
```

The `version_number` column is a string, and the `versionNumber` argument is a string with the value `8.0.3`

It appears to be that the library is improperly evaluating the parameter as a Date or Timestamp, and that's what is causing the error. Is `pg.types` also responsible for parsing input values?

Any help would be appreciated.

**Comment by sehrope** [comment]
That error is coming from the PG server, not this driver. It's happening because the server is trying to transform the text value of the parameter into the data type to which it's being assigned:

```
=> SELECT '8.0.3'::timestamptz;
ERROR:  date/time field value out of range: "8.0.3"
LINE 1: SELECT '8.0.3'::timestamptz;
```

Check your SQL to ensure that the WHERE clause is indeed referencing the "version_number" field and not the "version_timestamp" one. The data type of that "version_number" field could also be wrong.

**Comment by Prophet32j** [comment]
Thanks for the timely feedback. If it is the server that's doing it, how can I get it to correctly transform the value? The column is type `text`

Here's the full SQL:
```sql
WITH model_version AS (
  SELECT
    model_id,
    version_timestamp
  FROM data_registry.model_version
  WHERE 
    model_id='xyz'
  AND
    version_number='8.0.3'
)
SELECT 
  m.model_id as "modelId",
  m.model_name as "modelName",
  m.description,
  m.owning_area as "owningArea",
  m.comment_text as "commentText",
  m.system_start_time as "startTimestamp",
  m.system_end_time as "endTimestamp"
FROM data_registry.model m
JOIN model_version mv ON m.model_id=mv.model_id
WHERE 
  m.model_id='xyz'
AND
  m.system_start_time<=mv.version_timestamp
AND
  m.system_end_time>=mv.version_timestamp
ORDER BY m.system_end_time DESC
LIMIT 1
```

This query works perfectly fine within pgAdmin. The only difference is that here I'm manually adding the params

If I do this `version_number='8.0.3'::timestamptz` I get the same error you get.

If I do this `version_number='8.0.3'::text` I get a good results **within pgAdmin**. The same error exists within my node code.

Is there no way around this?

**Comment by sehrope** [comment]
What is the data types of the tables involved?

What is the actual JS code that's executing the query?

**Comment by Prophet32j** [comment]
it turns out this specific SQL query wasn't the problem, and we didn't know that until we added some additional logging around the error to see it was a different GraphQL resolver giving us trouble.

The server correctly assigns the value as a text, not a date/time.

Closing.
