### ISSUE TITLE
pg.pool on error

### ISSUE THREAD

**Issue by spambas** [brianc/node-postgres#2641]
I have a pool with max 20 clients with an error handler:

```javascript
pool.on('error', (err, client) => {
  console.error('Unexpected error on idle client', err)
})
```
which gives me nice errors like : **Unexpected error on idle client { Error: Connection terminated unexpectedly** 
and then a stack trace

I cannot find out what happens now. 

- will the client just stop? is the pool destroyed?
- will it restart as needed?
- will the query the client was handling be put back in the pool or is it lost? 
- if it is not put back in the pool, can I get it from the client object parameter?
- do I need to recreate the pool?
- if so, can I list what queries are in the pool to cache them before starting a new pool?

**Comment by brianc** [comment]
> * if so, can I list what queries are in the pool to cache them before starting a new pool?

You don't need to do this - if a query is active the client itself will callback or reject with an error.  The only time the pool will emit an error is when something like an idle, connected client suddely loses connection unexpectedly from the backend.  Example: start postgres. start a node app w/ the pool. Send a few queries to prime some connected clients in the pool. Shut down postgres abruptly.  Those connected clients in the pool will cause the pool to emit an error for each client.  FWIW I generally add something like this in my apps:

```
pool.on('error', (err) => {
  logger.fatal('pg.Pool emitted error', err)
  process.exit(-1)
})
```

Usually it means something unexpected & unplanned for has happend & it's really difficult to have a clean way to recover, so I just let the process die & the cluster manager or k8s runtime or whatever is keeping my node processes alive will start a new one.

**Comment by spambas** [comment]
I understand. 

I do not want to kill the process but buffer the queries (i have machines posting log data with not a lot of buffer space) and give the machines an ACK so they can move on. 

When the DB is back up I can send the buffered queries afterwards but I need to know what to do when the db goes away. 

It seems I do not have to do anything. 
The clients will re-emerge when needed. 

I had a feeling this is what happened but I could not find it anywhere so I opened an issue in the node-postgres-docs. It was transferred here for some reason. 

One thing that is not clear yet: when the database is down and all 20 clients are dead; then I do a pool.query while the db is still away, who catches the client that did not connect, is that the pool.query or the pool.on(error). in case of the latter, can I find our what the query was. or is it a timeout somewhere?
