### ISSUE TITLE
array json (valid json) not supported by parser

### ISSUE THREAD

**Issue by doug-two** [brianc/node-postgres#2649]
hi!

i recently come to this issue, when i try to insert the following value in a jsonb field

 `[{ name: 'Bicentennial man', age: 200, alive: true }]`

i got the following error:
```
error: invalid input syntax for type json
    at Parser.parseErrorMessage (/Users/douglasgrillet/git/node-postgres/packages/pg/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/douglasgrillet/git/node-postgres/packages/pg/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/douglasgrillet/git/node-postgres/packages/pg/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/douglasgrillet/git/node-postgres/packages/pg/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:376:20)
    at addChunk (node:internal/streams/readable:305:12)
    at readableAddChunk (node:internal/streams/readable:280:9)
    at Socket.Readable.push (node:internal/streams/readable:219:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:192:23)

```

This is perfectly valid json, can be tested in javascript:
```
let x = [{ name: 'Bicentennial man', age: 200, alive: true }]
let y = JSON.stringify(x)
console.log(y)
console.log(JSON.parse(y))
```

Also: this query works on the postgresql console:
```
CREATE TEMP TABLE stuff(id SERIAL PRIMARY KEY, data JSONB);
INSERT INTO stuff (data) VALUES ('[{ "name": "Bicentennial man", "age": 200, "alive": true }]'::jsonb);
```

i modified the test case to:  (packages/pg/test/integration/client/json-type-parsing-tests.js)
```
'use strict'
var helper = require('./test-helper')
var assert = require('assert')

const pool = new helper.pg.Pool()
pool.connect(
  assert.success(function (client, done) {
    helper.versionGTE(
      client,
      90200,
      assert.success(function (jsonSupported) {
        if (!jsonSupported) {
          console.log('skip json test on older versions of postgres')
          done()
          return pool.end()
        }
        client.query('CREATE TEMP TABLE stuff(id SERIAL PRIMARY KEY, data JSONB)')
        var value = [{ name: 'Brian', age: 250, alive: true, now: new Date() }]
        client.query('INSERT INTO stuff (data) VALUES ($1)', [value])
        client.query(
          'SELECT * FROM stuff',
          assert.success(function (result) {
            console.log(result)
            assert.equal(result.rows.length, 1)
            assert.equal(typeof result.rows[0].data, 'object')
            var row = result.rows[0].data
            assert.strictEqual(row.name, value.name)
            assert.strictEqual(row.age, value.age)
            assert.strictEqual(row.alive, value.alive)
            assert.equal(JSON.stringify(row.now), JSON.stringify(value.now))
            done()
            pool.end()
          })
        )
      })
    )
  })
)
```
and it fails.  (it should pass)

for some reason this work:
var value = {0:[{ name: 'Bicentennial man', age: 200, alive: true }]}

however at the moment of insertion i dont know if this json object is an array, so i would like it work like the javascript example.

is this a bug? or is it working as intended?
im assuming is a bug since: 1) its valid JS, and 2) i can insert it into PG as long as i dont use this library.

Im trying to fix it myself,  i thought the problem could be in pg-types, but i wrote the test case there and it pass. 
Im still looking, but some help finding where it could be would be appreciated; Im new here so i dont know my way around.

thanks!

P.S. using 'origin/master'

**Comment by doug-two** [comment]
Hi again!

found it!

in `packages/pg/lib/utils.js` there is this method called `prepareValue` which takes care of converting values from javascript types, and it does it step by step.

The check for an Array type comes prior to the check for Object, and the problem with my query is that it qualify as both Array and Json, and it's treated as an Array just because the check comes first.

I dont think this could be easily handled, since the method cannot read my mind and get what im trying to do, so i guess its not a bug but a limitation.

**Comment by charmander** [comment]
That’s right. You can use `JSON.stringify` to disambiguate:

```js
db.query(…, [JSON.stringify(array)])
```
