### ISSUE TITLE
Just last INSERT in loop executed

### ISSUE THREAD

**Issue by TheDevMen** [brianc/node-postgres#2658]
I have a simple INSERT which is called in a loop. Unfortunately, only the last INSERT is executed, unless I do an `await db.pool.query('COMMIT');` right after the INSERT. But this means I have several commits which makes a rollback useless if something goes wrong. 

Thanks for your help in advance.

**Comment by charmander** [comment]
Code?

**Comment by matthieusieben** [comment]
It seems you are performing your queries on the pool directly, which is not suitable for transactions.

If you need a transaction, you should grab a connection first, and use that to manage your transaction.

```js
const pool = new pg.Pool({ max: 1 })

const client = await pool.connect()
try {
  await client.query('BEGIN')

  for (let i = 0; i < 100; i++) {
    await client.query('INSERT INTO my_table (a) VALUES (1)')
  }

  await client.query('COMMIT')
} catch (e) {
  await client.query('ROLLBACK')
  throw e
} finally {
  await client.release()
}
```

**Comment by TheDevMen** [comment]
Thank you guys! That's the solution!
