### ISSUE TITLE
parseFloat not good for type conversion

### ISSUE THREAD

**Issue by brianc** [brianc/node-postgres#266]
The type conversion for floats should be reexamined.  Making a note here until I have time to look @ it further.  context:

https://gist.github.com/shtylman/4757910

https://twitter.com/defunctzombie/status/301085763188166656

**Comment by dmurvihill** [comment]
Forgive me for being thirteen years late, but shouldn't `real` and `double` be completely fine to parse to JavaScript `number`? Obviously Postgres `Numeric` requires different handling, but `real` and `double` are fully IEEE 754 compliant as are JS numbers.

**Comment by charmander** [comment]
@dmurvihill Yes. They are currently parsed to JavaScript `number`s, aren’t they?

**Comment by dmurvihill** [comment]
Yes, sorry. I must have been looking at old docs.
