### ISSUE TITLE
Not finding newly added tables. 

### ISSUE THREAD

**Issue by doozeeco** [brianc/node-postgres#2669]
Hi, 

I keep getting error that the relation doesn't exist, when it does. For example, I have a collection called Shops. I use the following code to get the data: 

module.exports.getShopByName = async (shopName) => {
    const result = await pool.query('SELECT * FROM "Shops" WHERE name = $1', [shopName]);
    return result.rows[0];
}

But I get the error: relation "Shops" does not exist. It exists in the public schema. 
![Screenshot 2021-12-15 at 21 16 14](https://user-images.githubusercontent.com/26605614/146258722-7c555293-c7ee-4796-bbb0-2b6813229bba.png)

I recently moved the db to AWS RDS, and now the application doesn't read any of the tables. Somehow, it's just not connecting to new tables. It could be something else but this is my understanding of the issue.

**Comment by marcbachmann** [comment]
could you execute `pool.query('SHOW search_path;')` to make sure you're really querying the public schema. `

By default it should be:
```
search_path
-----------------
"$user", public
```
