### ISSUE TITLE
pg and browser

### ISSUE THREAD

**Issue by satrock1** [brianc/node-postgres#2670]
hello i am a beginner js user i have a question.
I have a mapping project (GeoServer) that displays a map with information in a browser. Objects are displayed in the browser and there is a form with data saving. I am currently working with LocalStorage. But I don't need it, since I store data in Postgresql.

Now with the help of "pg" I was able to implement data output from my database in the console.

I need to somehow implement working with the database (adding and editing) through the browser.

I would be very grateful for your help!

**Comment by charmander** [comment]
This sounds outside of the scope of node-postgres issues. You can probably find some relevant tutorials if you look around, though.
