### ISSUE TITLE
Parametrized queries do not support LIMIT ALL

### ISSUE THREAD

**Issue by milesial** [brianc/node-postgres#2673]
When using a query with `LIMIT $1`, with $1 populated with the string `"ALL"`, we get this error

```
invalid input syntax for type bigint: "ALL"
```

According to the doc, that should be supported by PostgreSQL: https://www.postgresql.org/docs/8.1/queries-limit.html

**Comment by sehrope** [comment]
This is not a driver issue, that's how the server works. What you're trying to do is not possible with a query parameter as `ALL` in that context is a keyword and not a literal string `ALL`.

When you specify a parameter in the `LIMIT ...` clause then the server interprets the value of the parameter as a bigint value. There's no way to supply a value that would be the identifier `ALL`.

You'll need to either remove the LIMIT clause in the client code. Alternatively you could specify a gigantic value that will be beyond the max number of rows that could be returned. Though that might cause planning changes compared to removing the clause entirely.

**Comment by milesial** [comment]
Alright, got it, thanks for the explanation. Closing this then.

**Comment by benny-medflyt** [comment]
You can use `LIMIT $1` and pass `null` if you want all the rows

**Comment by yilmazdurmaz** [comment]
> You can use `LIMIT $1` and pass `null` if you want all the rows

this one works, nice. but is it safe?

**Comment by sehrope** [comment]
Yes `LIMIT $1` with a null value to fetch all the rows is supported going back to PostgreSQL server version 8.4: https://www.postgresql.org/docs/8.4/queries-limit.html (released in 2009 and EOL in 2014)
