### ISSUE TITLE
How to pass an array json object to query function

### ISSUE THREAD

**Issue by qieman** [brianc/node-postgres#2675]
I need to call a query function, the type of  'arr'  field  is json, this is my code:

```
const myArr = [1,2,3]
const queryStr = 'SELECT * FROM tableName WHERE arr=$1'
const values = [JSON.stringify(myArr)]

try {
  const result = await client.query(queryStr, values)
} catch (e) {
   console.error(e)
   throw e
}
```
I try to run this code and i got this error:
```
error: Operator does not exist: json = unkonwn
```

How can I fix this issue?

**Comment by marcbachmann** [comment]
theoretically you can coerce the value: `SELECT * FROM tableName WHERE arr=$1::json`

the automatic coercion most likely didn't work because comparing json doesn't work like that in postgres. Please see https://stackoverflow.com/questions/49391212/postgresql-compare-jsons

**Comment by qieman** [comment]
thanks for answer，it works
