### ISSUE TITLE
Adding option to map object to query instead of array based on numeric position

### ISSUE THREAD

**Issue by shadowwarior5** [brianc/node-postgres#2676]
Was ever considered implementing an option to use named attributes and not attributes based on numbers?
Example from sequelize library using named attributes:
```
await sequelize.query(
  'SELECT * FROM projects WHERE status = :status',
  {
    replacements: { status: 'active' },
    type: QueryTypes.SELECT
  }
);
```

Using numeric attributes based on position can be bug-prone, especially for big insert-style queries like this one:

```
const query = {
  text: 'INSERT INTO users(name, email, street_address, phone_number_1,phone_number_2, status) VALUES($1, $2, $3, $4, $5, $6)',
  values: ['brianc', 'brian.m.carlson@gmail.com', 'str', '123', '123', 'active'],
}

client
  .query(query)
  .then(res => console.log(res.rows[0]))
  .catch(e => console.error(e.stack))
```

**Comment by charmander** [comment]
This isn’t decided by the driver in PostgreSQL’s case – see https://github.com/brianc/node-postgres/issues/1720#issuecomment-420052196.
