### ISSUE TITLE
Client has already been connected. You cannot reuse a client

### ISSUE THREAD

**Issue by yaugenka** [brianc/node-postgres#2678]
--main.js
```
const pg = require('./db')

async function start() {
	try {
		await pg.connect()
		await main()
	} catch (e) {
		logPgError(e)
	} finally {
		try {
			await pg.end()
		} catch (e) {
			logPgError(e)
		}
	}
	clearTimeout(timer)
	timer = setTimeout(() => start(), 60000)
}
```

--db.js
```
const { Client } = require('pg');
module.exports = new Client({
	//connection params
});
```

The second iteration throws: Client has already been connected. You cannot reuse a client

**Comment by charmander** [comment]
If there’s an error, you have to create a new `Client` object (with `new Client`) – you can’t just call `connect` on the same one again. Use `Pool` to have this handled for you.

**Comment by yaugenka** [comment]
It it possible to just `reconnect` a client by any means?

**Comment by charmander** [comment]
No, not other than the very straightforward option of creating a new one the same way.

**Comment by jcalfee** [comment]
It would be good to have this in the docs... This just means I need to use the pool, but not knowing that would lead to code that needs to be refactored.
