### ISSUE TITLE
Feature request: Named parameters in prepared statements / parameterized queries

### ISSUE THREAD

**Issue by emilecantin** [brianc/node-postgres#268]
I would like it very much if we could name parameters in queries, instead of the current $1, $2, $3... nonsense. For example:

```
client.query("INSERT INTO beatles(name, height, birthday) values($1, $2, $3)", ['John', 68, new Date(1944, 10, 13)]);
```

would become:

```
client.query("INSERT INTO beatles(name, height, birthday) values(:name, :height, :birthday)", {
  name: 'John',
  height: 68,
  birthday: new Date(1944, 10, 13)
});
```

It would allow for much cleaner code in more complex cases.

**Comment by XeCycle** [comment]
I added in wiki a hint that ES6 tagged template strings may help.

https://github.com/brianc/node-postgres/wiki/Prepared-Statements

**Comment by pihvi** [comment]
Here's another "cleaner" way to solve this with a [library](https://www.npmjs.com/package/yesql). No need for monkeypatching:

```javascript
var sql = require('yesql').pg;

client.query(sql("INSERT INTO beatles(name, height, birthday) values(:name, :height, :birthday)")({
  name: 'John',
  height: 68,
  birthday: new Date(1944, 10, 13)
}));

```

**Comment by gajus** [comment]
> Here's another "cleaner" way to solve this with a library. No need for monkeypatching:

Using syntax `:[a-z]+` in postgres is probably not a good idea as it clashes with type casting syntax.

**Comment by pihvi** [comment]
Postgres syntax for type casting has two colons (::) so this does not clash
with that.

https://www.postgresql.org/docs/9.6/static/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS-GENERIC

**Comment by gajus** [comment]
> Postgres syntax for type casting has two colons (::) so this does not clash
with that.

Yes, sorry – corrected myself, deleted the comment. :-)

**Comment by pihvi** [comment]
[Here's](https://github.com/pihvi/yesql/blob/master/test.js#L13-L20) an example (test case) how it looks and works with type cast:
``` javascript
it('pg type cast', function() {
  assert.deepEqual(
    yesql.pg('SELECT id::int FROM user WHERE id=:id;')({id: '5'}),
    {
      text: 'SELECT id::int FROM user WHERE id=$1;',
      values: ['5']
    })
})

```

**Comment by brianc** [comment]
I've actually started using [this](https://github.com/felixfbecker/node-sql-template-strings) a lot which is IMO the most awesome way yet to build sql statements w/ parameters!

**Comment by gajus** [comment]
> I've actually started using this a lot which is IMO another awesome way yet to build sql statements w/ parameters!

Is dangerous. For one, if the query allows either `string | SQL` input, then it is easy to mistake:

```js
query(SQL`SELECT ${foo}`)
```

with:

```js
query(`SELECT ${foo}`)
```

**Comment by gajus** [comment]
I am working on bringing the best of mysqljs world into Postgres, https://github.com/gajus/mightyql.

**Comment by brianc** [comment]
Really nice! Can't wait to see how it turns out! :+1:

**Comment by avbentem** [comment]
> Is dangerous. For one, if the query allows either `string | SQL` input, then it is easy to mistake [...]

@gajus, just curious: the same problem would exist in your https://github.com/gajus/mightyql#tagged-template-literals, wouldn't it?

> ### Tagged template literals
>
> Query methods can be executed using `sql` [tagged template literal](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals), e.g.
>
> ```js
> import {
>   sql
> } from 'mightyql'
>
> connection.query(sql`INSERT INTO reservation_ticket (reservation_id, ticket_id) VALUES ${values}`);```

**Comment by gajus** [comment]
@avbentem Which problem?

**Comment by gajus** [comment]
Oops. Missed the quote:

> Is dangerous. For one, if the query allows either string | SQL input, then it is easy to mistake [...]

Yes, it does.

**Comment by gajus** [comment]
@avbentem I forgot to mention – I've created an ESLint plugin to avoid this, https://github.com/gajus/eslint-plugin-sql.

**Comment by brandonros** [comment]
```
const buildQuery = (sql, bindings = {}) => {
  const matches = sql.match(/(:[^ ]*)/g) || []
  const bindingIndexMatchMap = {}
  let bindingIndex = 1
  for (let i = 0; i < matches.length; ++i) {
    const match = matches[i]
    if (!bindingIndexMatchMap[match]) {
      bindingIndexMatchMap[match] = bindingIndex
      bindingIndex += 1
    }
    sql = sql.replace(match, `$${bindingIndexMatchMap[match]}`)
  }
  return sql
}
```

```
const sql = `select * from table where foo = :bar or bar = :foo or bizz = :foo`
const bindings = {
  foo: '123',
  bar: '456'
}
console.log(buildQuery(sql, bindings))
```

```
select * from table where foo = $1 or bar = $2 or bizz = $2
```

**Comment by charmander** [comment]
> ```js
> /(:[^ \),]*)/g
> ```

will interfere with casts;

> ```js
>  return {
>    sql,
>    bindings: Object.keys(bindingIndexMatchMap).reduce((prev, key) => {
>      return prev.concat(bindingsMap[key.substr(1)])
>    }, [])
>  }
> ```

takes quadratic time on the number of bindings and will do the wrong thing when a value is an array. `map` exists.

I recommend a [query builder][knex] or SQL template tag (the most starred one in the [Extras][] page is [sql-template-strings][]). The same kind of query/value separation possible with `:name`-style parameters can be preserved using functions.


[knex]: https://knexjs.org/
[Extras]: https://github.com/brianc/node-postgres/wiki/Extras
[sql-template-strings]: https://github.com/felixfbecker/node-sql-template-strings
