### ISSUE TITLE
Does this library automatically close connection on process exit?

### ISSUE THREAD

**Issue by rluvaton** [brianc/node-postgres#2683]
I couldn't find it by myself in the code (and debugged the listeners) so I'm asking here...

In case of exit (due to a normal exit or a crash) does this library automatically close the connection before exit?

From what I saw, it looked like the DB connection get closed by itself...

**Comment by charmander** [comment]
The library isn’t the one that does it, but yes, a process’s connections get closed by the OS when it exits.

**Comment by rluvaton** [comment]
Love your pic!

> The library isn’t the one that does it, but yes, a process’s connections get closed by the OS when it exits.

According to [this](https://stackoverflow.com/questions/36979146/is-a-connection-to-mongodb-automatically-closed-on-process-exit/51384451) SO thread (which is about MongoDB but it's the same case here in my opinion)

> DB connections don't gracefully shut down when you exit (or crash).

**Comment by charmander** [comment]
Right, it’s not graceful (if a transaction were in progress, for example), but the connections don’t stay open.

**Comment by rluvaton** [comment]
Thanks! Have a great day
