### ISSUE TITLE
Do we have executeMany function like OracleNode db

### ISSUE THREAD

**Issue by shindeja** [brianc/node-postgres#2688]
I wanted to check do we have feature like execute many like oracle node library
https://github.com/oracle/node-oracledb/blob/1dee2662eebb299eee164357d49d63a58a616fb2/lib/connection.js#L82

If not then, how we can implement the same?

**Comment by brianc** [comment]
this module sticks close to what the postgres protocol itself exposes & makes available. The postgres protocol doesn't have an "execute many" thing built in, so this module likely wont build something like that in, either.  I don't really understand what that function does with oracle.  The most you can do with postgres is something like:


```
const txt = 'INSERT INTO people (name) VALUES ($1), ($2), ($3)'
const values = ['user 1', 'user 2', 'user 3']
pool.query(text, values)
```
Which would perform 3 inserts.
