### ISSUE TITLE
Column Does Not Exist

### ISSUE THREAD

**Issue by Alifian1999** [brianc/node-postgres#2689]
When I tried to input data to database using nodeJs it says "column does not exist". but i'm sure that i got the right name of the coulmn in database
![Screenshot 2022-01-15 160451](https://user-images.githubusercontent.com/96964770/149614604-cf1ffd71-79f1-417a-af3b-102355d78667.png)
Above is the Syntax
![Screenshot 2022-01-15 160638](https://user-images.githubusercontent.com/96964770/149614645-35b289cd-d065-41b6-87ed-798791e23b30.png)
Above is the error
![Screenshot 2022-01-15 160508](https://user-images.githubusercontent.com/96964770/149614649-5372adb7-52f2-4e1d-a89a-49b1912dbc82.png)

**Comment by boromisp** [comment]
Double quotes mark SQL identifiers, use single quotes for literal strings.
https://www.postgresql.org/docs/current/sql-syntax-lexical.html

**Comment by Alifian1999** [comment]
> Double quotes mark SQL identifiers, use single quotes for literal strings. https://www.postgresql.org/docs/current/sql-syntax-lexical.html

Thankyou So Much!
