### ISSUE TITLE
API requests fail - get errors ("routine": "auth_failed")

### ISSUE THREAD

**Issue by jerryforcode** [brianc/node-postgres#2690]
I am not able to make any requests (POST, GET, etc) without getting this error:
```
{
    "length": 102,
    "name": "error",
    "severity": "FATAL",
    "code": "28P01",
    "file": "auth.c",
    "line": "330",
    "routine": "auth_failed"
}
```

I ran a test script on my server to see if I can insert values into the database and works fine on the server. But when trying a POST request (via Postman) I run into the above error. 
I built my API with Node Express.

Node version: `v16.13.1`
PostgreSQL version: `v12.9`

And I believe my config for pg is correct since the test script runs on the server without issues. 
**Am I missing something?**

**Comment by charmander** [comment]
Your configuration is probably not correct.

**Comment by jerryforcode** [comment]
@charmander thank you for your response. This is my config setup:

```
const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
  user: process.env.DB_USER,
  database:  process.env.DB_NAME,
  password: process.env.DB_PASS, 
  port: process.env.DB_PORT, //5432
  host: process.env.DB_HOST, //localhost
});

module.exports = { pool };
```

Curious to know why it works when I run a test script on the server that uses the same configuration? 

Appreciate the help!

**Comment by jerryforcode** [comment]
can anyone advise?

**Comment by jerryforcode** [comment]
for some reason it doesnt work with process.env but if i hardcode them its fine. Looking into process.env issue now.

**Comment by codemaker2015** [comment]
It is working fine if we hardcode it. But not working for process.env
