### ISSUE TITLE
How to use unnest to insert multiple rows with arrays?

### ISSUE THREAD

**Issue by pietrushka** [brianc/node-postgres#2692]
I saw this trick [here](https://github.com/brianc/node-postgres/issues/1116#issuecomment-283854402) but I have problem with array type columns

```
client.query({
    text: `INSERT INTO table  (id, tags)  SELECT * FROM UNNEST ($1::text[], $2::text[][])`, 
    values: [
        [ 'id1', 'id2' ],
        [ ['tag1', 'tag2'], ['tag3'] ],
    ],
})
```

I get this error ` column "tags" is of type text[] but expression is of type text`
How can I fix it?

**Comment by marcbachmann** [comment]
that's a postgres query issue, but not sure why it won't throw in that case.
Arrays members always need the same amount of elements.
So this will throw: ​`SELECT * FROM UNNEST ('{id1,id2}'::text[], '{{tag1,tag2},{tag3}}'::text[][])` 
And this unnests wrong: ​`SELECT * FROM UNNEST ('{id1,id2}'::text[], '{{tag1,tag2},{tag3,tag4}}'::text[][])`
So unnest won't work here. 

I'd rather use 
```sql
INSERT INTO table  (id, tags)
SELECT * FROM json_to_recordset('[
  {"id":"id1","tags":["tag1","tag2"]},
  {"id":"id2","tags":["tag3"]}
]'::json) AS e (id text, tags text[])
```

Therefore this query:
```js
client.query({
  text: `
    INSERT INTO table  (id, tags)
    SELECT * FROM json_to_recordset($1::json) AS e (id text, tags text[])
  `, 
  values: [
    JSON.stringify([
      {"id":"id1","tags":["tag1","tag2"]},
      {"id":"id2","tags":["tag3"]}
    ])
  ]
})
```

**Comment by pietrushka** [comment]
@marcbachmann thank you, this solved my issue
