### ISSUE TITLE
Does PG support CREATE DOMAIN?

### ISSUE THREAD

**Issue by frmoded** [brianc/node-postgres#2696]
The setting:
Node / express / pg 

**While the following works fine**

    CREATE TABLE blah(foo VARCHAR(128) PRIMARY KEY);

**The following breaks**

    CREATE DOMAIN Foo VARCHAR(128);  
    CREATE TABLE blah(foo FOO PRIMARY KEY);
 
**With the following error** 

    error: input of anonymous composite types is not implemented  at Parser.parseErrorMessage (.../node_modules/pg-protocol/src/parser.ts:369:69)

The node code that triggers this is (roughly):

    const { Pool } = require('pg');
    const pool = new Pool();
    
    module.exports = {
      query: (text, params) => pool.query(text, params),
    }

called:

    await db.query('CREATE DOMAIN Foo VARCHAR(128);');
    await db.query('CREATE TABLE blah(foo FOO PRIMARY KEY);');

The second call crashes

**Comment by boromisp** [comment]
The `input of anonymous composite types is not implemented` is produced by the PostgreSQL server.

The following code works on pg@8.7.1 without any error:

```js
const { Pool } = require('pg')

const pool = new Pool();

(async function () {
  try {
    await pool.query('CREATE DOMAIN Foo VARCHAR(128);');
    await pool.query('CREATE TABLE blah(foo FOO PRIMARY KEY);');
    console.log('Done');
    process.exit();
  } catch (err) {
    console.error(err);
  }
}());
```

**Comment by brianc** [comment]
Yeah this isn't an issue with node-postgres, your server is returning that error....you'd likely receive the same error via `psql`
