### ISSUE TITLE
Support build safety dynamic query ?

### ISSUE THREAD

**Issue by abcfy2** [brianc/node-postgres#2699]
Just like Python psycopg module, there's a built in function to help build safety dynamic query: https://www.psycopg.org/psycopg3/docs/api/sql.html#module-psycopg.sql

```py
from psycopg import sql

cur.execute(
    sql.SQL("INSERT INTO {} VALUES (%s, %s)")
        .format(sql.Identifier('my_table')),
    [10, 20])
```

Would you please support this feature?

Thanks.

**Comment by charmander** [comment]
https://www.npmjs.com/package/pg-format covers this. (`Client.prototype.escapeIdentifier` also exists in a pinch.)

**Comment by k-funk** [comment]
Really feels like this should be built in to node-postgres, even if there's a dependency on pg-format.

This mix of formatting for identifiers vs values feels weird/wrong:
```
import { Pool } from 'pg'
import pgFormat from 'pg-format'

...
const columnName = 'title' // identifier
const code = 'foo' // value
const queryText = pgFormat('UPDATE codes SET %I = true WHERE code = $1', columnName)
const res = await pool.query(queryText, [code])
```

Obviously I could just rely on `pg-format` to create the entire query,  but that also seems strange to not be using the piece of node-postgres that does work as expected.
