### ISSUE TITLE
Transaction block increases the request time 

### ISSUE THREAD

**Issue by Laswii** [brianc/node-postgres#2701]
I am using PG v-8.7.1 with node 16x 
I created a webhook api that will store the data in several tables. 
code A
``` 
Begin
insert into x values (..); 
insert into b values (..)
Select created_at from c when b.id = c.id
insert into c values (...)
COMMIT 
``` 
code_ B
``` 
insert into x values (..); 
insert into b values (..)
Select created_at from c when b.id = c.id
insert into c values (...) 
``` 
first I was using Code_b the request time was 2.7 sec.
since it is a Webhook API I needed to make it transactional, so after applying the Code_A, when I checked the time request, it has been increased to 6.8 sec.
so my issue is why the time has doubled after using transactions? and how to reduce the time request?

**Comment by charmander** [comment]
Unless you have additional information that makes this specifically related to pg (e.g. improved performance using some other database driver), this is more of a general PostgreSQL use question (and doesn’t really have enough detail to answer anyway).
