### ISSUE TITLE
pool.connect doesn't return error if it can't connect

### ISSUE THREAD

**Issue by ozgrakkurt** [brianc/node-postgres#2704]
currently if pool.connect can't connect to db it just hangs forever. can this be changed so it returns error?

Also if there are no clients left in pool it hangs forever. can we put a timeout to this so we get an error instead of it hanging forever? I realize this can be done from outside but it would better if library allows this to be done via it's api

**Comment by ozgrakkurt** [comment]
I found the related config parameters after opening the issue. if anyone needs them they are here: [https://node-postgres.com/api/pool](https://node-postgres.com/api/pool)

**Comment by outranker** [comment]
> I found the related config parameters after opening the issue. if anyone needs them they are here: https://node-postgres.com/api/pool

the url is actually `https://node-postgres.com/apis/pool`
