### ISSUE TITLE
`set application_name = ?` called millions of times when using pgbouncer

### ISSUE THREAD

**Issue by rickharrison** [brianc/node-postgres#2729]
We have been using `node-postgres` for years so thank you very much for all of your hard work! We recently swapped to using `pgbouncer` alongside an application level connection pool. Ever since we swapped, there have been millions of `SET application_name = ?` queries run, which we think is because of the constant connection creation from using pgbouncer. Does node-postgres initiate this query and is it possible to not run this query?

**Comment by charmander** [comment]
Have you configured an application name (`application_name` or `fallback_application_name` in config/querystring, or `PGAPPNAME` environment variable)? Does removing it help? pg doesn’t set that option unless it’s requested, so it might be pgbouncer default behaviour that has to be configured on the pgbouncer side.

**Comment by rickharrison** [comment]
To my knowledge we have not set any of that. It is definitely not in our connection string. I can check if `PGAPPNAME` exists

**Comment by rickharrison** [comment]
I checked and `PGAPPNAME` is `undefined`. I have no idea where this query is coming from, but it happened the day we went live with pgbouncer

**Comment by rickharrison** [comment]
This was indeed a `pgbouncer` issue. Whenever `application_name` differs, it will issue this query in order to keep things in sync. In a high throughput environment, this can happen a lot. If you have the pgbouncer setting `application_name_add_host` turned to on (Heroku does this for you), every app name will be different, thus causing these queries. More info in this blog post:

https://engineering.procore.com/dad-eliminates-top-db-cpu-consumer-with-a-single-env-variable/
