### ISSUE TITLE
Difference between `pool.connect()` and `client.connect()`

### ISSUE THREAD

**Issue by sepsol** [brianc/node-postgres#2731]
I'm sort of familiar with `pool.connect()` as it is well described in the [docs](https://node-postgres.com/api/pool#poolconnect), I know that it'll create a new `client`. But I can't find a good description for `client.connect()` in the [docs](https://node-postgres.com/api/client#clientconnect). Does it create another nested `client` within the parent `client`? Is that even possible?

**Comment by marcbachmann** [comment]
`new Client(opts)` just creates the client instance, it won't connect to postgres.
`client.connect` will then actually connect and make it available for queries.

```js
const client = new (require('pg').Client)(dbConfig)
// without a `client.connect` call this will never resolve
await client.query('SELECT 1')

// Connect to the client first
client.once('error', () => process.exit(1))
await client.connect()
await client.query('SELECT 1')
```
