### ISSUE TITLE
Can't use prepared statements if a unique comment prepended to the query every time

### ISSUE THREAD

**Issue by KristjanTammekivi** [brianc/node-postgres#2735]
We prepend a comment ID'ing the request that caused the db query for easier tracking. I wanted to add name parameter to one query that has a long planning time and ran into an issue where this error is triggered every time
https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/query.js#L149

```javascript
if (this.text && previous && this.text !== previous) {
  return new Error(`Prepared statements must be unique - '${this.name}' was used for a different statement`)
}
```

Can we add a way to bypass this check (or strip out leading comments in the check)?

**Comment by charmander** [comment]
The comment will be wrong anyway if you bypass this, won’t it? I’d suggest checking for a `name` and not adding the comment if it exists.

**Comment by KristjanTammekivi** [comment]
You're right, didn't think of it.
As for what to do, I can configure the methods in typescript so they're mutually exclusive, I think I'll do exactly that.

Issue invalid, thanks!
