### ISSUE TITLE
Interpolation for INTERVAL not working

### ISSUE THREAD

**Issue by MoSattler** [brianc/node-postgres#2737]
Interpolation for INTERVAL not working properly. This works fine
```typescript
query.andWhere(
  "session.created BETWEEN NOW() - INTERVAL '60 MINUTES' AND NOW()"
);
```

But this does not
```typescript
query.andWhere(
  "session.created BETWEEN NOW() - INTERVAL ':minutes MINUTES' AND NOW()",
  { minutes: 60 }
);
```

The error message is:
> bind message supplies 1 parameters, but prepared statement \"\" requires 0"

See also https://github.com/typeorm/typeorm/issues/8697

**Comment by charmander** [comment]
`- :minutes * INTERVAL '1 minute'`. Parameter references are expressions within the query, not string interpolation.

**Comment by av** [comment]
It appears that `:minutes::INTERVAL` will work as expected (consequently you'll have to add units to the interval itself)

**Comment by devonik** [comment]
> It appears that :minutes::INTERVAL will work as expected (consequently you'll have to add units to the interval itself)
Nice that this is possible but in my Tests i didnt get any records by WHERE pg.date_last_modified > now() - $1::INTERVAL
$1 = 60 
> - :minutes * INTERVAL '1 minute'
Works
