### ISSUE TITLE
invalid input syntax for type uuid: ""

### ISSUE THREAD

**Issue by Vimeux** [brianc/node-postgres#2738]
Hello, 
please be indulgent, I'm newbie with Postgres

I'm trying to insert data in a table, but it seems I'm doing it wrong.

Here is my code : 
```
router.route('/')
  // post request to add party
  .post(async (req, res) => {
    const { userId, bookingId, budget, invitationCode, checkInDate, maxPerson } = req.body

    // If data is missing
    if (!userId || !budget || !invitationCode || !checkInDate || !maxPerson) {
      return res.status(400).send({ message: 'missing fields' })
    }

    // query to add the party to the database
    const queryText = 'INSERT INTO "party" (user_id, booking_id, budget, invitation_code, check_in_date, max_person) VALUES ($1, $2, $3, $4, $5, $6)'
    db.query(queryText, [userId, bookingId, budget, invitationCode, checkInDate, maxPerson], (err, result) => {
      console.log(err)
      if (err) return res.status(500).send({ message: err.message })
      res.send({ message: 'party has been created' })
    })
  })
```
And the request I make in postman : 

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/55838254/166154058-53402d28-be68-47f4-b811-d109a13d791d.png">

I don't know why, but I can't insert my UUID in my table, is there something I'm missing?

Thank you in advance for your help.

**Comment by charmander** [comment]
`bookingId` is an empty string, and it looks like `party`’s `booking_id` column is a `uuid`. Like the error message says, an empty string is not a valid UUID. If it’s nullable and the intent is for the empty string to represent `null`, you should check that condition and convert it to `null` before performing the query.
