### ISSUE TITLE
Wrong use of array operator "in" with Boolean value "false"

### ISSUE THREAD

**Issue by danieltorscho** [brianc/node-postgres#2754]
https://github.com/brianc/node-postgres/blob/28ac2a17bce287cfa458153dcabe3ca06ca0e28f/packages/pg/lib/connection.js#L82

if `self.ssl` is `false`, following line provokes an error:
https://github.com/brianc/node-postgres/blob/28ac2a17bce287cfa458153dcabe3ca06ca0e28f/packages/pg/lib/connection.js#L85

Error: `TypeError: Cannot use 'in' operator to search for 'key' in false`

**Comment by charmander** [comment]
This is supposed to cover it:

https://github.com/brianc/node-postgres/blob/28ac2a17bce287cfa458153dcabe3ca06ca0e28f/packages/pg/lib/connection.js#L60-L62

Do you have a short test case you can post that reproduces the bug?
