### ISSUE TITLE
Possible Bug: pg.Client state after pg.Client.end() is not reset

### ISSUE THREAD

**Issue by yuval-po** [brianc/node-postgres#2765]
Greetings,

Preface:

- Using the `pg.Client` **directly**. No pool.
- Using the `Promise` API on `pg`
- Use-case is... non standard. A few thousand severs communicating directly with Postgres with no real intermediary (GWs/web servers excluded) so I cannot afford to keep sockets open for very long.
 I'm currently establishing a connection every X minutes (15, for example), inserting some data and closing.

Apparent/Possible Issue:

1. Calling `pg.Client.end()` does not reset the client's internal state (i.e. `this._connecting`, `this._connected` and `this._ending`)
2. Attempting to call `client.connect()` afterwards throws error "`Client has already been connected. You cannot reuse a client.`"
3. Attempting to call `client.query()` in that state throws error "`Client was closed and is not queryable`"
4. Not directly related but the client's internal connection state is not public making it harder to work with on this level

Repro:
```
  const client = new pg.Client();
  await client.connect();
  await client.end();
  // Client is now inoperable

  // Results in "Client has already been connected. You cannot reuse a client"
  await client.connect();

  // Results in "Client was closed and is not queryable"
  await client.query('query goes here');
```

Proposed fix:

- If the above **is** intended behavior I think it would be a good idea to expand upon existing documentation, stating this constrain whilst also advising on the preferred usage pattern for similar cases.
  Currently, documentation for `connect` or `end` do not reference this sort scenario.

- If the above is **not** intended behavior, a possible fix could be:
    1. Fix internal state management for `connect`/`end`
    2. Expose part of internal state so owners of `Client` instances may check the client's current state (i.e. connecting/connected etc.)

Env: (Sorry, writing from home, don't have exact Node/Postgres versions available)
- Node ~12
- Postgres ~12
- pg 8.7.3

If you consider my points valid, please let me know, I can draft up a P.R for this.

Thanks!

**Comment by charmander** [comment]
> Client has already been connected. **You cannot reuse a client.**

**Comment by yuval-po** [comment]
@charmander, I assumed this might be intentional but I was uncertain whether this means the entire client instance should be discarded. That's why I dubbed this a 'possible' bug and eluded to that documentation might benefit from a bit of clarification here.

Any idea if this is a design decision or just a current limitation?
Would make sense to be able to connect and disconnect the client at will, no?

In any case, if this behavior is not to be modified, it might be worth a mentioning the single-use nature of the client in the [official docs](https://node-postgres.com/api/client/)

**Comment by charmander** [comment]
It’s a design decision. The smaller the space of possible states, the better; having a single way to accomplish the task of creating a new connection (creating a new `Client` object) is more reliable. For maintaining a single object across multiple connections, even when only one at a time is wanted, a `Pool` is typically the right choice.

**Comment by yuval-po** [comment]
Fair enough. Still think this should go into the docs though heh.
Will move to using `Pool` and think nothing more of it then.

Thanks!
