### ISSUE TITLE
Cannot drop the currently open database

### ISSUE THREAD

**Issue by dschinkel** [brianc/node-postgres#2766]
I'm trying to figure out how this is even working if I haven't called `connect()` anywhere.  This code is sending queries successfully but I don't seem to be releasing anywhere because I don't have a client to call `release()` on.

I never have any problems with this code, but what I'm trying to do is make sure there are no clients in the pool so that I can `DROP` my database for test runs during migration runs and somehow something's still connected to the DB and I get an error `cannot drop the currently open database`.

`pool.totalCount`, `poll.idleCount`, and `pool.waitingCount` all return `0` so somehow they pool is releasing resources automatically?  Not sure, because the docs say you must call `release()` on the client.

`console.log('removed')` is definitely being called, so is it automatically handling removing of clients for me somehow without having to explicitly call `release()` ?

```
import { Pool } from 'pg';

require('dotenv/config');

export const queryType = {
    ONE: 1,
    MANY: 2,
};

const postgresPoolLocal = new Pool({
    user: process.env.DB_USER_LOCAL,
    host: process.env.DB_HOST_LOCAL,
    database: process.env.DB_NAME_LOCAL,
    password: process.env.DB_PASS_LOCAL,
    port: process.env.DB_PORT_LOCAL,
});

postgresPoolLocal.on('remove', (client: Client) => {
    console.log('removed');
});

async function queryDB(query, queryTypeId) {
    const rows = sendQuery(queryTypeId, query);
    return rows;
}

export async function sendQuery(queryTypeId, query) {
    let rows;
    const pool = getDBPool();
    
    try {
        const db = await (async () => {
	    try {
		return pool.query(query);
	    } catch (err) {
		console.error(err);
	    }
	    return { rows: undefined };
        })();
        
        if (!db || !db.rows) return;
        rows = queryTypeId === queryType.MANY ? db.rows : db.rows[0];
    } catch (err) {
        console.error('postgres query error', err);
    }

    console.log(`Pool client count: ${pool.totalCount}`);
    console.log(`Pool idol count: ${pool.idleCount}`);
    console.log(`Pool waiting count: ${pool.waitingCount}`);

    return rows;
}

function getDBPool() {
    return postgresPoolLocal;
}

export default {
    queryDB,
    queryType,
};
```

**Comment by charmander** [comment]
You’re issuing the `DROP DATABASE` query from a client connected to that same database. Specify a different `database` in the options for that client. (Consider `DROP SCHEMA` instead, though, to simplify connection management and permissions.)

**Comment by brianc** [comment]
`pool.query` automatically does

```
const client = pool.connect()
try { client.query() } 
finally { client.release() }
```

Only need to use `pool.connect` to "check out" a client for longer if you're doing transactions.
