### ISSUE TITLE
library ignores env variables loaded with dotenv

### ISSUE THREAD

**Issue by fedulovivan** [brianc/node-postgres#2769]
Hello! Please direct me, if im doing something wrong, but looks that node-postgress is not woking properly with dotenv package.

given **.env** file with connection params:
```
PGUSER=foo
PGHOST=bar
PGPASSWORD=baz
PGDATABASE=lorem
PGPORT=1234
```

deps from **package.json**:
```json
"dependencies": {
    "dotenv": "^16.0.1",
    "pg": "^8.7.3",
}
```

and main file **index.mjs** script as
```js
import 'dotenv/config';
import pg from 'pg';
const pool = new pg.Pool();
pool.query('SELECT NOW()', (err, res) => {
  console.log(err, res);
  pool.end();
});
```
test launch with **node index.mjs** says that defaults are used instead of values from .env:
```
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
```

**(!)** note that when variable is passed with bash as **PGHOST=bar node index.mjs** all works as expected:
```
Error: getaddrinfo ENOTFOUND bar
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'bar'
}
```

**Comment by fedulovivan** [comment]
@markcellus, as per [dotenv docs](https://www.npmjs.com/package/dotenv), it has an API without explicit invocation of config 
@charmander, cannot understand why issue why just closed as "not planned"

**Comment by charmander** [comment]
Did you try logging `process.env`? Or is there any other evidence that points to this being a pg bug?

**Comment by fedulovivan** [comment]
I cannot reproduce this anymore. It started to work properly in my project with no reason. My assumption was that your library may cache values from process.env at the import, or have some other specific of reading env values.
