### ISSUE TITLE
Supply both servername and host (IP)

### ISSUE THREAD

**Issue by anjoantoque** [brianc/node-postgres#2773]
Hi, 

Im currently working on nodejs app and azure database with private endpoints, but I am having this issue when using the server IP as host in my connection string and get this error.
  
    `Database Error:  Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:cr5.westus1-a.control.database.windows.net, DNS:*.cr5.westus1-a.control.database.windows.net, DNS:westus1-a.control.database.windows.net, DNS:*.westus1-a.control.database.windows.net, DNS:*.database.windows.net, DNS:*.database.secure.windows.net, DNS:*.secondary.database.windows.net, DNS:*.mariadb.database.azure.com, DNS:*.mysql.database.azure.com, DNS:*.postgres.database.azure.com, DNS:*.sql.projectarcadia.net, DNS:*.sql.azuresynapse.net, DNS:*.sql.azuresynapse-dogfo`
    
Is there any way we could supply both servername and host (IP) in the connection ? I just need the servername to validate TLS. It works when I tried to override servername [here ](https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/connection.js#L92).

**Comment by anjoantoque** [comment]
Here is the full error.
[npmpg-error.txt](https://github.com/brianc/node-postgres/files/9115656/npmpg-error.txt)

**Comment by gongshishao** [comment]
@anjoantoque Hi, seems you have fix the issue, can you pls help to share the solution, thx. I was stuck with this issue too, don't know if it's about ip or cert pem format. BTW, i was trying to reproduce this issue in my localhost. And pg confg ssl severt certs from local docker. And i can success use dbeaver to connect to PG by certs

**Comment by toxic-johann** [comment]
This hacky way work for me since I am not using this on the production..

4. **Ignore at your own risk**: In a **non-production environment**, for testing purposes only, you can choose to ignore the hostname and certificate checks by adding this to your node.js application:
```javascript
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
```
But remember, this disables all kinds of certificate checks and should NEVER be used in production environments as it exposes you to Man In The Middle (MITM) attacks.
