### ISSUE TITLE
Query syntax with array_agg throw ' invalid input syntax for type integer: "$1" '

### ISSUE THREAD

**Issue by Setanas** [brianc/node-postgres#2805]
Hello,

I encountered an issue while doing a particular request using "array_agg"

I am using postgresSQL 14.3 and pg 8.7.3 (I also tried with the 8.8.0)
My data base looks something like this (This was not what my db looked like when I encountered the issue but I still have the same issue with this smaller data base)

![image](https://user-images.githubusercontent.com/25301076/188005242-aa272bcf-973f-4a5c-b7fb-ccbcd2a3c529.png)

And Here is the code that I am trying
```
const { Client } = require('pg')
const client = new Client()

async function main() {

  await client.connect()

  const res = await client.query(`SELECT toto, tata FROM "public".debug
  WHERE multiple = $1`, ['1'])
  console.log(res.rows[0])

  const res_1 = await client.query(`SELECT toto, tata, array_agg(multiple) FROM "public".debug
    group by toto, tata
    having array_agg(multiple)<@'{1, 4, 3}'`)
  console.log(res_1.rows[0])

  const res_2 = await client.query(`SELECT toto, tata, array_agg(multiple)  FROM "public".debug
    group by toto, tata
    having array_agg(multiple)<@'{$1, $2, $3}'`, ['1, 4, 3'])
  console.log(res_2.rows[0])

  await client.end()
}

main()
```
The first and second query work but the last one doesn't and I have an Error ' invalid input syntax for type integer: "$1" '

I am guessing that's because in my syntax near the '$1' there is a '{' but I am not sure if I misuse the pg library and that is a normal behavior or not.

**Comment by boromisp** [comment]
The paramter you are passing to the second query is a single string. The error is thrown by the postgres server when it tries to parse `'1, 4, 3'` as an integer.
You should pass each parameter as a separate element in the parameter array: `[1, 4, 3]`.

**Comment by boromisp** [comment]
If you are trying to construct an SQL array from fix number of items, you can do it like this:
```js
client.query('SELECT ARRAY[$1, $2, $3]', [1, 4, 3])
```

If the number of items is not fixed, you either have to build the query string with N parameters or, stringify your list of items as an SQL array literal:
```js
// build the query with N parameters
client.query(`SELECT ARRAY[${items.map((_, i) => `$${i + 1}`).join(',')}]`, items);

// single parameter as an SQL array literal
client.query(`SELECT $1::int[]`, [`{${items.join(',')}}`]);
```

**Comment by Setanas** [comment]
Thank you for your reply

With what you said, I have tried with using the ARRAY keyword, this request work on postgresSQL
``SELECT toto, tata, array_agg(multiple)  FROM "public".debug
    group by toto, tata
    having array_agg(multiple)<@ARRAY[1, 4, 3]```

So I tried to retranscribe it with pg and it look like this:
```
const res_2 = await client.query(`SELECT toto, tata, array_agg(multiple)  FROM "public".debug
    group by toto, tata
    having array_agg(multiple)<@ARRAY[$1, $2, $3]`, [1, 4, 3])
```

But I had an error so what has worked for me was a mix of your answer, I had to add the "::interger[]" in my "Having" clause
(I guess it's because when doing the ARRAY[$1, $2, $3], it become an array of text and I am trying to compare an array of integer with an array of text)
```
const res_2 = await client.query(`SELECT toto, tata, array_agg(multiple)  FROM "public".debug
    group by toto, tata
    having array_agg(multiple)<@ARRAY[$1, $2, $3]::integer[]`, [1, 4, 3])
```

Thank you very much for your help and thank you for your contribution !
