### ISSUE TITLE
Load Balancing queries using pgpool

### ISSUE THREAD

**Issue by mai1x9** [brianc/node-postgres#2808]
Hi, 
I have a question regarding the max option in config for Pool, as per documentation of [pg.Pool](https://node-postgres.com/api/pool)
```
config = {
  // all valid client config options are also valid here
  // in addition here are the pool specific configuration parameters:
  // number of milliseconds to wait before timing out when connecting a new client
  // by default this is 0 which means no timeout
  connectionTimeoutMillis?: int,
  // number of milliseconds a client must sit idle in the pool and not be checked out
  // before it is disconnected from the backend and discarded
  // default is 10000 (10 seconds) - set to 0 to disable auto-disconnection of idle clients
  idleTimeoutMillis?: int,
  // maximum number of clients the pool should contain
  // by default this is set to 10.
  max?: int,
  
  // Default behavior is the pool will keep clients open & connected to the backend 
  // until idleTimeoutMillis expire for each client and node will maintain a ref 
  // to the socket on the client, keeping the event loop alive until all clients are closed 
  // after being idle or the pool is manually shutdown with `pool.end()`.
  //
  // Setting `allowExitOnIdle: true` in the config will allow the node event loop to exit 
  // as soon as all clients in the pool are idle, even if their socket is still open 
  // to the postgres server.  This can be handy in scripts & tests 
  // where you don't want to wait for your clients to go idle before your process exits.
  allowExitOnIdle?: boolean
}
```
I can see initially a single connection is opened with postgres server. After running couple of functions as a part of batch process, they are lot of SELECT queries used to fetch data from database.

Setting `max=50`, I can see suddenly the connection count increased from 1 to 50. (Which is verified by using `ss | grep 5435 | wc -l `). NOTE: postgres server is running on 5435.

After setting to `idleTimeoutMillis=120000`, after 2 minutes, the connection count is back to 1.

**My Question are,**
- Can I say that due to increase in number of select queries, new client connections has been established with postgres server. Is this a sort of load balancing handled by pg pool trying to open new connections when they are large number of queries to server upto `max` option.
- Let's say I have lot of traffic, and all my 50 connections are up, so I believe all other queries are queued and distributed among these 50 client connections by pg pool and processes them. If a connection is idle for more than `idleTimeoutMillis` amount of time, the connection is closed permanently. 
- There's a separate query load balancing between read replicas, does Pg pool automatically handle it. I see no where in documentation regarding `load_balance_mode` as mentioned in https://b-peng.blogspot.com/2020/12/load-balancing-in-pgpool.html. 
- If there are read replicas of postgres server, do I need to specifically mention to pg pool regarding the repliacas address(like Ip or host urls) or Pg pool automatically figures it out from master.

Thank you very much.

**Comment by brianc** [comment]
> * There's a separate query load balancing between read replicas, does Pg pool automatically handle it. I see no where in documentation regarding `load_balance_mode` as mentioned in https://b-peng.blogspot.com/2020/12/load-balancing-in-pgpool.html.

pgpool is not this library. this library does no load balancing. that's up to you in your app to handle.



> * Can I say that due to increase in number of select queries, new client connections has been established with postgres server. Is this a sort of load balancing handled by pg pool trying to open new connections when they are large number of queries to server upto `max` option.

pool will open max (n) connections to your backend where (n) is the `max` config option. after that, further query/connect requests are queued until a client becomes available



> * Let's say I have lot of traffic, and all my 50 connections are up, so I believe all other queries are queued and distributed among these 50 client connections by pg pool and processes them. If a connection is idle for more than `idleTimeoutMillis` amount of time, the connection is closed permanently.

i don't think this is a question



> * If there are read replicas of postgres server, do I need to specifically mention to pg pool regarding the repliacas address(like Ip or host urls) or Pg pool automatically figures it out from master.

you need a separate pool for read replica. if you want more sophisticated load ballancing in your pool you can implement your own - this one serves fine for most general use apps, but special logic just use `pg` direct and make your own poo, use pg-bouncer, etc.
