### ISSUE TITLE
Pg Pool for multiple schemas. 

### ISSUE THREAD

**Issue by mai1x9** [brianc/node-postgres#2809]
Hi, I have a question regarding the use of pg pool where we have multiple schemas (as a part of multi tenancy architecture, where data is logically separated, each client have their own schemas).

Is Pg Pool safe to query from multiple schemas. I have seen few of the articles mentioning pooling might lead to data corruption and it is recommended to open a new connection instead using Client.

**To describe more,**
Let's say i have pool of 10 connections that are opened to postgres server, one of the connections among pool let's say `pool1` executing query on `schema1` something like 
`select * from schema1.users_table where ..... order by ... LIMIT 20 OFFSET 100;`
Once query is processed, the same `pool1` is executing next query on `schema2` something like 
`select .... from schema2.statistics  where .... ;`

Imagine we have 1000 of queries running on different schemas, with 10 pool connections which are always opened with postgres server.

Will this lead to any data corruption (like fetching other schema data wrongly etc..) or while inserting data into schema, it gets wrongly inserted into another schema etc...

I have read somewhere on internet, where some answers suggest upto 1000 schemas it is fairly good enough and some suggest 10k schemas. However i did like to have a clarity regarding this from the developers of pg Pool.

Any help would be highly grateful.

**Comment by brianc** [comment]
You'll have to test on your side but this library doesn't do anything specific w/ schemas. If you're putting your schemas into your queris like

```
select * from "schema1"."table_name"
```
then I can't fathom how that could impact pooling in any way.  We just pass along your query unaltered to postgres and so if there's some kinda corruption problem w/ thousands of schemas that'd be related to postgres and not this library.
