### ISSUE TITLE
Question: should client.hasExecuted be reset?

### ISSUE THREAD

**Issue by alxndrsn** [brianc/node-postgres#2817]
I'm seeing https://github.com/brianc/node-postgres/issues/2168 frequently, and have bumped into https://github.com/brianc/node-postgres/issues/1872 occasionally.

#2168 seems to be caused by an out-of-order `parseComplete` message arriving, after `this.activeQuery` has already been set to `null`.

While digging around, I was intrigued by the property `this.hasExecuted` in `client.js` (https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/client.js#L482).  If I've understood correctly, the `Client` instance can be re-used for multiple queries, but `hasExecuted` is implicitly initialised to `undefined`, set to `true` just before the first call to `this.activeQuery.submit(...)`, and never re-set to something falsy.

Does `hasExecuted` track that the `Client` instance has submitted _at least one_ query?  Or should it be tracking if the `Client` instance has submitted _the current active query_?

**Comment by why-el** [comment]
I am intrigued by this too reading the node-pg code base this weekend. Who can we tag for more info?

**Comment by why-el** [comment]
Actually I spoke too soon, I think it works as is, the variable synchronizes multiple runs and is scoped to the client itself, thus "synchronizing" whether we are being active or not.

**Comment by why-el** [comment]
Log from a run where I run one query, then I run two queries inside a `Promise.all`: 

```
In active query
No longer, draining
In active query
No longer, draining
In active query
In active query
No longer, draining
No longer, draining
```
