### ISSUE TITLE
document bulk insert

### ISSUE THREAD

**Issue by molecular** [brianc/node-postgres#283]
Hi, sorry to enter this as an issue.

I'm using .query("insert into...") and it's too slow.

I couldn't find how to bulk-insert data. It says something about the \copy command in the README.md, but I wouldn't know how to use that (only ever used that to insert from csv file from psql shell)

can you give me a hint?

**Comment by manoj2589** [comment]
@anton-kotenko @brianc : Looks like the bulk load link is not available anymore. Is it documented somewhere else?
