### ISSUE TITLE
column with same name become one and get value from right table when LEFT JOIN and vice versa

### ISSUE THREAD

**Issue by boyafandy** [brianc/node-postgres#2837]
```
const { rows } = await db.query(
    "SELECT * FROM tab1 LEFT JOIN tab2 ON tab1.id = tab2.tab1_id"
)
console.log(rows)
```
get:

![image](https://user-images.githubusercontent.com/59204640/194887863-0989a22d-92d8-425e-af7f-bf60cba7f9c2.png)

same query in postgresql:

![image](https://user-images.githubusercontent.com/59204640/194887682-7ecd4921-f1aa-4cda-958e-e31c5370788b.png)

**Comment by brianc** [comment]
yeah, that's a limitation of automatically mapping column names to an object. you have 2 options:

```
select tab1.id, tab1.title, tab1.des, tab2.id as tab_2_id, tab2.title as tab_2_title, tab3.des as tab_3_des
```
in your query, or:

```
const { rows, fields } = await query({ text: 'your original query', rowMode: 'array' })
```

The latter will return an array of rows not built into an object.  You can get the row names from `fields` above (an array of objects describing each field in the result)
