### ISSUE TITLE
  const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);                                                                                                        ^  error: password authentication failed for user "junio"

### ISSUE THREAD

**Issue by marcwayn8** [brianc/node-postgres#2846]
Error making queries using pg module,   const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);      
                                                                                                 ^

error: password authentication failed for user "junior", I got this error even though the user I have my database in isn't my local C drive(junio) but postgres

**Comment by charmander** [comment]
Your client/pool isn’t configured to use the user you want to use (`postgres`). Check for typos, and compare against the [API documentation](https://node-postgres.com/api/pool).

**Comment by OrLevy23** [comment]
Hey @charmander, care to share updated link?

**Comment by Rakshit358** [comment]
> Error making queries using pg module, const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name); ^
> 
> error: password authentication failed for user "junior", I got this error even though the user I have my database in isn't my local C drive(junio) but postgres

While using the client method make sure you have followed the same scheme as that in the docs : 

import { Client } from 'pg' 
const client = new Client({
  host: 'my.database-server.com',
  port: 5334,
  database: 'database-name',
  user: 'database-user',
  password: 'secretpassword!!',
}).
Hope this helps..

**Comment by Omkar0200** [comment]
Try to put your plSQL password which you use to save in starting of installation.

const db = new pg.Client({
  user: "postgres",
  host: "localhost",
  database: "world",
  password: "_**Your Password which set you**_",
  port: 5432,
});
