### ISSUE TITLE
Create alias for BEGIN, COMMIT and ROLLBACK

### ISSUE THREAD

**Issue by Splinteer** [brianc/node-postgres#2859]
I find it very ugly to call `client.query('BEGIN')`, `client.query('COMMIT')` or `client.query('ROLLBACK')`.

Is it possible to make alias function like: `client.begin()`, `client.commit()` and `client.rollback()` ?

**Comment by brianc** [comment]
yup @abenhamdine is 100% right & this library isn't meant to contain higher level abstractions...that's a role for additional npm modules (maybe you write one?!) or your own code base.  For example  In my own code I actually have the following helper:

```ts

export async function withTransaction<T>(pool: Pool, cb: (client: PoolClient) => Promise<T>): Promise<T> {
  const client = await pool.connect()

  try {
    logger.debug('BEGIN')
    await client.query('BEGIN')
    const result = await cb(client)
    logger.debug('COMMIT')
    await client.query('COMMIT')
    client.release()
    return result
  } catch (e) {
    logger.warn(`Error in transaction: ${e}...closing connection & rolling back`)
    // this closes the client, automatically rolling back txn
    client.release(true)
    throw e
  }
}
```

and use it:

```ts
await withTransaction(pool, await (client) => {
  await client.query('FIRST QUERY')
  await client.query('SECOND QUERY')
})
```

and I never really write `BEGIN` or `COMMIT` manually anywhere.
