### ISSUE TITLE
Multiple DB pool

### ISSUE THREAD

**Issue by mayaank-gupta** [brianc/node-postgres#2878]
I am trying to create two DB pools for different databases/host.
But even if I passed the wrong DB creds for database2,
its using database1 pool and I am getting query results.

```
const database1 = new Pool({
  user: xxxxxxx,
  host: 09.35.6.8,
  database: xxxx,
  password: xxxxxx,
  port: xxxxxx,
  max: xx,
});

const database2 = new Pool({
  user: xxxxx,
  host: 12.23.45.67,
  database: xxxx,
  password: xxxxxx,
  port: xxxxxx,
  max: xx,
});
```
Only one pool is getting created and its shared for other connection.

any solution to use more than one database in a nodejs project.

Using pg library.

Example:
```
database1
      .query('SELECT NOW()')
      .then((res) => {
        logger.info(`Master Database Initialized : ${res.rows[0].now}`);
        setPool(database1);
      })
      .then(() => {
        logger.info(`Replica Database Initialized : ${new Date()}`);
        setReplicaPool(database2);
        done(true);
      })
      .catch((err) => {
        logger.error(err);
        throw err;
      });
```

**Comment by charmander** [comment]
It’s very likely that there’s some mistake in how you’re using the library that’s not possible to tell from pseudocode. Please make a small reproducible example either way.
