### ISSUE TITLE
Unexplained slowness in client.query

### ISSUE THREAD

**Issue by ramonsnir** [brianc/node-postgres#2884]
Sorry for the lame title, wasn't sure how to elaborate there.

Some keyword bingo for context: Node.js 16, AWS ECS Fargate, TypeGraphQL, TypeORM, AWS RDS Postgres, Postgres 12.11, pooling enabled, SSL connections, TypeORM uses extended query protocol.

The issue is reproducing on a test server environment with 0 traffic (other than the testing traffic) and a test database with only a handful of rows in each table. The database resources, in this case, are woefully underutilized to ensure nothing is going on there.

After some effort, the problem was narrowed down to somewhere inside the pg library. The following logs were added using `patch-package`:

```diff
diff --git a/node_modules/pg/lib/query.js b/node_modules/pg/lib/query.js
index 6655a0e..ef147a6 100644
--- a/node_modules/pg/lib/query.js
+++ b/node_modules/pg/lib/query.js
@@ -12,6 +12,8 @@ class Query extends EventEmitter {
     config = utils.normalizeQueryConfig(config, values, callback)
 
     this.text = config.text
+    this.queryId = Math.floor(Math.random() * 1000000)
+    this.log = config.log || function() {}
     this.values = config.values
     this.rows = config.rows
     this.types = config.types
@@ -134,6 +136,7 @@ class Query extends EventEmitter {
     if (this._canceledDueToError) {
       return this.handleError(this._canceledDueToError, con)
     }
+    this.log('[pg query] ' + this.queryId + ' completed');
     if (this.callback) {
       try {
         this.callback(null, this._results)
@@ -158,6 +161,7 @@ class Query extends EventEmitter {
     if (this.values && !Array.isArray(this.values)) {
       return new Error('Query values must be an array')
     }
+    this.log('[pg query] ' + this.queryId + ' submitted ' + this.text);
     if (this.requiresPreparation()) {
       this.prepare(connection)
     } else {
```

After evaluating ~350 SQL queries over a minute, the time difference between "submitted" and "completed" ranges randomly between a handful of milliseconds (great) and almost a whole second.

![image](https://user-images.githubusercontent.com/1024028/209398849-ec0fc1a7-c7ff-445e-99f8-bf96254e3d55.png)
(There is no x-axis, just plotting queries from slowest to fastest)

There's no material difference in the queries themselves between fast and slow cases. The second slowest query searches a table with 8 rows to find 2 rows (and could use an index, if there were enough rows), and takes 780ms to complete. The fastest run of the same query with the same inputs was completed in 2ms.

`SELECT "AK"."id" AS "AK_id", "AK"."created_at" AS "AK_created_at", "AK"."deleted_at" AS "AK_deleted_at", "AK"."v" AS "AK_v", "AK"."is_system" AS "AK_is_system", "AK"."tenant_id" AS "AK_tenant_id" FROM "aks" "AK" WHERE ( "AK"."tenant_id" = $1 ) AND ( "AK"."deleted_at" IS NULL )`

I am going to keep digging deeper into the code in `query.js` and `connection.js` and maybe `pg-protocol` but I'd love to hear if you have any idea what could be going on it or point to areas in the code that adding logs to might help in debugging here.

**Comment by ramonsnir** [comment]
@charmander I see that you added the "waiting for more info" label. Can you guide me here, and let me know what more info I could add that would be helpful?

**Comment by charmander** [comment]
Ideally, a minimal reproduction test case with complete code and as few libraries in between as possible (delete one thing at a time). Even just seeing if it happens on not-AWS would be a good start, though.

**Comment by chrishurlburt** [comment]
@ramonsnir Did you ever find a solution for this?

I am experiencing what may be a related problem on a similar stack (Fargate, RDS Aurora, TypeORM, connection pooling, Postgres 12.14)

We have an ETL workload that executes a large number of similar queries over a long period of time. The DB cluster and app containers are more than adequately provisioned, yet we're seeing the process progressively slow beginning at about the 45 minute mark.

The performance degradation is characterized by:

- Decrease load on the database (DB CPU, Connection count, network throughput, transactions per second, etc. all decrease)
- stable and consistent CPU / Memory use on the node containers for the full duration of the process (which would seem to rule out a memory leak or runaway process)
- query performance doesn't change - the queries are still performant, there's just far fewer of them being sent to the database

The code itself just iterates rows from a JSON file, runs them through some logic, and inserts them into the database. It's behavior is repetitive and so I would expect performance to be somewhat linear.

It feels like queries just take progressively longer to be sent to the database - perhaps waiting in a queue? Also worth noting this behavior happens locally as well, therefor I think it's unlikely to be an AWS issue.

I'm not sure exactly where or how to address this. Could very well be a configuration issue on my end as well. Any help would be greatly appreciated!

**Comment by ramonsnir** [comment]
@chrishurlburt If I'm not confusing this issue with another, eventually the issue traced back to TypeORM and fixed there in a version released a few months ago. TypeORM had massive blocking CPU usage in our use case, and it was starving node-postgres.
