### ISSUE TITLE
Connection Issues In Dev After 2nd Program Launch

### ISSUE THREAD

**Issue by ChrisYeet** [brianc/node-postgres#2885]
This is the error I receive:

const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^
error: server login has been failing, try again later (server_login_retry)

length: 88,
  severity: 'FATAL',
  code: '08P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: undefined,
  line: undefined,
  routine: undefined
}

**Comment by charmander** [comment]
What is this, https://github.com/zalando/postgres-operator? Maybe you ran into a connection limit?

**Comment by ChrisYeet** [comment]
Discord Bot. It is connecting to supabase's Postgres to the discord.js bot. It is running locally on my hard drive.
