### ISSUE TITLE
Migrating databases

### ISSUE THREAD

**Issue by jbenjoy2** [brianc/node-postgres#2891]
I'm wondering what library you suggest for migrating your postgres database when using node-postgres in your server. I've found a few that don't have a ton of reviews, so i was wondering what y'all use, especially @brianc as the creator of this repo. Native migration capabilities would be cool too!

**Comment by brianc** [comment]
Good question! Honestly we use a big node.js file with all our migrations written out in sql executed one at a time.  This wont scale forever but I'm @ an early stage startup right now so we're doing "KISS" method on things.  I know pg-migrate and there are a few other migration libraries relatively popular in the node community.
