### ISSUE TITLE
Does pg pool shares session state?

### ISSUE THREAD

**Issue by sushibear** [brianc/node-postgres#2897]
Hey,

we are developing a multi-tenant SAAS platform using a single database with RLS to isolate tenant data. For this we need to work with strictly seperated session states. Our current database connection is using pooling but it seems that the session state is not properly isolated between clients then. 
Do we need to change back to use clients instead of pools or is there another possibility how we could do this?

Thanks in advance

**Comment by boromisp** [comment]
In a similar situation I've used the pool the same way I would with transactions: https://node-postgres.com/features/transactions
Check out a connection from the pool, setup the session state, execute the actual queries and finally release the connection back to the pool. (The session state variables you didn't `RESET` before release are still `SET` on the connection!)

Or you could roll your own connection pooling, with ephemeral pools for each active user, but I wouldn't go there unless there are some concrete performance issues with the naive approach.

**Comment by sushibear** [comment]
Thanks for the comment and the suggestions you made. 

I hope I understand this right, I would still be using a pool but then before each query do this:
```
await client.query('BEGIN') 
---> my query here
await client.query('COMMIT')
await client.query('ROLLBACK')
```

**Comment by sushibear** [comment]
Sorry but I still have one more questions ...

if I am releasing the pool everytime after a transaction, then I would have to set the tenantID in the config again before the next transaction!?  Seems like overkill considering that a session state should be kept with each connection until it's released. 

I guess this leads me to my inital question.
