### ISSUE TITLE
query result is empty

### ISSUE THREAD

**Issue by sheliya-d** [brianc/node-postgres#2903]
my SELECT query in properly work but result is empty in sometime in node js rest api.

and don't show any `error`

`try {
        if (!req.query.id) {
            con.query("SELECT * FROM `mst_table` WHERE `ISActive` = '1'", function (err, result) {
                if (err) throw err;
                data = result
                res.status(202).json({
                    status: 1,
                    status_code: 202,
                    messsage: 'all table list find successfull',
                    data: data
                })
            });
        }
        else {
            con.query("SELECT * FROM `mst_table` WHERE `ISActive` = '1' AND `id` = '" + req.query.id + "' ", function (err, result) {
                if (err) throw err;
                data = result
                res.status(202).json({
                    status: 1,
                    status_code: 202,
                    message: "table list find successfull",
                    data: data
                })
            });
        }

    }
    catch (error) {
        res.status(404).json({
            status: 0,
            status_code: 404,
            messsage: error.message,
        })
    }`

**Comment by boromisp** [comment]
That's now how Javascript exceptions work. You won't generally be able to catch errors thrown in a callback functions in a synchronous try catch block.

I recommend looking through some guides or tutorials, eg:
- https://node-postgres.com/guides/project-structure
- https://node-postgres.com/guides/async-express


Btw are you sure, you aren't using mysql? In postgres we don't use ` (backticks) for quoting identifiers.

Also, you will want to use parameterized queries (https://node-postgres.com/features/queries#parameterized-query) for including dynamic values in your queries.

**Comment by charmander** [comment]
That looks like a MySQL query. Either way, not a complete pg bug report.
