### ISSUE TITLE
CI problems with password in v8.9.0

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#2904]
Trying to upgrade [pg-promise](https://github.com/vitaly-t/pg-promise) for v8.9.0 of the driver, I started getting the following errors within GitHub CI, specifically for PostgreSQL v14 and v15:

![image](https://user-images.githubusercontent.com/5108906/215252732-1a1a34c8-14f3-4fb1-aa54-01695b1434eb.png)

The issue started with v8.9.0, there was no problem within GutHub CI prior, it could run against PG 14 and 15 just fine.

**Comment by charmander** [comment]
The error message changed to be more specific (#2901).

**Comment by vitaly-t** [comment]
It does not look that way, as per my original post:

> The issue started with v8.9.0, there was no problem within GutHub CI prior, it could run against PG 14 and 15 just fine.

**Comment by charmander** [comment]
#2901 was released in pg@8.9.0.

**Comment by vitaly-t** [comment]
This is no longer an issue.
