### ISSUE TITLE
Password getting appended to hostname before connecting

### ISSUE THREAD

**Issue by chrispytoes** [brianc/node-postgres#2910]
When connecting to the database, I get an ENOTFOUND error. The invalid domain it outputs is just my password appended to the beginning of my hostname, literally like: "${password}${hostname}". This project has been working for weeks and the issue just started this morning and I didn't change anything. I deleted `node_modules` and `yarn.lock` and reinstalled to no avail.

```
const pool = new Pool(
  {
    database: process.env.PG_DB,
    port: +(process.env.PG_PORT || '25060'),
    host: process.env.PG_HOST,
    password: process.env.PG_PASSWORD,
    user: process.env.PG_USER,
    ssl: {
      ca: process.env.PG_CERT
    }
  }
)
```

I've quadruple checked my environment variables that they are indeed correct. I tried logging my `process.env`, and I did confirm that my `PG_HOST` variable only contains the hostname. I even tried entering all the fields directly into the source code without the variables and that still does the same thing. Somehow, the password is getting appended to the hostname on its own before connecting.

This was just working yesterday. How is this possible?

**Edit:**
I've been doing more testing, and it seems that if I rename my password variable to `PG_PASS`, the resulting host it tries connecting to is now "undefined${hostname}". So it looks like `pg` is automatically recognizing my `PG_PASSWORD` variable and using that instead of the configured one. However that still doesn't explain why it generating this bad hostname in the first place.

**Edit 2:**
This thing keeps blowing my mind the more I dig. If I rename my `PG_HOST` var to `PG_HOSTNAME`, it tries connecting to `${password}undefined`. If I provide options, it looks for the vars, if I provide the vars, it looks for the options... What is going on?

**Edit 3:**
Exact same behavior when I provide a connection string instead of individual options.

**Edit 4:**
If I change ALL my environment vars to not resemble the names of the default postgres vars like below, it tries connecting to `undefinedundefined`.

    {
      database: process.env.PG_DB1,
      port: +(process.env.PG_PORT1 || '25060'),
      host: process.env.PG_HOST1,
      password: process.env.PG_PASSWORD1,
      user: process.env.PG_USER1,
      ssl: {
        ca: process.env.PG_CERT1
      }
    }

**Comment by charmander** [comment]
How about `console.log(process.env)`?

**Comment by chrispytoes** [comment]
@charmander Did that, it is definitely correct.

**Comment by charmander** [comment]
Is there a compile step involved? Please try reproducing this in a self-contained, plain Node script. Also, how about `Client` directly instead of `Pool`? `console.log(client)`?

**Comment by chrispytoes** [comment]
@charmander Yeah this works on its own using both `Pool` and `Client` running with ts-node. I copied the exact same `.env` file over to the example project for this test and it worked fine.
```
import dotenv from 'dotenv';
import { Pool } from 'pg';

dotenv.config();

const db = new Pool({
	database: process.env.PG_DB,
	port: +(process.env.PG_PORT || '25060'),
	host: process.env.PG_HOST,
	password: process.env.PG_PASSWORD,
	user: process.env.PG_USER,
	ssl: {
		ca: process.env.PG_CERT
	}
});

db.connect();
```
