### ISSUE TITLE
Option to turn off hostaddr in connection string

### ISSUE THREAD

**Issue by crystaldust** [brianc/node-postgres#2911]
I've been using pg in my project for a while and found the issue that when target postgresql host name resolution is updated, the client still try to send request to the older server address.

After looking into the code of the [connection string construction](https://github.com/brianc/node-postgres/blob/adbe86d4a057b942298cab1d19b341c67a94d922/packages/pg/lib/connection-parameters.js#L159) and the postgresql official docs on [hostaddr](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS), it's obvious that the `hostaddr` parameter in connection string is making that issue happen. 

While today it's pretty common that pg services(or any other services) are orchestrated in large clusters(like in Kubernetes, docker swarm) with dynamic name resolution. So it might be essential to give the client's `connect` function a parameter to turn on/off `hostaddr` when constructing connection string.

**Comment by sehrope** [comment]
Wouldn't that be the same as leaving out the hostaddr property entirely and specifying a host name so it's resolved dynamically each time a connection is created?

Both properties are only used when the connection is first established. Once the socket is created you cannot change it and would need to close the connection and create a new one to point to a new server. You can hide that behavior behind a connection pool that tests the connection and creates a new one on failure.
