### ISSUE TITLE
Documentation - pg-pool instalation

### ISSUE THREAD

**Issue by kvetoslavnovak** [brianc/node-postgres#2918]
If we only need pg-pool modules do we need to install it via `npm i pg-pool pg` or just `npm i pg-pool`?

Thank you for clarification.

**Comment by brianc** [comment]
https://github.com/brianc/node-postgres/tree/master/packages/pg-pool#install

Though for legacy reasons you can just do `npm i pg` and then

```
const { Pool } = require('pg')
```
as `pg` will bring the pool in automatically

**Comment by kvetoslavnovak** [comment]
Thank you very much for your explanation.
