### ISSUE TITLE
How about answering my question instead of just closing my issue? How can I have PR (2682) merged?

### ISSUE THREAD

**Issue by thijs** [brianc/node-postgres#2920]
Why was my issue just summarily closed without any answer to my question? I'd like to know how to get a PR (https://github.com/brianc/node-postgres/pull/2682) that is now more than a year old merged?

It's not as if the PR is spurious. It adds quite simple functionality (that is basically implemented exactly the same as for existing support for dynamic passwords) so that it becomes possible to use pg with a Postgres server running in AWS RDS that uses the AWS password rotation feature from AWS Secrets Manager.

If there is existing functionality to get this working, then fine, point me to that. But I don't think there is. So this is kind of a required feature to be able to use AWS pw rotation.

I've been running a patched version of pg with this merged in production for all this time, but I'd prefer this to just be supported out of the box by pg.

What gives?

**Comment by brianc** [comment]
I didn't see it opened or closed - I get enough github notifications I only check things on a set cadence right now (life is extremely busy) and unfortunately missed your original PR. I'm working on it now, thanks!
