### ISSUE TITLE
Lambda payload limit for pg-query-stream

### ISSUE THREAD

**Issue by dbauszus-glx** [brianc/node-postgres#2926]
I successfully setup a pg-query-stream example in a serverless lambda node.js invocation.

Instead of process.stdout I pipe the JSONStream directly to the Node HttpResponse.

This works as expected.

```js
const pg = require('pg')
var pool = new pg.Pool()
const QueryStream = require('pg-query-stream')
const JSONStream = require('JSONStream')

//pipe 1,000,000 rows to stdout without blowing up your memory usage
pool.connect((err, client, done) => {
  if (err) throw err
  const query = new QueryStream('SELECT * FROM generate_series(0, $1) num', [1000000])
  const stream = client.query(query)
  //release the client when the stream is finished
  stream.on('end', done)
  stream.pipe(JSONStream.stringify()).pipe(process.stdout)
})
```

However if I increase the payload the Lambda fails at the hard 6mb limit.

I would have thought that a stream can possibly bypass the payload limit.

**Comment by ngervasi** [comment]
Unfortunately you cannot trick the Lambda 6MB payload limit and neither the 10MB limit of API Gateway.
The only workaround I found is to stream to S3 and redirect the client to a presigned download URL expiring in a couple of minutes.

**Comment by dbauszus-glx** [comment]
@ngervasi  Thanks for the information. We have file up and download working for S3 buckets with signed URL. Do you have a starting point for information in regards to streaming from node-pg to S3?

**Comment by ngervasi** [comment]
Not for node-pg but a stream is a stream:

`const readable = tar.pack(`${path}/${dirName}`);
  const pipeline = readable
      .pipe(zlib.createGzip())
      .pipe(uploadStream(readable, s3KeyName,config.dbStorageClass));

pipeline.on('close', () => {
    // upload finished, do something else
    if(debug) console.debug('stream closed');
  })
  pipeline.on('error', async(error) => {
    // upload wasn't successful. Handle it
    console.error('Attachments upload error');
    await notifyAdmins(JSON.stringify(error));
    process.exit();
  })
`
`function uploadStream(readable, path, storageClass) {
  const body = new stream.PassThrough();
  let key = path.replace(config.dbBackupDir+'/','')
  key =  key.replace('/Databases','');
  key =  key.replace('Preserved/','');
  const s3 = new AWS.S3({
    signatureVersion: 'v4',
    accessKeyId: config.s3.key,
    secretAccessKey: config.s3.secret,
    region: config.s3.region
  });
  const params = {
    Bucket: config.s3.bucket,
    Key: key,
    Body: body,
    StorageClass: storageClass
  };
  s3.upload(params)
      .on('httpUploadProgress', progress => {
        if(debug) console.debug('progress', progress);
      })
      .on('error', async(error) => {
        // upload wasn't successful. Handle it
        console.error('S3 upload error');
        await notifyAdmins(JSON.stringify(error));
        process.exit();
      })
      .send( async (err, data) => {
        if(err) {
          await notifyAdmins(JSON.stringify(err));
          console.error(err);
          body.destroy(err);
        } else {
          console.log(`${key} uploaded`);
          body.destroy();
        }
      });
  return body;
}`
