### ISSUE TITLE
[Question/Help] Supported version for postgres 14

### ISSUE THREAD

**Issue by osamakhanedu** [brianc/node-postgres#2931]
Hi, I have a question. I am using sequelize version v5 and pg version 7. does it support postgres version 14?

**Comment by aspic-fish** [comment]
this lib supports 3.0 protocol version [source](https://github.com/brianc/node-postgres/blob/65ca2458fd0079f36a99a7752a7931483cd57ed6/packages/pg-protocol/src/serializer.ts#L22)
according to postgres [docs](https://www.postgresql.org/docs/current/protocol.html)
> This document describes version 3.0 of the protocol, implemented in PostgreSQL 7.4 and **later**.

and
> A single server can support **multiple** protocol versions

So yes it does.
