### ISSUE TITLE
INSERT INTO array of arrays params argument

### ISSUE THREAD

**Issue by dbauszus-glx** [brianc/node-postgres#2937]
I have an array of ufo sightings. Each entry in the array is an array of fields.

This works well:

```SQL
INSERT INTO ufo_sightings VALUES
('10/10/1999 22:30','casey key (north end of)','fl', 29.38421, -98.581082),
('10/10/1999 22:30','elgin','or', 29.38421, -98.581082),
('10/10/1999 23:45','lewiston','mi', 29.38421, -98.581082)
```

How can I supply the array of field value arrays as $1 to my query?

```SQL
INSERT INTO ufo_sightings VALUES $1
```

I tried to pass this array a params argument with the query but receiver a parser exception.
![image](https://user-images.githubusercontent.com/22201617/227592708-0604e3ed-73b2-40ed-bee5-8e059025e003.png)

**Comment by Igorgro** [comment]
Having similar problem. I'm trying to executed sql code like this:
```sql
WITH "idsList"("id") AS (VALUES ('9d2ec2eb-5bc2-46fe-b91f-ae6907e79f9a'), ('a44f3494-fe46-489a-bff1-cdffbd861ddc')) SELECT * FROM "idsList"
```

this is my code:
```typescript
const ids = [
  '9d2ec2eb-5bc2-46fe-b91f-ae6907e79f9a',
  'a44f3494-fe46-489a-bff1-cdffbd861ddc'
];

const params = [ids.map(id => [id])]
await client.query('WITH "idsList"("id") AS (VALUES $1) SELECT * FROM "idsList"', params);
```
but it throws the following error:
```
error: syntax error at or near "$1"
```

I tried different variants, for example:
```typescript
const params = [ids.map(id => `('${id}')`)]
```
or
```typescript
const params = [ids.map(id => `('${id}')`).join(', ')]
```
none of them works.

I also tried to make every values a separate parameter, like this:
```typescript
await client.query('WITH "candidateList"("id") AS (VALUES $1, $2) SELECT * FROM "candidateList"', params);
```
it doesn't work either. So, what is the correct way to pass arguments to `VALUES` clause (https://www.postgresql.org/docs/current/queries-values.html) ?

**Comment by Igorgro** [comment]
Having similar problem. I'm trying to executed sql code like this:
```sql
WITH "idsList"("id") AS (VALUES ('9d2ec2eb-5bc2-46fe-b91f-ae6907e79f9a'), ('a44f3494-fe46-489a-bff1-cdffbd861ddc')) SELECT * FROM "idsList"
```

this is my code:
```typescript
const ids = [
  '9d2ec2eb-5bc2-46fe-b91f-ae6907e79f9a',
  'a44f3494-fe46-489a-bff1-cdffbd861ddc'
];

const params = [ids.map(id => [id])]
await client.query('WITH "idsList"("id") AS (VALUES $1) SELECT * FROM "idsList"', params);
```
but it throws the following error:
```
error: syntax error at or near "$1"
```

I tried different variants, for example:
```typescript
const params = [ids.map(id => `('${id}')`)]
```
or
```typescript
const params = [ids.map(id => `('${id}')`).join(', ')]
```
none of them works.

I also tried to make every values a separate parameter, like this:
```typescript
await client.query('WITH "idsList"("id") AS (VALUES $1, $2) SELECT * FROM "idsList"', params);
```
it doesn't work either. So, what is the correct way to pass arguments to `VALUES` clause (https://www.postgresql.org/docs/current/queries-values.html) ?

**Comment by charmander** [comment]
https://github.com/brianc/node-postgres/issues/3029#issuecomment-1627624896
