### ISSUE TITLE
race condition: pool sometimes terminates idle connections that have been checked out from the pool

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [brianc/node-postgres#2938]
I don't have a small reproducer (yet), but I've observed a race condition in the pool portion of this library where it will sometimes terminate "idle" connections that have just been checked out from the pool. When attaching a debugger, I'm most commonly seeing it terminating connections that are in the midst of running `BEGIN`, which isn't too surprising given the patterns in my application.

**Comment by boromisp** [comment]
I've quickly skimmed through the code.

Getting an idle connection from the pool and stopping its idle timeout:

https://github.com/brianc/node-postgres/blob/65ca2458fd0079f36a99a7752a7931483cd57ed6/packages/pg-pool/index.js#L140-L141

The idle timeout:

https://github.com/brianc/node-postgres/blob/65ca2458fd0079f36a99a7752a7931483cd57ed6/packages/pg-pool/index.js#L357-L360

The `_remove(client)` method, used by the idle timeout:

https://github.com/brianc/node-postgres/blob/65ca2458fd0079f36a99a7752a7931483cd57ed6/packages/pg-pool/index.js#L154-L159

There's no async code in these sections, so both getting a new connection and dealing with an idle timeout happen in their own single tasks.

---

Actually, a more likely reason is that your idle TCP connections are quietly dropped (without `RST`), and the server running your code only finds out when it attempts to send the next query. For AWS and Azure, this seems to happen after 4-4.5 minutes of being idle.

If this is the cause of the issue, you need to set up TCP keepalives with a shorter initial delay, either on the PostgreSQL server config (https://www.postgresql.org/docs/current/runtime-config-connection.html#GUC-TCP-KEEPALIVES-IDLE) or in your code (https://github.com/brianc/node-postgres/blob/4b229275cfe41ca17b7d69bd39f91ada0068a5d0/packages/pg/test/unit/client/set-keepalives-tests.js).

**Comment by mgabeler-lee-6rs** [comment]
Some more context:
* This is happening in a CI run of mocha tests, the time from the start of the test run to the failure is (far) less than any TCP timeout
* When I was able to attach the debugger, I could see in the call stack it was the pool's idle timeout firing for the connection, not any TCP error. Specifically I can see the `tid = setTimeout(...` callback you quoted in the call stack.
* As part of debugging some past (long fixed) issues in this test suite I had left the pool set to a 100ms idle timeout (`idleTimeoutMillis`). Removing that setting (so it takes its default 10s value) hides this issue.
* Looking through other settings that affect the code in question, it's perhaps worth noting that I'm not using an explicit config for `connectionTimeoutMillis`

I'm wondering if there's a race condition where a timer may be committed to fire but hasn't fired yet, and so clearing the timeout isn't cancelling the call?

I agree this is very strange given the code all seems synchronous, and am trying to capture more details on what is going on.

**Comment by mgabeler-lee-6rs** [comment]
I think I figured out what's going on. One of the tests had a temporary use of sinon's faked timers mode, which is messing up the timers pg-pool is using to manage the connection idle timeout. Will close this out once I confirm that is the issue.

**Comment by mgabeler-lee-6rs** [comment]
That was the issue, sorry for the false positive!
