### ISSUE TITLE
Question about prepared statements

### ISSUE THREAD

**Issue by iccicci** [brianc/node-postgres#2940]
Hi @brianc ,

does `pg-pool` take advantage from [prepared statemets](https://www.postgresql.org/docs/current/sql-prepare.html) under the hood?

I mean: I need that following code

```typescript
(db: Pool) => {
  const client = await db.connect();
  const query = "SELECT * FROM table_a WHERE column_a = $1";

  const result1 = await client.query(query, [1]);
  const result2 = await client.query(query, [2]);
}
```

will produce following sequence of statements

```SQL
PREPARE plan_a (unknown) AS SELECT * FROM table_a WHERE column_a = $1;
EXECUTE plan_a(1);
EXECUTE plan_a(2);
```

but I wasn't able to find nothing related in the documentation.

My question is: does this happens automagically thanks to `pg` or `pg-pool` or should I do something explicitely?

Thank you in advace.

**Comment by charmander** [comment]
You need to [specify a name](https://node-postgres.com/features/queries#prepared-statements) to get automatic prepared statement reuse.

**Comment by iccicci** [comment]
I'm so noob! Thank you @charmander
