### ISSUE TITLE
pg: md5 algorithm triggering security issue in Contrast report

### ISSUE THREAD

**Issue by andrewtcymmer** [brianc/node-postgres#2943]
My objective opening this issue, is to determine whether it is reasonable to make a change in the `pg` package that makes the encryption algorithm <md5> for password exchange configurable, so that SHA-256 is an option to pass in as a parameter instead of the hardcoded md5. I am referencing the use of NodeJS `.crypto()` [in util.js line 168](https://github.com/brianc/node-postgres/blob/65ca2458fd0079f36a99a7752a7931483cd57ed6/packages/pg/lib/utils.js#L167-L169).

The reason why I am asking, is that an issue has shown up in a security report from our [Contrast Security](https://www.contrastsecurity.com/) integration. In this report, Contrast has identified that there is a risk to using any md5 hash for cryptography since it is easily broken with modern tools and hardware. If we have found it, then certainly others will also. For reference, my team is running a NodeJS TypeScript API with TypeORM and a Postgres database.

So far as I have done other research, Postgres itself does not accept any other encryption algorithms for password exchange than md5. I am basing this assumption off of the [documentation about message exchanges](https://www.postgresql.org/docs/current/protocol-flow.html), which it looks like the `pg` package is using md5 to implement. But there is also [scram-sha-256](https://www.postgresql.org/docs/current/auth-password.html) available to use, with the right [configurations on Postgres](https://github.com/brianc/node-postgres/issues/2661#issuecomment-1303697494). Can you also comment, based on your work, if the `pg` package’s password authentication would be limited by which algorithms Postgres recognizes?

The issue with MD5 is documented in [CWE-328](https://cwe.mitre.org/data/definitions/328.html). I have also included some screenshots containing the information we got from the Contrast report.

Thank you for your time. Kindly let me know if I may clarify anything. Also, I do recognize that I may have missed some details; please do let me know if I have misunderstood something about `pg` or Postgres itself.

<img width="1029" alt="Contrast - md5 hash alg - overview" src="https://user-images.githubusercontent.com/29125201/228885369-52ed2473-685c-4829-9e50-6c63005a1ad0.png">

<img width="1029" alt="Contrast - md5 hash alg - howtofix" src="https://user-images.githubusercontent.com/29125201/228885440-2196f476-83d5-4e96-8adc-2f450fc0bdf8.png">

<img width="1029" alt="Contrast - md5 hash alg - stacktrace" src="https://user-images.githubusercontent.com/29125201/228885482-99770b5d-3f3a-4299-9131-6b8a50734d4f.png">

**Comment by brianc** [comment]
scram-sha-256 is available and supported within `pg`.   

> Can you also comment, based on your work, if the `pg` package’s password authentication would be limited by which algorithms Postgres recognizes?

Yes. This driver only supports what postgres supports. Just like the JDBC driver, psql, libpq, etc...

You can also not even use `md5` "encryption" and pass your password in plaintext.  This is entirely dependent on how you use the driver & how you configure postgres.  Recommend you use SSL as well if you want more encryption/security on your connection.
