### ISSUE TITLE
Error: self-signed certificate in Heroku

### ISSUE THREAD

**Issue by RodeoAdrian** [brianc/node-postgres#2946]
Hello!

I have an API that was updated, I'm using now:

- node v18.15
- pg v8.5.1
- sequelize v6.29.3

The config I'm using is:

**sequelize.js**

```javascript
const baseConfig = {
  dialect: 'postgres',
  port: process.env.SQL_PORT,
  protocol: 'postgres',
  connectionTimeout: 0,
  logging: isTesting ? false : () => Boolean(process.env.SEQUELIZE_LOG),
  retry: { max: 1 },
  pool: {
    max: 70,
    min: 0,
    idle: 200000,
    acquire: 200000
  },
  dialectOptions: {
    encrypt: true,
    connectTimeout: 300000
  }
};

const prodConfig = Object.assign({}, baseConfig, {
  use_env_variable: 'DATABASE_URL', // <-- HEROKU ENV VAR
  logging: false,
  dialectOptions: {
    ssl: {
      require: true,
      rejectUnauthorized: false
    }
  }
});
```

Using `pg`:

```javascript
const { Client } = require('pg');

const env = process.env.NODE_ENV || 'development';
const config = require('./sequelize');

const connectionArgs = [];
if (env !== 'production') {
  connectionArgs.push(config[env]);
} else {
  connectionArgs.push(config.prodConfig); // <- CONFIG HERE
}

const client = new Client(...connectionArgs);

module.exports = client;
```

And the way I initialize the app is like this (using the exported client described above):

```javascript
import chalk from 'chalk';
import initServer from 'Config/express';
import db from 'Config/db';
import logger from 'Config/winston';
import { port } from 'Config/vars';

const { NODE_ENV = 'development', DEPLOYMENT_ENV = 'local' } = process.env;
db.connect(err => {
  if (err) {
    logger.error(`Error connecting to database ${err.stack}`); // <-- THE ERROR I GET
    process.exit(1);
  } else {
    ...
  }
});
```

I can see in papertrail, in the heroku dashboard this:
<img width="562" alt="Screenshot 2023-03-30 at 13 22 40" src="https://user-images.githubusercontent.com/97752751/228915713-d1ffe4ef-1b75-4865-b371-a78228c2d916.png">

So I can't connect the DB and I tried a lot of things and configurations:
- (both solutions) from here https://help.heroku.com/MDM23G46/why-am-i-getting-an-error-when-i-upgrade-to-pg-8
- this config https://devcenter.heroku.com/articles/connecting-heroku-postgres#connecting-in-node-js
- Even setting the Heroku's var `PGSSLMODE` to _no-verify_

I don't need a certificate, it's all handled by Heroku.

**I can't make the connection to the DB in the production server hosted by Heroku**. I don't know what else to try.
I even tried to downgrade the `pg` version to `7.18.2` but it seems that version doesn't work with node `v18.15`. It hangs and does nothing, it doesn't connect neither log nothing.

I contacted Heroku support and they don't know how to fix it neither, they keep telling me that I need to review this error with the `pg` package maintainers.

**Comment by charmander** [comment]
Where is sequelize being used? I only see `Client` direct from pg in that code, which expects `ssl` as a direct property of the config object and not inside `dialectOptions`. You should probably avoid mixing the two and test the connection/obtain a client object for whatever lower-level purposes via sequelize somehow.

**Comment by RodeoAdrian** [comment]
> Where is sequelize being used? I only see `Client` direct from pg in that code, which expects `ssl` as a direct property of the config object and not inside `dialectOptions`. You should probably avoid mixing the two and test the connection/obtain a client object for whatever lower-level purposes via sequelize somehow.

sequelize is being used to run migrations when the API is deployed and then to make queries, not for the connection to the DB
btw, I tried this config:

```javascript
const prodConfig = Object.assign({}, baseConfig, {
  use_env_variable: 'DATABASE_URL',
  logging: false,
  ssl: {
    require: true,
    rejectUnauthorized: false
  }
}
```

I still get the same issue.

And I did what you mentioned and worked! I'm using the sequelize package now to make the first connection to the DB instead of `pg` package.

Info here: https://sequelize.org/docs/v6/getting-started/#connecting-to-a-database
However, the question still remains. Because I couldn't connect with the `pg` package. I will close the issue.

**Comment by charmander** [comment]
Please make a minimal pg-only reproducer if you’re still curious about this. With so many mixed used/unused options, environment variables, configuration paths, and confounding libraries, it’s too hard to definitively identify the problem. In isolation, the documented option of `ssl: {rejectUnauthorized: false}` *does* work to accept an arbitrary self-signed certificate.

**Comment by flyingn1nja** [comment]
I have issues with it as well deploying on Heroku. 

My code:

CODE:
```typescript
const pool = new Pool({
    connectionString: config.DATABASE_URL,
    idleTimeoutMillis: 30000,
    connectionTimeoutMillis: 2000,
    ssl: {
        rejectUnauthorized: false,
    },
})
```

DATABASE_URL: postgres://<username>:<password>@<host_url>/<db_name>?sslmode=require

**Comment by flyingn1nja** [comment]
> Please make a minimal pg-only reproducer if you’re still curious about this. With so many mixed used/unused options, environment variables, configuration paths, and confounding libraries, it’s too hard to definitively identify the problem. In isolation, the documented option of `ssl: {rejectUnauthorized: false}` _does_ work to accept an arbitrary self-signed certificate.

This does not work for me unfortunately.

**Comment by charmander** [comment]
@flyingn1nja `sslmode=require` in the connection string [overwrites the entire `ssl` option with `true`](https://github.com/brianc/node-postgres/blob/b1a8947738ce0af004cb926f79829bb2abc64aa6/packages/pg/lib/connection-parameters.js#L56), unfortunately. Remove `sslmode=require` from the connection string and it should work.

**Comment by flyingn1nja** [comment]
> @flyingn1nja `sslmode=require` in the connection string [overwrites the entire `ssl` option with `true`](https://github.com/brianc/node-postgres/blob/b1a8947738ce0af004cb926f79829bb2abc64aa6/packages/pg/lib/connection-parameters.js#L56), unfortunately. Remove `sslmode=require` from the connection string and it should work.

Yes, figured that out. Thanks!
