### ISSUE TITLE
Disable JSON type processing completely

### ISSUE THREAD

**Issue by B4nan** [brianc/node-postgres#2951]
For context: I am using node-postgres in MikroORM, where I am handling type conversion explicitly. JSON columns were always a pain, because libraries like to parse the response to objects, and never really handle the fact that it can be something else too correctly - the problematic cases are e.g. a string value.

Now I decided I want to disable this JSON conversion completely and handle it on the ORM side, where I have the full metadata available. I tried to use `TypeOverrides`:

```ts
const types = new TypeOverrides();
[114, 3802].forEach(oid => types.setTypeParser(oid, str => str)); // json, jsonb types
// and added `types` to the options
```

Now this disables the conversion of object values to JS objects, but apparently, there is still something that converts a string scalar (stored as JSON) to the string value - in other words, I store `'"foo"'` but I am getting just `'foo'` back and I want to disable that too - as I want to call `JSON.parse` on the value myself from the ORM, and now it fails because the JSON is already parsed.

Is there anything I am missing? 

-----

This is what I am getting back from the database, on the lowest level where I am mapping database results to a common shape across the drivers:

```
Result {
      command: 'SELECT',
      rowCount: 1,
      oid: null,
      rows: [ { id: 1, value: 'test' } ], // and I want to see `'"test"'` in here, as that is what i was inserting to the database
      fields: [
        Field {
          name: 'id',
          tableID: 16444,
          columnID: 1,
          dataTypeID: 23,
          dataTypeSize: 4,
          dataTypeModifier: -1,
          format: 'text'
        },
        Field {
          name: 'value',
          tableID: 16444,
          columnID: 2,
          dataTypeID: 3802,
          dataTypeSize: -1,
          dataTypeModifier: -1,
          format: 'text'
        }
      ],
      _parsers: [ [Function: parseInteger], [Function: bound parse] ],
      _types: TypeOverrides {
        _types: {
          getTypeParser: [Function: getTypeParser],
          setTypeParser: [Function: setTypeParser],
          arrayParser: [Object],
          builtins: [Object]
        },
        text: {},
        binary: {}
      },
      RowCtor: null,
      rowAsArray: false
    }
```

--- 

And one more note - I am rather confident this is not a problem in the ORM code, as it works just fine with SQLite, which never tried to handle JSON values. But the same problem is present with MySQL (where I am also disabling the JSON parsing explicitly). I'll be happy to prepare a minimal repro if it's needed.

**Comment by B4nan** [comment]
Here is a minimal repro:

```ts
const { Client } = require('pg');
// side note: why is this not exported from root? apparently its not even documented, took me some time to find it
const TypeOverrides = require('pg/lib/type-overrides');

const types = new TypeOverrides();
[114, 3802].forEach(oid => types.setTypeParser(oid, str => str)); // json, jsonb types
const client = new Client({
  database: 'test',
  user: 'postgres',
  types,
});
await client.connect();

// user table as `id: int` and `value: jsonb` or `json`

await client.query('insert into "user" ("value") values ($1)', ['"foo"']);
const res = await client.query('select * from user');
console.log(res.rows[0].value); // should be '"foo"' but is just 'foo'

// and this is what i want to do with the value, which obviously fails
// const parsed = JSON.parse(res.rows[0].value);

await client.end();
```

**Comment by B4nan** [comment]
Any updates on this? I'd appreciate _some_ answer, anything is better than nothing...

**Comment by brianc** [comment]
Sorry about the delay...dumb question here but what if you do `select value::text from user` - wonder if postgres is doing something to the value? Does it come out as `"foo"` when you run `select * from user` in psql?

**Comment by B4nan** [comment]
Yes, that works as expected, I've been using that as a workaround in some places already. And to be frank, now I am not even able to reproduce the original issue 🤦 

Sorry about the noise, will close this now and reopen if I find a way to reproduce again.

**Comment by brianc** [comment]
> Sorry about the noise

no worries! never huts to ask! (other than my inbox being exploded 24/7 but that's the life 😄 )
