### ISSUE TITLE
How to reuse queries?

### ISSUE THREAD

**Issue by sbettwieser** [brianc/node-postgres#2956]
If I have some query which I need to call many times with different parameter values, what would be the best way to do so?

I looked at the example given for [prepared statements](https://node-postgres.com/features/queries#prepared-statements) in the docs, but that doesn't seem like it would work for having different parameters, unless I'm misunderstanding.

**Comment by brianc** [comment]
If the query text remains the same, then adding `{name: 'whatever'}` to the query config will skip the "parse" query execution step where the query planning happens. It can have a performance impact in some niche situations.  If the number, order, or types of your parameters change then I'd imagine the query text would also change.



> If I have some query which I need to call many times with different parameter values, what would be the best way to do so?

"best" varies from app to app, but when in doubt keep it simple and just send the text and params every time!  For reference we have some pretty big queries in our apps and i usually don't name them & used prepared statements...easier to just not care and the overhead added is literally like 0 to 1 millisecond.
