### ISSUE TITLE
node returns 0 for numeric value 0.0268

### ISSUE THREAD

**Issue by narendra315** [brianc/node-postgres#2957]
I have a column in postgres table of numeric data type which has value 0.0268. I am trying to retrieve this value using this package but the output i am getting in the node is "0".

I've tried casting it as text and other data types to resolve this but nothing has worked so far.

**Comment by ngervasi** [comment]
Try this:

`// NUMERIC
    pg.types.setTypeParser(1700, function(val) {
      return val === null ? null : parseFloat(val)
    });`

**Comment by narendra315** [comment]
Hi, Thanks for responding @ngervasi
I've already tried this, doesn't work.

**Comment by narendra315** [comment]
sorry my bad, mixed up ids from difference columns and was referring to wrong records.
