### ISSUE TITLE
Pool parameters are ignored

### ISSUE THREAD

**Issue by naor-navina** [brianc/node-postgres#2963]
I upgraded my project from pg 7.18.2 to pg 8.10.0.
I'm using the Pool object.
It seems like it ignores the parameters I give him (at least "host" seems to be ignored) and it's using the PGHOST environment variable instead and if there is none, it just fails.

Node.js: 18.x (latest)

**Comment by brianc** [comment]
Can you include a self-contained script to replicate the problem? This sounds like an error on your side as the pool parameter names haven't changed almost ever.
