### ISSUE TITLE
bug!！ connectionString prot != 5432,   connection failed   

### ISSUE THREAD

**Issue by xxbld** [brianc/node-postgres#2966]
navicat  use any port  , successed
but node-postgres (version ^8.9.0 )
"postgres://postgres:xx@xxxx:5432/osm" successed
"postgres://postgres:xx@xxxx:10000/osm" failed   

AssertionError [ERR_ASSERTION]: unknown message code: 10
 at Parser.handlePacket (xxx\node_modules\.pnpm\pg-protocol@1.6.0\node_modules\pg-protocol\dist\parser.js:140:34)
    at Parser.parse (xxx\node_modules\.pnpm\pg-protocol@1.6.0\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (xxx\node_modules\.pnpm\pg-protocol@1.6.0\node_modules\pg-protocol\dist\index.js:11:42)

**Comment by charmander** [comment]
Is it a non-PostgreSQL database?

**Comment by xxbld** [comment]
> Is it a non-PostgreSQL database?

is pg  ！！
PostgreSQL 14.3, compiled by Visual C++ build 1914, 64-bit

**Comment by brianc** [comment]
If navicat is able to connect on any port it must have some internal logic to fall back to `5432` if it fails to connect on the invalid port. I'm fairly certain you cannot connect to postgres over the port other than it's bound to / listening on.  Similarly you cannot connect to a database if you don't include the correct host (though various drivers will fall back to using localhost or the hostname of the current machine if you don't supply a host).  Note `5432` is the default postgres port and if you don't specify `5432` node-postgres will use this port as default.
