### ISSUE TITLE
v8.11.0 UnhandledSchemeError when bundling with Webpack

### ISSUE THREAD

**Issue by andrew-pledge-io** [brianc/node-postgres#2975]
This [line](https://github.com/brianc/node-postgres/blob/14b840e96e57fc0617b5c4758f6318f774148ee4/packages/pg-cloudflare/src/index.ts#L1) introduced in [this PR](https://github.com/brianc/node-postgres/pull/2971) is causing errors in Webpack builds.

```
Webpack compilation failed:
in cloudflare:sockets
  Module build failed: UnhandledSchemeError: Reading from "cloudflare:sockets" is not handled by plugins (Unhandled scheme).
  Webpack supports "data:" and "file:" URIs by default.
  You may need an additional plugin to handle "cloudflare:" URIs.
```

This occurred after a minor update to the `pg` package from `v8.10.0` to `v8.11.0` when the `pg-cloudflare` package was added as an optional dependency.

For now, we've reverted to `v8.10.0`.

I expect this will affect a lot of people using Webpack as they start to update.

**Comment by elithrar** [comment]
cc @petebacondarwin

**Comment by irvinebroque** [comment]
@andrew-pledge-io — which version of Webpack are you using, where you hit this error?

I think this relates back to https://github.com/webpack/webpack/issues/15741 — and declaring `cloudflare:sockets` as an [external](https://webpack.js.org/configuration/externals/) in Webpack may help?

**Comment by petebacondarwin** [comment]
Here is a minimal webpack setup that should work with the latest version:

```js
const path = require("path");
const webpack = require("webpack");

module.exports = {
  entry: "./src/index.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  target: "node",
  mode: "development",
  plugins: [
    new webpack.IgnorePlugin({
      resourceRegExp: /^pg-native$|^cloudflare:sockets$/,
    }),
  ],
};
```

**Comment by petebacondarwin** [comment]
I put together a PR that I think should make this just work "out of the box" for everyday users of `pg`. See #2978.

**Comment by ravdeep-carechain** [comment]
Getting same error :)

**Comment by sondr3** [comment]
This also fails for me when using Kysely together with NextJS, had to revert to 8.10 as well.

**Comment by Harsh2509** [comment]
Ahm, I am using postgres server from docker image and getting same error. Isn't is solved yet?

**Comment by RomanDenysov** [comment]
@andrew-pledge-io 

It helps me:
- https://authjs.dev/getting-started/migrating-to-v5#edge-compatibility
- https://authjs.dev/guides/edge-compatibility#the-problem
