### ISSUE TITLE
 query works in pgAdmin but not in node-postgres!

### ISSUE THREAD

**Issue by Baradelli** [brianc/node-postgres#2985]
I dont know why  this query works in pgAdmin BUT when i use node-postgres the query never return a result or error? why? has any sense?

node      v14.21.3
postgres 9.0.4

I dont know why but when i run the query in my localhost works and when i run the query in AWS dont work.

Has anyone ever experienced this.

**Comment by charmander** [comment]
This doesn’t have enough detail to be answerable. I suggest reproducing the issue in a short, self-contained script and posting it here.
