### ISSUE TITLE
Warning for usage of pg-format in docs

### ISSUE THREAD

**Issue by jaads** [brianc/node-postgres#2986]
In the docs ([here](https://node-postgres.com/features/queries#parameterized-query)) it is recommended to use [node-pg-format](https://www.npmjs.com/package/pg-format) for parameterized identifiers. However this package is no longer maintained and hence not really an option for production systems. 

Therefore it might be best to warn the reader of the docs that this package is not actively maintained or maybe even remove the suggestion completely as it isn't really an option.

**Comment by charmander** [comment]
> However this package is no longer maintained and hence not really an option for systems production.

I wouldn’t rule it out. It’s not something that inherently needs much maintenance.

**Comment by charmander** [comment]
pg doesn’t have a real ESM module yet and and the way it’s currently exported has some issues with the Node compatibility approach, so for now you need

```javascript
import pg from 'pg';
const { escapeIdentifier } = pg;
```

**Comment by jaads** [comment]
Thanks! I tried this but it did not work either. I investigated a bit and when looking at [`pg/lib/index.js`](https://github.com/brianc/node-postgres/blob/4dbf1af06976ed6ea4f4c09b9caf620396be2de1/packages/pg/lib/index.js#LL27C33-L27C33) I would assume that it should work. It looks like this:
```javascript
var PG = function (clientConstructor) {
  this.defaults = defaults
  this.Client = clientConstructor
  this.Query = this.Client.Query
  this.Pool = poolFactory(this.Client)
  this._pools = []
  this.Connection = Connection
  this.types = require('pg-types')
  this.DatabaseError = DatabaseError
  this.escapeIdentifier = escapeIdentifier
  this.escapeLiteral = escapeLiteral
}
````
But when looking in my `node_modules` folder, in `node_modules/pg/lib/index.js` those last two lines where the escape functions should be are actually missing:
```javascript
var PG = function (clientConstructor) {
  this.defaults = defaults
  this.Client = clientConstructor
  this.Query = this.Client.Query
  this.Pool = poolFactory(this.Client)
  this._pools = []
  this.Connection = Connection
  this.types = require('pg-types')
  this.DatabaseError = DatabaseError
}
```
it seems to be now bundled correctly. If you give me a hint how to fixed that, I could do to :)

**Comment by jaads** [comment]
closing this in favor of #3001
