### ISSUE TITLE
Invalid URI error is thrown when password of connection string ends in a '/'

### ISSUE THREAD

**Issue by michihupf** [brianc/node-postgres#3013]
When trying to connect to a database with a user whose password ends in a '/' the client throws an error on connect:
Example connection string: `postgres://test:abc/@mydb.de:5432/mydb`

This should not be happening as this should be a valid connection string.

**Comment by charmander** [comment]
That’s a “valid” connection string (according to libpq), but the password doesn’t end with `/`. `test` is the host, `abc` is the port, `@mydb.de:5432/mydb` is the database name.

You need to URL-encode the password; `postgres://test:abc%2f@mydb.de:5432/mydb` will work as you expect in both libpq and pg.
