### ISSUE TITLE
Localhost VS. Docker

### ISSUE THREAD

**Issue by ThomeB** [brianc/node-postgres#3019]
I use the a client instance to make a connection to my database.
```
client = new Client({
            host: process.env.PG_HOST,
            port: parseInt(process.env.PG_PORT),
            user: process.env.PG_USER,
            password: process.env.PG_PASSWORD,
            database: process.env.PG_DATABASE
        })

await client.connect()
    .then(() => console.log('Client CONNECTED'))
    .catch((err) => console.error('connection error: ', err.stack))
```

I use an express app in node.js to handle my routes and other logic pertaining to the information retrieved/stored.

Now when I am running my web service in localhost on windows, it works flawlessly.
When I go to containerize my webservice I get: 

> connection error:  Error: getaddrinfo ENOTFOUND "**database host address**" at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)

I am just so confused as to whether or not this is a docker issue or a node-postgres issue that is preventing it from connecting to the db? I am not getting any other errors/warnings/cautions on the container.

The containers run debian linux.

Disclaimer: I am a junior developer and I apologize if I post this question out of ignorance or not catching something in the documentation.

**Comment by brianc** [comment]
I think on windows "out of the box" postgres only accepts requests from localhost. You'll need to configure postgres to allow the docker host to access it.  I _think_...it's been ages since I've used docker on windows. Either way, prolly a local config issue & not an issue w/ `pg`. I do wish you the best though!
