### ISSUE TITLE
Get Enum values from passed paramter

### ISSUE THREAD

**Issue by ChrisUntil** [brianc/node-postgres#3027]
Hello guys,

I was wondering if it was possible to do a request in order to list the values of a specific enum type passed as a parameter.

Essentially I would like to do such a query:

```
SELECT
    unnest(
        enum_range(NULL::$1)
    ) AS values
```
    
However, when I try to do that, it doesn't understand the value of $1, as I pass a string. Is there a way to pass a parameter as the type ?

I would like to avoid having one query per enum type, and just have a generic one.

Thanks !

Chris

**Comment by charmander** [comment]
https://github.com/brianc/node-postgres/issues/2259#issuecomment-650805343
