### ISSUE TITLE
How to pass multiple sets of parameters for insert

### ISSUE THREAD

**Issue by PeterWone** [brianc/node-postgres#3029]
Could you clarify/refer to docs for how parameters should be passed for this sort of query

```sql
INSERT INTO MyTable
( Column1, Column2, Column3 )
VALUES
('John', 123, 'Lloyds Office'),
('Jane', 124, 'Lloyds Office'),
('Billy', 125, 'London Office'),
('Miranda', 126, 'Bristol Office');
```

Would an array of arrays work or is this not a supported mode?

**Comment by PeterWone** [comment]
OK if it's a duplicate what's the other question? I'd very must like to read the answers

**Comment by PeterWone** [comment]
But there aren't any. I'll close it myself.

**Comment by charmander** [comment]
I don’t have time to look for the duplicates right now. Look harder or be patient. Keywords: `unnest`, `jsonb_to_recordset`

**Comment by PeterWone** [comment]
@charmander I meant there aren't any answers on the duplicate which I already found, the finding of which is what prompted me to accept that it was a true duplicate and close this issue. 

I notice that there is support for transactions. In terms of efficiency it would be best to open a txn, issue a bunch of inserts and commit the txn resulting in one index rebalance. The reason wanted to issue a single insert with a bunch of value clauses is ... I think I just worked out how to do this without risking injection attack. I shall close this again and code an experiment. If my little epiphany pays off I will post an answer on the other version of this question.

**Comment by charmander** [comment]
Here’s how to insert multiple rows from parameters
- with `jsonb_to_recordset`: https://github.com/brianc/node-postgres/issues/1644#issuecomment-595231696
- with `unnest`: https://github.com/brianc/node-postgres/issues/1644#issuecomment-387961410

**Comment by PeterWone** [comment]
OK yours is better. Thank you!
