### ISSUE TITLE
cursor documentation is incomplete

### ISSUE THREAD

**Issue by revington** [brianc/node-postgres#3034]
Url https://node-postgres.com/apis/cursor#cursorreadrowcount-number--promisepgresult

>If the cursor has read to the end of the result sets all subsequent calls to cursor#read will return a 0 length array of rows. Calling read on a cursor that has read to the end.
>
>Here is an example of reading to the end of a cursor:

What does it happen when we call `read` when a cursor has read to the end?

**Comment by brianc** [comment]
> What does it happen when we call `read` when a cursor has read to the end?



> If the cursor has read to the end of the result sets all subsequent calls to cursor#read will return a 0 length array of rows. Calling read on a cursor that has read to the end.

I'm pretty sure that's in the documentation?
