### ISSUE TITLE
Is custom Client class supported by pg-pool?

### ISSUE THREAD

**Issue by devinivy** [brianc/node-postgres#3035]
I noticed that pg-pool's constructor allows a custom `Client` class to be passed to it ([link](https://github.com/brianc/node-postgres/blob/cf24ef28ee2134b63576afba341452f8adfb8a4d/packages/pg-pool/index.js#L94)), which turns out to be quite useful!  I am interested to know if this interface is considered to be stable.  If it is stable, I'd be happy to contribute an update to the docs to note it.

**Comment by charmander** [comment]
Yes, it is

**Comment by devinivy** [comment]
Got it, thanks you!
