### ISSUE TITLE
TSL (SSL) connection needs 2 connections initially?

### ISSUE THREAD

**Issue by jacobbogers** [brianc/node-postgres#3045]
Hi, I am diving throught the source code, and I wanted to check if my assumption is right.

Especially these 2 lines support my assumption

- 1.  this is what seems to always happen, [always create a socket][line1]
- 2. it wait for the server to respond with "ssl" supported" then [replaces (code) the socket with one of created by (evantually) `tsl.connect()`][line2]

Is it really needed to to connect to postgres non-tsl and then secondly with tsl?

[line1]: https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/connection.js#L19
[line2]: https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/connection.js#L100

**Comment by charmander** [comment]
TLS is a layer on top of bidirectional byte streams, like the TCP and UDS connections pg creates (or any arbitrary `net.Socket` that you pass in). It doesn’t create a second connection; it [uses the socket from the first one](https://github.com/brianc/node-postgres/blob/58865b2c04777e3f79d6a90df3ab83ca65382730/packages/pg/lib/connection.js#L84). Yes, it’s needed.

**Comment by jacobbogers** [comment]
@charmander 
Yes I see the node  [tsl.connect][node-tsl-connect] takes an already opened socket to intitiate a tsl handshake

[node-tsl-connect]: https://nodejs.org/api/tls.html#tlsconnectoptions-callback
