### ISSUE TITLE
'Pool' can only be imported by using 'import Pool = require("pg-pool")' or a default import

### ISSUE THREAD

**Issue by prajeesh-mp** [brianc/node-postgres#3046]
I was trying to do connection pooling in my node js typescript project, but i was unable to import the library.
Here's the code i've tried. I was getting type error

![image](https://github.com/brianc/node-postgres/assets/75924306/67369d9b-59d9-4907-9781-96b175e46a32)

```
import { Pool } from "pg-pool";


class DatabaseService {
    private static instance: DatabaseService;
    private pool: Pool;

    constructor() {}
}

```

I'm using 

```
    "pg": "^8.11.0",
    "pg-pool": "^3.6.1"
    
    // dev dependencies
    "@types/pg": "^8.10.2",
    "@types/pg-pool": "^2.0.3",
```

Node JS - 18.16.1
npm - 9.5.1
PostgreSQL - 14.8

**Comment by charmander** [comment]
`Pool` is a named export from the *pg* package, preconfigured with pg’s Client. That’s generally what you should import, as recommended in https://node-postgres.com/guides/project-structure. The pg-pool package only needs to be used directly if you’re overriding the client type or making other low-level changes, and yes, [the pool type is intentionally a default export from that package](https://github.com/brianc/node-postgres/blob/a84ebb3fe85edafb1b358965bdb5e3de58b12c5d/packages/pg-pool/README.md#use).
