### ISSUE TITLE
Multiple Build Errors When Installing and Using 'pg'

### ISSUE THREAD

**Issue by Feierstein1** [brianc/node-postgres#3047]
Node version : v16.13.2
npm pg version: ^8.2

According to 'https://node-postgres.com/' documentation:
**"At the time of this writing node-postgres is compatible with node 8.x, 10.x, 12.x and 14.x To use node >= 14.x you will need to install pg@8.2.x "**

When I run my dev server and try to instantiate a variable using 'pg', I get a lot of errors:
For "Module not found: Error: Can't Resolve"
- 'pg-native'
- 'fs'
- 'assert'
- 'dns'
- 'net'
- 'crypto'
- 'util'
- 'tls'
- 'stream'
- 'path'
- 'buffer'

I am currently using "webpack": "^5.68.0" and I did go ahead and installed npm for 'assert' and 'util' since I got this error for them:
**BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.**

I added 'resolve:{ fallback: { ... } } to my webpack in an attempt to resolve these issues but it did not work.

Am I missing something? Seems like either there are a lot of missing dependencies or I need to configure my webpack better, but not really sure where to go from here.

My current package.json:
"dependencies": {
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@mui/icons-material": "^5.11.16",
    "@mui/material": "^5.13.4",
    "@mui/styles": "^5.13.2",
    "@mui/x-data-grid": "^6.8.0",
    "babel-cli": "6.24.1",
    "babel-core": "6.25.0",
    "babel-loader": "7.1.1",
    "babel-plugin-transform-class-properties": "6.24.1",
    "babel-plugin-transform-object-rest-spread": "6.23.0",
    "babel-polyfill": "6.26.0",
    "babel-preset-env": "1.5.2",
    "babel-preset-react": "6.24.1",
    "css-loader": "^6.5.1",
    "express": "4.15.4",
    "file-loader": "^6.2.0",
    "firebase": "^8.9.1",
    "history": "4.10.1",
    "lodash": "^4.17.21",
    "markdown-loader": "^8.0.0",
    "markdown-to-jsx": "^7.2.1",
    "mini-css-extract-plugin": "^2.5.3",
    "moment": "2.18.1",
    "normalize.css": "7.0.0",
    "numeral": "2.0.6",
    "pg": "8.7.3",
    "postcss": "^8.4.6",
    "postcss-loader": "^6.2.1",
    "react": "^16.14.0",
    "react-addons-shallow-compare": "15.6.0",
    "react-dates": "12.7.0",
    "react-dom": "^16.14.0",
    "react-modal": "2.2.2",
    "react-redux": "5.0.5",
    "react-router-dom": "4.1.2",
    "redux": "3.7.2",
    "redux-mock-store": "1.2.3",
    "redux-thunk": "2.2.0",
    "sass": "^1.49.7",
    "sass-loader": "7.3.1",
    "style-loader": "0.18.2",
    "svg-url-loader": "^8.0.0",
    "uuid": "3.1.0",
    "validator": "8.0.0",
    "webpack": "^5.68.0",
    "webpack-cli": "^4.9.2"
  },
  "devDependencies": {
    "cross-env": "5.0.5",
    "dotenv": "^14.2.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.6",
    "enzyme-to-json": "^3.6.1",
    "jest": "20.0.4",
    "raf": "^3.4.1",
    "react-test-renderer": "^16.14.0",
    "webpack-dev-server": "2.5.1"
  }
}

**Comment by charmander** [comment]
If you’re trying to use pg in web browsers on the frontend: you can’t[^1], it’s for backend Node.js.

If you’re trying to use pg on Node: you need to configure webpack to target Node. I imagine a dev server wouldn’t be involved.

[^1]: without a good reason and effort

**Comment by Feierstein1** [comment]
@charmander Thank you for the response, I think I understand better. So its my understanding that you cannot use pg in browser and that's understandable. Does this mean that pg is not capable of being used in a React application at all? I wanted to grab data and store it on my SQL database but based on what you said that is not possible correct?

**Comment by charmander** [comment]
You can’t connect to PostgreSQL directly from React targeting the browser, but you could expose it over an HTTP API (a very typical approach) to a React-based frontend, or use it with server-side rendered React. There’s nothing particular to pg or React here; the same relationship applies to every pair of generally-frontend and generally-backend tools.
