### ISSUE TITLE
Remove dependency to crypto so node-postgres can run on the edge

### ISSUE THREAD

**Issue by harrispap03** [brianc/node-postgres#3050]
I'm using ``node-postgres`` alongside with ``drizzle-orm``.  

I'd like to be able to make queries on the edge, though that's not possible due to the dependency of ``node-postgres`` to the ``crypto`` library.

Is there a chance it can be removed on the future so it can run on the edge ?

Edge reference [here](https://vercel.com/docs/functions/edge-functions/edge-runtime#check-if-you-re-running-on-the-edge-runtime)

**Comment by charmander** [comment]
- As of #2971, the Web Crypto API is already used instead of the Node crypto module where possible.

- > node_modules can be used, as long as they implement ES Modules and do not use native Node.js APIs

    though? pg isn’t ESM-based, and uses other Node APIs, like `net`. pg includes a Node-like API wrapper for Cloudflare Workers, but I don’t even see the ability to make TCP connections in the linked documentation.

- (Is your PostgreSQL server also on the edge?)

**Comment by harrispap03** [comment]
Hmm, that's interesting, it seems there are many roadblocks to get this working on the edge.

To be fair I haven't decided on the location of my db.  It could be on the edge.  I guess in this case I should use some other driver from drizzle

**Comment by savelichalex** [comment]
I had the same problem for Cloudflare Pages, I ended up patching the package, removing any `require('crypto')` calls, since this was the cause. Basically my edge function fell even before execution of the function logic itself, it fell in the `import` stage.
