### ISSUE TITLE
Running client.query inside loops

### ISSUE THREAD

**Issue by elhananjair** [brianc/node-postgres#3051]
Hello there, I am playing with node-postgres package, I have a table with ID and phone, and I want to insert multiple phone numbers from the array but it is not working as I expected, Any support is appreciated. 

```
let pnum = ['23144224', '23155323', '23148839', '231983323']
connect_db()
    .then(() => console.log("Successfully Connected"))
    .then(() => {
        pnum.foreach((num) => client.query('INSERT INTO myschema.phonelist (num) VALUES (num);'))
    })
    .then(results => console.log(results))
    .catch(e => console.log(e.detail))
    .finally(() => client.end())
```

What is the good way to achieve this with pg?

**Comment by charmander** [comment]
I don’t think this is an issue tracker kind of question.

**Comment by elhananjair** [comment]
Yeah, that's true sorry. I was just confused and wanted help.

**Comment by brianc** [comment]
I'd recommend using async/await

```
async function insertThings() {
  await connect_db()
  for (const num of pnum) {
   await client.query('INSERT INTO bla bla')
  }
}
```

Doing async work w/o async await in node is a huge pain

**Comment by elhananjair** [comment]
@brianc Thank you, I will try it with that!
