### ISSUE TITLE
Query returning less number of rows than it should

### ISSUE THREAD

**Issue by acehand** [brianc/node-postgres#3057]
I am building a serverless Lambda express setup with nodejs/ Serverless Framework.  When I try queries on tables with a lot of data, I get back less number of rows than I should be getting for such queries. When I run the same query on psql/ data grip, it takes a 4 mins to run, but I get back 51 rows. Here I am getting 4 rows. 

I have double verified the connection, I am talking to the Correct database, correct table etc. Event a simple query like 
`select * from A where A.customer_id = "xxx" LIMIT 200` , is returning only 70 rows. These table is huge. But I have been able to query this table from my other nodejs non lambda application. 

What I am not understanding is this 
 - if the issue is with lambda or memory, shouldnt I be getting a memory based error ? 
 -  Is there something basic I am missing to configure to query tables that take up memory ? 

PS -  I tried using cursor true, similar results.

**Comment by charmander** [comment]
Barring a serious bug, pg will never silently ignore an error and return an incomplete result to you. The problem is probably caused by something else, like whatever #2519 was.

**Comment by acehand** [comment]
My query is this - 
```
select count(1) from events where customer_id = 'xxx' and job_id not like '\_\_%' limit 200
```
For this, instead of 200 rows, am getting 70 rows. 

My escaping is not correct may be ? Is there something I am missing here ?

**Comment by acehand** [comment]
Well @charmander thanks for the introspect and confirmation. I should have probably thought of this sooner, but you pointing me to that link, suddenly made me want to think about escaping with `\\_` instead of just 1 backlash. And that worked. 

So DataGrip lets you use 1 backslash where in the query from node should be like this 

```
SELECT count(1) from events 
WHERE customer_id = 'xxx' 
AND job_id not like '\\_\\_%' limit 200

```
