### ISSUE TITLE
How do I modify the database in connection config

### ISSUE THREAD

**Issue by wflixu** [brianc/node-postgres#3058]
At the beginning of the connection, I did not know the database name, which I will need later. 
How do I modify the database in the connection?

I tried to write it like this, but it didn't work:

```
// this 
client.database = datname;
// or event this
 // @ts-ignore
client.connectionParameters.database = datname;
   
 const res = await client.query({
      text: 'SELECT * FROM information_schema.schemata;',
    });

```

**Comment by charmander** [comment]
You can’t; the PostgreSQL protocol doesn’t support it. Make a new connection.
