### ISSUE TITLE
ERROR [ExceptionHandler] getaddrinfo EAI_FAIL postgres

### ISSUE THREAD

**Issue by longnnt** [brianc/node-postgres#3065]
![image](https://github.com/brianc/node-postgres/assets/47670554/e14b9124-fba5-46a9-b121-2f2ef3318b61)
- I deploy posgres in Render and I can't connect to DB, I have an issue like title.

**Comment by charmander** [comment]
- your entire URI is in the `host` field, which is incorrect
- you probably need to change that password now that you’ve posted it in public
