### ISSUE TITLE
Add queryText in DatabaseError

### ISSUE THREAD

**Issue by AugustoPreis** [brianc/node-postgres#3069]
I have an errorHandler middleware to handle pg DatabaseError

this middlewares take infos from error (table, column, error message) and save to handle after

but it would be very useful if the DatabaseError class had a property to store the executed sql

I can get the query text actually, but the instanceof DatabaseError will be return false, because I change the main error class

There's my code:

```
  if (error instanceof PgDatabaseError) {
    // this will be return false if I put any property
    message = await pgErrorHandler(error, req);
  } else if (error instanceof Error) {
    message = error.message;
  } else if (typeof error === 'string') {
    message = error.trim();
  } else if (error instanceof Object){
    message = error.message;
  }
```

## Versions

Node: 12.22.12
pg: 8.7.3
Postgres: 12.15

**Comment by brianc** [comment]
Hey @AugustoPreis we'll likely never add the query text to the error message as there are quite a few ways that could potentially harm security - imagine someone has sensitive information in their query and they were logging out the error from `pg` - they upgrade to a new version & all of a sudden their logs now contain query text that wasn't logged in the past...leaking harmful information into a less trusted source. The best way to handle this is in your own application. I always suggest making a [facade](https://node-postgres.com/guides/project-structure) around pg if you want to do things like this so you can handle logging in your own code.  Its what I've had success with in past projects using pg.  I even have code that runs in development only and logs out any query text and parameters (to the local console) when a query takes more than 3 seconds so while I'm working I can see problem queries early.
