### ISSUE TITLE
Infinite memory leak in all connections

### ISSUE THREAD

**Issue by stx** [brianc/node-postgres#3070]
We recently switched to this package for high volume processing (500K/s) and it appears this package has a memory leak in both Pool and Client connections in 8.11.3. Even a 128GB server will run out of memory in a few minutes. It happens regardless of how many connections or pooled connections are used (1 or 400).

It's this: https://github.com/brianc/node-postgres/issues/2821

**Comment by brianc** [comment]
Sorry about that. Do you have code to reproduce the issue?

**Comment by stx** [comment]
@brianc It looks like someone made a reproduction here: https://github.com/ShadowLei/pg-test/

**Comment by brianc** [comment]
Do you have any code to reproduce the issue which is a bit more concise/readable? That example is pretty hard to read & does a bunch of stuff.  I'm not sold on this being an issue with node-postgres yet; rather, it could be a way you're _using_ the library.

**Comment by stx** [comment]
@brianc 

Sure. Here you go:

```
// On each thread (32 CPU):

const pool = new pg.Pool({
  user: 'user',
  database: 'db',
  password: 'password',
  port: 12345,
  host: 'host',
  max: 1,
  ssl: {
    rejectUnauthorized: false,
  },
  keepAlive: true,
  keepAliveInitialDelayMillis: 10000,
  idleTimeoutMillis: 0,
});

pool.on('error', (e) => {
  console.error(`PostgreSQL pool error: ${e}`);
});

async read(query, args) {
  const result = await pool.query(query, args);

  return result.rows;
}

// Around 1K/s queries per thread:

await read({
  text: `SELECT 1`, values: [1, 2, 3],
});
```

**Comment by brianc** [comment]
That code isn't exactly valid. Here's my code (modified version of yours)

```js

```

run with `node --expose-gc .` on an m1 ultra

I ran it for a few minutes. process hovered around 50 megabytes of memory usage after 13 million queries executed.

Here's the output from the program:

![image](https://github.com/brianc/node-postgres/assets/50081/89c6e39f-e4ab-4d9e-8abe-136b1a2eea23)

**Comment by stx** [comment]
Might be related to threading or the server connection? We just tested it again as a sanity check, and removing a single query (the only thing we're using pg for in this app) totally removes the memory leak. The query is rather long, with many CTEs, but I wouldn't think that would be relevant...

**Comment by brianc** [comment]
I'd need to see the threading code...or you wanna modify the code I sent over up there & add the threading stuff? I don't typically use threads in node, but I'm happy to dive in.

**Comment by stx** [comment]
Looks like this is due to underlying sockets piling up on a busy system. While triggered by this package it doesn't seem directly caused by it. Thanks for looking into it.
