### ISSUE TITLE
create the database if it doesn't exist

### ISSUE THREAD

**Issue by its-dibo** [brianc/node-postgres#3072]
when executing `connect()` it fails if the database doesn't exist.
there are two solutions:

- either to add an option to create the missing database
- or, just establish the connection without selecting a database

```
connect({createDb: true, host: 'localhost', ...config})
```
or
```
connect(config)
 .catch(err=>{
   if(/* error caused by a missing database */) 
     pg.query(`CREATE DATABASE ${db}`)
     .then(()=>connect())
}
```

**Comment by charmander** [comment]
> or, just establish the connection without selecting a database

That’s not possible with PostgreSQL.

**Comment by its-dibo** [comment]
> > or, just establish the connection without selecting a database
> 
> That’s not possible with PostgreSQL.

so there is another approach to create the database if not exists

**Comment by boromisp** [comment]
https://www.postgresql.org/docs/current/creating-cluster.html
https://www.postgresql.org/docs/current/managing-databases.html

Basically, you need to have a database already, to create new databases remotely.
