### ISSUE TITLE
using a subquery as a value

### ISSUE THREAD

**Issue by its-dibo** [brianc/node-postgres#3084]
I need to perform something like this:
```
pg.query(`insert into tbl (field1, field2), values($1, $2)`, ["a", "(select id from another_table limit 1)"])
```

this causes the following error
```
error: invalid input syntax for type uuid: "(select id from another_table limit 1)"
```

**Comment by brianc** [comment]
yes. that's not valid according to the postgres protocol.

**Comment by brianc** [comment]
You need to look up what valid parameters to a postgres query are. That's not node-postgres specific..it's a database constraint. Ya gotta google that.
