### ISSUE TITLE
pg.escapeLiteral is missing

### ISSUE THREAD

**Issue by Flunsi** [brianc/node-postgres#3099]
This works, but typescript complains: (_Property 'escapeLiteral' does not exist..._):
```
import pg from 'pg'
const myString= pg.escapeLiteral('hello')
```

So I added the following to fix it temporary, but it would be nice if its fixed in "@types/pg"
```
declare module 'pg' {
	export function escapeLiteral(str: string): string
	export function escapeIdentifier(str: string): string	
}
```

I'm using:
```
"@types/pg": "^8.10.9",
"pg": "^8.11.3",
```

**Comment by brianc** [comment]
absolutely. unfortunately I don't actually maintain `@types/pg` - the ultimate goal is to ship type defs directly w/ this library but I'm kinda behind on that.  You could always open up a PR to definitely-typed!

**Comment by Flunsi** [comment]
I'm glad you agree. :)
Yeah, it's a bit sad, that the such a good and big library doesnt have types.
Ok, I'll make a PR for `@types/pg` in 2-3 weeks. I'm kinda busy myself right now. :-p

**Comment by ViktorQvarfordt** [comment]
I would love to get the type for this in place. Any progress @Flunsi? Keep me posted :)

**Comment by Flunsi** [comment]
I no longer need pg.escapeLiteral in my project and I will most likely not make a PR.
But for anybody who is a bit more advanced than me, this is probably only a matter of 10min.
Or you could open a Issue at the right place (`@types/pg` ) unlike me who opened it in the wrong place. ;-)

I'm sorry @ViktorQvarfordt and community.

**Comment by ViktorQvarfordt** [comment]
No problem at all - thanks for letting me know. I'll try to take a stab at it

**Comment by ViktorQvarfordt** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68112
