### ISSUE TITLE
Client was closed and is not queryable after SQL INSERT error

### ISSUE THREAD

**Issue by lrodrigo-cluey** [brianc/node-postgres#3104]
Hi, not sure if this is the expected behaviour or not.

I have an INSERT statement failing because a string is too long (`value too long for type character varying(1000)`).

After that, I can see the client changes to `readyForQuery: false` and if I run another query, I get error "Client was closed and is not queryable".

Is there any way to check if the client is actually queryable? Like any way to access that `readyForQuery` variable?

For the moment I'm adding a validation on that 1000 varchar column but that will only fix it for this particular error.

I'm using the `Client` object (not `Pool`) and version is 8.11.3.

Steps to reproduce:
1 - Create a new client `const dbClient = new Client(dbCredentials);`
2 - Run a query that fails `dbClient.query(FAILING_QUERY)`
3 - Run another query `dbClient.query(OK_QUERY)`
4 - Get error "Client was closed and is not queryable"

**Comment by chrispytoes** [comment]
I am also getting this on this insert. It used to work fine but suddenly it's not.

```
INSERT INTO service_companies (cw_company, company_name, company_id, service, fixed)
VALUES
  (
      20785,
      'Example',
      'Example',
      'infosec',
      true
    )
ON CONFLICT (company_id, service) DO UPDATE SET
  cw_company = excluded.cw_company,
  fixed = true;
```

**Comment by brianc** [comment]
gross - having the client closed and not be queryable but not throwing an error isn't good.  Do you have steps to reproduce kinda "from scratch?" meaning something I can run on a blank postgres instance and it will create the required table/schema/etc as well as the code that triggers the issue? If so, I can write a test & fix this.  As far as `readyForQuery` being accessible...i mean with the amount this library is installed and used every day and the amount of annoyance and pain I have _personally_ experienced with accidental or casual breaking changes I try to keep the api as stable as possible and while its not a documented piece of the API I'm certain you're not the only one relying on it...so before I remove anything like that I will try to do a deprecation cycle for at least a few months.

**Comment by chrispytoes** [comment]
@brianc My apologies, I just realized what I was. Nothing to do with this.

**Comment by brianc** [comment]
okay - closing this now. feel free to open if it comes up again or open a new issue.
