### ISSUE TITLE
Significant Execution Time Difference Between Parameterized and Non-Parameterized Queries in Pg

### ISSUE THREAD

**Issue by vineboneto** [brianc/node-postgres#3109]
Hello everyone,

I have encountered a performance issue with parameterized queries compared to non-parameterized ones.

I performed two queries to the same database, one using a parameterized query and the other without parameterization. The execution time for the parameterized query was significantly higher (approximately 50ms) compared to the non-parameterized query (approximately 1ms).

## Example Code

```javascript
import Pg from "pg";

const pool = new Pg.Pool({
  host: "localhost",
  port: 5432,
  user: "postgres",
  password: "1234",
  database: "teste",
  max: 20,
});

async function queryDatabase() {
  const client = await pool.connect();

  console.time("pg 1");
  const data = await client.query(
    `select * from temp where id = $1`,
    [1]
  );
  console.timeEnd("pg 1"); // 50ms

  console.time("pg 2");
  const data2 = await client.query(
    `select * from temp where id = 1`
  );
  console.timeEnd("pg 2"); // 1ms

  pool.end();
  client.end();
}

queryDatabase();
```

Is it normal to have such a large difference in execution time between parameterized and non-parameterized queries? Is there something in my code that could be causing this discrepancy, or is it a characteristic of the pg library?

Node.js version: 18.17.1
PostgreSQL version: 15
Operating System: Windows 11

Thank you in advance for any insights or suggestions you can provide regarding this issue. I appreciate your help and time.

**Comment by charmander** [comment]
What happens if you swap the order of the queries? I expect this difference to be mostly the server loading things into cache.

**Comment by vineboneto** [comment]
I've considered this, but even when I reverse the order or execute multiple queries in sequence with the same connection pool, the execution time remains consistent. I can't seem to understand why.

```javascript
import pg from "pg";

const pool = new pg.Pool({
  host: "localhost",
  port: 5432,
  user: "postgres",
  password: "1234",
  database: "teste",
  max: 20,
});

async function queryDatabase() {
  const client = await pool.connect();

  console.time("pg 0");
  const data0 = await client.query(`select * from temp where id = 1`);
  console.timeEnd("pg 0"); //1ms;

  console.time("pg 1");
  const data1 = await client.query(`select * from temp where id = $1`, [1]);
  console.timeEnd("pg 1"); //50ms;;

  console.time("pg 2");
  const data2 = await client.query(`select * from temp where id = $1`, [1]);
  console.timeEnd("pg 2"); //50ms;;

  console.time("pg 3");
  const data3 = await client.query(`select * from temp where id = $1`, [1]);
  console.timeEnd("pg 3"); //50ms;;

  client.release();
  pool.end();
}

queryDatabase();


```

**Comment by vineboneto** [comment]
I tested it on an Ubuntu Linux distribution, and there was no difference in the execution of parameterized and non-parameterized queries. It's likely something specific to Windows 11, but I'm unsure of the exact cause. I'll close the issue for now.
