### ISSUE TITLE
pg don't recognize the number of params on the query

### ISSUE THREAD

**Issue by sergiohdljr** [brianc/node-postgres#3132]
i got this follow code : 
![Captura de tela de 2024-01-22 12-22-33](https://github.com/brianc/node-postgres/assets/102623806/4280404c-5e55-4395-9031-893e44960955)

and when i try to run i get this error : `bind message supplies 8 parameters, but prepared statement "" requires 6`

but how you can see i actually required 8 in the query 

another funny thing is: 
if i write the same query this way ` text: INSERT INTO farmacia(nome,telefone,cidade,bairro,rua,numero,coords)
                                                               VALUES ($1, $2, $3, $4, $5, $6 , ST_GeographyFromText('POINT(${coords.y} ${coords.x})'));`,
                
it work just fine.

**Comment by charmander** [comment]
`'POINT($7 $8)'` is the literal text `POINT($7 $8)`. It doesn’t reference any parameters.

**Comment by sergiohdljr** [comment]
thank you charmander.

any sugestions on how i could fix ?
