### ISSUE TITLE
pg Client doesn't use PGHOST by default

### ISSUE THREAD

**Issue by yaayes** [brianc/node-postgres#3137]
Hello,

I'm new to the library, I have a script which connects to remote database, I defined environment variables: `PGUSER`, `PGPASSWORD`, `PGDATABASE`, `PGPORT` and `PGHOST`, and to connect:

```js
const client = new Client();
await client.connect();
```

But it throws an error: `error: pg_hba.conf rejects connection for host "xxxxxxx", user "xxxxxxx", database "xxxxxxx", SSL off`

The thing is the host mentioned in the error is the machine's local IP where the script is executed not the one I've defined as `PGHOST` env var, I also tried to set it directly:

```js
const client = new Client({
  host: process.env.PGHOST
});
await client.connect();
```

but still give me the same error with wrong host, and I confirm I have that variable using printenv

**Comment by valera-rozuvan** [comment]
Check the defaults set in the file [packages/pg/lib/defaults.js](https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/defaults.js):

```javascript
// ...
host: 'localhost',
// ...
user: process.platform === 'win32' ? process.env.USERNAME : process.env.USER,
// ...
password: null,
// ...
port: 5432,
```

So - we see that you need to set all of these manually.

I suggest to load `PGUSER`, `PGPASSWORD`, `PGDATABASE`, `PGPORT` and `PGHOST` from your ENV using [dotenv](https://www.npmjs.com/package/dotenv), and pass them to the library constructor.

Cheers :-)

**Comment by charmander** [comment]
@valera-rozuvan Those are the last fallback defaults; `PGHOST` has precedence. https://github.com/brianc/node-postgres/blob/df0f4d19fbf0349c6b41e8982e058f7377ee3bea/packages/pg/lib/connection-parameters.js#L18

@yaayes This is probably an issue with your pg_hba.conf/PostgreSQL server. Do you get the same error from `psql` with the same `PGHOST`? Maybe SSL is required?

**Comment by yaayes** [comment]
Hello @valera-rozuvan and @charmander, apparently it was an SSL error, but the error looks a little bit misleading, so the remote server doesn't require SSL, but the client wants to force it, so I've set `rejectUnauthorized: false`, and I'm able to connect. I think it should be default but I may be wrong, I think if someone wants to reject unauthorized he can explicitly set it!

**Comment by charmander** [comment]
The error was accurate; providing any object as the `ssl` property of pg’s configuration, including `{ rejectUnauthorized: false }`, *enables* SSL. The server requires SSL. (If you have the server’s CA certificate, you should use that instead of `rejectUnauthorized: false`; MITM is particularly relevant for “remote” databases.)
