### ISSUE TITLE
How to Use PL/pgSQL Anonymous Functions in npm pg Queries?

### ISSUE THREAD

**Issue by Md-Anamul-Haque** [brianc/node-postgres#3163]
_Issue Description_:
I'm currently working on a Node.js project that involves interacting with a PostgreSQL database using the npm pg library. I need to leverage PL/pgSQL anonymous functions within my SQL queries for certain operations, but I'm struggling to find clear guidance on how to do this effectively.

**Problem Statement**:
While npm pg is excellent for executing SQL queries in Node.js applications, integrating PL/pgSQL anonymous functions into queries seems to be less straightforward. Despite my efforts to find documentation or examples demonstrating this integration, I haven't been successful.

**Expected Behavior**:
I expect to find clear instructions, examples, or best practices on how to incorporate PL/pgSQL anonymous functions seamlessly into npm pg queries. This would help me understand the syntax, usage, and potential limitations of using these functions within my Node.js application.

Proposed Solution:

**Documentation Update**: Could the documentation for npm pg be enhanced to include a dedicated section or examples specifically covering the usage of PL/pgSQL anonymous functions in queries? This would greatly benefit developers like me who rely on clear documentation to understand library features.

**Code Examples**: It would be immensely helpful to have comprehensive code examples demonstrating various scenarios where PL/pgSQL functions can be used within npm pg queries. These examples should cover common use cases and provide insights into best practices.

**Community Input**: I'd appreciate input from the community, especially from developers who have successfully integrated PL/pgSQL functions into npm pg queries. Any tips, tricks, or advice would be invaluable in overcoming this challenge.

**Testing and Validation**: It's important to ensure that any proposed documentation changes or examples are thoroughly tested to verify their accuracy and compatibility across different PostgreSQL versions and npm pg configurations.

By addressing this issue, we can empower developers working with npm pg to leverage the advanced capabilities of PL/pgSQL within their Node.js applications more effectively. Any insights, suggestions, or contributions from the community would be highly appreciated.

**Comment by jwaugh3** [comment]
I'm in the same situation. Not finding much documentation other than [this](https://github.com/brianc/node-postgres/issues/489). And that discussion is not the most desirable as you'd need a file per function.

**Comment by boromisp** [comment]
`DO` statements in postgresql are pretty simple: https://www.postgresql.org/docs/current/sql-do.html

`DO` statements can't be parameterized, you have to interpolate and escape all parameters on the client side.
See for example https://node-postgres.com/apis/utilities and https://www.npmjs.com/package/pg-format.

`DO` statements do not return anything. If you need some feedback, you can use `RAISE` statements inside the code block: https://node-postgres.com/apis/client#notice, or store the result in the database.

Otherwise, execute `DO` statements just like any other query.

---

See also:

User-Defined Functions:
- https://www.postgresql.org/docs/current/xfunc.html
- https://www.postgresql.org/docs/current/sql-createfunction.html

User-Defined Procedures:
- https://www.postgresql.org/docs/current/xproc.html
- https://www.postgresql.org/docs/current/sql-createprocedure.html

**Comment by charmander** [comment]
There’s nothing specific to pg involved here; read the PostgreSQL documentation on how to write queries. I’m not sure how much of the original issue description is an honest opinion, since it looks like it was generated by a computer. Would recommend not doing that.

**Comment by Md-Anamul-Haque** [comment]
I tried but it doesn't work If you think that works, you try a data insert using plpgsql, and try to return what it did.

**Comment by charmander** [comment]
If you think that it *doesn’t* work, show specifically what you tried, what you expected, and what you got.

**Comment by Md-Anamul-Haque** [comment]
#### for example, I want to get next_org_code after inserting data using **plpgsql** to return next_org_code

this is a simple example I write this code using OracleDB so I want to make a similar task with PostgreSQL and nodejs

```ts
const org = await db.query(
            `
                    DECLARE
                        next_org_code VARCHAR2(10);
                        existing_org_count number;
                    BEGIN
                        -- Check for existing organization with the same name
                        SELECT COUNT(*) INTO existing_org_count FROM ORG WHERE org_name = :orgName and USER_ID = :userId;
                        
                        IF existing_org_count > 0 THEN
                            RAISE_APPLICATION_ERROR(-20003, 'Organization name already exists.;');
                        END IF;
                        -- Generate next organization code
                        SELECT 'ORG' || LPAD(NVL(TO_NUMBER(SUBSTR(MAX(org_code), 4)), 0) + 1, 4, '0000') INTO next_org_code FROM ORG;
                        
                        -- Insert new organization (assuming unique org_name constraint doesn't exist)
                        INSERT INTO ORG (org_code, org_name, user_id)
                        VALUES (next_org_code, :orgName, :userId)
                        RETURNING next_org_code INTO :org_code;
                        
                        UPDATE USERS SET IS_OWNER = true WHERE user_id = :userId;
    
                        INSERT INTO ORG_DT (org_code, user_id, user_role)
                        VALUES (next_org_code, :userId, 'O'); -- Assuming 'O' for OWNER role    
                    END;
                `,
            {
                orgName: orgName,
                userId: userId,
                org_code: { type: OracleDB.STRING, dir: OracleDB.BIND_OUT }
            },
            { autoCommit: true }
        );```

**Comment by boromisp** [comment]
I suggest starting with the postgres documentation linked in my previous comment: https://github.com/brianc/node-postgres/issues/3163#issuecomment-2009558404

As a starting point, postgres `DO` expressions have no parameters (`IN` or `OUT`), so you will have to resort to named functions or procedures.

**Comment by Md-Anamul-Haque** [comment]
It works according to the documentation but I can't find its return value in nodejs

**Comment by boromisp** [comment]
I'm sure it works that way in oracle, but if you want to target postgres, you are going to have to read the postgres docs.

![image](https://github.com/brianc/node-postgres/assets/2242020/a311af60-b040-43fb-9b75-1d8cc768d2b6)

If you need to do it in a single command, and you need parameters and return values, you either [create a function](https://www.postgresql.org/docs/current/sql-createfunction.html), or try to fit the entire logic into a [CTE](https://www.postgresql.org/docs/current/queries-with.html).
