### ISSUE TITLE
pg-Pool cannot imported

### ISSUE THREAD

**Issue by mshajid** [brianc/node-postgres#3176]
I was having some trouble on importing the Pool and consistently throwing me the error that cannot be imported, but It works fine with the `commonJS` by using `module.exports`

**Comment by charmander** [comment]
code & error

**Comment by mshajid** [comment]
```js
const Pool = require("pg").Pool;
require("dotenv").config();

const pool = new Pool({
  host: process.env.HOST,
  user: process.env.USER,
  port: process.env.PORT,
  database: process.env.DB,
  password: process.env.PASS,
});

module.exports = pool;

```

If I use `commonJS` then it works fine, but When I convert this into `ESModule` then it started to throw error. Since I worked this out already since 2 days ago I couldn't remember the error right proper;y -_- .

**Comment by mshajid** [comment]
@charmander : This is not planned lol, nvm. :'D

**Comment by charmander** [comment]
"won't fix, **can't repro**, duplicate, stale"

if you do post the reproducer, this is probably a duplicate of an existing issue, but there's no point in guessing
