### ISSUE TITLE
Why do I have to provide a value to an OUT parameter when calling a stored procedure?

### ISSUE THREAD

**Issue by BjornMoren** [brianc/node-postgres#3179]
I have a stored procedure with six IN parameters and one OUT parameter (see code below).

I use pg 8.11.3. I assumed this would work to call it from pg:

```
        const qres = await client.query(
            `CALL sp_create_post($1, $2, $3, $4, $5, $6);`,
            [post.type, 0, null, userID, new Date().toUTCString(), JSON.stringify(post.text)]
        );
```
But I get this error message from pg : No procedure matches the given name and argument types. You might need to add explicit type casts.

When I add a seventh dummy parameter, it works. Why do I have to do that? Is this a bug in pg, or should I have called it in some other way?

```
        const qres = await client.query(
            `CALL sp_create_post($1, $2, $3, $4, $5, $6, $7);`,
            [post.type, 0, null, userID, new Date().toUTCString(), JSON.stringify(post.text), null]
        );
```

This is the sp:

```
CREATE PROCEDURE sp_create_post(
  IN type_param SMALLINT, 					
  IN relation_type_param SMALLINT,		
  IN parent_post_id INT, 					   
  IN userid_param INT, 						 
  IN date_param TIMESTAMP,					
  IN text_param JSON,						   
  OUT post_id INT)                    
LANGUAGE plpgsql
AS $$
DECLARE
  --post_id INT;
BEGIN

  INSERT INTO post ("type", userid, "date", "text") 
  VALUES (type_param, userid_param, date_param, text_param) RETURNING id INTO post_id;

  INSERT INTO relation (main_post_id, sub_post_id, "type", user_id, "date") 
  VALUES (parent_post_id, post_id, relation_type_param, userid_param, date_param);

  COMMIT;

END;

$$;
```

**Comment by charmander** [comment]
This is just [how it works in PostgreSQL](https://www.postgresql.org/docs/current/plpgsql-declarations.html#PLPGSQL-DECLARATION-PARAMETERS). You might be thinking of `CREATE FUNCTION`.

**Comment by BjornMoren** [comment]
Thanks @charmander. It makes sense to me now in the way you have to specify which OUT variable the result should be assigned to in a normal SQL CALL, and JavaScript doesn't have an equivalent mechanism for that.
