### ISSUE TITLE
Question: Can I create a `pg.Client` with a custom `net.Socket` object?

### ISSUE THREAD

**Issue by cakoose** [brianc/node-postgres#3195]
When creating a `pg.Client` (or `pg.Pool`), is there a way to pass a custom `net.Socket` object for it to use for communication?

Example scenario:
1. My Postgres DB is running on a VM in a private network.
2. The VM has no services exposed except SSH.
3. I would like to connect from my app server container to the Postgres DB by tunneling through SSH.

Option 1:
1. Install the OpenSSH client client software on my app server container.
2. Run the OpenSSH client process to maintain a tunnel to the Postgres VM.
3. In my Node.js process, tell `pg` to connect to the SSH tunnel port on localhost.

Problem: This requires running a separate OpenSSH process in my app server container, which is one extra moving part.

Option 2:
1. In my Node.js process, use an SSH library to set up a tunnel and listen for connections on some port.
2. In my Node.js process, tell `pg` to connect to that port.

Problem: While this allows me to eliminate the extra process, it's slightly inefficient/silly to have Node.js read/write the bytes one extra time.

Ideally, I'd like to just pass the SSH library's `net.Socket` directly to `pg.Client`. Is there a way to do that?

(Note: SSH was just an example. Other options for the tunnel that I'm considering: SPDY, QUIC, some VPN protocol. In all cases I could run an additional process to maintain the tunnel on the app server container, but it would be nice to be able to do it all in Node.js.)

**Comment by brianc** [comment]
Yup! You can pass the socket as the `stream` property on the config (this property has existed since node v0.2 hence the name `stream` instead of `socket`...but yeah - it needs a streamish type)

https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/client.js#L49
https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/connection.js#L19

LMK if this doesn't work - I'm open to exploring if there are bugs or writing more explicit tests around this behavior. Going to close in the meantime but feel free to re-open if this doesn't fix your issue / answer your question! ❤️

**Comment by cakoose** [comment]
Oh, nice!

Maybe worth adding the `stream` parameter to the docs? (I didn't see it, but maybe I'm looking in the wrong place: https://node-postgres.com/apis/client)

How does this work for `pg.Pool`? I can't figure out how to create a new stream every time `Pool.newClient` is called.

**Comment by shyam-somanathan** [comment]
@brianc I am trying to connect to postgresDB through ssh tunnel for test automation and when i try to add the ssh stream as a property on the pg config, Iam getting the following error on connection .

Tunnel: Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
Tunnel: Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
Tunnel: Inbound: Received DEBUG
Tunnel: Debug output from server: "/usr/bin/ldapsearch-ssh:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding"
Tunnel: Inbound: Received DEBUG
Tunnel: Debug output from server: "/usr/bin/ldapsearch-ssh:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding"
Tunnel: Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
Tunnel: Inbound: REQUEST_SUCCESS

Error connecting to the database: TypeError: this.stream.setNoDelay is not a function
    at Connection.connect (/Users/<removed>/node_modules/pg/lib/connection.js:43:17)
    at Client._connect (/Users/<removed>/node_modules/pg/lib/client.js:113:11)
    at /Users/<removed>/node_modules/pg/lib/client.js:167:12
 
My config is as below:
        const pgconfig = {
          user: <user>, 
          host: <host> ,
          database: <db>, 
          port: 5432,
          stream: sshstream     // stream from ssh tunnel       
        }

Setting the same **sshstream** as stream property for mySQL DB works without any issues.

**Comment by charmander** [comment]
@shyam-somanathan pg probably shouldn’t call `setNoDelay` on a stream it didn’t create, but in the meantime, as a workaround, you should be able to set

```js
sshstream.setNoDelay = () => {}  // no-op
```

**Comment by Hakentha** [comment]
Hi, i try with this solution:
https://github.com/brianc/node-postgres/issues/2503
And works perfect.

Replace:
this.stream.setNoDelay(true)
this.stream.connect(port, host)
to
//this.stream.setNoDelay(true)
//this.stream.connect(port, host)
if (typeof this.stream.setNoDelay === 'function') this.stream.setNoDelay(true)
if (typeof this.stream.setNoDelay === 'function') this.stream.connect(port, host)
