### ISSUE TITLE
support for postgres Large Objects (lo)

### ISSUE THREAD

**Issue by jeromew** [brianc/node-postgres#321]
Hello,

it seems like pg does not yet handle postgres large objects (http://www.postgresql.org/docs/9.2/static/largeobjects.html)

pg has bytea support, but has anyone implemented the lo bindings ? is it somewhere on the roadmap ?

do you think it could be possible to have lo support with a node.js stream interface ?

thanks !
Jerome

**Comment by sombriks** [comment]
+1 for this. i need to store files on database but didn't figured yet an elegant way to do that.

**Comment by brianc** [comment]
Looks like pg-large-object fixes this. LO is out of scope for this module.
