### ISSUE TITLE
throw new Error('SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string')

### ISSUE THREAD

**Issue by saiganesh346** [brianc/node-postgres#3210]
I am unable to run the Query when I try to run in Postman or CMD I am unable to executive the program please help me with this

Error: throw new Error('SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string')

**Comment by brianc** [comment]
> client password must be a string

something wrong w/ your password? W/o more code to reproduce I can't help ya more than that.

**Comment by saiganesh346** [comment]
In that particular error I didn't enter the password where I am trying to connect with database so when I am watching the video from Udemy it is a old code so I got error so when I entered a code it has fixed the error
