### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by MicHamoNZ** [brianc/node-postgres#3224]
Currently learning back-end development via Codecademy and I have tried to follow the example in the following https://node-postgres.com/guides/project-structure to connect my API/Routes to my local database instance and have used the suggested db/index.js 

`import pg from 'pg'
const { Pool } = pg
 
const pool = new Pool()
 
export const query = (text, params, callback) => {
  return pool.query(text, params, callback)
}` 

and then the routes/user.js file as given

`// notice here I'm requiring my database adapter file
// and not requiring node-postgres directly
import * as db from '../db/index.js'
 
app.get('/:id', async (req, res, next) => {
  const result = await db.query('SELECT * FROM users WHERE id = $1', [req.params.id])
  res.send(result.rows[0])
})
 
// ... many other routes in this file`

However when I try to run/debug the application I get the following error

![image](https://github.com/brianc/node-postgres/assets/28913158/94eacd5a-e50e-47ac-af0b-1da1345a24f8)

I am sure I am missing some code to define the connection but am not sure.

Any help would be appreciated.

**Comment by maliByatzes** [comment]
Hello, I'm pretty sure this is just a nodejs problem nothing to do with the library. To solve the problem make sure in your package.json file you have `"type": "module"` field and your file extension is fine as .js

**Comment by brianc** [comment]
Thanks @maliByatzes I think you're right! Yeah...the module system in node is pretty unfortunately brittle. Honestly bun really nailed it here...but it is what it is. Sorry for the confusion! I'll be adding emca module support to `pg` in the near-ish future but yeah the error your getting _looks like_ its from your code base.
