### ISSUE TITLE
bind message supplies 1 parameters, but prepared statement "" requires 8

### ISSUE THREAD

**Issue by jreybaylen** [brianc/node-postgres#3232]
I always get this error, even though I have properly added the required parameters. Please see the query and parameters below.
```typescript
const sql = `
	SELECT
		id,
		group_id,
		destination,
		start_date,
		end_date,
		pnrs,
		arrival_flight_number,
		arrival_flight_schedule,
		departure_flight_number,
		departure_flight_schedule,
		validity,
		supplier,
		remarks,
		status,
		created_by,
		updated_by,
		created_at,
		updated_at
	FROM
		blocking
	WHERE
		created_by = $1 AND
		LOWER(destination) = LOWER($2) AND
		(start_date BETWEEN $3 AND $4) AND (end_date BETWEEN $5 AND $6)
	ORDER BY
		validity DESC
	LIMIT $7
	OFFSET $8
`

const filters =  [
  '93343012-aada-422f-92f2-beb6392faafc',
  'Japan',
  '06/01/2024',
  '06/02/2024',
  '06/10/2024',
  '06/11/2024',
  15,
  0
]

await this.#connection.query(sql, [ filters ])
```

I noticed that when I add more placeholders in the WHERE clause, an error shows up. I'm using the latest version (8.11.5).

**Comment by sehrope** [comment]
The extra `[ ... ]` around `[ filters ]` is executing the command as if it's a single parameter with a value of the `filters` array. So you are only sending a single parameter when the query expected eight parameters.

Change it to:

```
await this.#connection.query(sql, filters)
```

**Comment by jreybaylen** [comment]
Thank you! The issue was fixed. I didn't notice this Array LOL.
