### ISSUE TITLE
How to avoid serialization when using setTypeParser?

### ISSUE THREAD

**Issue by ersinakinci** [brianc/node-postgres#3255]
I want to map `numeric` to complex objects using [bignumber.js](https://github.com/MikeMcl/bignumber.js):

```js
import { BigNumber } from "bignumber.js";

// Map numeric to BigNumber.
PG.types.setTypeParser(1700, "text", (value) =>
  null ? null : BigNumber(value)
);
```

I think that I'm misunderstanding something about `setTypeParser`, because what I expected was to get back instances of BigNumber. Instead, I seem to be getting serialized JSON objects like `{ s: 1, e: 0, c: [Array] }`.

I did note that the docs have [some info on serialization](https://node-postgres.com/features/queries), but it's unclear how this relates to mapping data types (if at all).

How do I get the non-serialized BigNumber object back? Also, what am I supposed to pass to my client if, say, I want to insert or update a `numeric`--do I pass a BigNumber, a string, a number...?

Thanks in advance and for the great library! I'm sure that I'm confused about something fundamental here.

**Comment by charmander** [comment]
What you have should work (but `(value) => null ? null : BigNumber(value)` can be simplified to `BigNumber`). Are you sure the `{ s: 1, e: 0, c: [Array] }` isn’t (part of) the `console.log` representation of a `BigNumber`? Have you tried performing operations on it?

> Also, what am I supposed to pass to my client if, say, I want to insert or update a numeric--do I pass a `BigNumber`, a string, a number...?

A string.

**Comment by ersinakinci** [comment]
Yep, when I try to call methods on the object, it says that they don’t exist.On Jun 11, 2024, at 9:34 PM, Charmander ***@***.***> wrote:﻿
What you have should work (but (value) => null ? null : BigNumber(value) can be simplified to BigNumber). Are you sure the { s: 1, e: 0, c: [Array] } isn’t (part of) the console.log representation of a BigNumber? Have you tried performing operations on it?

Also, what am I supposed to pass to my client if, say, I want to insert or update a numeric--do I pass a BigNumber, a string, a number...?

A string.

**Comment by ersinakinci** [comment]
I think this issue may have something to do with my SQL client, Kysely, or something else in my stack. I wrote a little test script that uses pg directly and everything works correctly:

```ts
import PG from "pg";
import BigNumber from "bignumber.js";

PG.types.setTypeParser(1700, "text", (value) =>
  null ? null : BigNumber(value)
);

const client = new PG.Client({
  connectionString: "postgres://postgres:postgres@localhost:5432/scrappy-cash",
});

await client.connect();

const result = await client.query("SELECT 0.1::numeric as num;");

// Output: num op 0.3
console.log("num op", result.rows[0].num.plus(0.2).toString());

await client.end();
```

Closing for now, thanks for your help @charmander (and also for the hint about inserting/updating with a string).

**Comment by ersinakinci** [comment]
Found my issue (it was Kysely's CamelCasePlugin): https://github.com/kysely-org/kysely/issues/1036.
