### ISSUE TITLE
Procedure names being converted

### ISSUE THREAD

**Issue by myersba** [brianc/node-postgres#3257]
I name all of my procedures using headless camel case such as getAllProjects. When I make a call like `pool.query(CALL getAllProjects())`, (Yes, I know there are supposed to be `` in that call but the code tool formats it in an odd way so I removed them), I'm getting an error that tells me that, "procedure getallprojects() does not exist."

If I indeed change the call and the procedure to match getallprojects, the call does work.

Could you please keep it from converting everything to lower case?

**Comment by boromisp** [comment]
This library doesn't mess with the query string. You need to quote your case sensitive identifiers: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
