### ISSUE TITLE
Type of result.rows is any[][] instead of any[] ?

### ISSUE THREAD

**Issue by ipython3** [brianc/node-postgres#3275]
Operating System: Ubuntu jammy 22.04 x86_64
node: 20.15.0
vscode: 1.91.0
pg: 8.12.0

Hi,

Thank you for creating this amazing library! I've just started using `pg` and ran into a strange problem.

In `pg`'s documentation, I can see that the type of result.rows should be `any[]`.
<img width="862" alt="image" src="https://github.com/brianc/node-postgres/assets/31297905/67861da4-3fc2-45a9-94fc-5536bc67d9e5">

I'm writing a Node.js server that need to get the total user count in the `user` table in my database. So I wrote JavaScript code like this:
```javascript
const result = await pool.query('SELECT COUNT(*) FROM users;');
const rows = result.rows;
return parseInt(rows[0].count);
```

The code can run smoothly without any error, but my editor (VS Code) detects the type of result.rows as `any[][]`.
![image](https://github.com/brianc/node-postgres/assets/31297905/bc622675-06b7-47a4-89b7-d2399ecd08b4)
Thus I get an linting error which says `Property 'count' does not exist on type 'any[]'.` 
![image](https://github.com/brianc/node-postgres/assets/31297905/638dbb9d-4c0c-4e2a-b283-2691520aa4a2)

I'm wondering if I'm using `pg` incorrectly? Or if I have configured VS Code incorrectly?
If the type of result.rows is `any[]` according to `pg`'s documentation, why VS Code detects the type of it as `any[][]`?
I'm not familiar with TypeScript and I'm wondering if there is a proper way to handle this linting error? Maybe writing some JSDoc comments?

My `jsconfig.json` file:
```json
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES2022",
    "checkJs": true,
    "allowJs": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true
  },
  "exclude": [
    "node_modules",
    "**/node_modules/*"
  ]
}
```

**Comment by cesco69** [comment]
The problem is `;`

```js
const result = await pool.query('SELECT COUNT(*) FROM users;');
//---------------------------------------------------------^
```
the char  `;` is used for multi statement sintax, eg.:

```js
const result = await pool.query('SELECT COUNT(*) FROM users; SELECT COUNT(*) FROM orders;');
```

**Comment by ipython3** [comment]
Hi @cesco69 
Thank you so much! Do you mean that removing the `;` should fix the problem? I tried but the type error is still there:
<img width="725" alt="图片" src="https://github.com/user-attachments/assets/1e8c4e4a-e323-41bc-9e8f-c6a9eb5440c5">
Is there something else I've missed?
