### ISSUE TITLE
Clarification: Does pool.end() close clients created with pool.connect()

### ISSUE THREAD

**Issue by Ivor808** [brianc/node-postgres#3280]
Hey all, I think the documentation may need some clarification around this. When grabbing clients from the pool with pool.connect. Does pool.end() close those clients? Or does it only close the clients pool internally has. It would seem that the case is it only closes its internal clients. Thank you!

**Comment by charmander** [comment]
You need to release clients back to the pool. The promise `end()` returns won’t resolve until all of the pool’s clients have been returned, and releasing a client back to an ending pool closes it.
