### ISSUE TITLE
How to avoid statement preparation with `pg-cursor`

### ISSUE THREAD

**Issue by viladimiru** [brianc/node-postgres#3285]
Hello!

First of all I want to thank you for your huge contribution in opensource, your library is awesome!

I found out a problem, when I try to execute multiple queries with cursor I get this error: `cannot insert multiple commands into a prepared statement`.

Is it possible to run query with cursor and without preparation? When I make same query without cursor, all works fine, I expected same behaviour with cursor.

Unfortunately I got stuck when I tried to figure out a problem, I though that control located [here](https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/query.js#L35), but when I did debug of query with cursor I see that this method didn't even call

It's sadly but in my case I can't split statements and run them separately because customer can write absolutely any request.

I hope you can suggest me something to solve my problem, thanks for your efforts!

How to reproduce:
```
const client = new Client({
    ...
});
await client.connect();

const cursor = client.query(new Cursor('select version(); select version();'));
await cursor.read(2);
```

**Comment by brianc** [comment]
Using a cursor _requires_ using the [_extended query protocol_](https://www.postgresql.org/docs/current/protocol-flow.html) which is the same flow used for prepared statements. You cannot use multiple statements in the extended query protocol so they wont work w/ cursors in postgres.
