### ISSUE TITLE
Security Concern: Use of Weak Hashing Algorithm in pg/lib/crypto/utils-webcrypto.js

### ISSUE THREAD

**Issue by furkantopal** [brianc/node-postgres#3291]
Hello there,

Our application recently underwent a security analysis, and it flagged a potential security issue related to the use of a weak hashing algorithm in one of your dependencies. Specifically, the concern points to node_modules/pg/lib/crypto/utils-webcrypto.js.

The analysis warns that the application utilizes a hashing algorithm that does not meet current security standards. Weak hashing algorithms can lead to vulnerabilities, such as the leaking of sensitive information or credentials. The primary issue is the potential use of an outdated or insecure hash function that could undermine the overall security of the application.

To address this issue, we recommend replacing the weak hash function with a stronger one. For example, you can use the SHA-256 algorithm.

Thank you for your attention to this matter, and we appreciate your ongoing efforts to maintain and improve.

Best regards

Observe the usage of the hashing algorithm in:
https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/crypto/utils-webcrypto.js#L35

**Comment by charmander** [comment]
Please make some effort to interpret the context before copying the results and generic advice of automated scans into issue reports.

pg uses MD5 to implement [PostgreSQL’s MD5 password authentication](https://www.postgresql.org/docs/16/auth-password.html#AUTH-PASSWORD), and indeed, you should use a better authentication method with PostgreSQL – but that’s a matter of server configuration. As long as pg supports connecting to servers requiring that authentication method, that code is going to be there.

**Comment by furkantopal** [comment]
Thanks @charmander for your answer!
