### ISSUE TITLE
Is there some string escaping or preparing?

### ISSUE THREAD

**Issue by unikoid** [brianc/node-postgres#33]
Hello. I'm using node-postgres. And I want to insert some strings into some table.
If I'm using single query, I can do like this and everything is working ok:

``` javascript
client.query('INSERT INTO sometbl VALUES ($1, $2)', ['foo', 'bar']);
```

But since I am using transactions and trying to do like this:

``` javascript
client.query('BEGIN; INSERT INTO sometbl VALUES ($1, $2); UPDATE sometable SET somevalue = $3; END;', ['foo', 'bar', 'foobar']);
```

I am getting an error with code 42601: `'cannot insert multiple commands into a prepared statement'`.

Yes, I know that I can use simple string concatenation or some realizations of sprintf() to insert these parameters into the query string, but, I think, it isn't safe to do it without any preparation like escaping.
Is there some convinient way to do such preparation before inserting string values into the query string?

For example, I have found PQescapeLiteral function in the libpq, maybe there is some interface to this or similar function exists?
If no, can it be implemented?
//Sorry if the question is silly, I'm newbie in postgresql and node.

**Comment by shaunc** [comment]
If you don't need to wrap in a transaction, but need atomic execution, the particular problem could be solved with a CTE as well: 

    ...
    client.query("with s as (INSERT INTO sometbl VALUES ($1, $2) returning 1) UPDATE sometable SET somevalue = $3 from s", ['a', 'b', 'c'])

**Comment by brianc** [comment]
haha @williamkapke sorry about that! Will edit my response to not suck!

**Comment by benjie** [comment]
(NOTE: the current `pg` supports both `escapeIdentifier` and `escapeLiteral` on client instances: https://github.com/brianc/node-postgres/blob/3f6760c62ee2a901d374b5e50c2f025b7d550315/packages/pg/lib/client.js#L408-L437 )

**Comment by jayarjo** [comment]
@benjie I do not recognize the logic can you elaborate on what `escapeIdentifier` and `escapeLiteral` are for?

**Comment by benjie** [comment]
Sure; escapeIdentifier is for escaping identifiers as documented here: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS  "(To include a double quote, write two double quotes.)"

escapeLiteral is for escaping string constants as documented here: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS

**Comment by dschinkel** [comment]
https://github.com/segmentio/pg-escape
