### ISSUE TITLE
Is there a way to affect how different JS types are serialized and/or how stringified values will be interpreted Postgres side?

### ISSUE THREAD

**Issue by laurisvan** [brianc/node-postgres#3302]
I am trying to add proper mapping of Postgres intervals to Luxon durations. I was able to do this in the parsing side by setting type parser (see below), but I could not whether a similar operation could be done when serializing values back. If I understood the documentation correctly, something is done for JavaScript dates already, so I suspect something for them exists already.

I am using Objection.js+knex+node-postgres stack. I am looking for a solution where minimum changes to the actual insert/update queries would be needed. I also checked knex implementation, and AFAIK the values would be JSONified, so the postgres driver will get the value as ISO date. This, by default would fail to parse in postgres side.

I wonder if setting postgresql.conf `intervalstyle = 'iso_8601'` would help with this problem?

Here is how I do the interval parsing:
```
types.setTypeParser(types.builtins.INTERVAL, parseInterval)
```

**Comment by sehrope** [comment]
See the `toPostgres` function description in the docs: https://node-postgres.com/features/queries#parameterized-query

If your object has a property `.toPostgres` that is a function, that will be used to serialize the object. The property must be on every object instance (e.g., if the object is an actual class and the class has a member function, that works).

Otherwise you have to handle it directly in your code when you construct the parameters array. If you provide a serialized value as a String or Buffer, it'll get passed as-is to the server and the server will accept it:

```js
const result = await pool.query(
  'SELECT ... WHERE foo = $1',
  [toCustomSerializedValue(foo)]
);
```

The serialized value should match the text representation of the data type on the server.

**Comment by laurisvan** [comment]
> See the `toPostgres` function description in the docs: https://node-postgres.com/features/queries#parameterized-query
> 
> If your object has a property `.toPostgres` that is a function, that will be used to serialize the object. The property must be on every object instance (e.g., if the object is an actual class and the class has a member function, that works).
> 
> Otherwise you have to handle it directly in your code when you construct the parameters array. If you provide a serialized value as a String or Buffer, it'll get passed as-is to the server and the server will accept it:
> 
> ```js
> const result = await pool.query(
>   'SELECT ... WHERE foo = $1',
>   [toCustomSerializedValue(foo)]
> );
> ```
> 
> The serialized value should match the text representation of the data type on the server.

Unfortunately I cannot augment the duration values with .toPostgres() method.

However, I did a bit of experimenting, and as the Luxon Durations serialize to ISO durations beautifully, they go through the driver without major hurdles if I set the Postgres configuration to use iso_8601 for formatting intervals.

This is my WIP implementation, for anybody that might be interested. I have not tested the performance implications yet. Luxon is slow in DateTime handling, so I expect similar performance characteristics for Durations. I am using it as a polyfill while waiting for JS Temporal spec to be accepted and implemented.

```
  /**
   * Handler for INTERVAL type - first parses incoming Postgres value to a Luxon Duration.
   * Note that in serializing, Luxon Durations serialize to iso_8601 format, which is
   * accepted by Postgres when intervalstyle = 'iso_8601' in postgresql.conf is set.
   *
   * Warning: This only works both ways with the intervalstyle = 'iso_8601' is set.
   */
  private static intervalHandler(interval: string): Duration {
    // Note: Due to our Postgres setting intervalstyle = 'iso_8601',
    // we can expect the value to be in ISO 8601 format.
    // Luxon is probably not very performant on this one, so we might need to optimize
    // the parsing in the future.
    const parsed = Duration.fromISO(interval)
    if (!parsed.isValid) {
      throw new Error(`Could not parse interval ${interval} - not a valid ISO 8601 duration`)
    }
    return parsed
  }
```
