### ISSUE TITLE
invalid byte sequence for encoding "UTF8": 0xce 0x6

### ISSUE THREAD

**Issue by lilouartz** [brianc/node-postgres#3307]
Seeing a lot of these errors happen at random:

> error: invalid byte sequence for encoding "UTF8": 0xce 0x6c

The query is simply `SELECT 1` (I use it for liveness check).

It happens about ~150 times a day (out of ~80,000 queries per day).

Anyone know what's going on?

**Comment by PhilipTrauner** [comment]
In case you're running Node v22.7, its probably https://github.com/nodejs/node/issues/54521 😬

**Comment by lilouartz** [comment]
That's going to be exactly that!

**Comment by lilouartz** [comment]
Appears to no longer happen in v22.8
