### ISSUE TITLE
Empty message when AggregateError

### ISSUE THREAD

**Issue by BCsabaEngine** [brianc/node-postgres#3312]
I use pg under Drizzle. When I use a connection string with localhost, pg packages try to connect both 127.0.0.1 and ::1 (maybe DNS results are more than one). When connection failure I get an AggregateError instead of Error. The message parameter of AggregateError is empty. (If I change localhost to 127.0.0.1 the result is simple Error. In k8s enveronment the multiple dns result is a chance)

**It should be equel with the first error of aggregate.errors, because some framework is baed on error.message.**

**Comment by charmander** [comment]
> It should be equel with the first error of aggregate.errors

That sounds potentially misleading.

This is an error directly from the native `net.Socket#connect` Node API and not a concept introduced by pg, so I’m not sure there’s anything more for pg to do here – it sounds more like something to resolve between whatever (logging?) frameworks and Node. You should be prepared to handle the same type of error from everywhere that makes network connections.

**Comment by BCsabaEngine** [comment]
Well, will handle at proper level.
