### ISSUE TITLE
Release notes 8.13.0

### ISSUE THREAD

**Issue by kirrg001** [brianc/node-postgres#3315]
Hi there!

Could you please publish release notes for 8.13.0?

The diff looks pretty big:
https://github.com/brianc/node-postgres/compare/pg%408.12.0...pg%408.13.0

Thanks a lot

**Comment by markedwards** [comment]
Can we please have release notes?  We can't upgrade without knowing what's changed.

**Comment by Yareaj** [comment]
Bump on this!

**Comment by DavideViolante** [comment]
@brianc

**Comment by brianc** [comment]
https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#pg8130

**Comment by DavideViolante** [comment]
Sorry but the PR linked in the changelog changes just 2 lines of code and add 1 test, while the comparison between v8.12 and v8.13 are `807 additions and 1,558 deletions`.
A better detail on the changelog would be appreciated.
Also v8.13.1 is missing.

**Comment by DavideViolante** [comment]
I recommend you to use semantic-release or similar in the future so you can automate and improve the process of the releases and changelog.
There are at least 4 different (but closed) issues about changelog, so it's a problem that developers are now feeling.
Since pg is a core library in any project, we can't upgrade without knowing the changes and the reason of the changes, as @markedwards said.

**Comment by kirrg001** [comment]
cc @MyNameIsNeXTSTEP Could you please help?

**Comment by kirrg001** [comment]
The git diff https://github.com/brianc/node-postgres/compare/pg@8.12.0...pg@8.13.0 looks very big. It contains 28 commits, 807 additions and 1,558 deletions.

The community was wondering why the public [changelog](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#pg8130) only contains one change:

> Add ability to specify query timeout on https://github.com/brianc/node-postgres/pull/3074.

Could you please double check and confirm **that this is the only customer facing change?**

Thanks a lot!

**Comment by MyNameIsNeXTSTEP** [comment]
@kirrg001 
If i understood you correctly, here what i've done so far.

As I explored the [comparing changes](https://github.com/brianc/node-postgres/compare/pg@8.12.0...pg@8.13.0) I have found these customer facing changes *(which they may afce as client of the lib)* not inluded in the current changelog description for v8.13.0:

- PR [3114](https://github.com/brianc/node-postgres/pull/3114)
  - Docs example of **pg-cloudflare** usage in a non-nodejs environment
- PR [3170](https://github.com/brianc/node-postgres/pull/3170)
  - Check Cloudflare API environment first, fallback to NodeJS in case of failure
- PR [3251](https://github.com/brianc/node-postgres/pull/3251) (*maybe for contributiors*)
  - Devcontainer now uses **postgres:14-alpine**

**Comment by wulfsolter** [comment]
Fwiw, I am happy with current release practices and grateful for all the hard work and contributions over the years. Thank you! 

Straight forward enough to use git to see what files changed between releases.

**Comment by kirrg001** [comment]
I am also confused why there is no [changelog](https://github.com/brianc/node-postgres/blob/pg%408.13.1/CHANGELOG.md) entry for [8.13.1.](https://github.com/brianc/node-postgres/releases/tag/pg%408.13.1)

**Comment by DavideViolante** [comment]
Just use the github releases please @brianc , it's extremely simple:
- people make changes, merge some PRs
- go to releases, click New release, click "Generate release notes"
- click publish and all the changes will be very clear for everyone
