### ISSUE TITLE
Array serialization to text field

### ISSUE THREAD

**Issue by SparK-Cruz** [brianc/node-postgres#3319]
When assigning an array to a TEXT column it creates an invalid JSON of an object with string values of all objects as valid JSON strings inside.

I understand it's not using the built-in JSON serializer:
```
{"{\"label\":\"Campo\",\"value\":\"40,00\"}","{\"label\":\"Campo+Kit\",\"value\":\"100,00\"}"}
```

Expected JSON:
```
[{"label":"Campo","value":"40,00"},{"label":"Campo+Kit","value":"100,00"}]
```

To be fair `typeof []` is "object" so we gotta check for `Array.isArray([])` which is `true` only for arrays when serializing manually.

**Comment by charmander** [comment]
That’s the PostgreSQL text representation of the array. It’s what you would get from

```sql
SELECT ARRAY['{"label":"Campo","value":"40,00"}', '{"label":"Campo+Kit","value":"100,00"}']::text;
```

and is expected behavior.

If you want to insert JSON into your text field, you need to serialize it as JSON with `JSON.stringify`.
