### ISSUE TITLE
Add pg dependency to pg-native package

### ISSUE THREAD

**Issue by melroyvandenberg** [brianc/node-postgres#3321]
While I DID install `pg-native` npm package, I got the following error:

```sh
Error: Knex: run
$ npm install pg --save
Cannot find module 'pg'
Require stack: ...
```

This should **NOT** be needed, since you can just add the `pg` package as a [dependency for `pg-native`](https://www.npmjs.com/package/pg-native?activeTab=dependencies), now I need to both add `pg-native` and `pg` to my package.json file.

**Comment by melroyvandenberg** [comment]
PR created: https://github.com/brianc/node-postgres/pull/3322

**Comment by charmander** [comment]
> now I need to both add pg-native and pg to my package.json file.

Yes, that’s how [peer dependencies](https://github.com/brianc/node-postgres/blob/92cb640fd316972e323ced6256b2acd89b1b58e0/packages/pg/package.json#L43) work.

It’s not correct to import pg without adding a dependency on it (this is true of all Node packages), and while you can import pg-native without pg, it’s probably not the package you want.

**Comment by melroyvandenberg** [comment]
I was talking the other way around I think.. I added `pg-native` package, assuming that package also installs `pg` (which it didn't). Ah nevermind, I still don't get it.

**Comment by brianc** [comment]
yeah fwiw i don't use pg-native either. I've built multiple startups of various sizes (some exited for 9 figures already) using pg w/o native. if you really need the extremely minor speed improvements it gives in some situations you should probably not use node.js at all for your backend.  The added complexity and native dependencies aren't worth the overhead IMO. And pg w/o native performs better in some situations as well.
