### ISSUE TITLE
Parallel Queries Not Launching Workers

### ISSUE THREAD

**Issue by mikewang333** [brianc/node-postgres#3344]
Hi,

When I try to take advantage of [parallel queries](https://www.postgresql.org/docs/current/how-parallel-query-works.html), I'm noticing that the planned number of workers is 2 but 0 end up getting launched and my performance is slow.

<img width="175" alt="image" src="https://github.com/user-attachments/assets/381acd67-3611-4af7-8eaf-ff77948f9e89">

You can repro this with any GATHER MERGE like related queries e.g.:

```
CREATE TABLE test_gather_merge AS
SELECT
    generate_series AS id,
    md5(random()::text) AS random_text
FROM
    generate_series(1, 1000000);  -- Adjust the number of rows as needed

-- Query with ORDER BY to induce sorting with parallel processing
SELECT id, random_text
FROM test_gather_merge
ORDER BY random_text
LIMIT 100;
````

I've already tried upping things like `max_parallel_workers` and `max_worker_processes` and I noticed that with other postgres clients (e.g. Postico) the parallel workers are launched successfully so I assume it's not server related. 

Strangely enough if I run the queries with "Explain Analyze" in front, the parallel workers are launched successfully and execution is much faster. 

Anyone have any idea why parallel queries using this SDK are not executed with parallel workers?

Thanks!

**Comment by charmander** [comment]
How do you get the information in the screenshot without using `EXPLAIN ANALYZE`? Are you passing any additional configuration with the query, e.g. [`rows` as mentioned in the PostgreSQL documentation](https://www.postgresql.org/docs/17/when-can-parallel-query-be-used.html) (show the complete code of a reproducer)?

I can’t reproduce this:

```javascript
const {Client} = (await import('pg')).default;

const client = new Client({host: 'db', user: 'postgres'});

const sql = `SELECT id, random_text
FROM test_gather_merge
ORDER BY random_text
LIMIT 100;`;

const measure = async (name, opts) => {
    const start = performance.now();
    await client.query({text: sql, ...opts});
    const end = performance.now();
    console.log(`${name}: ${(end - start).toFixed(1)} ms`);
};

await client.connect();

console.log((await client.query('SHOW max_parallel_workers')).rows[0]);

await measure('warm up', {});
await measure('plain', {});
await measure('rows', {rows: 100});
await measure('explain', {text: `EXPLAIN ANALYZE ${sql}`});

await client.query('SET max_parallel_workers TO 0');

await measure('serial', {});

await client.end();
```

> ```
> { max_parallel_workers: '8' }
> ```
>
> | test | time |
> |--:|--:|
> | warm up | 36.4 ms |
> | plain | 34.1 ms |
> | rows | 83.9 ms |
> | explain | 240.7 ms |
> | serial | 82.1 ms |

**Comment by charmander** [comment]
Right, that’s a current server-side limitation that pg can’t help with.
