### ISSUE TITLE
DELETE Query Response Mismatch in PostgreSQL 16.3 Client

### ISSUE THREAD

**Issue by akash-cambium** [brianc/node-postgres#3352]
**Problem**
When executing a DELETE query using the PostgreSQL client in version 16.3, the msg.text value returned by the client does not match the expected result or the behavior observed in PostgreSQL CLI.

**For PostgreSQL 12 (Client Response):**
The msg.text value is DELETE 100, accurately reflecting the number of rows deleted.

**For PostgreSQL 16.3 (Client Response):**
The msg.text value is DELETE 0, which is incorrect when rows are successfully deleted.

**From PostgreSQL CLI (Both Versions):**
Executing the same DELETE query via the CLI outputs DELETE 100 for both PostgreSQL 12 and PostgreSQL 16.3, matching the expected behavior.

**Root Cause**
The discrepancy seems to originate from the PostgreSQL client’s response parsing logic. Specifically, the function responsible for parsing server responses incorrectly populates the msg.text value in PostgreSQL 16.3.

**Expected Behavior**
The msg.text returned by the PostgreSQL client should match the output of the CLI and accurately reflect the number of rows affected by the DELETE query.

**Summary**
The msg.text value from the PostgreSQL client in version 16.3 is inconsistent with the PostgreSQL CLI output, introducing potential issues when using this value to validate query execution.

**Comment by charmander** [comment]
I can’t reproduce this issue. Please add all the usual necessary information, and don’t run it through AI. AI is liable to make things up about the issue, and at best just wastes everyone’s time by expanding a tiny amount of information into several repetitive and noisy paragraphs like it’s done here.
