### ISSUE TITLE
Case statement evaluates every branch when checking against column

### ISSUE THREAD

**Issue by evaogbe** [brianc/node-postgres#3354]
## Steps to reproduce

1. Create a database with a table and a column. In this example, the table is foo and the column is bar.
2. 
```javascript
const res = await client.query(
  "SELECT CASE foo.bar WHEN 9999 THEN 1 / 0 ELSE 1 END FROM foo",
  [],
);
console.log(res.rows);
```

In the real app, the condition is dependent on a nullable column not being null

## Expected result

Prints `[]`

## Actual result

Errors with `error: division by zero`

## Additional notes

node 22.11.0
pg 8.13.1

It works as expected in online SQL editors or when the column is replaced with a literal value. It also fails if I move the column into the when expression like `WHEN foo.bar = 9999`. For some reason, every single branch is being evaluated when comparing against a column.

**Comment by charmander** [comment]
This looks like a question about PostgreSQL behavior, not related to pg the client library. (And yeah, that’s how PostgreSQL behaves.)
