### ISSUE TITLE
Wiki and FAQ disagree over prepared statement behavior

### ISSUE THREAD

**Issue by whitelynx** [brianc/node-postgres#345]
From [the FAQ](https://github.com/brianc/node-postgres/wiki/FAQ#9-can-i-create-a-named-prepared-statement-for-use-later-on-without-performing-a-query-if-not-does-passing-the-same-text-again-to-a-named-statement-get-ignored-and-the-cached-version-used-i-dont-want-to-have-two-codepaths-in-a-function-one-for-first-use-and-one-for-every-other):

> If a prepared statement has a `name`, it is only parsed once. After that, `name` will re-use the prepared statement regardless of what `text` is.

From [the wiki](https://github.com/brianc/node-postgres/wiki/Prepared-Statements#prepared-statements):

> (In node-postgres, if a new prepared statement is issued with the same name as an existent prepared statement, the existent prepared statement will be replaced and no error raised.)

So, the question is... which one accurately represents node-postgres's behavior? The wiki and/or FAQ should be updated to reflect the actual behavior.

**Comment by vitaly-t** [comment]
@brianc now I'm looking at it, trying to figure out how to do the following...

I have a Prepared Statement object that wraps it and returns an object automatically.

I want to make set `text` based on whether it was the same connection as during the last call to get the object. This requires to be able to identify the current connection via some sort of unique id.

Question: Is there such thing within the current connection that can be used to uniquely identify the connection?

**Comment by vitaly-t** [comment]
@brianc I think I got it figured out - `client.secretKey` contains that unique value that I need :)

**Comment by darkclouder** [comment]
You might want to update wiki/Prepared-Statements referring to this issue
