### ISSUE TITLE
feature request: support single row mode

### ISSUE THREAD

**Issue by kamholz** [brianc/node-postgres#366]
In postgres 9.2, libpq supports single row mode (see http://www.postgresql.org/docs/current/static/libpq-single-row-mode.html). If this were supported in node-postgres, it would allow the 'row' event to be emitted as rows are returned in real time. As it is currently, I believe the rows do not start to come in until the entire query has run on the server.

**Comment by MayhemYDG** [comment]
@brianc 
What's needs to be done for single row mode to work with native bindings?

**Comment by donspaulding** [comment]
Hi @brianc.  Thanks for node-postgres!

I'm using it to run a query where I expect to get 600K rows back, and I'm currently processing them one-at-a-time with the `query.on('row', callback)` mechanism.  My callback can't process the rows faster than pg can dump the data from the server, so as you allude to in your last comment on this issue, it chews through memory until it panics on a failed memory allocation.

It seems like a solution to this issue would entail something that would allow me to signal pg to pause retrieving results from the server and resume at a later time.  If so, that would fit my use case (only a single client on the server at a time retrieving 500,000+ rows in one query).

This is a fairly one-off script I'm writing, so for the sake of just getting things done, I've resorted to writing every row out to a temporary file on disk and then iterating over that file in chunks, stopping to process them before moving on to the next chunk of results.

I know you probably don't need a "me, too!" list started here, just thought I'd share what I did after running into this tonight.

**Comment by brianc** [comment]
I'd suggest you check out [pg-query-stream](https://github.com/brianc/node-pg-query-stream) or [pg-cursor](https://github.com/brianc/node-pg-cursor) - it allows very efficient "pagination" through a query result set in a streaming or cursor based way respectively.

**Comment by charmander** [comment]
The query object that emits events isn’t returned by default as of pg 7, and @brianc’s comment above has the right ways to handle this.
