### ISSUE TITLE
Add ability to set connect timeout

### ISSUE THREAD

**Issue by nfitch** [brianc/node-postgres#397]
I read the docs on client options:
https://github.com/brianc/node-postgres/wiki/Client#constructor

And didn't see a way to set the connection timeout.  A simple example of what I'd like to tune:

```
var pg = require('pg');

//Assuming no machine with ip 192.168.255.255 exists
var client = new pg.Client('tcp://root:root@192.168.255.255');
var start = (new Date()).getTime();
client.connect(function (err) {
        var end = (new Date()).getTime();
        console.log({
                err: err,
                elapsedTime: end - start
        });
});
```

Results in:

```
[nate@dev madtom]$ node ./test/postgres_timeout.js
{ err:
   { [Error: connect ECONNREFUSED]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect' },
  elapsedTime: 75818 }
```

Notice that the elapsed time is 75 seconds.

**Comment by jwhitehorn** [comment]
:+1:

**Comment by booo** [comment]
+1 comments are super helpful to understand problems...

**Comment by jhansen-tt** [comment]
+1

**Comment by brianc** [comment]
Anyone care to take a crack at this in a pull request?

**Comment by zacharyrankin** [comment]
hi @nfitch,

I was looking for the same thing.  I am not using the pool feature, but pg.Client
directly.  I was playing with a couple of ideas.

Example 1:

```js
let stream = new net.Stream()
stream.setTimeout(2000) // however many seconds
stream.on('timeout', function () {
  console.log('client timed out')
  this.destroy()
})
let config = {
  // connection info
  stream: stream
}
let client = new pg.Client(config)
client.connect(err => {
  if (err) {
    console.error(err)
  }
  console.log('connected')
})
```

In Example 1, if a query takes longer than 2 seconds to return
results I think it will also trigger that timeout.  So here was another idea I had if you
just wanted to have a connection timeout.

```js
let stream = new net.Stream()
let config = {
  // connection info
  stream: stream
}
let client = new pg.Client(config)
let connTimeout = setTimeout(() => stream.destroy, 2000)
client.connect(err => {
  if (err) {
    console.error(err)
  }
  console.log('connected')
  clearTimeout(connTimeout)
})
```

These are just some ideas.  Let me know your thoughts.

**Comment by charmander** [comment]
Implemented as [`connectionTimeoutMillis`][1].

  [1]: https://github.com/brianc/node-pg-pool#create

**Comment by charmander** [comment]
@aliok That looks like it might leak a connection if it succeeds after the timeout. See pg-pool:

https://github.com/brianc/node-pg-pool/blob/277dc508daea03a8f6c0bcc3c534cab5b2501b12/index.js#L209

**Comment by aliok** [comment]
@charmander  thanks a lot for taking a look  at that.

The context I am actually using that function is during a connection test. So, after the promise is resolved I do `client.end()` in the caller.

Thanks for showing me how to force kill: I will use it.
```
// force kill the node driver, and let libpq do its teardown
client.connection ? client.connection.stream.destroy() : client.end()
```

Gonna edit my previous comment to add a note to not confuse anybody :)
