### ISSUE TITLE
SSH connection to a postgresql database

### ISSUE THREAD

**Issue by BrandonCopley** [brianc/node-postgres#400]
Is there a method currently available for sshing into a postgresql database and then running queries?

I am a little bit naive on this, but I am researching how to implement, and if we don't have this I may try to integrate this.

**Comment by einfallstoll** [comment]
Even though this isn't related to the module, I want to share my knowledge, since I also came across this issue:

## SSH Tunnel
Setting up an SSH tunnel from `localhost:12345` to `my.host.name:5432` (default port for PostgreSQL)
````
ssh -L 12345:localhost:5432 my.host.name
````

## Connecting using `node-postgres`
**The important part is the hostname and port `localhost:12345 `**
````
var conString = "postgres://username:password@localhost:12345/database";
````

**Comment by daisy-cyt** [comment]
So how to connect to remote postgresql via ssh tunnel in nodejs not in command-line? I really want to know. Thanks a lot~

**Comment by einfallstoll** [comment]
@daisy-cyt I guess don't understand your question. To create an SSH Tunnel you must use a command line or a tool that does the same (e.g. [PuTTY](http://putty.org) for Windows or [SSH Tunnel](https://itunes.apple.com/us/app/ssh-tunnel/id734418810?mt=12) for macOS). This module has **no built in support** for connections via SSH, as far as I know.

**Comment by daisy-cyt** [comment]
@einfallstoll Thanks for your answer. I know there is a npm package called 'tunnel-ssh', but I don't know how to integrate to pg module.

**Comment by einfallstoll** [comment]
@daisy-cyt Should be really easy: Just start an SSH Tunnel using this package and connect to the port you specified. Pretty much the same as I did.

**Comment by pintop2** [comment]
var conString = "postgres://user:content@1234@44.201.10.10:12345/databasename";
 if i give the query to insert its printing up in console  of node .but if i check it in vm its not been shown up ; if i want to display the content which i have hard coded its not showing up can u give an soultion

**Comment by einfallstoll** [comment]
@pintop2 I didn't even understand half of your comment, but your connection string looks odd. It should look more like this:

    var conString = "postgres://user:password@123.123.123.123:5432/databasename";

**Comment by pintop2** [comment]
can u help me out in full connection. i tried with that too. i am not able to send data through this connection or retrive

**Comment by einfallstoll** [comment]
@pintop2 if the connection string seems correct you should test wether you can access the database, IP, port, ...

**Comment by andreikho** [comment]
Has anyone figured out how to do ssh-tunnel via code? Having some trouble :S

**Comment by charmander** [comment]
@andreikho Are you using an ssh package like https://www.npmjs.com/package/ssh2, running `ssh` as a child process, or at that decision point?

**Comment by andreikho** [comment]
It's working. The solution is here https://github.com/mscdex/ssh2/issues/67
