### ISSUE TITLE
Sometimes query returns empty result set

### ISSUE THREAD

**Issue by aleksandrmelnyk** [brianc/node-postgres#401]
Hello guys,

I am using node-pg inside node-any-db wrapper with pool min: 100 max: 200 connections. Sometimes result set is empty or incomplete (for example it returns 200 rows instead of 1800). Restarting node application fixes it. 
While it returns empty result set, I tried to run the query from another node.js cli script using same parameters and it works ok.
Any ideas what could it be? 

Thank you in advance,

Alex.

**Comment by orshee** [comment]
I have the same problem (node version 8.11.1, mssql 2016, mssql/tedious driver)
Sample output from a process that fetches data with same conditions repeatedly for 500 times as kind of a load test

Rows returned : 13
Rows returned : 13
Rows returned : 13
Rows returned : 13
Rows returned : 0
Rows returned : 13
Rows returned : 0
Rows returned : 13
Rows returned : 13
Rows returned : 13

**Comment by charmander** [comment]
@orshee This is the repository for https://www.npmjs.com/package/pg, a PostgreSQL driver.

**Comment by Darcody** [comment]
I have the same problem and it occures very often. Sometimes every 3 to 4 querries. Running ^7.14.0 for NodeJS. I make a count querrie and then a querrie for the data and it occures quiet often that either the count querry or the data querry return empty results.

**Comment by brianc** [comment]
@Darcody I need the version of node, pg, and a self-contained code example that reproduces the problem if you want me to take a look.  If you're saying you're using version `7.14` of _node.js_ then that's an unsupported version of node, btw.

**Comment by Darcody** [comment]
Never mind. It was our fault. We have two databases and a consule to which we connect and for some reason the databases were asynchron which resulted to empty results. Sorry for your inconvenience.
