### ISSUE TITLE
Record/composite types

### ISSUE THREAD

**Issue by lippling** [brianc/node-postgres#419]
Hey! Are there any plans to support record/composite types?

**Comment by yaacovk** [comment]
Can you please explain your answer?
I have an composite type and need to pass it to a postgreSQL stored procedure from node-pg code.
Is this a solution to my problem? If so, how?

**Comment by parauchf** [comment]
I don't think this specific thread will help you.  This is more about getting data out of postgres than getting it in.

**Comment by markgardner** [comment]
This will help a ton with doing batch updates/inserts. There might be a better way but this is how I'm trying to use it now, if there is a better way let me know. I've simplified the example table a bit but the idea is shown. For large record sets this will greatly improve performance.

I get this error when running the code below:
```
malformed record literal:
```

I can implement the feature if this is something that would be accepted if done correctly.

## PSQL
```sql
CREATE TABLE test (
    id bigserial PRIMARY KEY;
    datecreated timestamp DEFAULT (now() at time zone 'utc') NOT NULL,
    dateupdated timestamp DEFAULT (now() at time zone 'utc') NOT NULL,
    account_id bigint NOT NULL,
    title text NOT NULL,
    items jsonb NOT NULL
);

CREATE OR REPLACE FUNCTION test_update(_tests test[], _user_id bigint)
RETURNS SETOF test
AS $$
DECLARE
	__account_id bigint := _account_id_by_user(_user_id);
BEGIN
	RETURN QUERY
	UPDATE test as s SET
		dateupdated = (now() at time zone 'utc'),
		title = p.title,
		items = p.items
	FROM unnest(_tests) p
	WHERE
		s.account_id = p.account_id AND
		s.account_id = __account_id AND
		s.dateupdated = p.dateupdated AND
		s.id = p.id
	RETURNING s.*;
END
$$ LANGUAGE PLPGSQL;
```

## Javascript
```javascript
return new Promise(function(res, rej) {
    pg.connect(connString, function(err, client, done) {
        if(err) {
            return rej(err);
        }

        var sql = 'select * from test_update(_tests:= $1::test[],_user_profile_id:= $2::bigint)',
            sqlParams = [[{
                  id: '5738975851451532',
                  dateupdated: '2016-01-01T11:39:09.455Z',
                  account_id: '5738974869984257',
                  title: 't_agitated_ramanujan',
                  items: []
            }, {
                  id: '5738975834674275',
                  datecreated: '2016-01-01T11:39:09.455Z',
                  dateupdated: '2016-01-01T11:39:09.455Z',
                  title: 't_agitated_varahamihira',
                  items: []
            }], 123],
            query = client.query(sql, sqlParams);

        query.on('row', function(row, result) {
            result.addRow(row);
        });

        query.on('end', function(result) {
            done();

            res(result);
        });

        query.on('error', function(error) {
            done();

            rej(error);
        });
    });
});
```

**Comment by mitar** [comment]
@brianc Have you made the tool to do queries as nested structure? Is it available somewhere?

**Comment by brianc** [comment]
I haven't - the type parser is fully customizable so if you need to parse a special composite type you can [register the oid](https://github.com/brianc/node-pg-types) and then build a parsing function in your app.

**Comment by geoyws** [comment]
But the problem with registering the oid is that if we are using multiple psql instances, the oids will be different...
