### ISSUE TITLE
Returning Invalid syntax for type json on arrays

### ISSUE THREAD

**Issue by jrf0110** [brianc/node-postgres#442]
When your column is type json and you try and insert a JSON array, you get the following error:

``` javascript
{ [error: invalid input syntax for type json]
  length: 154,
  name: 'error',
  severity: 'ERROR',
  code: '22P02',
  detail: 'Expected string or "}", but found "1".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'JSON data, line 1: {1...',
  file: 'json.c',
  line: '665',
  routine: 'report_parse_error' }
```

For example, this works in PSQL:

``` sql
insert into my_table ( data ) values ( '[1,2,3]' );
```

But this returns an error in node-pg:

``` javascript
client.query('insert into my_table ( data ) values ( $1 )', [ [1,2,3] ], function( error ){
  /* ERROR */
});
```

**Comment by eriknyk** [comment]
Hi, this issue should be reopened, since in postgres shell is possible execute:

```
INSERT INTO public.my_table ("userId", "personId", books) VALUES (1, 1, '[1,2,3]');
```

Best Regards.

**Comment by jamesdixon** [comment]
I'm still running into this error even after stringifying the input array. Here's my JSON object:

```js
[
   { serviceId: 2, petId: 5, checked: true },
   { serviceId: 3, petId: null, checked: false }
]
```

After stringifying: 

```js
"[{"serviceId":2,"petId":5,"checked":true},{"serviceId":3,"petId":null,"checked":false}]"
```

I insert and receive the following error:

```
{"msec":54.03032702207565,"error":"update \"appointment\" set \"ended_at\" = $1, \"report_card\" = $2, \"staff_notes\" = $3, \"status\" = $4, \"updated_at\" = $5 where \"id\" = $6 - invalid input syntax for type json","data":{"message":"update \"appointment\" set \"ended_at\" = $1, \"report_card\" = $2, \"staff_notes\" = $3, \"status\" = $4, \"updated_at\" = $5 where \"id\" = $6 - invalid input syntax for type json","severity":"ERROR","code":"22P02","condition":"invalid_text_representation","detail":"Expected \":\", but found \",\".","where":"JSON data, line 1: {\"{\\\"serviceId\\\":2,\\\"petId\\\":5,\\\"checked\\\":true}\",...","file":"json.c","line":1198,"routine":"report_parse_error","name":"PgError","isBoom":true,"isServer":true,"data":null,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}}}
```

It appears the input is being stringified again. Am I missing something here?

Appreciate any help!

**Comment by brianc** [comment]
Here's an example of using a json data type & doing a round-trip query from node -> postgres -> and back to node with the json type preserved:

https://github.com/brianc/node-postgres/blob/master/test/integration/client/json-type-parsing-tests.js

Hope that helps!

**Comment by jamesdixon** [comment]
@brianc thanks for this. However, isn't this just testing on a single object and not an array of objects?

**Comment by jrf0110** [comment]
@jamesdixon using pg for arrays of objects is working fine for me:

```javascript
require('pg').connect( (error, client, done) => {
  if (error) throw error

  client.query('select $1::json as arr', [JSON.stringify([{foo: 'bar'}])], (error, result) => {
    done()
    if (error) throw error
    console.log(result.rows[0].arr) // => [{ foo: 'bar' }]
    process.exit(0)
  })
})
```

**Comment by jrf0110** [comment]
If you stringify first, you'll need to cast the value to `json` or `jsonb` depending on what you're using

**Comment by jamesdixon** [comment]
@jrf0110 thanks for this. I've confirmed this does work on insert as well. It appears something is double-stringifying my input. 

Appreciate the help, fellas!

**Comment by PythonDevOp** [comment]
@charmander so are issue 442 and [1143](https://github.com/brianc/node-postgres/issues/1143) overlapping issues? I see they are going back between open/close. @joskuijpers seemed to find my issue, I was wondering if any progress had been made regarding a solution

**Comment by charmander** [comment]
@PythonDevOp Yes, they’re the same issue. I’m not sure how @brianc wants to solve it, if at all, but you can use `JSON.stringify` manually in the meantime as seen above.

**Comment by brianc** [comment]
If you need to pass in an array of objects as a single JSON value then do what @jrf0110 has done and call `JSON.stringify` on the parameter yourself before adding it to your array of parameters.  node-postgres ignores any array parameter that's a string, passing it directly onto the wire and to the backend.  You might need to cast in your query.

**Comment by tamlyn** [comment]
Would it make sense for `node-postgres` to intercept this error and augment it with something like `Are you inserting an array into a JSON column? See <link to docs>`? Helpful error messages make for a nice developer experience.

**Comment by sparebytes** [comment]
A way to configure the default behavior would be desirable.

**Comment by oakgary** [comment]
@charmander should this be closed?
as a new user i just ran into this problem and only found the reason by this github issues

https://node-postgres.com/features/types would probably be a good place to mention this behaviour or as proposed above within the error message

**Comment by felixfbecker** [comment]
Would it be possible to hint at pg what the type of a value should be?

**Comment by felixfbecker** [comment]
PG Arrays vs JSON array can make a big difference to the query planner. `unnest()` on a PG array can correctly estimate the result row count given the input. `jsonb_to_recordset()` on the other hand has no such support function can will therefor be completely off in guessing the result, which may result e.g. in a different JOIN method to be chose (NESTED LOOP over HASH JOIN) and an extremely slow query.

**Comment by charmander** [comment]
> Would it be possible to hint at pg what the type of a value should be?

@felixfbecker Essentially, with `JSON.stringify`.

**Comment by felixfbecker** [comment]
Does that have any disadvantages? E.g. larger payload size over the wire to the DB?

**Comment by charmander** [comment]
No, it’s what pg does with objects too.

**Comment by felixfbecker** [comment]
pg-native too?

**Comment by charmander** [comment]
Correct. pg passes JSON to libpq, not JavaScript objects.

**Comment by danvk** [comment]
Another option is to make your column have a type of `jsonb[]` rather than `jsonb`.

**Comment by brianc** [comment]
open to a PR if you find a way to fix this!

**Comment by charmander** [comment]
@bbsimonbb Both of those approaches do work, so if you’d like some help, post the usual necessities (minimal reproducible example, debugging details).
