### ISSUE TITLE
A quotemeta() convenience function would be nice.

### ISSUE THREAD

**Issue by EvanCarroll** [brianc/node-postgres#446]
When the user provides input there should be some way to sanitize it as a literal. This is provided in most languages as a core function quotemeta() in perl for instance.

It would be nice if the query object provided such a function. I can patch if it you're interested.

Then you could do something like

`[ '%' + Query.quotemeta(req.params(s)) + '%' ]`

For the parameterized input, and if the user supplied a '_' or '%' inside it's meant to be taken literally. In fact, I think it'd be good to suggest that of all req.params be sanitized in the docs.

**Comment by aashidham** [comment]
@brianc @rpedela I'm curious about the state of this issue, since it has been a few years. Is this issue resolved?

**Comment by rpedela** [comment]
OP never made it clear what was wrong. What related issue are you having and can you provide example code? If you just need escaping then I recommend [pg-format](https://github.com/datalanche/node-pg-format) which I wrote.

**Comment by aashidham** [comment]
How is this different from what is used in pg mom module directly? I thought that format syntax did this escaping by default.

**Comment by rpedela** [comment]
If you meant "pg module" and the "mom" part is a typo, then pg does not escape by default. It has parameterized queries where the query and parameters are sent separately over the wire and then the server inputs those parameters into the query in a safe manner. pg also has ```escapeLiteral``` and ```escapeIdentifier``` functions which only work for strings (I ported them from Postgres C code).

[pg-format](https://github.com/datalanche/node-pg-format) handles escaping for all JS and Node types and it can be used in situations where parameterized queries don't work. For example, let's say you wanted to dynamically specify the list of columns in a SELECT. You must escape each column name as an identifier to protect against SQL injection, but that is not possible with parameterized queries.

```js
// SELECT a, b, c FROM my_table
var pg = require('pg');
var pgFormat = require('pg-format');

var columns = [ 'a', 'b', 'c' ];

// using pg
var escapedColumns = [];
for (var i = 0; i < columns.length; i++) {
    escapedColumns.push(pg.escapeIdentifier(columns[i]));
}
var sql = 'SELECT ' + escapedColumns.join(',') + ' FROM my_table';

// using pg-format
var sql = pgFormat('SELECT %I FROM my_table', columns);
```

This is a trivial example, but [pg-format](https://github.com/datalanche/node-pg-format) handles a lot of the logic you would have to write yourself so it simpler and correct.

**Comment by aashidham** [comment]
I see. That was a typo on my end, apologies, I meant to say npm.

What about in this scenario:

//using pg
var arr = ['bob', 'cat'] //arr is populated from user input
pool.query('select col1 from containers_hist where ipaddr= ANY ($1)', arr)

Is pg protecting me from user input in this case?

**Comment by rpedela** [comment]
That is a parameterized query and yes you would be protected. If you wanted to use [pg-format](https://github.com/datalanche/node-pg-format) instead, here is the equivalent query.

```
var pgFormat = require('pg-format');
var arr = ['bob', 'cat'];

var sql = pgFormat('SELECT col1 FROM containers_hist WHERE ipaddr = ANY (ARRAY[%L])', arr);

// alternative version
var sql = pgFormat('SELECT col1 FROM containers_hist WHERE ipaddr IN (%L)', arr);

pool.query(sql);
```
