### ISSUE TITLE
Native query callback issue...

### ISSUE THREAD

**Issue by BrandonCopley** [brianc/node-postgres#449]
I found a small issue with the documentation vs. the code:

When running a query, the documentation specifically states when running a simple query with callback to do this:

var query = client.query("SELECT name FROM users", function(err, result) {
    console.log(result.rows[0].name);
  })

However, we have found that in order for the callback to actually function with the ERR

we have to use:

var query = client.query("SELECT name FROM users", null, function(err, result) {
    console.log(result.rows[0].name);
  })

It appears that something is breaking, because I found that when making large queries in query.js under native, this was being called - this.emit('error', error); - even though I had specifically specified a callback.

**Comment by paragi** [comment]
This is still (or again?) an issue.

var query = client.query(sql, function(err, result) {
  ...
})

fails. eg. returns an old result buffer. Where as

var query = client.query(sql, null, function(err, result) {
  ...
})
works!
