### ISSUE TITLE
Is there a way to pause and resume query output?

### ISSUE THREAD

**Issue by jlfaber** [brianc/node-postgres#460]
I'm using the eventEmitter model to handle the results from a query that produces a large number of rows.  The handler has some async components, so I'd really like to be able to keep the next 'row' event from firing until after the current one has completed processing.  

Ideally this would take to form of pause() and resume() calls on the query object itself.

``` javascript
 var query = client.query("select * from big_data_table");
 query.on('row', function (row) {
    query.pause(); // turn off the firehose
    return do_something_async(row, function() {
      query.resume(); // turn back on the firehose
    });
 });
```

**Comment by danteleon** [comment]
Hi! sorry for re-opening this, but I was wondering if you were able to achieve what you were looking for @jlfaber ? 

I tried following @brianc advice but I couldn't achieve that behavior that Joe is looking for through pg-query-stream.

I figured out that maybe there's another option available to this date , I'm basically looking for exactly this:
"The handler has some async components, so I'd really like to be able to keep the next 'row' event from firing until after the current one has completed processing."

Thanks guys! any feedback will be greatly appreciated.

**Comment by jgoux** [comment]
I'm interested as well. I'd like to handle an async process inside the `data` handler, and receive the next row only when my async process in the handler is over.

**Comment by brianc** [comment]
You can also try https://github.com/brianc/node-pg-cursor which gives you very direct control of when and how many rows you return at a time.

**Comment by danteleon** [comment]
@brianc thank you for quick response! I ended up using query-stream.

@jgoux  this worked for me buddy:

var QueryStream = require('pg-query-stream')
var pg = require('pg')

var conString = "yourConnectionString";
var client = new pg.Client(conString);

client.connect(function(err) {
       if(err) {
             return console.error('could not connect to postgres', err);
        }

	if(err) throw err;
	var query = new QueryStream(queryStr, values)
	var stream = client.query(query)

	stream.on('data', function(row) {
		stream.pause();
	        //handle your async process here
		stream.resume();
	})
	stream.on('end', function() {
		client.end();
	})
});

Cheers!

**Comment by cyberjoac** [comment]
Thanks for your code ! 
I have an issue with it though, stream.on('end' gets called BEFORE the last resume (last row).

Thanks a lot.

**Comment by danteleon** [comment]
Anytime! I noticed that issue too, for that I had to use flags in order to process the last record only if I am at the 'end' event and there isn't any other record being processed on 'data'. So basically:


    .on('end', function() {

        // Received End Event
        receivedEE = true;

        // Process Last Row
        if(receivedEE && !processingRow)
        {
          processLastRow();
        }

    });


where processLastRow consists of whatever you are doing to your rows on 'data'.

________________________________

**Comment by cyberjoac** [comment]
Thanks a lot !
