### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by zanothis** [brianc/node-postgres#462]
I'm not sure if this is an issue with binding.gyp or if it's an issue with node-gyp, but here are the results of installing pg.

<pre>
$ npm install pg --save
npm http GET https://registry.npmjs.org/pg
npm http 304 https://registry.npmjs.org/pg
npm http GET https://registry.npmjs.org/generic-pool/2.0.3
npm http GET https://registry.npmjs.org/buffer-writer/1.0.0
npm http 304 https://registry.npmjs.org/generic-pool/2.0.3
npm http 304 https://registry.npmjs.org/buffer-writer/1.0.0
npm http GET https://registry.npmjs.org/cloned/0.0.1
npm http GET https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/cloned/0.0.1
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/rmdir
npm http 304 https://registry.npmjs.org/rmdir

> pg@2.8.2 install /home/username/node_projects/writer/node_modules/pg
> node-gyp rebuild || (exit 0)

/bin/sh: 1: pg_config: not found
gyp: Call to 'pg_config --libdir' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.8.0-19-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/username/node_projects/writer/node_modules/pg
gyp ERR! node -v v0.10.20
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
pg@2.8.2 node_modules/pg
├── generic-pool@2.0.3
└── buffer-writer@1.0.0 (async@0.2.9, cloned@0.0.1)
</pre>

**Comment by ndey96** [comment]
Ran into this problem on OSX (10.11). The solution was to
```
export PATH=/Library/PostgreSQL/9.3/bin:$PATH
```
creds to http://stackoverflow.com/questions/21713680/can-not-install-node-postgres

**Comment by ndey96** [comment]
Ran into this problem on OSX (10.11). The solution was to
```
brew install postgresql
```
creds to http://stackoverflow.com/questions/32948935/gyp-failing-when-installing-pg-native
AND
```
export PATH=/Library/PostgreSQL/9.3/bin:$PATH
```
creds to http://stackoverflow.com/questions/21713680/can-not-install-node-postgres

I definitely think this would be worth adding to the docs
