### ISSUE TITLE
restarting postgres throws an error

### ISSUE THREAD

**Issue by chani3** [brianc/node-postgres#465]
if I restart postgres, pg, throws an error like so:

events.js:72
        throw er; // Unhandled 'error' event
              ^
error: terminating connection due to administrator command
    at Connection.parseE (/home/ec2-user/source/releases/20131108025818/node_modules/pg/lib/connection.js:558:11)
(sorry, the rest of the BT was lost)

it should call my callback with the error instead, so that I don't have to resort to ugly hacks to make sure it's caught.

**Comment by Protosac** [comment]
I'm having the same error. It happened while configuring passport-github authentication. I tried the code at pull request #468 but the same error occurs. In the browser console I'm getting a `ERR CONNECTION REFUSED` error, but I can't tell where this is coming from.

![screenshot from 2015-01-01 02 06 50](https://cloud.githubusercontent.com/assets/6880594/5591984/e9fafa44-915a-11e4-85b5-b3cd6c2996f1.png)
