### ISSUE TITLE
periodic errors fetching a client from a pool

### ISSUE THREAD

**Issue by domino14** [brianc/node-postgres#479]
I call the following function and the "error fetching client from pool" line gets logged:

```
  function getPointsByDates(name, beginDate, endDate, callback) {
    var query;
    query = {
      text: [
        "SELECT name, value, ts FROM timeseries_data WHERE ",
        "ts between '", beginDate.format(), "' and '", endDate.format(), "'",
        " and name = $1 ORDER BY ts"
      ].join(''),
      values: [name]
    };
    pg.connect(conString, function(err, client, done) {
      if (err) {
        console.log('Error fetching client from pool', err);
        callback(err);
      }
      client.query(query, function(err, result) {
        done();
        callback(err, result);
      });
    });
  }
```

The error that gets logged:

```
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

This happens mostly on startup (when I restart my script) for a few minutes but after a while everything is fine and works. The postgresql database is running the whole time. Has anyone seen this behavior?

**Comment by traegerp** [comment]
I am experiencing the same problem on OSX 10.11.14 with node 6.1.0 and postgres 9.4.  I will get an error stating: error fetching client from pool { error: password authentication failed for user "postgres" but if i run the command from node to execute a simple query say 15 times, it'll eventually go through.
