### ISSUE TITLE
Many properties are not present in result.fields when using native binding

### ISSUE THREAD

**Issue by raycmorgan** [brianc/node-postgres#481]
When using pg.native result.fields (of a select query) only contains `{name: 'id', dataTypeID: 32}`

When not using native, you get:

```
{ name: 'id',
  tableID: 16769,
  columnID: 6,
  dataTypeID: 23,
  dataTypeSize: 4,
  dataTypeModifier: -1,
  format: 'text' }
```

**Comment by brianc** [comment]
FYI I'm tracking this (in a different issue) for pg@7.0.  Better late than never I guess. :smiley_cat: 

https://github.com/brianc/node-postgres/issues/988
