### ISSUE TITLE
How do I pass Boolean values in?

### ISSUE THREAD

**Issue by mjhamm75** [brianc/node-postgres#499]
I am trying to pass Boolean values in and I keep getting an error that of a syntax error, near the value.  I have tried "true"/"false", true/false, "0"/"1" and 0/1.  Do you have any examples or a gist that you can show me how to use Boolean values?  Thanks

**Comment by oop** [comment]
I'm having the same issue and couldn't find any solution yet...
![image](https://user-images.githubusercontent.com/5330471/50907204-3c154480-1440-11e9-8c3b-eb768ba70ac5.png)

**Comment by charmander** [comment]
@oop With `UPDATE SET`, use commas, not `AND`s.

**Comment by oop** [comment]
> 
> 
> @oop With `UPDATE SET`, use commas, not `AND`s.

Silly me. Thank you very much!
