### ISSUE TITLE
Results from multiple statements query returned as single dimensional array

### ISSUE THREAD

**Issue by traderboy** [brianc/node-postgres#508]
I have 3 queries I'm running as multiple statements, but the results are all returned in a single dimensional array.  The MySQL library returns multiple statement queries  in a multidimensional array.  The problem is I can't tell which results come from which query.

SQL: select id from table1;select id from table2;select id from table3;

PG:
row: [ {aaa},{bbb},{ccc}]

MySQL:
row: [ [{aaa}], [{bbb}], [{ccc}] ]

**Comment by clayzermk1** [comment]
:+1: 

What is the current status of this feature? Are you still looking for pull requests?

**Comment by matt212** [comment]
reference topic  
https://github.com/brianc/node-postgres/issues/1190#issuecomment-301101575

**Comment by brianc** [comment]
Added this to the pg@7.0 release milestone. Long standing bug but it should be fixed.

**Comment by brianc** [comment]
This is fixed in pg@7.0

**Comment by vitaly-t** [comment]
While this does improve the driver nicely, for any library that works based off the results returned from the driver, it screws up everything, and requires major changes.

There is probably not a single library out there ready to handle multi-result sets. This can cause a havoc :smile:

**Comment by alitaheri** [comment]
@vitaly-t It has, it broke sequelize badly, and we don't know how to handle multiple statements throughout the library 😅 😅 But it was needed. necessary evil 😈 

Thanks @brianc for this nice feature. 👍 👍 Hope we can migrate soon so others can use it from sequelize too 💟

**Comment by vitaly-t** [comment]
@alitaheri same here, I'm stuck trying to figure out a good approach to supporting multiple results in `pg-promise`. I have already redesigned everything for that, but released nothing, as I'm not too happy about the new architecture, it seems too verbose. Here's me discussing some of it with the author of `massive.js`: https://github.com/vitaly-t/pg-promise/issues/371
