### ISSUE TITLE
Client documentation includes removed pauseDrain/resumeDrain

### ISSUE THREAD

**Issue by jamesjenner** [brianc/node-postgres#515]
The doco for client still states that pauseDrain/resumeDrain exists, with an example showing how to use them. 

Other examples also use the drain event to do a `client.end.bind(client)`. 

This creates a problem with dependent queries, as the drain is fired before the dependent queries are added. It's not clear from the doco how to handle dependent queries.

**Comment by brianc** [comment]
This issue's been fixed.
