### ISSUE TITLE
Timeout slow queries ?

### ISSUE THREAD

**Issue by riston** [brianc/node-postgres#518]
What to do you think about adding check if the query time exceed certain limit then it stops the execution ?

**Comment by davisford** [comment]
FWIW @brianc I disagree.  I think this library should expose this as a configurable option.  We're hitting some nasty issues with this now on our data warehouse.  We're lucky enough that we have complete control over the database, so we can configure this in postgres itself, but I feel pretty strongly that the right thing to do is expose the ability to set this in the library itself.

**Comment by juliusza** [comment]
statement_timeout (integer) would work only while client has connection to server, what if your TCP connection is stuck instead? Timeout should be implemented in PG driver as well.

**Comment by edevil** [comment]
So, just to be clear, there is currently no way to specify a query timeout via configuration that would guard against a non-responsive server (after establishing the connection)?

**Comment by abenhamdine** [comment]
fro thread readers : see also https://github.com/brianc/node-pg-pool/issues/85 for timeout issue when the pool is full
unfortunately, the fix is not released yet
