### ISSUE TITLE
{ [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }

### ISSUE THREAD

**Issue by Egidius** [brianc/node-postgres#520]
I recently switched from MySQL to postgres as my database for an node.js project. While I'm able to reach my remote postgres database from my local pgAdmin III (OSX) client, so far I've been unable to connect to my database through node.js. I'm sure that the credentials I entered for pgAdmin and my node.js were exactly the same. The other thing I've tried was setting my local ipadress to trust in stead of md5 in the pg_hba.conf at my database server. Is there anything I did wrong? My favourite search engine came up with some worrying hits about resetting my local os. I just used the example from the github repo doc of node-postgres:

var pg = require('pg');

var conString = "postgres://myusername:mypassword@hostname:5432/dbname";

var client = new pg.Client(conString);
client.connect(function(err) {
  if(err) {
    return console.error('could not connect to postgres', err);
  }
  client.query('SELECT NOW() AS "theTime"', function(err, result) {
    if(err) {
      return console.error('error running query', err);
    }
    console.log(result.rows[0].theTime);
    client.end();
  });
});

And these are the errors I get every time I try to start my server:

could not connect to postgres { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }

Help would be greatly appreciated

**Comment by tophsic** [comment]
Is that confirmed `pg` package does not support password with hashtag ?

**Comment by brianc** [comment]
It supports it. Don't use a connection string, use a config object and pass
it as { host: 'foo', password: 'blah#blah' } etc.

**Comment by tophsic** [comment]
Thx

**Comment by Egidius** [comment]
Indeed. If you use a connection string you should escape it, I learned the hard way: http://stackoverflow.com/questions/21740560/node-server-cant-connect-to-postgres-db/21765024#21765024
