### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by Sneppers** [brianc/node-postgres#532]
My host provider requires SSL (Heroku) to connect from remote locations.
Any idea on how to enable SSL in the connection string?

postgres://user:pass@host:port/database;

Been looking for it everywhere but it does not seem to be a very popular topic.
By the way, am using the connection-pooled method:

pg.connect(connString, function(err, client, done) {
  /// Should work.
});

Please, let me know.

**Comment by hunterloftis** [comment]
@brianc @lepinsk, I've updated the docs so users following them will always start with the latest version of `pg`. That should help folks avoid resolved issues in the future.

I've also added a note about the ssl requirements:

- https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js

**Comment by parris** [comment]
Don't mean to re-awaken this dead thread. But I see that node-postgres wants some certs now. Does `ssl: true` still work?
