### ISSUE TITLE
Error: syntax error at or near "$1" with super simple query

### ISSUE THREAD

**Issue by tj** [brianc/node-postgres#539]
any query using `.query(string, [value...], fn)` gives me this error, even with the appropriate number of values, did the api change or something? Even simple stuff like:

``` js
    client.query('create user $1 with password \'Something1\'', ['tobi'], function(err){
      if (err) throw err;
      console.log('created');
    });
```

I'm probably doing something obvious wrong :D

**Comment by gajus** [comment]
Is there somewhere Postgres documentation that identifies all contexts in which prepared statements cannot be used?

**Comment by gajus** [comment]
Found it:

> Another restriction on parameter symbols is that they only work in SELECT, INSERT, UPDATE, and DELETE commands. In other statement types (generically called utility statements), you must insert values textually even if they are just data values.

https://www.postgresql.org/docs/9.1/plpgsql-statements.html
