### ISSUE TITLE
Error message when trying to make 2 database calls.

### ISSUE THREAD

**Issue by richaagr** [brianc/node-postgres#563]
Hi Brian,
I am trying out my first app with node-postgres. My database call functions look like these:
Code in app.js:
        var pg = require('pg');
        var conString = "postgres://postgres@localhost:5432/postgres"
        var dbClient = new pg.Client(conString);

Index.js :

```
exports.submitResponse = function (dbClient) {
   return function (req, res) {
        var feedback = req.body.feedback;
        dbClient.connect(function (err) {
              if (err) {
                   return console.error('could not connect to postgres', err);
              }
            dbClient.query('CREATE TABLE IF NOT EXISTS Feedback (id bigserial);');
            dbClient.query('INSERT INTO Feedback (id) VALUES($1);', [feedback],
            function (err, result) {
                if (err) {
                    console.log(err);
                } else {
                    console.log("Row Inserted:" + feedback + result);
                    dbClient.end();
             }
      });
      res.render('index', {feedback_response: "Thanks for the feedback."})
     });
  }};

  exports.notify = function (dbClient) {
           return function (req, res) {
            var email = req.body.email;
             dbClient.connect(function (err) {
            if (err) {
                return console.error('could not connect to postgres', err);
             }
           dbClient.query('CREATE TABLE IF NOT EXISTS NotifyDetails (email text);');
           dbClient.query('INSERT INTO NotifyDetails (email) VALUES($1);', [email],
           function (err, result) {
              if (err) {
                  console.log(err);
             } else {
        console.log("Row Inserted:" + email + result);
        dbClient.end();
       }});
       res.render('index', {email_response: "Thanks."})
        });
   }
};
```

If I make one of these calls things are fine, but if both notify and submitResponse are called then I get this error. I guess this is somehow related to incorrect connection pooling. Can you help??
events.js:72
        throw er; // Unhandled 'error' event
              ^
error: invalid frontend message type 0
    at Connection.parseE (/WebApp/node_modules/pg/lib/connection.js:561:11)
    at Connection.parseMessage (/WebApp/node_modules/pg/lib/connection.js:390:17)
    at null.<anonymous> (/WebApp/node_modules/pg/lib/connection.js:92:20)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)

**Comment by RyanPliske** [comment]
This helped a lot. Thanks.

**Comment by vastus** [comment]
Thanks, had the same problem. More discriptive errors would be nice.
