### ISSUE TITLE
Creating a read only client

### ISSUE THREAD

**Issue by davetapley** [brianc/node-postgres#569]
I'd like to ensure all the queries going though a [client](https://github.com/brianc/node-postgres/wiki/Client) are read only.

I can simulate this in `psql` using [`SET SESSION CHARACTERISTICS`](http://www.postgresql.org/docs/9.3/static/sql-set-transaction.html), thus:

```
psql (9.3.4, server 9.2.8)
Type "help" for help.

dave=# SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY;                                              
SET
dave=# DELETE FROM visit WHERE date = '2014-04-08 09:52:54.09';
ERROR:  cannot execute DELETE in a read-only transaction
```

What would be a smart way to go about doing this in node-postgres?

**Comment by rex-remind101** [comment]
Have there been any changes related to more easily allow read only clients since it was last discussed?
