### ISSUE TITLE
 no pg_hba.conf entry for host 

### ISSUE THREAD

**Issue by joaquimknox** [brianc/node-postgres#575]
I am new to node, so forgive me if this is a silly question.
I have written a node js/express/postgress app on my local system and things work great.
I tried to move the app to the Amazon Cloud -- everything the postgress DB and node code. When the node app tries to connect to the postgress DB I see this error:
 error: no pg_hba.conf entry for host "54.201.213.227", user "automation", database "automationdb", SSL off

I tried using:
var pg                  = require('pg').native;

but it does not help.

**Comment by vinniciusJ** [comment]
guys, can you help me out? I have the same problem. I'm trying to connect my application with a Heroku Postgres database and when I try to get some information from the db it returns this error. I've already set PGSSLMODE=require at .env and it isn't working.

**Comment by charmander** [comment]
@vinniciusJ Can you show the full error message? Make sure to check the username and database name.
