### ISSUE TITLE
Maybe bug in PG.prototype.cancel

### ISSUE THREAD

**Issue by kobalicek** [brianc/node-postgres#579]
Just wondering if the function is implemented the right way.

As I understand it checks if the 'config' has been passed, but it doesn't correct 'client' and 'query' parameters which are passed to cancellingClient in case 'config' it hasn't been passed.

Is that intentional? Maybe checking 'arguments.length' would be much nicer.

```
PG.prototype.cancel = function(config, client, query) {
  var c = config;
  //allow for no config to be passed
  if(typeof c === 'function') {
    c = defaults;
  }
  var cancellingClient = new this.Client(c);
  cancellingClient.cancel(client, query);
};
```

**Comment by whitelynx** [comment]
When this gets fixed, it'd be nice to modify `Client#cancel` to be able to be called with just the query. (it would do something similar to `pg.cancel`: create a new Client instance using `this.connectionParameters`, and call the new client's `cancel` method) This would allow you to cancel queries using `client.cancel(query)` for both the pure JS and native clients.

**Comment by brianc** [comment]
`PG.prototype.cancel` is being deprecated in `pg@7.0`
