### ISSUE TITLE
How do I get the error message out of the error object?

### ISSUE THREAD

**Issue by kasperpihl** [brianc/node-postgres#596]
I'm a little confused about the errors node-postgres sends back.
I get an error object like below, but it is misformed json and I can't access the message inside the first array. I wan't to handle the error to save out the situation.

{ [error: null value in column "title" violates not-null constraint]
  name: 'error',
  length: 287,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (36284, null, null, 0, 2014-05-21 17:11:56.119877+03, null, o7d3qkV7Dk, null, null, 0, null, null, null, Mx0IyT, f, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'execMain.c',
  line: '1611',
  routine: 'ExecConstraints' }

**Comment by mietennet** [comment]
as @Rauno56 suggests, thats my solution:

    function getErrorMessage(e) {
      return JSON.parse(
          JSON.stringify(e, ['message'])
        ).message;}
