### ISSUE TITLE
throw er; //Unhandled 'error' event

### ISSUE THREAD

**Issue by atlantageek** [brianc/node-postgres#609]
Trying to run simple example from README.md and getting error.

The only difference is the connection string.  localhost database does not requr a password.

var pg = require('pg');
//or native libpq bindings
//var pg = require('pg').native

var conString = 'postgres://metricdb:@localhost:5432/metricdb'

var client = new pg.Client(conString);
client.connect(function(err) {
  if(err) {
    return console.error('could not connect to postgres', err);
  }
  client.query('SELECT NOW() AS "theTime"', null,function(err, result) {
    if(err) {
      return console.error('error running query', err);
    }
    console.log(result.rows[0].theTime);
    //output: Tue Jan 15 2013 19:12:47 GMT-600 (CST)
    client.end();
  });
});

**Comment by joskuijpers** [comment]
@brianc this can be closed, the same issue is posted in the comments of #613

**Comment by brianc** [comment]
👏
