### ISSUE TITLE
Array Query Parameter with IN operator

### ISSUE THREAD

**Issue by Cosrnos** [brianc/node-postgres#623]
I have a query where I'm trying to retrieve a list of posts that have a post type that is in an array. For example...

```
SELECT * FROM posts WHERE post_type IN ('post', 'comment')
```

I'm trying to use query parameters for this so I started off with the following:

```
SELECT * FROM posts WHERE post_type IN $1
```

and pass in the array ['post', 'comment']. However I get an error stating there's a problem with my syntax near $1. I tried wrapping the $1 in parenthesis and while this query executed, it returned no rows while my original query (without parameters) would return at least 5 rows.

I'm wondering what PG does with array parameters that's causing this query to return 0 rows. I would expect that if I passed an array as a parameter that I should be able to use it with an IN operator. Am I missing something or is this perhaps a bug?

**Comment by erayhanoglu** [comment]
Hi, 
There is an other problem about this issue.
using ANY($1) works fine only if array has one dimension. Think that we want to query from a table with 2 keys fields. So we need arrays of array.

The query below works:
`select * from my_table where (key1, key2) in (('a1','a2), ('b1','b2))`

But if we want to use parameters, like below:
`client.query('select * from my_table where (key1, key2) in ANY($1)', [[ ['a1', 'b2], ['a2', 'b2]]]])` returns `input of anonymous composite types is not implemented` error.

**Comment by tonyxiao** [comment]
Out of curiosity, does typeorm do the building inlist clause manually as specified in @brianc 's post above? cc @pleerock
