### ISSUE TITLE
Many Insert Rollback Buffer

### ISSUE THREAD

**Issue by defnorep** [brianc/node-postgres#648]
Hi,

I have a large number of inserts that are fired in a loop. I would like to be sure that each insert is committed to the database and that node-postgres is not filling up memory with the rollback buffer.

I do not see any pg/pg.connect options for what I am discussing, so it is most likely set to auto-commit. 
It seems that all of the transactional/commit-type logic is contained in the client.transact method, but I would like to be 100% certain of the behavior before calling my application complete. 

Thanks!

**Comment by Johnchristian99** [comment]
@jcalderonzumba

I am in similar situation where I need to use Postgres functions but I have a question it may sound dumb but I am new to SQL and JavaScript.
How do you include and use those functions in main project files like in controllers? I am using ExpressJS framework.
I will write the functions in .sql files so should I just keep those .sql files in a directory in project root directory and include those files directly in my js controller files like this var sqlFunctions = require(‘./sql-directory/productfunctions.sql’); and then use function like this sqlFunctions.MyFunction() or those files needs to be compiled someway then functions will be accessible directly then use? can you please help me.

Thanks,
John
