### ISSUE TITLE
Hang on client.query()

### ISSUE THREAD

**Issue by defnorep** [brianc/node-postgres#656]
I have an application that is storing tens of thousands of rows.

I use async.each to manage the insert, calling `pg.connect()` to complete the insert inside of the async.each iteration, and calling `done()` when the query returns.

I am able to store my full dataset using this method, 45k+ rows.

The problem occurs when, in the same HTTP call, I use `pg.connect()` again, and try to query once more.

``` language-javascript
// Generate SQL `INSERT INTO table (columns) (SELECT...))`
pg.connect(connString, function(err, client, done){
  if(err) {
    log.error(err);
    done();
    return;
  }

  // This is the last thing I see in my logs... it sits here indefinitely
  log('Created connection into Postgres, running query...');

  client.query(sql, function(err, result){
    // App never gets this far
    log('Query complete');
  });

});
```

Just in case I have problems with the many insert queries, I've been doing everything I can think of for connection pooling. Inspecting it, turning off the pooling, setting pool limit to 20... The real kicker is this all works fine on my development machine, but as soon as we push this into staging the problem starts occurring.

I have set both node versions to be v0.10.30, the problem still only occurs on staging, which is a CentOS distribution. My local environment is OSX Mavericks.

I am starting to think there are other issues at play here but I might as well see if the node-pg community has some insight for me. Thanks.

**Comment by jacobbogers** [comment]
Hi BrianC I am having the same issues, what was the solution?
