### ISSUE TITLE
Queries are not sent until previous queries are done, nullifying all advantages of using Node

### ISSUE THREAD

**Issue by jusou** [brianc/node-postgres#660]
This module waits to send a query until the results of previous queries arrive from PostgreSQL.

This is an issue that nullifies all advantages of using Node: the whole point of using Node is that you can easily make requests in parallel and receive answers asynchronously.

With this  implementation, doing N queries results in N database roundtrips, even if the queries are issued in parallel, while of course there should be more than 1 roundtrip only if subsequent queries need the output of previous ones.

For instance, if you try to insert a million objects in parallel with this library in its current state using separate queries, you will create a million of unnecessary database roundtrips. 

You can see this easily with the following code:

```
var pg = require('postgres-bluebird');
var Promise = require('bluebird');

pg.connectAsync('/run/postgresql').spread(function(c, done) {
    return Promise.all([
        c.queryAsync("SELECT pg_sleep(10)"),
        c.queryAsync("SELECT 31337")
    ]).finally(function() {done(c);});
}).done();
```

Just run it through strace to get this result:

```
$ strace -t -s 65535 node test.js 2>&1|grep -E 'pg_sleep|31337'
[...]
22:43:22 write(10, "Q\0\0\0\30SELECT pg_sleep(10)\0", 25) = 25
<-- 10 seconds gap
22:43:32 read(10, "T\0\0\0!\0\1pg_sleep\0\0\0\0\0\0\0\0\0\10\346\0\4\377\377\377\377\0\0D\0\0\0\n\0\1\0\0\0\0C\0\0\0\rSELECT 1\0Z\0\0\0\5I", 65536) = 65
22:43:32 write(10, "Q\0\0\0\21SELECT 31337\0", 18) = 18
22:43:32 read(10, "T\0\0\0!\0\1?column?\0\0\0\0\0\0\0\0\0\0\27\0\4\377\377\377\377\0\0D\0\0\0\17\0\1\0\0\0\00531337C\0\0\0\rSELECT 1\0Z\0\0\0\5I", 65536) = 70
```

In case it's not obvious, this is the expected output:

```
$ strace -t -s 65535 node test.js 2>&1|grep -E 'pg_sleep|31337'
[...]
22:43:22 write(10, "Q\0\0\0\30SELECT pg_sleep(10)\0", 25) = 25
22:43:22 write(10, "Q\0\0\0\21SELECT 31337\0", 18) = 18
<-- 10 seconds gap AFTER sending both queries
22:43:32 read(10, "T\0\0\0!\0\1pg_sleep\0\0\0\0\0\0\0\0\0\10\346\0\4\377\377\377\377\0\0D\0\0\0\n\0\1\0\0\0\0C\0\0\0\rSELECT 1\0Z\0\0\0\5I", 65536) = 65
22:43:32 read(10, "T\0\0\0!\0\1?column?\0\0\0\0\0\0\0\0\0\0\27\0\4\377\377\377\377\0\0D\0\0\0\17\0\1\0\0\0\00531337C\0\0\0\rSELECT 1\0Z\0\0\0\5I", 65536) = 70
```

**Comment by abenhamdine** [comment]
Hi Brianc, I opened https://github.com/brianc/node-postgres/issues/2646
