### ISSUE TITLE
Connecting to Amazon Redshift

### ISSUE THREAD

**Issue by awm33** [brianc/node-postgres#686]
I'm trying to connect to Amazon Redshift using Node.js from an EC2 instance. I can connect using psql

`psql -h {host} -U {username} -d {database} -p 5439`

But not this library, it times out.

```
var client = new pg.Client({
            user: {username},
            database: {database},
            password: {password},
            port: 5432,
            host: {host}
});
```

I also tried a connection string

`postgres://{username}:{password}@{host}:5432/{database}`

**Comment by doron2402** [comment]
happens to the best :)

**Comment by RakeshKulangara** [comment]
@awm33 Were you able to get this working? I'm seeing the following error.

https://github.com/brianc/node-postgres/issues/1212

**Comment by awm33** [comment]
@RakeshKulangara I messed up the port in the connection info. Make sure you are using the correct port. Redshift defaults to 5439, which is different than postgres.
