### ISSUE TITLE
New error fields in PostgreSQL v9.3

### ISSUE THREAD

**Issue by moll** [brianc/node-postgres#701]
According to http://www.postgresql.org/message-id/E1U0JMj-0001zn-Sv@gemulon.postgresql.org PostgreSQL v9.3 got a few new error fields in January 2013. I don't believe these are represented in the error node-pg returns: https://github.com/brianc/node-postgres/blob/master/lib/connection.js#L523.

Particularly the table, table column, data type, or constraint fields.
The full list: http://www.postgresql.org/docs/9.3/static/protocol-error-fields.html

**Comment by charmander** [comment]
Fixed in #712.
