### ISSUE TITLE
Cannot find module '/node_modules/pg/lib/native/../../build/default/binding'

### ISSUE THREAD

**Issue by ghost** [brianc/node-postgres#702]
I found this in my log after clicking on a button (generated an error). Re-clicking on the button, the action worked correctly. It seems to appear when I call sequelize's reload. But just once. My app works fine otherwise. I see newrelic is mentionned there so I'm not sure if it's a node-postgres issue or no.

```
api_1 | 2014-12-08 08:45:11 - error: Error: Cannot find module '/app/node_modules/pg/lib/native/../../build/default/binding'
api_1 |     at Function.Module._resolveFilename (module.js:338:15)
api_1 |     at Function.Module._load (module.js:280:25)
api_1 |     at Function.cls_wrapMethod [as _load] (/app/node_modules/newrelic/lib/shimmer.js:208:38)
api_1 |     at Module.require (module.js:364:17)
api_1 |     at require (module.js:380:17)
api_1 |     at Object.<anonymous> (/app/node_modules/pg/lib/native/index.js:17:13)
api_1 |     at Module._compile (module.js:456:26)
api_1 |     at Object.Module._extensions..js (module.js:474:10)
api_1 |     at Module.load (module.js:356:32)
api_1 |     at Function.Module._load (module.js:312:12)
```

**Comment by Luchooo** [comment]
Hi, you use postgres 9.3?, this solution is first unistall pg with `npm uninstall pg`, after if use postgres 9.3 install the next dependency `sudo apt-get install libpq-dev` and now install pg with `npm install pg`, This solved my problem.
