### ISSUE TITLE
Have a way of initializing new connections in pool

### ISSUE THREAD

**Issue by monsanto** [brianc/node-postgres#703]
Often I need to initialize connections before use (setting session variables, creating temporary views, etc). I don't see any way to do this with pooling; pool.connect() does not appear to have a way of communicating whether the connection returned is new or reused.

node-mysql solves this problem by having a 'connection' event on pools: https://github.com/felixge/node-mysql#connection

**Comment by ss108** [comment]
@brianc I'm a fairly green programmer who's interested in taking a shot at it if you wanna walk me through it (well I'm gonna take a shot at it anyways lol).

**Comment by brianc** [comment]
I would love to help you take a shot. Want to gchat me? I can walk you
through

**Comment by ss108** [comment]
Awesome thanks! just sent you chat invite

**Comment by ss108** [comment]
@brianc Submitted a PR, please let me know if I'm on the right track. If I am, I will run the tests. (And put something in or remove the empty `if` statement when the pool acquires a connection)

**Comment by brianc** [comment]
This should become a lot easier in `pg@7.0` - I'm upgrading the pool & will expose it's factory methods in a way that makes builder customization easier.
