### ISSUE TITLE
Issues encoding output for transit-js

### ISSUE THREAD

**Issue by blissdev** [brianc/node-postgres#707]
I'm attempting to encode the output of a `node-postgres` query into [cognitect/transit-js](https://github.com/cognitect/transit-js) formatted transit+json. It seems to be running into an issue parsing the row. From inspection, the array/object-per-row appears to be plain, but I'm guessing that's not the case. Could you point me in the direction of what is custom, so that I can write a custom writer for node-postgres rows? This just a super-basic query where I'm using `result.rows`.

Thanks!

**Comment by ostronom** [comment]
Had the same issue. Most dumb and straightforward way is to:

```javascript
transitWriter.write(JSON.parse(JSON.stringify(result.rows)));
```

But, you can use some cloning function, like:

```javascript
var clone = function(r) {
  var res = {};
  Object.keys(r).forEach(function(k){ res[k] = r[k] });
  return res;
}

transitWriter.write(result.rows.map(clone));
```

**Comment by blissdev** [comment]
@ostronom I did bring this up in the transit discussion list, but I haven't had a chance to test the changes made. Maybe it will help you.

https://groups.google.com/forum/#!topic/transit-format/zGXBjF82Llg

**Comment by brianc** [comment]
Havent heard anthing on this
