### ISSUE TITLE
Possible error in rowCount returned by native bindings

### ISSUE THREAD

**Issue by clariture** [brianc/node-postgres#708]
When performing an insert, update, or delete using the pure JavaScript implementation, the rowCount attribute of the query result is a number:

```javascript
JSON.stringify(result);
// {"command":"INSERT","rowCount":1,...}
```

I switched to the native bindings - with no other changes to my code - and the rowCount attribute is now a string:

```javascript
JSON.stringify(result);
// {"command":"INSERT","rowCount":"1",...}
```

You asked that we report any required code changes other than modifying the `require` statement, so I'm passing this along.  Thanks so much!

I'm using:
PostgreSQL 9.3.5
Ubuntu 12.04
node-postgres 4.1.1
node-pg-native 1.7.1

**Comment by MayhemYDG** [comment]
@brianc 
I'm reproducing this too, rowCount is a string with `pg.native`.

**Comment by brianc** [comment]
Ah sorry about that.  Good catch. Those kind of things can jack stuff up in
weird minor ways.  Interested in submitting a PR for it? Just a quick test
to assert the rowCount is a number, and then a one line `parseInt`
addition. :)

**Comment by MayhemYDG** [comment]
I'll give it a try.
