### ISSUE TITLE
events.js: 72 throw er; // Unhandled error

### ISSUE THREAD

**Issue by Protosac** [brianc/node-postgres#710]
I'm having the same error as the one reported in #465 but the proposed solutions aren't working. It happened while configuring passport-github authentication. I tried the code at pull request #468 but the same error occurs. In the browser console I'm getting a `ERR CONNECTION REFUSED` error, but I can't tell where this is coming from.

![screenshot from 2015-01-01 02 06 50](https://cloud.githubusercontent.com/assets/6880594/5591984/e9fafa44-915a-11e4-85b5-b3cd6c2996f1.png)

**Comment by jbmyid** [comment]
I am having same issue. On heroku its coming regularly after some time. Have to restart app. Please suggest fix.

**Comment by brianc** [comment]
Can you submit a small self contained unit of code to reproduce the problem
as well as your version of pg, node, and what operating system you're
seeing the issue on?
