### ISSUE TITLE
pg takes long time to exit node application

### ISSUE THREAD

**Issue by baodang** [brianc/node-postgres#713]
I tried to run the following example from README. It shows 1 immediately, but then takes a while (more than 10 seconds) to exit. Is it normal?

```javascript
var pg = require('pg');
var conString = "postgres://username:password@localhost/database";

pg.connect(conString, function(err, client, done) {
  if(err) {
    return console.error('error fetching client from pool', err);
  }
  client.query('SELECT $1::int AS number', ['1'], function(err, result) {
    //call `done()` to release the client back to the pool
    done();

    if(err) {
      return console.error('error running query', err);
    }
    console.log(result.rows[0].number);
    //output: 1
  });
});
```

**Comment by brianc** [comment]
Yah it's normal. You initialized a connection pool when you called `pg.connect` - the pool takes 30 seconds by default to destroy an idle client.  If you want the process to quit right away call `pg.end()` when you're finished with everything. This will tell the pool to shutdown all clients immediately.  Hope this helps!

**Comment by baodang** [comment]
Thanks for your reply. I think pg.end() should be documented in README.
