### ISSUE TITLE
Can't get standalone client to connect

### ISSUE THREAD

**Issue by maximski** [brianc/node-postgres#715]
I can't get a client connect to my pg database (like described here: https://github.com/brianc/node-postgres/wiki/Client#tcp-example). The following is the complete code of my testfile: 

```javascript
pg = require('pg');
global.config = require("./config");
var client = new pg.Client(conString);

var client = new pg.Client({
    user: config.pg_user,
    password: config.pg_pass,
    database: config.pg_db,
    host: config.pg_host,
});

client.connect(function(err) {
    if(err) {
        console.error('could not connect to postgres', err);
      }
});
```

The error message is plainly "[Error: Connection terminated]". Meanwhile it works fine if I just use pg.connect() to create a connected client with the same config. I am working on localhost. Am I missing something?

**Comment by brianc** [comment]
Sorry for the delay here in responding - where you able to figure this out at all? Could you console.log(JSON.stringify(err)) ? the error has additional fields if it comes from postgres.  Also, could you post a sample code where `pg.connect()` is working? It's slightly hard to tell what's going on in that code sample

**Comment by denaje** [comment]
Hello, I'm getting this issue quite a bit. I have an application that runs queries in very quick succession, and many (about half?) are returning the error `[Error: Connection terminated]`. When I output `JSON.stringify(err)`, I simply get an empty object `{}`. If helpful, the code I'm using is:

```coffeescript
@query: (query, params, next) =>
        pg.connect @connection, (err, client, done) =>
            if err 
                return console.error('error fetching client from pool', err)

            client.query query, params, (err, result) =>
                done()

                next result['rows'] if next and result

                if err 
                    console.error('error running query:', query, params)
                    console.log err 
                    console.log JSON.stringify(err)
                    return null

                client.end()
```

**Comment by brianc** [comment]
Hi @denaje - the final line of your example `client.end()` is ending & disconnecting the client though you've already returned it to the pool. Do __not__ call `client.end()` on a pooled client.

**Comment by denaje** [comment]
Ah, thanks for that. It works much better now.

I wonder why, then, you include `client.end();` in the example code under the "Client Pooling" section on the readme. Is there ever a case for calling `client.end()`?

**Comment by maximski** [comment]
Sorry for my delay, too, just seen it here now. I basically "fixed" the issue by using knex.js and bookshelf.js instead of my own queries. Knex connected seamlessly.

**Comment by wkentdag** [comment]
+1 for @denaje 's comment - I was also confused by the [client pooling docs](https://github.com/brianc/node-postgres/wiki/pg#method-connect) and mysterious empty `error` object. 

@brianc IMO your explanation of `done()` vs `client.end` in the above comment is much clearer than it is in the `pg.connect` docs - would you consider a pull request?

**Comment by brianc** [comment]
Definitely always down with pull requests

On Thu, Jul 23, 2015 at 4:14 PM, will kent-daggett <notifications@github.com
