### ISSUE TITLE
Catching RAISE WARNING

### ISSUE THREAD

**Issue by paulxtiseo** [brianc/node-postgres#716]
So, if I RAISE a WARNING in a function, can I catch it in my Node code? I don't see anything in the docs expect handling errors.

**Comment by mblakele** [comment]
Does adding a `client.on("notice", fn)` handler work? See https://github.com/brianc/node-postgres/wiki/Client#notice--object-notice for an example.

**Comment by Michael77** [comment]
This doesn't seem to catch warnings that pertain to transactions such as:
"WARNING:  there is already a transaction in progress" or
"WARNING:  there is no transaction in progress"
Is there any way to capture those messages?

**Comment by brianc** [comment]
`client.on('notice')` should capture those. If you're using native bindings they'res an outstanding feature request to add it - I don't have time to add it myself but would happily review a PR to node-libpq for the feature!
