### ISSUE TITLE
Add ability to log executed queries, and output from postgres when executing those queries

### ISSUE THREAD

**Issue by oveddan** [brianc/node-postgres#721]
When executing queries, it would be great if we could see the queries that were executed, or the results of executing those queries.  If this is possible now, there should be documentation on how to do this.

**Comment by sehrope** [comment]
That isn't part of the core driver. Features like this would be part of modules that sit atop of node-postgres.

The [pg-db](/sehrope/node-pg-db) module (written by me) allows you to register event listeners for various actions (execution, commit, rollback, etc). More info is here: https://github.com/sehrope/node-pg-db#events-api

**Comment by joskuijpers** [comment]
You can also watch the log on the PostgreSQL server.

@brianc this can be closed, for the reason stated by sehrope
