### ISSUE TITLE
Mac Brew PostgreSQL 9.4.1

### ISSUE THREAD

**Issue by andreas4all** [brianc/node-postgres#723]
After today update of PostgreSQL 9.4.1 ( from 9.4.0) stop working PG module (installed 4.2.0)

```
>> events.js:72
>> throw er; // Unhandled 'error' event
>> ^
>> error: could not access file "$libdir/plpgsql": No such file or directory
>>     at Connection.parseE (/xx/node_modules/pg/lib/connection.js:534:11)
>>     at Connection.parseMessage (/xx/node_modules/pg/lib/connection.js:361:17)
>>     at Socket.<anonymous> (/xx/node_modules/pg/lib/connection.js:105:22)
>>     at Socket.emit (events.js:95:17)
>>     at Socket.<anonymous> (_stream_readable.js:765:14)
>>     at Socket.emit (events.js:92:17)
>>     at emitReadable_ (_stream_readable.js:427:10)
>>     at emitReadable (_stream_readable.js:423:5)
>>     at readableAddChunk (_stream_readable.js:166:9)
>>     at Socket.Readable.push (_stream_readable.js:128:10)
```

```bash
$ pg_config --libdir
/usr/local/Cellar/postgresql-9.4/9.4.1/lib
```

hotfix:
``` bash
$ cd /usr/local/Cellar/postgresql-9.4/9.4.1/lib
$ ln -s plpgsql.so plpgsql   
```

**Comment by chbrown** [comment]
I'm pretty sure this has nothing to do with `node-postgres`, but I just ran into the same problem after upgrading to postgresql 9.4.5 (via `brew`) on OS X El Capitan, which raised the `could not access file "$libdir/plpgsql"` error when trying to call a `CREATE FUNCTION ... LANGUAGE plpgsql ...` SQL command in a `psql` REPL.

The hotfix that @andreas4all proposed solved the issue for me, so thanks for that :), but I'd suggest closing this issue and creating a new one in the [homebrew](https://github.com/Homebrew/homebrew/issues) repo if it's a problem for other users.
