### ISSUE TITLE
Connection Pooling Doesn't work in V4.2.0

### ISSUE THREAD

**Issue by philberg** [brianc/node-postgres#732]
Using the example from the [README](https://github.com/brianc/node-postgres#client-pooling) exactly as is (or even without the execution of the query).

`done` is undefined (not passed through the callback).

Using v4.1.1 works correctly

**Comment by brianc** [comment]
Are you still able to reproduce this? Are you using the native bindings? I am pretty sure nothing changed w/ the connection pooling from v4.1.1 to v4.2.0.  Can you log all the arguments passed to the callback when `done` is undefined? Also, can you include an `npm ls` from the directory where you have `pg` installed?

**Comment by philberg** [comment]
I am no longer able to reproduce this for some reason, so I'll close this
