### ISSUE TITLE
Array of byteas returning string instead of buffers

### ISSUE THREAD

**Issue by imathews** [brianc/node-postgres#738]
I ran into this issue over at sequelize/sequelize#3135, where I want to store an array of binary data but am getting returned a string instead; it looks like it's an issue with the `pg` module and not `sequelize`. Not sure if this behavior is as intended, though I would imagine this defeats the performance/memory improvement in storing binary data. 

There's a more detailed description over in the original issue that I won't reprint here, though a SELECT query returns : 

```
{ command: 'SELECT',
  rowCount: 1,
  oid: NaN,
  rows: 
   [ { id: 6,
       serieArrays: '{"\\\\x00000000"}',
       timepointArrays: '{"\\\\x00000000"}' } ],
.....
```

serieArrays and timepointArrays are both of arrays of byteas (in this case, arrays of dimension 1, holding a zero), though I was having the same issue with more interesting/multi-dimensional data.

**Comment by Hoverbear** [comment]
Yup, just ran into this too.

**Comment by yanickrochon** [comment]
I'm not sure if this is related, but I also have a similar problem. A view takes a `bytea` column type and properly convert it into a `text` value. But once in Node.js, the value is totally different (as if it was hex-encoded).

![pgAdmin III Query](https://cloud.githubusercontent.com/assets/78461/7724348/e7951a9c-febe-11e4-8058-179389146fbf.png)
![JSON output from Node.js](https://cloud.githubusercontent.com/assets/78461/7724394/33c33db8-febf-11e4-92d3-fa0ed8287b5f.png)

**Comment by brianc** [comment]
This is an issue with `node-pg-types` which IIRC has been fixed a while ago.
