### ISSUE TITLE
help with delete

### ISSUE THREAD

**Issue by thegreatmichael** [brianc/node-postgres#741]
hi, sorry to post this here, but there's the possiblity it's a bug. I do fear it's more likely a problem with my understanding.

I run a delete, and I think I get a success message, but the record remains...

http://stackoverflow.com/q/28821899/1449799

**Comment by brianc** [comment]
No worries about posting it here. I don't really check up on stackoverflow: this is definitely the best place to get in touch.

I'm 99% sure there's something going on in the way you're using the library or the way the query is being constructed, but I'm not really able to see anything immediately that stands out as incorrect in your stackoverflow post.

I'd recommend adding more logging. In your query function add the query text and query parameters there. Also, when the query is complete, lot the entire result object. It will contain a count of number of rows deleted.  If its not calling back with errors and its not deleting anything it's likely something about the parameters you're passing are not what you think...I think? :dizzy_face:

**Comment by brianc** [comment]
Did you get this figured out?
