### ISSUE TITLE
high data frequency

### ISSUE THREAD

**Issue by aberenyi** [brianc/node-postgres#742]
Hi,

I am aware that this is not really an issue, however, I am keen to get some input from you.

Basically I have a data feed that gives 5-10 packages every second. After parsing the content I compose a single INSERT query for every single package.

I've tried to actually insert those into the database with the async pooled approach, however, after a few minutes I got the good old "too many clients already".

Then I've tried with a 'persistent' approach (i.e. create a client and open the connection outside the loop and run the query using the previously initiated client and close the connection only if the data connection drys out). It was okay for 5 mins, but after that the queries were not executed - interestingly no errors were thrown. 

What technique would you suggest? Should I create a buffer and store the queries in it for like 5 mins and execute once the timer expires?

Thanks in advance.

Cheers

**Comment by brianc** [comment]
have you tried using the built in connection pool? 5 INSERT queries a second is far below what I've pushed through this library in production systems before.  If you're getting "too many clients already" then I'm guessing you're not using pooling?

**Comment by aberenyi** [comment]
I've definitely used pooling,  but if you suggest that is way below the threshold I'll give it a try again.

**Comment by brianc** [comment]
how did things work out for you?

**Comment by aberenyi** [comment]
Sorry for not getting back to you earlier. It turned out that there was a bug in my wrapper module that encapsulates node-postgres. Fixed it and now it works like a charm. Feel free to close - thanks.

**Comment by aberenyi** [comment]
Quick update on this.

Using my updated wrapper function I've noticed, that I got a lot of ```error running query [Error: Connection terminated]``` in the logs (see below), however, ```JSON.stringify(err)``` always returns an empty object (```{}```). 

```
Mar 18 09:55:38 TCPServers[10413]: {}
Mar 18 09:55:38 TCPServers[10413]: error running query [Error: Connection terminated]
Mar 18 09:55:38 TCPServers[10413]: {}
Mar 18 09:55:38 TCPServers[10413]: error running query [Error: Connection terminated]
Mar 18 09:55:38 TCPServers[10413]: {}
Mar 18 09:55:38 TCPServers[10413]: error running query [Error: Connection terminated]
```

The wrapper function
```js
/**
 * PostgreSQL helper functions
 * @mixin
 * @requires pg
 */
var pg = require('pg').native;


/**
 * Run a query on a DB.
 * @param connString
 * @param query
 * @param callback
 */
exports.query = function(connString, query, callback)
{
  pg.connect(connString, function(err, client, done)
  {
    if (err) {return console.error('error fetching client from pool', err);}
    client.query(query, [], function(err, result)
    {
      done();
      
      if (err)
      {
        console.log(JSON.stringify(err));
        return console.error('error running query', err);
      }
      
      if (callback) {callback(result);}
      client.end();
    });
  });
}
```

I've tried both with ```pg``` and ```pg.native```, the result is the same.

Any thoughts - I am kinda lost in here?

**Comment by aberenyi** [comment]
Looks like that the trigger function on the table that I am inserting into was a bit of a bottleneck. After optimising the trigger (the execution time was about 3 s before) the error seems to pop up less frequently. 

Maybe the main issue is caused by some sort of timeout?

**Comment by sehrope** [comment]
@aberenyi: You shouldn't be calling `client.end()` and the end of your function.

Calling `done()` returns the connection to the pool so that it can be reused. Calling `client.end()` closes the underlying connection itself. You're returning a closed connection to the pool which is eventually being reused (since the pool doesn't know it's closed), hence the `Connection terminated` errors.

@brianc: I just noticed that the [connection pooling example](https://github.com/brianc/node-postgres/blob/master/README.md#client-pooling) in the README has the same problem. As a standalone example it makes sense, as otherwise the program would hang with the pool remaining open, but for a new user I guess it's a bit confusing.

**Comment by aberenyi** [comment]
@sehrope thanks for your input on this.

Although what you're saying makes perfect sense, I haven't seen a single `Connection terminated` in the last two weeks. It is possible that the frequency of the incoming data changed, however, I was not notified about such a change.

Anyway, I'll keep this in mind - thanks again.

**Comment by sehrope** [comment]
With a low throughput you might not run into the issue of a closed connection being reacquired. I think the default for the connection pool is to close connections and remove them from the pool after 30 seconds of inactivity. It's possible that alone is preventing you from seeing the error.

If you want to see the error first hand try running the following script. It runs a bunch of queries in parallel, closing the underlying client after the query has returned back.

```coffeescript
async = require 'async'
pg = require 'pg'

doStuff = (cb) ->
  pg.connect process.env.DATABASE_URL, (err, client, done) ->
    if err then return cb(err)
    client.query 'SELECT 1', (err, result) ->
      done()
      if err then return cb(err)
      client.end()
      cb(null)

iter = (i, cb) ->
  doStuff (err) ->
    console.log 'i=%s err=%s', i, err
    cb(err)
async.each [1..10], iter, (err, results) ->
  pg.end()
```

Output will look something like this (note the errors):

```
i=1 err=null
i=2 err=null
i=3 err=null
i=4 err=null
i=5 err=null
i=6 err=null
i=7 err=Error: Connection terminated
i=8 err=Error: Connection terminated
i=9 err=Error: Connection terminated
```

Remove the `client.end()` line and you won't see the errors anymore.

**Comment by aberenyi** [comment]
@sehrope cheers for the test script, I'll definitely give that a go.

@brianc can you please confirm that the idle connections in the pool are closed after 30s?

**Comment by brianc** [comment]
After noticing a handful of issues w/ people calling `client.end()` on a pooled client....Yeah I just realized [this pull request](https://github.com/brianc/node-postgres/pull/729) updated the documentation to __incorrectly__ say to call `client.end()` on a pooled client. This is bad info.  I fixed it today - so sorry about that!

Yeah the pool closes idle connections after 30 seconds.  You can _configure_ that delay by setting [pg.defaults.poolIdleTimeout](https://github.com/brianc/node-postgres/blob/master/lib/defaults.js#L31) to a different integer value.  The value is in seconds.

**Comment by brianc** [comment]
Just to reitterate: if you check a client out from the pool..._never_ call `end` on it.

**Comment by aberenyi** [comment]
After ditching `client.end()` from the wrapper function `Connection terminated` disappeared as it never was there before. Thanks for the pro tip, closing now.

**Comment by brianc** [comment]
:dancer:
