### ISSUE TITLE
require('pg').native doesn't work with query row event

### ISSUE THREAD

**Issue by adayton1** [brianc/node-postgres#743]
If I uncomment the query.on('row'...) section below, node complains that the function addRow does not exist. When I just use require('pg') it works properly.

    var pg = require('pg').native;

	pg.connect(connectionString, function(err, client, done) {
	
		if (err) {
			console.error(err);
		}

		var query = client.query(queryString, params);
		
		query.on('error', function(err) {
			console.error(err);
		});
		
		/*query.on('row', function(row, result) {
			result.addRow(row);
		});*/

		query.on('end', function(result) {
			done();
		});
	});

**Comment by deyhle** [comment]
+1

Tested with node 0.12.2.

Apparently the `result` parameter is no `Result` object. My debugger shows that it is `module.exports` instead.

`JSON.stringify(result)` returns:
```
{"command":"SELECT","rowCount":1,"rows":[{"description":"0.2.1"}],"fields":[{"name":"description","dataTypeID":25}]}
```

**Comment by vaseker** [comment]
+1
node 0.12.4
pg@4.4.0
pg-native@1.8.1

**Comment by traviscrawford** [comment]
Hi all, I just came across this today when switching to `pg-native`. Per this note in the project readme I believe this method should be available, even if its a no-op when using `libpq`:

> node-postgres abstracts over the pg-native module to provide exactly the same interface as the pure JavaScript version. No other code changes are required. If you find yourself having to change code other than the require statement when switching from require('pg') to require('pg').native please report an issue.

```
"pg": "4.4.4",
"pg-native": "1.10.0",
```

**Comment by coagmano** [comment]
+1 
node 4.2.4 

    "pg": "4.4.4",
    "pg-native": "1.10.0"

**Comment by coagmano** [comment]
Made a PR ^^ to fix this
