### ISSUE TITLE
SQL order by is not working

### ISSUE THREAD

**Issue by diegoddox** [brianc/node-postgres#744]
Well I have a sql command and it works well on pgAdmin3 but when
I use the same query the order by don't work here is my sql. Take note that I get a result of rows but not order

"SELECT * FROM table_name ORDER By create_at DESC"

create_at is a timestamp.

**Comment by brianc** [comment]
I can guarantee you `order by` is respected by node-postgres.  Can you provide a self-contained code sample I can run to reproduce the output you are seeing?

**Comment by brianc** [comment]
accidentally hit "close and comment" instead of "comment" - my bad

**Comment by diegoddox** [comment]
This is the function that I'm using.
var pg = require('pg');

pg.connect(config.db, function(err, client, next) {
  client.query('SELECT * FROM tablename ORDER BY create_at DESC', function(err, result) {
      callback(result.rows);
  });
});

**Comment by diegoddox** [comment]
What do you @brianc mean when you say "self-contained code sample"? I hope the sample I had given above is ok,

**Comment by brianc** [comment]
The code above doesnt run on my computer. I dont have the right tables. I
need something i can execute here to reproduce the ossue

**Comment by diegoddox** [comment]
Thanks @brianc for your quick response what about this one.

var express = require('express');
var pg      = require('pg');

var config = {
  user: process.env.RDS_USERNAME || 'root',
  password: process.env.RDS_PASSWORD || 'root',
  host: process.env.RDS_HOSTNAME || 'locahost',
  database: 'dbname'
};
var app = express();

pg.connect(config, function(err, client, next) {
  client.query('CREATE  TABLE  IF NOT EXISTS posts ("title" VARCHAR  DEFAULT NULL ,"id" UUID NOT NULL,"create_at" TIMESTAMP NOT NULL,PRIMARY KEY ( "id" ))');
});
app.get('/', function(req, res) {
  pg.connect(config, function(err, client, next) {
    // No mater what I use it always get the same order!
    client.query('SELECT * FROM posts ORDER BY create_at DESC', function(err, result) {
      res.json(result.rows);
    });
    next();
  });
});

var server = app.listen(3000, function() {
  var host = server.address().address;
  var port = server.address().port;
  console.log('Example app listening at http://%s:%s', host, port);
});

**Comment by brianc** [comment]
That's good except your temp table doesn't have any data in it, so I get no
rows out....hard to tell the order there ;)

**Comment by diegoddox** [comment]
I don't know what's happen but I have edit the post right after I create and I have added a router that creates new rows every time you visited the address /create

app.get('/create', function() {
  pg.connect(config, function(err, client, next) {
    for(var ii = 0; ii < 5; ii++){
       var title = 'title_'+ ii;
       client.query('INSERT INTO posts (title) VALUES ($1)', [title], function(err, result) {
       next();
     });
   });
  }
  res.send('done');
});

**Comment by brianc** [comment]
Thanks - could you put together a self-contained code sample that creates a temp table, inserts a few records with dates, and selects them in an order. Then show in the executable code sample how they're coming out with the wrong order? Your sample you gave doesn't really have an expected output or a _known set of data_ being put into the table.

Something like...

https://gist.github.com/brianc/35e36fb4db6b645ed65f

**Comment by diegoddox** [comment]
Thanks again for your great response. Well I don't know why I have not change the db code and it works now maybe it was some issue with aws?
