### ISSUE TITLE
postgres composite type

### ISSUE THREAD

**Issue by yaacovk** [brianc/node-postgres#755]
Say I have the following postgreSQL composite type:

CREATE TYPE myType AS(
    id  bigint,
    name  text,
);
and a stored procedure that excepts that type:

CREATE FUNCTION myFunction(mt myType){
   //do some stuff
}
I would like to call this procedure from Node-js using node-postgres module.

var pg = require('pg');
var connectionString = "connection string";
pg.connect(connectionString, function(err, client, done) {
   client.query('SELECT myFunction($1)', [some value],   
        function(err, result) {
        // do stuff
        done();
    });
});
Is there a way to pass a type from Node to a Postgres stored procedure? 
does node-postgres support this kind of thing?

**Comment by yaacovk** [comment]
Found the following  solution:

var pg = require('pg');
var connectionString = "connection string";

var myType = [
  12345,
  'you'
];
pg.connect(connectionString, function(err, client, done) {
   client.query('SELECT myFunction($1::myType)', 
     ['(' + myType.toString() + ')' ],   
     function(err, result) {
      // do stuff
    done();
});

**Comment by pankleks** [comment]
Is there another way?

Above solution works, but it's very inconvenient because you need to convert all values to string, so essentially you skip all `pg-node` build in conversions.

I think better solution would be to pass array of composite type elements and allow `pg-node` to convert them using standard conversion.

Any chance for this?

**Comment by pankleks** [comment]
Also I think there is a bug when function return composite type.
`SELECT db_function(...`
throws exception that it cannot convert to integer or sth. like that.

Thanks
