### ISSUE TITLE
Cannot read property 'getTypeParser' of undefined

### ISSUE THREAD

**Issue by Tarang** [brianc/node-postgres#759]
Not too sure what is causing it. I'm querying a redshift database, thats about the only difference.

With the native parser `pg-native` its this instead:

TypeError: Cannot read property 'push' of undefined /pg/lib/native/index.js:129:19)

**Comment by brianc** [comment]
Do you have more details? What are the data types for the table you're querying? Can you provide example code & a test instance of redshift for me to run the code against?

**Comment by KeKs0r** [comment]
Having the same issue. @Tarang How did you solve the problem?

**Comment by monteslu** [comment]
if you call `query` outside of its client context you can reproduce the problem.

`client.query.apply(this, args);`
as opposed to:
`client.query.apply(client, args);`

**Comment by brianc** [comment]
Need code to reproduce this. @monteslu that code is definitly invalid. You cant change the scope of an instance method and expect it to still work in most cases. Its bound to the prototype exactly so it can reference the properties on the prototype. ☺️
