### ISSUE TITLE
difference between pg and pg.native

### ISSUE THREAD

**Issue by trailsandtribulations** [brianc/node-postgres#762]
pg client has readyForQuery, pg.native does not

pg.native has connected, pg does not

programs dependent on either of these cannot be ported between `requrie('pg')` and `require('pg').native`

**Comment by joskuijpers** [comment]
Is this still the case in the latest version?

**Comment by brianc** [comment]
You shouldn't depend on the `readyForQuery` event or the `pg.native.connected` flag.  Neither are documented as part of the public API and can change (though they likely wont).
