### ISSUE TITLE
Inserting into JSON column

### ISSUE THREAD

**Issue by pushkeryadav** [brianc/node-postgres#767]
I have been using the node pg module to access postgres from Node.
I have a table which has a column of type JSON.'
In order to insert into this I am using the JSON.stringify function to convert the object to String.
JSON.stringify adds double quotes around the keys without any escape and this is standard behaviour.
When I execute the query directly on pgadmin with single quotes wrapping this stringified JSON it inserts fine. But as expected it fails when I use double quotes to wrap the string.

I am unable to insert into the DB as I get an error Insert failed when I use node-pg module to insert from node server.
How do we populate the JSON column of Postgres from a Node JSON object?
Please Help.

**Comment by brianc** [comment]
Can you create a self-contained example I can run to demonstrate the issue?  Have your sample use `CREATE TEMP TABLE` with whatever table schema you are using and then have it run an example `INSERT` statement that fails.  Its hard to diagnose more without specifics.

**Comment by pushkeryadav** [comment]
Sorry, it was due to some silly mistake. Thanks for help.

**Comment by brianc** [comment]
No problemo!
