### ISSUE TITLE
Using more complex query doesn't work

### ISSUE THREAD

**Issue by BorisPazin** [brianc/node-postgres#768]
Hi,

I experience an issue with certain queries. For example, simple query like this works correctly:

select brand, program, region from orders;

But, query like this is not working:

select brand, program, region, sum(subtotal) as sales, min(orderdatetimestore) as firstOrder from orders group by brand, program, region

Also, if I place complex query in View named test and then try:

Select * from test. 

Also not working.

Any idea how to resolve this?

Thanks!

**Comment by BorisPazin** [comment]
What could maybe be the reason, I noticed that queries which don't work take long time to execute, so maybe there is some timeout parameter?

Thanks

**Comment by BorisPazin** [comment]
Huh, not sure but I think I narrowed the problem. It is happening when there are more than about 100 000 rows affected by query. 

So, if I try something like,

select top 100 brand from orders

That is working fine.

But,

select top 150 000 brand from orders returns an error.

So, I guess that is some parameter regarding to PostgreSql? Please let me know if it can it be set by node-postgres?

Thanks

**Comment by brianc** [comment]
What error are you getting back?

**Comment by BorisPazin** [comment]
Hi Brian,

I think I understand what is happening, and looks like it is not related stritcly to node-postgres, but it could be Node.js topic.

This SQL query takes about 5 minutes to execute. On front end, I got nothing. Rows object of result is undefined (empty) without error returned. 

I placed break point inside of client.query() function and after about 5 minutes code execution stopped on marked place. :)

So, query actually does work, but Node.js execution goes further before query is completed. Thus, it sends empty result to view.

Please let me know if you have some recommended way how to execute long (slow) queries?

Thanks,
Boris Pazin

**Comment by brianc** [comment]
Sure, could you provide a little code example?

**Comment by BorisPazin** [comment]
Hi Brian,

Here is the code. It works well for fast queries, but if query takes long time it returns empty result:

var express = require('express');
var config = require('../Web.config.js').config;
var router = express.Router();

// Make PostgreSQL connection
var pg = require('pg');
var sqlQuery = "";
var title;
var postgreData;
var errMessage;

var client = new pg.Client(config.connStr.postgreSql);
client.connect(function (err) {
    if (err) {
        title = err.stack;
    }
    else {
        title = "connected";
        
        sqlQuery = "select top 150000 brand, program, region from orders"
                
        client.query(sqlQuery, function (err, result) {
            if (err) {
                return console.log(err.stack);
            }
            client.end();
            postgreData = result;
        });
    }
});

/* GET PostgreSql result set.
 * For short queries, this works correctly, but
 * for long queries, the part bellow executes before client.query() part 
 * and returns empty result 
 */
router.get('/', function (req, res) {
    res.render('postgre', { title: title, postgreData: postgreData.rows });
});
module.exports = router;


Thanks!

**Comment by brianc** [comment]
small note: I edited your post to provide syntax highlighting

**Comment by brianc** [comment]
Can you provide the route code as well? It looks like you're doing something kinda funky w/ a global variable there...but its hard to tell w/o seeing the entire thing.

Also, if you remove the routing/express stuff all together & execute the query and `console.log` the result to the console when the query finishes do the results have data?

**Comment by BorisPazin** [comment]
How do you mean route code? This is the code from route routes/postgre.js 

Last part is rendering view and sending result in form of array.

"Also, if you remove the routing/express stuff all together & execute the query and console.log the result to the console when the query finishes do the results have data?"

Yes, the data are there and it works perfectly. The problem is that it takes some time and then last part (res.render...) is executed before client.query() is finished.

**Comment by brianc** [comment]
yeah i see the problem - it's due to the way you structured your route. I'll provide a corrected version

**Comment by brianc** [comment]
```js
var express = require('express');
var config = require('../Web.config.js').config;
var router = express.Router();

// Make PostgreSQL connection
var pg = require('pg');
var sqlQuery = "";
var title;
var postgreData;
var errMessage;



/* GET PostgreSql result set.
 * For short queries, this works correctly, but
 * for long queries, the part bellow executes before client.query() part 
 * and returns empty result 
 */
router.get('/', function (req, res, next) {
   var client = new pg.Client(config.connStr.postgreSql);
pg.connect(function (err, client, done) {
    if (err) {
        return next(err);
    }

        title = "connected";
        
        sqlQuery = "select top 150000 brand, program, region from orders"
                
        client.query(sqlQuery, function (err, result) {
            if (err) {
                done();
                return next(err);
            }

    res.render('postgre', { title: title, postgreData: result.rows });
        });
});
    
});
module.exports = router;
``

That is the proper way to query postgres. You do the query __in the route handler__ and return the result when the query is finished.  I went ahead and used _client pooling_ as well - you don't want to open a client for each connection.

**Comment by brianc** [comment]
Sorry the formatting is jacked - github's code editor isn't the greatest in a PR comment.  I think you should be able to get the gist though.

**Comment by BorisPazin** [comment]
Hi Brian,

This approach works, thanks!

For some reason, my PostgreSql server refuses connection if using pool, so I had to use client.connect(). 

Thanks again!
Boris
