### ISSUE TITLE
Question: What is the best way to have node-pg wait in a queue?

### ISSUE THREAD

**Issue by JemiloII** [brianc/node-postgres#769]
So I'm using node-pg to run queries, however the database I'm using will have a queue. It seems that when it becomes my turn, node-pg doesn't know, and I get passed on, leaving the app to hang.

**Comment by brianc** [comment]
I'm not sure what you mean by the database having a queue. Are you using
some 3rd party queuing technology between your app and postgres?

**Comment by JemiloII** [comment]
Yeah, it's a greenplum db that uses postgres for the driver. Essentially, there is a max concurrent queue limit. Everyone else just has to wait.

**Comment by brianc** [comment]
If greenplumb isn't using the standard postgres protocol (which I'm
guessing its not because it has to signal a 'wait' somehow) then its not
gonna work with node-postgres unfortunately.  Custom protocol signaling is
not supported.  Do you know the internals?

**Comment by JemiloII** [comment]
I just know that it uses postgresql 8.2, the node-pg works fine as long as there isn't many users. What internal information do you need, and I'll try and get them.

**Comment by brianc** [comment]
Unfortunately, if it's not an actual postgres (or redshift) database then
I'm not really in the business of supporting it.  However, open source is
great cause we can all build on what each of us does, so if you want to dig
in and see if you can figure out where things are going wrong I'm happy to
point you in the right direction.  Firstly you'd probably need to figure
out if it implements the entire postgres protocol and doesn't extend it in
any way. To find that out I'd dig into the docs for the source system or
code if its open source.
