### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by mrft** [brianc/node-postgres#774]
I have a problem where pg keeps going out-of-memory with this parameterized insert query that upserts some json.

example code in icedcoffeecript ( *await* and *defer* do the same as pgclient.query( sql, params, function(...) { } ) but makes it more readable )
<pre>
	sql = "insert into content( json ) select $1 where not exists ( select true from content where json->>'key' = $2 )"

	for f in files2
		err = result = null
		await pg.connect( connectionString, defer( err, pgclient, done ) )
		if ( err )
			return cb( "Error fetching client from pool: #{err}" )

		params = [ f, f.key ]
		await pgclient.query( sql, params, defer( err, result ) )

		done()

		if ( err )
			return console.error( 'error running query', err )
</pre>

If I comment the line 
<pre>await pgclient.query( sql, params, defer( err, result ) )</pre>

(so the connection is made but no query is executed) there is no problem.

As soon as I execute the query, memory usage starts increasing on every run and nodejs finally always crashes.

(pg version 4.3.0)

**Comment by brianc** [comment]
Are you using the native bindings?

Can you write an example in vanilla JavaScript & make sure you run out of
memory there?  Many people have used node-postgres for many years in
production without memory leaks & I have specific tests that I've let run
for hours executing queries on a local postgres in a tight loop with steady
memory usage...my hunch is its something in the implementation or in iced
coffee-script or something.

**Comment by mrft** [comment]
I am reading a file line-by-line and when I have enough characters, I flush a whole lot of them (depends on their size) to the database at once. So I didn't rewrite the whole script, but I did rewrite the function that does the actual saving in plain javascript, like this (using the async library to do the inserts in series).

As you will see I wrote a function doSomething, that allocates a new string, then prints something to the console, which works (mem goes up and down again when the GC kicks in).
As soon as I comment *doSomething* and uncomment *pgclient.query*, it goes out-of-memory after some time.

<pre>
	function storeOnPostgresqlDb( pgclient, files2, cb ) {
		var sql = "insert into content( json ) select $1 where not exists ( select true from content where json->>'key' = $2 )"
		async.eachSeries( files2,
						function( f, acb ) {
							sql = "insert into content( json ) select '" + JSON.stringify(f).replace( /\'/g, "''") + "' where not exists ( select true from content where json->>'key' = '" + f.key + "' )"

							function doSomething( str, pars, dscallback ) {
								setTimeout( function() {
									var str2 = "===" + str
									console.log( str2.slice( 0, 60 ) + " " + (pars ? JSON.stringify( pars ) : "<null>" ) );
									dscallback();
								}, 1);
							};
							doSomething( sql, null, function( err ) {
								acb( err );
							} );


							/*
							pgclient.query( sql, null, function( err, result ) {
								acb( err );
							} )
							*/
						},
						function( err ) {
							gc()
							cb( err )
						}

		);
	}
</pre>

To make sure that it wasn't related to the use of parameters in the query, I made sure that the sql contains the values.

So, I don't see how this could be a coffeescript problem.

**Comment by NitroPye** [comment]
Running into a memory leak as well. Node process will just consume all memory while the query is running and then the OS kills it. It seems that whenever using a sub query happens and as soon as the sub query is commented out it runs fine. Happens with both pg and pg-native

**Comment by brianc** [comment]
Please provide a self contained code snippet demonstrating this issue. This is most likely an issue in your app and not node postgres
