### ISSUE TITLE
Mix native and non-native bindings

### ISSUE THREAD

**Issue by chriskinsman** [brianc/node-postgres#777]
My project uses the native bindings historically.

Now I have a need for pg-query-stream.  The problem is that even though this module does 

var pg = require('pg') 

it behind the scenes gets "upgraded" to native due to other dependencies that load require('pg').native.

Is there any way to get a non-native pg after loading native?

**Comment by brianc** [comment]
Hmm...yeah its kinda weird its upgrading itself to pg-native.  Could you post a bit of a code sample?  likely I'll need to patch `pg-query-stream` to accept an instance of `pg` or something but need to see the code a bit

**Comment by chriskinsman** [comment]
// Running in node 0.10.21
// My lib uses require('pg').native
var myLib = require('myLib');
var pg = require('pg');
var QueryStream = require('pg-query-stream');

function queryStream(query, params, destinationStream, callback) {
    pg.connect(myLib.THIRDPARTYURL, function (err, db, close) {
        if (err) {
            return callback(err);
        }
        else {
            var queryStream = new QueryStream(query, params, {batchSize:1000});
            var stream = db.query(queryStream);
            // When I look at stream here in debugger I see it is "Native"
            stream.on('error', function(err) {
                console.error(err);
            });
            stream.on('end', close);
            // This line fails indicating there is no method pipe on stream
            stream.pipe(destinationStream);
            return callback(null);
        }
    });
}

**Comment by brianc** [comment]
That's odd....https://github.com/brianc/node-postgres/blob/master/lib/index.js#L70

Calling `require('pg')` should return you the non-native object.  Are you possibly leaking a global of `pg` as a native version somewhere else in the app? What if you rename the `pg` variable in this file to like `pgjs` or something?
