### ISSUE TITLE
Invalid result for type money[]

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#781]
Type money[] isn't converted into an array of money values, returning a string instead, like this one: `'{$2.50,$1.99,$200.00}'`

Originally reported: https://github.com/vitaly-t/pg-promise/issues/22

**Comment by vitaly-t** [comment]
After a bit of research, I can say with certainty that the issue is within [pg-types](https://github.com/brianc/node-pg-types), file [textParsers.js](https://github.com/brianc/node-pg-types/blob/master/lib/textParsers.js) where at the bottom it registers nothing for type `money[]`, which is **791**. And since the string in this case contains money symbols, we cannot just reuse something like `parseFloatArray`, it won't work, I've tried. It needs a new parser for the `money[]` type.

**Comment by vitaly-t** [comment]
I have created a PR to fix this: https://github.com/brianc/node-pg-types/pull/27

Please see if the change is good for general use. One thing I'm not quite sure - symbol $, could it be something else on other language platforms? If so, it may need tweaking.

**Comment by vitaly-t** [comment]
@brianc , could you, please, merge the PR, or at least let us know if there is any problem with it? It's been almost 2 weeks since it was submitted.

**Comment by brianc** [comment]
Sorry for missing this - I added some comments to the PR over on `node-pg-types` :smile:
