### ISSUE TITLE
More documentation on pooling

### ISSUE THREAD

**Issue by napalm272** [brianc/node-postgres#782]
Can you elaborate on how pooling works?  Right now I create a new instance like the following in every request:
```
someHttpGetRoute(req, res){
        var pgClient = new pg.Client(conString);
        pgClient.connect(function(err){
            pgClient.query('some query', [...], function(err, result){
                pgClient.end();
                res.send(result);
            });
        });
}
```
I read the documentation more carefully and it seems that this is bad because creating a connection takes some effort and this request is called very often (multiple times every second).
I want to switch to pooling, but I don't know how pooling will work after I exceed the pool size.  Let's say I set the size to 20, but 21 requests happened at the same time, what happens to the last request?  Is it not responded?  Blocked until one connection becomes available? The pool grows automatically to handle this request?  Or is doing new pg.Client(conString); the right way to go?

Thanks in advance

**Comment by brianc** [comment]
Sure thing - first read this:

https://gist.github.com/brianc/f906bacc17409203aee0

The tl;dr - Doing `new pg.Client` in a web request is *almost never* the way to go.  If you have more than a few thousand requests per second and you're not using pooling postgres *will* crash.  The requests will block waiting on the pool to have a free client if the db becomes the bottleneck but that's natural and how web apps traditionally have always worked.

Hope this helps!  Good luck & feel free to ask any more questions via issues. :smile:
