### ISSUE TITLE
prepared statement fails with parameters

### ISSUE THREAD

**Issue by matthewmorgan** [brianc/node-postgres#784]
Any help would be appreciated.  Resorted to concatenating strings, using a function to escape the parameters, and that worked.  But, seems like the below should be working:

Using node 0.12.2, testing on OSX 10.10.3, Postgres 9.4

Error is: 
```javascript
{
    [error: bind message supplies 1 parameters, but prepared statement ""
        requires 0
    ]
    name: 'error',
        length: 130,
        severity: 'ERROR',
        code: '08P01',
        detail: undefined,
        hint: undefined,
        position: undefined,
        internalPosition: undefined,
        internalQuery: undefined,
        where: undefined,
        schema: undefined,
        table: undefined,
        column: undefined,
        dataType: undefined,
        constraint: undefined,
        file: 'postgres.c',
        line: '1497',
        routine: 'exec_bind_message'
}
```
code is:
```javascript
exports.fetchOneForHomePage = function (req, res, callback) {

  var args = [req.params.deptid];
  var rollback = function (client, done) {
    client.query('ROLLBACK', function (err) {
      //if there was a problem rolling back the query
      //something is seriously messed up.  Return the error
      //to the done function to close & remove this client from
      //the pool.  If you leave a client in the pool with an unaborted
      //transaction weird, hard to diagnose problems might happen.
      return done(err);
    }) };

  pg.connect(dbParams, function (err, client, done) {
    if (err) throw err;
    client.query('BEGIN', [], function (err) {
      if (err) return rollback(client, done)
      var queryString = 'CREATE OR REPLACE TEMPORARY VIEW nonregistries as (' +
          'SELECT item_id, sum(qtydue) AS funk FROM solineitem WHERE parent_id not in (' +
          'SELECT id FROM so WHERE delivery=4) GROUP BY item_id)';
      client.query(queryString, [], function (err) {
        if (err) return rollback(client, done)
        var queryString2 = "CREATE OR REPLACE TEMPORARY VIEW AVAIL AS " +
            "(SELECT DISTINCT i.id, i.description, i.vendorname, i.qty-COALESCE(n.funk, 0) AS qty FROM item i LEFT JOIN " +
            "nonregistries n ON n.item_id=i.id WHERE i.dept_id = $1)";
        client.query(queryString2, [req.params.deptid], function (err, result) {
          if (err) {
            console.log(err);
            return rollback(client, done)
          }
          var queryString3 = 'SELECT * FROM AVAIL WHERE qty>4 ORDER BY RANDOM() LIMIT 1';
          client.query(queryString3, [], function (err, result) {
            if (err) return rollback(client, done)
            client.query('COMMIT', [], function (err) {
              done();
              res.send(result.rows);
            })
          })
        })
      })
    })
  });

};
```

**Comment by sehrope** [comment]
You can't use bind variables, i.e. the `$1`, when defining a view. It must be a literal:

    var queryString2 = "CREATE OR REPLACE TEMPORARY VIEW AVAIL AS " +
            "(SELECT DISTINCT i.id, i.description, i.vendorname, i.qty-COALESCE(n.funk, 0) AS qty FROM item i LEFT JOIN " +
            "nonregistries n ON n.item_id=i.id WHERE i.dept_id = $1)";

I don't see any reason to use temp views in your code. You can combine all three statements into a single SELECT statement and simply execute that. That would also eliminate the need for wrapping things in a transaction.

If you are going to be using transactions you should use a wrapper library that handles them for you rather than manually implementing them each time (much less error prone). One such library is [`pg-db`](https://github.com/sehrope/node-pg-db#transactions) (written by me). There's a couple other modules listed on the node-postgres [homepage](https://github.com/brianc/node-postgres#extras) as well.

Unrelated, your `rollback(...)` function doesn't handle the client response. It'll just hang indefinitely.

**Comment by matthewmorgan** [comment]
Thanks for your response.  I will try combining the statements as you suggested.

I'm unclear on the issue with the ```rollback(...)``` function.  I thought that by invoking ```done(err)``` I was 'Returning the error to the done function to close & remove this client from the pool'.   

Ah...you're talking about the ```res``` object, right?  So I should add something like ```res.send(500)``` to the rollback function?  Or is it something else?

**Comment by sehrope** [comment]
Yes something like that. If you're using something like express then you'd usually handle this by calling `next(err)` and having a single error handler for your app. That's out of scope for an issue here though.

**Comment by matthewmorgan** [comment]
Thanks again.  I appreciate the advice.
