### ISSUE TITLE
Functional equivalent to toPostgres

### ISSUE THREAD

**Issue by moll** [brianc/node-postgres#786]
Hey,

The `toPostgres` method is great for classes and objects one can edit, but unsuitable for closed classes one's not supposed to touch. What would the functional equivalent be that doesn't require mucking other classes?

I've so far wrapped `pg/lib/utils`'s `prepareValue`, but I'm worried it's not part of the public API. Also, its array preparing function `arraySring` calls `prepareValue` directly, rather than through the `module.exports` object, bypassing my modifications.

Thanks!

**Comment by brianc** [comment]
What about:

```js

var makeConverter = function(converter) {
  var ConvertWrapper = function(raw) {
   this.raw = raw
  }
  ConvertWrapper.prototype.toPostgres = function( ) {
    return converter(raw)
  }
  return function(item) {
     return new ConvertWrapper(item)
  }
}


//in your code
var opaqueTypeConverter = makeConverter(function(raw) {
  return 1;
})

pg.query('INSERT INTO something', [opaqueTypeConverter(yourOpaqueType)])

```
