### ISSUE TITLE
Default database name

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#788]
What is the point of defaulting the database name to the current process user name?

Source: [defaults.js](https://github.com/brianc/node-postgres/blob/master/lib/defaults.js):

```javascript
//name of database to connect
  database: process.platform === 'win32' ? process.env.USERNAME : process.env.USER,
```

**Comment by sehrope** [comment]
That's how libpq (the main client library for PostgreSQL) defaults the username: http://www.postgresql.org/docs/9.4/static/libpq-connect.html#LIBPQ-CONNECT-USER
