### ISSUE TITLE
event-stream readArray not working after pg.connect

### ISSUE THREAD

**Issue by TheFive** [brianc/node-postgres#789]
Hi, 

i am using event-streams to move data to my pg database. In case of internal data, i use the same mechanism, to put them in, and create streams out of the arrays.

I have several mocha test, where this concepts works, but in a very small environment, it looks like, that the array streams are not working properly INSIDE a pg callback.

i have build a small github project containing the error, to test several node versions with travis-ci, but it looks the same for 0.10,0.11 and 0.12.

In my sample sourcecode i just generate an array, stream that with readArray and count the number of array elements. The same line of code is working outside a pg.connect handler, but not inside.

See the source code:
https://github.com/TheFive/pg-es/blob/master/test.js

**Comment by charmander** [comment]
The example link is dead. If this is still an issue, please add a short example script.
