### ISSUE TITLE
how to get returned result as value to a global parameter

### ISSUE THREAD

**Issue by ghost** [brianc/node-postgres#793]
Hello!

I have some problems getting the results from a postgre DB query into a parameter. 
i'm using node.js, from which i want to get a value from the DB and assign it to a parameter and use it later in some other function.

My code looks like this:
var result2 = '';
var pg = require('pg');
var conString = "pg://user:@localhost:5432/db";
var client = new pg.Client(conString);
client.connect();
var query = client.query('SELECT \* FROM islocked');
query.on("row", function (row, result) {
result.addRow(row);
});
query.on("end", function (result) {
console.log("test: " + JSON.stringify(result.rows));
result2 = result.rows;
});

the problem is that result2 never gets updated with a new value. Why? How can i do that?

Thanks!

**Comment by matthewmorgan** [comment]
Hi,

I took a few minutes to test your code, and it works fine for me, in the sense that result2 does contain the same data as result.rows.

have you tried this:

```javascript
query.on("end", function (result) {
  //console.log("test: " + JSON.stringify(result.rows));
  result2 = result.rows;
  console.log(result2);
});
```

Do you see what you expect to see?  IE, the rows of table islocked?
