### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by myndzi** [brianc/node-postgres#795]
I was looking into this issue over at knex: https://github.com/tgriesser/knex/issues/849

The stack dump shows an unhandled error event being emitted and not caught as a result of the connection closing during an active query.

I thought, didn't we fix this? (Past versions of knex had missed binding the error event on the client when creating it); Yes, we had. Closer examination shows that for an active query, the error event is emitted on the *query* object:

https://github.com/brianc/node-postgres/blob/master/lib/client.js#L185
https://github.com/brianc/node-postgres/blob/master/lib/query.js#L99

...but I can't see any way I'm supposed to be able to access this object to bind an event. Nor can I see anywhere that node-postgres itself binds an 'error' event here to handle it itself.

As far as I can tell, this is just an unavoidable crash. Am I missing something?

**Comment by brianc** [comment]
Hey Kris -

If you supply a callback to a query when you execute it the query will pass
the error to the callback __and will not emit an error event__. If you dont
supply a callback then you're responsible for handling the possibilty of
the query erroring out and emitting an error.

Every call to client.query returns an instance of a query. You can
subscribe to the error event there if you want.

var query = client.query('select now()')
query.on('error', ...)

In practice i supply the callback 99.9% of the time so having to do this is
kinda rare

Does this help?

**Comment by myndzi** [comment]
Yes it does, thanks. I was having trouble running down the exact details here from the code :)

**Comment by brianc** [comment]
Glad it helped! :clap:
