### ISSUE TITLE
undefined bind vars result in: caught unhandled error error: syntax error at or near "$1"

### ISSUE THREAD

**Issue by devTristan** [brianc/node-postgres#797]
```javascript```
client.query('SELECT * FROM stuff WHERE id=$1', [4]);
```
Expected behavior: `SELECT * FROM stuff WHERE id=4`
Actual behavior: `SELECT * FROM stuff WHERE id=4`
:)

```javascript```
client.query('SELECT * FROM stuff WHERE id=$1', []);
```
Expected behavior: exception thrown
Actual behavior: exception thrown
:)

```javascript```
client.query('SELECT * FROM stuff WHERE id=$1', [undefined]);
```
Expected behavior: exception thrown, OR `SELECT * FROM stuff WHERE id=null`
Actual behavior: `SELECT * FROM stuff WHERE id=$1`
:(

I don't know if there's any kind of specification for how bind vars should be treated in different situations. I know the practice has been around for a long time, so I feel like there might be.

If you think it's a good idea, I can send a pull request that results in errors being thrown when you try to use `undefined` as a bind var. Otherwise I'll go around checking all of my bind vars before I send them and I'll be sad, but not that sad, but a little sad.

**Comment by xaka** [comment]
The same here. I'd expect `undefined`/`null` to be equally treated as `NULL`. After switching to latest version of `node-postgres`, existing code stops working.

**Comment by sehrope** [comment]
What version of pg, node, and OS is this happening on?

I tried it with the latest version of pg (v4.3.0) with both node v0.10.38 and v0.12.4 on OSX and passing undefined returns `null`.

Here's what I ran:

    var DATABASE_URL = process.env.DATABASE_URL;
    var pg = require('pg');

    pg.connect(DATABASE_URL, function(err, client, done) {
        if (err) {
          return console.error(err);
        }
        var sql = "SELECT $1::text AS x";
        return client.query(sql, [undefined], function(err, result) {
          done(err);
          if (err) {
            console.error('err:', err);
          } else {
            console.log('rows:', result.rows);
          }
          return pg.end();
        });
    });

Output:

    rows: [ { x: null } ]

**Comment by brianc** [comment]
I definitely agree `undefined` should be coerced into a `NULL` in the query...yeah specific OS, node, and pg verison would be good because this should work.

Thanks for chiming in on this one @sehrope

**Comment by devTristan** [comment]
Interesting. I observed this issue using pg 4.3.0, node 0.12.2, inside the official node:0.12.2 docker image. However, I now find myself unable to reproduce the issue. In my environment, your test works as expected, @sehrope. I'm going to put more effort into reproducing it, but for now I'm going to close this issue and assume it was either my fault, or more likely the work of a poltergeist.
