### ISSUE TITLE
Call done() on clients when garbage collected

### ISSUE THREAD

**Issue by callmeStriking** [brianc/node-postgres#798]
Would it be possible to automatically remove clients when they go out of scope? It would simplify code that gets a client during an HTTP request.

**Comment by brianc** [comment]
I dont think thats possible. v8 doesnt give GC hooks for specific
collections afaik.

**Comment by brianc** [comment]
Yeah unfortunately V8 doesn't really give you hooks like that - you're responsible for manually returning pooled clients to the pool.  Generally I wrap data access sorta like this:

https://gist.github.com/brianc/f906bacc17409203aee0

But you're free to manage the connection pool however you'd like, or even roll a different one.

Hope that helps!

**Comment by callmeStriking** [comment]
I found out that it actually is possible! https://www.npmjs.com/package/weak provides this functionality by exposing the V8 API.
