### ISSUE TITLE
example of inserting jsonb

### ISSUE THREAD

**Issue by tigernassau** [brianc/node-postgres#800]
this code doesn't work and cannot find a good example with jsonb (we can insert manually, just not with this node code)  have substiuted  a test json string instead of data in the brackets -  - it's outputting "error inserting signup" 

insertSignup = function(data){
  console.log("data param: " + JSON.stringify(data));
  pg.connect(pgConnectionString, function(err, client, done) {
    if(err) {
      return console.error('error fetching client from pool', err);
    }
    client.query('insert into signups(data) values($1)', 
        [{"title":"test"}],
        function(err,result) {
      done();
      if (err) {
        console.log("error inserting signup");
        return (500,JSON.stringify({"Error":true}));
      }
      console.log("added signup");
      return(result);
    });
  });
};

**Comment by NikolayS** [comment]
Actually this code is working (changed it a little bit, adding connection string and actual function calling):
```javascript
var pg = require('pg');
var pgConnectionString = 'postgres://mysuer:mypassword@localhost:5432/test';

insertSignup = function(data){
    console.log("data param: " + JSON.stringify(data));
    pg.connect(pgConnectionString, function(err, client, done) {
        if(err) {
            return console.error('error fetching client from pool', err);
        }
        client.query('insert into signups(data) values($1)',
                [data],
                function(err,result) {
                    done();
                    if (err) {
                        console.log("error inserting signup");
                        return (500,JSON.stringify({"Error":true}));
                    }
                    console.log("added signup");
                    return(result);
                });
    });
};

insertSignup({"title":"test"});
```

Running it:
```
nikolay@dev:~/nodejs$ node pgjsonb.js
data param: {"title":"test"}
added signup
```

Meanwhile in Postgres:
```sql
test=# create table signups(data text);
CREATE TABLE

-- and after running the script:
test=# select * from signups;
       data
------------------
 {"title":"test"}
(1 row)
```
