### ISSUE TITLE
Connection pool doesn't work as expected

### ISSUE THREAD

**Issue by lerouxb** [brianc/node-postgres#801]
If I try and create one more connection than the connection pool allows, then it doesn't wait for a slot to open up AND it doesn't call my callback with an error.

Here is a gist that isolates and demonstrates the issue:
https://gist.github.com/lerouxb/7e6e806f3b90982a523b

I would expect it to either wait around a while for a connection to open up or at least return an error immediately.

In an express app it behaves slightly different in that my callbacks never get called and the process doesn't exit, so that request just eventually times out. No further connections can be made with that node process until I restart it, so future requests also time out as soon as you try and make a db query.

These queries are really tiny and short lived. As you can see I call done() immediately after running a query and even before I look at the query results, so I don't think you could argue that I'm leaking connections.

This is admittedly a silly example/test, but it is easily possible that one node.js process will be managing more than 10 (or whatever connection size is set to) concurrent requests eventually, so even if I just use one connection per request, then this can still easily happen.

I suppose I could try and work around this by having just one long running connection per node process, but then what's the point of connection pools and concurrency?

Or is this a bug in node.js, postgresql or some library? While trying to debug this I upgraded every dependency, restarted just about everything and I'm still getting the same behavior.

Any ideas on how to debug this further?

**Comment by sehrope** [comment]
In your sample code you're calling done(client). If client is not-null (ie a legit connection), then that would instruct the pool to close/discard the connection. You should call done(err) so that the connection is dropped only if there's an error using it.

Still, I don't think that would necessarily cause the issue you're describing. I think it would just thrash the connection pool as nothing would get reused. Haven't tried running the example though.

**Comment by lerouxb** [comment]
Interesting. Removing the parameter from done() causes it to work!

I wonder where I got that from? I first wrote (or pasted?) that query function ages ago. Just tried to search through github and I see some lines here and there where people call done(client) and done(true) including in the example app in the wiki. I also can't really see it spelled out anywhere in the documentation that you must pass err to done, btw.

Checked the actual code and done only takes an error parameter. 

I guess this isn't that much of a bug, then.

**Comment by lerouxb** [comment]
So this is the code for done():

    function (err) {
      if(err) {
        pool.destroy(client);
      } else {
        pool.release(client);
      }
    }

I passed it an error that wasn't actually an error and it calls pool.destroy(). If it calls pool.destroy() 10 times, shouldn't an 11th connection still be allowed afterwards?

**Comment by bendiy** [comment]
The issue with the 11th connection not working is detailed here:
https://github.com/brianc/node-postgres/issues/1460

**Comment by charmander** [comment]
Fixed in pg 7.
