### ISSUE TITLE
query row event adds rows without calling addRow

### ISSUE THREAD

**Issue by volkmarbuehringer** [brianc/node-postgres#802]
var pg = require('pg').native;

    query.on('row', function(row, result) {
     //   result.addRow(row);
     //no add Rows done
    });

    query.on('end', function(row ) {   
   // row.rows contains all rows
  });

**Comment by sehrope** [comment]
>    
    query.on('end', function(row ) {...}


This isn't a bug as the `end` event doesn't get passed a row. It gets passed the entire result object which contains the aggregated rows as well as other meta data about the result.

You're using it wrong. You should be using it like this:

    query.on('end', function(result ) {...}

**Comment by volkmarbuehringer** [comment]
the problem is I don't want any aggregation

so I don't use addRows

I want to process large resultsets and don't want to consume huge memory

**Comment by volkmarbuehringer** [comment]
I got it.
I must not use end-event and callback, then it works

But it would be better to have the end-event handler without aggregated rows.

I can now only use client-drain
