### ISSUE TITLE
Buffer type in parameterized query mangles input

### ISSUE THREAD

**Issue by daliwali** [brianc/node-postgres#807]
I am trying to write to the database with a buffer as a parameterized query:

``` js
new Buffer('deadbeef', 'hex')
```

However, what happens is that the buffer gets naively cast as a string so that when I try to read what I just wrote, I get:

``` js
<Buffer de ad ef bf bd ef bf bd>
// Equivalent to `new Buffer('deadbeef', 'utf8')`
```

The solution is to manually cast the buffer to a string, like:

``` js
`\\x${buffer.toString('hex')}` // postgres actually expects the format \x<HEX>
```

I wish that this was the default behavior.

**Comment by charmander** [comment]
I think passing buffers through unchanged was already the behaviour at the time this issue was opened; it’s worked for quite a while by now, anyway.
