### ISSUE TITLE
Seemingly unnecessary files get bundled.

### ISSUE THREAD

**Issue by kaukas** [brianc/node-postgres#813]
Hello.

I can see that commit 77da9e9b0dd00f45af5293235fcfd6e794505bbb removes the `.npmignore` file. Now the builds include files like `Makefile`, `NEWS.md` and folders like `test` (which is not small).

Is this intentional? I know we're not talking gigabytes here but size still matters for a popular and often downloaded project. Even more if you are deploying to [AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/limits.html).

Thank you!

**Comment by kaukas** [comment]
I can create the file and make a PR if you think it is a good idea.

**Comment by bendrucker** [comment]
Using the files property in the package would be better than an npmignore

**Comment by charmander** [comment]
`.npmignore` is back. @brianc, would a complete `files` list in `package.json` be okay?
