### ISSUE TITLE
Use a specific version of "pg-types"

### ISSUE THREAD

**Issue by sarathsaleem** [brianc/node-postgres#820]
Currently `"pg-types": "1.*"` is used in package.json. This should use the specific version.
Today we ran in to this issue https://github.com/brianc/node-pg-types/issues/34 since we have "1.*"

**Comment by bendrucker** [comment]
Yeah, it should be a ~ and not a ^ dep

**Comment by charmander** [comment]
Specifying an exact version of pg-types avoids changing behaviour (even unintentionally) within a version of pg, so I’m very much for this. + @brianc

**Comment by brianc** [comment]
Yah I'd like to move all pg things into a single repo so it's easier to release everything in lock step and test cross-repo changes that might impact and break things.  I'll go ahead and lock down the pg-types version to a `~` dep now in node postgres.

**Comment by brianc** [comment]
How's this look for a fix? https://github.com/brianc/node-postgres/pull/1423

**Comment by charmander** [comment]
A `^` range is fine if pg-types follows semver, and a `~` range isn’t necessarily enough if it doesn’t… but given that brianc maintains them both, `~` probably doesn’t hurt.
