### ISSUE TITLE
Prepared Statement hangs on invalid queries

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#822]
If you try to execute any of the following prepared statements:
```javascript
{name: "test", text: ""}
{name: "test", text: "    "}
{name: "test", text: null}
```
then node-postgres hangs and never comes back.

Tested on Windows 8.1

**Comment by brianc** [comment]
Thanks for reporting this!  Kinda weird protocol gotcha there, but I got it sorted. :clap:

**Comment by vitaly-t** [comment]
@brianc , well done! :+1:
