### ISSUE TITLE
Prepared Statements misconception in Wiki

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#829]
[from your wiki page](https://github.com/brianc/node-postgres/wiki/Prepared-Statements#prepared-statements)

> If you have statements that are executed repeatedly, then prepared statements are the fastest.

I'm sure this has taken lots of developers onto the wrong path, because the statement is totally incorrect. In most cases Prepared Statements are slower than regular queries.

At first, I have done some benchmarking here to compare the speeds, getting consistent 15%-20% drop in speed when using Prepared Statements with node-postgres. And when I started researching it further, I found similar misconception that developers were caught up with.

Prepared Statements were designed to optimize certain type of complex query structures, ones that are particularly heavy when reconstructing the execution plan. In all the other cases, not only they do not help, but they are harmful, as they will only drop the performance.

Please rectify this in your documentation, as this statement must have served poorly too many developers by now, making people jump on with Prepared Statements without understanding the implications.

**Comment by brianc** [comment]
The documentation is a wiki: if you think something is lacking then the opportunity is ripe to contribute directly to the docs.
