### ISSUE TITLE
Support for multiple statements in one string?

### ISSUE THREAD

**Issue by mikl** [brianc/node-postgres#83]
I'm trying to add migration scripts to my little framework, and for that, I need to execute all statements in a file.

As far as I can see from the documentation, `client.query()` is designed for single statements only. Is there another way to accomplish this? I suppose I could just shell out to psql, but that is inconvenient…

**Comment by poshest** [comment]
@brianc "client will queue the queries internally and execute them each one at a time".  Is that done _in the order_ that `client.query` was called?

**Comment by brianc** [comment]
Yah it will.

**Comment by poshest** [comment]
Great thanks.  :) 

I'm trying to debug a problem over [here](http://stackoverflow.com/questions/36739289/node-calling-postgres-function-with-temp-tables-causing-memory-leak/36743914#36743914), and was wondering how exactly should a sequence of calls be made?  This...

```
client.query("BEGIN;");
client.query('select * from get_jobs()', [], function(err, result) {
  client.query("COMMIT;");
  done();
  // do something with result
...
```

Should be equivalent to this...

```
client.query("BEGIN;", function(err) {
   client.query('select * from get_jobs()', [], function(err, result) {
      // do something with result
      client.query("COMMIT;", function (err) {
          done();
...
```

Right?

I understand that everything between `pg.connect(conString, function(err, client, done)...` and `done()` is done in sequence and no other call can be made through that given connection before `done()` is called by the current call.  Would love your thoughts :)

**Comment by brianc** [comment]
Yah thats true. I would highly recommend using callbacks though as error
handling can get really hairy without them.  Also i wouldnt call done
before the callback to commit returns. The query queue was added a looong
time ago for convienece in scripts and in production stuff I highly
recommend you avoid it and use callbacks or your flow control lib of
choice. In my own stuff I use async/await for everything - no callback
hell! :)

**Comment by poshest** [comment]
Sage advice Brian, thank you very much!

**Comment by brianc** [comment]
Haha no problemo! Glad i could help!!

**Comment by rv2358** [comment]
Hi There
Sorry for jumping in, but I have a similar issue. Except that I have multiple insert statements and I want to do them as one Commit block. So I have 
"BEGIN;Insert Stmt1;InsertStmt2;InsertStmt3;COMMIT"
Which works fine, except that I want to get the rowCount on the number of rows inserted. Because of the Commit at the end, the rowCount is applied to the Commit and I get a NULL.
Is there a way around this?
Alternatively If I send it as a single query command, will it Commit as a single block without the BEGIN/COMMIT?
Thanks!
