### ISSUE TITLE
Server Disconnect handling

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#830]
Following issue #821, it seems that node-postgres is missing one very important feature - being able to detect the server disconnect / shut-down to do the following automatically:

1. Terminate any ongoing query;
2. De-initialize the connection pool (for the specific server instance)

I do believe that by calling `pg.end()` we can terminate the entire application pool, so on the next connection it will re-initialize properly, though I'm not 100% sure in that, and doing it regardless of what servers are  currently in the pool isn't very good.

The first item is still important to cater for, because the chances of it happening are very high.

The complication is when the pool contains connections to more than 1 server. The right thing would be to do selective clean-up, based on the server name/address + port, which uniquely identifies the server instance.

**Comment by brianc** [comment]
I'm closing this in favor of continuing the discussion on the original thread.
