### ISSUE TITLE
pg does not seem to support select array_to_json

### ISSUE THREAD

**Issue by tigernassau** [brianc/node-postgres#831]
trying to return an array of json back to express to send into view template 

client.query('select array_to_json(array_agg(signups)) from signups;',function(err,data) {
        if (err) {
          console.log("select signups failed");
        } else {
          console.log("signups");
          console.log(data);
          console.log("using stringify");
          console.log(JSON.stringify(data));
          return (JSON.stringify(data.rows)); 

select runs fine from psql command line 
from nodejs pg -> returning undefined
select runs but instead of an array of json, it returns a bunch of meta data such as row count, .... 
tried it returning just data, JSON.stringify(data) and JSON.stringify(data.rows)

examples found all show results being returned from REST functions with res.JSON - but we are just trying to the json data back into a non-rest function.   Is node-pg supporting this postgres data function ?

**Comment by brianc** [comment]
Yeah it's supported - I've used it in the past.  what is the console output from `console.log(data.rows[0])`?

**Comment by tigernassau** [comment]
On 08/03/2015 10:46 AM, Brian C wrote:
>
> Yeah it's supported - I've used it in the past. what is the console 
> output from |console.log(data.rows[0])|?
>

{array_to_json: [{id:1, email:"jdoe@doe.com",full_name:"john doe", 
.......}]}
so it wraps the desired json array in a json format - could hack to 
extract the desired json array such as "result.array_to_json" but that 
doesn't seem right

console.log(JSON.stringify(data.rows[0])) but that returned nil
console.log(data.rows) => [ { array_to_json: [ [Object] ] } ]

besides, would using rows[0] only return first row, not the others ?




> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/brianc/node-postgres/issues/831#issuecomment-127328395>.
>


-- 
Tiger Nassau, Inc.
www.tigernassau.com

**Comment by sehrope** [comment]
You can use `json_agg` to do this directly. There's no need to use `array_to_json(array_agg(...))`:

    SELECT json_agg(signups) FROM signups

This would return a single row with a single column, "json_agg", that you could access in the query result as `data.rows[0].json_agg`. Since the datatype is json, the driver will convert it to a javascript object which will be an array of the rows of your table with column names as properties.

**Comment by tigernassau** [comment]
On 08/03/2015 05:39 PM, Sehrope Sarkuni wrote:
>
> You can use |json_agg| to do this directly. There's no need to use 
> |array_to_json(array_agg(...))|:
>
> |SELECT json_agg(signups) FROM signups|
> |
> |
>
> This would return a single row with a single column, "json_agg", that 
> you could access in the query result as |data.rows[0].json_agg|. Since 
> the datatype is json, the driver will convert it to a javascript 
> object which will be an array of the rows of your table with column 
> names as properties.
>

thks - getting close - now it might be more of an node/express question 
to get the right returned data but hope you can help so we can add this 
to a node-pg FAQ since it's a common operation

// in model.js
function signups_all() {
   client.connect(....
   client.query('select json_agg(signups) from signups;', function(err, 
data) {
     console.log(data.rows[0].json_agg); //=> yes, gives the correct 
array of signups
     return (data.rows[0].json_agg);
   });
   });
}
exports.signups_all = signups_all;

in server.js
app.get("/signups", function(req, res) {
   var signups = model.signups_all(function(err,result){
     if (err) {
       console.log("error");
     } else {
       signups = result;
       res.render("signups", {signups:signups));
     }
   });
});
===> hangs "waiting for localhost"



> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/brianc/node-postgres/issues/831#issuecomment-127433734>.
>


-- 
Tiger Nassau, Inc.
www.tigernassau.com

**Comment by sehrope** [comment]
@tigernassau: Format your messages with indented whitespace so that it shows up as code. It makes it much easier for others to read it.

>    function signups_all() {
>      ...
>      return (data.rows[0].json_agg);

You can't return values from an async function. You need to pass a callback and invoke the callback on the result.

**Comment by tigernassau** [comment]
On 08/03/2015 07:48 PM, Sehrope Sarkuni wrote:
>
> @tigernassau <https://github.com/tigernassau>: Format your messages 
> with indented whitespace so that it shows up as code. It makes it much 
> easier for others to read it.
>

sorry, we usually do but might have been lost cutting, pasting w/ email

>     function signups_all() {
>     ...
>     return (data.rows[0].json_agg);
>
> You can't return values from an async function. You need to pass a 
> callback and invoke the callback on the result.
>

understand re return but really lost on using pg to callback from a 
model.js file or are we just condemned to putting all queries into the 
express req res functions  - there don't seem to be any examples with 
postgreql queries in a model file





> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/brianc/node-postgres/issues/831#issuecomment-127452567>.
>


-- 
Tiger Nassau, Inc.
www.tigernassau.com

**Comment by brianc** [comment]
@tigernassau how you structure your application is up to you, but as far as I can tell fr om where we're at in this issue node-postgres itself is working properly.
