### ISSUE TITLE
Parameters in ORDER BY and LIMIT clauses don't throw an error

### ISSUE THREAD

**Issue by MatteoVH** [brianc/node-postgres#832]
In reference to #300, attempting to add parameterized values outside of WHERE clauses should throw a parse error. Right now they seem to be silently gobbled and given some sort of default value or none at all.

Example query:
client.query("SELECT id, ... ORDER BY $1 LIMIT $2"), ['id', 10], cb);

No errors are thrown, I just get results that seem to abide by the LIMIT but not the ORDER BY.

If a parameter is placed outside of a WHERE clause, there should at least be a warning of undefined behavior, preferably a hard error.

**Comment by sehrope** [comment]
> In reference to #300, attempting to add parameterized values outside of WHERE clauses should throw a parse error. Right now they seem to be silently gobbled and given some sort of default value or none at all.

Can you post a full example? I don't see anything wrong with the snippet you've listed.

> If a parameter is placed outside of a WHERE clause, there should at least be a warning of undefined behavior, preferably a hard error.

You can use parameters outside of a WHERE clause. It's a pretty common thing to do. 

All of the following are all valid queries:

* `SELECT $1::text AS x`
* `SELECT 1 AS x WHERE $1 = 'test'`
* `SELECT 1 AS x ORDER BY $1::text` - Note this doesn't really make much sense as you're sorting by a constant value so it'll be the same for all rows. It's still valid though.
* `SELECT 1 AS x LIMIT $1`

**Comment by brianc** [comment]
node-postgres doesn't parse your query text or look at it in any way.  If your query doesn't return an error from postgres than it's a valid query though possibly not working the way you intend it to.  If postgres does return an error than you know something is wrong with your query.  We're never gonna add query parsing and error checking to this library - it's definitely the role of postgres itself to do that & it does a good job.

**Comment by charmander** [comment]
(accidental double-click?)
