### ISSUE TITLE
Does node-postgres have a PSQL parser/AST?

### ISSUE THREAD

**Issue by Josiah** [brianc/node-postgres#835]
I'd like to implement some 'smart' string templates which can incorporate other string templates in them. Something like:

```js
function isActive(table) {
  return {
    text: `${table}.is_active = true`,
    values: []
  }; 
}

function getActiveFoo(id) {
  return `SELECT * FROM foo WHERE id = ${id} AND ${isActive('foo')}`;
}
```
The reason a parser/AST is required is that `text` could contain parameters for which the offset needs to be adjusted. Regular expressions would be a mess and a simple find/replace operation would fail under some circumstances.

I'm asking here before I go off and (attempt to) implement my own SQL Parser.

**Comment by brianc** [comment]
Hey @Josiah - node-postgres definitely does not have a PSQL AST parser.  That would be a super awesome module to build though so lemme know if you do start on it - i'd love to keep my eye on it and I'm sure the community could find a lot f awesome use-cases for it!

**Comment by Josiah** [comment]
:+1: I'll ping you when I've got something to share for some feedback
