### ISSUE TITLE
Named Parameters - now supported in PostGres v9.2+

### ISSUE THREAD

**Issue by nfloersch** [brianc/node-postgres#839]
It seems that node-postgres does still not support named parameters in queries. I realize that this was a problem a few years ago because PostGres itself did not support such a thing. But it does now. I would prefer to not have to use a different library/tool that extends node-postgres just to have better access to this functionality. Thanks!

**Comment by sehrope** [comment]
PostgreSQL doesn't support named parameters. It only supports positional parameters (`$1`, `$2`, ...etc) though you can reference the same parameter more than once. Ex: `SELECT * FROM foo WHERE bar = $1 AND baz = $1`

There's a couple of npm modules that wrap node-postgres to provide named parameter support listed as "Extras" on the [README](https://github.com/brianc/node-postgres#extras). Check out [pg-db](https://github.com/sehrope/node-pg-db) (I wrote it). It handles auto-returning connections to the pool, transactions, as well as named parameters. See [here](https://github.com/sehrope/node-pg-db#named-parameters) for some examples of using it with named parameters.

**Comment by nfloersch** [comment]
So... what about...

http://www.postgresql.org/docs/devel/static/sql-syntax-calling-funcs.html

"PostgreSQL allows functions that have named parameters to be called using either positional or named notation."

Or any of the stuff in "4.3.2. Using Named Notation" of that document?

The named notation was added in 9.2, although the syntax has changed slightly since it was introduced. 

I admit to being a non-guru with PostGreSQL... so maybe I just mis-understand the terminology.

**Comment by sehrope** [comment]
That's for user defined functions, not arbitrary SQL commands. When you execute SQL commands from node-postgres, or really any client including psql, you specify a SQL command such as a `SELECT`, `INSERT`, etc. Those can't have named parameters as the wire protocol only supports only numbered parameters.

**Comment by sibelius** [comment]
can't we build an abstract to transform named parameters in positional parameters?

**Comment by sehrope** [comment]
@sibelius There's plenty of existing libraries that support named parameters but it's beyond the scope of the driver as PostgreSQL itself (the server) does not support them. It, the server, only supports positional parameters and thus that's the interface that the driver provides.
