### ISSUE TITLE
some regex expressions don't seem to work

### ISSUE THREAD

**Issue by ltramos** [brianc/node-postgres#841]
Hi Brian, 

Thanks for your good work on pg.  I have been trying to use regex in my current queries. I notice that '\s', '\S' , 'w' , '\W' don't seem to be recognized as valid regex. For instance when I use ''\s\w+$'' as a query parameter, it doesn't work. What works instead is '[A-Z0-9_]+$'. Have you encountered this before?

Thanks for your time reading this.

**Comment by stenrap** [comment]
I also ran into a problem with regex escapes and pg. When I use this where clause at a psql prompt, the query returns zip codes as expected...

`WHERE zip ~ E'\\d{5}'`

...but when I try to use it in pg, I get zero results. If I change it to this...

`WHERE zip ~ E'[0-9]{5}'`

...it works in pg.

This minor issue aside, thanks for making such a stellar Postgres library for Node.js!

**Comment by sehrope** [comment]
@stenrap That looks like a JS escaping issue. You need to double the backslashes as JS (so four backslashes in total) for it to show up properly in the SQL sent to the database:

    > var s1 = "SELECT * FROM foo WHERE zip ~ E'\\d{5}'";
    > console.log(s1);
    SELECT * FROM foo WHERE zip ~ E'\d{5}'

    > var s2 = "SELECT * FROM foo WHERE zip ~ E'\\\\d{5}'";
    > console.log(s2);
    SELECT * FROM foo WHERE zip ~ E'\\d{5}'

**Comment by stenrap** [comment]
D'oh! Right you are. Sorry about that.
