### ISSUE TITLE
Limit with placeholder

### ISSUE THREAD

**Issue by Aconradty** [brianc/node-postgres#844]
I would like to set LIMIT as described here http://www.postgresql.org/docs/current/static/queries-limit.html

LIMIT { number | ALL }

 but if i try that with node-postgres:
pg.queryAsync('SELECT * from image_files LIMIT $1', ['ALL'])

it gives me : invalid input syntax for integer: \"ALL\"

Any chance to be able to use ALL instead of integer ?

**Comment by booo** [comment]
Why don't you use 
```sql
SELECT * FROM image_files LIMIT ALL
```
or
```sql
SELECT * FROM images_files
```
?

**Comment by jardakotesovec** [comment]
Because if you implement some pagination functionality its just handy to use 'ALL' parameter instead of number in case of unlimited query.  I guess thats the point of 'ALL' anyway.  

Its similar situation as you would do with `OFFSET 0`.

**Comment by booo** [comment]
You can use `ALL` but it must be part of the query text or you can omit it at all. Maybe that makes your code a little bit more complicated (read unhandy) but that's the way it is.

**Comment by jardakotesovec** [comment]
@booo Ok Thanks. So there is some good technical reason to not support that?

**Comment by booo** [comment]
I think it's more a problem of the postgres protocol that we implement with node-postgres and not a problem of the driver (node-postgres) implementation. But I'm not THE expert on this.
