### ISSUE TITLE
Default username setting is broken on at least Linux

### ISSUE THREAD

**Issue by Lekensteyn** [brianc/node-postgres#847]
From http://www.postgresql.org/docs/9.4/static/libpq-connect.html#LIBPQ-CONNECT-USER:

> user
> 
> PostgreSQL user name to connect as. Defaults to be the same as the operating system name of the user running the application.

The current implementation for defaults set the username to the `$USER` env var on non-windows systems (including Linux):

```
process.platform === 'win32' ? process.env.USERNAME : process.env.USER
```

The `USER` env var is non-standard and not set in a cron for example. Isn't there a node function to get the username? Nothing in [process](https://nodejs.org/api/process.html) or [os](https://nodejs.org/api/os.html) at least...

Edit: this happens with node-postgres 4.4.1. And spitting through node's code, there is indeed no way to get the username (searched for `logname`, `passwd`). The best that can be done now is to add a fallback to `LOGNAME` (which is actually used by cron).

**Comment by brianc** [comment]
Yeah I'd suggest if the default isn't working out for you your best bet is going to be to manually configure it. I prefer to use environment variables: `PGUSER` should do what you want.
