### ISSUE TITLE
Connection using SSL even though I have SSL set to false in options

### ISSUE THREAD

**Issue by ym-mqual** [brianc/node-postgres#848]
Stems from line 44 in the connection-parameters.js.  I corrected it as follows:

OLD: config.ssl || useSsl(); -this is a problem if you send in false.
CORRECTED: this.ssl = typeof config.ssl === 'undefined' ? useSsl() : config.ssl;

**Comment by ym-mqual** [comment]
Actually thought about it again and this is probably better:

this.ssl = typeof config.ssl === 'boolean' ?  config.ssl : useSsl();

**Comment by simonv3** [comment]
:+1: I can confirm that this is an issue, and that fixes it.

**Comment by joskuijpers** [comment]
Can you submit a Pull Request?

**Comment by joskuijpers** [comment]
@brianc This can be closed now

**Comment by brianc** [comment]
@joskuijpers you are so helpful! Thank you!!
