### ISSUE TITLE
defaults.poolSize = 0 does not only disable pooling, but all functionality

### ISSUE THREAD

**Issue by oliversalzburg** [brianc/node-postgres#853]
The comment about `poolSize` mentions:

>  //Connection pool options - see https://github.com/coopernurse/node-pool
>   //number of connections to use in connection pool
>   //0 will disable connection pooling

However, when I set `poolSize` to `0`, only the first query ever is processed and then our application stops working. I'm suspecting that calls, which would normally start a transaction, never actually return or their callbacks are never invoked.

Seems very similar to #517, which we're also dealing with.

**Comment by brianc** [comment]
Seems like a bug w/ generic pool.  I'm upgrading to generic-pool 3.0 in the next version of node-postgres & hoepfully it's fixed then!
