### ISSUE TITLE
Connection string without a password

### ISSUE THREAD

**Issue by dschinkel** [brianc/node-postgres#854]
I assume if the username is postgres and no password you'd format the string like this:

'postgres://username:@servername:port/dabaseName'

Notice I left out a password after the 2nd : and just have postgres:@

**Comment by jalcine** [comment]
[**@dschinkel**](https://github.com/dschinkel) commented on [Sep 9, 2015, 3:02 PM EDT](https://github.com/brianc/node-postgres/issues/854#issue-105661903 "2015-09-09T19:02:14Z - Replied by Github Comment Enhancer"):
> I assume if the username is postgres and no password you'd format the string like this:
> 
> 'postgres://username:[@servername](https://github.com/servername):port/dabaseName'
> 
> Notice I left out a password after the 2nd : and just have postgres:@

That could result in a parsing issue, no? One would expect to be:
`postgres://username@servername:port/databaseName`

**Comment by bdunavant** [comment]
Hi @dschinkel

I believe that jalcine is correct.  Without a password, you should use "username@"

http://www.postgresql.org/docs/9.4/static/libpq-connect.html#LIBPQ-CONNSTRING

If this addresses your question, please close the issue :)

**Comment by joskuijpers** [comment]
@brianc Wield your magic closing-wand
