### ISSUE TITLE
Synchronous call with Pg library what's the best way ?

### ISSUE THREAD

**Issue by atrhacker** [brianc/node-postgres#856]
I'm trying out the framework node.js on one of my projects. I'm really seeing some good advantages on what they called "event-driven, non-blocking I/O model" however if my project there are some moments where I don't necessarily want to have some asynchronous calls and to be able to several operation before launching some asynchronous call.

Especially when I want to do some factorization and create some functions.

Typically I have the following case: I know that in several part of my program I have to check if a media is existing in my database for a given string or id.

So as a guy who tried to stay organize I want to create a function that I will call each time I need to check this. However, I did not find the way to do that with node.js and pg  . Indeed, there is always a callback in the function and the return is null because of the callback. Here is an example below
```javascript
 /*
 Function which is supposed to check if a media existing
*/
function is_media_existing (url_or_id){
    log.debug("is_media_existing : begin of the function", {"Parameter" : url_or_id});
    pg.connect(connectionstring, function (err, client, done) {
        if (err) {
            log.warning("is_media_existing : Problem with Database connection", {
                "Parameter": url_or_id,
                "Error": err
            });
        }
        if (isNaN(url_or_id)) {
            // Case is parameter is not a number (string)
            var query = client.query('SELECT COUNT(*) as count FROM media WHERE url = $1::string ', url_or_id);
            query.on('error', function (error) {
                log.warning("is_media_existing : Problem with Database query (connection to db passed but not query " +
                    "", {"Parameter": url_or_id, "Error": error});
            });
            return query;
        } else {
            // Case is parameter is a int
            log.debug("is_media_existing : Type of Parameter is a string");
            // Case is parameter is not a number (string)
            var query = client.query('SELECT COUNT(*) as count FROM media WHERE id = $1::id ', url_or_id);
            query.on('error', function (error) {
                log.warning("is_media_existing : Problem with Database query (connection to db passed but not query " +
                    "", {"Parameter": url_or_id, "Error": error});
            });
            return query;
        }
    });
 }

// Executing the function 
var test = is_media_existing("http://random_url_existing_in_db");

// test is always null as the return is in a callback and the callback is asynchronous +
```
I have the feeling my question is touching the core concepts of node.js,  and perhaps my approach is wrong and I apologize in advance.
I know it's not good to wait for a response before doing somehting.
But what's the alternative ? How can I factorize my code into functions when I need some functionnalities in several part of my code ?

 So if there would be anyone who could explain how to do that with a best practice of programming it would be great.

Thanks

Anselme

**Comment by spyalert01** [comment]
I am having the similar problem as well. 
It needed to be sync. I tried install PG-Sync in windows enviroment, and it failed to install, so do pg-native fail me.
I found the yield method, but preferably it can be used with the async await and return promise.

**Comment by brianc** [comment]
The only way to do sync queries is to use [pg-native](
https://github.com/brianc/node-pg-native) and use the `sync` variant of the
methods.  Using pure javascript client it is __impossible__ to do sync
queries because of how node works.  You should also never use sync queries
in a production application in a hot code path (such as in a web server
when serving requests) - use an async flow control library or promises.

**Comment by spyalert01** [comment]
The async is using pg or pg native?

**Comment by DaAwesomeP** [comment]
@brianc What about for just the connection part? I'm making a separate DB module of my app that I want to include like so: `var db = require('./db')(config);`. So, the library included is really just an exported function that runs when the library is included and returns an object when it's done (it returns the object synchronously, but what's in the object returned doesn't have to be). In this case, having `pg.connect()` be synchronous is advantageous. The individual queries can still be asynchronous.

**Comment by DaAwesomeP** [comment]
Nevermind! I used `co` and generators to solve the problem like so:
```js
var lib1, db, lib2;
co(function *loadLibs () {
  lib1= yield require('./lib1')(config);  // Will load these in order, one at a time
  db = yield require('./db')(config);    // Each one returns either a Promise or another co statement 
  lib2= yield require('./lib2')(config);  // When the last one finishes, it runs then()
}).then(function() {
  // Continue with those vars, loaded in order
});
```

**Comment by cuteboi** [comment]
You could always use the async-waterfall.
