### ISSUE TITLE
How to insert data recursively?

### ISSUE THREAD

**Issue by silvioprog** [brianc/node-postgres#860]
Hello,

I have a very simple structure:

create table test (id integer, description varchar(50))
And I already insert data normally when I need to send just one data, however, now I need to send my data in a array, something like this:

[
  { "id": 1, "foo" },
  { "id": 2, "bar" }
]

And this array will be inserted recursively.

So I have a question: can I insert data recursively using node-pg?

Thank you!

**Comment by brianc** [comment]
You can use an async flow control lib or do something like [search for 'multiple' here](http://www.postgresql.org/docs/8.2/static/sql-insert.html)
