### ISSUE TITLE
Confused about ensuring that Prepared Statements are reused

### ISSUE THREAD

**Issue by 3n-mb** [brianc/node-postgres#863]
[Wiki page](https://github.com/brianc/node-postgres/wiki/Prepared-Statements) in "Using Prepared Statements" states that  **pg tracks which statements have been prepared for a session**.  
What **sessions** is it talking about?  
How do I control that Clients are from the same **session**, so as to ensure that reuse of prepared statements does take place?

**Comment by harshitgupta** [comment]
+1

I am confused here.

So, let's say we have pool of clients here. If

1. I pick one `client` from the `pool`, 
2. run a `prepared statement` with `name`
3. then return the `client` to `pool`
4. again pick up one `client` from `pool`
5. run the same `statement`
6. and  return the `client` to `pool`

Would I get the benefit of `prepared statements`?

Next, lets after step 3, `client` was released due to `idletimeout`, would I still get the benefits in further steps?

Thanks

**Comment by 3n-mb** [comment]
@harshitgupta 
Initial question was from 2015. Now, readme.md documents about pool-ing, i.e. us, users of the lib should use it.
Wiki page close to the end [says](https://github.com/brianc/node-postgres/wiki/Parameterized-queries-and-Prepared-Statements):
> ### Re-using prepared statements
> Since caching is per-session, sometimes it is not possible to be sure that a given prepared statement exists in the cache. If all calls are made within the same pg.connect block, the statement will be cached because all calls use the same pg session.
 > However, in practical use (e.g. with Express), you could have a pool of pg connections being used by middleware serving hundreds of HTTP requests. The fail-safe way to use prepared statements is to always supply both the text and the name. When a statement named name is found to be cached, text is ignored and the cached statement is used. If name is not found in the cache, a new prepared statement is created using the text supplied. (as discussed in this issue)

I assume that each opened client has its own session, and we should follow quoted text, as second time statement prepping will not occur.

BTW, wiki is updated and has proper links to postgres' docs. Session in my original question are from [there](https://www.postgresql.org/docs/devel/static/protocol-overview.html#protocol-message-concepts).

**Comment by harshitgupta** [comment]
Thank you for the response.

You said 
> I assume that each opened client has its own session

With due respect, I still didn't get my answer. I don't want write code based upon assumptions. 

if @brianc or someone else could confirm it. It would be really helpful.

**Comment by 3n-mb** [comment]
Given no response since 2015, even though guys were updating code and 
docs, which I appreciate. The best insurance is a look-into-code.

Are you writing new code? Or, are you in an optimization stage?

In the writing stage, I am going to follow quoted wiki page. Ya.

**Comment by 3n-mb** [comment]
Specifically for your question.

Pool concept increase throughput when client is not released. Pools 
sweet spot is when objects are reused. When client's disconnects, it is 
probably removed from the pool. At least other implementations do this. 
The disconnect closes client's session from postgres' protocol.

So, the best way to reuse prepped statements is to use pool with quoted 
from wiki approach.

If postgres' protocol allows session resumption, it would be reasonable 
to ask, if pooled clients support it. But this stage is for 
optimization, at which stage, source is your friend.

**Comment by harshitgupta** [comment]
I am in optimization stage. 

I followed the documentation but it didn't help. 

If releasing the client clears all the prepared statements, then I will have to preserve the client, thus will have to lot of changes. But main focus is to be able to optimize the whole logic for better performance. I will do the changes once I am sure of what I am doing or knowing if it really worth it?

**Comment by 3n-mb** [comment]
When I wrote client is released, I meant that connection has idled, and 
it got closed. Then pool releases an object into the void.

But when you have an idle client, it indicates that you server is not 
busy. Why worry about this time spot?

At busy times clients are reused with open connections somewhere in 
them. So, you get all benefits when server is busy.

**Comment by 3n-mb** [comment]
Closing connection due to idle by pg server probably closes session. It 
is closing the session that invalidates prepped statements.

As per readme, client is used inside of pool's connect. So, we do not 
return explicitly client to pool. In other API you would be returning 
client to a pool. But this return to pool does nothing with pg session, 
which is kept by client for a reuse.
