### ISSUE TITLE
Insert array into a JSON column

### ISSUE THREAD

**Issue by yanickrochon** [brianc/node-postgres#865]
This query fails

```
var q = adapter.query('INSERT INTO tbl_data (id, data) VALUES ($1, $2)', [ 1, ['a', 'b'] ] );
```

with 

```
 error: undefined
      at Connection.parseE (/home/user/dev/node_modules/pg.js/lib/connection.js:534:11)
      at Connection.parseMessage (/home/user/dev/node_modules/pg.js/lib/connection.js:361:17)
      at Socket.<anonymous> (/home/user/dev/node_modules/pg.js/lib/connection.js:105:22)
      at Socket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)
```

The table is defined as 

```
CREATE TABLE tbl_data
(
  id bigserial NOT NULL,
  data json,
  CONSTRAINT "PK_data" PRIMARY KEY (id)
)
```

(Note: the table is for tests only, and it illustrate the problem I am having in my project.)

Also, see #864

**Comment by yanickrochon** [comment]
The actual error is this :

```
{ [error: invalid input syntax for type json]
  name: 'error',
  length: 148,
  severity: 'ERROR',
  code: '22P02',
  detail: 'Expected ":", but found ",".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'JSON data, line 1: {"a",...',
  file: 'json.c',
  line: '1136',
  routine: 'report_parse_error' }
```

I don't understand why `['a', 'b']` gets transformed into `{'a', 'b'}`.

**Comment by yanickrochon** [comment]
[This function](https://github.com/brianc/node-postgres/blob/eb894900ed2ffe317632c7a1fc7217773a660f8c/lib/utils.js#L5) is at fault. Why isn't `JSON.stringify` used as is?

**Comment by yanickrochon** [comment]
The only solution I can think of is to execute the query like this :

```
var q = adapter.query('INSERT INTO tbl_data (id, data) VALUES ($1, $2)', [ 1, JSON.stringify(['a', 'b']) ] );
```

Which seems to work.

**Comment by sehrope** [comment]
That format is the PostgreSQL literal format for arrays. That's why that function is used instead of `JSON.stringify(...)`. Arrays are a core feature of PostgreSQL and have been around long before json support was added (*fun fact: you can even have arrays of json*). I'm not sure of the full history of the driver but looking at the code I'd guess that the point is to automatically handle JS arrays turning into PG arrays.

Since it's already handled like that (and has been for a while), it'd be quite a breaking change to have it send an array as `json` instead. Your solution of stringifying the array should work fine.

**Comment by yanickrochon** [comment]
A user reported that some data wasn't saving, the error thrown is still this one. It would be nice to know exactly what query threw an error instead of a partial stack trace that shows no tie to my code. The error is throws after a few queries have been executed and I have no idea which one is at fault. Manually executing the queries in pgadmin seems to be fine, so I'm totally clueless and I need to dig and spend a lot of time on this "trivial" fixing task.

As the soul developer, I wish I'd have the time and resource to test everything... and I do for everything else but model related. This is not expected to fail.

**Comment by yanickrochon** [comment]
Alright, closing this, now. It was a `-` character on a different line that caused `NaN` to be sent (i.e. `-{}`) This is not pg's fault.
