### ISSUE TITLE
Close particular pool

### ISSUE THREAD

**Issue by Suor** [brianc/node-postgres#867]
There is now `pg.end()`, which closes everything. It is sometimes desirable to close all connections to particular db, i.e. single pool. Probably with:

``` js
pg.end(connString)
```

**Comment by brianc** [comment]
Yeah that's true - I'm open to a pull request with that functionality!

**Comment by brianc** [comment]
I've deprecated the global singleton pool manager mumbo jumbo in favor of creating pools yourself via `new pg.Pool()`
