### ISSUE TITLE
Tests try to connect with wrong user

### ISSUE THREAD

**Issue by Suor** [brianc/node-postgres#868]
I am trying to run tests with

``` bash
make test-all connectionString=pg://postgres@localhost:5432/postgres
```

and also just

``` bash
npm test
```

And both times I get:

```
130-tests.jsMessage: expected Error: Command failed: psql: FATAL:  role "suor" does not exist
 to be null
AssertionError: expected Error: Command failed: psql: FATAL:  role "suor" does not exist
 to be null
    at Function.assert.isNull (/home/suor/projects/node-postgres/test/test-helper.js:170:10)
    at /home/suor/projects/node-postgres/test/integration/gh-issues/130-tests.js:10:16
    at /home/suor/projects/node-postgres/test/test-helper.js:159:16
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

Looks like it's trying to connect with current user instead of `postgres`.

**Comment by brianc** [comment]
Weird - try setting the connection params w/ environment variables instead
of that connection string:

`PGUSER=foo PGPASSWORD=bar PGDATABASE=baz make test-integration`

**Comment by Suor** [comment]
That worked. Should docs and/or `npm test` be updated?

**Comment by whymarrh** [comment]
I'm seeing this same issue on `7.4.3` with a similar connection string:

    postgres://postgres:password@localhost:5432/postgres

Using the environment variables works:

    PGUSER=postgres PGPASSWORD=password PGDATABASE=postgres npm start

Is this expected behaviour?

**Comment by charmander** [comment]
@whymarrh How are you passing the connection string to pg?

**Comment by charmander** [comment]
@whymarrh Does it work if you use a string literal instead of `process.env.PG_CONNECTION`?

**Comment by whymarrh** [comment]
Inlining the string doesn't work either, no.
