### ISSUE TITLE
"[0:X]=" prepended to the first element of array

### ISSUE THREAD

**Issue by ghost** [brianc/node-postgres#870]
The query:

```
var query = db_client.query("select * from users where id = $1", [user_id]);
```

Where one of the columns in table `users` is of type `text[]` returns:

```
["[0:4]=item1","item2","item3","item4","item5"]
```

as the contents of that column. 
pgAdmin III shows the actual contents as:

```
[0:4]={item1,item2,item3,item4,item5}
```

Using PostgreSQL 9.4, node v0.12.4 and pg 4.4.2

**Comment by charmander** [comment]
Arrays with bases other than 1 aren’t really a good idea, but I suppose the parser should do *something* with them.

**Comment by charmander** [comment]
@brianc, are you interested in supporting this/throwing an error when encountered?

**Comment by brianc** [comment]
It is probably not a hard fix, but I need a self-contained piece of code to reproduce it.  If there isn't one I think it's fine to close for now unless it comes up again.  No one's mentioned it for almost 2 years now. 😄

**Comment by charmander** [comment]
Self-contained:

```js
client.query("SELECT '[0:0]={example}'::text[]")
```

It’s a valid format, but there’s no good reason to use non-1-based arrays.
