### ISSUE TITLE
Cannot Query for all Tables in Database

### ISSUE THREAD

**Issue by ethanmick** [brianc/node-postgres#885]
Heyo,

I'm running this query:

```
SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE';
```

It works fine in Postgres itself, but not when doing:

```
// About 80% of a full example
client = new pg.Client(URI)
client.connect()
// Successful connection, then later
client.query("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE';")
```

It throws:

`Uncaught TypeError: Cannot read property 'getTypeParser' of undefined`

I'm expecting a list of results with a single column, `table_name`, where each row is a table name in my database.

Thank you!

**Comment by Aconradty** [comment]
this works for me
```
client.query("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE';", function (err, result) {
     console.log(result.rowCount);
});
```

using "pg":"4.4.3" with native: false

if you are using pg-native, i think it's related to this issue

https://github.com/brianc/node-postgres/issues/759

**Comment by charmander** [comment]
You should wait for `connect`’s callback before sending queries. This seems to work fine now, anyway; if not, just leave a comment.
