### ISSUE TITLE
Reading bytea[] fails

### ISSUE THREAD

**Issue by sibedge** [brianc/node-postgres#886]
Fails to read data of type `bytea[]` when one or more of the array values are `null`.

For example, node-postgres does correct insertion of value `['\x1A2B', null, '\x1C2D']`, but it fails to read such data back.

**Comment by vitaly-t** [comment]
1 year later, and not a single comment? :(

**Comment by charmander** [comment]
@brianc With brianc/node-pg-types#67 merged, a new published version of pg-types will fix this. 😊

**Comment by vitaly-t** [comment]
Would be nice to have a test for this case ;)

**Comment by brianc** [comment]
@charmander thanks for the heads up! I have set to 'watch' on pg-types and own the repo yet still don't seem to get notifications from it.  I've published a new patch version with your fix! `pg-types@1.12.1`
