### ISSUE TITLE
using variable named "arguments" results in variable overwriting

### ISSUE THREAD

**Issue by samlobel** [brianc/node-postgres#891]
I wrote the following method:

    function newDatabaseFetch(queryString, args, callback){
	  var conString = "postgres://my_username:my_password@localhost/account";
	  pg.connect(conString, function(err, client, done) {
		if(err) {
	    console.error('error fetching client from pool', err);
	    return callback(err);
	  }
	  console.log("querying now");
	  console.log(args);
	  client.query(queryString, args, function(err, result){
	  	done();
	  	if (err){
	  		console.error('error running query: ', err);
	  		return callback("error running query: " + err);
	  	}
	  	return callback(null, result);
	  });
	});
  }

And when I print args, I get 

{ '0': null,
  '1':
   { domain: null,
     _events: { error: [Function], end: [Function] },
     _maxListeners: 10,
     connectionParameters:
      { user: 'user',
        database: 'database',
        port: 5432,
        host: 'localhost',
        password: 'password',
        binary: false,
        ssl: false,
        client_encoding: '',
        isDomainSocket: false,
        application_name: undefined,
        fallback_application_name: undefined },
     user: 'user',
     database: 'database',
     port: 5432,
     host: 'localhost',
     password: 'password',
     _types: { _types: [Object], text: {}, binary: {} },
     connection:
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        stream: [Object],
        lastBuffer: false,
        lastOffset: 0,
        buffer: null,
        offset: 1,
        encoding: 'utf8',
        parsedStatements: {},
        writer: [Object],
        ssl: false,
        _ending: false,
        _mode: 0,
        _emitMessage: false,
        _reader: [Object] },
     queryQueue: [],
     binary: false,
     encoding: 'utf8',
     processID: 27301,
     secretKey: secretkey,
     ssl: false,
     poolCount: 1 },
  '2': [Function] }

So by the time I called client.query, arguments was overwritten! Changing my variable name from arguments to args made it work again. Thoughts?

**Comment by brianc** [comment]
`arguments` is a special case variable 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments

So it's always being re-defined in the child functions.  Best thing to do is never declare a function parameter or variable named `arguments` because it already exists.
