### ISSUE TITLE
How to implement pgnotify in client side - need alert in html page

### ISSUE THREAD

**Issue by sambsa** [brianc/node-postgres#893]
I have referred this tutorial http://bjorngylling.com/2011-04-13/postgres-listen-notify-with-node-js.html and it is working perfectly in my Command Prompt. I need to integrate this feature on my html page. I need in such a way that if a database insertion happens then I should get an alert message in my web page like real time notification.is there any ways to do that?

**Comment by iwootten** [comment]
You need to use socket io in node to emit notifications to the client web app which also uses socket io to update with alerts. See here (you'll need to update for api changes since 2013): http://darrenoneill.co.uk/post/real-time-web-apps-postgresql-and-node/
