### ISSUE TITLE
What happens if multiple queries are submitted to the same connection client?

### ISSUE THREAD

**Issue by bamoqi** [brianc/node-postgres#896]
If I write
````
function(err, client, done) {
    client.query(query1,cb1);
    client.query(query2,cb2);
}
````
Does the client wait until query1 receives a result before submitting query2 to the DB? Or it submit the queries together?
Secondly, what happens if 2 separate queries in different turns of the event loop are submitted to the same connection client? Do they behave the same as the above code?
Thanks.

**Comment by brianc** [comment]
Yeah it will buffer queries and send them one at a time. That's actually just some unfortunate behavior we've had in node postgres since the behinning of time. Your best bet is to jse async, promises, or what I do is async/await with es6. I should have some blog posts coming out around this soon!

**Comment by nicholaswmin** [comment]
@brianc Well, what about transactions? Those can't be sent in parallel unlike regular queries
