### ISSUE TITLE
Is not multiple commands supported anyway?

### ISSUE THREAD

**Issue by mageddo** [brianc/node-postgres#897]
Can not I pass multiple queries? examples:

	con.query('SELECT 1 as id; SELECT 2 as id');
	con.query('INSERT INTO t1 VALUES (1); UPDATE t2 SET a=1;');

**Comment by brianc** [comment]
you should be able to do that - are you getting an error message about it?

**Comment by dcousens** [comment]
What was the result of this?

**Comment by gtjoseph** [comment]
I have the same issue.

```javascript
var ins_stmt = 'delete from mytable where cola = $1 and colb = $2 ; insert into mytable (cola, colb) values($1, $2);'

client.query({text: ins_stmt, values: values}, function(err, result) {
}
```
"ERROR:  cannot insert multiple commands into a prepared statement"
Per the docs, `name` is NOT specified in the config object.

Tried with native, same error.

pg@4.4.3
pg-native@1.9.0

**Comment by brianc** [comment]
Postgres does not support multiple commands in a prepared statement. You have to send multiple commands separately.

**Comment by gtjoseph** [comment]
It's not a prepared statement.  There's no `name` in teh config object.  It's a parameterized one.

**Comment by brianc** [comment]
Yah sorry doesnt support either. Plain text query you can pipeline, but any parameters and you need to do 1 query per call.

**Comment by mageddo** [comment]
I am trying 

	client.query('BEGIN;DELETE FROM tagBookmark WHERE tagId = $1; DELETE FROM tag WHERE id = $1 ;COMMIT;', [1,2] ,function(err){});

And getting 

	 Uncaught AssertionError: { [error: cannot insert multiple commands into a prepared statement]
	  name: 'error',
	  length: 116,
	  severity: 'ERROR',
	  code == null

	....

It will not work with `postgre`? Because it works great on pgadmin

**Comment by brianc** [comment]
You have to send each command as a separate query. You cannont separate multiple commands with a semi-colon if you're using parameters.

**Comment by mageddo** [comment]
Ok, thanks
