### ISSUE TITLE
Error: Cannot find module 'pg-native' from '....projectFolder/node_modules/pg/lib/native'

### ISSUE THREAD

**Issue by mdcsfk** [brianc/node-postgres#904]
I'm receiving this error when i'm trying to create a bundle with gulp, browserify and babelify.
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'pg-native' from '[projectFolder]/node_modules/pg/lib/native'
    at [projectFolder]/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process ([projectFolder]/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir ([projectFolder]/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load ([projectFolder]/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex ([projectFolder]/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at [projectFolder]/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

I've tried all suggested solutions from here: 
https://github.com/brianc/node-postgres/issues/127 
it doesn't help. 
node v4.1.1 (npm v2.14.4)

gulp task:
```
gulp.task('buildServer', function() {
  return browserify('./server/server.js')
    .transform(babelify)
    .bundle()
    .pipe(source('server.js'))
    .pipe(buffer()) 
    // .pipe(uglify())
    .pipe(gulp.dest('./'));
});
```

**Comment by brianc** [comment]
Are you trying to bundle node-postgres into the browser?  I'm not sure that's going to work.  It relies on some compiled parts as well as `net.Socket`

**Comment by mdcsfk** [comment]
i see, my mistake. I'm working on frontend mostly, so i've didn't event noticed, that browserify does not suppose to do that. Could you suggest simple solution to bundle js files (with es6) into single file and uglify it?

**Comment by brianc** [comment]
I use webpack myself. ;)  Seriously though I am not sure about browserify,
you'd be better served looking for info somewhere else on the internet for
how to use it.

**Comment by evbo** [comment]
fyi, this fix appears in multiple issues and may be the best path forward, as of pg `8.2.1`:

https://github.com/brianc/node-postgres/issues/838#issuecomment-405646013
https://github.com/brianc/node-postgres/issues/1187#issuecomment-303770070
