### ISSUE TITLE
Newline character in query results

### ISSUE THREAD

**Issue by camsteffen** [brianc/node-postgres#905]
Currently, if query results contain a newline character, it will return as *backslash n* instead of an actual newline character. This seems like an unnecessary "feature" when JavaScript strings are perfectly capable of storing these characters.

**Comment by brianc** [comment]
We don't do any parsing of the results from postgres if they're a string other than calling `Buffer.toString('utf8')` on them...so its probably going on somewhere in your code.

**Comment by camsteffen** [comment]
oh my bad...it turns out that was the actual values I had in my database. sorry!
