### ISSUE TITLE
How do I get column names of a table?

### ISSUE THREAD

**Issue by napalm272** [brianc/node-postgres#908]
Hi, I want to get the column names of a table.  This is what I'm doing now:

``` javascript
var selectQuery = 'SELECT * FROM "' + tableName + '" LIMIT 1';
pgClient.query(selectQuery, function(err, result){
	result.fields.shift();
	var columns = _.pluck(result.fields, 'name');
})
```

Wondering if there's a better way.  Thanks!

**Comment by brianc** [comment]
http://www.postgresql.org/message-id/AANLkTilsjTAXyN5DghR3M2U4c8w48UVxhov4-8igMpd1@mail.gmail.com

**Comment by napalm272** [comment]
Thanks for the reply. Would this be faster than what I had above?

**Comment by brianc** [comment]
Not sure about faster, but it wouldn't throw an error if the table you're
looking for doesn't exist.  It's probably 6 one way 1/2 dozen the other
really.
