### ISSUE TITLE
Running multiple commands with prepared statements.

### ISSUE THREAD

**Issue by vmasto** [brianc/node-postgres#911]
Hi there,

I was wondering if it's possible to run multiple commands with prepared statements, clearly the error I'm getting says it's not, but maybe there's a workaround.

Namely the following query:

```
BEGIN;
LOCK TABLE content IN SHARE ROW EXCLUSIVE MODE;
INSERT INTO content
(id, hid, content)
VALUES (DEFAULT, ${hid}, '${content}');
COMMIT;
```

**Comment by brianc** [comment]
Nope, it's not supported by postgres

**Comment by vmasto** [comment]
Thanks!
