### ISSUE TITLE
Put the done method on the client

### ISSUE THREAD

**Issue by qimingweng** [brianc/node-postgres#914]
I was wondering why the done callback had to be separated from the returned client. Could the client just contain its own done function?

This is useful for wrapping the `pg.connect` function into a Promise.

``` js
new Promise((resolve, reject) => {
  pg.connect(string, (err, client, done) => {
    if (err) {
      return reject(err);
    }
    client.done = done;
    resolve(client);
  });
});
```

Caveat: I'm thinking putting a reference to done on the client could have some garbage collection implications.

**Comment by brianc** [comment]
You can totally do the above in your code & I encourage you to play around with which design pattern fits your style best!  As far as garbage collection is concerned I wouldn't worry too much about it.  It most cases the v8 GC is smarter enough to figure things out.

**Comment by charmander** [comment]
pg 6.x comprises a wonderful pool implementation that works well with promises and has exactly this!
