### ISSUE TITLE
Postgres Native Error Code Change

### ISSUE THREAD

**Issue by RHavar** [brianc/node-postgres#919]
Just in reply to:

> If you find yourself having to change code other than the require statement when switching from require('pg') to require('pg').native please report an issue

I recently switched to postgres native, and had to make this change:

https://github.com/moneypot/bustabit-gameserver/commit/d82a2346704e620855816a128f561a7440ff6258

Although I jumped a few version ( https://github.com/moneypot/bustabit-gameserver/commit/e2c192178a031ff55f277c3f8324f67fc7c99a13 )  so it's possible the change is more to do with pg 3.3  -> 4.3,  rather than pg native.  (Although I didn't see anything about the api change in the release notes)

**Comment by abenhamdine** [comment]
the change seems to concern the whole error object, see #938

**Comment by charmander** [comment]
The links are now dead; if the resolution to #938 didn’t fix your problem, please comment.
