### ISSUE TITLE
Prepared statements in combination with copy.to

### ISSUE THREAD

**Issue by Brutusn** [brianc/node-postgres#920]
Hello,

I like to export to csv with the copy-streams.to add-on with prepared statements. My implementation seems to work for non prepared statements (the csv is filled with the correct data). But as soon as I use a prepared statement I get empty csv files. 

How is it possible to use prepared statements in combination with the copy.to?

Ps. my current implementation were I tried several things:

In the function queryConfig is given always with a .text containing the sql. What I tried was
1.  Manually replacing the $1, $2, etc.. with the values from the .values array. This works but doesn't feel the right way to do it.
2.  Provide the values in the query() function. This doesn't work, but I could have messed up the syntax.

```
var copyTo = require("pg-copy-streams").to;
var c = new pg.Client(<connection>), stream;//, qry;
c.connect();

//// TODO Find proper solution for prepared statements and csv copyto..
//// This expects sanitized values...
//if (queryConfig.hasOwnProperty("values") && queryConfig.values.length > 0) {
//    for (var i = 0; i < queryConfig.values.length; i++) {
//        qry = queryConfig.text.replace("$" + (i + 1), "'" + queryConfig.values[i] + "'");
//    }
//} else {
//    qry = queryConfig.text;
//}

//var stream = c.query(copyTo(qry), function () {
//    c.end();
//});

// PREPARED OR NOT.
if (queryConfig.hasOwnProperty("values")) {
    // It's supposed to be a prepared statement.
    stream = c.query(copyTo(queryConfig.text), queryConfig.values, function () {
        c.end();
    });
} else {
    // Non prepared statement.
    stream = c.query(copyTo(queryConfig.text), function () {
        c.end();
    });
}

var writable = fs.createWriteStream(MKS.INSTALL_PATH + queryConfig.file);
//Insert BOM character to force proper encoding recognition in Excel for the CSV file,
writable.write("\uFEFF");

stream.on("end", function () {
    callback();
});
stream.on("error", function (err) {
    log.error(err);
});

stream.pipe(writable);
```

**Comment by charmander** [comment]
`COPY` statements don’t support parameters. I’m not sure where you’d use them in `COPY` anyway?

**Comment by Brutusn** [comment]
The parameters are used inside the select statement inside the copy. Something like:

`copy ( select * from table where id = $1 ) to csv`

**Comment by charmander** [comment]
One possible workaround is [pg-format][], then.

  [pg-format]: https://github.com/datalanche/node-pg-format
