### ISSUE TITLE
Question: one asynchronous client, several ones, pool of clients? best approach?

### ISSUE THREAD

**Issue by chemabc** [brianc/node-postgres#923]
Hi, 

Thanks for such a great piece of software. I am using it, and I have a doubt. The most of the time I only have one client that access to the database due to external events. It can be the case that two or more events occurs really fast at the same time, so they come to my server, and they ask to be inserted and then processed in the DB. Since everything is coded in nodejs and it is asynchronous, not sure if I can assume it is really one client, or they are different ones making asynchronous requests to the pg module. 

My question is: which would be the right approach to access the database?
Right now I am using a pool of clients, but not sure if this is the fastest and best way of doing it. To illustrate it: everytime I got a message from a TCP socket (which initiates the actions to the database) I execute 'doQuery' function. Not sure if this is the best approach (although it works):
```nodejs
var doQuery = function(_query, callback){
  pg.connect(dbConfig, function (err, client, done){
    if(err){
      err.msg += "** [doQuery] ERROR when connecting via pool";
      callback(err);
    }
    client.query(_query, function(err, result){
      if(err){
        err.msg += '** [doQuery] ERROR doing query: ' + _query;
        callback(err);
      }
      if(result){
        done(); // client idles for 30 seconds before closing
        callback(err, result.rows);
      }else{
        done(); // client idles for 30 seconds before closing
        callback(err, null);
      }
    });
  });
};
```

Thanks a lot!

**Comment by brianc** [comment]
Using a pool is the right way to go.  There is minimal overhead. Every
connection to postgres takes a lot more time to set up than to send a
query, and postgres is usually limited to a few hundred simultaneous max
connections in total from all apps. So - keep on with the pool! :thumbsup:

**Comment by chemabc** [comment]
Great Brian! I keep it then. 
Thanks really a lot :)

**Comment by brianc** [comment]
no problemo!
