### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by tanzim** [brianc/node-postgres#924]
Hi,
I had a few question about the library and I hope this is the right place to ask.

Firstly, is it possible to do nested array expansion like node-mysql in node-postgres? Nested expansion is very handy for doing things like inserting rows using one SQL statement (bulk insert) without having to resort to generating SQL statements manually. See https://github.com/felixge/node-mysql#escaping-query-values.

Secondly, how does BIGNUM handling work with the library? In node-mysql, turning on `supportBigNumbers` has the nice effect of returning numbers up to +2^53 as number which is practically all you need. And for safety all the time, BIGNUMBERS can be returned as strings always as a matter of choice too.

Cheers.

**Comment by rpedela** [comment]
1. For advanced escaping, I suggest [pg-format](https://github.com/datalanche/node-pg-format) which I wrote. It doesn't currently handle nested arrays but you can open an issue or make a PR.

2. By default, numeric and bigint are returned as strings. I don't know if there is a flag (there might be), but you can override the default type parser.

```js
var pg = require('pg');

// numeric
pg.types.setTypeParser(1700, function (value) {
    return parseFloat(value);
});

// bigint
pg.types.setTypeParser(20, function (value) {
    return parseInt(value);
});
```

**Comment by tanzim** [comment]
Closing this since 
 1. Has been solved with https://github.com/datalanche/node-pg-format/pull/2
 2. Fair enough. Will do for now.
