### ISSUE TITLE
Question on multiple queries in single client?

### ISSUE THREAD

**Issue by rdkgit** [brianc/node-postgres#929]
Hi!

New to Node programming and trying to do something like this (pseudocode)

pg.connect
   for (i=0; i<someNumber; i++) {
        client.query(insert row into table)
   }
   done after all the client queries

I don't know how many rows I will insert a prior as it depends on lots of factors.  I get the async nature of node and the pg library.  Whats the best way to do this?  Sorry if this is really a node question and not a pg question.

Thanks,

Bobby

**Comment by RHavar** [comment]
Yeah, this is more of a general javascript question. But the answer you're looking for is a library like:
https://github.com/caolan/async

which is a library that helps with control flow for async functions like this

**Comment by rdkgit** [comment]
Thanks for the reply.  I was coming to that conclusion.   I am reading about it and re-reading the Node book I have.  I'm still having trouble wrapping my head around what an async call for this would look like?

How would an async style module help with an invocation to pg client.query where we have an undetermined number of inserts that we'd like to finish before we call done()?  Perhaps some psuedo code?

Thanks,

Bobby

**Comment by rdkgit** [comment]
I think I found an answer to a similar question that is applicable to me.

https://github.com/brianc/node-postgres/issues/530

Thanks,

Bobby

**Comment by RHavar** [comment]
Here's the more general solution (note: I haven't actually run this)

```
var async = require('async'); // make sure to npm install this
var values = [1, 2, 3, 4, 92, 23, 2342, 234]; // these are what i want to insert in the db
var sql = 'INSERT INTO table(x) VALUES($1)'

// Let's transform the values into an array of async functions
var tasks = values.map(x => function(callback) {
     client.query(sql, [x], callback);
});

// Let's run 3 of the tasks at a time
async.parallelLimit(tasks, 3, function(err, res) {
    console.log('All done! Got err: ', err, ' and result: ', res);
});
```

Things to note: if you're using the same pg connection, even though async is firing 3 in parallel they will run in series anyway.  If you're just using doing multiple inserts, the solution from #530 will run *way* faster. But the way I showed you is more general (i.e. it's just general async control flow)





```

**Comment by rdkgit** [comment]
Hey!  Thanks!

I was thinking a lot this topic on my afternoon hike today.  Basically, my challenge is I don't know a prior how many rows I'm going to have so hardcoding async patterns would be tough.  What if I kept a counter of number of callbacks and when that number equaled the number of rows, I then called done() ?  Something like:

  pg.connect

     numRows = input from json object in request
     numCallbacks = 0;
     for (i=0; i<numRows; i++) {
           client.query(insert statement, function(err,result) {
                    numCallbacks++;
                    if (numCallbacks == numRows) {
                       done();
                   }
           });
    }

Would this work with node, pg, and its async nature?

Thanks,

Bobby

**Comment by RHavar** [comment]
Yes, this is exactly how you do it (if you want to fire them all in parallel), you just need to handle errors.

But you're far better off using `async.parallel` which is a library that abstracts this for you. (If you look at the source code, you'll see it works basically exactly how you tried)

**Comment by rdkgit** [comment]
Hi!

Thanks!!  I don't mind firing parallel.  I'll go look more at async.  I need to figure it out anyway as I'm sure I'm going to want to use it down the road.

Thanks,

Bobby

**Comment by NumminorihSF** [comment]
Hello.

You use 1 Client instance, so queries will not run paralel. 2nd will start, then 1st will recieve result.
So last will end only after another are finished.

Async lib just wrap multiple async function calls to more comfortable usage.

Also, you can use Promise (es2015).

**Comment by rdkgit** [comment]
Hi!

I read over and monkeyed with async.each which I think better matches my application semantics.  I don't need to do the inserts in parallel and performance is not a big deal yet.  async.each can take an array of items so that matched my application well.  Here is the rought pseudo-code.

Thanks,

Bobby

pg.connect(pgConnectString,function(err,client.done)
{
    async.each(items,function(sample,callback) {
        client.query("INSERT INTO . . . .",[item vals],function(err,result) {
               if (err) . . . callback(err)
               else callback();
        });
    },
    // function executed when all each items completed
    function(err)
    {
          done(); // close DB client connection
    }
  );



}
