### ISSUE TITLE
readme suggests done() which is incorrect

### ISSUE THREAD

**Issue by phillip-haydon** [brianc/node-postgres#930]
On the readme, it says to call `done();`

Following this, 3 times I managed to exhaust all database connections. The link under the example suggests `done(client);` which correctly closes the connection.

I think this is a possible documentation error.

---

Basically we need the connection timeout handler to live in a separate process to make the lambda function freezable. That should solve the termination timeout issue (in theory).

How lambda handles re-use is described here in detail:
https://aws.amazon.com/blogs/compute/container-reuse-in-lambda/
Pay attention to the last section in particular.

**Comment by brianc** [comment]
where exactly in the readme is there an error? calling done() without
passing it any arguments is the correct way to return clients to the
connection pool. if you are exhausting your pool it is likely you are
forgetting to call done somewhere?

**Comment by phillip-haydon** [comment]
I only have 2 queries total in node, and both queries are the same shown in the activity, no other code queries those 2 tables.

Both were only using `done();`, the only thing I changed was pass in the client, `done(client);` and the problem went away. I can see it in the activity, before change if I touched the url, the connections would pile up and never leave. After the change they show and disappear pretty much immediately.

**Comment by brianc** [comment]
If you pass a truthy value to `done()` it will close the client.  You might not want to do that because you aren't really using a pool if you close the client every time you run a query.  Can you share a code sample so I can look at it?  Otherwise I can't really help...I just double-checked and the code in the readme is 100% correct in the way its calling done.

**Comment by phillip-haydon** [comment]
Yup sure.

This runs in an AWS Lambda, it checks to see if the token exists, then calls a bunch of web services (removed) then inserts the result.

This is called using run-waterfall library.

https://www.npmjs.com/package/run-waterfall

```
        function(args, callback) {
            pg.connect(connectionString, function (err, client, done) {
                console.log('Querying the Token to check user is authenticated');
                client.query('SELECT * FROM token WHERE token = $1', [args.token], function(err, result) {
                    done(client);

                    if (err || result.rows.length === 0) {
                        return callback(new Error("Token is invalid."));
                    }

                    return callback(null, args);
                });
            });
        },
        // Snipped a bunch of 3rd party requests for data

        function(args, callback) {
            pg.connect(connectionString, function (err, client, done) {
                console.log('Insert the suggestions');
                client.query('INSERT INTO mt_doc_album ("data") VALUES ($1)', [JSON.stringify(args.suggestions)], function(err, result) {
                    done(client);

                    if (err) {
                        return callback(err);
                    }

                    return callback(null, args);
                });
            });
        },
```

**Comment by brianc** [comment]
Yeah calling `done(client)` up there is gonna disconnect the client immediately after the query.  You _can_ do that but you lose the advantage of using a pool at all.  The reason to use a pool is because the overhead of establishing a connection to postgres initially is 20x as much work as dispatching a single query.  I'd remove the `client` argument and just call `done()` - it wont close the connections to postgres right away (by default there's a 1 minute timeout) but it wont open more than `pg.defaults.poolSize` connections either - it will reuse them.  The default pool size is 20.  

One thing I can see is I'm not sure exactly how aws lamda works.  If every instance of a lambda script spins up its own worker process then each worker process will have its own pool, so you can end up with `number-of-workers * 20` connections to postgres which might be too many.  Depending on your database resources you *will* eventually exhaust connections - in my experience I try to keep connections to under 200.  In this situation you can either reduce the pool size for each worker: `pg.defaults.poolSize = 2` which will get you past the hump.  Regardless of poolSize if you have __enough__ requests simultaneously to lambda you will exhaust your connections - bascially if your lamda process group size is unbounded you have to have a way to funnel your queries through some more bounded endpoint....there is also `pgbouncer` but I've had bug reports on it from time to time - YMMV.

Hope this was helpful.

**Comment by phillip-haydon** [comment]
Ahh ok. 

Then what is happening would be correct, to disconnect the client immediately. 

Lambda's are small containers that are deployed and your piece of code is executed against, exists for short period of time. Once that piece of code is executed the process is killed. There's nothing to share the client with to pool a connection. 

So if I was using express I would just call `done();` which would close the current connection but keep it in the client for pooling.

Thanks for clearing that up :heart:

**Comment by brianc** [comment]
awesome! so glad we got that figured out! extra glad because i was gonna
start fiddling with lamda soon. :smile:

**Comment by lukas-gitl** [comment]
Thanks, this helped me a lot!

@phillip-haydon @brianc According to the AWS documentation you would expect the pool to persist between different lambda runs (not guaranteed). And then you wouldn't have to destroy the client.

I suspect this has something to do with the timeout of the reap function. It somehow prevents the thread from sleeping even though the lambda context has been closed (??). Very weird. Here is a related thread on the aws forums: https://forums.aws.amazon.com/thread.jspa?threadID=216000

I'm wondering if we can do something in this library. Can we solve idle connection killing differently than with a timeout? Something that doesn't block the lambda function?

**Comment by lukas-gitl** [comment]
After thinking about this more, I'm re-opening this as a feature request:
Basically we need the connection timeout handler to live in a separate process to make the lambda function freezable. That should solve the termination timeout issue (in theory).

How lambda handles re-use is described here in detail:
https://aws.amazon.com/blogs/compute/container-reuse-in-lambda/
Pay attention to the last section in particular.

**Comment by phillip-haydon** [comment]
We shall await @brianc's statement on this.

**Comment by lukas-gitl** [comment]
I think I finally figured out what is happening: 
https://aws.amazon.com/blogs/compute/node-js-4-3-2-runtime-now-available-on-lambda/
Take a look at "Node callbacks". Let me test this and confirm that this actually solves the issue!

**Comment by lukas-gitl** [comment]
Yep, setting context.callbackWaitsForEmptyEventLoop = false; seems to resolve this.

Can you confirm @brianc ?

**Comment by Vanuan** [comment]
This should be documented.
I'm using pool because there's no way to provide a connection string when using raw pg client.

**Comment by lukas-gitl** [comment]
_Final Note for now:_
We stopped using connection pooling. Amazon handles this very badly. Basically we now always call `client.release(true)` to terminate any connection.

This will be best practice until Amazon improves their container handling with Lambda. If you don't do this you are dealing with all sorts of issues (one is that many open connections are just sticking around).

**Comment by benoittgt** [comment]
Thanks @lukas-gitl for this statement. I'm not using lambdas but I would like to know if it's possible to deal with "connection sharing" across lambda invocations.

I have a simple lambda like this one : 
```javascript
'use strict';
const config = require('./config');
const pg = require('pg');

// PG connection pool, max connections = config.max
const pool = new pg.pool(config);

// Lambda Handler
exports.handler = function (event, context) {
    // query
    const query = `REFRESH MATERIALIZED VIEW CONCURRENTLY ${event.table_name};`;

    // use a connection from pool 
    pool.connect(function (err, client, done) {
        if (err) {
            // connect error
            return context.fail(`Falied to connect to database: ${err}`);
        } else {
            // connected, run query
            client.query(query, function (err) {
                // release connection to pool
                done();

                // handle query result
                if (err) {
                    return context.fail(`Falied to run database query: ${err}`);
                } else {
                    return context.succeed(`Successfully Refreshed.`);
                }
            });
        }
    });
};
```
But the connection is made inside the handler function. I would like to move it outside to follow this advice: 
> Instantiate AWS clients and database clients outside the scope of the handler to take advantage of connection re-use.
But if I do it I will loose error management ? 
Thanks

**Comment by lukas-gitl** [comment]
@benoittgt No, you're not loosing error mgm. You are still doing the connecting inside the lambda function. The variable just lives outside. E.g. you could have a boolean check flag `isConnected`.

**Comment by benoittgt** [comment]
Thanks @lukas-gitl. Will probably give a try with something similar to what [Pratik J.](https://github.com/sequelize/sequelize/issues/4938#issuecomment-245211042) said then.

```javascript
var dbConnection;

exports.handler = function(event, context){
if(!dbConnection){
//init db connection
}
//otherwise reuse the connection
};
```

**Comment by ck7m** [comment]
This thread was incredibly useful. I had exact same issue. Couple of things for the people using pg module with lambda.
Note: I didn't use connection pool as it is not useful with lambda.

1. Create Client and Connection as local variable not as global
    `var client = new pg.Client(connectionString);`
2. Call the `client.end()` before calling context.done or callback

**Comment by BardiaAfshin** [comment]
I'm using lambda to kick off COPY statement in RedShift, using this module. The load is longer than 5 minutes and it's timing out and terminating the query.

I tried using pg.Pool thinking client.query will fire and forget , not wait for the result

BUT as soon as the end of my lambda function is reached, the connection goes away and the query terminates. Help?

```javascript
  var sql = "COPY.......";

  console.log('SQL ===> '+sql);
  client.query(sql);
  client.end();
  console.log('query executed!');
```

**Comment by BardiaAfshin** [comment]
@benoittgt so anything you define outside of your exports.handler will live on?

**Comment by charmander** [comment]
To address the original comment here: if you always close clients after using them, there’s no point in having a pool. The pool is there to keep clients connected and available for reuse. If you want to close a pool after releasing all of its clients, use `pool.end();`.

@BardiaAfshin `client.end()` will disconnect the client. If you don’t want that to happen, don’t call it.

**Comment by benoittgt** [comment]
@BardiaAfshin I'm using pg-promise now so can't tell you

@charmander Thanks for the additional infos.
