### ISSUE TITLE
An enum array is returned inconsistently

### ISSUE THREAD

**Issue by RHavar** [brianc/node-postgres#944]
Fetching an enum array is parsed like `"{cat,dog}"` ( a string), while fetching a text array is parsed as `["cat", "dog"]` (an array of strings). 

I think the latter behavior is preferable for an enum array

Originally was reported as #691 but closed due to poster finding a work around

**Comment by brianc** [comment]
This would be an issue better handled in [node-pg-types](https://github.com/brianc/node-pg-types)
