### ISSUE TITLE
Row accumulator event behaves differently with pg-native

### ISSUE THREAD

**Issue by hampelm** [brianc/node-postgres#953]
The wiki has [this example](https://github.com/brianc/node-postgres/wiki/Query#examples) for using the `row` event to accumulate rows in a `results` object. It works as expected with `pg`, but when using `pg-native`, the results object starts out as the full list of results and does not change. 

I'm using `pg` 4.5.1 and `pg-native` 1.10.0. I'm upgrading from much earlier versions of the two libraries, where the code worked as expected. The change may be entirely intentional, but I didn't see a reference to it in the documentation. 

Here's a snippet to show the two behaviors, changing only the require statement to from `require('pg')` to `require('pg').native`:

```
    var query = client.query('select * from sample limit 10');
    query.on('row', function(row, result) {
      console.log("Length", result.rows.length);
      // When run with pg, result.rows.length will start at 0 and count up (expected)
      // When run with pg-native, rows.length will start at 10
      result.addRow({ hello: "world" });
    });
    query.on('end', function(result) {
      // With pg, result will be an array of 10 "hello world" objects (expected)
      // With pg-native, result will be the original result
    });
```

**Comment by charmander** [comment]
As of pg 7, `query` no longer returns a query object by default.
