### ISSUE TITLE
How to insert multiple rows with a single query?

### ISSUE THREAD

**Issue by zettam** [brianc/node-postgres#957]
I have `n` number of items. I would like to add them all with a single insert query.

`insert into testtable(id,name) values (1,"jack"),(2,"john"),(3,"jill");`

I have an array for my rows, and I like to add them all in. So, if I provide `pg` the correct string (after manually forming it in a variable) it works perfectly fine, but this all seemed a bit pointless to me. I expect pg to handle arrays for me as well, but I'm unable to find the option for that. So I'm asking, is this possible?

How can I insert multiple rows from an array of rows, with a single insert query with this library?

Would love to know. Thank you.

**Comment by vitaly-t** [comment]
No such thing supported. This is not an ORM, this library just executes queries.

**Comment by zettam** [comment]
hm, okay.
What's the best way to handle this situation in this case? Sending multiple queries is pretty costy hen you can do the same with a single query.

**Comment by vitaly-t** [comment]
You can concatenate your inserts. However, since this library doesn't provide a separate query formatting, you can't really do it correctly.

You can do it with [pg-promise](https://github.com/vitaly-t/pg-promise) though. Article [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost) should echoes all your concerns nicely.

**Comment by langpavel** [comment]
Prepare your insert statement

**Comment by rpedela** [comment]
Using [pg-format](https://github.com/datalanche/node-pg-format) with a nested array:

```js
var format = require('pg-format');

var values = [
    [ 1, 'jack' ],
    [ 2, 'john' ],
    [ 3, 'jill' ],
];
console.log(format('INSERT INTO test_table (id, name) VALUES %L', values));
// INSERT INTO test_table (id, name) VALUES ('1', 'jack'), ('2', 'john'), ('3', 'jill')
```

Disclaimer: I wrote [pg-format](https://github.com/datalanche/node-pg-format).

**Comment by awenger** [comment]
You could also do something like:
```
var query = 'INSERT INTO table (SELECT (data->>'c1')::int, (data->>'c2')::text FROM (SELECT json_array_elements($1::json) AS data) tmp)'
var data = JSON.stringify([{c1: 1, c2: 'text1'},{c1: 2, c2: 'text2'}])

client.query(query, [data], ...)
```

Formatted version of the query:
```
INSERT INTO table (
  SELECT 
    -- extract the props from the json object so that they match the table cols
    (data->>'c1')::int, (data->>'c2')::text
  FROM (
    -- expand the json array
    SELECT json_array_elements($1::json) AS data
  ) tmp
)
```

**Comment by joskuijpers** [comment]
@zettam Did any of the above solve the problem for you?

**Comment by mrxgodfather** [comment]
You can user this  plugin https://www.npmjs.com/package/mysql-insert-multiple

**Comment by charmander** [comment]
@x0days That’s for MySQL, not PostgreSQL.

@zettam:

```js
pg.query(
    "INSERT INTO testtable (id, name) SELECT * FROM UNNEST ($1::int[], $2::text[])",
    [
        [1, 2, 3],
        ["Jack", "John", "Jill"],
    ]
)
```

**Comment by barbu110** [comment]
> This is not an ORM, this library just executes queries.

You don't need an ORM for that. PostgreSQL supports this natively, as stated in [their docs](https://www.postgresql.org/docs/9.6/static/sql-insert.html)

```sql
INSERT INTO films (code, title, did, date_prod, kind) VALUES
    ('B6717', 'Tampopo', 110, '1985-02-10', 'Comedy'),
    ('HG120', 'The Dinner Game', 140, DEFAULT, 'Comedy');
```

**Comment by bloodorca** [comment]
```js
const videos = [["Peru is a nice country.", "limaGuy"], ["Breaking bad is a great show.", "mikeGuy"], ["I like the winter.", "novemberGuy"]]
```

Since Postgres supports multi-record inserts using syntax. 
```sql 
 INSERT INTO videos (title, author) VALUES 
    ('Peru is a nice country.', 'limaGuy'), 
    ('Breaking bad is a great show.', 'mikeGuy'), 
    ('I like the winter.', 'novemberGuy'); 
```

I wrote a helper function called expand.

```js 

expand(3, 2) // returns "($0, $1), ($2, $3), ($4, $5)" 



Here is a helper function I wrote called expand(). 

// expand(3, 2) will return "($0, $1), ($2, $3), ($4, $5)"


var videos = [["Peru is a nice country.", "limaGuy"], ["Breaking bad is a great show.", "mikeGuy"], ["I like the winter.", "novemberGuy"]]

Query(`INSERT INTO videos (video_name, video_author) VALUES ${Expand(videos.length, 2)}`, Flatten(videos))



```

**Comment by bloodorca** [comment]
Since Postgres supports multi-record inserts using syntax. 
```sql 
 INSERT INTO videos (title, author) VALUES 
    ('Peru is a nice country.', 'limaGuy'), 
    ('Breaking bad is a great show.', 'mikeGuy'), 
    ('I like the winter.', 'novemberGuy'); 
```

I wrote a helper function called expand.

```js 
// expand(3, 2) // returns "($1, $2), ($3, $4), ($5, $6)" 
function expand(rowCount, columnCount, startAt=1){
  var index = startAt 

  let rows = []
  for (let r = 0; r < rowCount; r++){
    let columns = []
    for (let c = 0; c < columnCount; c++){
      columns.push("$".concat(index)) 
      index++ 
    }
    rows.push(`(${ columns.join(", ") })`)
  }
  return rows.join(", ")
}
```

```js
const videos = [["Peru is a nice country.", "limaGuy"], ["Breaking bad is a great show.", "mikeGuy"], ["I like the winter.", "novemberGuy"]]

Query(`INSERT INTO videos (title, author) VALUES ${expand(videos.length, 2)}`, videos.flatten())
```

The query ends up being. "INSERT INTO videos (title, author) VALUES ($1, $2), ($3, $4), ($5, $6)"

Flatten just flattens an array. [[1, 2], [3, 4], [5, 6]] -> [1, 2, 3, 4, 5, 6]

**Comment by ZiaDev** [comment]
You can use this package https://www.npmjs.com/package/pg-essential. You just need to call it's executeBulkInsertion function like

**Comment by nhevia** [comment]
> I wrote a helper function called expand. It creates the query placeholders.
> 
> ```js
> // expand(3, 2) returns "($1, $2), ($3, $4), ($5, $6)" 
> function expand(rowCount, columnCount, startAt=1){
>   var index = startAt
>   return Array(rowCount).fill(0).map(v => `(${Array(columnCount).fill(0).map(v => `$${index++}`).join(", ")})`).join(", ")
> }
> 
> // flatten([[1, 2], [3, 4]]) returns [1, 2, 3, 4]
> function flatten(arr){
>   var newArr = []
>   arr.forEach(v => v.forEach(p => newArr.push(p)))
>   return newArr
> }
> ```

This is great.
Since ES6 you can use Array.prototype.flat() instead of the `flatten` function

```javascript
const arr = [[1, 2], [3, 4]]
console.log(arr.flat()) // [1, 2, 3, 4]
```

**Comment by mymirai-nikki** [comment]
> You could also do something like:
> 
> ```
> var query = 'INSERT INTO table (SELECT (data->>'c1')::int, (data->>'c2')::text FROM (SELECT json_array_elements($1::json) AS data) tmp)'
> var data = JSON.stringify([{c1: 1, c2: 'text1'},{c1: 2, c2: 'text2'}])
> 
> client.query(query, [data], ...)
> ```
> 
> Formatted version of the query:
> 
> ```
> INSERT INTO table (
>   SELECT 
>     -- extract the props from the json object so that they match the table cols
>     (data->>'c1')::int, (data->>'c2')::text
>   FROM (
>     -- expand the json array
>     SELECT json_array_elements($1::json) AS data
>   ) tmp
> )
> ```

is there any explanation why you use `tmp` as alias when it's not used anywhere?

**Comment by charmander** [comment]
> is there any explanation why you use `tmp` as alias when it's not used anywhere?

@mymirai-nikki

```sql
SELECT FROM (SELECT);
```

> ERROR:  subquery in FROM must have an alias

**Comment by mymirai-nikki** [comment]
> > is there any explanation why you use `tmp` as alias when it's not used anywhere?
> 
> [@mymirai-nikki](https://github.com/mymirai-nikki)
> 
> SELECT FROM (SELECT);
> 
> > ERROR:  subquery in FROM must have an alias

I tried without `tmp`:
```sql
INSERT INTO registered_groups
SELECT (data->>'periode')::text, (data->>'group_id')::int, (data->>'user_id')::int FROM (SELECT json_array_elements($1::json) AS data)
ON CONFLICT (periode, group_id, user_id) DO NOTHING
```

and no error occurred?

**Comment by charmander** [comment]
@mymirai-nikki Ah, [that requirement was dropped in PostgreSQL 16](https://www.postgresql.org/docs/16/release-16.html#RELEASE-16-GENERAL).
