### ISSUE TITLE
Possible BUG - When using parameters ($1) with redshift it returns an error

### ISSUE THREAD

**Issue by ilaif** [brianc/node-postgres#960]
Hey,

I've been using this package successfully for querying _Redshift_. Then I implemented parameterizing to increase security and ran into the following error:

> {
>   "name": "error",
>   "length": 138,
>   "severity": "ERROR",
>   "code": "XX002",
>   "file": "/home/awsrsqa/padb/src/pg/src/backend/access/nbtree/nbtpage.c",
>   "line": "170",
>   "routine": "_bt_getroot"
>   "message": "index "sessions_pkey" is not a btree"
> }

The query fails on parameterizing a date like so:

``` sql
SELECT * FROM sessions WHERE start_date BETWEEN $1 AND $2;
```

``` js
params = ['2016-03-06', '2016-03-06']
```

`pg version: ^4.5.1`

Did anyone run into this? The error doesn't sound related to the problem.

**Comment by vitaly-t** [comment]
Are you running it on Linux?

I have tried it here on Windows 10, and it just works.

**Comment by tonylukasavage** [comment]
I've also been running parameterized queries from both Mac OSX and AWS AMI boxes targeting Redshift and have had no issues. Is it _all_ parameterized queries that are causing a problem for you, or just this particular instance? You might also want to determine, as @vitaly-t noted, whether or not it's specific to handling dates.

**Comment by charmander** [comment]
This is probably not a driver problem.
