### ISSUE TITLE
Column alias in join query

### ISSUE THREAD

**Issue by damianobarbati** [brianc/node-postgres#962]
A simple query like:
`select * from vertices v1, vertices v2`
return a set of rows with fields overwritten.
How do I get properly prefixed fields in rows objects for join queries?
I'm probably missing something easy here.

**Comment by vitaly-t** [comment]
You get exactly what PostgreSQL returns in this case, it got nothing to do with this library.

**Comment by damianobarbati** [comment]
Oh I finally see. I was sure there could be a way to prefix the columns in the result set with the table alias, my bad!
