### ISSUE TITLE
Expand parameterized query

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [brianc/node-postgres#964]
Say I have this query:

``` js
 var query = client.query({
      text: 'SELECT name FROM users WHERE email = $1',
      values: ['brianc@example.com']
    });
```

Is there any way to have it "expanded" and get the following sql query **string**?

``` js
var sql = pg.expand(query); // a method I'm asking for
// sql = 'SELECT name FROM users WHERE email = 'brianc@example.com';
```

I know I can do it myself (by replacing $x items with those from a values array - taking care whether I should quote value string or not etc.), but I'm asking whether `node-postgres` already offers such solution?

**Comment by vitaly-t** [comment]
The purpose of Prepared Statements is to separate parameters from the query, to allow the PostgreSQL server format the query, thus preventing SQL injection and optimizing the execution plan.

Only the server knows what the actual result will be, you cannot assume it on the client side, as this would defeat the purpose of safety (against SQL injection).

This is why this library does not make that assumption, it processes Prepared Statements as it is supposed to, by passing the data further into the server to format the data.

Having said so though, it is fairly easy to counteract SQL injection on the client side, by following certain rules of query formatting. You won't find such approach within this library, but some derivative works provide their own query formatting layer with consideration for safe query formatting.

For example, in my own library, [pg-promise](https://github.com/vitaly-t/pg-promise), I implemented special syntax extensions to allow safe query formatting, such as [SQL Names](https://github.com/vitaly-t/pg-promise#sql-names). And I did a separate query formatting engine that can be and is successfully used on its own whenever needed. But that's miving the safety of queries into the client side, which is only safe if you pay attention to it, and use as supposed to.

With Prepared Statements, however limited they are, in terms of the query formatting, they are more fool-proof, you can't make a mistake or else they won't work.

There is even one more approach to it, some libraries even use a ported from PostgreSQL library to formatted queries exactly as it happens within the prepared statements. I can't remember it by name at the moment, unfortunately.

**Comment by ktrzeciaknubisa** [comment]
@vitaly-t Thank you for your extensive elaboration :) My current need is very trivial: when I get an error of e.g. `SELECT $1 FROM XXX` I would like to know what is $1 in there. Of course that's just one simple example :)

**Comment by vitaly-t** [comment]
You can't do it with the basic Prepared Statements, it would have to be a higher level, supported by the library. This library doesn't do it. All I know, pg-promise does this, via a generic error reporting, where the values passed are reported.

If you are talking about a select few queries, you can log parameters manually there for each, otherwise you would need to use a different library.

**Comment by rpedela** [comment]
I wrote [pg-format](https://github.com/datalanche/node-pg-format) which you could probably use for this.

```js
var format = require('pg-format');
console.log(format('SELECT name FROM users WHERE email = %L', 'brianc@example.com'));
// SELECT name FROM users WHERE email = 'brianc@example.com'
```

**Comment by vitaly-t** [comment]
This question has an answer to it: http://stackoverflow.com/questions/36101141/postgresget-executable-query-from-query-with-parameters
