### ISSUE TITLE
Wiki Example inserts multiple "visit" records per http request

### ISSUE THREAD

**Issue by nelsonic** [brianc/node-postgres#966]
Hi @brianc & @DaAwesomeP,

Trying the code from the Wiki Example: https://github.com/brianc/node-postgres/wiki/Example
we note that *each time* an http request is made, ***two*** records are inserted into the visit table...

We [modified a couple of lines](https://github.com/dwyl/postgres-connection-pool-test/blob/e7f79dcf034a8e2487a12809ac06173ed2da35bc/server.js) in `server.js` to make the example run on Heroku so you can see the issue in *action*: 
> https://node-postgres-example.herokuapp.com/
>  try it in **Google Chrome** ... *each* time you refresh the page you will see the count go up by *two*...

We don't *think* this is the ***desired behaviour***... @brianc can you please confirm? (*thanks*!)

Note: Also created StackOverflow question: http://stackoverflow.com/questions/35970724/why-does-node-js-postgres-wiki-example-insert-multiple-records-per-http-request (*in case others have come across this issue and want some SO points for answering...*)

**Comment by nelsonic** [comment]
Closing as this is a Google Chrome issue. (*Chrome makes two requests to the server, one for the content, the other for the favicon...*)

**Comment by DaAwesomeP** [comment]
@nelsonic Just wondering...but why was I cc'd on this?

**Comment by nelsonic** [comment]
@DaAwesomeP apologies. you were CC'd because you were the last person to update the [Wiki page](https://github.com/brianc/node-postgres/wiki/Example) 
![node-postgres-wiki-page](https://cloud.githubusercontent.com/assets/194400/13731245/4ba341ca-e95c-11e5-9345-6bacb4ea211a.png)

and I hoped you would be able to help. turns out it was a Google Chrome issue, 
again sorry for bugging you. :+1:

**Comment by DaAwesomeP** [comment]
No problem!
