### ISSUE TITLE
Docs: document use of pg.defaults.parseInt8

### ISSUE THREAD

**Issue by abenhamdine** [brianc/node-postgres#968]
Hi @brianc.
I think the wiki is not explicit enough on the default value and the behavior of pg.defaults.parseInt8, see
https://github.com/brianc/node-postgres/wiki/pg#pgdefaultsparseint8

Would you mind if I edit the wiki in order to : 
- explicit the default value (false if i'm right)
- add a link to https://github.com/brianc/node-pg-types, for folks who don't want to use this shortcut, and see how to specify their own type parsers

**Comment by abenhamdine** [comment]
The wiki is no longer there, but the option is still alive : 
https://github.com/brianc/node-postgres/blob/e087305f316b364bdbd3045f5c5339b80f757174/lib/defaults.js#L66-L70

It should be documented in new docs : https://node-postgres.com

**Comment by charmander** [comment]
The option is gone now, with the documentation for people who want to change the default at https://node-postgres.com/api/types/ → https://github.com/brianc/node-pg-types.

`int8` parsing selection might be made explicit to accommodate `BigInt`s soon too.

**Comment by rdsedmundo** [comment]
> The option is gone now

That doesn't seem to be true, latest on `master`. I confirmed on my side that the option still works as well.

https://github.com/brianc/node-postgres/blob/373093d176f0ceb0266333680b20d0acf38004e3/packages/pg/lib/defaults.js#L80-L84
