### ISSUE TITLE
rowCount is available in callback result of Client.query, why no document on it?

### ISSUE THREAD

**Issue by aleung** [brianc/node-postgres#973]
In document of [`Client.query`](https://github.com/brianc/node-postgres/wiki/Client#method-query-simple), it describes:

> object **result**:
> - and object containing the following properties:
> - array **rows**:
>   - an array of all rows returned from the query
>   - each row is equal to one object passed to the Query#row callback

Source code and test shows that the result object here is actually the same as the result object in Query's [end event](https://github.com/brianc/node-postgres/wiki/Query#end). It has the following properties:

> - command: The sql command that was executed (e.g. "SELECT", "UPDATE", etc.)
> - rowCount: The number of rows affected by the SQL statement (more information)
> - oid: The oid returned
> - rows: An array of rows (if the addRow command is used)

Why the other properties beside `rows` are **NOT** documented in `Client.query` callback?

I ask this question because I need to check `rowCount` after an UPDATE query. I wanna to make sure it's safe to read `result.rowCount` from the `Client.query` callback.

**Comment by vitaly-t** [comment]
It is safe, the property is always there: https://github.com/brianc/node-postgres/blob/master/lib/result.js#L8

**Comment by aleung** [comment]
Modified the wiki to improve document.
Please review: https://github.com/brianc/node-postgres/wiki/Client/_compare/19fa8ad8b7e046ba56eb7617569b6a3e1dcf2eb1...cc0ebcde047d70086585d996386975d76e3f8dc6
