### ISSUE TITLE
Possible issue with PostgreSql 9.5's UPSERT

### ISSUE THREAD

**Issue by stanislasdrg** [brianc/node-postgres#974]
Hello everybody, I am having an issue with a very simple query, using ON CONFLICT DO UPDATE.

Here is my code : 

```
var package_name_id;

client.query("INSERT INTO package (package_name) 
VALUES($1) 
ON CONFLICT (package_name) 
DO UPDATE SET package_name = package.package_name 
RETURNING package_name_id",[apps[j].appId], function(err, result) {

package_name_id = result.rows[0];
                                                      
//call `done()` to release the client back to the pool
done();
if(err) {
return console.error('error running query', err);
}
}); 
```

The package table only has two columns : an auto-incremented package_name_id and a package_name. For some reason the script crashes when I try to access the result, which is undefined.
If I remove the ON CONFLICT part, everything runs smoothly. Has anybody encountered such an issue ?

Cheers,

Stanislas.

**Comment by odini** [comment]
Hi Stanislasdrg. I run in the same problem. Did you actually find a work around for that?

**Comment by stanislasdrg** [comment]
Hi Odini,
yes I did, but not the way you'd expect. I used the excellent pg-promise library instead. 
I am not a huge fan of callbacks, especially since I had many chained queries to do.
The support from the author on Github and S.O has been top-notch. I can only recommend it.

**Comment by odini** [comment]
Hi again,
I actually catch the error code and perform update. Not the nicest solution as well but working fine. I have 2 parameterised queries one does insert and if it gets code 23505 it does update. I was hoping for a neater UPSERT implementation.
