### ISSUE TITLE
How I can have two different connection pools for two different databases?

### ISSUE THREAD

**Issue by alekbarszczewski** [brianc/node-postgres#975]
It is possible to set pool size in `pg.defaults`. However let's say I have two databases and two separate connection strings for them:

```
postgres://localhost/db1
postgres://localhost/db2
```

And I want to have two different pool sizes for each of them. For example max 20 connections for db1 and max 100 connections for db2. How I can do that? Changing pool size in pg.defaults will set it globally...

**Comment by rpedela** [comment]
I don't think it is supported. I recommend using [pgbouncer](https://pgbouncer.github.io/) for connection pooling. It is more flexible, faster, mature than the node-postgres connection pooling. There are [other options](https://wiki.postgresql.org/wiki/Replication,_Clustering,_and_Connection_Pooling) too from the Postgres community. If you use [pgbouncer](https://pgbouncer.github.io/), then you can open/close single connections in your JS code without any significant performance penalty.

**Comment by vitaly-t** [comment]
@rpedela and how does this work in Node.js?

**Comment by rpedela** [comment]
You configure ```pgbouncer```, have it run as a daemon, and then you make Postgres queries in Node.js like normal without using the pooling code like the example in the README:

```js
var pg = require('pg');

var conString = "postgres://username:password@localhost/database";

var client = new pg.Client(conString);
client.connect(function(err) {
  if(err) {
    return console.error('could not connect to postgres', err);
  }
  client.query('SELECT NOW() AS "theTime"', function(err, result) {
    if(err) {
      return console.error('error running query', err);
    }
    console.log(result.rows[0].theTime);
    //output: Tue Jan 15 2013 19:12:47 GMT-600 (CST)
    client.end();
  });
});
```

**Comment by vitaly-t** [comment]
Does this mean that we an use it through the pooling also? I understand it would be more like double-pooling, but it would make this thing compatible with how most people use this library - through the connection pool.

**Comment by rpedela** [comment]
Yes you could double pool or set the Node.js pool size to 1.

**Comment by vitaly-t** [comment]
@rpedela Now with version 4.5.3 we have isolated Native Bindings from JavaScript Bindings, which includes the pool instances.

So, if you only have 2 databases, then you can have one database use Native Bindings, and another one - JavaScript bindings. This will give you two separate pools.

It is a little nasty, but quite functional work-around for you ;)

**Comment by alekbarszczewski** [comment]
Hey I think I found solution - instead of passing connection string to `pg.connect` it is possible to pass connection config as object (described in docs). However inside config it is possible to pass all pool options (which is not described in docs).

For example:

```js
var pg = require('pg')

pg.connect({
  host: 'localhost',
  database: 'db1',
  poolSize: 10
}, function (err, client, done) {
  done()
  pg.connect({
    host: 'localhost',
    database: 'db2',
    poolSize: 20
  }, function (err, client, done) {
    done()
    console.log(Object.keys(pg.pools.all)) // Two pools with different sizes
  })
})

// output:
// [ '{"host":"localhost","database":"db1","poolSize":10}',
//  '{"host":"localhost","database":"db2","poolSize":20}' ]
```

In code above first `pg.connect()` will use one pool and second one another one.
This means it is possible to get two pools of connections to different databases, but also two different pools of connections to same database.

**Comment by vitaly-t** [comment]
>In code above first pg.connect() will use one pool and second one another one.

Are you sure about that? I'm not. I believe they use one shared pool.

**Comment by alekbarszczewski** [comment]
I did not test it, but `pg.connect` calls `pools.getOrCreate()` internally, and this method (`pools.getOrCreate()`) returns two different instances of `Pool`. I am pretty sure it means that they are separate pools with completely different configs.

**Comment by vitaly-t** [comment]
I have looked at the code, and I can see it creates a new pool for every new connection detail, regardless of whether it is a configuration object or a connection string.

**Comment by brianc** [comment]
I've deprecated the singleton opaque pool factory in favor of manually creating and managing your own pool instances in your app: https://github.com/brianc/node-pg-pool

**Comment by PaulKushch** [comment]
@brianc Hi, any updates on this issue? I use serverless and pgbouncer. What is the correct way now days to use node-postgres library with such a set up? Also is it possible to execute multiple queries in the same statement? 
Great library btw!
Best Regards

**Comment by brianc** [comment]
if you want two pools it's pretty straight forward:

```js
const pool1 = new pg.Pool({ database: 'database1' })
const pool2 = new pg.Pool({ database: database2' })
```

Up to you in your app to decide which pool to use.

As far as serverless + pgbouncer...it should work though I don't run pgbouncer myself in production.



> Also is it possible to execute multiple queries in the same statement?

You can only run multiple queries in a single statement if you do __not__ use parameters.  This is a postgres protocol restriction & there's no working around it.  99% of the time just do multiple statements w/ `async/await`

```
const res1 = await pool.query('SELECT 1')
const res2 = await pool.query('SELECT 2')
```

If you absolutely need to execute multiple statements in the same query, don't use parameters:
```
const res = await pool.query('SELECT 1; SELECT 2;).
```
