### ISSUE TITLE
Using parameters on array function queries.

### ISSUE THREAD

**Issue by ChaseKeeling** [brianc/node-postgres#976]
When attempting to use a contains operator (@>) as such:
`client.query('select * from strongholds where owner=$1 or members @> \'{$1}\'', [result.rows[0]['id']], function(err, result) {...});`

it throws the error
> error: invalid input syntax for type numeric: "$1"

I went around it by using a string concatenation, but is there something I may do with the above code to avoid concatenation?

`client.query('select * from strongholds where owner=$1 or members @> \'{' + result.rows[0]["id"] + '}\'', [result.rows[0]['id']], function(err, result) {...});`

**Comment by langpavel** [comment]
@ChaseKeeling Your query is badly written.

It should be possible to write this:
```sql
select * from strongholds where owner=$1 or members @> ARRAY[$1]
```
