### ISSUE TITLE
rollback not sent if an error happens in a transaction

### ISSUE THREAD

**Issue by nodejsbspa** [brianc/node-postgres#977]
Hi!
I have just started working with postgresql so I have no experience. I'm using strongloop's PostgreSQL connector which uses node-postgres. While implementing transactions I found something which is odd to me, the following investigation led me to node-postgres pool.

My steps were:
1) I have activated log_statement = 'all' in order to log every query which is execute on postgre server. 
2) Execute a transaction in which a query has an error in order to make it fails. The purpose was to test the rollback statement.
3) Look at the list of logged queries where I have found that the rollback statement was absent.

My expectations was to see in the log query:

```
BEGIN TRANSACTION
query 1
query 2 #<-- which fails
ROLLBACK
```

instead I saw:

```
BEGIN TRANSACTION
query 1
query 2 #<-- which fails
```

looking in the code I saw that the client which connects to postgre server is [destroyed](https://github.com/brianc/node-postgres/blob/master/lib/pool.js#L84) when there is the error. 

My questions are: 
- why do we need to destroy a client when an error happens?
- is it correct that, during a transaction, when an error occurs, the client is destroyed without sending rollback statement? Do we risk to leave pending transactions on the database?

Thanks!

**Comment by vitaly-t** [comment]
This would be an issue with StrongLoop, not with this library, which only executes queries, it does not pertain to the transaction logic in any way.
