### ISSUE TITLE
Name array type doesn't parse

### ISSUE THREAD

**Issue by calebmer** [brianc/node-postgres#986]
I'm doing reflection on my PostgreSQL database and I have this query:

``` sql
select
  n.nspname as "schemaName",
  t.typname as "name",
  array(
    select
      e.enumlabel
    from
      pg_catalog.pg_enum as e
    where
      e.enumtypid = t.oid
  ) as "variants"
from
  pg_catalog.pg_type as t
  left join pg_catalog.pg_namespace as n on n.oid = t.typnamespace
where
  t.typtype = 'e';
```

Which has a sample result of:

```
 schemaName |    name    |     variants      
------------+------------+-------------------
 public     | bug_status | {new,open,closed}
 a          | letter     | {a,b,c,d}
 b          | color      | {red,green,blue}
(3 rows)
```

I'd expect the `pg` module to parse the `variants` column as an array of strings, but that's not what happens. Instead the `variants` column is the string `{a,b,c,d}` for example.

After some digging the type appears to be named `_name` with an id of 1003, which is an array type for `name` with an oid of 19. For more information:

``` sql
select typname, oid, typarray from pg_type where oid in (1003, 19);
```

**Comment by langpavel** [comment]
I agree. You can fix this by typecasting to text in your nested query for now:
```sql
select e.enumlabel::text
from pg_catalog.pg_enum as e
where e.enumtypid = t.oid
```

**Comment by vitaly-t** [comment]
The same issue? - http://stackoverflow.com/questions/34644522/array-of-type-enum-coming-back-as-string-from-postgres

**Comment by calebmer** [comment]
@vitaly-t not certain, but `vehicle` looks like a custom type, so `vehicle[]` probably wouldn't (and couldn't) be included in [`pg-types`](http://npmjs.org/pg-types) parsing.

**Comment by langpavel** [comment]
There is possibility to detect array types and split every array type to it's parts, however this would need retrieving all array types OIDs. Array splitting is already implemented.

May be some helper function in pg-types?

**Comment by charmander** [comment]
See https://github.com/brianc/node-pg-types/issues/68.
