### ISSUE TITLE
SQL Code single quotes

### ISSUE THREAD

**Issue by ryananderson0219** [brianc/node-postgres#990]
run a query like this:

pg.connect(conString, function(err, client, done) {
  if(err) {
    return console.error('error fetching client from pool', err);
  }
    console.log(email);
   var emailquotes = "'" + email + "'";
   console.log(emailquotes);
   var queryuserid = client.query("SELECT id from users WHERE login = 'someone@somewhere.com'");
   console.log(queryuserid);

When I look at the text it tried to send it loos like this:
text: 'SELECT id from users WHERE login = \'someone@somewhere.com\''

It errors out. How to I send: SELECT id from users WHERE login = 'someone@somewhere.com'

**Comment by langpavel** [comment]
@ryananderson0219 You should run this:
```js
pg.connect(conString, function (err, client, done) {
  if (err) {
    console.error('error fetching client from pool', err);
    return;
  }
  client.query(
    'SELECT id from users WHERE login = $1',
    ['someone@somewhere.com'],
    function (err, result) {
      if (err) {
        console.error('Query error:', err);
        return;
      }
      if (result.rows.length === 1) {
        console.log('ID:', result.rows[0].id);
      } else {
        console.error('Expected ore row but ' + result.rows.length + ' returned');
      }
    }
  );
});
```

Please, RTFM ;-)

**Comment by langpavel** [comment]
BTW you can use my library ['pg-async'](http://langpavel.github.io/node-pg-async/) if you use babel

**Comment by ryananderson0219** [comment]
Thank you so much! I don't know why I couldn't understand that. I was trying to make it more complicated than it is. It's simple know that I think about it.

**Comment by langpavel** [comment]
@ryananderson0219 Hey, I make mistake in first example. You should call `done()` when you are done with connection :-) This is not needed in `pg-async` so I forgot it. I edited my first example so it will not leaking resources..

**Comment by NumminorihSF** [comment]
@langpavel, you also need to call `done()` on `client.query()`'s error (or pool will leak), and `return` there (without `return` it will crash).

**Comment by langpavel** [comment]
@NumminorihSF Thanks, I don't need `done()` with `pg-async` :-)
