### ISSUE TITLE
How to display real executed SQL on error?

### ISSUE THREAD

**Issue by elfet** [brianc/node-postgres#994]
Hi,

How to display real executed SQL on error? Not just `error: invalid input syntax for type json`, but full executed query with inserted params in it.

Is it possible?

**Comment by vitaly-t** [comment]
[pg-promise](https://github.com/vitaly-t/pg-promise) makes it possible. Event [error](http://vitaly-t.github.io/pg-promise/global.html#event:error) contains all the details available, including the query that's executed.

**Comment by elfet** [comment]
I’m not using pg-promise. I’m using `pg`. Hot to do it here? Without switching to another lib?

**Comment by vitaly-t** [comment]
@elfet I have answered that above. You can't do it with this library. By the way, pg-promise builds on top of pg, it doesn't replace it.

**Comment by vitaly-t** [comment]
@elfet If this answers your question, then please close the issue ;)

**Comment by elfet** [comment]
So, answer is it impossible?

**Comment by vitaly-t** [comment]
@elfet yes, correct. This library doesn't keep the query information when an error occurs.

**Comment by elfet** [comment]
Maybe it's better to implement such feature? PR?
