### ISSUE TITLE
Errors are a bit unhelpful

### ISSUE THREAD

**Issue by ricardograca** [brianc/node-postgres#995]
So, currently when there is an error it's usually like this:

```js
{ [error: value too long for type character varying(128)]
  name: 'error',
  length: 92,
  severity: 'ERROR',
  code: '22001',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'varchar.c',
  line: '623',
  routine: 'varchar' }
```

The problem is that the `internalQuery` and `internalPosition` values are always `undefined`, so how am I supposed to know what value and what column is triggering the error? Is there a way to have the query and the position show up in there?

I would also argue that the `length`, `file`, `line` and `routine` values are totally useless and just add noise, but maybe they are helpful to someone? (PS: I know they are automatically added from the error that postgresql outputs)

**Comment by vitaly-t** [comment]
Have you tried this? - #978

Other than that, this is what PostgreSQL provides, not this library, so it is not really a related issue.

**Comment by ricardograca** [comment]
I did some research in the mean time and found that, according to the [official documentation](http://www.postgresql.org/docs/9.4/static/errcodes-appendix.html):

> For some types of errors, the server reports the name of a database object (a table, table column, data type, or constraint) associated with the error; for example, the name of the unique constraint that caused a unique_violation error. (...) As of PostgreSQL 9.3, complete coverage for this feature exists only for errors in SQLSTATE class 23 (integrity constraint violation), but this is likely to be expanded in future.

So, error reporting from the base PostgreSQL server is a bit lacking currently. I wonder how ActiveRecord does it then.

I'll try the feature that is mentioned in that linked issue, which this one is a duplicate of.

Thanks for the help.
