### ISSUE TITLE
error: invalid input syntax for integer: "123.456"

### ISSUE THREAD

**Issue by devTristan** [brianc/node-postgres#996]
numeric arguments in prepared statements are sent to postgres as [strings](https://github.com/brianc/node-postgres/blob/fe6f32a6e7e62b276cda100e2a82af755500bb42/lib/utils.js#L51). I'm not sure why this is important, but it causes the following case to fail:

```js
client.query('SELECT * FROM numbers WHERE n > $1', [123.456])
```

where `numbers.n` is of type `int`, `bigint`, etc. Since `123.456` is sent as a string, postgres interprets this like `WHERE n > '123.456'::int` which fails with the following error:

```
error: invalid input syntax for integer: "123.456"
```

Preparing the query manually, as follows, works without a hitch:

```js
client.query('SELECT * FROM numbers WHERE n > 123.456')
```

A test case is incoming.

**Comment by vitaly-t** [comment]
Use `SELECT * FROM numbers WHERE n > $1::decimal` in the query, and you will be fine.

**Comment by joskuijpers** [comment]
What vitaly set. Also, an integer does not have a decimal value. An integer is a whole value, like 1 or 123.

Sidenote: I _always_ use the `::type` on input values to have some error checking.

@brianc Also not a pg problem. Never had any troubles myself.

**Comment by brianc** [comment]
:godmode:
