### ISSUE TITLE
native with import with transpiling

### ISSUE THREAD

**Issue by Brakkar** [brianc/node-postgres#999]
Hi, what's the proper way to convert var pg  = require('pg').native to import.
Using import * as pge from "pg" I found no way to specify .native so it gets correctly transpiled.

What is the best way to do it ?

**Comment by vitaly-t** [comment]
I believe you've got your answer - http://stackoverflow.com/questions/36867736/convert-pg-postgress-node-module-native-from-require-to-import

;)

**Comment by vitaly-t** [comment]
@Brakkar can you close the issue now, please?
